### ISSUE TITLE
Feature Request: Distraction-Free Mode

### ISSUE THREAD

**Issue by sahil48** [Zettlr/Zettlr#10]
A Distraction-free mode would keep the focus on the editor and hide other unnecessary UI elements until you exit the mode. User could select to dim text not in the same sentence or paragraph as the cursor is currently on while this mode is active.

**Comment by nathanlesage** [comment]
I know what you mean. As distraction-free I've until now simply hidden the directory and file lists (Cmd/Ctrl+1 and Cmd/Ctrl+2) and increased the editor's font size, so that you still had the toolbar buttons ready at hand. But yes, I fear that I've forgotten to document this, the docs are somewhat outdated because I was mainly busy developing the app recently.

Concerning the text dimming etc., I also thought to maybe implement a type writer mode that keeps the current line in the center (such as if you were writing with an old typewriter), so this would definitely be a good addendum!
