### ISSUE TITLE
Bibtex "citation database could not be loaded"

### ISSUE THREAD

**Issue by mojohealy** [Zettlr/Zettlr#1002]
## Description
Zettlr will not load my bibtex files, either from Jabref or betterbibtex exported from Zotero. I get an error message: "citation database could not be loaded". CSL JSON file from Zotero works as expected. 

## Reproducing
Any attempt to load bibtex files from Jabref or Zotero export in export tab of settings. 

## Platform
 - OS and version: Windows 10 1803
 - Zettlr Version: 1.7.0
 - Screen Resolution: 1920 X 1080

## Additional information
Zettlr logs show: "[Error] [citeproc] Expected "#", "%", ",", [\r\n], [_:a-zA-Z0-9\-], or [})] but "@" found."
The same bibtex files work fine when converting with pandoc from the command line.

**Comment by nathanlesage** [comment]
> Zettlr logs show: "[Error] [citeproc] Expected "#", "%", ",", [\r\n], [_:a-zA-Z0-9-], or [})] but "@" found."

Is there, in the logs, a small arrow on the right side? If so, is there an additional output?

**Comment by mojohealy** [comment]
No, no arrow or additional output. 
[2020-07-05.log](https://github.com/Zettlr/Zettlr/files/4874586/2020-07-05.log)

**Comment by nathanlesage** [comment]
Yeah the additional output is only visible in the log viewer (enable by activating debug mode in Advanced preferences)

**Comment by mojohealy** [comment]
Got it. 
![image](https://user-images.githubusercontent.com/39457654/86532383-db6ba880-bf0c-11ea-8baa-909d9b442e14.png)

However I can't see any problem with the reference at that location. 

![image](https://user-images.githubusercontent.com/39457654/86532409-0ce47400-bf0d-11ea-82e9-19f7e027ed2d.png)

**Comment by nathanlesage** [comment]
Hmm … I'm pretty sure IF there is any error in your file, it's in the previous reference. In any case, the error pertains to the Astrocite-library we use to parse BibTex-files, so maybe it's an issue with these guys? If you have any time, feel free to browser their issue list as well to see if this is something others also experience --> https://github.com/dsifford/astrocite

**Comment by martinlabaj** [comment]
I have the same problem with Bibtex library, it reports "citation database could not be loaded"

**Comment by vtcarlino** [comment]
I have a similar problem since I updated to v1.8.7 (macOS 10.15.7). Each time I add a reference to my JSON file, I get this error: "[Citeproc Provider] Could not parse library file: Unexpected end of JSON input". The JSON file seems to be parsed, as I can cite newly added references despite the error. 

The bibfile ends with a closing square bracket. I've been using the same Better CSL JSON file automatically generated and updated with Zotero/BetterBibTex.

**Comment by areographe** [comment]
Hey, I've just recently started getting this error with Zettlr 1.8.7 and Zotero 5.0.95 with Better BibTex 5.2.117. Prior to a month ago I had no errors, but now I regularly get a "The citation database could not be loaded: unexpected end of JSON input" error on every reload due to a changed reference in Zotero. However, all the references in the JSON file are still found/updated in Zettlr, so the citation database *is* still being loaded.

**Comment by nathanlesage** [comment]
Yeah, I'm pretty sure this is because Zettlr is actually a little bit more stable and re-parses the file, but tells you now that there went something wrong the first time. I'm not sure, however, if I can (read: should) suppress this error.
