### ISSUE TITLE
[ENHANCEMENT] More exporting options (Projects+Single File)

### ISSUE THREAD

**Issue by ploum** [Zettlr/Zettlr#1005]
Instead of PDF, I would like to be able to export easily a whole project as an epub.

**Comment by nathanlesage** [comment]
Easy:

Either find three more export formats that Pandoc can handle, so that we have a full row of four new formats, or drop one (which I wouldn't like :()

I would suggest to add latex (merely because it'll help me debug stuff better, so I'm not sure if this would be really useful except for developing :D)

Then, I know that Albert from the Pandoc project wishes to disseminate further knowledge of the JATS-XML format, so maybe we could throw that in. And then … beamer? I don't know … 🤔

Let's ask Twitter! 🎉

**Comment by ploum** [comment]
Are you talking about project? For projects, when I right-click -> export, I immediately have a PDF. I don't have any option. Am I missing something ?

**Comment by nathanlesage** [comment]
No, I'm talking about single-file export (the popup at the top toolbar)

> I don't have any option

You have: Open the project preferences, you have, I think, four formats to choose from

**Comment by ploum** [comment]
Indeed ! That's where the "epub" format would make sense to me (which is good news as it solve the need for others formats). That's what the original intent behind this ticket.

**Comment by nathanlesage** [comment]
Aaaah, so you want to export a *project* to Epub.

Too many issues, and then I tend to accidentally overlook these nuances :D Sorry!

**Comment by nathanlesage** [comment]
(But still, we can add another row of export options to the single-file exports as well, because it costs me like 10 lines of code each to implement)

**Comment by nathanlesage** [comment]
From issue #1030: PPTX export

**Comment by zhangfanfansz** [comment]
Hi, I am Fan Zhang from the University of Adelaide, my team and I are very interested in this issue and happy to contribute to this issue. Are there any suggestions that you can give us to tackle this issue? We may do our first pull in a few weeks.

**Comment by nathanlesage** [comment]
And finally re-implemented!

**Comment by happytodev** [comment]
Hi @nathanlesage , I'm not sure to understand, ePub export is available or not ?
If not what are the steps to enable it or to export single/multiple documents into ePub ?
I didn't found precise steps in documentation.
Sorry for that.

**Comment by nathanlesage** [comment]
There is no epub export yet, feel free to open a request for adding it
