### ISSUE TITLE
[FEATURE] Add option to disable update check at application start

### ISSUE THREAD

**Issue by dessant** [Zettlr/Zettlr#1007]
It would be great to have an option to disable update checks, and avoid making requests on app start. This would be useful for two reasons:

- Privacy: there should be a way to opt out of data collection, even if the collected stats are minimal
- Usability: the update popup needs to be dismissed on every app start

**Comment by nathanlesage** [comment]
> Usability: the update popup needs to be dismissed on every app start

This is exactly the reason why this won't happen. It is _intended_ to be annoying, because I don't want people running on older versions. I have so much on my hands already (please just look at the list of open issues) that I cannot support more than exactly one release. And with the update dialog being able to be turned off, there will be an incredible amount of new issues complaining about bugs that have been solved by newer versions. Simply download the newest version asap.

**Comment by dessant** [comment]
Installing the newest version may not always be *immediately* possible on a managed device, and until the update happens, users are needlessly annoyed.

The privacy aspects of the issue should definitely not be ignored, even if you have a lot on your plate, and the app should respect our wish to not be tracked. The requests you make on app startup reveal our coarse location (based on IP) which is tied to a unique ID, and when we travel, you are pinged with our new location whenever we start the app. Not to mention the activity patterns of a person that can be inferred by these startup requests.

**Comment by nathanlesage** [comment]
> A Not to mention the activity patterns of a person that can be inferred by these startup requests.

If I would save this information, you were surely right, but I don't! But yeah, being more transparent is surely a thing to do. Saving the UUIDs was only a measure for me to get to know how many people use the app, but the UUIDs (UUIDv4) are generated at random, so there is zero personal information saved in them, and I would like to have at least this metric available. So disabling the update check is still not going to happen, but I will make sure to add an opt-in button to the settings.

**Comment by dessant** [comment]
> but I will make sure to add an opt-in button to the settings.

Thanks! Having a way to opt out of update checks and tracking would be wonderful. Would you mind reopening this issue, so that things are not forgotten?

**Comment by nathanlesage** [comment]
As I said: The UPDATE CHECK will never go. The tracking will go.

**Comment by dessant** [comment]
I'm honestly disheartened by your attitude, but sure, it's your project. Just keep in mind that you are working against your goals and you're hurting your project when you dismiss a reasonable suggestion that would solve an annoyance on managed devices or when the app is installed from a third-party package, such as Linux distro repositories, and when the requests you make can affect the user's privacy, even if you promise not to keep the data from now on.

I don't understand why would you refuse to give control over this when update checks would be enabled by default anyway, and I hope you will come to your senses, or you'll talk to someone who is better equipped to explain why your attitude is alarming.

**Comment by nathanlesage** [comment]
> Just keep in mind that you are working against your goals and you're hurting your project when you dismiss a reasonable suggestion that would solve an annoyance on managed devices or when the app is installed from a third-party package, such as Linux distro repositories, and when the requests you make can affect the user's privacy, even if you promise not to keep the data from now on.

Well, the app is directed towards academics, and these people in general do not use managed PCs. So there's not much lost here. I am not, in fact, working against my goals, I am fully working towards them. Please do not misinterpret me here: I do not, in fact, dismiss your suggestion.

And don't forget: Being a German citizen with a German server, I fall under the EU's GDPR, which I fully implement and agree upon. Your data is safer with me than with GitHub, even though I don't even save any personally identifiable information. And please don't be upset: I totally get your point, which is why I will implement it. But you have to agree that update notifications and data issues are two different issues.

Last but not least, I do not need people telling me my attitude is "alarming". If THIS attitude is alarming, please feel free to hate upon 90 % of the world's population.
