### ISSUE TITLE
Externally modified files are badly handled

### ISSUE THREAD

**Issue by ploum** [Zettlr/Zettlr#1015]
Usecase 1:
1. Open a Zettlr folder
2. Create a file from another software 
3. The file does not appear (should be the case)

Use case 2:
1. Open a zettlr folder
2. in a terminal, rename a file in that folder "mv a.md b.md"
3. a.md is still displayed but content cannot be accessed. b.md is not displayed.

This was working well with 1.6

**Comment by davidbosman** [comment]
I have a somewhat similar problem: after I 'mv', a.md is still listed (the file can't be displayed) *but* b.md is listed too and its content can be displayed. 

Zettler 1.7.1, on Manjaro.

**Comment by nathanlesage** [comment]
Just fixed this seconds ago. I never had the opportunities that I have now to thoroughly test the FSAL on a dummy directory.

(For those who are interested, I compared a negative search result in the children-arrays to `null`, instead of `undefined` which the `Array.prototype.find()`-function returns)

Coming in 1.8!
