### ISSUE TITLE
RMarkdown syntax highlighting

### ISSUE THREAD

**Issue by jzelner** [Zettlr/Zettlr#1023]
Hi - I was wondering if there was any possibility of adding R syntax highlighting in RMarkdown code blocks, formatted like so:
![image](https://user-images.githubusercontent.com/136323/86835182-bb9dc700-c069-11ea-8981-2c93b69772ef.png)

I'm loving zettlr for writing papers in markdown/rmarkdown and it would be nice to have highlighting similar to what is available in RStudio within these blocks, i.e. as zettlr currently highlights blocks starting with "```r"

Thanks!

-Jon Zelner

**Comment by nathanlesage** [comment]
How is this case implemented in Pandoc (whose behaviour I'd like to mirror)?

**Comment by petrbouchal** [comment]
@nathanlesage Just to add that this would be useful (and R syntax highlighting already works in normal code blocks). 

Not sure how feasible it would be to get the pandoc part right. In short, pandoc will not process a Rmd file sensibly AFAICT. Currently, in R Rmd files are processed by an R package (knitr) which produces a .md file with the text + either the output of the code in the chunks starting ` ```{r} ` or both the code and the output. The sensible approach here would be to just turn these chunks into regular code blocks (` ```r `) before passing to pandoc, while omitting from the output the params often contained in the ` ```{r} ` chunk header. Not sure how hard/in line with your approach that would be.

**Comment by david-blackwell** [comment]
@jzelner I've created a fork of 1.8.9 here (https://github.com/david-blackwell/Zettlr) that supports syntax highlighting for r code blocks that follow the pattern` ```{r} ``` ` (I've also added the ability to fully fold up entire code blocks, instead of just sections of the code, as that was useful to my workflow.)
I haven't implemented any of this for the current version 2.0 dev channel as there are too many breaking changes for my workflow there at the moment)

@nathanlesage In regards to Pandoc, when exporting the file it just treats the whole section as plain text (so the ` ```{r .. ` etc. is included in the output), but does not break normal r code blocks that follow the standard pattern of ` ```r `. As the ` ```{r ` chunks would need to be knited separately anyway, this seems like a reasonable compromise.
If there is interest I can look at updating these changes to the 2.0 dev version.

**Comment by nathanlesage** [comment]
@david-blackwell Interesting choice to add `{r` as a selector. But I guess what works works :shrug:

I just checked the CommonMark specs, in there they only show alphanumerical characters. But Pandoc does support more attributes by adding these in curly brackets, and as far as the specification goes this should be valid CommonMark. So I'm curious whether we should allow this in general (not just for Markdown) – example:

Not just \`\`\`info-string but also \`\`\`{info-string}

@david-blackwell If you feel up to it, feel free to try to add this general rule ([see also the Pandoc manual on this](https://pandoc.org/MANUAL.html#extension-fenced_code_attributes)) and open a PR against the 2.0 dev branch.

You can implement it on your 1.8.9 fork and, if it works there, it should work in 2.0.0 as well, since I haven't changed the multiplexer in between (and don't intend to).

@tarleb what is your take on possible incompatibilities between R's knitting with Pandoc and Pandoc itself?

**Comment by tarleb** [comment]
> @tarleb what is your take on possible incompatibilities between R's knitting with Pandoc and Pandoc itself?

Nothing to worry about, really. Treating `{r}` just like `r` for syntax
highlighting is reasonable IMHO.

**Comment by nathanlesage** [comment]
> Nothing to worry about, really. Treating `{r}` just like `r` for syntax highlighting is reasonable IMHO.

Thank you!

**Comment by david-blackwell** [comment]
@nathanlesage I have a generalised version that works on both 1.8.9 and the 2.0.0 (the changes have been pushed to my 1.8.9 fork).
This was done by editing the RegExg command in multiplex.js to also search for ` ```{ `
I don't know how much of an issue it is, but the auto-completion of the code blocks is slightly odd when the setting 'Automatically close matching character pairs' is enabled. Hitting return after selecting the coding language results in:

    ```{r
    ```}

If this isn't a major issue, I'll open a PR against the 2.0 dev branch, or if you can point me in the general direction of where in the code I can possibly fix this, I'll happily give it a shot.

**Comment by nathanlesage** [comment]
> Hitting return after selecting the coding language results in:

It does look interesting, you've gonna give it to the code :D

> or if you can point me in the general direction of where in the code I can possibly fix

I'd say the possibly most straightforward way would be in the `autocomplete.js` of the editor. There you can basically listen for these changes and just remove whatever you don't need. I have commented the "after autocompletion" hook pretty much.

**Comment by david-blackwell** [comment]
I've pushed an update to my 1.8.9 branch that fixes the issues I was having before (as well as another I came across in working through it). If these look good to you I'll update them for the 2.0 dev branch and then open a PR.
