### ISSUE TITLE
Improve tags from YAML-frontmatter

### ISSUE THREAD

**Issue by lsolesen** [Zettlr/Zettlr#1024]
## Description

In https://github.com/Zettlr/Zettlr/commit/490ccd6099522b8f93607b9679ca4824fa3ff84b YAML-frontmatter support was added. Things in the keywords arrray would be added to the 'tags' feature of Zettlr. However, the Jekyll theme I am using relies on 'tags' and 'category'. Could it be made configurable which array from the YAML-frontmatter which goes into the 'tags'?

Also I am wondering why tags from a non-open folder is still part of the tags cloud. Is that intentional (right now the tag cloud only consists of tags from the Zettlr docs and one tag, I have added to my new open folder with documents.

**Comment by nathanlesage** [comment]
> Also I am wondering why tags from a non-open folder is still part of the tags cloud.

Not intentional, these need to be taken off, yes (after a restart, however, these tags will be gone for sure)

**Comment by indirection** [comment]
Very nice project! 

I know you're working on improving "YAML Frontmatter", tagging, etc. 

The approach using YAML Frontmatter isn't aligned with common Markdown _"rules to encourage standards and consistency for Markdown files"_ as noted in one of the most popular Markdown Linters (https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint)

Here are three examples to help illustrate the issue. I love Markdown because I can edit with nearly any tool and it looks like Zettlr may become a favorite. 

### 1. File that comes with Zettlr (thank you):
<img width="2048" alt="Screen Shot 2021-04-24 at 11 27 42 AM" src="https://user-images.githubusercontent.com/398047/115963994-34ceb380-a4f0-11eb-82c7-3d95649a5a2e.png">

### 2. Using a linter to 'format and clean up' markdown code:
We can see that this breaks Zettlr tagging and removes YAML formatting. 

<img width="2048" alt="Screen Shot 2021-04-24 at 11 32 00 AM" src="https://user-images.githubusercontent.com/398047/115964081-b3c3ec00-a4f0-11eb-9773-44987e22e4c9.png">

### 3. Using a `code block` to retain YAML formatting:
We can see this breaks Zettlr tagging.

<img width="2048" alt="Screen Shot 2021-04-24 at 11 37 59 AM" src="https://user-images.githubusercontent.com/398047/115964250-89bef980-a4f1-11eb-9daa-0c4ca5e330b7.png">

**Comment by nathanlesage** [comment]
@indirection The reason is that the default Zettlr files contain YAML frontmatters delimited by `---` at the top and `...` at the bottom. That is the reason since that was how Pandoc also supports frontmatters.

That being said, most apps and frameworks (e.g. Jeckyll, Hugo) delimit frontmatters by `---` on top as well as on bottom. So, if you exchange the three dots with three hyphens, the frontmatter should display correctly in all apps.

While being at it, it might seem that we might safely exchange the `...` with `---` in all tutorial files, since both Zettlr and Pandoc support the latter one as well, and this would increase the cross-compatibility.

So, if you want an easy PR and become a contributor, go for it: https://github.com/Zettlr/Zettlr/tree/develop/source/main/assets/tutorial
