### ISSUE TITLE
[FEATURE] Allow all file names that is legal on Unix systems

### ISSUE THREAD

**Issue by inquisitiv3** [Zettlr/Zettlr#1033]
## Description

I would like to be able to create files with file names with all characters that's allowed on Unix systems. Most Unix file systems support "any 8-bit set" minus `/` and `NULL`[0].

## Example Workflow

1. Go to Settings --> Advanced --> Enable the option "Allow more different characters in file names"
2. Create file with the file name "Zettlr: Hello, World!.md" that also gets that exact file name.

## Caveats

This would enable the user to create files that is not compatible with NTFS (the file system on Windows).

The option "Allow more different characters in file names" should have a warning message that says that this enable the user to create files that can't be opened on regular Windows computers (should be able to open them on WSL). The option maybe even should be disabled on Windows systems.

## Additional Information

I know that I can avoid using colons in my file names but still use them in file headers, but I don't like to do that. I'm currently creating the files manually using the command line and edit them in Zettlr. But that work flow is cumbersome and take extra time and is frustrating.

## References

[0] https://en.wikipedia.org/wiki/Filename#Comparison_of_filename_limitations

**Comment by inquisitiv3** [comment]
Okey, this maybe should have been an enhancement request when I think about it (I was unsure what to chose when creating the issue). I can edit the OP if you want.

**Comment by nathanlesage** [comment]
Mh, I have stomach aching with this request, as this might open the gate for many users to attempt to do that (because "more freedom!") and then opening bug requests here because their filenames are not recognized … I'd like to discuss that first. Use-cases where I think this could be a problem:

- A user uses Linux at home, activates that option, but complains that their cloud service won't synchronize their files
- A user uses Windows, sees this option, and then wants it implemented on Windows as well
- A user on Linux creates a file having this option turned on, sends it to a colleague on Windows, colleague complains that they can't open the file

The idea to _not_ enable more platform-specifics in this regard was to maintain compatibility, because restricting the uses of certain characters makes the app much more maintainable. Plus: You already have a workflow that allows you to circumvent this!

I'm sorry if sounds disappointing, but I always have to keep in mind users :S

**Comment by inquisitiv3** [comment]
I understand your concerns! I've changed my workflow, so I no longer need this feature, nor use a workaround.
