### ISSUE TITLE
Copying title text from OneNote treats text as image

### ISSUE THREAD

**Issue by canpolat** [Zettlr/Zettlr#1058]
## Description
When copying a page title from OneNote, Zettlr treats text as image and tries to paste it using the image insert dialog.

This may be due to OneNote doing something wrong with their handling of page titles, but at least Notepad++ seems to handle it correctly. (possibly related to rendering HTML input?)

## Reproducing
- Create a new page in OneNote and add a title
- Copy the title of the page
- Paste copied text into Zettlr
- Observe that Zettlr treats the pasted data as image

## Expected behaviour
Zettlr should paste the data as plain text (or possible a heading if the data contains that sort of information)

**Screenshots**
![2020-07-12_22-49-49](https://user-images.githubusercontent.com/459891/87256431-d8376600-c492-11ea-8bc8-24a01f06d0cc.gif)
Nevermind the location of the mouse cursor in the screencast, the program I use places it wrong, for some reason.

## Platform
 - OS and version: Windows 10 1903
 - Zettlr Version: 1.7.1
 - Screen Resolution: 1920 x 1080

**Comment by nathanlesage** [comment]
Yes, this is related to MS Office stuff, as Word, Excel, and OneNote apparently too push the following content to the clipboard if you copy something:

- **Plain Text Clipboard**: The text without any formatting
- **HTML Text Clipboard**: The text with HTML formatting
- **The RTF Text Clipboard**: The text with RTF formatting
- **The Image Clipboard**: A screenshot of that goddamn text for no reason at all

To circumvent this, you'd need to paste without formatting, as Zettlr first checks the image clipboard, and, if there is an image in clipboard, it will try to paste this first. This is because sometimes the text clipboard then contains the source link (which can be used as an ALT-text for the image). I have not yet found any heuristic for dealing with this stupid behavior of Office, which clearly runs against every good standard.

**Comment by sheilman16** [comment]
This was very helpful. For OneNote to github, I right clicked and selected "Paste without Formatting" which pasted text instead of image.

**Comment by SN-CH** [comment]
I needed to copy long list of hyperlinks from One note to Zetllr and found the following work around. So I describe it here in case some one has similar problem.

Right-click the title for One note page (or whatever they call it in MS) and select «Export», than save it as a mht-file. Open the file in MS Edge and copy links from there, they will be transferred nicely.
