### ISSUE TITLE
VIM mode eats Ctlr+P and Ctlr+N shortcuts

### ISSUE THREAD

**Issue by boutil** [Zettlr/Zettlr#1065]
## Description

When the editor is in the VIM mode, some menu shortcuts are intercepted by the VIM mode, and prevent some actions to be executed.

## Reproducing

- Activate VIM mode
- Open and edit a file
- Type `Ctrl+P` to try to preview the document and watch the cursor go one line up
- Type `Ctrl+N` to try to create a new file and watch the cursor go one line down.

## Expected behaviour
- the `Ctrl+P` and `Ctrl+N` shortcut should trigger actions described in the menu
  (remapping them to other shortcuts when the VIM mode is activated is another possibility, but much less desiarable from a consistency point of view).

## Platform
 - OS and version: Debian unstable
 - Zettlr Version: 1.7.1
 - Screen Resolution: 1280x1024

**Comment by boutil** [comment]
I'm adding that this happens in "normal mode".
In "insert mode", the shortcuts Ctrl+N and Ctrl+P work as expected (new file, and preview).

**Comment by ianhi** [comment]
The offending lines of the codemirror vim keymap are here: https://github.com/codemirror/CodeMirror/blob/f5bf57b39816f0e6524a1b7d0212e9f26135ba08/keymap/vim.js#L61-L62

A thing to note is that is expected behavior for vim, although probably not widely known (see this SO https://vi.stackexchange.com/a/4249)

>  In "insert mode", the shortcuts Ctrl+N and Ctrl+P work as expected (new file, and preview).

I think codemirror just doesn't implement this but those also have a meaning in vim in insert mode https://vim.fandom.com/wiki/Any_word_completion

> the Ctrl+P and Ctrl+N shortcut should trigger actions described in the menu

:+1:  I think this makes sense to override these vim commands as these seem somewhat esoteric as vim commands go and they are redundant with other movement commands. Codemirror is already not a perfect implementation of the vim keybindings so breaking some of the less important commands in order to better fit into an interface that isn't a terminal seems very sensible. Also if someone really wants to use `ctrl-N` and `ctrl-P` to navigate up and down then with https://github.com/Zettlr/Zettlr/issues/884 they would be able to regain that functionality.

**Comment by nathanlesage** [comment]
Sounds like a plan to deactivate them for now and have CodeMirror just bubble up the commands to the renderer in order to trigger the menu actions.

**Comment by ianhi** [comment]
@nathanlesage to deactivate I think you need to do something like this:
```javascript
let extraKeys = editor.getOption('extraKeys') || {};
extraKeys['Esc'] = CodeMirror.prototype.leaveInsertMode;
extraKeys['Ctrl-N'] = false;
extraKeys['Ctrl-P'] = false;
editor.setOption('extraKeys', extraKeys);
```
where editor is a codemirror editor instance. I'm also pretty sure you can also set it for all instances of codemirror vim by using `_cm.Vim` instead of `editor`

**Comment by nathanlesage** [comment]
@ianhi Almost, there's the generate keymap-file, which we need to utilize for this!

**Comment by Joelius300** [comment]
Is this change still being considered?

**Comment by Joelius300** [comment]
Another issue, more important than Ctrl + N and Ctrl + P (because those work in insert mode), there's no more shortcut for closing a file, is there? In normal mode, Ctrl + W doesn't do anything it seems and in insert mode it deletes a whole word (like Ctrl + Backspace outside of VIM). It would be nice to have a shortcut that allows closing a file in VIM mode.

**Comment by nathanlesage** [comment]
@Joelius300 Hm, given that the vim mode overrides quite a few shortcuts, it might make sense to discuss all of these issues collectively over on Discord! I don't want to change some things and then break something seemingly unrelated!
