### ISSUE TITLE
Copy ID Not working

### ISSUE THREAD

**Issue by edusantana** [Zettlr/Zettlr#1073]
## Description

Copy ID Not working for me. 

- Or it is not working
- Or how it works needs to be documented #67 

## Reproducing

![copy-id](https://user-images.githubusercontent.com/3603111/87480547-e6f15a80-c603-11ea-9ca8-fd95e399fc1b.gif)

## Platform
 - OS and version: Ubuntu 20.04
 - Zettlr Version: 1.7.1

**Comment by nathanlesage** [comment]
I can see from your screencast that Zettlr does not recognize any IDs in the files (would be visible by the IDs showing up in the second line under the filename). It is clearly not related to the copy ID feature.

This potentially might mean a bug in the ID recognition engine, so I'd like you to first test this out with the standard ID settings (these should work) – if that doesn't work either, this would mean this is a bug. If not, there is a different bug.

**Comment by edusantana** [comment]
![default-id](https://user-images.githubusercontent.com/3603111/87605999-52a0f980-c6d0-11ea-8ded-d869572531ac.gif)

**Comment by edusantana** [comment]
> would be visible by the IDs showing up in the second line under the filename

I don't understand your saying. Can you show it?

**Comment by edusantana** [comment]
Are you talking about this?

![Captura de tela de 2020-07-15 19-30-27](https://user-images.githubusercontent.com/3603111/87606854-66e5f600-c6d2-11ea-98a7-a7080d925c88.png)

I think i'm missing the understanding of IDs. Because I don't see how this is a good thing to have there, since the filename (without `.md`) is also the ID.

**Comment by canpolat** [comment]
@edusantana In your preferences I can see that the "ID regular expression" does not fit the way you name your files (meaning, Zettlr cannot use that regular expression to find the ID from the names of your files). That's why, Zettlr does not show the recognized IDs in some of your files. So, you have a couple of options:

You can change the regular expression to something like `(\d{4}-\d{2}-\d{2}-\d{6})`. This will fit the pattern in 'Pattern used to generate new IDs" and therefore will recognize files that have a file name like `2020-06-25-093821.md`. But it will not recognize a filename that looks like `20200625093821.md`. It looks like you have both of these. It is probably a good idea to have a single naming pattern for all files, but if you don't want to rename your files and support both of these scenarios, you can use a regeular expression like this: `\d{4}-?\d{2}-?\d{2}-?\d{6}` This should cover both scenarios. (But I recommend renaming your files to use either one of the naming patterns. The "Test your ID generation" button can be used to test if your regular expression fits your naming pattern.)

**Comment by edusantana** [comment]
Thanks @canpolat I understand the Regular expression to identify keys **now**.

What I do not understand is:

- why do we need keys?
- what the difference between keys and file names?
- where and how the key is defined? is the key defined from filename of file content?
- when to use keys and when to use filenames?
- how can we use keys with auto complete?


![trying-keys](https://user-images.githubusercontent.com/3603111/87851369-7467cf80-c8ce-11ea-9729-3270a0e92076.gif)

Here are my files:

![Captura de tela de 2020-07-18 08-01-30](https://user-images.githubusercontent.com/3603111/87851466-6c5c5f80-c8cf-11ea-9a51-5df6facdc805.png)

- Why `Tenepes.md` has the id `20200717213134`? Here's it content:

```markdown
20200717213134

# Tenepes

```

- Why `Proéxis.md` has the id `20200717211143`?

```markdown
[[Proéxis]] Proéxis [[pesquisa]]
- [[vida]]

# Pesquisa

# Perguntas da pesquisa
- Como é um suporte técnico amparador?
- Quais minhas condições iniciais como aspirante a técnico amparador? [[2020-07-15-161028]]

Ok 20200717211143 nice.

20200717211918.
```

- How to reference the `20200718080454` note? The `Trying to understand keys on Zettlr`? (from the first image)

- How to best use the auto complete feature? With keys or filenames?

**Comment by canpolat** [comment]
@edusantana here is what I know:

> why do we need keys?

I will refer to them as IDs (as that's the way they have been documented in the documentation). IDs are useful for those who use the Zettelkasten method in their workflows. I suppose you could look into Zettlkasten and see how they are being used. Most people use them for linking notes together ([internal linking](https://docs.zettlr.com/en/academic/zkn-method/#internal-linking)) But, generally speaking, you don't have to have IDs. You can use Zettlr without the IDs.

> what the difference between keys and file names?

They are two different things. A filename does not have to have an ID in it. Using an ID in the file name is the way for some people (again, Zettelkasten). You don't have to follow them. You can set your own way of naming your files. And if you want to still use IDs in your files (despite the filename not containing one, you can do so by inserting it in the file). See [The ID Regex](https://docs.zettlr.com/en/reference/settings/#the-id-regex) section in the documentation for more info. 

> where and how the key is defined? is the key defined from filename of file content?

You can do it either in the filename or in the content. If the filename does not match the ID Regex, then Zettlr will look for it in the content and will pick the first matching string. See [The ID Regex](https://docs.zettlr.com/en/reference/settings/#the-id-regex) section in the documentation for more info. 

> when to use keys and when to use filenames?

Well, you HAVE TO have a file name. And you can define whether to put the ID in the filename, in the contents of the file or not use it at all.

> how can we use keys with auto complete?

I don't understand this question, but your first screenshot shows IDs when you open an internal link.

> Why Tenepes.md has the id 20200717213134? Here's it content:

If the filename does not match the ID pattern, Zettlr will look for it in the content and will pick the first matching string. That's why it gets that ID. See [The ID Regex](https://docs.zettlr.com/en/reference/settings/#the-id-regex) section in the documentation for more info. 

> Why Proéxis.md has the id 20200717211143?

Same as above. It's the first string in the file that matches the Regex. If you want to use IDs and not put them in the file name, it is recommended to insert them towards the beginning of the file to avoid confusion.

> How to reference the 20200718080454 note? The Trying to understand keys on Zettlr? (from the first image)

You can use internal links to reference notes. See [internal linking](https://docs.zettlr.com/en/academic/zkn-method/#internal-linking) for more info.

> How to best use the auto complete feature? With keys or filenames?

This depends on your workflow. I think most people use IDs since they don't change very often (filenames may be modified to reflect the contents of the file and this may break the links).

I hope this addresses some of your questions.
