### ISSUE TITLE
Feature Request: Shell code annotation

### ISSUE THREAD

**Issue by aroumeliotis** [Zettlr/Zettlr#108]
Hi! Just started using zettlr and was wondering if there are any plans  to include shell code annotation

**Comment by nathanlesage** [comment]
Shell code annotation? You mean syntax highlighting for shell code? If so, it's integrated within five minutes.

**Comment by aroumeliotis** [comment]
yes! that's what I meant :)

**Comment by nathanlesage** [comment]
Here you go! Possible are both the keyword `shell` and `bash` (because I saw that highlight.js seems to differ between the two, so exported Markdown on CMS or Blog pages won't break)

![image](https://user-images.githubusercontent.com/17251683/53412015-745cec00-39c8-11e9-9f44-dee64421cad5.png)

![image](https://user-images.githubusercontent.com/17251683/53412030-7c1c9080-39c8-11e9-9746-43b2d4a31e97.png)
