### ISSUE TITLE
Make it easier to test unreleased snapshots

### ISSUE THREAD

**Issue by tobiasdiez** [Zettlr/Zettlr#1089]
It would be good to give users the possibility to test the current development version (the compiled version of the `develop` branch). This makes it easier for users to test if a bug is indeed fixed / the new feature works indeed as expected, giving shorter feedback loops.

As a good start (that might already be sufficient), we could run the build workflow also on the develop branch and then point users to the recent build, where the artifacts can then be downloaded, similar to https://github.com/Zettlr/Zettlr/actions/runs/158253182

**Comment by nathanlesage** [comment]
I think those artifacts are only available to people with elevated privileges, if I remember correctly …? But nevertheless: Great idea to offer nightlies!

**Comment by ianhi** [comment]
> I think those artifacts are only available to people with elevated privileges, if I remember correctly …

I'm able to access them. Furthuremore I seem to be able to see all of the actions that are run so that shouldn't be an issue.
![image](https://user-images.githubusercontent.com/10111092/87864284-6b114e00-c934-11ea-9045-f71d2d35a02b.png)

**Comment by nathanlesage** [comment]
> I'm able to access them. Furthuremore I seem to be able to see all of the actions that are run so that shouldn't be an issue.

Ahh, fantastic! So all we need to do is basically copy the build workflow as a nightly, run via Cronjob every … week?

I'd say it would make sense to have the CI publish everything from develop on every Friday (so that people have the weekend to test out and play around).

Any other suggestions? If not, I'll just do this in the evening (I mean we can adjust the workflow later on either way)

**Comment by tobiasdiez** [comment]
You could also run it automatically after each push to develop. Then people can play whenever they want with it, and after fixing a bug you put something like "This is now fixed, please try from ..." and get immediate feedback.

**Comment by nathanlesage** [comment]
> You could also run it automatically after each push to develop.

Mh, I don't want to build it after _every_ push, but rather a *little bit* more condensed, as this way we can test also interrelations and stuff. Plus I fear that everything's getting too polluted this way. Plus we could actually release nightlys once we've improved on the whole process, so that it's a little bit more convenient. Or am I missing something here?

**Comment by tobiasdiez** [comment]
I don't see any problems with "building on every push" as in the end its github's server which is polluted ;-)
But it shouldn't matter that much, and can be easily changed by modifying the "on" statement in the action from a schedule to "push".

**Comment by nathanlesage** [comment]
Perfect, then I'd say let's first start with every week, and if this is too slow, every push!

**Comment by nathanlesage** [comment]
Sometimes it helps to scroll through old issues: Since we now have nightlies, the issue is resolved!
