### ISSUE TITLE
Vim Keybinding - Weird visual block behavior

### ISSUE THREAD

**Issue by rafedramzi** [Zettlr/Zettlr#1098]
## Description
So i have this problem when using visual block (ctrl+v) in zettlr with vim-keybidning,

Issues:
1. Can only select at most 2 lines
2. If i write to 1 line and escape, the edit doesn't applied to the other line
3. If I select vertically 2 times then horizontal 1 times it clears the vertical selection

## Reproducing

Issue 1:
ctrl+v j j

issue 2:
ctrl+v j I blah Esc

issue 3:
ctrl+v j l

## Expected behaviour

issue 1:
expected 3 lines selected, actual 2 lines selected

issue 2:
expected changes applied to 2 lines, but ony applied to 1 line

issue 3:
expected 2 by 2 block, actual 1 by 2 block, and the block starts from the 2nd line instead of the first line

**Screenshots**

## Platform
 - OS and version:
❯ uname -a
Linux hostname 5.7.8-zen2-1-zen #1 ZEN SMP PREEMPT Fri, 10 Jul 2020 14:47:51 +0000 x86_64 GNU/Linux
 - Zettlr Version: 1.7.1
 - Screen Resolution: 1920x1080 ( doesn't matter)

## Additional information

がんばって :fire:

**Comment by nathanlesage** [comment]
Heya, thanks for reporting! Unfortunately, I am not at all adept at vim, so I'll label it so that maybe someone might have a look at what's happening!

**Comment by ianhi** [comment]
@nathanlesage feel free to @ me on any vim issues. I can't guarantee I'll be able to help but I do have a decent understanding of codemirror vim from the jupyterlab world. 

@rafedramzi these are all good catches and thank you for the clear key combinations for reproduction. 

**Issue 1:** 
I can confirm this issue and that  it is specific to zettlr as it does not work on the codemirror vim [demo](https://codemirror.net/demo/vim.html)
In zettlr:
![ctrl-v](https://user-images.githubusercontent.com/10111092/88563419-f60eda00-cfff-11ea-87bf-3ccd6e5046bf.gif)
on https://codemirror.net/demo/vim.html
![crtl-v-demo](https://user-images.githubusercontent.com/10111092/88563505-0de65e00-d000-11ea-9e54-5c875eb1c75a.gif)

**Issue 2:**
This is partially a limitation of codemirror. Your example doesn't work on the codemirror demo either. However on the demo if you make a vertical selection with crtl-V and then use `shift-i` you can modify multiple lines:
![multi-line-demo](https://user-images.githubusercontent.com/10111092/88563918-936a0e00-d000-11ea-97a9-4b7c13b4b980.gif)

however this does not work in zettlr

**Issue 3:**
Yup I find the same. I think this is unique to zettlr 
![horizontal-select-zettlr](https://user-images.githubusercontent.com/10111092/88564109-ce6c4180-d000-11ea-9dcf-0b4b6a45d5ed.gif)
vs 
![horiz-demo](https://user-images.githubusercontent.com/10111092/88564121-d330f580-d000-11ea-9ecb-1e2981021fdc.gif)


All these issues likely share a root cause though I don't really know what that is. @nathanlesage does zettlr modify how codemirror keeps track of lines?

**Comment by ianhi** [comment]
Confusingly both visual selection (`v`) and visual line selection (`shift-v`) behave as expected
