### ISSUE TITLE
[ENHANCEMENT] Performance on directories with many files is lacking

### ISSUE THREAD

**Issue by tsbertalan** [Zettlr/Zettlr#1100]
## Description
One of the downsides to many personal-knowledgebase tools (Evernote, Roam, OneNote, Google Keep) is their insistence that you keep your data in their silo. Zettlr (and its corporate cousin Obsidian) seem to have the *potential* to avoid this pitfall, since they require only that you point them at a base directory, and they'll crawl that directory for files they understand.

However, in practice, Zettlr seems to expect that you'll have one folder for all your notes, and nothing extraneous. I would like to tell Zettlr to just open `~/Dropbox`, wait a minute or two (maybe, really I don't want this either), and then get instant completions for wiki-links to any existing markdown files.

To give a sense of scale, I have about half a million files in my Dropbox (per `find ~/Dropbox -type f | wc`), and about three thousand markdown files (`find ~/Dropbox -type f -iname "*.md" | wc`).

As it stands right now, I can tell Zettler to open that file, and in 70 seconds or so (40 on later starts), it will emit a `Loaded directory` in the terminal where it's running and I can browse to and open individual markdown files in the directory tree, but the list of completions for `[[X` does not contain some files I know to be present.

## Proposed Changes
I'm not sure what sort of performance improvements need to be made, but the above `find` commands only take a few minutes on first run, and less than a second on later runs. It's possible Zettlr is doing too much work to index other files (PDFs and things).

## Caveats
For the most part, it's hard to see how pure performance improvements would ever hurt other features. But, if it turns out that some of things Zettr currently does are just too expensive to do at scale (not having profiled the program or used these features, I don't know what these are), there might need to be UI adjustments there, such lazy-loading of some features.

## Additional Information
I'm testing Zettlr on a i7-4770K desktop with 32G of RAM. My Dropbox directory is on a 5400RPM Western Digital WD40EZRZ drive formatted with ext4. I'm using Ubuntu 18.04, and I have Zettlr version 1.7.1.

**Comment by nathanlesage** [comment]
> (maybe, really I don't want this either)

I don't think you want this :D 

Concerning performance: Yeah, I mean we should be grateful that it can load such directories AT ALL, because a few months back I'd be unsurprised if Zettlr simply showed you the middle finger attempting this.

I always try to do as less indexing as possible, but there are certainly ways to improve upon the performance, that is for sure!

**Comment by tsbertalan** [comment]
Yeah, I saw that the 1.7 release notes that you made some major overhaul to the FASL, so I know it's on track for this. I think my situation is not actually as dire as it might seem, since there are only between 400 and 2500 markdown files (the smaller number after I remove one `node_modules` directory--it would be good to be able to "`.zettlrignore`" some directories or files).

However, I find that there are in fact 15000 PDFs in that directory tree, which might be an issue. Probably it would take some very deliberate architecture choices to handle this (like a pool of file workers that do tasks like watching for file changes in the background, so things like autocompleting potential wikilinks isn't blocked; I see only one zettlr process with one child thread in htop).

I see also that you have some decent contribution instructions; I might try forking and seeing if I can offer any more useful suggestions than just "make it better". But I'm a novice in Javascript, let alone the desktop Javascript toolchain, so it would take some time to get going.

Thanks for your work on this great project, though; I think the mission and the open source approach are really encouraging!

**Comment by nathanlesage** [comment]
Thanks a lot!

Yeah, the app grew at lightning speed in the past three years, plus I hadn't written a single JavaScript file in a decade when I started working this project, so there's surely a lot to do! As of now I was hesitant to outsource computationally expensive tasks to other threads, because in the Electron world you can only achieve this using BrowserWindows, which is pretty bad semantics … but yeah, the FSAL-rewrite was necessary precisely as it is now easier to add functionality and, hopefully, also optimize.

The question is: Is it always that slow or only on the first start? Because it should've written all file descriptors into 100 cache files (but I'm not sure how big they are, do you mind looking it up?)
