### ISSUE TITLE
[ENHANCEMENT] Word count for entire project of markdown files

### ISSUE THREAD

**Issue by jsstanley** [Zettlr/Zettlr#1105]
## Description
It would be great to be able to view the word count of an entire project, as opposed to single files.

## Proposed Changes
This would involve Zettlr automatically providing the global word count of a project instead of having to manually sum the word counts for all the files in a project.

## Caveats
I don't think there would be any caveats.

## Additional Information
I hope this would be simple to implement given the word count feature for individual files is already there. This isn't a super critical enhancement, more like a 'nice to have' one.

**Comment by nathanlesage** [comment]
Surely a good addition!

**Comment by efficacy** [comment]
I came here to add a similar feature request, but found this one. I'm not sure exactly what is meant by a "_project_" in this context, though. Is it the same as a sub-folder? Is it the whole Zettlr file structure? Is it something else?

Calculating a word-count for folders or even for the whole file structure, would potentially be useful, and if necessary I could live with that. What I would really like, though, is a bit different.

I would like to see aggregate stats in a panel with the search results, so I can (for example) click on a tag to see a word count for all tagged notes. This would give me the freedom to count the words in chapter, a novel, or a whole series, or all books written under a particular pen-name, or with a particular character, and so on.

If aggregate word counting were done on a per-folder basis, for example, I would only be able to count one aspect of this at a time. To do otherwise would require moving notes around a physical file structure (which seems contrary to the Zettelkasten way)

Of course, there are pathological cases such as a search which returns everything in a very large Zettelkasten, but that also poses problems for searching and display of results.

**Comment by nathanlesage** [comment]
> I'm not sure exactly what is meant by a "project" in this context, though.

A "project" is, in fact, a project in this context – that is, a Zettlr Project as outlined in the [Zettlr Docs](https://docs.zettlr.com/en/academic/projects/) :)

> To do otherwise would require moving notes around a physical file structure (which seems contrary to the Zettelkasten way)

A), you could make a workspace itself a project, counting everything in it, and b) I don't see any use of counting words within a Zettelkasten, as these are supposed to be re-written a little bit for book projects. Please also don't let yourself be fooled by statistics, I have come to realize most of them (especially if you yourself are concerned) are counter-productive across a wide range of issues.

Plus, above everything else, the cost-benefit ratio viewed from the whole Zettlr eco-system is simply not feasible (with regard to implementation vs. what we get from it).

**Comment by nathanlesage** [comment]
Word counts are now provided on a per-folder basis, which you can see in the properties or in the file list
