### ISSUE TITLE
[ENHANCEMENT] Allow turning off replacement of filenames with YAML titles

### ISSUE THREAD

**Issue by Shandi97** [Zettlr/Zettlr#1117]
## Description

Add an option to disable replacement of filenames with YAML titles (or anything else).

## Additional Information

I like using folgezettel ids (yes, I know) in the filename but that is tad hampered by having them overridden.  It would be nice if Zettlr didn't replace whatever is put in the filename if we don't want to.

**Comment by nathanlesage** [comment]
Mh, just had another issue that also wants to add yet another way to display file information in the filename thingy … albeit I'm more in favor of adding this option

**Comment by dajare** [comment]
> ## Description
> 
> Add an option to disable replacement of filenames with YAML titles (or anything else).
> ## Additional Information
> 
> I like using folgezettel ids (yes, I know) in the filename but that is tad hampered by having them overridden. **It would be nice if Zettlr didn't replace whatever is put in the filename if we don't want to.**

(My concerned "bolded" in quote above!)

I normally don't use YAML frontmatter ... but now I'm involved in working with a small book project that lives in Markdown, and gets exported to EPUB, and its several versions (for different uses) all have the same YAML **title** ... which makes distinguishing them in the sidebar a **real pain**. 

Given Zettlr's design, it should be a simple matter for the `title` and `filename` to be **additive**, rather than the "title" to *replace* the filename. And surely more user friendly?

Any chance of getting this re-opened? 😬

**Comment by BsNoSi** [comment]
#2620 Afaik, Pandoc uses file names as sorting, therefore  "sort be file name" should sort by file name and not be messed up by a single file showing a title instead of file name.
![13-10-_2021_14-03-07](https://user-images.githubusercontent.com/2784683/137129317-ced603df-6855-4baa-bbda-ab5d042babc0.jpg)

1. is the display of Zettlr (use file name, sort order descending)
2.  is first file with `rename` active which is obviously in wrong sort order

**Comment by lostlostlost** [comment]
Yes, please include an option to show filenames. If the title in the yaml front matter is empty, the filename is just empty, this is not practival at all in my opinion. Also working with different versions of the same file becomes very difficult if they all have the same title but different file names which you can't see right now. Thanks a lot, your work is much appreciated!

**Comment by dajare** [comment]
@nathanlesage THANK YOU!!! :tada: :pray:

**Comment by nathanlesage** [comment]
You're welcome 🥳
