### ISSUE TITLE
Titled Zettelkasten links

### ISSUE THREAD

**Issue by ElectronicTeaCup** [Zettlr/Zettlr#1122]
## Description

Can zettel links be made with specific words? 

![image](https://user-images.githubusercontent.com/31346583/88530239-5d795980-d001-11ea-966d-6558e08ffcc4.png)
![image](https://user-images.githubusercontent.com/31346583/88530272-6e29cf80-d001-11ea-9566-83b29d475d7c.png)

## Proposed Changes
Currently the link will open the path of the number dictating the title, which of course does not exist. From what I understand, the unique tags are necessary for searching, but even with this kind of linking, the tag will be in the .md file.

**Comment by klieret** [comment]
I also just thought of this and fully support it!   This would be really nice to have :)

**Comment by grst** [comment]
One way of supporting this in a markdown-compliant way would be to add standard markdown links with the full relative path to the markdown file, e.g. 
```[Grounding](../test/2020045130234.md).``` 

(I believe these kinds of links are already supported, but it would be nice if autocomplete worked on those)

**Comment by klieret** [comment]
They are actually not supported yet! Also they are prone to breaking if the note moves. I think this is another separate issue (that I'd love to see as well).

**Comment by nathanlesage** [comment]
> Also they are prone to breaking if the note moves

Exactly this is why this won't come. Use-case:

1. Create a file with name `my-file.md`.
2. Link it from a different file using `[[my-file]]`.
3. Add a title which then supersedes the filename, e.g. `[[Some awesome title]]`
4. Rename the file
5. Wonder why it will still search for something possibly unrelated to the link.

While I do understand that some of you want to migrate the ZKN to such an extend that you don't see the underlying stuff anymore, this will be extremely confusing for other users, because people will then use this feature, and afterwards complain that it frustrates them.

Please remember: Internal links are NOT ACTUALLY LINKS in the sense of Wiki-Links. They are fuzzy searches. And you wouldn't want a Google search for "my title" to return "some completely different file", would you?

So, please orient yourselves at what @grst has written, as this is the way to go. In case it doesn't work, please open a bug report, if you'd like some form of auto-complete, please make sure to provide an actionable example-workflow that all of you can agree upon!

Thanks a lot for the feedback! :)

**Comment by klieret** [comment]
@nathanlesage Thank you for your time to write this, I understand your concern.

I think you misunderstood our suggestion though: The specific syntax would be ``[Title]([[ ID ]])``, so this is **just as stable** as the normal ``[[ ID ]]`` syntax, except that you also give a title.

What I wrote about link stability was regarding @grst suggestion of a workaround (use normal markdown style links instead of what @ElectronicTeaCup suggested).

Did that clear up some confusion? I hope we can reopen this issue.

**Comment by nathanlesage** [comment]
> The specific syntax would be [Title]([[ ID ]])

Which would be non-valid Markdown, right?

> just as stable as the normal [[ ID ]] syntax (because it's identical)

No, it's not and that was precisely my point :D My point was very specifically that these "internal links" are **not actual links** and giving it a title _will_ lead to confusion amonst users, especially the newer ones. Try to see it from my perspective: Right now I have to close about 5 issues demanding that feature and say it won't come (out of said reasons). Now imagine I would add the feature: I already have a lot of people that are asking over on reddit much, much easier to answer questions. I do not want to add possible "why does my link not work anymore??" questions. I simply do not have the time for this. :/ I'm simply trying to save time in order to bring Zettlr further forward. Maybe we can think of this feature once I don't have to answer a ton of questions every day about basic functionality.

**Comment by ElectronicTeaCup** [comment]
I felt the way @klieret felt, however, after thinking about it, it seems there is an easy work around for anyone who wants to do this. It will simply need two clicks:

![links](https://user-images.githubusercontent.com/31346583/89017741-18b03400-d31b-11ea-9fdd-61fce7ed0955.gif)

**Comment by klieret** [comment]
@nathanlesage 

I understand that you want to focus on the core functionality, that makes a lot of sense of course. I didn't want to appear as greedy, I can only imagine how much time goes into this already. Thank you for taking the time to explain your decision!  

@ElectronicTeaCup 

Oh that's nice, thank you for the suggestion ;)

**Comment by nathanlesage** [comment]
@ElectronicTeaCup I actually like this workaround, because it basically kills two birds with one stone: One, those of you who want titled links actually get this, and it still works, and others won't be confused :)

**Comment by canpolat** [comment]
@nathanlesage I think this would make a good tip in the documentation about [internal linking](https://docs.zettlr.com/en/academic/zkn-method/#internal-linking). I will see if I can send a PR for this in the weekend.

**Comment by nathanlesage** [comment]
@canpolat you're the best!
