### ISSUE TITLE
[ENHANCEMENT] Folder Ordering

### ISSUE THREAD

**Issue by Kangie** [Zettlr/Zettlr#1137]
## Description
Zettlr should provide the option to process Project dirs / subdirs by name, as an alternative to the current processing method.

## Proposed Changes
Project directories should be able to be parsed in 'name' order, rather than by 'filename' then 'foldername'
```
01 File_1.md
02 File_2.md
03 Subdir\01 File_1.md
03 Subdir\02 File_2.md
04 File_3.md
```
This should be implemented as an alternative (not a replacement) for the current processing method. 

## Caveats
This is a breaking change for established projects; This should not be made the default or the change should be clearly called out in the release notes.

## Additional Information
This would be useful for technical documents (guides, etc) where one section needs to be expanded into a subdir (for granularity in documentation), but not necessarily others. I don't see a point in making a subfolder for each individual file in a project directory / subdirectory just so that the one subdirectory with two (or more) files is exported in the correct position.

**Comment by nathanlesage** [comment]
Do I understand you right that your aim is to have folders "interleaved" with the files instead of always files first?

**Comment by Kangie** [comment]
> Do I understand you right that your aim is to have folders "interleaved" with the files instead of always files first?

Exactly. 

I think that the added flexibility will be worthwhile. 

I'm currently working on a project where to match the UI I'm documenting (in natural order of progression) it would be convenient to be able to have multiple markdown documents for mutually exclusive settings in a folder that's processed in the middle of an otherwise flat structure (at that level).

**Comment by nathanlesage** [comment]
Well it should be actually pretty easy, as I only need to tap into a specific part of the code. Should be easy enough!

**Comment by boomesq** [comment]
Is it still possible to have this implemented? Others like me coming to Zettlr from Scrivener would really appreciate this feature. Having folders and files interleaved rather than having one appear over the other helps a lot with visualizing/keeping track of the logical flow of a book manuscript or other large work when there are big discrepancies in the complexity of ideas or how developed they are. For example, in Scrivener, if you have some ideas that involve multiple subissues and/or are still largely inchoate, and others being very simple and/or more-or-less finished, and you know the order they will appear in,  you can make the former folders and the latter files, order them accordingly, and collapse or expand the folders depending on whether you want to focus on the individual ideas or the larger structure.

**Comment by nathanlesage** [comment]
Feel free to open a PR; I unfortunately don't have the bandwidth to deal with this.
