### ISSUE TITLE
[FEATURE] Support Editing History for the TableEditor

### ISSUE THREAD

**Issue by 13rac1** [Zettlr/Zettlr#1155]
## Description
Row/column additions/deletions in the table UI can not be undone using the Undo command. Safe to assume redo is broken also.

## Reproducing

1. Make a new note
2. Right Click to open the context menu
3. Select _Insert table_
4. Use the "Delete Row Icon" to remove a row
5. Press `Ctrl/Cmd`-`Z`
6. Nothing happens

## Expected behaviour

Row and data should reappear.

**Screenshots**
Row delete button selected.
![image](https://user-images.githubusercontent.com/195061/89228255-20c6d880-d594-11ea-9646-e48e51c4b807.png)

## Platform
 - OS and version: Ubuntu 20.04 / Mint 20
 - Zettlr Version: Current `master`
 - Screen Resolution: 2560x1440 & 1920x1080

**Comment by nathanlesage** [comment]
> Safe to assume redo is broken also.

It can't be broken if it's not even implemented 😛

But I see your point. However, this will require a s\*\*\*load of work, so I can't say anything as to when …

**Comment by 13rac1** [comment]
I wasn't trying to be glib :laughing: It didn't seem like a feature request since "undo" doesn't work.

**Comment by nathanlesage** [comment]
Absolutely, only "undo" doesn't look like a feature request – but the problem is that by changing tables you're actually leaving the editor, so nothing is currently recorded in the editor — the editor itself only sees two states: The table BEFORE your edits, and then the table AFTER your edits — so using "undo" you can only completely revert the changes to your table right now, and hence the table editor needs to implement its own undo/redo-history.

Gonna be fun 🙃
