### ISSUE TITLE
[ENHANCEMENT] Clarify setting: Home and End keys

### ISSUE THREAD

**Issue by caseywatts** [Zettlr/Zettlr#1176]
## Description
Clarify Home/End options in settings

## Situation
Currently the help text in Preferences `Use the CodeMirror default actions for Home and End` requires that I know:
* what CodeMirror is
* what CodeMirror's default actions for home and end are, and
* what the implied alternative would be 

I definitely didn't notice the setting it the first three times I poked around for this haha. I only found it after coming across these two issues:
* https://github.com/codemirror/CodeMirror/issues/1576#issuecomment-19146595
* https://github.com/Zettlr/Zettlr/issues/201

## Proposal
I propose changing the text to say says `Home and End go to the beginning and end of the paragraph (instead of beginning and end of the visible line)`.

"Paragraph" is more accurate than "line" in this writing context we're in. I don't think of "line" in the same way when I'm writing text vs writing code.

## Additional Info
I'm both a writer and a developer, and I definitely think of Zettlr as more of a writing editor than a code editor, even though I totally realize it uses CodeMirror under the hood.

## Default?
This could be a separate issue, but I think the default setting for this option is backwards from what the majority of Zettlr users probably expect. (I also believe it's probably the opposite of what most CodeMirror users expect too haha but that's another discussion).

Changing defaults can be contentious, but maybe if we polled the users somehow we could get a good sense of it! "when you are on the third line of a paragraph and you press "home" on the keyboard, where do you expect the cursor to go?" "to the beginning of the paragraph" vs "to the beginning of the line".

Alternative help text if we flipped the default could be `Home and End go to the beginning and end of the line (instead of beginning and end of the paragraph)`.

**Comment by lodestone** [comment]
I agree `Use the CodeMirror default actions for Home and End` wording is unclear. To be honest, I saw it, and because I didn't understand what it was, I just ignored it. Perhaps that reaction is a sign that the CodeMirror Home/End settings could be safely moved into a more advanced settings area. Might help keep the main Editor settings screen simpler.


---


In fact, off the top of my head, the wording of other settings on the Editor tab could be improved as well.

<img width="801" alt="Screen Shot 2020-08-08 at 1 29 47 PM" src="https://user-images.githubusercontent.com/8401/89717375-ae7f3b00-d97b-11ea-9c6f-06abff4a94ce.png">

- "Mute non-focused lines in distraction-free mode"
    - *Suggestion*: "**_In Distraction-Free mode, dim the text outside of the current typing area_**"
- "Automatically close matching character pairs"
    - *Suggestion*: "**_Automatically add the matching end character for `(`, `[`, `{`, `"`, or `'`_**"

...just some quick suggestions..


## More Food for Thought

In terms of approachability, an easy way to reduce the learning curve of a new app is to make any text straightforward. Also, to that end, the fewer "in your face" settings, the more approachable it will feel.

I see this broken down in to:

### **1. _Clarification of wording_**

_Yes, I expect any Zettlr users to be highly intelligent linguistically 😜_

### **2. _Organize settings locations to optimize learning curves_**

_For example, which settings warrant inclusion on the main/default areas versus living in an "Advanced"._

**NOTE:** _Obviously this might trigger a redesign/reorganization of the actual Advanced tab...._

Please forgive my newbie ignorance of any issues already in the pipeline on this! 😄

**Comment by nathanlesage** [comment]
Uh, finally a non-code-related issue, what a relief! ❤️ 

Concerning the wording: Yes, absolutely. With regard to the specifics:

**"Use CodeMirror default actions"**

I would even suggest we transform this thing into a radio button. I implemented it as a checkbox because I was lazy, and a radio button would be more natural:

```
- ( ) Home/End refer to the visible line
- (*) Home/End refer to the paragraph
```

The wording in itself would then need to be done in [Zettlr Translate](https://translate.zettlr.com/) by users, but you can certainly immediately translate this so that your wording gets precedence!

Feel free to provide clear ideas on what should be changed how, this would help because this would be actionable. You can also point me to your new translation suggestions on Zettlr Translate — all of the English ones are only by me and I can easily remove my translations so that yours end up in the translation file. And as English is the reference language this would cascade onto the other languages as well.

The easiesst way might be to collect everything here and adapt that in one batch, then I could email all other translators as well and ask them to revisit all translated strings to see if the new wording changes something which they should adapt in their language.
