### ISSUE TITLE
[ENHANCEMENT] Make update notification non-obstructive

### ISSUE THREAD

**Issue by tupio** [Zettlr/Zettlr#1178]
## Description
It is nice to be notified about new releases and I like it, but I would like it to be non-obstructive.

## Proposed Changes

1. Make the pop-up smaller.
2. Show an icon that denotes a fix for a critical bug. (So that I can update it quickly)
3. The notification should not obstruct the user.

## Caveats

The adoption of the new update will be slower if the update. (A possible solution is to create a self-updating app)

## Additional Information

If this problem is already present kindly point me at it.

**Comment by nathanlesage** [comment]
I do see that! The reason the update notification is that "in ya face" is because I want to minimize the people using older apps opening issues here and thereby reduce the workload. Maybe a self-updating app would be the easiest, but it's quite something to set up … however, I'm considering replacing the update notification with a visible button in the toolbar

**Comment by nathanlesage** [comment]
Already done, ships with 1.8
