### ISSUE TITLE
[DEVELOP] Migrate from electron-builder to electron-forge

### ISSUE THREAD

**Issue by tobiasdiez** [Zettlr/Zettlr#1187]
With #1060, electron-forge is used to package the application, but electron-builder creates the installer. In the long term, the second step should also be handled by electron-forge using their `maker`. https://www.electronforge.io/config/makers

For windows, the [electron-forge-maker-nsis](https://www.npmjs.com/package/electron-forge-maker-nsis) could be helpful. And a few related issues (concerning the deprecated squirrel): https://github.com/electron-userland/electron-forge/issues/485 https://github.com/electron/electron/issues/17722

**Comment by nathanlesage** [comment]
As far as I can tell, there are (as of now) some problems:

- There is no plugin for AppImages; according to the GitHub API there are approximately 300 downloads alone for the AppImages (approximatel 10% of the macOS target group)
- There is no plugin for Windows 10 ARM 64 builds, right?

**Comment by nathanlesage** [comment]
Since it doesn't seem that Electron-forge will support the range of stuff we actually need I am going to close the issue for now. However, we can always re-open it if the circumstances change. But since the electron-forge/electron-builder couple work pretty flawless right now, I think it's perfectly fine to close it for now!
