### ISSUE TITLE
[FEATURE] Add a graphical way to use custom `--reference-doc`s for Pandoc

### ISSUE THREAD

**Issue by nasteffe** [Zettlr/Zettlr#1193]
Offer a visual space in the program settings where a user could choose from standard Word reference documents or upload their own customized version. Then when they try to export/share their markdown into a Word document, Zettlr could pass the Word reference document via pandoc's '--reference-doc=FILE' option.

1. User selects reference document, either by selecting a pre-filled standard option or by uploading their own customized Word style reference file. 
2. When sharing the markdown file into a Word file, Zettlr would use the reference file for the conversion.

This would directly impact that current share to a Word document feature.

I imagine the aforementioned setting space would offer a set dropdown menu of a few example reference documents and a link to download them. For users confused as to what constitutes a reference file in Word, having examples to work off of could be helpful.

The inspiration for this is not my own. Raphael Kabo created a small application called DocDown to help send markdown files through pandoc as part of his own academic paper workflow and asks users to select a Word style reference file. I used this functionality myself and found it would allow users to do a remarkable amount of customization to their preferred Word style document in Word itself. I was disappointed to find that other markdown programs exporting into rich formats were not using this functionality. 

Looking at Kabo's code, it appears that in line 134 of https://github.com/lowercasename/docdown/blob/69ec46d755ed3f3eeb7790de2ee268686b18dfae/main.js he passes in settingsObject.docxFile as a --reference-doc option.

**Comment by the-solipsist** [comment]
I'm not sure this is a good idea. 
1. Pandoc has [dozens of options](https://github.com/jgm/pandoc/files/3993006/defaults-narrow.pdf). People would arguably be benefited by any number of those options being exposed in the Zettlr GUI. But that would make the GUI needlessly cluttered.
2. Since version 2.8 (2019-11-22), Pandoc provides a way of specifying "default" command-line arguments in a separate file, which can be added using `--defaults` or `-d`.  This is, to my mind, a preferable way of specifying the command-line arguments (including `--reference-doc`, using `reference-doc:` in the defaults file), rather than in a dedicated GUI element for `--reference-doc`.
3. Zettlr promotes directory-based "projects", rather than just files. But one can work on multiple projects in multiple tabs.  Defaults (including reference-doc, as well as the bibliography/"citation database" and citation style files) can and usually do change from project to project.  So, rather than having these in the GUI, it makes sense to separate them into project-specific files.
4. A clear set of criteria are needed to determine the threshold for what Pandoc options should be made visible in the preferences GUI and what should not.

As an aside, but following from (3) above:
Currently Zettlr uses "citation database" and CSL files not just for exporting (though that is where the options are located), but for suggestions (for citations) and for displaying the "References" sidebar.  Allowing for project-specific options for these would be advantageous (Zettlr wouldn't need to load a gigantic citations database into memory if there's a smaller project-specific bib file available).  This will also mean that one can specify the CSL and BIB files once for both pandoc and Zettlr, instead of specifying them in two different places.  If there is interest in considering this further, I will open a separate Github issue / post on the forum, and discuss the positive and negative implications of this suggestion.

**Comment by nathanlesage** [comment]
> But one can work on multiple projects in multiple tabs.

This would be a great enhancement: Enable the possibility to export a project if you export a file from within a project!

> Allowing for project-specific options for these would be advantageous (Zettlr wouldn't need to load a gigantic citations database into memory if there's a smaller project-specific bib file available).

That's already a feature request somewhere!

**Comment by nathanlesage** [comment]
Just found this issue again, and I think we can close it, since 2.0 will actually offer such a graphical way, since you can edit all default files easily with a built-in editor!
