### ISSUE TITLE
More Sort Order options

### ISSUE THREAD

**Issue by davidbosman** [Zettlr/Zettlr#120]
## Description

Is it possible to have more sort options in folders: by Date Created, by Date Modified, both in ascending or descending order. *And* also have the option to order them *manually*.

* By Date is useful to access the more recent files easily (descending/more recent first by default?).
* A manual sort order is useful when writing fiction and playing around with chapters order: being able to move them freely without having to rename them each time. Exactly like in Ulysses or Scrivener.
## Reproducing

Have the buttons next to the actual ones in the sidebar?

## Expected behaviour

Sorting the files as expected ;)

## Platform
 - OS: macOS Mojave, Windows 10
 - Zettlr Version 1.2.0

**Comment by nathanlesage** [comment]
Heya,

soooo (you don't have to use the bug report template when you're suggesting new features :D)

Currently the sorting options are names asc/desc and modified date asc/desc. The creation date should pose no problem to add!

**BUT** (there's always a "but", because life is bad)

Concerning the manual order: I'm hesitant, because what I utterly disliked was the way Ulysses, for example, managed this: they added meta info files into every directory to both manually sort files and remember the sorting (as suggested in your second issue), and those pesky little files remained even until two years after I stopped using Ulysses, which I really hated. Even the small files added when creating a project or adding virtual directories now cause a lot of headache for me.

So while I really see the benefits, I'm still a little bit "meh" :/

**Comment by davidbosman** [comment]
As a user I'm not that worried about files (and I use quite heavily the manual sort option), but I do see your point. It can be a mess.

>So while I really see the benefits, I'm still a little bit "meh" :/

To mitigate the '*meh*' factor wouldn't it be possible to delete those files, if Zettlr was to create them, after they haven't been used/accessed for a while?

Or maybe not store those files in each folder direclty but in some central config ".whatever" file somewhere else, avoiding all clutter at once?

(any impression that I know close to nothing to dev would be justified, I'm afraid ;))

**Comment by ploum** [comment]
Adding my voice for the creation date. Trying to handle my journal in Zettlr and it happens that I just added a letter to an old entry, breaking the flow.

<img width="272" alt="Screenshot 2019-05-19 at 23 04 09" src="https://user-images.githubusercontent.com/1233155/57988134-b1e28a00-7a8a-11e9-9e60-a60988dbbc2a.png">

**Comment by filipgoc** [comment]
Another voice.
Creation date feels like a no-brainer :-) 

As for custom order... While I am sympathetic to the possible implementation conundrums, UX-wise it feels useful. For many projects I really want a specific order, especially when splitting longer writing into sections, and having to preface the name with numbers or something and keep that consistent is an annoyance. 

Part of me just expects it. It's one of those things that I don't expect in IDE, but do expect in writing and note taking apps (Notion, Onenote, Evernote... whatever). 

Also Project feature could really use this. Especially when quick testing exports so that we can see how the final project would look like and quickly test various versions etc... It makes me think that custom sorting needs to also be persistent. As in, truly a third sorting option that is remembered. And, it is mostly desirable in virtual folders and projects. 

All of this is just to say... I think it's definitely desirable. If implementation is an issue, then that's a different discussion.

**Comment by nathanlesage** [comment]
Finally an old issue to close!

**Comment by ploum** [comment]
insert crowd cheering gif.

**Comment by filipgoc** [comment]
Wohoo.
