### ISSUE TITLE
[ENHANCEMENT] Rownum and scroll bar  for the code blocks

### ISSUE THREAD

**Issue by atlasbioinfo** [Zettlr/Zettlr#1241]
## Description

Zettlr is a perfect note-taking software, which completely meets my requirements. I have migrated my notes to Zettlr. **I take lots of notes with the code, like python, R, and HTML. But I find that there is less support for "Fenced code blocks" at the moment.** It would be perfect if the following changes could be added.

## Proposed Changes

* Add row number to the code block
* Add horizontal scroll bars instead of word wrap

I don't know if this feature is troublesome, but it will help me a lot. 

Many thanks for this great note-taking software.

**Comment by nathanlesage** [comment]
mh, I'm not sure that the requested changes (which I totally agree would be a huge improvement) are possible using the current setup. We'd need to wait for the Vue refactor of the frontend for this to work, I think … so I'll pin this issue but we can't really tackle this. Once you hear about us rewriting the frontend, please make sure to ping us here so that we can keep that in mind while we rewrite everything. To hear about the frontmatter rewrite, it's best to [follow our twitter](https://www.twitter.com/Zettlr).

**Comment by nathanlesage** [comment]
Hey, just chiming in here. Since this issue has now been open for more than two years, and even CodeMirror v6 doesn't give a clear path to doing so, I will close this as `wontfix`. This means that horizontal scrollbars aren't going to be implemented. As with everything, if someone does manage that, I'm always happy about PRs!
