### ISSUE TITLE
Sometimes doesn't save an editor input method

### ISSUE THREAD

**Issue by dukebarman** [Zettlr/Zettlr#1245]
## Description
I have a saved option: Editor Input Mode - Vim and sometimes it returns to Normal after restart.

## Reproducing
I haven't got a 100% scenario to reproduce but guess that it happens after shutdown machine without default Quit from Zettlr.

## Expected behaviour
Editor Input Mode doesn't return to default value

**Screenshots**

## Platform
 - OS and version: Windows 10 with last updates
 - Zettlr Version: 1.7.5
 - Screen Resolution: 1920х1080

**Comment by canpolat** [comment]
I don't think Zettlr saves the settings if it is force closed (terminated instead of the window being closed). But you can do an easy test on this:

1. Launch Zettlr
2. Edit your preferences and select the mode you want
3. Close Zettlr 
4. Restart machine
5. Launch Zettlr

If the mode is Normal, then it is a bug, if it is Vim, then the problem was occuring due to Zettlr not saving the configuration on forced quit (which is the expected behavior).

**Comment by nathanlesage** [comment]
Exactly, in order to prevent un-startable instances, the settings are only saved juuuuust before the app shuts down normally. So in case some setting misbehaviour causes the app to break, it'll restart again with the last known working configuration.

**Comment by nathanlesage** [comment]
Closing due to lack of feedback, I'll view this as solved. If not, please comment.

**Comment by dukebarman** [comment]
Sometimes this behaviour returned but couldn't catch a scenario for repeating so agree.

**Comment by nathanlesage** [comment]
As soon as there is reproducibility, I will fix whatever is causing this. Please comment here if you find anything!
