### ISSUE TITLE
[FEATURE]: MarkDown Linting.

### ISSUE THREAD

**Issue by Kangie** [Zettlr/Zettlr#1260]
# Description
When working with documentation across a large project (or several large projects), it would be useful to be able to perform some MarkDown linting (configurable at the project level) to ensure that content is consistent across the project.

## Example Workflow
1. Select 'Lint Project' (assuming that linting rules have been setup for the project).
2. Zettlr processes the project (implementation details TBA; suggestions?)
3. Zettlr outputs a report on enabled linting rules; e.g.
  - Absolute image paths
  - Links that don't have a destination (e.g. `[This is a link]` with no attached URL).
  - Invalid / non-existent Pandoc-style auto-generated heading links.
  - Whatever you want, really! It's configurable.
  - This report should probably be a MarkDown document opened within zettlr with a tasklist for errors / warnings / etc, filenames and line numbers.

## Additional Info
Just a thought. I've been considering writing a script that would do this, but thought that others might benefit from this functionality available within Zettlr.

I'd be very interested in feedback / discussion!

**Comment by nathanlesage** [comment]
This would require an additional overlay mode if I'm not mistaken – I personally don't really want to invest this time (because it will also make the CodeMirror config even heavier) – at least not now. Zettlr will soon switch to CodeMirror.Next, once it's released, and _then_ we can update everything and perform some cleanup in the CodeMirror code as well, so I won't implement this for CodeMirror 5, but I'll be willing to do it for CodeMirror.Next!

**Comment by Kangie** [comment]
I'm happy to wait for CodeMirror.Next for this to save on development effort and complexity - doesn't look like it's too far off.

If I get to the point that I'm spending more time reviewing documents for consistency & nitpicking than writing I'll see if I can convince work to allow me to work on this for efficiency (or look at it in some spare time) before then!
