### ISSUE TITLE
"Paste without style" key combination not working

### ISSUE THREAD

**Issue by samarulmeu** [Zettlr/Zettlr#127]
## Description
When copying from a web page the pasting process is not working as expected. 
Using `Ctrl+Shift+V` you paste also the code (tags, etc), but when using the application menu `Paste without style` the application behaves at expected and pastes only the text. 

## Platform
 - OS: Linux
 - Zettlr Version: all version (including the last one - 1.2.1)

**Comment by nathanlesage** [comment]
Thanks for the report, I'll look into it!

**Comment by davidbosman** [comment]
Same here, under the Mac and Windows version. The only workaround I've found is to paste it first in a standard text editor, then copy that to paste it in Zettlr.

Pasting without style is also very slow on huge chunk of text (like 15 seconds or more with nothing happening on screen, probably because of all the code colouring it does in the background?). 

Experimented that on my 2015 15" Mojave MacBook Pro (Core i7, 16g ram), and on my Windows 10 Pro desktop (Core i7/16Gb ram).

**Comment by nathanlesage** [comment]
I just tested it with the latest dev-build, but it does not happen under macOS (anymore). I think it has something to do with the keymaps. I'll test something out

**Comment by nathanlesage** [comment]
So, just tested it on my work Windows PC; it was indeed a problem with the keymaps, somehow pressing `Ctrl/Cmd+Shift+V` triggered a standard paste instead of the specific behaviour of precisely _not_ having the stuff converted from HTML to Markdown.

@davidbosman Short question: How much text did you try to paste to wait 15 (!) seconods until Showdown.js was done? o.O I mean that a huge chunk of text takes some time is one thing, but 15 seconds is extremely long for a simple conversion, especially with an i7 Quadcore on macOS.

(Update: I just tried to paste the full CodeMirror manual by myself and the app just died ☹️)

**Comment by davidbosman** [comment]
Appox 4k, but it could have been 10 seconds I did not measured it: it just felt *that* slow ;)

**Comment by nathanlesage** [comment]
Yep, it might be an issue with the Showdown-library, but I'm not sure. What I'm sure of is that at least one component that Zettlr uses is unable to handle that much text.

**Comment by semiopat** [comment]
Hi,
I'd like to reactivate this thread to know if a solution was find.
 Tell me if I'm wrong, the problem on mac os is that a keyboard shortcut is used by the system to copy with no style (`Maj`+`Alt`+`Cmd`+`V`), and Zettlr use another one (`Maj`+`Cmd`+`V`), but both are not working on Zettlr: the first did nothing, the second open a promt grey useless window with the text copied… Is that possible that Zettlr just use the system shortcut rather than a special one which could interfer with other commands in the system?
Did a solution be find, or, in case not, would there be a solution ?

**Comment by nathanlesage** [comment]
So the shortcut doesn't work but the menu item works? Sounds as if any other app is blocking the `Cmd+Shift+V`-shortcut. I've had the problem related to the app Spectacle and LibreOffice. Inserting comments in LibreOffice uses the shortcut `Cmd+Alt+C`, but that shortcut was then subsequently blocked by Spectacle, which resulted in me not being able to paste any new text.

Besides, I'd not want to switch the shortcuts, because for one it's easier only having to press three buttons instead of four (`Cmd+Shift+Alt+V` is a horribly un-ergonomic movement) and second to maintain cross-platform behaviour.

So what I'd suggest are these options:

1. Find the app that registers `Cmd+Shift+V` as a system-wide shortcut and re-assign it in that app.
2. Override the `Cmd+Shift+V`-shortcut on your Mac in the System Preferences -> Keyboard (I think)

**Comment by semiopat** [comment]
Yeees! Thanks for your answer, I find the app that takes over the shortcut: FlyCut, my clipboard manager, that explains why it's overriding others apps. The best thing is that shortcut is totally useless for me, but was set by default. Thanks, that is just an annoying behavoir that flies away.

**Comment by nathanlesage** [comment]
Glad it works out! :)
