### ISSUE TITLE
Toggle Sidebar shortcut not working as expected on mac

### ISSUE THREAD

**Issue by YueGan** [Zettlr/Zettlr#1273]
## Description
`Toggle Sidebar` shortcut (Command + Shift + 1) not working, it would switch to first tab insteand

## Reproducing
Command + Shift + 1

## Expected behaviour
Toggle Sidebar

## Platform
 - OS and version: Catalina 10.15.6
 - Zettlr Version: 1.7.5

**Comment by sxn** [comment]
A similar thing happens with `View attachments`, which is assigned to `CmdOrCtrl+?`, though I'm not sure if the cause is the same.

On `macOS`,  `Shift+Cmd+/` is, by default, assigned to `Show help menu`:
<img width="780" alt="Screenshot 2020-09-18 at 21 34 50" src="https://user-images.githubusercontent.com/1155589/93638013-dcce4c80-f9f6-11ea-8731-b0c9b1ba2c51.png">
There's an ongoing discussion in the [Electron repository](https://github.com/electron/electron/issues/19048) about this.


Would it make sense to change [the shortcuts for `toggle-sidebar` and `toggle-attachments`]( https://github.com/Zettlr/Zettlr/blob/develop/source/main/assets/menu.tpl.json#L230-L239) to `Ctrl+!` and `Ctrl+?` respectively? On Windows & Linux it shouldn't change anything, but it would fix the issue on macOS (though arguably `Ctrl+!` is less comfortable to press than `Cmd+!`).

**Comment by nathanlesage** [comment]
> Would it make sense to change the shortcuts for toggle-sidebar and toggle-attachments to Ctrl+! and Ctrl+? respectively? On Windows & Linux it shouldn't change anything, but it would fix the issue on macOS (though arguably Ctrl+! is less comfortable to press than Cmd+!).

Hmm … this might make sense. But this would interfere with the way keyboard shortcuts work in general on macOS. Plus, the problem does not occur on a German keyboard layout, it's specific to US-based keyboard layouts (if I'm not mistaken?).

Hence, if there's an obvious bug by the Electron framework, we should wait for them to solve the issue. Especially keybindings are weirdly handled by Electron, which I don't like myself (see the Zoom shortcut on Windows, where you have to click `Shift` as well)
