### ISSUE TITLE
[ENHANCEMENT] Closing tabs behaviour adjustments 

### ISSUE THREAD

**Issue by regoje** [Zettlr/Zettlr#1282]
A couple of suggestions to the way tab closing works, mostly following what other software does:

1. Ctrl + W should not close the window once all the tabs are closed OR at least there should be a preference for whether it does
2. Ctrl + Shift + W should close all tabs (+ optionally the window as well)
3. There should be a way to close all other tabs

**Comment by Kangie** [comment]
This has been partially addressed in #1250 - You can now right click on a tab to close all tabs. It will be available in the next release.

Closing all other tabs would be a nice enhancement.

It's probably worth some discussion around how users want tab closing behaviour to work though; 

To Clarify: 

| Command                                             | Current Behaviour | Desired Behaviour                      |
|-----------------------------------------------------|-------------------|----------------------------------------|
| **Ctrl**/**Cmd**+**Shift**+**W**                    | Close Window      | Close all Editor tabs.                        |
| **Ctrl**/**Cmd**+**W**                              | Close Editor Tab  | Close Editor Tab; Do not close Zettlr. |
| Right-Click on tab heading --> Close all other tabs |                   | Close all other editor tabs            |

Thoughts, everyone?

**Comment by nathanlesage** [comment]
With regard to the table:

1. Ctrl/Cmd+Shift+W: This is behaviour I took from macOS. Is this being done differently on Windows, and Linux? If so, I need a precise listing of how this works on these platforms so that we can adapt the shortcuty.
2. Ctrl/Cmd+W: Same as row 1
3. No no no, please add a context menu entry for that. (According to another issue we have to fix, the "Close ALL tabs" command currently works exactly like that, heh)
