### ISSUE TITLE
Performance issues when Zettlr is left open

### ISSUE THREAD

**Issue by sifutao** [Zettlr/Zettlr#1298]
## Description
Performance issues arise when Zettlr is left open. At launch no particular problems but after half an hour or so, Zettlr seems to ask for more and more ressources to the point that I have to close it. My Zettlr is composed of two main directories that are sync to the cloud /jottacloud and /onedrive. Not too many .md in each directory maybe less than 200 for each directory.

## Proposed Changes
I have no idea technically what should be done. But it would be great to be able to keep Zettlr open without too much impact on the computer performances (right now I have to close it, so it does have a huge impact on how practical Zettlr is on a day to day basis).

## Additional Information
Thanks for the awesome work you do with Zettlr.

**Comment by sifutao** [comment]
Is this the info you want? 

Current System Load
CPU Load: 2.77 %
Resident Set Size: 244.69 MB
C++ memory for JS Objects: 1.23 MB
Heap: 38.98 from 44.94 MB (Limit: 4194.05 MB

**Comment by nathanlesage** [comment]
Yes, and now after the performance issues occur. If the Resident Set Size and the C++ memory and the Heap (or one of them) is going way up from this (very normal looking) stuff, then we have it!

**Comment by ploum** [comment]
For me, the performance issue is mainly due to the new "stay open in tab" behavior. As I don't close file (just switch between them) and because Zettlr never close tabs (even after a restart), I have thousand of tabs open without realizing it.

It becomes so problematic that, sometimes, I click on a file in the pane and another file is displayed and the whole system seems to be on his knees (yes, my processor is very weak)

**Comment by nathanlesage** [comment]
For your problem maybe a reminder (warning, you have too many tabs open) would make sense?

**Comment by ploum** [comment]
I don't think it would adress the root cause of the problem, which, for me, is that tab should not open if I don't explicitely ask them to be open. But this is for another ticket. I wanted to highlight the fact that, maybe, performance issues are caused by the new behaviour which opens lot of tab without the user noticing.

At least for me, this is the case. Solving the tab problem would solve my performance issue.

I don't know if I'm representative of other users or if I'm kind of a edge case but I thought it worth being mentioned ;-)

**Comment by jdidion** [comment]
I am on version 1.7.5. Zettlr is constantly using 15-20% cpu with only two small documents open (display only, I am not editing them).

**Comment by nathanlesage** [comment]
@jdidion What does the About panel say about the CPU usage? Similar?

**Comment by jdidion** [comment]
This is all my about panel shows:

![image](https://user-images.githubusercontent.com/125854/94948058-b3a8c400-04ac-11eb-8073-dafaabf2d041.png)

**Comment by nathanlesage** [comment]
@jdidion I meant the "big" one, not the native macOS one (the one I mean is accessible from the Help menu)

**Comment by jdidion** [comment]
Oh, sorry. It is reporting very different CPU usage than Activity Monitor. I know the percentage in AM is for a single CPU, so if the Zettlr number is normalizing over all CPUs (I have a quad-core Macbook Pro) that could explain some of the difference.

![image](https://user-images.githubusercontent.com/125854/94953775-19e61480-04b6-11eb-8be1-483fae46207d.png)

**Comment by nathanlesage** [comment]
This almost seems like an issue with Electron itself, because as far as I know the CPU usage number in the About window only applies to the renderer, not the main, and I know for sure that there's nothing in any computing loop there (except chokidar, but I don't have any reason to believe that this process is using as many resources as the numbers you are reporting). Maybe an Electron update will fix this in the alphas?

**Comment by nathanlesage** [comment]
Bonjour! There are good news: The high CPU load and performance issues were caused by a bug that even Microsoft has to deal with.

The solution was as simple as two options, [for the rest & your enjoyment I'll just leave my rant-tweet about it here](https://twitter.com/zettlr/status/1328798858680410112). Comes not with 1.8 beta number 3, but with the one afterwards! Maybe even 1.8 stable. Let's see!

**Comment by jdidion** [comment]
Hooray, it's fixed! Down to 2-3% cpu usage.
