### ISSUE TITLE
Feature: Optional Folding

### ISSUE THREAD

**Issue by jcuenod** [Zettlr/Zettlr#130]
I would just like to be able to turn off the the folding marks.

I will basically never want to fold sections and I just don't need the UI there and feel like it's distracting...

Thanks again for a great note app!

**Comment by samarulmeu** [comment]
You can turn it off adding this to your Custom CSS:

```
.CodeMirror-gutter-wrapper {
  display: none;
  visibility: hidden;
}
```

**Comment by nathanlesage** [comment]
Please see the solution by @samarulmeu. I might add additional gutters and the problem is that styling CodeMirror gutters is difficult, and therefore I would like to keep the variables easy to maintain. Maybe I'll see to adding such options in a future version, but currently I would really like to keep this off my mind :)
