### ISSUE TITLE
[Enhancement] Allow users to open files in the standard way

### ISSUE THREAD

**Issue by andypea** [Zettlr/Zettlr#1307]
##  Description

It took me about 10 minutes of googling and experimenting before I could figure out how to open an existing markdown file in Zettlr. Zettlr has many nice features, but I don't feel comfortable recommending it to my colleagues when the process of opening files is so different from the standard approach used in most other pieces of software.

## Proposed Changes

Add a new path for opening existing markdown files that closely matches the typical workflow in other pieces of software, such as Microsoft Word.

## Caveats

A comment on issue #236 mentions that "Zettlr is made for working mainly with directories". As a novice user, I don't completely understand this point, but it seems important.

**Comment by Kangie** [comment]
I see what you're saying here - Within the Zettlr UI there's no easy way to open a file and the open action and shortcut (**Ctrl** + **O**) defaults to opening a directory. Outside of Zettlr, if you double-click on MarkDown files they open as 'Files' within Zettlr. You can also drag-and-drop MarkDown files onto Zettlr to do this.

Would a Keyboard Shortcut (say **Ctrl** + **Shift** + **O**) and an 'Open Single File' action in the _File_ menu go towards fixing that? It _shouldn't_ be the default method of opening files, but if the capability is already there and you just quickly need to open a single file I can't see why you should have to use a separate file manager.

Really though, Zettlr is designed to work with directories. If you open a directory within Zettlr, it'll show the directory structure from that point down, but only files of the following types will be available to edit/open within Zettlr: 

- Markdown (.md)
- LaTeX (.tex)
- RMarkDown (.Rmd) (if enabled.)

In my use case, that's a directory for each piece of documentation that I create, and I work within that folder structure.

Give it a go and let us know if it makes a bit more sense to you now - it could be that the documentation needs an update.

It's very unlikely that the default Zettlr 'open' action will ever target files; your colleagues may need to learn to open directories instead.

**Comment by nathanlesage** [comment]
So the reason why I implemented it this way and didn't change it is because I want to nudge people to order their files in directories. I've seen many, many friends completely cluttering their desktops with random files, and this strongly triggers my OCD. So I want users to open directories, not files -- file opening is fine, of course, but the default in my opinion must be to work with permanently opened directories. However, you are completely right that it is somewhat difficult for new users, which was one of the reasons I recently added the tutorial.

Nevertheless, I just had an idea as to how we might be able to mitigate this! First, purely technically it's super simple to implement an "Open file"-shortcut, but moreover, how about we rename "root directories" (which arguably do not resonate with the user base) to "workspaces"? I think this might make it much easier to understand what the purpose of opening directories is in the context of Zettlr and doesn't make it weird for non-technical users.

Opinions?

**Comment by ecodiv** [comment]
I do organize all my files in directories, but I still would love to have a direct way to open files directly as well. These are the files I need to be able to access quickly and often, but which are not part of a notebook (which is for which I use Zettlr primarily). What makes this so convenient is that those files stay on top, under 'files' in the files-directory tree.

As for the renaming root directories to workspaces, good idea. It is a more intuitive and generic name.

**Comment by andypea** [comment]
Thanks for the detailed responses.

Now I understand how Zettlr works I do appreciate how the interface focuses on directories and I think it will work well for me. However, I still think that allowing individual files to be selected for opening would be beneficial for people who use the software less frequently.

How about allowing a file be selected in the "Open project folder" dialogue, which would result in the containing directory being opened in the side-bar and the file being opened in the main pane?

**Comment by anoopengineer** [comment]
I am one of those people who would like the current behavior to change. Zettlr is absolutely great to edit Markdown and I often see myself awkwardly loading entire Github projects into Zettlr so that I can edit just the README.md file with it. The normal workflow that you would expect - double clicking or right click a file and select "Open with Zettlr" is broken.

Folks have their muscle memories and their age old ways of opening files in their computers and Zettlr comes in an breaks that workflow -- this doesn't help Zettlr in gaining adoption and as @andypea mentioned above, it makes me not recommend it to others and definitely doesn't pass the "mom test".

For a Markdown editor whose motto is "A Markdown Editor for the 21st century", you have build a wonderful theme park for Markdown editing, the absolute best there is. But the gate to the theme park is currently broken and is preventing people from getting in and enjoying the theme park. If i were the CEO of the theme park, I would prioritize fixing the gate first.

**Comment by nathanlesage** [comment]
> double clicking or right click a file and select "Open with Zettlr" is broken.

Now we are talking. Please mention such important bugs, instead of casually dropping them in a by-sentence!! I cannot fix what I don't know.

**Comment by Kangie** [comment]
@anoopengineer That's definitely a bug, probably #1312. You should be able to double click on files associated with Zettlr and have them open! It certainly works for me on Win10 with 1.7.5.

**Comment by anoopengineer** [comment]
Sorry, based on the issue description and the comments so far, it gave me the impression that this was the designed behavior. Glad to know that this is a bug!

I am on arch linux with KDE. I can try to debug this and see what is happening.

**Comment by nathanlesage** [comment]
I just remembered that there were some errors during boot of the latest develop-builds, and I think I found the bug - will take care of that!
