### ISSUE TITLE
Add support for symlinks

### ISSUE THREAD

**Issue by klaus7** [Zettlr/Zettlr#131]
Hello and thanks for zettlr,
I just want to suggest adding support for symlinks as I noticed my symlinks to my markdown files don't get followed. Maybe make it an option in the preferences if a user wants symlinks to be followed?

I've got a quite big directory tree with a lot of markdown files spread in different directories, that's why I wrote a script that will link all these files in one directory for easier access in Zettlr, but unfortunately those links don't seem to be found.

Best regards,
Klaus

**Comment by nathanlesage** [comment]
I'll see into it!

**Comment by samarulmeu** [comment]
This will be a nice feature, indeed. When I'm writing I'm using drafts folders where I temporary copy the piece I'm working on. With symlinks no need for duplicates.

**Comment by nathanlesage** [comment]
Originally, I thought the "Virtual Directories" functionality would provide this, b/c this way you could create symlinks from within the app itself … does anybody use this feature, like, _at all_?

**Comment by samarulmeu** [comment]
I looked a little in the `Virtual Directories` and I did some tests, but somehow it did not appeal to me. It seems that it adds an extra layer (and also a new file - the `.ztr-virtual-directories`) to what a symlink already offers. And, working in Linux, I'm used to use symlinks. 
Maybe you could provide both functionalities for people that find it easier to use Virtual Directories.

**Comment by nathanlesage** [comment]
Yup, it also makes my work easier as I don't have to carve out the Virtual Directories again =D

**Comment by klaus7** [comment]
I've also tried out the virtual directories right now. It's an interesting feature I was not aware of, but at present I find it a little cumbersome to work with. E.g. I cannot right-click on a file and add it to the virtual directory - this again makes it almost impossible in a big directory to add the files to it with just drag'n'drop.

**Comment by nathanlesage** [comment]
This is correct, but I'm afraid I can't clone myself to work double-time on all the features :(

**Comment by CircleCode** [comment]
also, symlinks to folder are ignored too.
Please consider following folder symlinks.

**Comment by RyanGreenup** [comment]
The lack of symlink support is a real shame, I run a bash script to filter out tags concurrently and return the matches as symlinks in another directory like this:

    # Find Tags
     tagval=$(
        for i in $(cat 00TagMatchList); do
            rg --pcre2 --sort-files --no-filename '(?<=[\n\s]#)[a-zA-z]+(?=[\s\n$])' -o $i;
        done | sort -u | fzf)

    # Match to Files
       cat 00TagMatchList | xargs rg ":$tagval:|\s#$tagval\s" -l > 00TagMatchList;
     
    # Return Symlinks
         mkdir 00TagMatch
        rm 00TagMatch/* 
         ln -s $(realpath $(cat 00TagMatchList)) ./00TagMatch
        rm 00TagMatchList
         cd 00TagMatch; 
        sag -f "\s#$tagval" ./

Ideally I'd be able to open that directory in zettlr to go through the files but I can't (this is however supported in [MarkText](https://github.com/marktext/marktext), unfourtunately however Marktext doesn't otherwise support `#tags`.

Tangentially related, is there a way to concurrently filter tags? For example if I wanted all notes related to `#Chocolate` and `#Cake` could I select two tags from the tag cloud? I could just copy and paste from tags I type into the text editor but ideally the tag cloud would filter for occurence (like that script above or Evernote on iOS or [Boostnote v14](https://github.com/BoostIO/Boostnote)

**Comment by nathanlesage** [comment]
With regard to the symlink support, please watch this issue here: https://github.com/Zettlr/Zettlr/issues/392

As soon as this is resolved, symlink support is a think. The major reason why I haven't been able to do this is because the full file layer is currently a sham, and I have to get things straight there!

**Comment by tsbertalan** [comment]
Note--Zettlr does "follow" hardlinks just fine, so that might be a workaround for some. For me, it doesn't work, because many programs will follow the "best practice" of replacing a file entirely instead of writing into it in-place (notionally, to guarantee atomic writes). This means that the links will be broken. Dropbox is one such program.

**Comment by nathanlesage** [comment]
Planned to do that in the FSAL rewrite, but guess what I forgot to add …
