### ISSUE TITLE
The top right corner of the screen, when Zettlr is maximized in Windows, is not part of the "X" hitbox

### ISSUE THREAD

**Issue by BellLongworth** [Zettlr/Zettlr#1314]
## Description

The top right corner of the screen, when Zettlr is maximized in Windows, is not part of the "X" hitbox.

## Reproducing

Bring mouse to the top right of the screen. Left click. Zettlr doesn't close.

## Expected behaviour

Zettlr closes.

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.8.0-alpha

**Comment by nathanlesage** [comment]
It might be because of the hidden Window decorations that there is a 1px margin for the resize handles that native windows don't have?

@tobiasdiez Do you have an idea?

**Comment by tobiasdiez** [comment]
I cannot reproduce it in 1.7.1. @BellLongworth was this bug introduced only in one of the recent versions?

**Comment by nathanlesage** [comment]
Hey, short update: I think I know what you mean. The frameless windows on Windows 10 have a 1px border that is not part of the hit box; and as the buttons in non-native appearance are not part of the window chrome itself but rendered on the webpage this is to be expected due to the nature of how Electron works. Mitigation: Either remember this and click slighly inset, or switch to native appearance which'll re-introduce the native window chrome where you can actually click in the top-right-most corner.
