### ISSUE TITLE
 Package conflict with anther software

### ISSUE THREAD

**Issue by sith-on-mars** [Zettlr/Zettlr#1321]
I was trying to install Zettlr on Fedora 32.

I found that if I installed [Freetube](https://github.com/FreeTubeApp/FreeTube), a FOSS desktop Youtube software using electron, I wasn't able to install Zettlr on my device.  I got this error output in my terminal:

V1.75:
`Error: Transaction test error:`
  `file /usr/lib/.build-id/1b/46d89702261ec7350b37d9c294e9cf30056cec from install of zettlr-1.7.5-1.x86_64 conflicts with file from package freetube-0.8.0-1.x86_64`
  `file /usr/lib/.build-id/3a/c7cba3b980738c950b4f65063d26a2bdea49cd from install of zettlr-1.7.5-1.x86_64 conflicts with file from package freetube-0.8.0-1.x86_64`
  `file /usr/lib/.build-id/46/08cfee8a6c5916de40a1eb9aa8584a12ae65e0 from install of zettlr-1.7.5-1.x86_64 conflicts with file from package freetube-0.8.0-1.x86_64`
  `file /usr/lib/.build-id/65/a1ae27d9027fcf07a6e027c5ed4d3f7d389c54 from install of zettlr-1.7.5-1.x86_64 conflicts with file from package freetube-0.8.0-1.x86_64`
  `file /usr/lib/.build-id/e2/9e37c9cc2e715a24a77b13bee84b4e1e6e06f0 from install of zettlr-1.7.5-1.x86_64 conflicts with file from package freetube-0.8.0-1.x86_64`
  `file /usr/lib/.build-id/ed/11ec403fe639e0d12f9263a7aaa93f8bbf6a6c from install of zettlr-1.7.5-1.x86_64 conflicts with file from package freetube-0.8.0-1.x86_64`

V1.80 alpha1:
`Error: Transaction test error:`
  `file /usr/lib/.build-id/02/24d01b2ebfa2d5f8a42c5749b8a4126308ec95 from install of zettlr-1.8.0_alpha.1-1.x86_64 conflicts with file from package freetube-0.8.0-1.x86_64`
  `file /usr/lib/.build-id/1b/46d89702261ec7350b37d9c294e9cf30056cec from install of zettlr-1.8.0_alpha.1-1.x86_64 conflicts with file from package freetube-0.8.0-1.x86_64`
  `file /usr/lib/.build-id/3a/c7cba3b980738c950b4f65063d26a2bdea49cd from install of zettlr-1.8.0_alpha.1-1.x86_64 conflicts with file from package freetube-0.8.0-1.x86_64`
  `file /usr/lib/.build-id/46/08cfee8a6c5916de40a1eb9aa8584a12ae65e0 from install of zettlr-1.8.0_alpha.1-1.x86_64 conflicts with file from package freetube-0.8.0-1.x86_64`
  `file /usr/lib/.build-id/65/a1ae27d9027fcf07a6e027c5ed4d3f7d389c54 from install of zettlr-1.8.0_alpha.1-1.x86_64 conflicts with file from package freetube-0.8.0-1.x86_64`
  `file /usr/lib/.build-id/e2/9e37c9cc2e715a24a77b13bee84b4e1e6e06f0 from install of zettlr-1.8.0_alpha.1-1.x86_64 conflicts with file from package freetube-0.8.0-1.x86_64`
  `file /usr/lib/.build-id/ed/11ec403fe639e0d12f9263a7aaa93f8bbf6a6c from install of zettlr-1.8.0_alpha.1-1.x86_64 conflicts with file from package freetube-0.8.0-1.x86_64`

Also, I can' install Freetube if Zettlr is installed previously.

What could have cause this package conflict? Could that be an electron version incompatibility? I have also submit a [bug report](https://github.com/FreeTubeApp/FreeTube/issues/569) on the Freetube Github page, if that's helpful for you. Thank you!

**Comment by nathanlesage** [comment]
After some googling, this appears to be a common problem among electron applications, especially if they use different electron versions. Here's what I found:

Apparently, one has to somehow pass an option to fpm during build, so that said directory is omitted and different versions of electron are not compared against themselves.

I don't know how I would set this option in electron-forge, but it seems to be a workaround.

Sources:

- https://github.com/jordansissel/fpm/issues/1503
- https://stackoverflow.com/questions/17582768/how-to-ignore-conflicts-in-rpm-installs
- https://www.google.de/search?client=safari&hl=en-de&ei=pN96X-jkFom-kwXWno-oAQ&q=rpm+package+conflicts+electron&oq=rpm+package+conflicts+electron&gs_lcp=ChNtb2JpbGUtZ3dzLXdpei1zZXJwEAMyBQghEKABOgQIABBHOgYIABAWEB46CAghEBYQHRAeOgQIIRAVUOOjBlifsQZgvbMGaABwAXgAgAGaAYgBpAeSAQM2LjOYAQCgAQHIAQjAAQE&sclient=mobile-gws-wiz-serp
