### ISSUE TITLE
[ENHANCEMENT]: Scrolling when drag-and-dropping images is not sensitive enough.

### ISSUE THREAD

**Issue by Kangie** [Zettlr/Zettlr#1327]
## Description

When drag and dropping images into Zettlr, it is possible to scroll up and down within the file, however it could be easier to trigger this behaviour (e.g. you need to be 'very close' to the top or bottom of the editor pane for this to work)
## Proposed Changes

The scroll 'gutter' at the top and bottom of the editor should be increased in size.
## Caveats

Nil.
## Additional Information

Happy for some discussion on this one, I've just noticed that you have to be *really* close to the top or bottom to get the scroll behaviour to work - I only discovered that it existed by accident!

**Comment by nathanlesage** [comment]
I'm not sure I can tap into that behaviour of CodeMirror, because what you observe is normal scroll-behaviour during drag&drop. The file manager was easy because I can tap into the drag movement, but on CodeMirror idk.

But I'm almost sad that you didn't discover the bug that somehow made its way into the refactored editor that you cannot drag and drop images anywhere but they are inserted precisely where the cursor was BEFORE the movement started :D

**Comment by Kangie** [comment]
> But I'm almost sad that you didn't discover the bug that somehow made its way into the refactored editor that you cannot drag and drop images anywhere but they are inserted precisely where the cursor was BEFORE the movement started :D

I'm not sure what you mean here. Drag and drop seems to put images exactly where I want it to, but I only ever drag from my file manager directly into the editor, and move images around using Cut+Paste within the file!

**Comment by nathanlesage** [comment]
Huh? Then maybe I was inattentive yesterday, I'll be having a look into that 🧐

**Comment by nathanlesage** [comment]
As I still don't see any way of improving this, I'll close the issue. Any PRs are of course welcome!
