### ISSUE TITLE
[ENHANCEMENT / BUG?] Override pre-existing text in global search bar with highlighted text when pressing CTRL+Shift+F

### ISSUE THREAD

**Issue by kyaso** [Zettlr/Zettlr#1346]
## Description

**Current state**: After you searched something globally, the search term(s) remain in the search bar. Now, when you highlight some text in some document, and then press `Cmd/Ctrl+Shift+F` to search globally for it, the content of the search bar will not be updated with the highlighted text. _(Not sure if this behaviour is a bug or not)_

## Proposed Changes

When pressing `Cmd/Ctrl+Shift+F` with some text highlighted, override the content of the global search bar with that of the highlighted text.

## Caveats
I believe none.

## Additional Information
Tested with Zettlr **1.7.5** on Linux Mint 19.2

**Comment by kyaso** [comment]
I quickly implemented a possible solution.

Basically, now, whenever the searchbar is focussed, its content is updated with the first item of the `selections` array (only if the first item is a non-zero string; for some reason the content got cleared whenever I clicked inside the searchbar without having anything highlighted --> So I changed the check from previously checking for the length of the `selections` array, to checking the length of its first element `selections[0]` instead).

**Comment by cdaven** [comment]
I want the same behaviour as default when pressing Cmd/Ctrl+Shift+F, _but_... would a user really expect this behaviour when selecting text in a note, and then clicking the search field with the mouse? I would say no.

It would make more sense to me if the "dir-find" command (triggered by the menu item or the accelerator keys) fetched the selected text from the note and sent it to the search field, instead of the search field's "on focus" event handler looks in the note.

What do you say?
