### ISSUE TITLE
[FEATURE] Don't check for updates on open

### ISSUE THREAD

**Issue by marwahaha** [Zettlr/Zettlr#1349]
## Description
I do not want to check for updates every time I open Zettlr.

## Example Workflow
There is a setting that says "do not check for updates" in the preferences menu.
Then I can check for updates manually when I feel like in the help menu.

**Comment by nathanlesage** [comment]
Update check disabling will not be implemented, due to reasoning I have put elsewhere on this issue tracker. The short version: There will be some users (some = more than I can handle) which will discover bugs using older versions, open issues here and I will have to close those issues as only the newest version is supported. I have already made the update check non-intrusive, and it will ship with 1.8. There will also be an option to disable the update check by providing certain files, I have not yet implemented that but it is only intended for system administrators of bigger departments.

**Comment by marwahaha** [comment]
Ok, thanks. As long as I don't get the notification popup each time, I will be ok.
