### ISSUE TITLE
Enhancement: zettelkasten tree diagrams

### ISSUE THREAD

**Issue by ElectronicTeaCup** [Zettlr/Zettlr#135]
**I want to see is the sequences of notes without having go note by note.** Could it be made possible to either incorporate labeling of new notes so that it makes "branches" from the original note? I can think of alternatives, but can't really see how they could be implemented (I don't know about databases, etc.) 

I may be thinking in a far too analog sense — or perhaps because I could not find the functionality (not in any other program that used .md either). With my current program (not your app) I made files with the following names: "0001","0002","0003","0003a","0004" and suppose I get a new note that relates more to 0002 I add it in with 00021 (so the naming gets a bit funky and I am unsure if it will lead do some kind of database insanity; but it does lie "next to" the note similar to it). 

I like your [method](https://www.youtube.com/watch?v=c5Tst3-zcWI) where you put in the the links ("strong" links) in the initial part of the note and that seems like a perfect multidimensional reference — BUT how do I trace the nodes? From what I see, the search heatmap looks for the number of times a search keyword is found but it won't show me a node connected to a note downstream (i.e through a couple of nodes downstream).

When I am looking at a stream of notes I can type 0003 and I'll get a list of 0003 0003a0001 0003a0002 0003b0001 0003b0002, etc. So I can think of it as a tree diagram. How do *you* do that in your work flow? Jumping from one note/node to another, one at a time, seems difficult and cumbersome.

**Comment by nathanlesage** [comment]
Heya, thanks for the long post!

It's an interesting system that you use, and it actually reminds me a lot of Niklas Luhmann's system. Your note naming methodology resembles quite what he did.

I just found a good post containing a lot of images concerning this approach: https://webaudiotech.com/2017/12/08/luhmann-zettelkasten-ha/

Let's have a look at this image from the article:

![image](https://user-images.githubusercontent.com/17251683/55537556-c6c2b400-56bc-11e9-8da2-c65116322997.png)

This is basically what you are doing currently: You begin with short increasing numbers and add other systematic parts to this naming convention whenever you branch "down" from your main branch. And this is precisely what I criticise in my video. Let's just pose some questions to this method:

1. What justifies the "top" branch of notes to be exactly that — the top branch — except for the fact that they were first?
2. Is it really that new branches must begin at a specific note, or wouldn't they also fit beneath other notes?
3. What about the branches itself? Couldn't it be that these are connected in some part themselves?

Why Luhmann used such a branching structure was, as I explained, a result of him not having computers. He had to somehow "mock" a computer database, and, for his time, this was revolutionary. But nowadays we not only have more sophisticated databases, but also powerful computers able to perform real-time searches. And I think another way should be possible. So here's how I think of a Zettelkasten, which is precisely what's possible in Zettlr (except, of course, a lot of work still has to be done concerning the functionality, especially the search):

---

The core content of every Zettelkasten is the content of the notes. Whenever you have a thought or want to write down a quote, this is what's important. And when we think originating from the content instead of focusing on the systematic we use to arrange this content, we clearly see what kinds of problems a tree-based method runs into:

1. There really is no justification in having one branch of notes at the top, because whenever your research focus shifts, another branch needs to be at the top. With such a rigid naming convention, this is only really hard to achieve, and the Zettelkasten therefore is only capable of telling you things following the "hard" paths you introduce using such a convention.
2. Every note can be related to an infinite number of other notes. When you have one note on the stimulating effects of coffee, and then another one containing a statistic of global coffee consumption, that second note could also very well be related to yet another one containing cultural practices containing coffee. There's really no use in hierarchy if we focus on the content.
3. Applying the answer to question 2 to question 3, we can see that instead of thinking of Zettelkästen as trees, we should be using a concept introduced in the philosophy of knowledge by Gilles Deleuze and Félix Guattari: [the **rhizom**](https://en.wikipedia.org/wiki/Rhizome_(philosophy)).

![image](https://user-images.githubusercontent.com/17251683/55538989-ec04f180-56bf-11e9-99af-7da6743dc515.png)

A rhizom is basically the counterpart for the tree's branches: the root system. The core difference is that instead of having that one note named "0001", you name them as you like, because the name does not contain any structure. Think of it this way: If you have such a hierarchic structure of notes, even if you have global full text search and thereby find a note somewhere in this branch system, you are more than likely to — from this note on — traverse the branches as they were laid out by you. But the problem is: If you thought at the time of the creation of the notes "Oh, this note fits to that other note!", then this is a hard link. Because whenever you find a note on that branch, this branch is unable to change dynamically and you're prone to follow this branch instead of finding new paths.

Instead, using Tags and purely linguistic differences (e.g., the proximity of similar words, the amount of words) to generate such proximity/distance-relationships each time you search the notes, the whole link-system will always be generated anew, depending on what has happened to the Zettelkasten in the meantime. For instance, if you think "alright, I have this note here, and it fits perfectly to another note I made some time ago, so I'll link them here", then you create a hard link, but you are not limited to only one — you can create gigantic lists of "hard links". And — given a proper search algorithm (which I still have to develop) — it could take into account these links and indeed display a list of notes during global search where the first note is the "core" of what you were searching for, and all other notes are basically concentrically ordered around this note, so you can choose any of these notes as your entry point, and _then_ you can traverse the Zettelkasten without using search. But you'll still be able to traverse a network instead of a tree, because you can create as many hard links between notes as you like, and you'll never have a note that is rigidly placed between two different notes.

---

I hope I did a better job at explaining this using these images 🙈 If you have any further questions, please ask!

**Comment by nathanlesage** [comment]
Oh, and to answer your implicit question from the issue title: Based on what I've argued I strongly advise _against_ visualising such trees.

**Comment by ElectronicTeaCup** [comment]
I fully agree with the difficulties you've posited with Luhmann's system. I really liked the Rhizome concept, and better understand the problem of a hierarchical system enforcing context to its components. Thanks a lot for the elaborate explanation.

My interest in the zettelkasten  was piqued, primarily, because of the idea of context free knowledge. I often make a lot of notes in my books, and then make outlines in the empty pages in the book but had problems pulling out arguments when not in the context of the book. Often, as you know, arguments seem very sound in a particular context or when coming from a sequence of other arguments. So I definitely aim towards removing context/bias. 

In turn, I can enforce context in a single note by building an argument from multiple notes from the zettelkasten. This way I have a single note as an overview note connecting all these notes in a particular sequence, without biasing the system. When sequence is unimportant, tags would unite the notes.

I agree with your idea on how the search options will really enhance the Zettenkasten.

>  And — given a proper search algorithm (which I still have to develop) — it could take into account these links and indeed display a list of notes during global search where the first note is the "core" of what you were searching for, and all other notes are basically concentrically ordered around this note, so you can choose any of these notes as your entry point, and then you can traverse the Zettelkasten without using search

That would be extraordinary!

But if tags and other implicit components are responsible for encoding proximity, then from the users side —  tagging has to be used more efficiently, correct? I read that Luhmann only used 1-2 "tags" which he indexed. But now tags will more central when searching for similar ideas, so more tags should be used right?

**Comment by nathanlesage** [comment]
>  Often, as you know, arguments seem very sound in a particular context or when coming from a sequence of other arguments. So I definitely aim towards removing context/bias.

Plus this way you can automatically rearrange several thoughts, and purposedly rip them out of context for this!

> This way I have a single note as an overview note connecting all these notes in a particular sequence, without biasing the system. When sequence is unimportant, tags would unite the notes.

Precisely! Plus, tags would be the most efficient thing you could do, because through them you would automatically create connections between notes that you're not aware of unless you search for a specific combination of tags. This is why tags are so powerful — you simply say "This note belongs to the general concept of \#coffee!", for instance, and then when you have the note on coffee culture, you'd find both notes when searching for this tag. But when you are searching for, for instance \#society (or something that you've tagged the coffee culture note with), you wouldn't find the statistics on coffee, but you would find — for instance — sociological concepts or something like that. The connections, therefore, are created dynamically only through searches, and would be broken up again as soon as you close the search.

> That would be extraordinary!

Thanks, let's hope I get to rewriting the search engine sooner than later!

> But now tags will more central when searching for similar ideas, so more tags should be used right?

On point! I mean the concept of "tags" simply didn't exist prior to twitter; even most blog systems was using categories way more frequently until a short time ago, so we have to "re-educate" ourselves to some extend. Even I am still struggling with a way to correctly tag, but it's coming about!

**Comment by ElectronicTeaCup** [comment]
True, I've never really understood how powerful tags could before. Thanks for the insight— the app works really well in this framework. Fingers crossed for the super search engine. Keep up the excellent work!

**Issue closed on philosophical grounds of app usage.**

**Comment by nathanlesage** [comment]
This must be the most sophisticated reason an issue has ever been closed on GitHub ❤️
