### ISSUE TITLE
HTML5 Export - Renders equations in the middle

### ISSUE THREAD

**Issue by stefnotch** [Zettlr/Zettlr#1360]
## Description
Not sure if this is intentional, but the HTML5 export renders mathematical equations in the middle. Meanwhile, in Zettlr, they are left-aligned.

## Reproducing
```md
**Induction step**
$$
\begin{aligned}
P(n+1) &= 7^{n+1}-1 \\
&=7^1 \cdot 7^n-1 \\
&=7(7^n-1) + 6 \\

&=7(6x) + 6 \\
&=7 \cdot 6x + 6 \\
&=6 (7x+1) \\
& \Box \\
& 
\end{aligned}
$$
Also $3 \in \N$
```

![image](https://user-images.githubusercontent.com/10220080/96444988-7dd73f80-120f-11eb-86a7-b667a35d0e55.png)

## Expected behaviour
![image](https://user-images.githubusercontent.com/10220080/96444975-7879f500-120f-11eb-99d4-e77ac4fc7c00.png)

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.8.0-alpha.2

**Comment by nathanlesage** [comment]
In Zettlr they need to be aligned left due to CodeMirror's way of handling inline widgets, but in HTML they render "correctly" (centered). Please do not forget that Zettlr's preview is only that: the preview. I don't particularly see why this is overly distracting (as the editable code will always be left-aligned, so having the render close to the source code is better than if the render would "jump"  into the middle) … do you concur, or do you have a suggestion?

**Comment by stefnotch** [comment]
So it is intentional, good to know.

I suppose a suggestion would be to make it possible to add CSS to the HTML5 export? (I suppose adding a style tag works for now https://github.com/Zettlr/Zettlr/issues/1363#issuecomment-712208230 )
