### ISSUE TITLE
Display Math seems broken – in Editor and HTML Export

### ISSUE THREAD

**Issue by kellertuer** [Zettlr/Zettlr#1379]
## Description

Thanks for providing this nice note taking tool. Lately I stumbled upon a strange error with Displayed math formulae: Let's say I want to display this solid formulae

```
\begin{split}
    \text{Minimize } \quad& f(x) \text{ over } x \in\mathcal M\\
    \text{ such that } \quad & g(x) \leq 0,\\
      \text{ and } \quad & h(x) = 0,
\end{split}
```

In Markdown and MathJax or classic LaTeX one would enclose these either in `\[` and `\]` or `\begin{equation*}`and `\end{equation*}`– in old (discouraged) LaTeX in `$$` which might sometimes be used in Markdown and is documented to be used by Zettlr.

The first two methods to not gain any markup, the $$ is rendered in the editor as code but not as a math formula, but only in red text.
The first two methods just print nothing on HTML output, the last just plain the test including the `$$`.

## Reproducing

Copy above code and add one pair of the three mentioned delimiters

## Expected behaviour

Copying that same code (without delimiters) into a MathJax renderer yields for example [this](https://arachnoid.com/latex/?equ=%5Cbegin%7Bsplit%7D%0A%20%20%20%20%5Ctext%7BMinimize%20%7D%20%5Cquad%26%20f(x)%20%5Ctext%7B%20over%20%7D%20x%20%5Cin%5Cmathcal%20M%5C%5C%0A%20%20%20%20%5Ctext%7B%20such%20that%20%7D%20%5Cquad%20%26%20g(x)%20%5Cleq%200%2C%5C%5C%0A%20%20%20%20%20%20%5Ctext%7B%20and%20%7D%20%5Cquad%20%26%20h(x)%20%3D%200%2C%0A%5Cend%7Bsplit%7D)

## Platform
 - OS and version: Mac OS Catalina 10.15.7
 - Zettlr Version: 1.7.5

**Comment by nathanlesage** [comment]
You mention that you attempt to use HTML output. HTML is also supported without having Pandoc installed. Does this possibly mean that you decided not to install Pandoc (for instance because you only need HTML export either way)? If so: the built-in showdown exporter is by no means as powerful as Pandoc and, among others, does not support Math equations.

If this is not the case and Zettlr exports using pandoc, would you mind to help solve this issue by attempting the following and report your results?

- Test it in the latest release (the first beta at time of writing, see the releases section here on GitHub)
- attempt to use Pandoc directly for exporting HTML
- Looking into the dev console if an error is thrown (again in the newest version; the console opens by first enabling debug mode in the preferences, and then choosing, from the menu, Develop -> Toggle dev tools)

That would be great!

**Comment by kellertuer** [comment]
Thanks for the quick answer. I actually have Pandoc installed. How can I test whether the panic export is used?

I will surely give 1.8 a try then.

**Comment by nathanlesage** [comment]
Thank you for trying these things out quickly; so it seems there is something off with the parsing process. I will have a look, but don't let that stop you from also looking for clues!

**Comment by kellertuer** [comment]
Thanks, one thing that I noticed is when I do
````
>> pandoc in.md -o out.html
````
I get 
````
[WARNING] Could not convert TeX math '
  \begin{split}
      \text{Minimize } \quad& f(x) \text{ over } x \in\mathcal M\\
      \text{ such that } \quad & g(x) \leq 0,\\
        \text{ and } \quad & h(x) = 0,
  \end{split}
  ', rendering as TeX
````
(and for sure a completely broken TeX. When I use `\begin{equation}` from the options above and do
````
pandoc in.md -s --mathjax -o out.html
````
works fine.

**Comment by nathanlesage** [comment]
Ah I see.

So, do I understand you right that there are exactly two ways to demarcate a MathJax-equation: the \begin-blocks and the \\[-delimiter? Are there any possible variations? Because, I mean, if I know exactly how these are demarcated, I (or someone else) could add this option to the Math renderer and therefore enable those as well?

**Comment by kellertuer** [comment]
I think there are even more ways.
As far as I saw
1. `$$` seems to be allowed in Markdown (is for example written in the pandoc documentation), but it is for example no recommended LaTeX
2. Both `\[` and `\begin{equation*}`and their counterparts are valid in the default settings of MathJax
3. `\begin{equation}` might be used but depending on the setting might yield a numbered equation

The second two are equivalent in LaTeX and the current recommended way to do displayed formula (unnumbered) and the third of course yields a numbered formula.

Sometimes `\begin{split}` and `\begin{align)' are also valid most outer environments in MathJax, but in LaTeX these have to be put into the environments in 2. (MathJax would just add `\[`, `\]` on the outer). These environments are used to split a formula intomultiple lines (like mine) or to align multiple formulae.

I think due to 2. MathJax just handles that file well when doing the Pandoc MathJax stuff. That was what actually surprised me, that the export did not work. If even the rendering would work – wow, that would be really nice.
