### ISSUE TITLE
Tabs do not close or swithc when many are open

### ISSUE THREAD

**Issue by gabrielrudas** [Zettlr/Zettlr#1383]
## Description

When more tah 15 files are open, close button stops working. When re-launhing app. The only tab that closes is the current file tab.

## Reproducing

- Use File Manager bar to navigate different files. 
- Modify each file, so when clicking in a different file it is open as new tab (instead of replacing current tab)
- Repeat this 15 times
- Try to close a tab (different from the current file tab)
-Does not work
-Try to switch file displayed by clicking in a tab
- Does not work
- Trying to switch file displayed by clicking in File Manager Bar
- Does not work

## Expected behaviour

Allow to close tabs and switch files displayed after 15 open tabs.

## Platform
 - OS and version: Mac OS 10.14.6
 - Zettlr Version: 18.0-beta

**Comment by RedDocMD** [comment]
I tried to reproduce this bug on Ubuntu 20.04 on the current develop branch (current as of my writing).
The bug did **not** reproduce. In fact, I can open as many as 26 tabs with no problem.
I believe this may be a RAM issue, since  Zettlr is quite RAM intensive, like any other Electron app.
@gabrielrudas, can you please mention what is the model of your  MacBook and how much RAM do you  have.
Also, @nathanlesage, I guess you could reproduce the problem since it is flagged as bug. Which OS do you use?

**Comment by nathanlesage** [comment]
@RedDocMD No, if I were able to reproduce it, I would've added the "confirmed" label!
