### ISSUE TITLE
Zettlr loses configuration and opened files/directories after OS reboot

### ISSUE THREAD

**Issue by FacundoAcevedo** [Zettlr/Zettlr#1384]
## Description
I've noticed zettlr loses config ( for example Dark mode and Theme) and doesn't open last opened directory after rebooting my OS,
whithout rebooiting If I close and open zettlr it's fine, it load averything ok.

## Reproducing
1. Open zettlr, set some config and open a directory.
1. Reboot
1. Open zettler ( all config is lost)

## Expected behaviour
After reboot zettlr load last configuration.

## Platform
 - OS and version: Fedora 32 workstation ( running on X-session)
 - Zettlr Version: 1.7.5

**Comment by nathanlesage** [comment]
Could it be that you happen to have some security mechanisms that clean out certain directories? Because if everything works fine even between reboots of the app without any problem, this indicates that the config file is being written successfully, but removed on reboot of the system. Would you mind checking the `config.json` for me?

The path should be:  `/home/<your username>/.config/zettlr/`

**Comment by FacundoAcevedo** [comment]
Hope you doing well,

I am not aware of any security mechanism in my system deleting  `.config/*` files. It's a vanilla Fedora installation. It's happening only with zettlr here.

I have checked `config.json`, it's there and filled with data. Btw I've killed zettlr with `kill -9` to emulate a violent shutdown but the config file stills there :p  

What I have noticed is that if I change the theme, pick on __save__ and `cat ~/.config/zettlr/config.json`, it keeps showing the previous theme, if I close the app it saves the new config. I can't assure if have never closed zettler before rebooting XD.

To clarify what I've said before:
* If I set up a theme, it's not save to config until I close zettlr
* If i set up a theme and kill -9 ( even after click on save )  config is not saved

**Comment by nathanlesage** [comment]
Ah alright, now I understand. This is wanted behaviour as this way it is ensured that always a working configuration is saved -- in case some config options don't go well together, this way we ensure that after killing the app it works again! This is necessary because not only simple config parameters are saved there but also some more things, and it's easier to maintain this way. So to actually save the config, always make sure to close Zettlr normally 👌🏼
