### ISSUE TITLE
Environment CSLReferences undefined on Pandoc 2.11

### ISSUE THREAD

**Issue by Doctorados** [Zettlr/Zettlr#1414]
When exporting a document to PDF the following error is thrown:
`! LaTeX Error: Environment CSLReferences undefined.`

OS is Manjaro KDE 20.2 with Zettlr 1.7.5.3 and Pandoc 2.11-5.

This is caused by Line 166 in Zettlr's default TeX template: `\newenvironment{cslreferences}%`
changing this line to `\newenvironment{CSLReferences}%` fixes the issue.

The default Pandoc template also uses `\newenvironment{CSLReferences}` since Version 2.11 [See Commit](https://github.com/jgm/pandoc-templates/commit/9904bf716a276cc927280cf1e1e7b7d8e661ca75#diff-f218051b4ca8f740a9f585a149101d4a3025037c568b391b5216edf7b14cfadc)

The default template should probably be changed accordingly.

**Comment by hildebrand-institute** [comment]
Well, in fact once the suggested correction is applied it compiles without errors, but finally the bibliography does not appear, because references are not resolved... Is it another new pandoc issue? Till now using Zettlr and pandoc I never had to compile multiple times like while directly using LaTeX...

See attached pic.
![cls](https://user-images.githubusercontent.com/57742994/98448907-d3787b00-212f-11eb-8e0a-58036e30f1a9.png)

**Comment by nathanlesage** [comment]
Pandoc 2.11 does not yet work with Zettlr. Before I am able to implement a fix, please downgrade to at most Pandoc 2.10. I am sorry for the inconvenience, but I will get to this eventually.
