### ISSUE TITLE
[1.8.0.beta2] Only one window available in Windows

### ISSUE THREAD

**Issue by mattwien** [Zettlr/Zettlr#1417]
## Description
After installing the beta, when I use Zettlr it only opens one file. As soon as I open an other file the current window is replaced with the new window. I'm not able any more to switch between mutliple files.

## Reproducing
Start Zettlr, open a new or existing file, click in file manager or on a link to open an other file.
The previous file is closed.

## Expected behaviour
Multiple windows that can be used and switched between - as in the previous version

## Platform
Zettlr Version: 1.8.0-beta.2
System: win32 10.0.19041 (architecture: x64)

**Comment by nathanlesage** [comment]
I do not understand what you refer to – the tabs in the main window's editor? The quicklook windows? Please be more specific, so I can help you.

**Comment by mattwien** [comment]
Sorry for my imprecise terminology- should have added a screenshot. I refer to the tabs. In the meantime I found or that when I click in the files section with CTRL Shift on a file a new tab is opened (I preferred the old Behavior- always opening a new tab)- but a [[- link always open in the same Tab.

I haven't found out how the quicklook window can be used or opened.

Additional issue: when right clicking a tab and selecting rename an empty rename box appears - but when using the rename pen above the tabs, the original name can be modified.

**Comment by nathanlesage** [comment]
Is the title of the tab italic? If so, this simply means that you stumble upon the transient file behaviour. To make tabs "sticky", double-click on the tab, so that the title is not italic anymore. Then, it works as expected. I will be adding more features for making non-transitive tabs easier such as double-clicking a file in the file manager.

Quicklook windows can be opened using right-click or by holding down Alt on a file in the file manager.

With regard to the renaming window, I'll have a look, but that's a different issue.

**Comment by mattwien** [comment]
As in most situations the problem was just 30cm in front of the screen... 😉

Thank you for the explanation- is was guessing that it was some kind of wrong usage on my side. Might be helpful to have these features also in the right click  context menu - incl the shortcut info- might make it easier for people to learn?

**Comment by nathanlesage** [comment]
> As in most situations the problem was just 30cm in front of the screen... 😉

Don't worry, as this is one of those cool features that need to actually be explained because it's not really intuitive!

> Might be helpful to have these features also in the right click context menu - incl the shortcut info- might make it easier for people to learn?

Absolutely, but it does take time, and the current implementation is still not that stable :S But I will be adding more and more improvements – if you yourself have a good idea where something concrete should happen, please feel free to even implement it and open a PR! :)
