### ISSUE TITLE
[ENHANCEMENT] Using LanguageTool for spell and grammer checking

### ISSUE THREAD

**Issue by cavemanr** [Zettlr/Zettlr#1426]
It would be nice if Zettlr used LanguageTool for spelling and grammar checking.

The problem with a built-in directory is that my personal dictionary, which I created in LanguageTool, is not available in Zettlr. So I have to keep my user dictionary multiple times.

**Comment by jdittrich** [comment]
See also
* [#696, SpellCheck Grammalecte and Antidote](https://github.com/Zettlr/Zettlr/issues/696)
* [#1022, New Dictionary/Spellchecking Mechanism ](https://github.com/Zettlr/Zettlr/issues/1022)

**Comment by AimVaguely** [comment]
This feature would add a lot to this application to me, as well as probably a lot of other people. The interface and editor itself is really nice, but the language checking could still be better. I believe this would be the best way to go about improving this problem. 

This would have a extra bonus of possibly fixing #1022 to a very usable point since [LanguageTool has support for a range of languages](https://dev.languagetool.org/languages). This will also possibly delegate a lot of the requirement for the dictionary support and language support (specifically with the editing, the interface will still have to be translated I guess) with only having to maintain the communication layer between LanguageTool and Zettlr (which sounds like a significant decrease in work in the long run). 

This would have the negative of adding a dependency on java, but it can be done as an optional dependency and fall back on existing dictionary support if it is not there, [or you could use the online API for LanguageTool as an option](https://dev.languagetool.org/public-http-api) (probably disabled unless checked, because this has a fair amount of restrictions and should have a disclaimer on where it is sending all your data). This is how [manuskript](https://github.com/olivierkes/manuskript) did it (minus the public API use), [LibreOffice](https://www.libreoffice.org/) also [does it as an extension](https://languagetool.org/libre-office)

**Comment by YetAnotherAccount5345f** [comment]
LanguageTool brings so much to the table that it would lift Zettlr several miles above the ground.

At the moment, I copy and paste every chapter back and forth into their standalone application. The spellchecker that comes with Zettlr just hinders your workflow more than it should help. But that problem has every other similar tool that does not use a solid spellchecker.

Really looking forward to that feature. Awesome software so far.

**Comment by nathanlesage** [comment]
@YetAnotherAccount5345f See issue #2988. Once that is merged, all of these tools become possible!
