### ISSUE TITLE
Too many file watchers

### ISSUE THREAD

**Issue by TriciaHampton** [Zettlr/Zettlr#143]
It would be awesome for me to be able to open my complete home directory at once, but unfortunately there seem to be too many files or directories. The following error occurs:  
https://i.imgur.com/AjMZfSC.png

An option to configure some exclude patterns by hand would be helpful.

**Comment by nathanlesage** [comment]
Puhhh… we've had these problems a lot in the initial phase of development over a year ago, when many people tried to open `C:\` or `/home/user`. I personally would say that it's rather unconventional to read in _your complete home directory_. I'm always asking: Why should anybody want to do this ...?

If you have any folders that exist on many computers that definitely shouldn't be read (such as .app-folders containing a macOS application or hidden ones starting with a dot), please let me know so that I can add them to the internal ignore pattern ... but I would strongly advise against reading in your full home folder.

Zettlr is designed that you have one big "overarching" folder containing all of your Markdown files, but no, e.g. images etc. This is also good practice because it clearly divides all your different work packages visually on your disk.

**Comment by TriciaHampton** [comment]
Yeah, I think you are right.

The problem is, I have some markdown files lying in the top levels of my home directory, which I want to keep at these locations for documentation purposes. Adding patterns or paths for inner directories to exclude would solve my problem, but of course they are specific to my system. But it is ok anyways, since I do not need to edit these files often.

Still I would recommend to improve handling of that exception. As it is now, restarting the app provokes throwing lots of these exceptions again. Perhaps cancelling the complete open task with a short info message would be cleaner here. But this is also not critical.

Keep up the good work!

**Comment by nathanlesage** [comment]
I have a good idea concerning your few files on the top level:

![image](https://user-images.githubusercontent.com/17251683/56018215-c8fec100-5d01-11e9-8452-953fb54db038.png)

As you can see, there are three standalone files open (i.e. files that are not somewhere in the directories). I use them sometimes, but not very often. But this way I have them open without needing to pull in all of the home directory!

And concerning the error: Well, I need to get to the mechanics behind reading in the files and folders anyway, because currently there's a significant lack in opening 10.000+ files. Zettlr works smooth afterwards, but opening them takes some time. Maybe the error resolves itself after I've rewritten that logic :)

**Comment by TriciaHampton** [comment]
I can't seem to find the menu entry to open a file standalone. When I click on 'File - Open', I am prompted to open a directory, not a file. When I use 'Import files' the app complains about wrong filetypes (for both txt and md files). Would be glad about a hint :)

**Comment by nathanlesage** [comment]
Ah, yes. The "Open...." dialog is meant for directories only, because you can't open them with an app by double-clicking them. The "Import" function is meant to import non-markdown files and convert them to markdown (i.e. docx -> markdown and then into a folder). So to open standalone files, either double-click them in your Finder/Explorer/file browser, Zettlr registers itself as an app capable of opening .md-files. You can also drag them over the app, this will also work!
