### ISSUE TITLE
No display for v.1.8.0.beta4 on Windows 10

### ISSUE THREAD

**Issue by whytong** [Zettlr/Zettlr#1449]
## Description
The display of the content is blank. Exported file (tried Word) is OK.

## Reproducing
Uninstalled and reinstalled, same result.

## Expected behaviour
![image](https://user-images.githubusercontent.com/54590532/100404541-a5e86880-302f-11eb-8fac-c80197dcf266.png)

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.8.0 beta.-4

## Additional information
Was using v.1.7.5. and was fine.

**Comment by nathanlesage** [comment]
Would you mind checking the logs for me?

Here's how you find the logs:

1. Ensure the "debug mode" is active (Preferences -> Advanced -> Debug mode)
2. In the "Develop"-menu item, choose "Open Logs"
3. A new window will appear which contains all logs since the start of Zettlr. The logs will be updated regularly.

The logs themselves are color-coded:

- Grey is a debug message indicating a normal process within the app (useful to correlate your actions to processes within the application)
- Blue is an informative message, mostly indicating internal switches
- Yellow is a warning message indicating that something might be off
- Red is an error message indicating that a process has failed to execute correctly.

**Comment by whytong** [comment]
Sorry I don't know how to export the log, neither could I find the exported log so here is the screen copy. No Yellow/Red msg.
![image](https://user-images.githubusercontent.com/54590532/100466085-568d5100-309e-11eb-94cc-4648fb494a1f.png)

**Comment by whytong** [comment]
Just tried it on the new release v.1.8.0, same issue, including the same JavaScript error.

**Comment by nathanlesage** [comment]
Quick update, I just looked up the position of said error (line 101, char 26,066) and found this:

![image](https://user-images.githubusercontent.com/17251683/100477713-74cc6e80-30e9-11eb-805e-02a3d476ef3f.png)

This means that, due to some reason, the "inspect-element" command is being processed with no coordinates given. This seems very, very odd.

I would suggest that maybe a quick clean-up of your application data directory (`C:\Users\<your username>\AppData\Roaming\zettlr`) would help:

1. First ensure that the application is closed (in some error cases, there is a "zombie" process, which you can close from within your Task Manager or Activity Monitor)
2. Make sure to optionally backup these files:
    - `stats.json` (your writing statistics)
    - `config.json` (the app settings)
    - `custom.css` (your custom CSS, if any)
    - `tags.json` (your colour-coded tags)
    - `targets.json` (your writing targets)
    - `user.dic` (your own custom dictionary)
3. For informative purposes, it might also make sense to backup the `logs`-folder, which contains logs from the application.
4. Select everything in this directory and delete it.
5. Restart the application. Some of these files will be re-created.

**Comment by whytong** [comment]
Thank you. This solves the problem. 

It seems the ```config.json``` is the culprit. When I put the old ```config.json``` back to the application data folder, the display issue re-occurs.

In case you are interested in finding out, the bad config.json file is attached.
[config.json.txt](https://github.com/Zettlr/Zettlr/files/5609485/config.json.txt)

**Comment by nathanlesage** [comment]
@whytong Thank you for providing the config.json! I could not immediately spot anything off with it, but it is indeed curious. I'll be closing this issue, but now that I know there's something off, I'll be keeping this in mind and hopefully come to an answer some day.
