### ISSUE TITLE
Zettlr resets upon restart on Apple Silicon under Rosetta 2

### ISSUE THREAD

**Issue by hubertau** [Zettlr/Zettlr#1456]
## Description

Zettlr seems to reset when quitting and restarting the application on Apple Silicon machines, both in displaying no open files/folders and any settings (e.g. Zotero file library path, custom pandoc export commands).

## Reproducing

Any quitting and restarting of the Zettlr app (running under Rosetta 2, of course)

## Expected behaviour

Retain open files and preferences.

## Platform
 - OS and version: MacOS Big Sur 11.0.1
 - Zettlr Version: 1.8.0

## Additional information

Happy to provide more information/test!

**Comment by nathanlesage** [comment]
Might be because Rosetta 2 sandboxes the app, I don't know, but Zettlr will be supporting M1 chips natively from one of the next releases on. I won't do anything to make Rosetta 2 work; as soon as Electron 11 ships, then please feel free to report any bugs if there should be any (but please make sure to distinguish between Zettlr bugs and Electron bugs and report the latter directly to Electron; I figure there will be some :)

**Comment by hubertau** [comment]
Okay! Thank you for the quick update :)
