### ISSUE TITLE
[Feature] Support mermaid

### ISSUE THREAD

**Issue by jlnbdt** [Zettlr/Zettlr#147]
Hi,

[mermaid](https://github.com/knsv/mermaid) is a very convenient way to draw graphs into a markdown file. It could be very nice if Zettlr supported it (like Typora or Notable).

Thanks :-)

**Comment by myn-user** [comment]
Hi,

yes, please integrate mermaids.

**Comment by StoltHD** [comment]
or Markvis and get 3d.js functionality

**Comment by jrcharney** [comment]
It's been a while since I've used Zettlr myself. Mainly because I've been using Typora for a little while.

The four most outstanding features it has is
1. (Partial) emoji support. (It doesn't have all of them)
2. When you type `[toc]`, a table of contents is generated based on the headings.
3. Horizontal Rules are created with three dashes! (I think I've said something about this before. It's also part of Github Flavored Markup)
4. Mermaid (but not the most updated version since it doesn't underline static functions or italicize abstract functions in class diagrams.) (To make it better, Mermaid needs to have underlined properties too!)

Mermaid is a **MUST HAVE**!  Considering most of the other features of Zettlr appear to be Node based, and Mermaid.js is available as a node module, let's kick of 2020 with a new feature!

**Comment by nathanlesage** [comment]
Hey, yeah, I get that Mermaid is increasingly popular, so don't worry!

Concerning the other points you make:

1. I'm pretty sure you use Windows? Because macOS and, with add-ons, Linux, have native Emoji-picker. I'm not quite sure if Emojis are _that_ necessary for text editors …? (Besides: With AutoCorrect you can add all Emojis that you need, so this is not true anymore since 1.5 ;)
2. Something that could be asked using a different issue, not within here.
3. … which also applies to Zettlr? I mean, I don't quite get your point?

**Comment by alerque** [comment]
@jrcharney A quick note re your number 3 — exactly three dashes is also the separator used to delineate YAML meta data blocks inside Markdown (and stand alone) when on a line my themselves. This syntax is used by Pandoc and many other tools, horizontal rules must use at least 4 dashes to not conflict with this. Also three dashes is used by LaTeX as a way to enter em-dashes and many Markdown parsers with smart typography extensions use this convention as well. All that to say that HRs should require 4 or more, and trying to support 3 would open up mine fields of conflicts.

**Comment by jrcharney** [comment]
> @jrcharney A quick note re your number 3 — exactly three dashes is also the separator used to delineate YAML meta data blocks inside Markdown (and stand alone) when on a line my themselves. This syntax is used by Pandoc and many other tools, horizontal rules must use at least 4 dashes to not conflict with this. Also three dashes is used by LaTeX as a way to enter em-dashes and many Markdown parsers with smart typography extensions use this convention as well. All that to say that HRs should require 4 or more, and trying to support 3 would open up mine fields of conflicts.

That doesn't seem to be an issue on Typora, even more so since I'm not using YAML metadata at the beginning. The YAML Code block should kick in ONLY  if the FIRST LINE is three dashes. The codeblock closes upon the next line that is online three dashes. For all other cases, three dashes acts as an HR.

em-dash conversion should be optional. Especially if I wanted to inline something like `x--` or `--x` as part of a inline code block describing a decrement in C, C++, Java or some other language that uses those operators. Basically, some refinement of the rules would be good.

I would think that em-dash conversion would occur if a word (which may or may not be part of an inline code or inline LaTeX), not separated by spaces had two or three dashes next to it, followed by another word (which may or may not be part of inline code or inline LaTeX would) would then process the appropriate hyphenation. If there are any spaces in front or behind this sequence, the conversion doesn't happen. The only exception of this conversion would be if the dashes were inside of a code block.

I didn't think that would cause too much of a conflict, but if you feel like that could be problematic then I guess we can table that matter. Especially since I didn't want this thread to be about the first three points but the forth one: **MERMAID!**   (My apologies to @nathanlesage if it seemed like I was threadjacking an issue. I will ask about those other things in different issues, especially since I really like that second point, which is from some other node module whose name escapes me at the moment.)

But Mermaid is a total must have!  I wish I had it back when I was in college. So many UML Class Diagrams, Sequence Diagrams, and Gantt Charts would have be generated.

**Comment by nathanlesage** [comment]
I think we got it that Mermaid is definitely a wanted feature^^

**Comment by jrcharney** [comment]
I was wondering, because I was checking the previous issues first to see if someone else metioned that.

BTW, I'm moving all the em-dash/HR/YAML talk to another thread so it doesn't seem like we're getting off topic.

**Comment by nathanlesage** [comment]
Okay, I just had a look at the mermaid package on npm, and wtf, it would add 40 megabytes in size to the binary. I will NOT increase the size of the already way too big binary from 220 to 260 megabytes just for one single component.

So if anybody knows of a "lightweight" version of mermaid, I'd be happy to explore that option instead. The only thing I'd like is a library that takes mermaid code and transforms it into an SVG image. As soon as I have an SVG image I can take it from there. I do neither need PNG transformation options (which do tend to bloat packages), nor any other graphical stuff. For this I can use native Electron stuff, hence stuff that's already shipped.

**Comment by jrcharney** [comment]
> Okay, I just had a look at the mermaid package on npm, and wtf, it would add 40 megabytes in size to the binary. I will NOT increase the size of the already way too big binary from 220 to 260 megabytes just for one single component.

Hmm...didn't think mermaid would be more like a ["chubby mermaid"](https://www.youtube.com/watch?v=OSXpWrVmPxM). Of course, I remember the days where programs were measured in kilobytes rather than megabytes or gigabytes. Not to mention that meme where `node_module` weight [is compared to that of celestial objects](https://twitter.com/linuswillner/status/855011967534235648). I didn't know Zettlr was trying to aim toward being lithe.

To that end, you've already got an app that is over 200 MB in a word where hard drives and flash storage are being sold by the gigabyte and terabyte and the costs of buying more space to stuff is relatively affordable even on a fixed income.

On the other hand, think of all the new features adding this package would add to Zettlr.

Maybe it would be wise to sit on this feature for the moment until after making something like a [cost-benefit analysis](https://en.wikipedia.org/wiki/Cost%E2%80%93benefit_analysis) to see what would be the return of investment would be for including such a feature.

So far, I've manage to enjoy using mermaid in another markdown editor to make sequence diagrams, flow charts, and class diagrams in my notes for a class I am taking. So this "chubby mermaid" seems to be worth the effort from a user's perspective.

**Comment by nathanlesage** [comment]
> Hmm...didn't think mermaid would be more like a "chubby mermaid".

lol

> Not to mention that meme where node_module weight is compared to that of celestial objects.

Well … it's not *that* inaccurate …

![image](https://user-images.githubusercontent.com/17251683/73482868-cbb8c880-439e-11ea-85c0-42f1fe37153b.png)

> To that end, you've already got an app that is over 200 MB

Chubby Electron fwiw ¯\\\_(ツ)\_/¯ 

Well, I mean I see your point. Arguing about 40 megs is not that hard when compared to the overall size. I think I was just being shocked a little bit because I tend to ignore the `node_modules`-folder because of said reasons (don't stare into the abyss, you know? ;D)

After some thinking I realised that (hopefully!) many of the modules I pulled into the fresh repository will actually already be included into the app so that it doesn't bloat up by 40 megs, but only 10!

> On the other hand, think of all the new features adding this package would add to Zettlr.

Well, let's keep it realistic: Yes, it's charts, but not more than that. Many features will pertain other areas :P

I'll continue to look out for implementing this, but oof … I don't wanna hit the size of one Atom (if you get the pun, you'll most certainly feel punched)

**Comment by jrcharney** [comment]
Oof, indeed!

I though there was an alternative to Electron, especially after it was having issues with eating memory like it was an all-you-can-eat buffet?  Did they fix that?

> Well, let's keep it realistic: Yes, it's charts, but not more than that.

What if it could be added as an optional extension?  Some people might not use the LaTeX features as well, so what if that could also be an optional extension that could be added on-demand?

>  I don't wanna hit the size of one Atom

I understand. I've been using VS Code lately, simply because the of the GitHub integration even though I use GitHub Desktop for this one project that I am working on that is not being done in an IDE.

At least let's be grateful that `node_modules` is also in the `.gitignore` file and that users will have to download all those `node_modules` to their own computer instead of the developer uploading it from their own computer and having the user download it all from GitHub.

I'm trying to think if Node still has that pitfall where instead of using aliases/shortcut/"soft links" to point to frequent files, it just download the same modules repeatedly?  Unless there is a package manager that does this.

**Comment by nathanlesage** [comment]
> Did they fix that?

Well, I'm not sure. I've opened an issue concerning a minor bug with major consequences (light/dark mode detection on Catalina is still broken), and it's been closed since a week with no interaction :(

> Some people might not use the LaTeX features as well, so what if that could also be an optional extension that could be added on-demand?

That's the beauty of LaTeX: People can install it as a separate program, but don't have to. But Mermaid charts would need to be rendered within the page so I'd have to include at least rendering support within the app. Additionally, as the Mermaid Pandoc-filter is not included in default installs, it might very well be that I have to either tell people "Hey, besides pandoc and pandoc-citeproc, please also install pandoc-mermaid lol" or write a filter that performs pre-rendering before the file is actually handed over to Pandoc.

As you can see, there's a lot of work involved just getting the feature going :S 

> that users will have to download all those node_modules to their own computer

Well, it's not that easy. The node_modules need to be bundled within the final app, so in a way, yes, I have to "upload" it (albeit currently the VMs from GitHub Actions perform the heavy duty of doing that — it's simply not in version control)

> Unless there is a package manager that does this.

I do recommend [Yarn](https://yarnpkg.com/)!

**Comment by nathanlesage** [comment]
Hello hello. Just threw the 40 megs in the app: It now renders mermaid stuff. Still some work to do (that is: custom chart theming), but initial support is a thing!

Therefore I'll close this issue. **Wanna help?** Then please have a look at this issue: https://github.com/Zettlr/Zettlr/issues/498

**Comment by akasolace** [comment]
Is the export of documents containing mermaid graphs supposed to work out of the box?

**Comment by nathanlesage** [comment]
@akasolace Nope, only the previewing. For Pandoc-exports, there is apparently a filter somewhere, but it has to be installed just like citeproc in order to work! But adding support for that should be pretty straightforward given the tools Zettlr already offers!
