### ISSUE TITLE
[BUG]: Open File dialog has wrong name. 

### ISSUE THREAD

**Issue by Kangie** [Zettlr/Zettlr#1478]
## Description
Open file dialog presents internal name in titlebar.

## Reproducing

Attempt to open a file. :)
## Expected behaviour

"Open File"

![image](https://user-images.githubusercontent.com/9733178/100555497-f7267f80-32ef-11eb-97b8-cf53485a56ff.png)

## Platform
 - OS and version: 20.04 - Windows
 - Zettlr Version: 1.8.0

**Comment by nathanlesage** [comment]
Ah for Christ's sake …

(Thanks for reporting, I'm just annoyed by those miniscule bugs right now :D)

**Comment by nathanlesage** [comment]
So, just did a check and saw that I simply forgot to add that string to Zettlr Translate …

In general, may I ask a favour? I know you have a job yourself, but it would help incredibly if you could maybe over the course of the next weeks go through the translations and see if there's something else off? I have shuffled the translations quite a bit in preparation for 1.8 and I know there are still some things untranslated across the app, and some strings have to be exchanged, because they don't fit anymore.

While looking through the source, I for instance discovered this:

![image](https://user-images.githubusercontent.com/17251683/100580278-eec94700-32e5-11eb-999f-a21e4c2c06c5.png)

There are no "root directories" anymore, and I forgot to exchange those translations. Furthermore, I know that the "Exporting to ..."-strings are wrong (because the corresponding messages are displayed **after** the exporting, not prior to it).

This would incredibly help if you could have an open eye for those things, and of course there's no deadline attached!

(The Open Files I just created, so it should load when you next start the app)

**Comment by Kangie** [comment]
Happy to help out. I'll see if I can get to it this weekend.
