### ISSUE TITLE
Zettlr v1.8x not saving data in tables consistently

### ISSUE THREAD

**Issue by aarif** [Zettlr/Zettlr#1501]
## Description

I am having a problem with data in tables not getting saved. It appears that there is a "file changed" detection issue.

## Reproducing

1. Create a new file
2. Right-click and select "Insert Table"
3. Select any cell in the table
4. Type anything
5. Click empty space after the table
6. Type something
7. Click the cell where you typed something in step 4
8. The value you typed in step 4 disappears

## Expected behaviour

Any changes to the table should be not be lost.

## Platform
 - OS and version: MacOS 10.15.7
 - Zettlr Version: 1.8.0 and 1.8.1

## Additional information

I have tried enabling and disabling the advanced preference "Activate Watchdog polling" without luck.

**Comment by KnightSch** [comment]
I had the same problem, so I went back to version 1.7.5

**Comment by raphraph** [comment]
I can confirm this problem in version 1.8.1

- OS and version: Ubuntu 20.10

**Comment by AIBN60** [comment]
I confirm this for Ubuntu 18.04;

**Comment by nathanlesage** [comment]
Yeah the table editor is a little bit buggy right now. Mitigation: Do Not switch to 1.7.5 again, because there are numerous other bugs. Simply disable the table editor in the settings. I have this on my mind, and I'm looking for what's causing this, but I'm pretty much exhausted, so I cannot promise anything with regard to this. But don't use 1.7.5.
