### ISSUE TITLE
[ENHANCEMENT] New tab in sidebar for backlinks (file search results?)

### ISSUE THREAD

**Issue by mirenbz** [Zettlr/Zettlr#1522]
## Description

I would like to propose to add a new tab with backlinks (in the form of a list of files that link to the current file) to the right sidebar.

I'm finding myself tending more and more to backlinks to relate my notes with one another, and making this persistent would help a workflow where this is also the case. It would allow to use links as tags (though I am aware this is completely another debate) and then have "cluster" pages where many pages link to (like general terms), without the need to phisically add the links to the file. Not sure if I am explaining myself here.

## Proposed Changes

I'm not a coder so I don't know if a new feature is needed to grasp these files linking to the current one, but maybe just showing the "search for this file" results in a new tab in the sidebar could work.

## Caveats

(None that I can think of, but my thinking is limited in may ways 😉 )

## Additional Information

It occurred to me that his might not be all that difficult when I saw that the backlinks functionality is somehow there through "searching for the file" specifically here: [#56](https://github.com/Zettlr/Zettlr/issues/56#issuecomment-453593376)

**Comment by mberasategi** [comment]
Seeing that 5 people gave this a 👍🏼 , I would imagine there is at least some interest. Would anyone like to add their views on this in order to keep it from closing? Thanks!

**Comment by nathanlesage** [comment]
Sorry, I'm drowning in work. Added to 2.0 roadmap.

**Comment by mberasategi** [comment]
No need to apologise!
Thanks!

**Comment by Chris75539** [comment]
I would like to add to the proposal the idea that a new sidebar tab for links should not only show backlinks but also the outgoing links of a note, at least the internal ones.

Pros:
- In longer notes it would be easier to find all notes that this note links to
- Having both links and backlinks in one tab could be a great way to quickly navigate between related notes without having to scroll through the text

Cons:
- Maybe having a list of links is less useful the more links there are in a note because the "meaning" of each link is less obvious without reading the context of the link

Perhaps it would be useful if the links tab not only allows to follow the link but also to find and jump to the lines where the links are within the note.

**Comment by nathanlesage** [comment]
Will hopefully come with 2.1

**Comment by nathanlesage** [comment]
And it came with 2.1.1!
