### ISSUE TITLE
[DEVELOP] Performance Sink on Long Lines

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#1523]
A few have already complained about that on the issue tracker here, and I just experienced the same issue: On long lines, input can take seconds to actually appear, which is indeed a frustrating experience. I just had a 20 seconds blocking task running until the characters I wrote actually appeared.

I ran a quick performance check and found out that the long waiting times are caused by the multiplexing mode which Zettlr uses for codeblock syntax highlighting.

The culprit function that is being called dozens of times per keystroke (!) is the `indexOf`-function:

```javascript
  function indexOf(string, pattern, from, returnEnd) {
    if (typeof pattern == "string") {
      var found = string.indexOf(pattern, from);
      return returnEnd && found > -1 ? found + pattern.length : found;
    }
    var m = pattern.exec(from ? string.slice(from) : string);
    return m ? m.index + from + (returnEnd ? m[0].length : 0) : -1;
  }
```

Especially the `pattern.exec` function takes considerable time. I currently presume the reason is that the multiplexer mode has to go through all supported syntax highlighting modes (currently around 50) and test if it begins here. The multiplex mode does have its problems either way with the way Zettlr uses it, but now that I finally got a hint, here's what we need to do:

1. Think of a good method of integrating the multiplexer into the markdown-zkn mode Zettlr defines. Instead of having fifty regular expressions run over the same piece of code forever, we need one catch-all regex and then implement this functionality ourselves.
2. Migrate all syntax highlighting modes into the markdown-zkn mode
3. Remove the multiplex-mode from the loading chain so we can directly pull in the markdown mode

**Comment by mattj23** [comment]
Forgive me if this is naive; I don't know JavaScript and I've not looked at Zettlr's codebase or CodeMirror's before yesterday and it's a lot to take in.  I also don't know Electron, so half of my struggle is just trying to understand what's happening and how things are supposed to flow.

This is what I _think_ I understand:

You mentioned that the `indexOf` function seems to be the performance bottleneck.  I found that in [CodeMirror's repository](https://github.com/codemirror/CodeMirror/blob/master/addon/mode/multiplex.js) and see that it gets called from [line 49](https://github.com/codemirror/CodeMirror/blob/a46e33049de2c6f4550b77cad743d293039f2e93/addon/mode/multiplex.js#L49) inside of a loop that passes through an array(?...sorry struggling to catch up with JS) that seems to be populated from Zettlr's [multiplex.js line 230](https://github.com/Zettlr/Zettlr/blob/74cada087b24dc3e1a30209831cf175c2a4c44ca/source/renderer/modules/markdown-editor/modes/multiplex.js#L230)

Zettlr's multiplex.js produces this array from iterating through `highlightingModes` and constructing a regular expression that _always(?)_ starts with three backticks and then matches any of the selectors.

What seems to be happening, then, as I interpret what you described, is that in the [`token` method in CodeMirror's multiplexer](https://github.com/codemirror/CodeMirror/blob/a46e33049de2c6f4550b77cad743d293039f2e93/addon/mode/multiplex.js#L44) for every keypress iterates through every single regular expression in `others` looking for a match to see if we are transitioning to an "inner" mode?

Did I understand that correctly or get close?

If I'm close and the `indexOf` call in line 49 is indeed the culprit you were referring to, perhaps as a temporary solution rather than trying to create an entirely new multiplexer from scratch we could simply copy and modify this one by adding a single check to see if the triple backticks can be located in the stream.  If they can't be, then none of the regex which start with the triple backticks need to be checked at all.

**Comment by mattj23** [comment]
@nathanlesage, I was able to follow your very helpful [Get Involved](https://docs.zettlr.com/en/get-involved/) to get Zettlr building on my machine.  I decided to try making the modification to CodeMirror's multiplexer and it ended up working.  I was only able to try it on a Linux machine, but I might be able to build and test it on MacOS as well.

**Comment by nathanlesage** [comment]
Fixed thanks to @mattj23, closing …
