### ISSUE TITLE
Internal link autocomplete disappears when typing SPACE

### ISSUE THREAD

**Issue by yhoiseth** [Zettlr/Zettlr#1548]
## Description

When making internal links with `[[`, the autocomplete disappears when typing SPACE.

## Reproducing

First, create a file with spaces in the filename. For example, `20201220195013 Paul Graham.md`.

Second, open a separate file and type `[[` followed by `paul`. You should now see an autocomplete containing the file created in the previous step:

<img width="396" alt="Screen Shot 2020-12-21 at 14 55 02" src="https://user-images.githubusercontent.com/8469540/102784327-875e5e80-439c-11eb-86aa-7d8b2efb7b38.png">

Third, type SPACE:

<img width="228" alt="Screen Shot 2020-12-21 at 14 56 02" src="https://user-images.githubusercontent.com/8469540/102784445-b674d000-439c-11eb-9aa7-842c8c6536ad.png">

## Expected behaviour

The autocomplete should not disappear, and it should contain the file being searched for.

## Platform
 - OS and version: macOS 10.15.7 (19H114)
 - Zettlr Version: 1.8.3

## Additional information

This really starts to matter more when the number of search hits is greater. For example, if we have a lot of notes for people named Paul, it is nice to be able to narrow down the search results by typing the first letter(s) of the last name.

**Comment by crbald** [comment]
This exact thing greatly annoys me as well given how I tend to name my files ( e.g. [abbreviation of a book/course title] - [chapter] - [topic]).
When I e.g. try to reference a file for which I know some parts of the filename, but not all (e.g. only abbreviation and topic) I can't throw all the info tokens into the search to narrow it down.

There have been multiple previous complaints about this [(1)](https://github.com/Zettlr/Zettlr/issues/694) , [(2)](https://github.com/Zettlr/Zettlr/issues/953) [(3; with a dev request for suggestions how to solve this)](https://github.com/Zettlr/Zettlr/issues/622) but the dev says this is intentional [(here)](https://github.com/Zettlr/Zettlr/issues/682#issuecomment-616357896) [(and here)](https://github.com/Zettlr/Zettlr/issues/622#issuecomment-601405250).

I'd personally like to at least have an option to use space for "search for files with the tokens separated by spaces" instead of the (in at least my opinion) annoying and unnerving (amusingly the dev's reaction to the dropdown _not_ closing as fast as possible) closing of the dropdown. One of the users in (3) made some suggestions but that apparently never went anywhere or the support shown was too small.
