### ISSUE TITLE
[[ Autosuggest/linking stops working

### ISSUE THREAD

**Issue by puldzian** [Zettlr/Zettlr#1570]
## Description
Autosuggest/linking by ID (using [[) crashes

## Reproducing
Select a text, press [[... , start writing, overwriting selected fragment, then deselect it.
Autosuggest won't show anymore, restart of the application is required.

## Expected behaviour
Autosuggest should work even during overwriting text in square brackets.

## Platform
 - OS and version: Ubuntu 20.04.1
 - Zettlr Version: 1.8.4

## Additional information
I think this bug is new to 1.8.
Thank you for your work on Zettlr!

**Comment by nathanlesage** [comment]
Please provide any error logs, this is not reproducible unfortunately.


Here's how you find the logs:

1. Ensure the "debug mode" is active (Preferences -> Advanced -> Debug mode)
2. In the "Develop"-menu item, choose "Open Logs"
3. A new window will appear which contains all logs since the start of Zettlr. The logs will be updated regularly.

The logs themselves are color-coded:

- Grey is a debug message indicating a normal process within the app (useful to correlate your actions to processes within the application)
- Blue is an informative message, mostly indicating internal switches
- Yellow is a warning message indicating that something might be off
- Red is an error message indicating that a process has failed to execute correctly.

**Comment by puldzian** [comment]
I've reproduced the bug, unfortunately. 
Whether the autosuggest works or not on every keypress logs say:
> Trying to run command through Application: file-modified

**Comment by nathanlesage** [comment]
Maybe it's an error in the state machine of the autocorrect hook, but I'm not sure.

**Comment by cdaven** [comment]
I got the same issue now, in Windows 10 with Zettlr 1.8.4. Could reproduce once, but don't know how. The logs and console say nothing interesting.
