### ISSUE TITLE
'Delete file' does not remove file from file system.

### ISSUE THREAD

**Issue by TriciaHampton** [Zettlr/Zettlr#158]
## Description

In preview: Right click + 'Delete file' does not delete the file from the file system.  
It is removed from the preview, but reappears when Zettlr is restarted.

## Reproducing

Right click + 'Delete file'  in the preview. Inspect the containing directory with a file browser of choice.

## Expected behaviour

The selected file is deleted from the file system or moved to trash.

## Platform
 - OS: Debian buster / testing
 - OS Version 10
 - Zettlr Version 1.2.3

**Comment by nathanlesage** [comment]
I can't reproduce this on either Windows 10 or macOS 10.14.4 right now. Hmm, if the file is removed from the file list, this means that maybe the Debian 10 API is incompatible [with this line](https://github.com/Zettlr/Zettlr/blob/master/source/main/zettlr-file.js#L334), as it definitely gets executed. And if the file is removed from the preview list, this means that this line is definitely executed without errors.

A quick search yielded some apparently related issues:

- https://github.com/Microsoft/vscode/issues/13189
- https://github.com/electron/electron/issues/637

From the last one:

>  the gvfs-trash program is called to accomplish this. This program is, however, not installed by default on my debian (and maybe other linux distros, although I did not test this). So when calling the method, nothing happens, not even an error or warning.

Would you mind to check and, potentially confirm this?

**Comment by TriciaHampton** [comment]
gvfs-trash was indeed missing. It is contained in the *gvfs-bin* package on Debian buster. Now deleting works. Thanks!

**Comment by nathanlesage** [comment]
Good to know, I'm adding this to the FAQ section on Zettlr in case anybody else experiences that problem! :)

**Comment by keunes** [comment]
@nathanlesage I have this issue, too. I have `gvfs-bin` installed:
```
sudo apt install gvfs-bin
Pakketlijsten worden ingelezen... Klaar
Boom van vereisten wordt opgebouwd       
De statusinformatie wordt gelezen... Klaar
gvfs-bin is reeds de nieuwste versie (1.36.1-0ubuntu1.3.3).
0 opgewaardeerd, 0 nieuw geïnstalleerd, 0 te verwijderen en 0 niet opgewaardeerd.
```

Still, I can't delete files (I do get a confirmation message, but it doesn't get removed from my drive). My drive is a mounted ntfs drive - if that could be related. Would you mind re-opening this issue?

As possible solution (if root cause can't be fixed), would you be willing to add a setting in the advanced tab along the lines of 'All my notes are synced and have a back-up in case I accidentally delete a wrong file. Delete files without moving them to the trash.' for the Linux version?

**Comment by nathanlesage** [comment]
Yes, the NTFS can be the problem. NodeJS, and node-based solutions have in the past been prone to errors based on "exotic" storage configurations (albeit I'd say mounted NTFS drives and server drives should not be considered exotic). I can certainly implement a "remove directly"-setting. Nevertheless, I'd have to have a look at the Electron bug tracker, because this has nothing to do with Zettlr itself, but more with the fact that the shell module of Electron does not work as it should!

**Comment by nathanlesage** [comment]
Well, apparently they never really got into fixing the method:

https://github.com/electron/electron/issues/15370

**Comment by MZ62** [comment]
@nathanlesage same issue here on **Windows 10** having the data on a **network drive**. Deleting a file or directory in Zettlr removes the entry but not the file/directory .

Other electron apps (e.g. VS Code) detect that there is no trash bin and delete the files/directories permanently (optionally after asking for confirmation).

Could you please consider implementing this method (as also suggested by @keunes)? I don't store my personal data locally on my PC but on a network drive. So this would be an important feature for me.

**Comment by nathanlesage** [comment]
Ahh, the good old hassle with Windows network drives … I could certainly implement a switch to alter Zettlr's behaviour to automatically fully remove files if there's no trash, off by default.

**Comment by MZ62** [comment]
That would be great, thanks.

**Comment by halcyonquest** [comment]
I see part of the 1.7 roadmap is the file system abstraction layer. Any chance the ability to 'hard delete' files will be part of that? I'm trying to use Zettlr with a directory in my OneDrive Personal Vault for extra security and I am experiencing the issue discussed above where I delete a file but it doesn't actually get deleted. For now I'm opening file explorer to delete but I only have a few files since I am new to this. Once there are a lot of files, this will become difficult and tedious.

Like I said I'm a new user and other than this, I'm really loving Zettlr!!! Thank you!

**Comment by nathanlesage** [comment]
@halcyonquest This sounds like a new issue, feel free to open one up ;)
