### ISSUE TITLE
Chromium Browser showing up as Zettlr Icon on Toolbar in Linux Mint

### ISSUE THREAD

**Issue by SolarDesalination** [Zettlr/Zettlr#1584]
This is an odd one, and may be more related to Linux Mint than Zettlr;

My chromium browser is using the Zettlr Icon.

![Screenshot from 2020-12-31 09-30-58](https://user-images.githubusercontent.com/51060565/103414246-2d535b00-4b4b-11eb-9c22-dcd68414864c.png)

**Comment by nathanlesage** [comment]
Interesting. But yes, I am pretty sure it has to do with either Electron or Chromium, or how Mint handles this. What I have noticed in the past is that somehow certain elements of ALL (!) Chromium processes are somehow shared on the low level operating system layer, so that sometimes, when one Chromium instance (be it an Electron app or a Chrome tab) hangs, sometimes it drags down all other instances with it.

So I'd suggest you test it out with other apps, and if this happens with those as well sometimes, this indicates this.
