### ISSUE TITLE
Apple Silicon Export does not work

### ISSUE THREAD

**Issue by JJger148** [Zettlr/Zettlr#1613]
Ich habe die Version 1.8.5 für APPLE SILICON (ARM 64) installiert. 
Das problem ist, dass der Export mit pandoc und LaTeX funktioniert nicht. 

Error:
pandoc: $: openBinaryFile: does not exist (No such file or directory)

Hat jemand anders das gleiche problem?

**Comment by nathanlesage** [comment]
You have to reset your Pandoc command, because there was an error in the last version. You can reset your command by going into the app Preferences (`Cmd+,`) --> Advanced --> clicking the small button next to the Pandoc Command-text field.

If that does not work, please comment a screenshot of the full Pandoc command in here, like such:

![image](https://user-images.githubusercontent.com/17251683/104053038-e3bddc80-51ea-11eb-9149-8ec4e5531691.png)

**Comment by JJger148** [comment]
that worked, thanks!

**Comment by JJger148** [comment]
I have to problem again, even though I restored Pandoc in the settings.

**Comment by nathanlesage** [comment]
Please provide a screenshot or a more detailed description, as mentioned already. Otherwise, we can't help you.
