### ISSUE TITLE
bug about statistic in Chinese 

### ISSUE THREAD

**Issue by Wangaixue23** [Zettlr/Zettlr#162]
## Description
Hey, Thank you for the hard work.I'm a Chinese user. There are 1 bugs I think.( another is a feature XD)
Cannot count chinese characters correctly.  

## Reproducing

if you type several chinese words, 你好，谢谢，they can't be counts in words. and when you try to generate a table, it can not export successfully.

## Expected behaviour
I hope Zettlr can support mixed statistic in both Chinese and English . Can distinguish between words and characters，just  like Word！

as hope Zettlr can support tables.

**Screenshots**

![image](https://user-images.githubusercontent.com/39932352/56425568-761b9f80-62e7-11e9-9c1f-c8d585e4954a.png)

this is a chinese essay (unfinished) you can see chinese characters as squares !

## Platform
 - OS Version [e.g. 11]
 - Zettlr Version [e.g. 0.15]
 - Screen Resolution [only necessary if the bug is relating to the GUI]

my version is win64 1.2.2

**Comment by nathanlesage** [comment]
Thank you for the issue! The word counter has been raised a few months ago, I'll put it on my agenda!

Concerning the font: Liberation Mono (which is used for tables) was supposed to contain all Glyphs … but well, you can change the font using the [Custom CSS feature](https://www.zettlr.com/docs/custom-css) for tables so that you have a font that supports your missing glyphs!

**Comment by Wangaixue23** [comment]
Thanks a lot!
