### ISSUE TITLE
[BUG] WYSIWYG formatting occurs within code blocks.

### ISSUE THREAD

**Issue by Kangie** [Zettlr/Zettlr#1625]
## Description

A task list within a code block is rendered as WYSIWYG
## Reproducing

Create a task list. Put it in a block!
## Expected behaviour

The WYSIWYG portions of the editor should not be enabled within code blocks.

![image](https://user-images.githubusercontent.com/9733178/104266900-a73cfa00-54e4-11eb-9868-3936343d3d14.png)

## Platform
 - OS and version: Win 10 20H2
 - Zettlr Version: 1.8.5/Develop

**Comment by Kangie** [comment]
Seems to be more widespread than I thought:

![image](https://user-images.githubusercontent.com/9733178/104268704-a7d78f80-54e8-11eb-8da7-f3a049587ef9.png)

**Comment by nathanlesage** [comment]
Known, but without any known mitigation: The problem is that the rendering plugins check for the highlighting mode: If it's not markdown, they won't trigger, but if it is, they will. Unfortunately, we need to check the innerMode (because of the multiplexer), and this will mean that also non-specific code blocks and markdown code-blocks will also be rendered.

Clever ideas are welcome.

**Comment by nathanlesage** [comment]
Done!

If some thing that SHOULD work in normal mode doesn't anymore, please say so, because then I have forgotten to replace some `markdown` with a `markdown-zkn` :D
