### ISSUE TITLE
[BUG]: Zettlr console: application uptime suffers a rollover at 24 hours.

### ISSUE THREAD

**Issue by Kangie** [Zettlr/Zettlr#1628]
## Description

Past 24 hours uptime the Zettlr log provider rolls over as (I suspect) the day is not being recorded.
## Reproducing

Run Zettlr for >24h, then close the application. Output best viewed from console.

```text
[11:32:02] Shutdown almost complete. Application uptime was: 1 hours, 13 minutes, and 42.942 seconds.
[11:32:02] Log provider shutting down ...
Done in 90836.98s.
```
## Expected behaviour

Also record / calculate / retain days. Alternately declare won'tfix because it doesn't matter!

FYI, 90836.98s = 25.23 hours = 1d 1h, 13m....

## Platform
 - OS and version: Win10 20H2
 - Zettlr Version: 1.8.5/Develop

**Comment by nathanlesage** [comment]
:D I actually added a warning that SHOULD have been printed on the console if you run Zettlr for more than 24 hourse because my traditionalist brain still thinks running a computer for more than 24 hours is bad.

Think the error is this beauty of some weird logical error:

https://github.com/Zettlr/Zettlr/blob/be3c4e320e1dbeb7c0c4b825b76011dafff0e414/source/app/util/resolve-timespan-ms.ts#L54-L64

**Comment by nathanlesage** [comment]
Let's see if that was the cause …
