### ISSUE TITLE
[Feature Request] Column and row numbers 

### ISSUE THREAD

**Issue by offray** [Zettlr/Zettlr#163]
First, thanks for Zettlr (yep I have done it in Twitter and adding my emoji reaction to the Gratittute issue, but being this my first report, it seems fine to repeat it).

Second, I would like to have more real time stats about the document when I'm writing it. Particularly, I would like to have column and row number, as I like to have my column size about 90-ish characters for documents, following the [Practical Typography](https://practicaltypography.com/) advice and avoiding line wrapping or scrolling while seeing diff on control version systems, for the documents I have wrote.

**Comment by nathanlesage** [comment]
Concerning line numbers: I've been playing with how this looks already. I haven't implemented it yet, as I'm still not convinced that it looks great, but now I'll move it up on my Todo-List!

Concerning the character count per line … so you would like something like a status bar where you can see "Your Cursor is currently at Line x, Character y", just as in word processors etc, right? Plus ideally the 90-characters indicator-line so that you have a visual representation, right? The last thing would only work with a monospaced font, so it'll take some ifs and elses, but I'll see what I can do!

And, of course, as always: Thank you very much! :)

**Comment by offray** [comment]
Maybe a colored count indicator could be available near to the word count for columns and the more it approaches to 90 (or any predefined number) it will become more red. Other editors add a little vertical line that shows when you reach the predefined characters length, but I don't think that the approach is good for windows resizing while the colored character count per line near to the word count could work better, while keeping Zettlers minimalist aesthetics.

**Comment by nathanlesage** [comment]
> Other editors add a little vertical line that shows when you reach the predefined characters length

Which is what I'll implement, albeit you'll need to activate it using CSS afterwards (to not confuse users sticking to the default sans-serif font). I'll get to it!

**Comment by nathanlesage** [comment]
It's coming

![image](https://user-images.githubusercontent.com/17251683/63650584-517b7c80-c74c-11e9-9bb8-ab3b5a5fa0a1.png)
