### ISSUE TITLE
[ENHANCEMENT] Add setting to dynamically hide formatting symbols

### ISSUE THREAD

**Issue by bleonard252** [Zettlr/Zettlr#1634]
## Description
There should be a setting that applies similar formatting as unfocused links to all text, similar to the (closed-source) Typora.

## Proposed Changes
This setting would hide formatting markers around bold and italic text when the formatted text is not focused. I assume it would be implemented as a CodeMirror plugin...

## Caveats
If it is off by default, nothing else should be disturbed.

## Additional Information
I'd be glad to implement this, but I'm clueless as to how this whole thing works-- how are the formatting markers rendered, for example?

**Comment by nathanlesage** [comment]
We already have this as some sort of experimental WYSIWYG-plugin, I don't want to implement this actually …

**Comment by chchen2021** [comment]
I know @nathanlesage's stance on this issue, but I would like to voice support for offering an **option** to hide formatting characters. The option is not fundamentally different from the option to [hide heading characters](https://github.com/Zettlr/Zettlr/discussions/2502) or the option to [remove formatting color](https://github.com/Zettlr/Zettlr/issues/2243). 

In my own case, I very rarely use italic or bold, perhaps once every three printed pages. When I do use such an emphasis, the emphasized texts tend to be very important and get looked at much more frequently than the rest of the text. In such case, the formatting characters become a real distraction. Also, these texts may be for personal notes and will not be converted to a prettier publication format -- the Zettlr form is the final form in which the notes are reviewed.

For the time being, I actually forgo the editing convenience by using a css snippet (adapted from a [reddit post](https://www.reddit.com/r/Zettlr/comments/l4lsol/chiaroscuro_custom_css/)) to completely hide the formatting characters:
```
#editor .cm-formatting.cm-formatting-strong.cm-strong {
  font-size: 0em;
  visibility: hidden;
}

#editor .cm-formatting.cm-formatting-em.cm-em {
  font-size: 0em;
  visibility: hidden;
}
```

Please consider adding a display option to hide the formatting characters. I do not have much problem with bullet points `-` and block quotes `>` because they are at the beginning of each text line, and are less distracting than the `* *` in the middle of the text.
