### ISSUE TITLE
[UPDATE 1.8.6] Please rename your configuration folder from "zettlr" to "Zettlr" (Windows & Linux)

### ISSUE THREAD

**Issue by kyaso** [Zettlr/Zettlr#1635]
## Description
Whenever I start the AppImage of 1.8.6, it is like opening Zettlr for the first time, i.e. all settings reset, no open tabs, etc. However, when I launch 1.8.5 instead, everything is as as usual.

Looks like AppImage 1.8.6 is ignoring the local config.

## Reproducing
Start AppImage of 1.8.6.

## Expected behaviour
All stored settings and states should be loaded.

## Platform
 - OS and version: Manjaro Linux 20.2
 - Zettlr Version: 1.8.6

## Additional information
I use [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher) to manage AppImages on my system.

**Comment by nathanlesage** [comment]
We've had some issues with the CI but I didn't touch the AppImage generation, so I'm not quite sure what is happening here. If someone wants to dive into it (I can't debug AppImages locally, unfortunately), relevant are the files `electron-builder.yaml` and the corresponding config, available at https://electron.build

**Comment by ihindha** [comment]
Had the same problem with the .deb version on ubuntu 20.04. 

What I can see, the problem is that the path to where zettlr looks for the config has changed from "~/.config/zettlr" to ~/.config/Zettlr". That means when you starts the app after update, it can't find it's config and creates a new.

A workaround is to rename the old folder

**Comment by nathanlesage** [comment]
@ihindha Yes, indeed!

I've had a similar reply on Twitter just now: https://twitter.com/AIBN_60/status/1350430856259776517

I personally think that this is better, and this would also explain why I did not have any error: macOS is case-insensitive!

So, sorry again for new inconsistencies, but I had to realize during the CI failures in the past day that the electron environment is incredibly badly documented, and a lot of stuff is "just happening" without any explanation given …

I will adapt the Changelog accordingly, and not touch the build configuration for the foreseeable future.

**Comment by nathanlesage** [comment]
Just adopted the title, because this way everyone will know what is happening …

**Comment by nathanlesage** [comment]
I just spread the word on Twitter: https://twitter.com/zettlr/status/1350442799393599488

... and the forum: https://forum.zettlr.com/discussion/359/update-1-8-6-windows-linux-users-probably-need-to-rename-their-config-folder/

If you encounter someone, point them to these sources, I included a reference to the docs where they can find which folder they need to rename.

I'll keep this issue open for a week (let's see if the stale bot is clever enough to auto-close it) so that most of GitHub users will encounter this issue until then.

Apologies for the small shock I caused!
