### ISSUE TITLE
Discussions about Zettlr need a home

### ISSUE THREAD

**Issue by ngirard** [Zettlr/Zettlr#167]
Unless I'm mistaken, and according to Zettlr's [guide](https://www.zettlr.com/docs/get-involved), people wanting to discuss about Zettlr are invited to do so on Github issue tracker.

I think it's too limited. Giving such discussions a good, dedicated place would:

1. Give Zettlr more visibility ;
2. Give food for thought to implementers of the Zettelkasten system, regardless on the software they're using ;
3. Allow to gain insight on Zettlr's development ;
4. Help best practices about the Zettelkasten to emerge, since Zettlr is one of the very few existing and actively maintained software that allows Zettelkasten principles to be put into practice.

Now, from your [very recent comment](https://github.com/Zettlr/Zettlr/issues/166#issuecomment-485242531), I can safely conclude you're sharing these concerns ; so how about walking around the possible candidates ?

### Reddit

While Reddit is very popular and convenient, I can see downsides using it to host Zettlr-related discussions:

- if I remember correctly, threads are closed to further discussions and commenting after 30 days
- you need to choose a subreddit (e.g. either r/Zettler, or r/Zettelkasten) before publishing, which makes discussions invisible to those who're not following the chosen subreddit. Doing cross-posting is inelegant, inconvenient and problematic at once, so I wouldn't regardit as a solution

### The Zettelkasten forum (forum.zettelkasten.de)

This is *de facto* the place where Zettelkasten practitionners gather nowadays, so I'd strongly consider joining it.

Zettlr has first been welcome --- how should I say ? --- [a bit reluctantly](https://forum.zettelkasten.de/discussion/329/zettlr) by the forum administrator (*"I do not really like the technology involved"*) ; but then he [recently posted](https://forum.zettelkasten.de/discussion/536/wtf-is-a-zettelkasten) a link to your video called "WTF is a Zettelkasten?" ; so all in all I'd say the doors are open.

But the way I see it, Zettlr discussions on this forum would need a dedicated category, so the administrator would need to be asked first. If needs be, I guess you should be the one to ask, but I'd gladly do it if you wish.

**Comment by nathanlesage** [comment]
Thank you for this issue!

First concerning reddit: The good thing there is that the community can basically "manage itself", so that I don't need to be around all the time, moderating stuff. Reddit therefore is very good for users to just ask small questions concerning, as has happened some weeks ago, how to facilitate bible reading with the app, without me needing to comment as well.

So for users who are not "inside" the Zettlr community (communities do become "closed" to some extent as they form) this is a great place, because it works just like the rest of reddit, so they know how to behave in the Zettlr subreddit and have a lower threshold of "just asking".

The Zettelkasten forum, as you have mentioned, is a great place for asking stuff about the Zettelkasten methodology, however I see two issues concerning it. First, it's _only_ about Zettelkasten, so it does not make sense to have a forum dedicated to discussions of Zettlr, and I don't think Christian would welcome this, as my app in a way is competing against their Archive. =D

So let's discuss two more alternatives:

**A Slack Channel**

A slack channel would combine the benefits of reddit while alleviating some of the issues you've mentioned exist with reddit. It's also industry standard and offers additional methods of integrating stuff into the channel. The alternative to slack would be a dedicated mattermost server.

**A Standard Forum**

Easy set up, and gives maximum flexibility by allowing plugins, and stuff. And I also happen to have a forum already set up. Still, I wasn't sure whether people would like to set up an account there (but I guess my experiences with Zettlr Translate have shown that people are indeed willing).

**Comment by nathanlesage** [comment]
If anybody is interested in giving it a try, there's a small forum set up at https://forum.zettlr.com, so feel free to use it and give feedback. I've felt that this is the best idea to do, as Zotero, for instance, [has a forum itself as well](https://forums.zotero.org/discussions).

**Comment by ploum** [comment]
As there's a forum, I would say that this issue might be closed.

**Comment by nathanlesage** [comment]
Yes!
