### ISSUE TITLE
[ENHANCEMENT] faster newfiles with no autoselect ".md" in newfile name modal 

### ISSUE THREAD

**Issue by bionicles** [Zettlr/Zettlr#1672]
## Description
When we create new files, it opens a box with the generated filename. The whole filename is selected, including the ".md" extension. The enhancement would simply be to not select ".md" so when you create a new file you can instantly type a filename without an extension

## Proposed Changes
Simply change the selection of the text in the filename modal to not include the ".md" 
(perhaps via string slicing) -- or don't include the extension in the modal

## Caveats

might need to include .txt

## Additional Information
tiny improvements yield compounded exponential growth

**Comment by humaoxuan** [comment]
Hi, we are a group of students of The University of Adelaide in Australia studying the course Software Process Improvement, we are interested in Zettler and would like to work on the issue. As we need time to get familiar with the project, we are planning to commit the first pull request in 4 weeks.

**Comment by nathanlesage** [comment]
I now implemented a way better way of creating new documents: Using the shortcut or the menu item yields a file in-memory, where you can decide on the filename later on. So I'm gonna see this issue as obsolete.

However, since the context menu will still allow to create files BEFORE adding content to them, a PR for this can of course still be merged and makes sense.
