### ISSUE TITLE
[DEVELOP] ESLint throwing weird errors

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#1676]
So after some ESLint upgrade, the linter throws weird errors. The VSCode ESLint extension shows everything as expected. However, running `yarn lint` produces weird errors. These all relate to when some functions receive a `this`-property as default of a variable.

While I agree that it's not the best style, I would like both the ESLint plugin in VSCode as well as the command line linter to report the same amount of errors.

If anyone wants to look into it, I assume it's just a settings error, and so it's an easy grab for anyone who wants to do a PR :)

**Comment by Kangie** [comment]
I'll take a look next time I work on Zettlr. I just had to setup all of my own linting configs so hopefully I can spot the issue and possibly suggest some improvements.

**Comment by nathanlesage** [comment]
Thank you! 🙏

**Comment by Kangie** [comment]
See #1734, however I may have gone a bit further than just investigating weird errors. 

A whole new world of linting awaits. There will be tons of warnings until everything is typescriptified, but I think that the new rules will make life easier overall. I strongly encourage you to check out that PR / branch of my fork and see what you think of the linting rules. It's still in progress, but I'll try to get it done asap so that I don't have to keep rebasing. ;)

**Comment by nathanlesage** [comment]
Thank you for the awesome work! I'll work through this thoroughly once I have the time :)

**Comment by nathanlesage** [comment]
Since the linter is not throwing any weird errors anymore, I'm gonna close this issue (wanna go forward with the 2.0-project) – the PR is unaffected, obviously :)
