### ISSUE TITLE
[ENHANCEMENT] Have a date-time generator and add liquid support

### ISSUE THREAD

**Issue by TwoPizza9621536** [Zettlr/Zettlr#1681]
## Description
Have a general date-time generator. Also add liquid tags syntax support listed here #1027.

## Proposed Changes
This will change the Zettelkasten ID generator. The Zettelkasten ID generator is a fine date-time generator but its not very customizable and not everyone is using Zettelkasten for note taking. Instade of using the Zettelkasten ID generator, I think using [date-fns](https://date-fns.org) to generate date and time. It has been used as a plugin for text editors, includes time zones, l18n and uses the Unicode standard for date-time.

For liquid tags, this changes the syntax highlighting for markdown. I want to add Kramdown dialect for Jekyll(or equivalent) static page generators and add a syntax highlighter for liquid as Zettlr has YAML Frontmatter support and someone requested it here #1027.

## Caveats
Backwards-compatibility - due to the patterns being different between the two unless separating the two generators.

**Comment by nathanlesage** [comment]
Liquid support can't come since that would open the gates for all other templating engines (Twig, Handlebars and whatnotelse). However, it's thinkable that this might come in handy if Zettlr at one point receives plugin support.

As for the date generator: I don't see any reason why you can't type human-readable dates by yourself? If you really want a datetime generator, Zettlr already ships with Luxon, but in that case I would like you to request support for a different variable that Zettlr can spit out containing a localised human-readable date.
