### ISSUE TITLE
ARM builds for Linux

### ISSUE THREAD

**Issue by norweeg** [Zettlr/Zettlr#1747]
## Description
Please provide ARM equivalents for your linux builds.  You provide ARM builds for MacOS and Windows, but not Linux.  Linux on ARM **has** to be more common than Windows on ARM!

**Comment by nathanlesage** [comment]
The main impediment for why I am not offering these just yet is because I need Pandoc compiled for ARM64, which is not yet happening (Zettlr bundles Pandoc). However, in case Linux in general has an equivalent of macOS's Rosetta for running x64 binaries, I'll consider it!

**Comment by norweeg** [comment]
@nathanlesage where are you finding pandoc binaries for windows on ARM?  I'm on https://github.com/jgm/pandoc/releases and only see x86_64 builds

**Comment by norweeg** [comment]
Looks like there's an issue open on Pandoc's repository for ARM builds https://github.com/jgm/pandoc/issues/5450

**Comment by nathanlesage** [comment]
> @nathanlesage where are you finding pandoc binaries for windows on ARM? I'm on [jgm/pandoc/releases](https://github.com/jgm/pandoc/releases) and only see x86_64 builds

Windows has an x64-emulator for its ARM builds, just like macOS. This is why I can ship ARM builds for both Windows and macOS, but not (yet) for Linux. But the Pandoc team knows that there is a demand for ARM builds, as you rightfully found out. Once they're here, we can go all-out on ARM releases :)

**Comment by norweeg** [comment]
@nathanlesage question for you: I notice you distribute both .deb and .appimage for linux.  While I understand the bundling of pandoc in an appimage, bundling it in a .deb seems like an antipattern to me.  Pandoc is already available in Debian/Ubuntu's ARM repositories.  Couldn't you distribute an ARM binary as a deb which [depends on the debian Pandoc package?](https://pandoc.org/installing.html#linux).  No need to bundle it if it is installable as a dependency

**Comment by boutil** [comment]
@norweeg the problem is that there has been a change of behavior of pandoc between the one currently shipped by Debian testing/unstable (2.9.x) and the current one (2.11.x). The engine for citations, citeproc, which was before an external filter, is now part of pandoc. It changes the way options on the command line should be passed to pandoc. It was impossible, or at least too difficult, to support the two ways at the same time.
(that is at least my understanding of the situation)

**Comment by nathanlesage** [comment]
@boutil is right: The standard Pandoc version in the repositories is too old, Zettlr needs at least 2.10 to work properly. Plus, we decided to bundle it to go around precisely those issues of outdated dependencies. If the binary is shipped with the app, there's no way that's not going to work. We have had our fair share of users complaining that they couldn't export on Debian, and it became fairly obvious that we need to bundle a version of Pandoc we can write the API commands for.

So, yeah, in a perfect world, Pandoc would also offer ARM builds. So let's hope they get the remaining problems in getting cabal to compile on ARM sorted out :)

**Comment by tarleb** [comment]
Good news: https://github.com/jgm/pandoc/commit/d560038342ad45fabd10be85d8343d05d7f20c92

**Comment by nathanlesage** [comment]
That's great news! 🤩 Thank you for the notification!

**Comment by tarleb** [comment]
Pandoc 2.13 and 2.14 have official arm64 binaries for Linux.

**Comment by nathanlesage** [comment]
Perfect, so now we just need to update the CI!

**Comment by nathanlesage** [comment]
Hey everyone! I just tried to add everything to CI, but that requires testing out full builds. However, since I don't have Linux running, the build fails locally.

**It would be awesome, if someone could do the following**:

1. Build the ARM builds by running `yarn package:linux-arm && yarn release:linux-arm`.
2. Figure out the exact artifact names as they are in the `./release`-folder
3. Tell me these so I can update the CI pipeline.

Of course, you can open a PR that does 3 yourself, the file should be pretty self-explanatory: https://github.com/Zettlr/Zettlr/blob/develop/.github/workflows/build.yml

**Comment by nathanlesage** [comment]
After taking a second look, I figured that Electron builder has indeed created two releases – the debian installer and the AppImage binary. However, it did fail to create the RPM installer (common problem on macOS). I'm now assuming that the ARM64 RPM installer follows the same architecture naming convention, and I have added that to the CI. If someone knows it's _not_ `arm64`, please tell me so that I can fix the pipeline.

If nobody says anything, we'll know if it's correct if the build pipeline doesn't fail …
