### ISSUE TITLE
Spellcheck Marks Emoji as Wrong Spelling 📚

### ISSUE THREAD

**Issue by hozza** [Zettlr/Zettlr#1751]
## Description
When Spellchecking is enabled, emojis are listed as incorrect spelling, which then shows every letter of the alphabet (and more) as spelling suggestion options.

## Reproducing
Turn on Spellcheck and then add an emoji to a notes content. 📚

## Expected behaviour
Emojis should not be underlined in red, or suggesting all letters as corrections.

## Platform
 - OS and version: Linux Mint 20
 - Zettlr Version: 1.8.7

## Additional information
This can be fixed by adding each emoji to the User Dictionary in Settings, although this would take some time if done manually. 

Would it be possible to ship with emojis excluded from Spellchecking? Perhaps silently appending them to the User Dictionary.

I'm using the English UK spelling dictionary if that helps.

**Comment by nathanlesage** [comment]
I've searched the world wide webs, and finally found a somewhat manageable regular expression for matching emojis:

![image](https://user-images.githubusercontent.com/17251683/123236550-2d6e5b00-d4dd-11eb-8b86-37166e492880.png)

Thank this person: https://stackoverflow.com/a/43243160

***

**NOTE**: The regexp might not match every (especially future) Emoji, but I think it suffices to reduce the amount of 'wrong' spell check results to a very small degree so that manually adding some Emojis shouldn't be too burdensome.
