### ISSUE TITLE
on footnotes: a couple of suggestions

### ISSUE THREAD

**Issue by persianphilosopher** [Zettlr/Zettlr#18]
Absolutely love this project. I am simply annoyed I didn't know about it earlier. 

What I absolutely need in an editor is the ability to handle footnotes and you have that integrated nicely. It's not markdown's greatest strength but it's too often neglected.  I have to suggestions for your consideration:

1. Please, please add a shortcut for footnotes. I use them so often and I prefer not to leave the keyboard for them if possible. It does not appear that you have Ctrl+Alt+F linked to anything (and that's MS Word's shortcut) and it would be great to be able to insert it quickly. 

2. This one is a much bigger ask, but here we go. Since you aim (Thank you!) for the humanities, you know that we use a lot of notes. If at all possible, it would be great to be able to have the footnotes in a sidebar and not right below the text. That would be an improvement even on MS Word in my opinion. 

Thank you greatly for this project.

**Comment by nathanlesage** [comment]
Hey,

thank you for your appreciation. Indeed there is lots of work still to be done with the footnotes. For instance, in the source code you may find a file in which I already tried to implement a "beautification" command for the footnotes (that simply re-counts them starting from 1, thereby removing gaps and cleaning the ordering). It's still a mess and it does funny things to the files (which is why it is unused at the moment).

Also the positioning of the footnotes (that they simply show up at the bottom of the file) is still not the best way to handle this, that is completely correct. I have simply implemented it this way because it was the easiest option for me at that time (Zettlr still misses some features I personally want to implement as well).

Here are my ideas on how to improve footnotes in the future:

- Add a shortcut (Your suggestion with Cmd/Ctrl+Alt+F is indeed a good option)
- Finalise the "beautification" command that will be run after every footnote insertion/removal
- Add an option to alter the footnote's text using a small popup (which would be a great relief because no scrolling would be necessary to alter the footnote's text)

A sidebar would also be an idea, but the question there is: where and how could I put it? Wouldn't hover-to-preview and click-to-edit be sufficient…?

**Comment by nathanlesage** [comment]
Hey,

just added the features in a rudimentary version. There will be space for improvement, but now that it's implemented, we can work on that. It will be released in 0.17 — please test it and give feedback on it!

Cheers

**Comment by persianphilosopher** [comment]
@nathanlesage thanks a million and you can count on the feedback in due course
