### ISSUE TITLE
Update french translation

### ISSUE THREAD

**Issue by ngirard** [Zettlr/Zettlr#182]
Could you please include the french translation updates to the forthcoming beta version ?

It would give me some feedback and help with what remains to be translated.

Thanks in advance !

**Comment by nathanlesage** [comment]
I last downloaded the French translation yesterday at noon, and this version will be included in the forthcoming beta. According to the admin backend, all translations will be included, as the last updates were added at the same time as I added some missing localisations, so it seems everything's okay :)

![image](https://user-images.githubusercontent.com/17251683/57857691-f1da1080-77ef-11e9-9279-6d99746fca8d.png)

BUT I've got an idea: you can rename the downloaded translation, say, from `fr-FR.json` to any other language; for instance `it-IT.json`. Then it'll show as Italian in the app, but obviously you'd get French translation. This way you might even be able to compare the current French translation to your updates, so that you can maybe even find more instances where the translation is bad!

**Comment by ngirard** [comment]
Very nice, thanks for your efforts & for the tip !

**Comment by nathanlesage** [comment]
You're welcome 🤗
