### ISSUE TITLE
Always save every modification

### ISSUE THREAD

**Issue by ploum** [Zettlr/Zettlr#183]
Most modern editors don't have "save" buttons. It is assumed that every modification needs to be saved.

It looks like Zettlr behaviour is inconsistent in that regards :

Good : I've never saved anything in Zettlr and it seems to work.

Bad : 
- there's a save entry in the menu. What does it do?
- sometimes, when I close Zettlr, it warns me that the current content has not been saved (!).

Solution : it should be assumed that, when closing, the content should always be saved (after all, it works when Zettlr crashes) and the "save" entry should be removed from the menu.

**Comment by nathanlesage** [comment]
The "Save" button is there "just in case"; I'm always a little bit paranoid and have really internalised the "Save early, save often" mentality. Zettlr saves everything, always. The "Save" button will only be there just in case.

But concerning the second aspect you've mentioned: When this dialog appears it is indicative of a bug, because it shouldn't appear (this is why I will keep the Save button as well, as you can't always be sure of bugs interfering).

Could you give a timeline of what you did prior to the dialog box appearing, when it happens again? Then we could investigate further, but please in a new issue! :)

**Comment by ploum** [comment]
Thanks a lot for the reply. I understand. Filled a new bug for the popup.
