### ISSUE TITLE
Lost preferences and open files/workspaces in upgrade from 1.8.3 to 1.8.7

### ISSUE THREAD

**Issue by pcraciunoiu** [Zettlr/Zettlr#1830]
## Description

Hi, I had a dark theme setup and several files open in 1.8.3. I installed 1.8.7 on Debian through `dpkg -i`, and all my preferences were lost. No files are open, and the theme is back to white.

I downgraded for now and got everything back. This didn't happen with previous upgrades.

## Reproducing

See above.

## Expected behaviour

Should remember theme and open files.

## Platform
 - OS and version: Ubuntu 20.04 (Pop OS version)
 - Zettlr Version: 1.8.7

**Comment by nathanlesage** [comment]
Mh … are there any indications in the log files, some errors or what might've happened? Something that Zettlr wasn't able to load the configuration, or similar?

Here's how you find the logs:

You can find the logs at `/home/<your username>/.config/zettlr/logs`

They are named after the day where they were created in the format `yyyy-mm-dd.log` (e.g. you'd need to look into the file of the day where this happened)

**Comment by pcraciunoiu** [comment]
I do see one line, could be related:

```
[08:52:39] [Info] [Citeproc Provider] There is no CSL library selected in the preferences. Nothing to do.
```

**Comment by nathanlesage** [comment]
Mh no, that's just the citation engine logging that there is no CSL library … that is...

OH WAIT.

Yes, we had this problem: It's because the configuration folder has been renamed from `zettlr` to `Zettlr` in one of the recent versions! It was a little bit unplanned, but in the end I wanted the folders to be `Zettlr` (with a capital Z) in the first place.

So what to do? Easy: install 1.8.7 again, then remove the new (and "blank") "Zettlr" folder, and then rename your old "zettlr" config folder to "Zettlr" with a capital Z, and THEN start 1.8.7. Then it will work!

Apologies for forgetting this!

**Comment by pcraciunoiu** [comment]
Thanks @nathanlesage  - that did it. I had to toggle "Night mode" to be always on again, but the files were reopened, so I think it worked! I'll close this.
