### ISSUE TITLE
Trash folder

### ISSUE THREAD

**Issue by ploum** [Zettlr/Zettlr#184]
The "delete note" feature of Zettlr is very disturbing when used to a modern workflow.

1. The popup disturb you from your mental workflow
2. The popup asks you to take a definitive decision that can't be reverted.

Obvious possible solution: 

A trash folder. Upon delete, file are moved to the trash without any warning. This will highly reduce the risk of data loss (yes, I've already lost data in Zettlr because I'm not used anymore to those popups and replied to quickly).

See what Ulysses does in that regard.

**Comment by nathanlesage** [comment]
Zettlr never deletes any file. It will move the file to the system trash, from where you can restore it everytime. And the dialog should be easily handled: `Return` confirms the move to the trash bin, while `ESC` will abort. If it doesn't, you've stumbled upon wrong behaviour by the app! So point 2 is not correct, as this action will always be revertible.

Concerning your first point: I can implement a way that you can deactivate the popups from appearing, because I totally see your point here.

**Comment by ploum** [comment]
Thanks, using the system Trash looks like a very sensible choice, especially if Zettlr implements once the concept of "archives" ( #185 ), meaning that the Trash should be out of the UI.

If there's a Archives, I don't know if bypassing the delete popup would still be needed (as I'm the kind of guy who archives everything without deleting anything).

**Comment by nathanlesage** [comment]
Me too, and the idea of using a dedicated "Archive" folder was exactly the idea I needed for keeping my own directory clean. So thank you a lot for this insight!

**Comment by ploum** [comment]
then I guess this ticket can be closed.

**Comment by nathanlesage** [comment]
Alright!
