### ISSUE TITLE
[ENHANCEMENT] Execute arbitrary command for export

### ISSUE THREAD

**Issue by xldrkp** [Zettlr/Zettlr#1842]
## Description
An enhancement would be if one could execute arbitrary commands in a custom export function. Thus, it would be possible to use the editor's Markdown e.g. with a Docker command and produce all kinds of output with Zettlr.

## Proposed Changes
- Add a new icon to the list of export formats named something like "custom"
- Add a new section to the setting tab "Advanced" that relates to this icon.
- Add a new form field to this section that takes custom commands being executed on the text corpus when the custom icon is clicked.

## Caveats
Not imaginable yet. But could be that the custom pandoc command is no longer necessary with this enhancement.

## Additional Information
Main reason for this enhancement request is that we would like to use Zettlr more in the context of the single-source production we have developed in https://doi.org/10.15480/882.2902

**Comment by nathanlesage** [comment]
Already planned and everything is already in place for exactly such a feature; @tarleb has already explained what kinds of commands one would need to be able to run. While we're at it: The easiest way for me to implement such a thing with, like, five lines of code, would be if I could access this via frontmatter.

So basically, you write a Markdown file, and there is some frontmatter value, and if you use the "Use custom command" exporter, the exporter would read whatever is in there and execute that one instead of Pandoc. Would that be useful? Or, rather, some form of input field in the preferences? I'd argue the former method would be more customisable …?

**Comment by tarleb** [comment]
> The easiest way for me to implement such a thing with, like, five lines of code, would be if I could access this via frontmatter.

I'm not 100% what you mean here, is it a suggestion for pandoc to treat frontmatter like a defaults file? That would lead to security concerns in pandoc, so such a feature is unlikely to happen.

**Comment by nathanlesage** [comment]
Another idea just crossed my mind: How about the ability to create custom exporters that can also use the defaults files from the "standard" exporters but you can define arbitrary shell scripts for that one? That would mean the following:

* A "standard" exporter is defined as running Pandoc to convert Markdown to the corresponding writer format using the user-provided defaults file
* An "advanced" exporter would then be a built-in exporter that does something different or doesn't use Pandoc at all (the Chromium PDF writer, or the Textbundle exporters, for example)
* A "custom" exporter, then, would be just a text editor where you can put some custom shell script in that you can then access via some name

In order to make that secure, we could prevent malicious software from adding shell scripts to the script directory by signing the scripts using the application UUID (so that valid scripts must be created and edited via Zettlr itself, that would also enable us to add, as Albert has once put it, "a big fat warning" to prevent people from just copying and pasting some arbitrary code from the internetz™). If security is really important, instead of the UUID (which could, in theory, be read by said malicious software), we could also enforce password-protection.

I figure that would give a lot of possibilities to people, with reasonable security, lots of flexibility, and the ease of accessing scripts via a GUI instead of having to head into the terminal. Thoughts? CC @tobiasdiez @tarleb @xldrkp 

***

N.B.: Those scripts could look like this:

```bash
#! /usr/bin/bash

SOURCE_FILE="$1"
USER_DEFAULTS_DIRECTORY="$2"
BUNDLED_PANDOC_PATH="$3"
SOME_ADDITIONAL_SETTING_FROM_ZETTLR="$4"

cp $SOURCE_FILE /some/dir
$BUNDLED_PANDOC_PATH $SOURCE_FILE --some-switch -t html5 -o temporary_file.htm

# ... and so on and so forth ...
```

**Comment by xldrkp** [comment]
@nathanlesage Sounds good to me! Although I think I'd be fine with "standard" and "custom". What you suggest for "advanced" could be an inspiring library of scripts that paste themselves in the mentioned text editor like the license dropdown in GitHub or GitLab. This way, people could get an idea of what is possible with the custom exporter. The security issue sounds well thought out to me. 

I like the idea that the exporter scripts are shareable code that can be used outside Zettlr as well, e. g. in a CI/CD pipeline.

**Comment by tobiasdiez** [comment]
Sounds like a good solution. However, I wouldn't add the shell script business to Zettlr. If the user can run an arbitrary command (with predefined argument expansions), then she could also easily write a own shell script that does more advanced steps.

For reference: https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#latex-recipes solves a similar problem in the latex world (where one needs to run certain tools in a certain order to get the desired result).

**Comment by nathanlesage** [comment]
> Although I think I'd be fine with "standard" and "custom". 

Yeah, the advanced stuff is just what I already implemented either way (I just thought it'd make sense to differ these from export formats that just take a defaults file and run Pandoc).

> then she could also easily write a own shell script that does more advanced steps.

The thing is that that is _always_ possible. You could completely do everything that Zettlr offers solely from within your terminal. Or, use Zettlr solely for writing Markdown and then use shell scripts to export/reformat/whatever it. And some people already do that. So the whole purpose of a GUI application is just that it's easier and looks nicer. That being said, there are certain things even a GUI cannot anticipate and "arbitrary commands" are one of these things.

So instead of re-inventing the wheel here what my suggestion would do is simply give users an easier way of writing shell scripts for that exact purpose (and, if I'm not mistaken, Axel's project is currently doing exactly that using Zettlr). To be fair, you could just write those shell scripts in a dedicated editor and run them from the command line, but if you have the ability to just write such a script even if you're, say, on a friend's computer, and then execute it with the push of a button is easier and looks nicer. Plus, we don't have to invent anything Zettlr-specific – bash script can do all of the stuff, and I don't see a reason why we should develop our own solution when we can just use what's already there. We shalln't forget that designing a GUI can be quite difficult in and of itself …

So I'd suggest the following:

1. In the defaults window editor (which I have deliberately not yet put on Zettlr Translate because I figured we could use that window for a few more things than simply editing defaults files) add another tab next to Exports and Imports, called "Custom".
2. In there, add our big, fat warning and allow users to write custom shell scripts, which are subsequently accessible in the export window.
3. Test out things that work and don't work, such as: Does UUID-code-signing suffice, or should we use a user-provided password? What variables would we need on the command line? Stuff like that.

For this one, I'll be creating a PR, since it's a somewhat bigger feature, and I would like that one to be actually pen-tested. It's powerful, but also risky, so I think that's necessary.

So stay tuned, I think I'll get to that by June or something!

**Comment by tobiasdiez** [comment]
Sure, that works as well. My thought was just that you add quite some overhead for a relatively small benefit. It also opens spaces for additional improvements (code highlight, powershell instead of bash etc).

What about the following: You add a "custom exporter" field in the preferences, where users can specify a command that is executed in the users shell. Then users can for example specify a simple command (e.g. `pandoc %filename -some -custom -args`). This also gives the functionality to run an arbitrary script by using `bash path_to_my_bash_script`. I think it's safe to assume that people writing shell scripts have an code editor installed anyway.

**Comment by nathanlesage** [comment]
Hm, I think that's how Abricotine handles custom tasks … I'm not sure. Maybe I'm just biased against adding one single text input field with variables because we've had SO MUCH struggle with the Pandoc command field in the past.

**Comment by nathanlesage** [comment]
Bumping due to re-prioritization, now scheduled for next beta v3.0

**Comment by nathanlesage** [comment]
This feature is now in the dev branch and will ship with today's nightly. Please test to find out if it works as expected or if we have to adjust the feature.
