### ISSUE TITLE
Cannot find pandoc upon install

### ISSUE THREAD

**Issue by tobiasdiez** [Zettlr/Zettlr#1869]
Running `electron-forge start` on Windows 64 doesn't work and results in the following exception:
```
An unhandled rejection has occurred inside Forge:
Error: Failed to download Pandoc: Process quit with code 2. If the code is 0, then there was error output.
    at ChildProcess.<anonymous> (D:\Programming\Zettlr\forge.config.js:41:16)
    at ChildProcess.emit (node:events:369:20)
    at maybeClose (node:internal/child_process:1067:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)

Electron Forge was terminated. Location:
{}
error Command failed with exit code 1.
```
Running the get-pandoc manually yields more insight:
```
> bash ./scripts/get-pandoc.sh win32 x64
./scripts/get-pandoc.sh: line 2: $'\r': command not found
./scripts/get-pandoc.sh: line 6: $'\r': command not found
./scripts/get-pandoc.sh: line 12: $'\r': command not found
./scripts/get-pandoc.sh: line 17: $'\r': command not found
./scripts/get-pandoc.sh: line 20: syntax error near unexpected token `$'\r''
'/scripts/get-pandoc.sh: line 20: `if [ "$#" -eq 0 ] || ([ "$PLATFORM" != "darwin" ] && [ "$PLATFORM" != "win32" ] && [ "$PLATFORM" != "linux" ])
```

**Comment by nathanlesage** [comment]
I'm pretty sure your IDE - whichever you're using - or Git (since there is this weird option to add `\r`-characters on check-out) uses CRLF instead of simple LFs, because there seem to be `\r`-characters in there (which aren't in source control) and additionally, all the error lines correspond to empty lines (e.g., if you're using CRLF, this looks like `\n\r\n` for the interpreter).

Could you confirm this?

I can confirm that everything works on a brand-new Windows 10 x64 computer which I've just finished setting up this morning; forge was able to successfully download Pandoc here.

**Comment by tobiasdiez** [comment]
That could be the problem indeed. I was in a hurry so I didn't had time to further investigate.

I have `autocrlf=true` enabled, so all files are automatically have `\n\r` as line break, as most Windows-based tools need this. But of course this doesn't work for bash scripts which are invoked. Fix should be simple by adding a `.gitattributes` file setting the line ending for all bash scripts by `*.sh text eol=lf`.

**Comment by nathanlesage** [comment]
If that's what it fixes, feel free to open a PR :)
