### ISSUE TITLE
Cannot compile latest dev build on Windows x64: Error:  Failed to download Pandoc

### ISSUE THREAD

**Issue by RandBY** [Zettlr/Zettlr#1871]
## Description

Cannot compile latest dev build on Windows  x64
## Reproducing

yarn start 

![Zettlr issue](https://user-images.githubusercontent.com/69441779/114136149-6a4c9c00-9949-11eb-810c-aabf8d13115c.JPG)

## Expected behaviour

Zettlr application starts.

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.8.7

**Comment by nathanlesage** [comment]
The get-pandoc script requires Bash, so you need to make sure to have, e.g., git bash installed. If you just want to get it running, download Pandoc manually (using the links in the get-pandoc.sh script) and place it in the "resources" directory with the name `pandoc-win32-x64.exe`. This will circumvent the download process altogether.

**Comment by RandBY** [comment]
Thank you @nathanlesage . Unfortunately, that did not work with me and I already had git bash installed.

**Comment by nathanlesage** [comment]
@RandBY What exactly didn't work? Running the script normally, or having Pandoc placed in the resources directory?

**Comment by RandBY** [comment]
@nathanlesage Running the script and starting the app. Although I followed your advice by downloading Pandoc, renaming and moving it to the resources directory, I keep receiving the same exact error.

**Comment by nathanlesage** [comment]
Hm … `pandoc-win32-x64.exe` works if you're on a 64 bit windows. Basically, the file should be named `pandoc-{platform}-{arch}.exe` where platform and arch correspond to whatever `process.platform` and `process.arch` returns.

Ah … wait. And I believe it requires a bash-installation, so installing Git might be necessary; I'm not sure whether windows ships with `bash.exe` itself (which is required since neither the Windows command line nor PowerShell understand bash script)

**Comment by RandBY** [comment]
Hi @nathanlesage , I figured out that I was trying to run the commands via **cmd** instead of **Git Bash**. Thank you for your help.
