### ISSUE TITLE
Difficult to write in-text citations under the format "author (year)"

### ISSUE THREAD

**Issue by Klemet** [Zettlr/Zettlr#1872]
## Description
From what I understand, according to the [Pandoc citation syntax](https://pandoc.org/demo/example19/Extension-citations.html), it should be possible to use in-text citation by only using the "@" without any square brackets.

From the documentation : 

> You can also write an in-text citation, as follows:
> @smith04 says blah.
> @smith04 [p. 33] says blah.

However, when I try this in Zettlr,
- [@smith04] will result in (Smith, 2004)
- @smith04 will also result in (Smith, 2004)

Making it impossible to easily write a sentence like "As said by Smith (2004),..."

The only current workaround I know of is to use [-@smith2004], which removes the author from the citation, resulting in writing only "(2004)"; but then, one has to copy/paste the name of the author in front of it, reducing the advantage of having the implementation of citations.

This problems (if it is one) happens both in the Zettlr interface, and in the exports.

## Reproducing

- Open a new document
- Make a citation in text by using "@authorYear", without any square braquets

## Expected behaviour
If I'm not wrong, Zettlr should be able to allow the writing of in-text citations in the format of "Smith (2004) says blah."; meaning no brackets around the author, but brackets around the year.

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.8.7

I apologies in advance if I misread the pandoc citation syntax, and this is indeed not a bug !

**Comment by nathanlesage** [comment]
Technically, writing `@smith1234` is the same as `[@smith1234]`, so I have Zettlr automatically add the square brackets (since they allow you more flexibility). However, I have also come to the conclusion that if you want to exclude the author name, and you write `-@sm` and then let autocomplete take over, it will result in `-[@smith1234]` instead of `[-@smith1234]`. This is on my radar and I will make sure that the autocomplete will pull in a hyphen character if it directly preceeds the @-sign.

This way you can write more naturally and, if you want to exclude the author, simply write a hyphen, then the @, and let autocomplete fetch the correct citekey. But please feel free to test certain edge cases. Note that you will have to _export_ rather than just view it in Zettlr, since the Zettlr built-in previewer is just that: A citation previewer that is not as sophisticated as citeproc.

**Comment by Klemet** [comment]
Thank you for your answer, @nathanlesage !

However, I don't think that @smith1234 and [@smith1234] are supposed to be the same. To make sure, I installed Atom, and used the package `markdown-preview-plus` to allow for pandoc-citeproc to display the citations in a preview. This is the result : 

![image](https://user-images.githubusercontent.com/41070328/114284415-b832d400-9a1d-11eb-9c70-4cc8d307605c.png)

As you can see, @dijkstraNoteTwoProblems1959 results in "Dijkstra (1959)", which is an in-text citation. However, [@dijkstraNoteTwoProblems1959] results in "(Dijkstra 1959)", which I would call an in-bracket or out-of-text citation. Another problem is that this behaviour is also there in the export of Zettlr documents; so it doesn't seem to be a problem limited to the Zettlr previewer.

The problem with the workaround that I found (e.g. writing "Dijkstra [-@dijkstraNoteTwoProblems1959]" as shown in the image) is that you have to go and copy past the author's names, or format it/them by yourself. This, in return, completely break the advantage of having this citation system which is supposed to format things for you, or to quickly gather the information with the autocomplete.

Does that makes sense ? I'm really sorry if it sounds like I'm nitpicking, but in-text citations in the format of "Dijkstra (1959)" is something that I use pretty often; so it's becoming more and more limiting with time for me.

**Comment by nathanlesage** [comment]
Ah, I see what you mean.

The basic problem is that the citeproc documentation is not very clear on how something should look like.

To me, it seems that citeproc's rule to follow is "If the citation is without bracketrs, treat it as if you should suppress the author using a hyphen". If so, that should be pretty easy to implement.

Could you be so kind to test this intuition out so that we can be certain of citeproc's behaviour?

Then the next thing would be of how to also allow citations without brackets. Because while I totally get it that writing the citekey without square brackets is easier during writing flow, having the engine automatically add brackets comes in useful a lot of times for more complex citations as well, and we need to reconcile these two behaviours.

**Comment by Klemet** [comment]
I completely agree that the citeproc documentation is not very clear; before I tested things with Atom, I was pretty unsure myself.

In my point of view, the rule is rather "if the citation is without brackets, put the author(s)'s name(s) out of brackets, but put the year inside brackets", which translate to what I call an "in-text" citation looking like that : "`As shown in Dijkstra (1959)`".In that way, **both the author(s)'s name(s) and the date in brackets are part of the citation**. Hence, the user don't have to copy/paste the author(s)'s name(s), or format them themselves.

I made a couple more tests in Atom, if this can help you. I just copy/pasted the result as HTML code here, so nothing is altered. Each time, the only thing that is not changing is the "This is shown by" sentence. The markdown I used is in the titles, and the results are just bellow :

* * *

<h1 id="testing-citations-with-pandoc">Testing citations with Pandoc</h1>
<h3 id="dijkstranotetwoproblems1959"><code style="font-family: Palatino, Menlo, Consolas, &quot;DejaVu Sans Mono&quot;, monospace;">@dijkstraNoteTwoProblems1959</code></h3>
<p>This is shown by <span class="citation" data-cites="dijkstraNoteTwoProblems1959">Dijkstra (1959)</span>.</p>
<h3 id="dijkstranotetwoproblems1959-1"><code style="font-family: Palatino, Menlo, Consolas, &quot;DejaVu Sans Mono&quot;, monospace;">[@dijkstraNoteTwoProblems1959]</code></h3>
<p>This is shown by <span class="citation" data-cites="dijkstraNoteTwoProblems1959">(Dijkstra 1959)</span>.</p>
<h3 id="dijkstranotetwoproblems1959-2"><code style="font-family: Palatino, Menlo, Consolas, &quot;DejaVu Sans Mono&quot;, monospace;">-@dijkstraNoteTwoProblems1959</code></h3>
<p>This is shown by <span class="citation" data-cites="dijkstraNoteTwoProblems1959">(1959)</span>.</p>
<h3 id="dijkstranotetwoproblems1959-3"><code style="font-family: Palatino, Menlo, Consolas, &quot;DejaVu Sans Mono&quot;, monospace;">[-@dijkstraNoteTwoProblems1959]</code></h3>
<p>This is shown by <span class="citation" data-cites="dijkstraNoteTwoProblems1959">(1959)</span>.</p>
<h3 id="dijkstranotetwoproblems1959-4"><code style="font-family: Palatino, Menlo, Consolas, &quot;DejaVu Sans Mono&quot;, monospace;">-[@dijkstraNoteTwoProblems1959]</code></h3>
<p>This is shown by -<span class="citation" data-cites="dijkstraNoteTwoProblems1959">(Dijkstra 1959)</span>.</p>
<h3 id="dijkstranotetwoproblems1959-and-dijkstranotetwoproblems1959"><code style="font-family: Palatino, Menlo, Consolas, &quot;DejaVu Sans Mono&quot;, monospace;">@dijkstraNoteTwoProblems1959 and @dijkstraNoteTwoProblems1959</code></h3>
<p>This is shown by <span class="citation" data-cites="dijkstraNoteTwoProblems1959">Dijkstra (1959)</span> and <span class="citation" data-cites="deanFindingOptimalRoutes1997">Dean (1997)</span>.</p>
<h3 id="dijkstranotetwoproblems1959-and-deanfindingoptimalroutes1997"><code style="font-family: Palatino, Menlo, Consolas, &quot;DejaVu Sans Mono&quot;, monospace;">[@dijkstraNoteTwoProblems1959 and @deanFindingOptimalRoutes1997]</code></h3>
<p>This is shown by <span class="citation" data-cites="dijkstraNoteTwoProblems1959">Dean (1997)</span>.</p>
<h3 id="dijkstranotetwoproblems1959-and-deanfindingoptimalroutes1997-1"><code style="font-family: Palatino, Menlo, Consolas, &quot;DejaVu Sans Mono&quot;, monospace;">[@dijkstraNoteTwoProblems1959; and @deanFindingOptimalRoutes1997]</code></h3>
<p>This is shown by <span class="citation" data-cites="dijkstraNoteTwoProblems1959 deanFindingOptimalRoutes1997">(Dijkstra 1959; and Dean 1997)</span>.</p>
<h3 id="dijkstranotetwoproblems1959-and--deanfindingoptimalroutes1997"><code style="font-family: Palatino, Menlo, Consolas, &quot;DejaVu Sans Mono&quot;, monospace;">[@dijkstraNoteTwoProblems1959; and -@deanFindingOptimalRoutes1997]</code></h3>
<p>This is shown by <span class="citation" data-cites="dijkstraNoteTwoProblems1959 deanFindingOptimalRoutes1997">(Dijkstra 1959; and 1997)</span>.</p>

* * *

As you can see from those results : 

- Using a citation without brackets (e.g. @authorsDate ) results in the format "Author(s)'s name(s) (date)"
- The citations -@authorsDate and [-@authorsDate ] give the same result; because in both cases, we take away the author(s)'s name(s), but that leaves the date inside brackets in both cases.
- The citation -[@authorsDate ] doesn't work : it only results in the hyphen being in front of the citation.
- Using in text citations (without brackets) makes it easy to cite different authors (e.g. @authorsDate and @authorsDate )
- It's possible to use the hyphen inside brackets to remove the author(s)'s name(s) of one of the citation inside the brackets; but one has to always respect the rule that inside brackets, citations **must be separated by a semi column** (;).

I hope that this will help : ).

Finally, do you have examples in mind where automatically adding brackets around the whole citation when not writing the square brackets around it would be helpful ? Personally, I thought that the distinction between the two (@authorsDate and [@authorsDate ]) is quite elegant and easy to remember. But I can't speak for other users. Maybe inserting a section in the Zettlr tutorial concerning the citations could help users, like a cheat-sheet ? Seeing that citations are a big part/advantage of Zettlr, I think it could be helpful.

**Comment by nathanlesage** [comment]
> I hope that this will help : ).

It most certainly does, thank you! This confirms that the general distinction for Citeproc seems to be solely around the placement of the author's name (which is most likely also influenced by the used CSL style, but that's not important for Zettlr's preview, as you can choose your CSL style for exporting).

The question now remains how do we get `citeproc-js` to follow that rule ...? I'll be asking them if I don't find the answer myself.

As for the issue when to choose square brackets vs. the vanilla citekey: I have no idea. In the end, you'll always need them if you want to cite additional stuff. The citeproc docs indicate that additional information can be put in square brackets immediately following the cite-key, but that's an option we (in my opinion) don't need to support, since it is no different to "everything in square brackets" and adds unnecessary bloat to the app. But the real core issue is: No app can foresee if you need to add more stuff (such as page numbers) frequently, or not. I know that in CS, for instance, you normally only cite the paper itself, and never individual page numbers, so there the plain style would be the way to go. However, in the social sciences, you are expected to indicate page numbers wherever possible, so there the (current) behaviour is the best one (which is why I implemented it in the first place).

So the easiest workaround would be to add an option to let users enable and disable the automatic bracket addition so that users who only seldomly need additional citation info can add those brackets themselves, and those who often need additional citation info can remove the square brackets if wanted.

**Comment by Klemet** [comment]
> that's an option we (in my opinion) don't need to support, since it is no different to "everything in square brackets"

I understand that it's adding more code to the app, which is always something to avoid; and I really don't want to ask for a feature that nobody wants excepts me ! But I think that in-text and in-bracket (if I can call them that) citations are still quite different. I also think that it's the reason why pandoc-citeproc distinguishes the two : both of them are often seen in scientific articles, at least in my field (ecology).

Plus, pandoc seems to deal with additional details (pages, chapters) really well for those in-text citations : 

* * *
<h3 id="dijkstranotetwoproblems1959-p.-33"><code style="font-family: Palatino, Menlo, Consolas, &quot;DejaVu Sans Mono&quot;, monospace;">@dijkstraNoteTwoProblems1959 [p. 33]</code></h3>
<p>This is shown by <span class="citation" data-cites="dijkstraNoteTwoProblems1959">Dijkstra (1959, 33)</span>.</p>
<h3 id="dijkstranotetwoproblems1959-pp.-33-35-38-39"><code style="font-family: Palatino, Menlo, Consolas, &quot;DejaVu Sans Mono&quot;, monospace;">@dijkstraNoteTwoProblems1959 [pp. 33-35, 38-39]</code></h3>
<p>This is shown by <span class="citation" data-cites="dijkstraNoteTwoProblems1959">Dijkstra (1959, 33–35, 38–39)</span>.</p>
<h3 id="dijkstranotetwoproblems1959-chap.-1-pp.-33-35"><code style="font-family: Palatino, Menlo, Consolas, &quot;DejaVu Sans Mono&quot;, monospace;">@dijkstraNoteTwoProblems1959 [chap. 1 pp. 33-35]</code></h3>
<p>This is shown by <span class="citation" data-cites="dijkstraNoteTwoProblems1959">Dijkstra (1959, chap. 1 pp.&nbsp;33-35)</span>.</p>

* * *

I think that leaving the choice to users to enable or disable this aspect is interesting; and I'm afraid that this will be a bit difficult to convey the difference between the two for the user (and still result in more code, if I'm not mistaken ?). I personally think that i t would be clearer to put it this way : 

> *If you want in text-citation, don't use brackets; if you want all of your citation in brackets, use brackets; if you want to add details to an in-text citation, put it into brackets; for the rest, check the pandoc doc.*

However, I'm far from being a software creator, and I'm sure that you and the rest of the Zettlr team will figure out the best way : ). Thank you for the exchange, and good luck ! I'd have been glad to propose a commit, but I'm still not used to Typescript/Java/etc.

**Comment by nathanlesage** [comment]
> and I'm afraid that this will be a bit difficult to convey the difference between the two for the user

Absolutely, but I have added the auto-addition of square brackets for a reason … it's super difficult to do this all the time :D With the square brackets being automatically added it's much easier to write in-bracket-citations.

However, I'll be looking into that one.

**Comment by nathanlesage** [comment]
Btw I've just adapted the title from "Impossible" to "difficult", since you are indeed able to write the citekeys standalone such that citeproc will process them correctly, it's just a hassle.

(I figure that potentially users would only look at the title and then be like "Nah, that thing doesn't work")

**Comment by dekuenstle** [comment]
> The question now remains how do we get `citeproc-js` to follow that rule ...? I'll be asking them if I don't find the answer myself.

Pandoc does in-text citation (e.g. no bracket), by adding two citation items: One type *author-only* and one type *suppress-author*.
https://github.com/jgm/pandoc/blob/dc0ba7294d9c40987b016ac886440a85ade8ae44/src/Text/Pandoc/Citeproc.hs#L347

> So the easiest workaround would be to add an option to let users enable and disable the automatic bracket addition so that users who only seldomly need additional citation info can add those brackets themselves, and those who often need additional citation info can remove the square brackets if wanted.

I would also suggest this option for the default in-text vs normal-cite (e.g. auto-brackets).  As you said, the default depends a lot on the subject.

**Comment by nathanlesage** [comment]
Holy hell, you manage to read the Haskell source of Pandoc, I salute you! But that is actually quite helpful going forward!

**Comment by dekuenstle** [comment]
Please tell how to support you with this Issue. The full power of pandoc citations (as in @Klemet examples) would make academic notetaking with zettlr even more fun.

Just a wild idea (I did not check the internals of zettlr): Wouldn't it be possible to use pandoc for parsing the markdown/citation?

**Comment by nathanlesage** [comment]
> Wouldn't it be possible to use pandoc for parsing the markdown/citation?

Possible: Yes. But unnecesarily resource-intensive, since we'd have to always spin up a secondary process with the full 100MB Pandoc binary in the background. I fear that this might have a non-trivial performance impact.

However, that's what Citr is for: It's a library (I just wanted to publish a library on NPM, there's literally no other reason why it's standalone) that is able to extract citations from any Markdown text and transform these into CSL JSON objects.

Basically, if Pandoc's Citeproc does `Markdown --> CSL JSON --> Rendered citation`, Citr does `Markdown --> CSL JSON`, because for `CSL JSON --> Rendered citation` we're using citeproc-js, which does a really good job.

That being said, we would need two changes: First, empower Citr to extract those citations, and maybe even also return locations where the citations have been found so that the CodeMirror plugin can then transform them into Markers.

Relevant links:

* Citr: https://github.com/Zettlr/Citr
* The CodeMirror plugin: https://github.com/Zettlr/Zettlr/blob/develop/source/common/modules/markdown-editor/plugins/render-citations.js
* The provider that takes CSL JSON and returns rendered citations: https://github.com/Zettlr/Zettlr/blob/develop/source/app/service-providers/citeproc-provider.ts (be careful, the logic is pretty fragile I think)
* Please note that the Sidebar also extracts all cited items (it could also include the `nocite`-frontmatter property, which I didn't implement yet) to retrieve the full bibliography: https://github.com/Zettlr/Zettlr/blob/develop/source/win-main/Sidebar.vue

**Comment by yaxu** [comment]
Hello I'd like to add my voice in support of this feature. I think I was the one to request this feature in pandoc in the first place. It came from the \citet and \citep that I enjoyed using in LaTeX: http://merkel.texture.rocks/Latex/natbib.php

I also noticed that a non-parenthetical citation needs whitespace around it, and therefore doesn't render in zettlr at the end of a sentence or clause e.g. `@franklin1999.` won't show the reference because the period stops it from finding the right reference.

**Comment by camilstaps** [comment]
At least since https://github.com/Zettlr/Citr/commit/40aa7d18b6578fb850cfbd4d8da7bb93e7284e54#diff-ac3670f141fd38205fa393b40d051187d901450cb50b9a9cfe8bda1d436e6a12 it seems that Citr at least recognizes these identifiers, but apparently [`parseSingle`](https://github.com/Zettlr/Citr/blob/9549b621af01a222d5895413ee2c9dde435e4a03/lib/citr.ts#L64-L74) does not return the right cite item for citeproc-js.

It seems that with citeproc-js you can use `author-only` to get the author without any other info, and `suppress-author` to get the citation without author information (https://citeproc-js.readthedocs.io/en/latest/running.html#citation-flags-with-makecitationcluster). So I think that for `@Franklin1999` you can join the results for `{"Franklin1999", "author-only": true}` and `{"Franklin1999", "suppress-author": true}` by a space.

I think the way `parseSingle` is set up currently does not allow you to return that kind of information (that you have two citations and want them joined by a space). Maybe the return value of `parseSingle` should be extended to get that info across?

**Comment by nathanlesage** [comment]
Yeah, over the past weeks of having let that sink I've come to the realization that I'll be merging Citr into the app (which makes adapting simpler) and then giving it a quick overhaul, so that it can, i.e., detect `@citekey [locators]` among other things and finally render everything correctly!

**Comment by nathanlesage** [comment]
Fixed in the most recent commit!

**Comment by yaxu** [comment]
Thanks @nathanlesage you're a superhero!

**Comment by Klemet** [comment]
Citr is going to be used in Zettlr ? That's awesome ! I'm impatient to try it. Thank you so much, @nathanlesage !

**Comment by nathanlesage** [comment]
> Citr is going to be used in Zettlr ?

To clarify: It's *not* the R-package Citr :D

**Comment by Klemet** [comment]
> To clarify: It's not the R-package Citr :D

I stay by my statement that this will look awesome anyway, and that I'm still very impatient to try it :D !

**Comment by nathanlesage** [comment]
Okay :D Feel free to download the beta.5, it's basically the final stable version, there are only extremely minor points to be changed until stable, so you don't have to wait!
