### ISSUE TITLE
create new note when double clicking in a folder

### ISSUE THREAD

**Issue by ploum** [Zettlr/Zettlr#188]
Creating a new note is a tedious process :  going to the icon, typing the title (I've never have any idea about what title I should put when I start a note).

I would suggest that you could create a new note by simply double clicking in an empty space of the current folder. The new note would be called "new note 21". The name of the note should be the first title above and, of course, you could change it in the editor.

I realise that this implies merging the filename with the first title of the note. I think it something cool but to discuss.

**Comment by nathanlesage** [comment]
Better idea:

- Add a preferences option for automatic file names so that you just can use the strokes `Cmd+N` + `Return` to immediately create a unique note in the folder
- Add a preferences option to automatically rename the files on changes based on the first title in the file (which would then resemble the way Ulysses does this)

**Comment by dambaras** [comment]
How about: New note is named with ID number (as in The Archive), with preferences option to add first title after that.

**Comment by nathanlesage** [comment]
ID as a variable was meant to be included, no worries :)

**Comment by ploum** [comment]
If the automatic filename option is enabled, I would even remove the need for the "return". The note is created, that's it. That removes one useless step (pressing enter) which is out of the workflow (the naming dialog is out of the note space, which makes it "out of workflow" for me)

**Comment by nathanlesage** [comment]
Good point.
