### ISSUE TITLE
Citation fails with semicolon

### ISSUE THREAD

**Issue by JCalinawan** [Zettlr/Zettlr#1883]
Hello,

Thank you for this app. It's amazing! I'm reporting an issue. If a citation has a semicolon like in the form, [@author, p.100; emphasis added], the proper citation will not be generated at export time. Is this a bug or am I missing a citeproc setting? Thanks in advance for your help.

Regards,
Jonah

**Comment by nathanlesage** [comment]
Yes, you can only use semicolons to delimit multiple citations, not to add any prefix or suffix. Since citations can be written in a fairly natural language matter (and programs are not that smart in seeing what that should result in) they have to make some concessions; one of them is that you can't use semicolons within square brackets other than for delimiting citations. So each semicolon must be followed by some string that contains a valid citation key:

```
Valid: [something @AuthorYear; another @AnotherAuthorYear, p. 256-257]

Invalid: [something @AuthorYear; something]
```
