### ISSUE TITLE
Zettlr adds `\` when pasting

### ISSUE THREAD

**Issue by indirection** [Zettlr/Zettlr#1894]
## Description
Copy a string with `\` and an additional `\` is added. 

### 1. paste within `code block`:

… copied string was: ` '%*s\n' `

… Zettlr pasted:       ` '%*s\\n' `

`printf  '%*s\\n'  "$(tput cols)"  '' | tr ' '  '#'`

### 2. paste in _non-code block_:

printf  '%*s\\\n'  "$(tput cols)"  '' | tr ' '  '#'

## Expected behaviour
Paste text as copied. 

<img width="1322" alt="Screen Shot 2021-04-24 at 1 50 32 PM" src="https://user-images.githubusercontent.com/398047/115968613-bfbaa880-a506-11eb-9930-0a538b1e1cb5.png">

## Platform
 - OS and version: macOS 10.15.7
 - Zettlr Version:    Version 1.8.7 (1.8.7)

## Additional information
I'll submit another bug for the inability to step out of a `code block` if at the end of the document.

**Comment by nathanlesage** [comment]
That's because Zettlr by default looks up if there is any HTML in the clipboard and pastes that instead of the plain text. The reason is that most text (Word, for instance) also contains some formatting (emphasis, bold text, etc) and in general that's what most people would like. However, that also means we're internally processing the HTML to Markdown, and that process also includes escaping of (potentially) problematic characters.

Thus, if you want to paste just the plain text as-is, select "paste without style" (`Cmd/Ctrl+Shift+V`), which will just insert whatever is in the plain text clipboard and do not any processing to it. This behaviour, unfortunately, will differ between apps (pasting _with_ style is almost impossible with MS Office apps, since these even put an image of the selected text into the clipboard; don't ask me why…).

Can you confirm this?
