### ISSUE TITLE
Open Zettlr, deni internet access, two errors windows, then loads app and files

### ISSUE THREAD

**Issue by indirection** [Zettlr/Zettlr#1896]
## Description

Open Zettlr, use firewall to deni internet access. Two errors are presented, then Zettlr starts and opens files. 

## Reproducing

See image sequence below. 

Here is text from one of the error dialog boxes:
```
Uncaught Exception:
RangeError [ERR_OUT_OF_RANGE]: The value of "err" is out of range. It must be a negative integer. Received 536870212
    at Object.getSystemErrorName (util.js:231:11)
    at exceptionWithHostPort (internal/errors.js:535:21)
    at internalConnect (net.js:923:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:351:12)
    at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1063:9)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:68:8)
```
#### 2. Block Internet Access

<img width="748" alt="Screen Shot 2021-04-24 at 2 52 46 PM" src="https://user-images.githubusercontent.com/398047/115969903-5ab68100-a50d-11eb-81da-39f5d7a9f528.png">

#### 4. Error:

<img width="425" alt="Screen Shot 2021-04-24 at 2 52 58 PM" src="https://user-images.githubusercontent.com/398047/115969918-5e4a0800-a50d-11eb-8081-f1a36919f0ef.png">

#### 5. Error:

<img width="424" alt="Screen Shot 2021-04-24 at 2 53 11 PM" src="https://user-images.githubusercontent.com/398047/115969922-6144f880-a50d-11eb-95d1-88800530638a.png">

#### 6. Zettlr starts

<img width="930" alt="Screen Shot 2021-04-24 at 2 53 57 PM" src="https://user-images.githubusercontent.com/398047/115969926-63a75280-a50d-11eb-991a-f02443a82e30.png">

## Platform
 -   OS and version: macOS 10.15.7
 -   Zettlr Version: Version 1.8.7 (1.8.7)

**Comment by nathanlesage** [comment]
Mh, this might seem like a bug in the internals of Electron or Node itself, since the error traceback only displays internal function calls. Additionally, the errors only happen since Zettlr wants to check for update which it obviously can't, that's why afterwards the program works just fine. I'm not sure there's anything I can do. Would you mind trying this trick with another electron app that tries to connect to some internet API and see what happens? (e.g., Slack, MS teams or something like that)
