### ISSUE TITLE
automatically hides last lines of working document

### ISSUE THREAD

**Issue by febr3s** [Zettlr/Zettlr#1918]
Hello. When I'm editing a text, it automatically scrolls up, hiding the last four or five lines. However, the scroll shows as if it were still at the bottom of the document. It is extremely annoying. Thanks!

![image](https://user-images.githubusercontent.com/33102833/116281715-fb987c80-a757-11eb-9261-00aa78062c38.png)

**Comment by nathanlesage** [comment]
… we have issue templates, which would've helped me seeing which version you're using. Because just a screenshot doesn't convey much context.

**Comment by willfe** [comment]
FWIW, I'm seeing identical behavior on `v1.8.7`. If I'm typing near/at the end of a document that's long enough to have a scrollbar, after a few seconds the view will scroll up, usually scrolling the cursor (and whatever text I'm actively typing) off screen. The scrollbar still indicates that the view is showing the bottom of the document. Typing anything (even just one character) will scroll the cursor back into view, though it usually doesn't restore the view exactly (it just scrolls enough to show the cursor instead of going back to the exact scroll position prior to scrolling up).

This happens pretty consistently for me. I don't think I've been able to edit any document that I can recall where this doesn't start happening once it's long enough to have a scroll bar.

To reproduce:
* Create a new document.
* Paste a whole bunch of paragraphs into it from, e.g. a lorem ipsum generator, so that the document is long enough that it becomes scrollable.
* For good measure, use a Markdown feature or two, such as making some of the pasted text into an unordered list. I don't know for sure that this is required to trigger the behavior, but it's something my documents all have in common, so I mention it just in case.
* Scroll down to the end of the document and type out a few words, then wait for a few seconds. Usually it happens for me within 5-10 seconds, but sometimes it can take up to 30 seconds.
* The viewport will scroll up on its own without user input, and the cursor will no longer be visible (as it is now below the viewport).
* Type something (anything will do), and the viewport will scroll down just enough to make the cursor visible again.
* Wait again, and the viewport will scroll back up again, hiding the cursor once more.
* Scroll down with the mouse to make the cursor visible again.
* Wait again, and the viewport will scroll back up again just as before.
* This is repeatable. No matter how many times you scroll the viewport back down so you can see the cursor (and no matter how you do it -- typing, dragging the scroll bar, scrolling the mouse wheel, using cursor movement keys, etc.), the viewport will reliably scroll up again on its own every time once this behavior is triggered. [1]

I'd be happy to furnish configuration details and/or perform specific tests if needed.

[1]: I'm not 100% sure whether this happens in all documents and all sessions and I've just gotten used to it, or if it starts happening after a certain period of time, or if it's triggered by some other action or event. It does happen very frequently though and I can't recall any editing session where it _hasn't_ happened.

**Comment by nathanlesage** [comment]
@willfe Mh, I think the first thing to check would be whether it happens in the current 2.0-dev branch as well. We had quite a few bugs in the past like this one, but I've made sure to go over every instance of problematic behaviour and now the editor behaves much more consistently. However, I can't yet provide any pre-built releases for the 2.0-branch, because the styling on Linux is still non-existent and I haven't had time to do that.

**Comment by willfe** [comment]
Roger. I'll grab the sources and try to get 2.0-dev built on my Win10 64-bit machine (lol wish me luck 😂), and see how it behaves. Thanks!

**Comment by nathanlesage** [comment]
Thanks for helping out with that! :)

**Comment by willfe** [comment]
Aaack! I got swamped and haven't had a chance to test this. I'll make some time this week to (finally) dive in and check this out again. Sorry for the delay.
