### ISSUE TITLE
Single quote in French

### ISSUE THREAD

**Issue by ekkipatang** [Zettlr/Zettlr#1920]
## Description

In French, the single quote character is strangely displayed as a single bracket. 

## Reproducing

Juste press single quote on keyboard

## Expected behaviour

Display single quote

![Screenshot_20210428_143650](https://user-images.githubusercontent.com/76942940/116407248-dd06b400-a831-11eb-9af4-ddd6ac3b56b6.png)

## Platform
 - OS and version: Kubuntu 20.04
 - Zettlr Version: 1.8.7

## Additional information

Other software displayed single quote as expected. Keyboard parameters are checked and ok.

**Comment by nathanlesage** [comment]
That's because the program cannot differentiate between beginning and ending of a quotation, encapsulated in single quotation marks, and abbreviated expressions; so it cannot see if you're going to type in a "L'état c'est moi" or "Il dit «Sacre bleu»" (but with single French quotes, didn't find them quickly on my keyboard).

That being said, unless you really need them, I'd suggest to set the single quotes in your preferences to something suitable (which is what I'm doing for when I'm typing German as well)

**Comment by ekkipatang** [comment]
thanks for your help ! 
By searching a little, I did what you suggested and it works !

Once you have selected the preferred language for the software, it's not obvious that you have to specify which kind of single quote you want to use. Usually this is set automatically.
Moreover, the french pre-selection below set single bracket instead of single quote. Maybe it could be fixed.

**Comment by nathanlesage** [comment]
Well, in the AutoCorrect section I simply added every single combination of double- and single quotes that I could find, just so that all eventualities are covered. With regard to the automatic selection that might be an interesting thought … however, upon thinking: Many people might just want to stick to the default (" and ') instead so that might upset these people. I mean, you can direct Pandoc to automatically replace these with the correct quotes upon export.
