### ISSUE TITLE
TeX files get included into export.tmp when building a project

### ISSUE THREAD

**Issue by frederik-elwert** [Zettlr/Zettlr#1924]
## Description

I have a custom template that I keep with the .md files of my project. However, when I export the project, it fails with a LaTeX error. Inspecting the export.tmp file Zettlr produces I found that the verbatim content of my template was also included when gathering the input files.

## Reproducing

* Create a project
* Add some test markdown files and a .tex file into the project directory
* Export

## Expected behaviour

Zettlr should ignore .tex files when bundling the input.

## Platform
 - OS and version: Ubuntu 20.04
 - Zettlr Version: 1.8.7

## Additional information

I can fix this by just moving the template into a separate directory, but the default behaviour is still confusing.

**Comment by nathanlesage** [comment]
That is wanted behaviour, and [even documented](https://docs.zettlr.com/en/academic/projects/): The reason we have this is since you may want to include graphics or huge tables that come from an external program.

Imagine you're using some Python script to run several models on some data, and then you want to compare their performance. So you calculate some measures and now you want to include these in a project of yours. Wouldn't it be awesome to have your Python script just output some .TeX-file simply containing these numbers into your project directory, and then re-exporting it? The reason why TeX-files are also included is simply because Markdown tables are somewhat limited so in some cases you might want to directly write those as TeX-code.

I'm right now working on a project where I will need precisely this behaviour.

Are there any insurmountable roadblocks you see with putting templates into their dedicated templates folder instead of on a per-project basis …?

**Comment by frederik-elwert** [comment]
Oh, okay, wasn’t aware of this.

Of course this is not insurmountable. But there are cases where I have a dedicated template for a single project, and I thought it would make sense to keep it together with other auxiliary files like the bibliography and CSL in the project directory.

I guess this only works because pandoc supports raw LaTeX in markdown, right? So I guess to support this kind of generated output, one could also have the tex generated and save it in a .md file? Or even more cleanly, use pandoc’s output specific formatting:

    ```{=latex}
    my tex code
    ```

I think it would feel more natural to have a Zettlr project include only .md files (even if they contain latex fragments), and reserve .tex for templates. But maybe that’s just me.

**Comment by nathanlesage** [comment]
Yeah, I understand what you mean. However, I figured that it's easier both for separation of concerns and for syntax highlighting to have separate TeX files for that. Makes it cleaner (+ saves me the hassle of introducing another kind of syntax)

**Comment by nathanlesage** [comment]
Just saw that this issue is still open – version 2.0 will contain a glob filter so you can basically include/exclude those files that you want!
