### ISSUE TITLE
Under some circumstances, Zettlr's scroll jumps around

### ISSUE THREAD

**Issue by potato-aardvark** [Zettlr/Zettlr#1928]
## Description

In version `1.8.7`, under some circumstances, the view will jump around, as if I had scrolled upward. Sometimes, this scrolling will force the cursor out of view. The scrollbar doesn't change position until I scroll manually.

I ran some quick tests. It definitely happens after saving the document and after switching documents. 

It _might_ have other causes. ~~It seems to happen after scrolling with my mousepad (something weird happens when I use a two-finger scroll with the mousepad, and I'm not exactly sure what it is or if it's related to this issue). But this isn't easily reproducible.~~

Nope. Zettlr behaves differently depending on if my two-finger scroll is straight up/down or if it has more diagonal. The direction and speed both change. Not sure if intended. If not, I can create a separate issue since it looks like a different thing.

It might be related to #1918. In particular, it looks like the effects of #1918 are identical to this one, though maybe it has different causes, since I'm having trouble reproducing it without saving manually.

## Reproducing

Irregular scrolling after saving the document:
1. Create a file that is long enough to require scrolling (e.g., lipsum text). 
2. Scroll to the middle of the document (so that there is room to scroll up and down). 
3. Make a change to the document, then save with Ctrl+S.
4. The document view jumps around. The scrollbar doesn't move.

Irregular scrolling after changing documents:
1. Create two file that are long enough to require scrolling (e.g., lipsum text). 
2. Scroll to the middle of each document.
3. Save both. 
4. Switch between each one.
5. The document views jump around.

## Expected behaviour

In both situations, the view shouldn't move.

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.8.7

## Additional information

n/a

**Comment by nathanlesage** [comment]
That has been fixed in the 2.0 branch. Due to my limited time, there will be no backport to the 1.8-line of Zettlr. However, I'm aware of the mounting problems in 1.8.7 and currently my main priority is to get 2.0 into beta asap so that all can use that release where bugs such as this one are not happening anymore.

**Comment by cyannuremagik** [comment]
My two cents, as someone who also has a similar issue.

The auto scroll that happens seems to be directly related to auto-saving my documents in a sync folder. 
In my case all my notes are saved in a OneDrive cloud folder. 
Each change that is done to the .md is automatically saved and uploaded to the OneDrive.
This is the cause of the scrolling as, as soon as I disabled automatic syncing (pause for X hours or turn off OneDrive), the auto-scrolling behaviour does not occur anymore.
I can reproduce that behaviour and its fix 100%.

To avoid that I was hoping I could time the syncing (i.e. every hour, sync all file), alas Onedrive does not have such option.

Hope this helps with your problem until Zettlr 2.0 is out (exciting!)

**Comment by potato-aardvark** [comment]
Thanks so much! I went ahead and compiled the dev branch. The scrolling thing is indeed not there anymore.

I think @cyannuremagik makes a good point, and my experience in the release builds of Zettlr is similar to theirs. When I started working in the 2.0 branch I experienced the following instead:
1. With OneDrive sync enabled, I opened a file in my OneDrive folder and made an edit.
2. I saved the file.
3. A prompt appeared saying the file had been modified remotely and asking whether I would like to replace the loaded version with the one on disc. 

The expected behaviour is that the prompt doesn't appear.

Not sure if this is a Zettlr problem or a OneDrive problem, but either way I thought I'd make a note of it. I don't think it's particularly serious since as mentioned before OneDrive sync can just be temporarily disabled.

**Comment by nathanlesage** [comment]
> A prompt appeared saying the file had been modified remotely and asking whether I would like to replace the loaded version with the one on disc.

Yeah, I think the problem with OneDrive is that it changes the file metadata after a successful sync, and doesn't take the file on your computer as the source of truth. I suspect that, after the Microsoft server confirms that the file has been successfully uploaded, the OneDrive app on your computer changes the modification timestamp to match the one on the server. And that's where Zettlr detects a change in the file.

The reason is that it's computationally much cheaper to check for the timestamps than for the actual contents (small number vs. potentially large text data). Additionally, I don't really see any way to change that since the same problem does not appear when using Nextcloud, Dropbox, and box.com. It seems to be a Microsoft problem at this point. Or are there other opinions from people using different cloud storages?

**Comment by potato-aardvark** [comment]
Ooh, while troubleshooting another issue, I found a good resolution to this: Preferences > Advanced > checking "Activate Watchdog Polling" (and adjusting the time to wait as appropriate for the connection speed if required) solved the issue for me.
