### ISSUE TITLE
[ENHANCEMENT] Redo spell check after adding misspelled word to dictionary

### ISSUE THREAD

**Issue by Redsandro** [Zettlr/Zettlr#1946]
## Description

When you rightclick on a misspelled word and choose "Add [word] to dictionary", the word remains flagged as misspelled.

![image](https://user-images.githubusercontent.com/1702193/117816663-0b8b8280-b267-11eb-80bb-df0d981f35ec.png)

## Proposed Changes

Rescan the document for spelling after adding the word to the dictionary. 

## Additional Information

A workaround to quickly rescan the document for spelling is to click on the currently open note in the note sidebar on the left.

**Comment by nathanlesage** [comment]
The problem is you have to manually trigger a re-draw of the line in question (which will, after some delay, also update other instances above and below). However, I haven't so far found a way to do so programmatically; PRs welcome!

**Comment by Redsandro** [comment]
Thank you for explaining. I am not familiar with this framework. Give me some time to play more with Zettlr, and if I can figure something out, I will revisit this issue.

**Comment by raphraph** [comment]
I used to go to the Preferences dialog and click on the "Save preferences" button that used to exist in Zettlr prior to version 2.0. That was enough to update the spell check on all instances of the word added.

I don't know what that button used to trigger exactly but could it be possible to trigger something similar after adding a new term to the dictionary ?

I didn't know the workaround suggested by @Redsandro but will now use that since the save button is not there anymore.

**Comment by nathanlesage** [comment]
So, it should work now; Zettlr will now remove any spellcheck errors after adding a word to the dictionary. Redoing the full linting is unfortunately not possible, but this should be close enough of a visual help!

**Comment by Redsandro** [comment]
I'm looking at the commit, and I'm puzzled and pleasantly surprised. I was afraid this would require some draconian code.
I appreciate this, @nathanlesage!

**Comment by nathanlesage** [comment]
:D Luckily it didn't!
