### ISSUE TITLE
1.3 beta: non-working sidebar toggle (Windows)

### ISSUE THREAD

**Issue by davidbosman** [Zettlr/Zettlr#195]
The **Ctrl+Shif+1** toggle to show/hide the sidebar is not working under Windows. The attachement panel is working, though. (and its macOS equivalent is working fine)

Latest Zettlr beta running on an English Windows 10 Pro (1809), using either a French/azerty or US/qwerty keyboard.

**Comment by nathanlesage** [comment]
The problem is that sometimes Electron performs internal normalization which can yield unwanted results. For instance, on macOS the shortcut tells me `Cmd+!`, on Windows `Ctrl+Shift+1`. Maybe have a look in the View menu and see what Electron provides you with ...? It could be that it's also something like `!` instead of `Shift+1` (because `Shift+1` equals pressing `!` on a German layout)

**Comment by davidbosman** [comment]
I tried to reinstall Zettlr to no avail. Then I did a clean install of it, on a test account: the shortcut worked as expected. Time to do some cleaning on my user session I reckon ;)

**Comment by nathanlesage** [comment]
Argh, it's something I've been battling for months, as I can't convince electron to clear out the *full* cache on each restart ... but thanks for solving it! Let's hope it's just a remnant from an early version of Electron (I just realised that Zettlr has already had three Electron versions shipped!)
