### ISSUE TITLE
No Vim option in Editor mode

### ISSUE THREAD

**Issue by sadakmed** [Zettlr/Zettlr#1965]
I want to switch to VIM editor mode, but it shows only normal and emacs.
I think the documentation about settings editor is quite old, because it doesn't show the editor mode selection.

**Comment by nathanlesage** [comment]
Yes, the documentation has not received an update in quite some time, and yes, there is currently no way to select the Vim mode, because it broke at some point in the past. If I can get it working again for 2.0, I'll re-enable it again, but I can't promise that. If I can't then the update for 2.0 will reflect that.

**Comment by sisrfeng** [comment]
I learnt that this software can use vim mode and try it. Look forward to new version !
