### ISSUE TITLE
New Zettlr UI looks "weird" on Linux

### ISSUE THREAD

**Issue by kyaso** [Zettlr/Zettlr#1979]
## Description

So, after using 1.8 for quite some time, I thought of giving the most recent development version a try, and see how things a going. I cloned a fresh copy of Zettlr, and started a test with `yarn test-gui`, and for the first time I saw the new UI:
![zettlr-210518](https://user-images.githubusercontent.com/18646029/118730553-1e3e2280-b838-11eb-8925-f51d7641c7a2.png)

I won't go into much detail here, I think the image speaks for itself. Eg, the buttons at the top look kind of odd. Another example is the Settings menu:
![Screenshot from 2021-05-19 00-32-52](https://user-images.githubusercontent.com/18646029/118731987-d02a1e80-b839-11eb-9458-b23ce3060452.png)

Overall, to me the UI looks like as it was from a very ancient Zettlr version.

Please don't get me wrong: I know that 2.0 is still under development. I just wanted to throw this out here, as I wasn't sure if this look of the UI is normal or not. Maybe it looks nice on Windows/MacOS, but wasn't tested on Linux so far?

(if you want more details, such as further examples, just let me know)

## Platform
 - OS and version: Manjaro Linux (GNOME)
 - Zettlr Version: `develop`

**Comment by nathanlesage** [comment]
The UI does not look normal, you're right. The reason is that while I already implemented the necessary styles for Windows and macOS, I couldn't tend to Linux as of now because my Virtual Machine refuses to work :( I need that because I want Zettlr 2.0 to look completely native on all operating systems; here's a screenshot from the macOS version:

![image](https://user-images.githubusercontent.com/17251683/118766418-ae9e5680-b87c-11eb-837f-8463d3618aa4.png)

So what you're basically looking at is a completely unstyled GUI. I'm still hoping someone with a Linux machine implements the GNOME styling from the GNOME Human Interface Guidelines so that that one is off my plate …

**Comment by kyaso** [comment]
Just out of curiosity: What is the reason for separating the UI handling for Linux? How was that handled previously?

**Comment by nathanlesage** [comment]
Previously, Zettlr was much more custom-looking (and, the same across all platforms). Right now, I've separated not just Linux, but also macOS and Windows styling, since it is much easier to style for the OSs this way.

**Comment by nathanlesage** [comment]
I've just added a lot of styling to Linux. It's still not complete, but now it should be at least usable. I've in some instance simply copied over the styles for Windows, less out of spite, and more because the GNOME Human Interface Guidelines are ridiculously short of screenshots.
