### ISSUE TITLE
[Feature] Add support for Plantuml

### ISSUE THREAD

**Issue by ytee** [Zettlr/Zettlr#198]
It will be great to have support for plantuml. 
Expecting something like this: 
When we write plantuml in the editor, be able to see live preview of uml diagram.

Thanks.

**Comment by nathanlesage** [comment]
How does PlantUML differ from Mermaid as already requested in #147?

**Comment by ytee** [comment]
- I looked into mermaid website and could not find uml diagrams. With mermaid i can draw flowcharts and sequence diagrams.
- I have a large number of notes with plantuml. This is just a secondary reason ;)

**Comment by nathanlesage** [comment]
Soooo … UML seems to be uncommon in the JavaScript world, there are a few packages whom I wouldn't personally trust to be maintained. However, Pandoc seems to offer a filter using UML: https://github.com/timofurrer/pandoc-plantuml-filter

Mermaid is non-standard (b/c no UML), yet it would be easy to implement. I think the question of UML vs. Mermaid should be brought into the [Forum](https.//forum.zettlr.com/) so that it can be discussed there, as it seems to involve more than a few lines of code!

**Comment by ytee** [comment]
Sure. But just for info, list of tools using PlantUML:
http://plantuml.com/running

**Comment by nathanlesage** [comment]
Ah, I see Pandoc also has a filter available, this is good.

**Comment by StoltHD** [comment]
If UML is uncommen in the JAVA world, d3.js is a great alternative for graphs and diagrams...
https://markvis.js.org
Markvis is a markdown-it plug-in that utilities d3.js library

**Comment by Beurt** [comment]
Hi,

I would like to also advocate for PlantUML because it is already implemented in the very handy [QOwnNotes](https://www.qownnotes.org/) (cf.the plugin https://github.com/qownnotes/scripts/tree/master/render-plantuml) and a feature request for the popular [Marktext](https://marktext.app/) (cf. https://github.com/marktext/marktext/issues/603).

I also think it would be interesting to tend to Markdown compatibility by using the same implementation:

```
 ```plantuml
[optional @startuml or @startsomethingelse]
some plantuml, or graphviz or whatever data
[optional @enduml or @endsomethingelse]
```
```

https://github.com/qownnotes/scripts/blob/master/render-plantuml/render-plantuml.qml shows the JS code used for QOwnNotes implementation.

**Comment by shaoyanmin** [comment]
There is a [reveal.js plugin](https://reveal-plantuml.github.io/) to convert embed plantuml snippet to external image.
```html
<pre>
    <code class="language-plantuml">
  @startuml
  Alice -> Bob: Authentication Request
  Bob --> Alice: Authentication Response
  Alice -> Bob: Another authentication Request
  Bob --> Alice: Another authentication Response
  @enduml
    </code>
</pre>
<pre>
<script>
zettlrRevealOptions.plantuml = {
	    serverPath: 'http://www.plantuml.com/plantuml/svg/'
}
zettlrRevealOptions.dependencies = [
        {
            src: 'https://cdn.jsdelivr.net/npm/reveal-plantuml'
        }
    ]
</script>
```
that maybe help.

**Comment by StoltHD** [comment]
I don't think we will ever see some real graph tool in Zettlr, sad, because it could have been a great tool if it only had the feature needed for research report writing ... mermaid just doesnt do the job when it comes to timelines and network graphs or other similar graphs and diagrams ...

**Comment by nathanlesage** [comment]
@StoltHD Relevancy of the Graphing question to this issue?

**Comment by StoltHD** [comment]
> 
> 
> @StoltHD Relevancy of the Graphing question to this issue?

PlantUML are a graphs/diagram tool, d3.js are graph/diagram tool, mermaid are a less featured alternative to both of this tools, and actually not useable or extremely limited for UML charts, timelines and different type of network graphs ...
The diagrams in mermaid are also limited in compare to UML and specially in compare to using d3.js as charting tool ...

I just stated that we most likely would never see real graphing/diagram tools in zettlr, just as we want see a web clipper ... and for those two reasons it is limited as a tool for research ... but great for writing notes and school papers without to much graphs and diagrams ...

**Comment by LeNouveau** [comment]
Mermaid is nicer but not as featured as PlantUML. 

I like the Zettlr's concept/interface. 
But leaving PlantUML is impossible for me.

Too bad we are not enough wanting this feature. :(

**Comment by nkaul** [comment]
would like support for plantUML added.

**Comment by joelee** [comment]
Not having support for PlantUML is the only thing stopping me from migrating to Zettlr. 
Currently I am using Boost Note which has PlantUML support, but I very much prefer Zettlr interface.

**Comment by ajeep8** [comment]
I don't think Zettlr need develop each graph/diagram render. 
I'm not a programmer but can copy/modify some codes, I expand pandoc lua-filters for my own usage: https://github.com/ajeep8/lua-filters 
The pandoc lua-filters:diagram-generator can render plantuml and python plot, but not render mermaid. I studied it and find the py2image is just run python code to save svg/png to a temporary file, then include the temporary image file.
So I add a mermaid renderer, it's just run cli command: mmdc -q -i mmdfile -o /tmp/mmdfile.png(or svg), then pandoc lua-filter will replace the mermaid code with the mmdfile.png.
The same way, I add a draw.io renderer too.
So I think Zettlr could give out a plugin interface, so we can run external shell command to render any kind of graph.
I had read Zettlr render-mermaid.js, I'm not familiar with js, it seem render mermaid by itself, not by mermaid-cli.
