### ISSUE TITLE
[develop] Decoupling open files from the file manager

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#1998]
This is more a conceptual discussion that came to my mind in recent days. Precisely, the question popped up for the first time once I implemented the "Untitled files" functionality (that you could open up a new file that was not yet saved to disk, in order to write first, and think about a filename second).

That functionality is incredibly useful and user-friendly, and honestly I don't know why I didn't implement this further. _However_, there was a problem that immediately popped up: Up until then, the open files were directly sourced from the FSAL layer: Every open file (the tabs in the editor) had a single corresponding file somewhere in the file tree.

With untitled files, however, that assumption is violated: Since untitled files are not stored on disk, they do not occur in the file tree.

This led me to implement a few, as I would call them, monkey patches: Wherever I checked, e.g., the consistency of the open files array, I would do so by simply checking "Do we have this file somewhere in the file tree?" and if we didn't, I just removed that file from the array. Simple as that. This also allowed me to introduce some short-circuits so that any modification to that array could be easily handled in the FSAL and the callers didn't have to worry about leaving that array in an unstable state.

However, one specific problem occurred very soon afterwards: Since you know I'm using the most recent develop version myself in production (because only then do you really see where the bad bugs happen), I noticed that there were still a lot of race functions, precisely when you _save_ an untitled file, and it then becomes part of the file tree. In that case, what happens right now is nothing short of comedy: In order to re-use as much code as possible, Zettlr will do the following:

1. Save the file according to where you specify
2. Add it as a "root" file (since `handleAddRoots` was the only function that consistently allowed opening arbitrary files on the file system - remember users could also save these untitled files outside the loaded file tree)
3. Close the untitled file forcefully (since it's now saved) and immediately open the just added root file (so that, visually, it appeared that nothing has changed except instead of "Untitled.md" you'd have whatever filename/title the file had)
4. However, I realised that the user could also have saved the file somewhere inside the file tree, in which case the root file had to be transformed into a "regular" file somewhere there, for which I implemented the function `consolidateRootFiles`, which basically just removed a root file if the very same file path was found somewhere in the file tree.

And, guess what? Race conditions! 🎉 Overall I think the idea to tightly couple the open files to the file tree is kind of a relic from way back when I started Zettlr. Right now, it makes more sense to have, on the one hand, a file manager that enables you to browse files without leaving the app, and on the other hand files that you are editing. But in general, I think we should completely decouple these two. This would _additionally_ solve my "root file" problem: Since then we could "re-define" what a root file is in that a "root file" would be simply a file that is currently open but that is nowhere to be found inside the file tree (the loaded _folders_). Plus, I could get rid of a lot of the weird code that I used to make the untitled files work.

But there are some hesitations:

1. Is it computationally efficient to just grab all the file descriptors in total from the main process to display as tabs? (Mainly asking because in the FSAL we're using delta-updates because you can, in theory, load an awful lot of those)
2. I'm always afraid of putting too much strain on the disk devices if I query, e.g., the file existence too often. Or is that just a myth I have, and checking for a file existence or reading a file a little too often doesn't have such a great, practical impact?

@tobiasdiez Maybe some thoughts if you have time?

**Comment by tobiasdiez** [comment]
I'm not very up-to-date with this part of Zettlr, so what I'm saying now might be completely stupid.

In general, I think it is a good idea to separate the file viewer (the sidebar) from the open files. Let's call the latter documents, because as you say they don't need be files until they are saved.

Then you would have two managers, or services.
1. File manager: The thing that powers the file viewer, i.e. reads which files are currently in the project folder and updates itself upon file changes (e.g. by listening to OS-file change notifications). This manager also handles caching of information about these files if needed (e.g. words contained, file name and extension, last modification date). This is completely powered by the underlying file system, so you never need to actively add or change information. This manager would be your only single source of truth about every related to files, e.g. no other part of Zettlr should directly read file information directly.

2. Document manager is responsible to handle the open documents. It has methods for example for opening a file as a document, or saving a document as a file.

So when the user opens an existing file, the click handler gets the `File` object the user clicked and creates a new `Document` from it (e.g. by simply storing the `file` in a variable, and reading the file to get the markdown content). If you save a `Document` then it simply writes the content to a file (new or existing, depending on context); the File manager is then notified by the OS about this change and updates itself accordingly. The only somewhat tricky part is that the document needs to be notified about changes to the file object (which is updated by the file manager), but there many solutions for this. For example, you could use [Vue's reactive variables](https://v3.vuejs.org/guide/reactivity-fundamentals.html#declaring-reactive-state) to propagate changes from `File` to `Document`.
Both managers shouldn't know about each other's existence. The only time when they need to indirectly communicate with each other is the conversion File > Document. Changes to the document are transmitted to the file manager via the change listeners of the file system.

In my opinion, this results in a nice decoupled architecture. Where each part (file viewer, open document tabs) of the application only cares about one purpose and doesn't rely on each other. Does this make sense?

**Comment by nathanlesage** [comment]
It does make sense, and I like the idea. The only things where I'm still unsure is with efficiency reasons, and potential race conditions. For example:

- A user opens a file from a directory
- Then he modifies the file
- Before saving, he tries to move the directory around

How should we handle this case? Or even without the document being modified? Do you have a clever idea? I fear until we have that solution decoupling might actually be difficult – right now I'm moving the open Files array around as necessary when the user moves a directory …

**Comment by nathanlesage** [comment]
Just did a quick table:

![image](https://user-images.githubusercontent.com/17251683/119225159-6db77380-bb02-11eb-9aa2-7df483305154.png)

Did I miss anything …? I mean, if that works, the FSAL is already propagating the OS-level events, so if we move the openFiles to its own module we could hook into these as well … what do you think? Shall I just do a PR and then see where we actually hit roadblocks?

**Comment by tobiasdiez** [comment]
The table looks good to me. If files are moved remotely (by the OS), then the FSAL is also notified by the OS event. It then propagates this event to the document service, which has a few options:
- If the file is not open, we don't need to do anything.
- If the file is opened by the user, we simply replace the underlying `file` object of the document by the updated file. Then any further action (like save) is against this new path.

**Comment by nathanlesage** [comment]
That does sound good. I'll do that one via PR in the coming weeks (possibly end of June/beginning July), it would be great if you could have a look at what I've come up with before merging!

**Comment by nathanlesage** [comment]
So, works surprisingly well, even though we're now on "eventual consistency" and FSAL/document tabs are not always perfectly in sync.

There might be some more issues, and we definitely need to clean up some code, but it's working fine thus far and so I'll just let the crowd intelligence find the last bugs.
