### ISSUE TITLE
Display on lower-resolution monitor

### ISSUE THREAD

**Issue by corypanshin** [Zettlr/Zettlr#20]
I've been exploring Zettlr, and it looks like it could be exactly what I've been looking for as a research/writing application.  The one problem I'm running into is the display.  I have an older, non-widescreen monitor (19" I think) set at 1024x768 resolution, and the editor just doesn't display well on it.  The amount of writing space is limited, especially given the generous margins.  The lines of text display at only about seven words long, and I have to close the tree view and zoom out once or twice to get to something more usable.

I'm also finding the text itself a bit on the pale side.  The lines are thinner to start with than in some fonts, and once I've zoomed out they appear closer to medium grey than to black.  If some accommodation could be made to systems like mine it would make the app a lot more accessible.

**Comment by nathanlesage** [comment]
Hey, thank you for this info. I don't have a lot of different systems to test upon, therefore it's difficult for me to explore how it looks on low-resolution monitors. If you could give me some screenshots of the design that would definitely help me identify where I have to make changes to the styles to make it look better on smaller screens!

Also, which operating system are you using? Zettlr uses two fonts: Lato on Linux-based systems, and Segoe UI on Windows (because Lato simply doesn't render good on Windows systems due to font smoothing issues).

Thanks in advance for your infos so that I can look into them!

**Comment by nathanlesage** [comment]
I just had time to change the margins to make it smaller in commit 07798923c95d6196c162e88925c021bfcdaf0a79 — so I'll regard the issue as closed for now.

**Comment by corypanshin** [comment]
That's a lot more usable for me now.  Thanks.


> 
> I just had time to change the margins to make it smaller in commit 0779892 — so I'll regard the issue 
> as closed for now.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.






--
Cory Panshin, torve@panshin.net
http://trogholm.panshin.net/
http://www.panshin.com/trogholm/trogholm.htm

**Comment by nathanlesage** [comment]
That's nice to hear! If there are any other margins I've overlooked please let me know.
