### ISSUE TITLE
Hope to support vim shortcut :)

### ISSUE THREAD

**Issue by Alopex4** [Zettlr/Zettlr#200]
Totally, I think this application is great.   
However as a Linux user, I very miss the `vim` shortcut. Maybe someone has the same feeling too.  May I ask the developer would you plant to add `vim` support as a new feature ?   
Thanks again for your awesome job !

**Comment by nathanlesage** [comment]
Support for a `vim` mode in CodeMirror seems to be not so good:

> Note: The CodeMirror vim bindings do not have an active maintainer. That means that if you report bugs in it, they are likely to go unanswered.

**Comment by sndnyang** [comment]
I gave a simple try on the vim mode. And two small issues:

1. The 'Ctrl-f' is still 'find' instead of 'PageDown'.  Other shortcuts I have tried work fine.
2. The status/shape of the cursor keeps the same in normal(command) mode and insert mode.  In normal mode, the cursor usually shows a flickering block rather than the normal flickering line. It will help us to know the current mode we are using(but not very crucial).

It's an excellent software!

**Comment by nathanlesage** [comment]
To point 1: It's because I override the keymap with some keys, refer to this file to know which ones!

To point 2: Yeah, I didn't implement the necessary CSS styles, as I don't officially support these (yet) — If you have an idea, please feel free to PR!

**Comment by antoniy** [comment]
I would love to have option to enable vim mode in the settings. I've tested the suggested method and it actually makes the app usable to already broken Vim user like myself. There are just two small things I need personally to make this way better.

1. When in normal mode (vim) the caret should be a block style so you could tell you're in normal mode. When in insert mode - switch back to pipe style caret.
2. For a variety of vim motions the ability to see line numbers is actually useful to reformat whole blocks of text. So a support for line numbering, relative line numbering and hybrid line numbering will bring all that joy back.

Can we at least have the option in the settings as an experimental feature so we can actually use it without manually executing commands in the developer console?
