### ISSUE TITLE
[Need Fixing] Home and End Button

### ISSUE THREAD

**Issue by shanvrolijk** [Zettlr/Zettlr#201]
Hi, I run Zettlr Beta 1.3 on Windows 10, and whenever I push Home and End button on keyboard, the the cursor moves in front and end of a paragraph, instead of the line. Thank you for fixing this. 😄

**Comment by nathanlesage** [comment]
Do you write your paragraphs in one line or do you use manual text wrapping (a.k.a. consciously using line breaks inside paragraphs)? Because according to the CodeMirror manual, `Home` should move to the beginning of the line, and Zettlr does not override this behaviour internally!

**Comment by shanvrolijk** [comment]
I'm not sure of what you mean. I just write normally, I don't use code or anything (because I can't). Unless I copy something from the internet, I don't use CTRL + shift + V.

**Comment by Adrien-H** [comment]
Could we see some text producing this behavior?

My guess is that what we are talking about here is a wrapped line. And indeed, I find the current behavior being counter intuitive when compared to what is usually done in common textareas. Example:

```text
Some lalala lorem ipsum text that
is automatically wrapped by its
own length
```
In that case, let's consider I never pressed `Enter` and rather let the editor automatically wrap the text when I was at the edge of the window. Now I place my cursor on **Some** and I press `End`: while I would expect my cursor to jump to **that**, it will jump to **length** instead.

In the same way, the `Home` key will produce the same behavior on the opposite side. Pressing `Home` on **length** will lead my cursor to **Some** instead of **own**.

It looks like this is a default CodeMirror behavior and could probably be fixed by something like [this answer](https://stackoverflow.com/a/25019442/7918180).

**Comment by nathanlesage** [comment]
Aaaaaah I see. Yes, you're right. On macOS, for instance, the `Home`/`End` equivalents are `Cmd+ArrowLeft`/`Cmd+ArrowRight` but CodeMirror is indeed only "going left"/"going right".

I'll fix it, thanks to @Adrien-H for the suggestion!

**Comment by samarulmeu** [comment]
But it will be possible to have a switch to keep the current behavior of `Home` / `End`? I'm so used to go to the end or begining of paragraph using them!

**Comment by nathanlesage** [comment]
🤔 You got a point there.

**Comment by samarulmeu** [comment]
I discovered how to do what I want using `renderer._editor._cm.setOption..` in the console, but how do I tell Zettlr to load my values on start?

**Comment by nathanlesage** [comment]
For this a switch would be needed, which I would need to implement.

Could you tell me what arguments you've given to setOption so that I don't need to search for them and can easily implement them?

**Comment by samarulmeu** [comment]
I used this code in the `Console`:
```
renderer._editor._cm.setOption("extraKeys", { 
    Home: "goLineStart",
    End: "goLineEnd"})
```

**Comment by nathanlesage** [comment]
Perfect, thanks! I'll see to adding a switch in the preferences!

**Comment by nathanlesage** [comment]
Did it!

**Comment by osted** [comment]
Today I downloaded version version 1.5.0 and this is broken for me - Home and End move to the end of paragraph and not the line. Running Windows 10, 64bit installed "for me only".

**Comment by nathanlesage** [comment]
This setting needs to be turned off:

![image](https://user-images.githubusercontent.com/17251683/73097538-b1d33d80-3ee7-11ea-9643-413a99f66896.png)

**Comment by osted** [comment]
That's it - thanks a lot for the support, really appreciate it.
