### ISSUE TITLE
[ENHANCEMENT] Better developer documentation

### ISSUE THREAD

**Issue by bxff** [Zettlr/Zettlr#2032]
## Description

Looking for a place to start to learn how the application technically works.

## Proposed Changes

I am finding it very hard to understand overall how CodeMirror, Electron and other 
elements of Zettlr works together. There is no proper documentation of, how I can 
start developing on the project, other than a vague file/folder structure in the [getting 
involved section](https://docs.zettlr.com/en/get-involved/#project-structure). 

I would love to do chores of the project, but what I really want to do is understand how 
the project really works.

## Caveats
Would require a lot of time to documentation everything.

## Additional Information
Personally all I want to know is how does the editor handles everything but after watching 
a video made by one of you, I am more confused then when I started: https://www.youtube.com/watch?v=sa_ehm0yDEo

**Comment by nathanlesage** [comment]
I really do understand these concerns; and have to apologise for not being able to do a good dev documentation along the way. However, I do extensively add comments even where the code might be self-explanatory, so the comments should already help.

The basic structure (as of today) is:

The first file to be executed when Zettlr starts is `source/main.ts`. It will then run the boot-method in `source/app/lifecycle.ts`, which will start up all providers. Afterwards, it will instantiate the main object (`source/main/zettlr.ts`) which will load all modules (`source/main/modules`) and perform the final startup sequence. Then the main window is being opened. Each individual window the app offers is in a folder prefixed with `win-`. The HTML-file in there will be loaded and the `index.ts`-file will be executed. And that will just set up a default Vue app per each window with no special magic happening. The only difference to common Vue-apps is that instead of pinging an API-server we're using `ipc`-calls, but these do work exactly like regular API calls. The rest should be deductible from reading the comments, I hope.

Does this already help a little bit?

**Comment by nathanlesage** [comment]
I have now added a large portion of info to the README itself which should help much more. It includes all concepts that are important, some clarifications, and a short description of the directory tree. At some point I'll also overhaul the Contributing-documentation on docs.zettlr.com.
