### ISSUE TITLE
[FEATURE REQUEST] support for relative paths for images

### ISSUE THREAD

**Issue by cesarpachon** [Zettlr/Zettlr#205]
images that uses paths like "../img/myimg.png" (relative to the markdown file) are not being rendered.

**Comment by nathanlesage** [comment]
It should be rendered, because images already support relative paths. The algorithm tries the following steps:

1. Render the image using the exact path. If that doesn't work:
2. Render the image using the given path, joined with the file's directory path. If that doesn't work:
3. Display a 404-image.

Could you please check the output of the console, as loading errors from images will be logged there? Thanks!
