### ISSUE TITLE
[ENHANCEMENT] Images should be resized into exports

### ISSUE THREAD

**Issue by Porrumentzio** [Zettlr/Zettlr#2055]
## Description
Images should be resized into exported files, so the same size used in Zettlr display should be used on exports.

## Proposed Changes
Resizing the image for exports, the same way it's done for displaying in Zettlr.

## Caveats
Maybe this has the same problem as #2046, that [Zettlr is thought as WYSIWYM](https://docs.zettlr.com/en/concepts/wysiwym/).

**Comment by nathanlesage** [comment]
If you want to resize images, you might want to add a little bit CSS to the HTML file. There is no way Zettlr will have the same image size as your exports, since that is dynamically calculated both in Zettlr's editor as well as the HTML document.

I get the impression that you have difficulties around the WYSIWYM principle. But then, I think, you might be right in that the heading formattings definitely need some work. The idea behind all that rendering and previewing you see in the app is solely that you can preview an image, not in the actual size, but only insofar as it helps you.

In general, the highlighting in Zettlr is done after the following principle: Given both a pre-rendering of the element and the plain element, is the pre-rendering benefitial for visual understanding? If yes, I'll implement it. This is why images are pre-rendered – an image is easier to visually categorise than the `![Image title](some/obscure/path.jpg)` tag. The same holds true for links: It's much easier to read `a sentence _with a link_ in between` than it is to read `a sentence [with a link](and-some-long-url-afterwards) in between`.

The intention is **not** to resemble the potential output closely, which is impossible either way (think alone of the difference of revealJS exports vs. HTML vs. PDF).

I think I will amend the WYSIWYM-docs page with a few more example to make the point more clear!
