### ISSUE TITLE
Update on KaTeX

### ISSUE THREAD

**Issue by furkantaskin** [Zettlr/Zettlr#2056]
## Description

KaTeX is a package which gets updates frequently. But major update period is not that common. Zettlr's maintenance on KaTeX version may satisfy in common usage, but current version of KaTeX brings many features for matrices in calculus and linear algebra.

## Proposed Changes

I am, and I believe many students those using Zettlr for their lecture notes, writing many calculus formulas or linear algebra formulas with tons of matrices on the notepad. Especially, taking notes from academic journals or articles needs an advanced math editor. Current major KaTeX version brought a massive support for equation environments and commutative diagrams which boosts the usage of matrices in math formulas. At least, updating to the latest major version would be great for many users. 

As I see in resource files, Zettlr is using v0.12.0 and current latest version is v0.13.11

## Caveats

As explained in the migration guide of KaTeX, there are breaking changes which may affect the performance of Zettlr.

Migration guide can be found in https://github.com/KaTeX/KaTeX/issues/2490

## Additional Information

Explained support for matrices and equations can be found in the [changelog of KaTeX](https://github.com/KaTeX/KaTeX/blob/master/CHANGELOG.md#v0130)

**Comment by nathanlesage** [comment]
Zettlr's source branch is already on 0.13.11, and this will ship with the next release.

I will always keep the dependencies up to date, but since Zettlr is an application, and additionally requires KaTeX to be hard-coded, this delay is unavoidable. As you mention, for common usage it's okay, and I think the way we do it right now (always ship updated dependencies with new versions) is the most sensible way with regard to time and resources.

Plus, please note that the current hiatus in new updates is mainly due to the fact that we're currently working on 2.0 which takes away all available time. I'm sure that once 2.0 is out, the update cycles will be shorter again, decreasing this gap in new releases and Zettlr's support for these.
