### ISSUE TITLE
No icon on Marco window manager [MATE]

### ISSUE THREAD

**Issue by Porrumentzio** [Zettlr/Zettlr#2064]
## Description
When launching the program, no icon appears on Marco window manager:
![irudia](https://user-images.githubusercontent.com/61913683/120996837-fc74f300-c786-11eb-9046-b77bc7505266.png)

## Expected behaviour
It should display the icon.

## Platform
 - OS and version: Manjaro MATE
 - Zettlr Version: 1.8.9

## Additional information
This happened with other programs, see https://github.com/rafaelmardojai/blanket/issues/54, and was solved with this: https://github.com/rafaelmardojai/blanket/commit/b3d0f92f97286cd5055b6e7abba29a4adad0f568

**Comment by nathanlesage** [comment]
I remember there were some difficulties with this earlier, but I don't really know how to change that. The app you linked to is written in Python making use of the immediate Gtk-bindings, to which Zettlr does not have access, since we're using a completely different framework.

I'm leaving this open for Electron-style suggestions. It's likely some setting in Electron-builder, but unfortunately I can't test around.
