### ISSUE TITLE
Navigating the directory structure

### ISSUE THREAD

**Issue by adhadjilambris** [Zettlr/Zettlr#2086]
I'm having some trouble with the shortcuts. I'm using a MacBook. [#1273](https://github.com/Zettlr/Zettlr/issues/1273) describes the problem I'm having. This issue was closed, because the problem was not internal to Zettlr. I've since checked that a more recent electron build should have fixed the problem. I'm not sure if we have just not gotten around to incorporating those changes. Anyway, I am looking for help with workspace navigation (namely up and down the tree), and I apologise if there should be some obvious way to do this from the documentation:

If I am somewhere in a nested folder, how should I navigate up the tree to a parent folder in the workspace?

I expected that If I could toggle between the file list and the tree view, I would easily be able to do that.

If I have the sidebar open in extended mode, and the file list is in focus, is there a way to focus the tree view directly?

**Comment by adhadjilambris** [comment]
⌘ + ⇧ + O, and then either ⌘ + ⇧ to navigate up or ⌘ + ⌥ + ⇩ and then ⌘ + O to navigate down has it, I think.

The tree view does scroll horizontally, however. Are we not supposed to go very deep, then?

**Comment by nathanlesage** [comment]
With regard to navigating the file tree, yeah, there are still a few things to be added. Navigation right now is only supported in the file list in a good way, something that bugs me as well. But it's hard to implement.

> The tree view does not scroll horizontally, however. Are we not supposed to go very deep then?

Yes, if you have too many folders, that's bad practice anyway. But furthermore, that would interfere with the horizontal scrolling you can do in order to quickly switch between file list and file tree.

I do confess, the UX of Zettlr isn't yet state of the art, but then I'm mostly alone with a little help here and there 💁🏻
