### ISSUE TITLE
[ENHANCEMENT] Add a note to the export settings dialog that YAML frontmatter also contains export settings

### ISSUE THREAD

**Issue by mousetrappling** [Zettlr/Zettlr#2108]
## Description
Add a sentence to the export settings dialog something along the lines of: "YAML frontmatter may also contain export options, see the manual: https://docs.zettlr.com/en/core/yaml-frontmatter/"

## Proposed Changes
This is just a UI change to remind people, like me, that if they are having export problems the options in this dialog are not the only things the end-user can change and the solution might be to add a variable to their YAML frontmatter.

## Caveats
The more words you have in a dialog the less likely people are to read them?

**Comment by nathanlesage** [comment]
Mh, I'm unsure. The thing is you generally add YAML frontmatter stuff yourself, and if something doesn't look cool I think it's not too much to expect from people to actually read the manual (yes, I know, most don't) … I don't want to "overdo" it, you know …? Plus, in 2.0 people will have a lot of config options much more accessible either way.

**Comment by mousetrappling** [comment]
I see your point (and perhaps it's entirely moot in 2.0 anyway :) ).  But I was seeing it as a pointer for where to start when reading the manual, not a substitute for people reading the manual.

From your perspective it's presumably blindingly obvious that one way you send options to Pandoc is via YAML frontmatter.  But from my perspective, well the first time I ever heard of Pandoc was installing it to set Zettlr up in May last year and I have no idea how any of that side of it works.  The model in my head, even after having read the manual while learning Zettlr (yes, I'm the weirdo who _does_ read the manual) is "I write -> I select an export format -> magic happens that involves a program called Pandoc and LaTeX -> I have an HTML file (or whatever)".  So my instinctive response to an export problem is to look at the export options and then if there's nothing there it must be either in the internals of Zettlr that I don't have access to, or in the internals of this Pandoc thing that I also don't have access to.  Even if I went to read the "Exporting" section of the manual there's no mention of YAML.

So actually, the answer might be to alter the Exporting section of the docs (tho I dunno if I would've gone and re-read the exporting section when I couldn't see an option for localistation? Maybe).  Which might not be worth it till after 2.0 lands anyway, given it sounds like you're changing so much about exporting :)

**Comment by nathanlesage** [comment]
Hmmmm … I do see your point, and I think that part will certainly still become even _worse_ in 2.0, since we're unlocking the defaults files (do you know what defaults files are? I bet not, so I definitely need to explain them)

Here's how the whole exporting process works:

![image](https://user-images.githubusercontent.com/17251683/122723402-365bf400-d273-11eb-8750-838733778a7e.png)

I figure we might need a whole new section in the docs to explain that, maybe in the concepts section …?

**Comment by mousetrappling** [comment]
You're quite right, I didn't know there were defaults files as well – tho having been told I could make a guess before looking at the diagram what they would be for, the problem would be I wouldn't know I needed to know about them and wouldn't know what sorts of things I could use them for. So I think you probably do need to explain the workflow in the docs (sorry!) and at least a list of the various ways the end user can interact with it to customise the output – I assume the LaTeX custom template stuff described in the docs fits in somewhere, for instance?

**Comment by nathanlesage** [comment]
> I assume the LaTeX custom template stuff described in the docs fits in somewhere, for instance?

… I … hope so? Actually, I've begun rewriting the docs for 2.0 prompted by this issue of yours, and I think I'll be quite merciless in trashing old stuff an re-arranging things.

However, it would be great if you – from a user's perspective – could give me some hints as to how the docs might be improved with regard to organisation. So feel free to collect some feedback and open an issue over on the Documentation repository. That would help me because then I just have a checklist I have to go through!

**Comment by mousetrappling** [comment]
Sure, I can do – but it's not going to be in the next couple of weeks I'm afraid, I'm on a bit of a deadline crunch so I need to finish that first. I'll put it on my to-do list for afterwards.

**Comment by nathanlesage** [comment]
Don't you worry. Everything here is completely voluntary. Plus, it'll be a few months until 2.0 is ready for release, and I think we don't have to update the docs beforehand! Any help is appreciated with no deadlines attached!
