### ISSUE TITLE
Multiple dashes are not accepted in Zettlr

### ISSUE THREAD

**Issue by break6700** [Zettlr/Zettlr#2118]
## Description

Zettlr does not allow insertion of more than one dash in a row. Adding more than one deletes the previous dash.
## Reproducing

Open file and try to insert more than one dash.
## Expected behaviour

Zettlr should accept multiple dashes.

![Animation](https://user-images.githubusercontent.com/44082853/123086854-6fcb6580-d413-11eb-88a7-bcba4879fc66.gif)

## Platform
 - OS and version: win32 10.0.19042 (architecture: x64)
 - Zettlr Version: 1.8.9+nightly-20210619 (and 2.0 DEV)

## Additional information

This is a serious issue that effects any who want to use a YAML header.

**Comment by nathanlesage** [comment]
This is really weird and I can't reproduce this locally. I figured out that the Word style AutoCorrect immediately replaces two dashes with one EN-dash (which is correct behaviour), while LibreOffice doesn't do that. But that doesn't delete the dashes. I'm currently wondering if the AutoCorrect table contains an entry to replace a dash with nothing …? This could be the cause.

Otherwise, as always, maybe there are some errors on the console…?
