### ISSUE TITLE
[DEVELOP/DISCUSSION] Implement Zettlr-specific file handling as Pandoc filter?

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#2121]
Bonsoir à tous,

I just had an idea. Since I fixed the project exports today I figured that one of the big, nasty things that Zettlr currently still does is: On export, it opens EVERY file, manipulates the file contents and saves it as a temporary file. Somehow this is pretty dissatisfying. It puts more strain on the HDD/SSD of the user, it can break relative links within the document, and overall it would be computationally efficient to simply perform any manipulation when the file is being processed by Pandoc.

We now have access to the `input-files` property of Pandoc, allowing us to simply stuff all the files we want to concatenate together in there and don't have to do that much on our own, especially since Pandoc is able to resolve relative image paths much better than we do. So actually I think we shouldn't do that AT ALL.

However, there are a few options that allow users to modify the output accordingly, for example to remove tags or unlink/completely remove internal links. These obviously have to be retained.

Given that @tarleb is always touting the great Lua-filtering options, I had an idea:

1. We completely leave all files alone. We simply provide pandoc with said `input-files` via our custom defaults writer which @Kangie is currently implementing and we add the configuration options the user can set as variables to the defaults object before we write that to file.
2. Then we always inject some LUA-filters into the filter array that perform the given transformations – remove tags and/or file links
3. The filters get called once Pandoc has opened and parsed the files. They have access to the variables so the filters can do their magic if these variables are set

What do you think about that idea? @tarleb would you be willing to give me a quick crash course in writing Lua filters if this idea is feasible? :D

**Comment by tarleb** [comment]
Sounds great, I'm in.

**Comment by nathanlesage** [comment]
Implemented that a few days ago. Lua is fun. Especially patterns. Not.

**Comment by Kangie** [comment]
Man, I missed merging my stuff before this by a hair apparently. 

Good news, finally had time to sort out that webpack stuff (I think).

Bad news, I should have merged my work a while ago because I hooked into prepare-files to also gather and strip in-document metadata blocks,  so working out a new approach there will be fun (or alternately just not doing it; I just figured that since the documents were already in memory using the old exporter that it was effectively free to do and we'd be able to see [and calculate] the resulting 'defaults'  output for a given project to assist in debugging.)

Now that we're not writing out the content, and therefore don't have the opportunity to strip and validate that data, we will just have to accept that users can arbitrarily configure pandoc from within their document in a way that overrides our configuration

**Comment by nathanlesage** [comment]
> we will just have to accept that users can arbitrarily configure pandoc from within their document in a way that overrides our configuration

I don't think that this is as much of a problem. In the end, the Pandoc pipeline explicitly states that there are two sections where users can configure pandoc: In defaults files and in the YAML frontmatter. So if users really want to override the defaults, they are free to do.

But I also know that Albert is not extremely happy that you cannot override certain defaults values from within the YAML frontmatter, so there might be movement around that. Nevertheless, if there are enough gains of actually parsing the frontmatter, we can just read in and parse the files prior. Still saves us the write-out (and just a read is always cheaper than a read AND write)
