### ISSUE TITLE
[ENHANCEMENT] Add version for Windows with virtual GPU

### ISSUE THREAD

**Issue by BarrOff** [Zettlr/Zettlr#2127]
## Description

Electron has problems on Windows when using virtual GPUs, see [here](https://github.com/electron/electron/issues/10551). In order to work, it seems that the hardware acceleration must be [disabled](https://www.electronjs.org/docs/api/app).

## Proposed Changes

I have no experience with Electron/Javascript, but disabling hardware acceleration is described [here](https://www.electronjs.org/docs/api/app).

In C i would define a macro like
```c
#define HW_ACCEL_ON
```
Later one could check for this macro with `#ifdef` to turn acceleration on or off. In CI/CD one could simply use the standard pipeline and add a compile time option.

If a similar approach is possible in Javascript/Electron I guess it would be easy to provide such a version for Windows.

## Caveats

I do not know if some code depends on hardware acceleration being available. That would obviously break.

## Additional Information

Virtual Windows installations are common in universities which are a prime target for Zettlr. From personal experience I can confirm that Zettlr does not work there. I would be glad to provide feedback for test builds.

**Comment by nathanlesage** [comment]
Rather than provide a special version, I can offer to implement a command line switch that disables hardware acceleration.

In order to test the feasability, would you mind testing the following on your system which uses virtual GPUs?

1. Clone the repository and set everything up as described in the README file
2. Open the file `source/main.ts`
3. Immediately after the `import` statements at the top of the file, add `app.disableHardwareAcceleration()`
4. Test out if the app starts correctly this way.

If it does, I'll implement a command line switch that disables hardware acceleration on start.

**Comment by BarrOff** [comment]
Hello,

I followed your instructions and built Zettlr myself. With disabled hardware acceleration it worked for me.

Build information is available here: https://gist.github.com/885eca82e7085bb395f411c4e0d2c170

**Comment by nathanlesage** [comment]
Perfect, thank you. I added a command line switch `--disable-hardware-acceleration` to do so programmatically from the coming builds on.
