### ISSUE TITLE
[ENHANCEMENT] When creating a new document only the part of the filename that precedes the .md extension should be selected

### ISSUE THREAD

**Issue by LePeti** [Zettlr/Zettlr#2158]
## Description

Now, when I press `cmd + n`, a text field appears with a generated filename, like `20210705141433.md` and the whole text is selected. I would like to propose a change, where only the filename without the extension is selected, so you don't have to modify your selection to rename your file. (Unless you wanted to change the extension `.md` as well, which should be rare I assume.)

I've never ever changed the extension so far and I'd assume this is the case with most users, thus it would save everyone a few (mili)seconds each time if we didn't have to reselect the title each time a new document is created.

**Comment by nathanlesage** [comment]
This has already been solved by a PR, it's in the nightlies & will come with 2.0

By the way, don't worry if everything is selected in Zettlr 1.8.9: If you don't specify an extension (i.e. overwrite `12341234.md` with `some note`) Zettlr will automatically append `.md` so that it becomes `some note.md`

**Comment by LePeti** [comment]
Oh, good to know , thanks! :) Sorry, I searched for this among the issues but didn't find it.
