### ISSUE TITLE
[Bug] [DEVELOP] "Do not prompt for filename when creating new files" setting isn't respected

### ISSUE THREAD

**Issue by sds100** [Zettlr/Zettlr#2179]
### Description

The "Do not prompt for filename when creating new files" setting isn't respected. Turning it off and then creating a new note (through the menu or Ctrl/Cmd+N) doesn't show a dialog allowing you to choose the file name.

### Reproducing

1. Disable the "Do not prompt for filename when creating new files" setting
2. Create a new note (through the menu or with Ctrl/Cmd + N)
3. No dialog is shown allowing you to change the file name.

### Zettlr Version

Right off the develop branch

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

KDE Neon Ubuntu 20.04

**Comment by nathanlesage** [comment]
Just took a look, and indeed the setting is never queried. However, I'm afraid it would be difficult to re-integrate that into the app. Currently, it works like this:

1. If you choose the menu item or use the shortcut, a new, unsaved document will be created. It already contains the generated filename. As soon as you save this one, you can either just confirm, retaining the filename or overwrite it. Here, the setting is not necessary at all, since the workflow accomodates both preferences.
2. If you right-click a directory, right now, the file will immediately be created without prompting and be opened. Thus, you can immediately use the renaming-shortcut and type a new name.

Thus, I think the setting is actually not required anymore, and I would like to remove it altogether. However, I'll keep this issue open for a week to allow others to enter the discussion.
