### ISSUE TITLE
Folder not found rewriting config

### ISSUE THREAD

**Issue by samarulmeu** [Zettlr/Zettlr#219]
I use Zettlr on different machines. On some of them, I access part of my notes (the private one especially) on removable media, but, if I forget to mount them before, Zettlr just removes those folders from the config files and I have to add them again. 
Would it be possible that it doesn't touch the config file in this case or ask if I want them removed from view?

**Comment by nathanlesage** [comment]
Sounds reasonable. I suggest the following solution:

1. Implement some kind of "Dead Directory" class that represents root paths that don't exist. They'd be greyed out in the GUI.
2. You can of course still "close" them to remove them manually.
3. Regularly check whether the paths exist and, if they do, replace the "Dead Dir" with a regular directory object. (And vice versa for USB sticks that are disconnected during runtime)

**Comment by samarulmeu** [comment]
Sounds perfect. *Regularly*, if it is slowing down the app, could be done only when the app is starting. 

Thank you for the great job! Hope to have an amazing 1.3! The betas are already nice and stable.

**Comment by nathanlesage** [comment]
It shouldn't have that much impact on the app's performance -- it would be basically as if you'd manually open the directory, so if you have a huge directory, you may experience some lag (at least until I've managed to implement asynchronous file reads, as it's always said to be the must-have; never implemented it that way because I didn't know how asynchronous functions worked when I implemented it two years ago lol)

And as for 1.3, I think I'll launch next Friday or so, so keep the champagner chilled! 🍾
