### ISSUE TITLE
[ENHANCEMENT] Distinguishable hyperlinks after exported

### ISSUE THREAD

**Issue by CarlossShi** [Zettlr/Zettlr#2209]
## Description

The hyperlinks in Zettlr editor look good. But after being exported to pdf files, these links are as same as normal text except that they are clickable. Would you please add some export settings so that hyperlinks are more distinguishable after exported? Thanks.

## Proposed Changes

Here is an example preview in both Zettlr and Typora. I prefer hyperlinks with underlines and a distinguishable color.

<img width="911" alt="test" src="https://user-images.githubusercontent.com/50014508/126424771-54684d10-9dbe-47e6-a988-a9d2ede31852.png">

## Caveats

Probably not.

## Additional Information

I have tried these methods, but nothing helps.

1.  Change the YAML Frontmatter as follows, see [How to underline links with pandoc?](https://tex.stackexchange.com/questions/319253/how-to-underline-links-with-pandoc), [Pandoc & Markdown: Colored links in PDF output](http://www.das-werkstatt.com/forum/werkstatt/viewtopic.php?t=2519).
    ```
    header-includes:
    - \hypersetup{colorlinks=false,
            allbordercolors={0 0 0},
            pdfborderstyle={/S/U/W 1}}
    ```

2. Change Pandoc command with `-V colorlinks=true` in advanced preferences , see [Pandoc conversion to PDF not providing colored hyptertext links](https://stackoverflow.com/questions/58866818/pandoc-conversion-to-pdf-not-providing-colored-hyptertext-links).

3. Use default .tex template plus the following code, see [Underlined links with hyperref possible?](https://tex.stackexchange.com/questions/47713/underlined-links-with-hyperref-possible?noredirect=1&lq=1).
    ```
    \documentclass{article}
    \usepackage[colorlinks=false,
                allbordercolors={0 0 0},
                pdfborderstyle={/S/U/W 1}]{hyperref}
    ```

**Comment by nathanlesage** [comment]
Would you mind trying that out (including your additions) in the current nightly version? I'll be going beta soon, so it's extremely stable, but haven't yet managed to do that. The reason is that, i.e. the property `header-includes` must be added to a **defaults file** – putting that into a YAML frontmatter will be ignored by Pandoc. Zettlr 1.8.9 doesn't give you access to the defaults files, but the 2.0.0 nightly does. (You can find the defaults in the nightly by going to File --> Assets Manager and then in the Exporting tab choose the PDF export)

You can find the nightlies here (they're still named 1.8.9 but in fact are the 2.0.0 branch): https://nightly.zettlr.com

**Comment by CarlossShi** [comment]
With `variables: {colorlinks: true}` in pdf assets manager, I can finally change the color of hyperlinks, but I don’t have enough time to find out how to underline them. Anyway, editable defaults file really helps me a lot. Thank you so much!

**Comment by nathanlesage** [comment]
I recommend you take a look at the Pandoc manual, it is fairly complete when it comes to these questions: https://pandoc.org/MANUAL.html
