### ISSUE TITLE
[Bug] The shortcut ctrl + ← to delete a file does not work

### ISSUE THREAD

**Issue by BenjaminHerbert** [Zettlr/Zettlr#2220]
### Description

The shortcut for file deletion does not work.

### Reproducing

Select a file and press <kbd>ctrl</kdb> + <kdb>←</kdb>. Nothing happens.

### Zettlr Version

Nightly

### Specify version

1.8.9+nightly-20210719

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [ ] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

System: linux 5.12.10-300.fc34.x86_64 (architecture: x64) - Fedora release 34 (Thirty Four)

### Additional Information

On startup, this logged messages:

```
> Zettlr --trace-warnings
(node:1914566) ExtensionLoadWarning: Warnings loading extension at /home/ben/.config/Zettlr/extensions/nhdogjmejiglipccpnnnanhbledajbpd:
  Unrecognized manifest key 'browser_action'.
  Unrecognized manifest key 'update_url'.
  Permission 'contextMenus' is unknown or URL pattern is malformed.
  Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.

(Use `Zettlr --trace-warnings ...` to show where the warning was created)
```

**Comment by nathanlesage** [comment]
Found the culprit: CodeMirror reserves that for deleting words/groups:

![image](https://user-images.githubusercontent.com/17251683/126864813-c31ec627-f58b-488b-b473-cce48f9e1bdf.png)

But it seems that I shouldn't disable that shortcut … question is: How do we solve this?

**Comment by BenjaminHerbert** [comment]
I would expect if a file or folder was selected or the file manager has focus, the _editor_ should not be "listening" for shortcuts and not interfere at all.
Other option might be to change the deletion shortcut to something like <kbd>ctrl</kbd>+<kbd>delete</kbd>.

**Comment by nathanlesage** [comment]
Hm, the editor should indeed not listen in its unfocused state. But it's actually quite hard to unfocus the editor instance, since in the past there were really many requests to always refocus the editor in many instances, so it's very likely that the editor is focused in a lot of instances.

However, even `Ctrl+Delete` doesn't work since that's reserved for removing to the _right_ of the group 🙄

I think I'll just be using the nightly on my Windows machine for a day or so to test out what seems to make the most sense. For instance, it might be sufficient on non-macOS systems to simply remove the keyboard shortcut for that menu item altogether (since all forms of delete and backspace are reserved in some form) and instead, if a file is selected and the file manager is focused that simply pressing `Del` suffices, because if my memory doesn't forsake me here that's how many apps on Windows are doing it anyway.

**Comment by BenjaminHerbert** [comment]
Just pressing <kbd>delete</kbd> when the file manager is focused sounds good. This is how it works in most of the apps I am using that have some sort of _file manager_.  (e.g., Gnome Files/Nautilus and ArchiveManager).

**Comment by nathanlesage** [comment]
Perfect! I don't know if I manage it this week, but if someone wants to tackle it, feel free to go forward!

**Comment by nathanlesage** [comment]
@BenjaminHerbert I just had a look and, weirdly enough, deleting files is already assigned the `Delete`-key, so it should already work that pressing Delete while the editor is focused should delete a character, whereas if anything else is focused (and the editor is not focused) it Zettlr should offer to delete the file o.O

**Comment by nathanlesage** [comment]
Anything new on this issue…?
