### ISSUE TITLE
[Bug] [Zettelkasten-Navigation] Sometimes Zettlr attempts to create files that already exist

### ISSUE THREAD

**Issue by cedardocster** [Zettlr/Zettlr#2228]
### Description

sometimes when you ctrl-click a file link when the file exists, zettlr must think you want to make a new file instead of open an already existing file and asks if you want to overwrite it.  Weirdly, sometimes it just opens the link.

(see attached)

### Reproducing

![Zettlr3](https://user-images.githubusercontent.com/10538705/126932874-baddf1e9-07b6-4106-a60c-7ddcd203ded5.gif)

### Zettlr Version

Nightly

### Specify version

1.8.9 july 19

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

ubuntu mate 20.04.2

**Comment by nathanlesage** [comment]
That's indeed weird. I just double-checked the logic for that and if there is a file called `Characters.md` it should simply open that one – across all loaded files. So I'm not quite sure what is happening there. Do the logs tell you something?

**Comment by cedardocster** [comment]
[R] [Main Window] Uncaught TypeError: Cannot read property 'toLowerCase' of null (index.js:2)

**Comment by nathanlesage** [comment]
Ahh thanks! That function name should help me narrow down where in the code stuff is going wrong. I hope I don't forget to, but I want to check in the coming days! (If I forget, just ping me on the weekend)

**Comment by nathanlesage** [comment]
I tried to reproduce this error locally but to no avail. Does this still happen in the most recent betas/nightlies? If so, it could be that the error occurs because of the chain of actions you performed until you hit that problem. I just tried having files auto-created and then following links to them but even that did not expose that behavior.

**Comment by vani-lu** [comment]
I am experiencing this error with ver 2.0.3, on MacOS BigSur. I sync all the files through OneDrive. I note that if I open a file with no prefix ID (in my case 8 digits), it opens normally. 

My solution: I change the regular expression to something else so that the prefix can not be matched to a Zettlr ID. The prefixed files can be opened through the link.

Some of my files are created or edited outside Zettlr (with Typora or Obsidian). I don't know if that behavior leads to the error. However, I'm also using a windows laptop but never experience this error on it. It is really weird.

**Comment by nathanlesage** [comment]
Found the culprit: Basically, when following internal links, Zettlr found an ID within the filename but then attempted to find a file that had the full filename (and not just the ID) as an ID, which obviously didn't work. Coming with 2.1

**Comment by cedardocster** [comment]
I discovered a while back that the error didn't happen if I stopped using a custom zettelkasten link regex:

(^[A-Za-z0-9 _]*[A-Za-z0-9][A-Za-z0-9 _]*$)

If I remember correctly I think I had that to allow for CamelCase links.  Does that even make sense?

**Comment by nathanlesage** [comment]
@cedardocster Your regex contains beginning and end-markers, and that makes the RegEx only match if the full string is an ID, and that was just what I fixed earlier!
