### ISSUE TITLE
[Feature request] Sync with git repo

### ISSUE THREAD

**Issue by brekov** [Zettlr/Zettlr#224]
Would you consider developing the feature that can synchronize documents using a git repositories?
some like  https://gitnoteapp.com/

**Comment by Monolecte** [comment]
For the moment, I’m using GitKraken.

**Comment by nathanlesage** [comment]
You can already sync it using Git. Only missing thing currently is an easy GUI for doing so. I can't promise when it will come, it could take up to a year depending on other features, it's low priority for me, because a) the people needing this will mostly be prepared to use the command line, and b) there are some more fundamental things that I need to do first. Besides: The idea is getting stronger to just build a plugin API for Zettlr, as the amount of features currently can't fit into the app all at once. I'll keep you posted.

**Comment by brekov** [comment]
known, thanks for reply.

**Comment by max-l** [comment]
Saving to a GIT repo could be a really powerfull feature, 
especialy if it is implemented in a way that doesn't require GIT knowledge, because
it would allow for (relatively) easily implementation of collaboration between users.


A user could configure a "Save to Git" (could be github or gitLab, or other...)
and that would setup a repo *or* join an existing repo (ex. the zettlr repo of another user).

Each  file would have it's own branch.

The user could have a "save to git repo" button which would have the effect of 
creating a commit and sending it to the remote repo.
There would also be a "publish" button that would cause a tag on the branch to be created, and the merge of the branch to the master branch.
