### ISSUE TITLE
[Bug] Following a link opens the search sidebar

### ISSUE THREAD

**Issue by matthijsbro** [Zettlr/Zettlr#2251]
### Description

When I click a link to another .md file the file is opened and the search sidebar opens with the id/title of the file in there. That seems unwanted since I'm no longer looking for that file, I just opened it. The file manager in the sidebar is closed /covered at the same time. 
Also, the file I linked from is closed, I'd rather see it remain open. My scenario is that I just opened an index file, follow one of the links and lose overview because the file manager disappears *and* the index file is closed too. 

### Reproducing

Follow an internal link too another Zettel. 

### Zettlr Version

Beta (if applicable)

### Specify version

v2.0.0-beta

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Big Sur 11.4

**Comment by kyaso** [comment]
The automatic search when following a ZKN link is there to help in finding backlinks. However, you can disable that behavior in the preferences (under tab "Zettelkasten").

I also noticed in the beta that file tabs get overridden when following links. There is also an option to force files into new tabs, however that would quickly fill your tab bar when you are just browsing through your notes. I think this is a bug, i.e., a file opened through a link should be opened in a new tab (as it's the case for 1.8.x).

**Comment by nathanlesage** [comment]
> That seems unwanted since I'm no longer looking for that file, I just opened it.

That is meant for finding other files that link to that file. You can turn off this behavior in the Zettelkasten preferences

> Also, the file I linked from is closed, I'd rather see it remain open.

By default, Zettlr tries to avoid new tabs. You can control this behaviour in the General preferences and tell Zettlr to always open files in new tabs instead of replacing the current one. If you use a mouse, you can also _middle-click_ (while also holding down Ctrl/Cmd) the link and it opens in a new one regardless of the setting. In general, middle-clicking something that opens a file will always open a file in a new tab even if you've told Zettlr to avoid opening new tabs.

> I think this is a bug, i.e., a file opened through a link should be opened in a new transient tab (as it's the case for 1.8.x).

The whole concept of transient tabs was too confusing to most users, so I completely ditched that in favor of more "browser-like" link behavior. I.e. there are no more transient tabs but rather you can use links and files just like in your browser:

* If you've chosen to avoid opening new tabs, Zettlr will in general attempt to replace the current tab (except the file has been modified or you're creating a new file in memory). You can _always_ open a file in a new tab by middle-clicking (with Ctrl/Cmd if in the editor) or by choosing "Open in new tab" from the context menu (if available)
* If you've not chosen to avoid new tabs, Zettlr will always open new tabs for everything.
