### ISSUE TITLE
[FEATURE REQUEST] Pinned notes

### ISSUE THREAD

**Issue by samarulmeu** [Zettlr/Zettlr#226]
Will it be hard to implement this option? Maybe have it appear on the file menu, like the "Set writing target...", and the pinned notes (note?) to appear on top of folders no matter how you choose to sort them?

**Comment by dambaras** [comment]
Second this.

**Comment by nathanlesage** [comment]
Currently, it's easy to achieve by using special characters in front of the file name:

![image](https://user-images.githubusercontent.com/17251683/59017843-dab59e00-8844-11e9-9efc-0e3180a566fd.png)

The implementation of such pinned notes would need to be included after manual sorting is implemented, see #120 and #121

**Comment by samarulmeu** [comment]
*Special* characters in front it is what I was using a lot before, but now I prefer to keep my notes' name as clean as possible (I even gave up using spaces), that's why I was thinking of pinned notes. 
I see your point in having to wait for the other issues to be resolved first.

**Comment by dambaras** [comment]
I've used special characters as well. BUT that doesn't help if you're viewing notes in "last modified" order. I agree that this is not a top priority, but it would be helpful. (As I've noted elsewhere, my top priorities are (1) a floating "new note" pane à la The Archive, and (2) the option to include note titles along with ids when linking notes.) Thanks as always.

**Comment by nathanlesage** [comment]
… I think I'm still puzzled as to what you mean with "floating new note pane"? Something as I've already opened as an issue in #175?

**Comment by dambaras** [comment]
#175 appears to relate only to Windows and Linux, no? Do you have something similar in plan for Mac? As for what I'm describing, see this little screencast I made of how this works in The Archive: [https://www.loom.com/share/f00fc9121ffc4074bc50dc55de5fb4ab](https://www.loom.com/share/f00fc9121ffc4074bc50dc55de5fb4ab). Thanks again for being so responsive!

**Comment by nathanlesage** [comment]
no no, #175 will be — as all features — cross platform :) (I don't develop features for all platforms except the one I use the most :D)

Imagine it a little bit like the Tray notes from MindNode, for instance: 

![image](https://user-images.githubusercontent.com/17251683/59091484-b96db400-890f-11e9-8768-4b782993ced5.png)

You simply browse the web/your PDF files/whatever and whenever you see something worth noting, you'll be able to use some global shortcut and such a small Tray Window will pop up, letting you type directly a new note!

On Windows and Linux, these Tray windows will be positioned differently (wherever the tray is), but it'll work the same for all, click the Tray Icon or use a global shortcut and just type! If you have any further questions, let's put this discussion to #175, to not pollute this issue here!

**Comment by dambaras** [comment]
OK, perfect re quick note/#175. Thanks!

**Comment by danieltomasz** [comment]
I am still +1 for innef notes (like pinned post on social media), quick note is also nicely but this is a differentiations functionality

**Comment by exilexi** [comment]
Also +1 on the pinned notes. I use Zettlr for Zettelkasten, so I mostly use daily notes and definitely use chronological sorting 100% of the time. But I have a resource page that I’d like to always have easy access to, even if I edit it rarely. In Roam, I had it in my shortcuts in the left panel so I could very easily use it all the time for reference - that’s the one thing I miss most since transitioning to Zettlr!

**Comment by nathanlesage** [comment]
With the new FSAL this will indeed be easily possible, just requires a super short amount of additional code! I'll get to it once I've done refactoring this behemoth!

**Comment by danieltomasz** [comment]
Any progress on that? :)

**Comment by nathanlesage** [comment]
Nope, there's lots to fix still with the 1.7 :(

As long as I don't find the root causes for the remaining two small bugs, I can't release 1.7 and begin working on new features …

**Comment by RM35M4419** [comment]
Hey! This feature would be great.
I've been using special character as several others.

But what I was thinking was similar to Firefox pinned tabs: always open when launching Zettler, first in the row, and a bit more difficult to close.

This might be a separate feature thou.
