### ISSUE TITLE
[Feature] Support for GDScript

### ISSUE THREAD

**Issue by johnnywong1** [Zettlr/Zettlr#2300]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [ ] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [ ] I have searched the documentation to make sure I did not overlook it.
- [ ] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

Hello,

I was hoping you could add syntax highlighting for GDScript which is used in Godot.

### Example Workflow

N/A

### Caveats

N/A

### Do you wish to attempt implementing this yourself?

No

### Platforms

- [X] Windows
- [X] macOS
- [X] Linux

**Comment by nathanlesage** [comment]
After a quick search it seems that there is no GDScript mode for CodeMirror, which means it is non-trivial to implement this.

Furthermore, since CodeMirror 6 is more and more progressing, I always try to refrain from making any bigger changes with the outdated CodeMirror 5.

That being said:

* I will not implement this feature for the current iteration of Zettlr, since it still requires CodeMirror 5.
* If someone, however, badly wants this feature and is ready to spend the time developing this highlighting mode knowing that will be deprecated in the future, a PR is always well-received.
