### ISSUE TITLE
[Enhancement] The home button should set the cursor at the start of a row

### ISSUE THREAD

**Issue by UriMtzF** [Zettlr/Zettlr#2306]
### Description

When I'm using other editors, I usually use a lot the keyboard and the "home" key is a keybind that I use to set the cursor to the start of the row, but today using this key, set me at the start of the paragraph.

So I don't know if it's a bug, but it will be great if the cursor will transport to the start of the row when pressing "Home" button.

### Proposed Changes

Set the cursor at the start of the row instead of the start of the paragraph.

### Caveats

There shouldn't be conflicts with other features.

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Beta (if applicable)

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
It is not a bug, but it's a less-well documented option. You can control this behaviour with the setting "Use the CodeMirror default actions for Home/End" (editor tab in the preferences). If it's unchecked, Home/End will go to the start/end of the _visible line_. If it's checked, Home/End will go to the start/end of the _actual line_ (which displays as a paragraph due to the line-wrapping).

I have now set the default of the preferences to "false" so that by default Home/End will go to the start/end of the visible line instead of the paragraph (the default thus far), which I think is more confusing for people.

I will also add a FAQ entry to the documentation!
