### ISSUE TITLE
[Bug] Exporting a project doesn’t seem to work on Zettlr 2.0 beta 1

### ISSUE THREAD

**Issue by ploum** [Zettlr/Zettlr#2312]
### Description

Exporting a project does not seem to work with Zettlr 2.0 beta.

### Reproducing

In the project properties, you can select the options you want to use for exporting.

1. It’s quite counterintuitive that no option is selected and that "export" is greyed out by default (not a big deal but I mention it for completness)

2. You can select multiple export options. I don’t understand how it is supposed to work.

3. I’ve tried a few of the options and didn’t manage to have any result. I simply have no feedback at all. (Tried all PDF and all Text related exports).

4. Only exception : TextBundle. Which throws an error telling me that this format requires a single text file and doesn’t work with projects.

I’m probably missing something here but it looks like the problem is not only my fault and that something is not working as it should, at least under Linux.

### Zettlr Version

Beta (if applicable)

### Specify version

2.0.0-beta1

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [ ] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Regolith Linux

**Comment by nathanlesage** [comment]
> It’s quite counterintuitive that no option is selected and that "export" is greyed out by default

Ah, good point. When I was (re)implementing the project functionality I didn't yet know how to pass default options but I think I just got an idea to simply pre-set the PDF functionality (so that you can immediately export and have a better visual information on how this is suppoed to work).

> You can select multiple export options. I don’t understand how it is supposed to work.

It should be a selectable list where you can click the checkboxes next to the names of the formats, like this:

![image](https://user-images.githubusercontent.com/17251683/129476022-3e2b5a7a-894d-4639-95de-3e4017e848d4.png)

It can very well be that there are still some styles missing so that you have a hard time seeing what I intended there. A screenshot would be most helpful!

> I’ve tried a few of the options and didn’t manage to have any result. I simply have no feedback at all. (Tried all PDF and all Text related exports).

Mh, that's not good. I realize that at least on my MacBook the first time Pandoc starts up it takes quite some time since Rosetta has to translate the program from x64 to ARM first, but it works well here. Is there anything in the logs after the failed export?

> TextBundle. Which throws an error telling me that this format requires a single text file and doesn’t work with projects.

I didn't know that I implemented that, but it does make sense (since Textbundle is intended for sharing single files with their assets).

**Comment by ploum** [comment]
What I mean by "not understanding" is that I select one or multiple export options. Then I close that dialog. Then I right clic on the project and select "export".  But nothing happens.

**Comment by nathanlesage** [comment]
> What I mean by "not understanding" is that I select one or multiple export options. Then I close that dialog. Then I right clic on the project and select "export". But nothing happens.

Hm. Not even an error in the logs? Just nothing?

**Comment by ploum** [comment]
I may sound completely stupid but… I didn’t manage to find the logs in the beta version…  (sorry for that)

**Comment by nathanlesage** [comment]
Don't worry! First you have to switch on the debug mode in the Advanced preferences, and then there should be a new menu called "Develop" where you can open the logs of the application.

**Comment by nathanlesage** [comment]
Ouh. Wait. I get it. I just tried out what you mean: I've switched to OS native notifications, and *obviously* Electron doesn't support native notifications on all Linux systems. So no wonder you don't see the notification.

I'll be pushing a commit that, on Linux, the exported files will be displayed despite the notification! Gimme one sec …

**Comment by ploum** [comment]
Thanks, will test in the next version :-)
