### ISSUE TITLE
[Bug] Export ignores unsaved changes

### ISSUE THREAD

**Issue by charris101** [Zettlr/Zettlr#2318]
### Description

The export function exports the previously saved version of the file, ignoring any unsaved changes. More significantly, there is no warning to the user that the Export has done this. I think the standard behaviour would be to export the current version, including unsaved changes, but at the very least there should be a dialog asking you to save first.

### Reproducing

Export a file with unsaved changes using the export function

### Zettlr Version

Beta (if applicable)

### Specify version

Zettlr2.0.0 - Beta1

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
… or have the export trigger a previous save silently? I wanna minimise the amount of reads/writes to the filesystem to not put too much strain on the SSD cells, so that might be the easiest solution. Thoughts?

**Comment by dialmove** [comment]
Hard to say... Without autosave, I'd expect Export to generate exactly whatever is already committed to saved files, ignoring unsaved changes. But with autosave, I'd expect it to include any recent change, not ignore those still in memory and waiting to be saved soon.

And when autosave is off, I definitely don't want to save pending changes silently without warning! If I disabled it is because I want to decide whether I want to save or discard those changes as a single action, being fully aware of this step.

So I'd say, treat this case similar as closing an file with unsaved changes:
- If Autosave is disabled, create a prompt dialog that all unsaved changes to all files in the project will be written before continuing. (If I cancel the dialog, nothing happens).
- If Autosave is enabled, silently write all those pending changes and export.

**Comment by charris101** [comment]
Great suggestions dialmove, those options sound like a good solution

**Comment by nathanlesage** [comment]
Sounds like a reasonable compromise!
