### ISSUE TITLE
[Bug] Info message about No Directory Selected hard to read and placed suboptimal

### ISSUE THREAD

**Issue by foss-** [Zettlr/Zettlr#2326]
### Description

After installing Version 2.0.0-beta.1 (2.0.0-beta.1) Zettlr showed an empty main window. It was not immediately obvious why, but library not opened correctly was an easy assumption. However the info messages about that was placed in a narrow column. Maybe it would be better to use the large right column for that? Or decrease font size to ensure it will not be cut off in many scenarios.

![main window no library selected](https://user-images.githubusercontent.com/5708172/129711730-a28fef26-dadd-4f9a-bc7d-096b2e9920a5.gif)

### Reproducing

Open Zettlr with no library selected.

### Zettlr Version

Beta (if applicable)

### Specify version

2.0.0-beta.1 (2.0.0-beta.1)

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

11.5.2

**Comment by nathanlesage** [comment]
Ugh, that definitely looks ugly! Seems to be a styling issue. I'll have a look.

**Comment by nathanlesage** [comment]
It's a super-weird visual glitch; I've been trying to pinpoint this for weeks now and just tried again – unsuccessfully.

**Comment by foss-** [comment]
You are able to reproduce but unable to understand why this is happening or you are unable to reproduce?

**Comment by nathanlesage** [comment]
The former: I noticed this bug myself, because when you set the setting to "combined" file manager mode and start the app, then the file list will display although it should not. Removing the class and re-applying it suddenly moves. I think it might be a race condition on startup where something forces a layout in Chrome (displaying the file list) and later on another layout does not happen (after the hidden-class has been applied)

**Comment by nathanlesage** [comment]
Since I fixed the weird combined sidebar mode display bug, this is also obsolete now!
