### ISSUE TITLE
[Bug] Distraction Free Mode/ Typewriter Mode is not updated in menu when selected.

### ISSUE THREAD

**Issue by tscheims1** [Zettlr/Zettlr#2360]
### Description

When the Option "Distraction Free Mode" or "Typewriter Mode" is selected the check mark in the context menu is not updated.
The function works as exspected

### Reproducing

1. Select Distraction Free Mode or Typewriter Mode in the Menu
2. The Check mark is not updated.

### Zettlr Version

Beta (if applicable)

### Specify version

Beta 3

### Your Platform

- [X] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10, Manjaro

**Comment by nathanlesage** [comment]
In fact I even disabled the checkmark because right now the behavior is more than wonky. I'll take this issue as a reminder to properly implement this.

**Comment by tscheims1** [comment]
maybe just change the text is enough.

**Comment by raphraph** [comment]
@nathanlesage This issue is not closed for me and since it is still there and got worse with the 3.0.0-beta version I would like to comment it. Do you prefer that I open a new issue ?

In my case I still do not have any checkmark for these two modes (or with version < 3.0.0-beta, the checkmark was sometime there but wrongly checked/not-checked... meaning not corresponding to the mode status) but now the Typewriter mode does not work at all (the distraction free mode seems to work correctly).

I'm on Ubuntu 22.10, with Zettlr v3.0.0-beta and in dark mode.

**Comment by nathanlesage** [comment]
I removed the checkmarks, since we cannot really track the state in the new editor implementation. Typewriter mode and distraction free mode should work, however. If you think they don't, please describe more of what you're expecting and what you're seeing. Also, feel free to include the community over on Discord, which may be more able to help you if this turns out to be miscommunication on my side!
