### ISSUE TITLE
[Bug] Writing progress "pie charts" do not show up in 2.0.0.-beta3

### ISSUE THREAD

**Issue by wilkohardenberg** [Zettlr/Zettlr#2414]
The writing progress pie charts used to show up in the file manager. With the update to 2.0.0.-beta2 and -beta3 they disappeared. As far as I can recall they worked in beta1 (but I must admit that I haven't used Zettlr in over a month because I was on holiday).

**Comment by wilkohardenberg** [comment]
Additional info:
I'm on macOS Mojave 10.14, architecture Intel 64x.

**Comment by nathanlesage** [comment]
Good to know they stopped working somewhere in between beta 1 and beta 2! I'll have a look

**Comment by nathanlesage** [comment]
Just checked, and for me they're working fine:

![image](https://user-images.githubusercontent.com/17251683/132982768-a53111c4-1f1d-4721-98e3-3f9e59fba3a7.png)

However, could it be that you are using the combined file manager mode, where files and directories are interleaved in the file tree? If so, there the writing targets don't appear due to the limited screen estate. This additional info is only visible in the file list since there we have much more space.

**Comment by wilkohardenberg** [comment]
I found the toggle for that, but no, I’m using the thin file manager. I checked, it looks the same with the combined one.

**Comment by nathanlesage** [comment]
That is weird. But you have a writing target set, right?

**Comment by wilkohardenberg** [comment]
Duh, yes. But I just noticed that the reset button doesn’t work.

**Comment by wilkohardenberg** [comment]
Sorry to bother, but not having heard anything further I wondered if I should just accept that it is a weird thing that happens only to me. Attached is how the file manager looks to me: not much space left for the pie charts.

![Screenshot 2021-09-12 at 14 29 40](https://user-images.githubusercontent.com/1612993/133325987-50242dff-df00-4ddd-895a-422a089a83c1.png)

**Comment by nathanlesage** [comment]
Oh. Yeah. The writing targets only appear if you select the option to also view file metadata. That explains it!

**Comment by wilkohardenberg** [comment]
Oh, that was it: "Show file information." Thanks. Solved!
