### ISSUE TITLE
[Bug] Beta 3 Search and Replace edits links

### ISSUE THREAD

**Issue by ludos1978** [Zettlr/Zettlr#2424]
### Description

Whats happening:
When searching and replacing characters it also changes links to images and URLs.

Expected behaviour:
When i search and replace characters it should not change links.

### Reproducing

have a md file with following content:

`
[github_bug_report](https://github.com/Zettlr/Zettlr/issues/new?assignees=&labels=bug&template=bug_report.yml&title=%5BBug%5D+)
`

search and replace "_" by "-"

results in:

`
[github-bug-report](https://github.com/Zettlr/Zettlr/issues/new?assignees=&labels=bug&template=bug-report.yml&title=%5BBug%5D+)
`

the "_" in the Link is also replaced by a "-"

### Zettlr Version

Beta (if applicable)

### Specify version

2.0 Beta 3

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Big Sur 11.5.2

**Comment by nathanlesage** [comment]
I would say this is expected behavior. I get that it can be confusing, but the links themselves are still part of the document, and I cannot imagine a way to accomodate this specific request without breaking a lot of functionality. I would maybe suggest you try using a regular expression instead, since that allows you to disregard links completely and only replace outside of links.
