### ISSUE TITLE
[Bug] Opening a file from the file sidebar replace current opened file in tab

### ISSUE THREAD

**Issue by tscheims1** [Zettlr/Zettlr#2473]
### Description

- The behavior is very unexpected. (I don't know any other tab based application that replaced an opened  tab when a new file is chosen)
- The behavior does not make much sense for me. If I want replace the current tab, then I close the tab and open an new file. in the most cases I want open an additional file (e.g for comparing, copy some blocks)  (I could open the file with the option open in a new tab, but I find it not very user friendly that the user has almost always choose the option from the context menu)

Maybe I don't get it. But why do you switched the behavior from zettlr1 to 2? What Is the intend of this?

### Reproducing

1. Open a file 
2. File is opened in tab
3. open second file
4. opened file in tab is replaced with new file

the same behavior happened when the file is chosen from a search

### Zettlr Version

Beta (if applicable)

### Specify version

Beta 4

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Manjaro Linux, i3, packages up to date.

### Additional Information

Thank you for your effort.

**Comment by nathanlesage** [comment]
This is the setting "Avoid new tabs" in the general settings of Zettlr. It is checked by default, since most users actually want files to be replaced (many use Zettlr as a note-taking app rather than a replacement for word processors).

That being said, simply disable that option to have Zettlr always open a new tab. It is not yet in the docs because these still need updating for the upcoming 2.0 release!

**Comment by tscheims1** [comment]
@nathanlesage In context of a note taking app make these option sense. 
I just disabled the option. Now it works. Thanks alot
