### ISSUE TITLE
Inconsistencies among the different ways to create a new file.

### ISSUE THREAD

**Issue by monkey-sapphy** [Zettlr/Zettlr#2480]
### Description

I have tested the 3 ways I'm aware of to create a new file. the behaviour of Zettler differs depending on the chosen way and this is quite onfusing.

1. using the menu bar file option and then selecting the type of file, i.e. : .md, .tex, .json, yaml:
- Zettlr asks to choose a type of file,
- Zettlr creates the file with the ID as name but does NOT prompt for a filename and the file is NOT saved on disk
- When using the "save" command after the file creation, the proposed directory where to save the file is NOT  the directory currently selected

2. using the shortcut Ctrl-N
- Zettlr creates a .md file (no choice of the type of file) with the ID as name but does NOT prompt for a filename and the file is NOT saved on disk
- When using the "save" command after the file creation, the proposed directory where to save the file is NOT  the directory currently selected

3. right-clicking from a selected directory (being a workspace or not)
- Zettlr prompts for a filename (_proposing the ID as name_) and when "enter-clicking" the proposed or the changed filename but Zettlr DOES save the file on disk in the selected directory. The created file is always of type .md

It would help to bring the following changes:
- always prompting for a filename independently of the way of creating a new file
- the proposed directory (in the file explorer) where to save the newly created file, should always be the currently selected directory
 

### Reproducing

Create a new file, resp. by: 
1. using the menu bar file option
2. using the shortcut Ctrl-N
3. right-clicking after having selected a directory

### Zettlr Version

Beta (if applicable)

### Specify version

2.0.0-beta.4

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Win 7

**Comment by tscheims1** [comment]
The Difference between 1 and 2 make sense for me, because ctrl + n creates a new markdown file.

But what confuses me as well: The File Dialog does not prompt the current working Directory.

**Comment by nathanlesage** [comment]
So there have been some important changes to the file-saving workflow recently. Basically, there are now two broad ways corresponding either to "quick'n'dirty: Just create me some file" or to "safety first: I wanna have full control over my files."

In the advanced preferences there's an option to either prompt or not prompt for filenames. If it's checked, Zettlr will simply always create a file and be done with it. If its unchecked, it will *always* ask you for a file.

The reason why the filename is always ending in .md is because that's the filename generation pattern. I have to replace that .md with some variable or something at some point. So in total, the new system can still require some more attention.

In light of this information: Could you clarify where you see the points of improvement? That would greatly help me make it better!

**Comment by monkey-sapphy** [comment]
It version 2.0.0.beta-4, checking or unchecking the option “Do not prompt for filename when creating new files” makes NO difference to the behavior of Zettler. 
Independently of the selection of the aforementioned option, when creating a new file:
-	By right-clicking on a directory, it DOES ask for a finename
-	By using the menu bar file option, it NEVER asks for a filename
-	By using Ctrl-N, it NEVER asks for a filename
So the first thing that should be checked is the working of the option “Do not prompt for filename when creating new files” as this option no longer works as expected in beta-4.

**Comment by nathanlesage** [comment]
Whops, that shouldn't be o.O I'll have a look.

**Comment by nathanlesage** [comment]
Alright, small update: I just sumbled upon this myself. Someone asked how to make Zettlr not create in-memory files and I was completely lost as to how to achieve that.

Furthermore, I also more and more see that we do need a cleanup finally.

After having had the chance of experiencing the problems myself and thinking about this problem, I would like to suggest the following solution — please comment anything I forgot!

***

First, we have two dimensions here:

1. Allow creation of in-memory files **versus** always create files on disk directly
2. Ask for confirmation of the filenames **versus** never ask for confirmation (renames are possible)

Second, we have two ways of creating files:

* Right-clicking a directory
* Utilizing `Cmd/Ctrl+N`

This leads, third, to the following use-cases:

1. A user who wants to have in-memory files where they can just drop some text, i.e. a form of clipboard and also wants to confirm every file name should retain the behavior of the directory creation method and wants to see the save dialog upon saving an in-memory file
2. A user who wants to have in-memory files but doesn't want to bother with filenames can use the directory creation method without any filename confirmation, and when they hit `Cmd/Ctrl+S` on in-memory files these just get saved to the currently selected directory without a dialog
3. A user who does not want to have in-memory files but wants to confirm the filenames should receive the input field upon the directory creation method and, when using `Cmd/Ctrl+N` be taken *directly* to the Save-File-dialog
4. A user who neither wants in-memory files and doesn't bother with the filenames then has the same workflow regardless what he does: `Cmd/Ctrl+N` utilizes the currently selected directory, right-clicking a directory does the same but with a specified directory.

Fourth, this means we need the following two options:

```
[ ] Allow in-memory files
[ ] Do not prompt for filename
```

One of these is already present, so we would have to add another one. **However** I think we need a better name than "in memory file" because that sounds relatively technical.

Any suggestions?

**Comment by efficacy** [comment]
Personally, I have never understood the rationale for the "in memory" (a.k.a silently disappear if anything goes wrong) files. 
The "feature" really doesn't feel like a core part of Zettlr to me.  It isn't grouped with a workspace, because it doesn't exist as a file. It can't be linked, as it doesn't have a filename. In short it has nothing to do with Zettlr, but is just an imagined convenience for someone who would rather clog up the Zettlr tab bar than change windows. When you add to this the large amount of risk and confusion which always accompanies the idea (not being able to think of a good name for it is a clue, here)  I think this is a prime candidate for trimming.

Every operating system that I am aware of already provides this kind of "scratch pad" facility through a generic text editor, for people who like to take risks with their information. I think Zettlt should always "fail safe" and never knowingly lose information on a crash or force-quit. That means always saving files.

If we remove the red herring of in-memory files, we are just left with a variety of ways to create new files (ctrl-N, right-click on a folder, the File::New File menu option, and the missing toolbar icon) , all of which can be linked to the same code but with slightly different parameters, and a single config option to choose between automatic file naming or prompting for a file name.

That all seems much more rational to me. Other opinions are also available ;)

**Comment by nathanlesage** [comment]
> but is just an imagined convenience for someone who would rather clog up the Zettlr tab bar than change windows.

That's basically specifically why I implemented that :D 

I really don't want to trim away that thing … I think.

**Comment by nathanlesage** [comment]
> Maybe provide a dedicated "scratchpad" button or a setting which adds a visually-different tab every time you start Zettlr, or some other thing which makes it very clear that this is not a regular file.

I was actually thinking of adding a scratchpad button to the traybar icon, so that you would have an always-on-top Markdown syntax highlighting text scratchpad that you could pull up whenever needed.

But then I remembered that a lot of editing apps do have this in-memory file concept. Or at least had, because now even VSCode has "unsaved" files they are still saved somewhere.

Nargh, it's difficult to get used to novel usability things. Maybe I'm getting old. I'd say let's discuss this tomorrow on Discord as well, because I feel there's a larger story to that!

**Comment by quickfold** [comment]
Small point from a non-programmer: the concept of "in-memory files" doesn't exist for me. For me a file is something saved with a filename that I can see in a file manager. I suggest workshopping the name if you keep this feature. Perhaps "Allow temp files (deleted upon Zettlr exit)"?

**Comment by zack-kimble** [comment]
I'll offer my two cents as a rather uninformed user: I found it confusing and thought it might be a bug.

I mainly use Zettlr for note taking with simple markdown and some linking. I occasionally use it to prepare something in markdown before rendering it for Confluence or a doc. I'm not a power user, and I don't exactly keep up with the release notes.

I used to create new docs by clicking the icon on the top left or using crtl-n. Since I use it for notes, I would sometimes open a document in the middle of a conversation, so I would just hit enter and take the default generated name. Later I'd go back and rename. Recently, it seemed like something about that process was different. I couldn't entirely put my finger on it. All I could concretely pick up on was that the new file button seemed to be gone and I now had to use save as instead of "rename" after I put notes in a default named file. I guess I was on top of things and always did that before closing the app until one day I didn't and I lost a bunch of notes.

Honestly, it didn't cross my mind at all that there would be an entirely unsaved file in the app. It had never worked that way before. I spend most of my time either in IDE's or web based applications where everything is autosaved in some form. Zettlr also resembles an IDE visually (and in that it works from a directory). At this point the only applications I use that don't autosave are MS dinosaurs, and they like to throw lots of warnings about unsaved work. Anyway, I was really confused about what happened and posted in the Q&A and was directed here.

I can't speak to whether others would like to have in-memory files. I personally don't see the need. I would only ever want to use that if it was something sensitive, which I wouldn't want to be pasting into my notes and publishing app. I'd just use gedit or similar. I will say that changing default behavior from autosaving to not (which is essentially what happened for new files) is not great for folks like me that don't read all the release notes. I know, read the manual and all that, but the consequences should perhaps be a little lower for not reading the release notes.

**Comment by nathanlesage** [comment]
> At this point the only applications I use that don't autosave are MS dinosaurs, and they like to throw lots of warnings about unsaved work.

This is a very important sentence, and also the reason why I implemented that. Most text editors (not just Word, the default text editors as well) also basically open up and unless you actually save the file, it's an unsaved document. I implemented this feature because I wanted to have that convenience of a non-saved scratchpad for very quick notes that I wanted to throw away afterwards again within Zettlr, without, as Frank mentioned, having to switch programs. Plus it does also fall into that category of "things that people know from other programs".

But to be honest, I don't use that very much (I have, for the better or worse, started doing this right within whichever file is currently open when I have to take some throwaway notes), and given that there are many people who are honestly baffled by it, I begin to see that it might add more confusion than it solves…
