### ISSUE TITLE
[Bug] Unable to save project folder settings

### ISSUE THREAD

**Issue by mo-nonym** [Zettlr/Zettlr#2535]
### Description

Hello.
When changing the project folder settings the Save button doesn't respond. Even when selecting Save via tab commands + enter, the button doesn't respond. Cancel works fine but rejects the changes.

### Reproducing

- Create project from folder
- Open project folder settings
- Make a change
- Click "Save" (bug)
---
Nothing happens until hitting "Cancel".

### Zettlr Version

Stable (most recent version)

### Specify version

1.8.9

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Manjaro Linux x86_64, 5.4.143-1-MANJARO

### Additional Information

AppImage version.

**Comment by nathanlesage** [comment]
Would you mind trying out the most recent Zettlr 2.0-beta version and see if that still doesn't work?

**Comment by mo-nonym** [comment]
Hi. I tried the AppImage 2.0.0-beta.5 and I can't find the project folder settings. Right-click on the folder doesn't brings it up. As well as no create/remove project.

**Comment by nathanlesage** [comment]
> Right-click on the folder doesn't brings it up. As well as no create/remove project.

Oh, right! It's under properties now. So you can right-click a folder, then "Properties" and then you have the project settings there! Apologies!

**Comment by mo-nonym** [comment]
Ok, found it ! I'm able to make changes for the export format and include/exclude files. These changes remain when closing Properties and are applied when I do an export.
But the options present under Settings in Zettlr 1.8.9 are missing (margins, title page etc.). Is this something to be mangage with a CSL stylesheet ?

**Comment by nathanlesage** [comment]
> (margins, title page etc.). Is this something to be mangage with a CSL stylesheet ?

Not with a CSL stylesheet but with TeX templates. Basically, those options were an attempt at making simple customizations easier, *but* I had to figure that it was not a sustainable solution, so I removed them. You can control many of those options with YAML frontmatter options, actually.

Feel free to remind me some time after release of 2.0 stable that it would be very good to document the default options in the Docs and how you can easily do that, since the Pandoc documentation is not very verbose in this regard.
