### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by walzenjet** [Zettlr/Zettlr#2540]
### Description

For personal comments in excerpts I use quotation marks, as in ``comment`` (seemed to be the best option).

When the two quotation stand at the end of the line and I hit enter, they get auto-completed to three of them (```). I then have to go back to the line and manually delete one of them. Is this preventable?

Thanks!

### Reproducing

Type `` and hit enter.

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Big Sur 11.6

**Comment by nathanlesage** [comment]
Backticks are used to delimit codeblocks in Markdown. I assume you attempt to use LaTeX quotation marks? If so, don't worry, since Pandoc can automatically convert the regular quotes to LaTeX-compatible ones during export. So this behavior is not preventable since it is very much intended. If you want regular inline-code to do your comments, use single backticks, not two backticks.
