### ISSUE TITLE
[Bug] Title of the citation options is still an internal variable not a nice title

### ISSUE THREAD

**Issue by mousetrappling** [Zettlr/Zettlr#2548]
### Description

In the editor section of the preferences dialogue the title of the citation options is a variable name not a title.

### Reproducing

Look at the dialogue.

### Zettlr Version

Beta (if applicable)

### Specify version

2.0.0-beta.5

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [x] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 20.04

### Additional Information

![Screenshot from 2021-10-02 16-57-49](https://user-images.githubusercontent.com/85501268/135724021-22bfb12d-e6ec-4d3b-8c71-173004452b39.png)

**Comment by nathanlesage** [comment]
Yes, the problem is that between me adding the title to Translate and the CI fetching the new languages I released the beta, so the app itself didn't contain the translation. However, on first start, the beta should've downloaded the updated translation automatically. A simple restart of the app should therefore fix that! :)
