### ISSUE TITLE
[BUG] Inconsistent behaviour handling files

### ISSUE THREAD

**Issue by samarulmeu** [Zettlr/Zettlr#255]
I mention from the start that this behavior I encounter on Linux (Ubuntu based distro). I don't know if it affects other platforms. 

I mainly used Zettlr for notes that where on a local drive or on a USB stick that I mounted and everything went fine until a week ago or so when I started to have a mixed environment and I tried to move some files from the USB stick to local drive and vice versa. The Zettlr's behavior is inconsistent and chaotic at times: 100% of times the files are not moved, some times are just copied and sometimes Zettlr doesn't *see* anymore the files I wanted to copy although it still exists in the folder and Zettlr displays it in the side panel. After I restart the app the files are again *seen*.

Moving files between folder from the same media is working perfectly **all the time**.

**Comment by nathanlesage** [comment]
As I've rewritten the complete file handling code due to the major refactoring of the underlying watchdog instance, I would suggest we wait until the 1.4 beta, as then we'll be able to test the file operations better. Maybe the bug you encountered is already fixed (and probably a bunch of others appeared)! Anyway, I think the next beta will be released in mid-July, when I've had the time to test the file operations a little bit more. A friend of mine has had some weird issues herself, as the logic is still a little bit unstable, I fear :S 

But I hope to make it run stable for 1.4, to not embarrass myself 😆

**Comment by samarulmeu** [comment]
Can't wait for the beta. It is supposed to solved a lot of my current issues. So let's hope will deal with this bug too. But can anyone confirm that Zettlr it has the same behavior on Mac or Windows?

**Comment by nathanlesage** [comment]
As far as I'm concerned the issue can by definition not occur on macOS and linux, as on Unix-based systems all removable media is mounted to the filesystem itself (either `/Volumes` or `/media`).

But I'm beginning to develop some hate towards NodeJS: https://github.com/nodejs/node/issues/19077

So it seems I have to implement a failsafe for that bastard behaviour on Windows. Why again did Microsoft invent drive letters in the first place ...?

**Comment by samarulmeu** [comment]
By definition, but I struggle with it on Linux. That's why I found it strange...

**Comment by nathanlesage** [comment]
Alright, that is indeed strange o.O I haven't considered that. On which distribution are you working, and where are the files mounted? To `/media`? If so, I strongly suspect an error within the NodeJS server itself …

**Comment by samarulmeu** [comment]
As I mentioned, is an Ubuntu based distro. The removable media are under `/media/username/UsbStickName`

**Comment by nathanlesage** [comment]
Hm … does this help: https://github.com/nodejs/node/issues/21957 ?

**Comment by samarulmeu** [comment]
I'll get into it tomorrow. Maybe look in some logs to see if an error appears. ...

**Comment by samarulmeu** [comment]
> Hm … does this seem to relate to your issue? [nodejs/node#21957](https://github.com/nodejs/node/issues/21957)

From what I see the problem there is in renaming directories. My issue is about not moving files between a mount media and the *normal* media.
 
So maybe I was not so clear in my explanation: 
- let's say I have in Zettlr 2 directories open dirLocal and dirMedia (located on an USB stick mounted under `/media/user/stick`).
- if I try to move a file `fileA` from `dirLocal` to `dirMedia` nothing happens (no error in the logs either). Sometimes if I try to select `fileA` Zettlr complains that it cannot find the file although it is still shown in the side panel and also in the `dirLocal` (restarting Zeetlr eliminates the complain, but `fileA` is not moved). The same thing happens when I try to move from `dirMedia` to `dirLocal`
- moving files inside  `dirLocal` or `dirMedia` works as expected. 
- using linux `cp` command I can move the `fileA` from `dirLocal` to `dirMedia` so the problem is not related to writing permissions.

**Comment by nathanlesage** [comment]
> From what I see the problem there is in renaming directories.

Yes, the function I'm using is `fs.renameSync`. If you rename the file `/media/user/USB/file.md` to `/home/user/Documents/file.md`, it's a "rename" strictly speaking but it will move the file accordingly. (You may notice that [in the NodeJS FileSystem API](https://nodejs.org/api/fs.html) there's no method called "move")

> if I try to move a file `fileA` from `dirLocal` to `dirMedia` nothing happens

It really sounds like a bug in Zettlr 1.3, because I've found a lot of strange code within the move commands when I was rewriting them last week, so it's very likely there was something strange going on. Maybe, indeed I accidentally fixed it while cleaning up the commands.

… oh boy, I just found superfluous code AGAIN. If you want to have a look at the respective logic: https://github.com/Zettlr/Zettlr/blob/develop/source/main/commands/request-move.js It _looks_ right, but maybe I've overlooked something!

**Comment by samarulmeu** [comment]
At my level of understanding, it seems OK. Let's see in the first beta if the issue is solved.

**Comment by nathanlesage** [comment]
I think we solved this one, right …? :D
