### ISSUE TITLE
[Bug] Weird formatting and scrollbars on preferences

### ISSUE THREAD

**Issue by praxiq** [Zettlr/Zettlr#2563]
### Description

The Preferences window has worse formatting in beta 5 than it did in 1.8, and has horizontal and vertical scrollbars.

As I recall, the settings used to be displayed in a rather nice 2d layout that fit all the settings in the window. Now, it's all one column, and I _think_ the text looks a bit smaller and less well aligned, as though perhaps some CSS is missing.

The vertical scrollbar seems to appear because the settings all show up in one column, which makes them not fit in the default window. The horizontal scrollbar seems to appear because the addition of the vertical scrollbar makes the space too narrow. (If I resize the settings window to fit all the settings, both scrollbars disappear.

<img width="846" alt="Screen Shot 2021-10-04 at 10 36 56 PM" src="https://user-images.githubusercontent.com/605533/135951580-6bd34577-1e2d-462f-b280-327c7bd8c248.png">

### Reproducing

Open the preferences.

### Zettlr Version

Beta (if applicable)

### Specify version

beta.5

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

11.2.3

**Comment by nathanlesage** [comment]
The preferences scrollbars have fortunately been fixed in the meantime. The reason why I abandoned the two-column layout: First, most preference windows actually feature a single-column layout, and since I want Zettlr 2.0 to look native, I had to roll with that. Secondly, the column algorithm basically first renders everything in a single column and then just splits that single column into two halves and moves the bottom half to the right. This unfortunately also splits input elements (checkboxes, text, radio buttons etc.) in half and I can't work around that.

I have to adapt the default size of the preferences window to be more narrow as well, but you can manually resize it. I felt that if you resize it so that the tabbar fills out almost the full window width, it looks quite nice.

Oh, and the text looks smaller because I finally made all text _one_ size. Previously, the labels were a little bit bigger and that didn't look nice.
