### ISSUE TITLE
[Bug] Four spaces triggers a code block, impacting Hierarchical Lists

### ISSUE THREAD

**Issue by jeffgeorge** [Zettlr/Zettlr#2637]
### Description

When you start a line with four spaces it triggers the start of a code block.

Ex:
```
This is normal text
 This is still normal text
    This line is a code block
```

This is unexpected behavior, and would be ok on its own, but it impacts hierarchical lists which get prefixed with four spaces for each tier:

```
- This is a list item
    - This is a list item after I hit tab
```

In Zettlr pre-2.0 this behavior was not present.

### Reproducing

- Start a line with four spaces.
- Observe that you are now in a code block

Alternatively:
- Start a list (- or *)
- Press Tab to indent one tier
- Observe that you are now in a code block

### Zettlr Version

Stable (most recent version)

### Specify version

2.0.0

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Big Sur 11.6

**Comment by nathanlesage** [comment]
CC @Redsandro

**Comment by Redsandro** [comment]
@nathanlesage shoot. The issue sucks because any fix I write only works for contents on screen. Everything that you scroll to later still breaks because CodeMirror does some clever trickery for buffer purposes but our hook works on the buffer and CM's internal markdown mode works on the entire thing. I need to know how they do that and write any future fixes there.

For the time being it's best to disable the indented code block formatting since hardly anyone uses it, but those indented lists are important. Please merge hotfix https://github.com/Zettlr/Zettlr/pull/2641

My apologies. I was afraid I missed something in testing. :cry:
