### ISSUE TITLE
[Feature] Double spaces or backslash at the end of a line when pressing enter to insert a newline.

### ISSUE THREAD

**Issue by aljohnston112** [Zettlr/Zettlr#2647]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [X] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

I have learned that newlines in Zettlr do not accurately reflect newlines in markdown. I was wondering if it is possible to add a feature to turn enter presses into markdown newlines. 

### Example Workflow

The user presses enter. The program inserts a double space or a \ to indicate a newline in markdown. It could be a setting that can be turned on or off. 

### Caveats

I am not aware of any caveats.

### Do you wish to attempt implementing this yourself?

Yes

### Platforms

- [X] Windows
- [X] macOS
- [X] Linux

**Comment by Joelius300** [comment]
Bumping this issue because I'd also love to see a setting for that. Currently if I had to pull up a file quickly without having Zettlr installed (could also be on my phone for example) and I'm displaying it using some other markdown renderer like the one built into GitHub, newlines aren't displayed as I intended when I wrote them in Zettlr (unless I manually add the two spaces).

I'm not sure what the best approach is to fix this without causing annoyances. One idea could be adding a setting that if enabled inserts two spaces when pressing enter (or shift-enter as you said) and removing them if enter is pressed again, since it's only needed when there's not a newline directly below.

### In Zettler it may look like this:

This is a line.
This is another line for some reason.

This is a new paragraph.

### While on GitHub it looks like this:

This is a line. This is another line for some reason.

This is a new paragraph.

**Comment by nathanlesage** [comment]
> Currently if I had to pull up a file quickly without having Zettlr installed (could also be on my phone for example) and I'm displaying it using some other markdown renderer like the one built into GitHub, newlines aren't displayed as I intended when I wrote them in Zettlr (unless I manually add the two spaces).

Yeah, the main problem is that most Markdown editors show you a preview instead of the Markdown source. I think the main problem is that this issue might be difficult to implement (because of a lot of edge cases - you don't want to insert spaces or something if you're pressing enter in a list item, for example).

And furthermore I think we should use backslashes if we indeed are to implement such an option instead of two spaces since then it's easier to see in case something isn't as it's supposed to be.

**Comment by Joelius300** [comment]
Bump
