### ISSUE TITLE
Error on Debian Buster

### ISSUE THREAD

**Issue by meaz** [Zettlr/Zettlr#266]
I wanted to test Zettlr today.
I've donwloaded the .deb but here is the error I have with
`dpkg -i Zettlr-linux-x64-1.3.0.deb`

```
Sélection du paquet zettlr précédemment désélectionné.
(Lecture de la base de données... 461609 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de Zettlr-linux-x64-1.3.0.deb ...
Dépaquetage de zettlr (1.3.0) ...
Paramétrage de zettlr (1.3.0) ...
Traitement des actions différées (« triggers ») pour hicolor-icon-theme (0.17-2) ...
Traitement des actions différées (« triggers ») pour desktop-file-utils (0.23-4) ...
Traitement des actions différées (« triggers ») pour gnome-menus (3.31.4-3) ...
/var/lib/dpkg/info/gnome-menus.postinst: 4: /var/lib/dpkg/info/gnome-menus.postinst: gnome-menus-blacklist: not found
dpkg: erreur de traitement du paquet gnome-menus (--install) :
 installed gnome-menus package post-installation script subprocess returned error exit status 127
Traitement des actions différées (« triggers ») pour mime-support (3.62) ...
Des erreurs ont été rencontrées pendant l'exécution :
 gnome-menus```

I'm on Debian Buster.

**Comment by nathanlesage** [comment]
I'm not sure but it's certainly a bug related to Debian and/or the Electron framework itself. I've found a [mailing list entry](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=922472), where a possible workaround is described -- would you mind giving it a try?

> As a workaround, I deleted my gnome-menus package, installed the Discord .deb
and then reinstalled gnome-menus (which is required by menulibre, otherwise I'd
just leave it uninstalled). Through this workaround, every step worked normally
without any errors or warnings.

(As the user mentions "Discord", which is also an Electron app, I conclude that this might very well apply in your case as well).

**Comment by meaz** [comment]
I've just tested the beta version and it works perfectly.

I didn't try to remove gnome-menus because it also removes gnome gnome-core task-gnome-desktop and I didn't want to mess everything up.

**Comment by nathanlesage** [comment]
Ah, so the beta works again? That's good to hear, seems like a small bug in either electron-builder or the framework itself that got remedied with a newer version :)

In case anything happens again just let me know so I can re-open this issue if necessary!
