### ISSUE TITLE
[Bug] Too little display space with too many tabs

### ISSUE THREAD

**Issue by Libralop** [Zettlr/Zettlr#2670]
### Description

When I open a certain number of slips, Zettlr moves the ones I opened first so that I can no longer access them. They are then located "behind" the file manager bar or are pushed over the left edge of the window.

Expected behaviour: Automatically reduce the size of the tabs so that all of them remain visible and usable. Alternative: A small button with which you can switch through the tabs. (Similar to the corresponding buttons in Firefox or Chrome.)

### Reproducing

- Display resolution: 1920x1080
- Window maximized
- Open more than 6 or 7 slips
- The first slips are not reachable with mouse

https://user-images.githubusercontent.com/28398802/137884167-7ae3300c-ef2a-41c7-9ceb-5ad7ffcb3ac2.mp4

### Zettlr Version

Stable (most recent version)

### Specify version

2.0.0

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 20.04

**Comment by nathanlesage** [comment]
If you have a mouse with a horizontal scrollwheel or a trackpad, you can swipe through the tabs sideways. But yes, a button to just select a tab from a dropdown is also on the bucket list.

**Comment by jchalifour** [comment]
I'd like to add to this issue a little bit. I'm currently using v2.2.4 on up-to-date Manjaro Linux with Gnome. I tried using the shift+scrollwheel and that does indeed work, so that's good to know about. However, I don't always have that ability (don't always have my mouse, err trackball, with the scrollwheel), which means this technique might not be possible all the time. 

It would be great if there was something like arrow buttons on the row of tabs (similar to Firefox) or a dropdown window that would reveal other tabs that aren't visible. This would also be useful as an indicator that there are other tabs open since that is not necessarily obvious when they're hidden off the screen. 

I'm attaching a screenshot to show a problem that I encountered with too many tabs. It's similar to the video already in this issue but shows another aspect. Thanks.

![zettlr-tabs-screenshot](https://user-images.githubusercontent.com/5346551/164083981-3c41aa4c-8433-44af-ae68-9d674058b2ce.png)
