### ISSUE TITLE
[Enhancement] Button for New File (as was in former releases)

### ISSUE THREAD

**Issue by AIBN60** [Zettlr/Zettlr#2685]
### Description

Ctrl N or several clicks will lead to a new file. Former releases had a button to create a new file. Would like to see this again. Button == Ctrl-N

### Proposed Changes

Adding Button with Ctrl-N as function

### Caveats

-

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Operating System Version

Linux 5.4.0-89-generic #100~18.04.1-Ubuntu SMP Wed Sep 29 10:59:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Additional Information

-

**Comment by efficacy** [comment]
As it stands in 2.0.1 the behaviour of the "New File" menu option and the Ctrl-N action are subtly different. 
- The menu item respects the context of the click, and creates a new file in the currently selected folder, immediately prompting for a name inline in the file manager. It is clear at all stages where the file will be created and what its name will be.
- The Ctrl-N action creates a "floating" file which does not really have a name or location until it is saved, at which point you have to deal with the system file chooser panel. This can be useful for strange situations such as creating a file outside the usual workspace, but adds needless extra complexity for regular use.

The old "New File" button behaved more like the right-click menu action, and this is what I would like to see reinstated.

**Comment by AIBN60** [comment]
Funny, but both ways to create a file show exactly the same beahviour as you described it for the menu item. Nevertheless, there is one point that is slightly different from your description:

> The menu item respects the context of the click, and creates a new file in the currently selected folder, 
Yes!

> immediately prompting for a name inline in the file manager. 
No! (nor anywhere else)

Ctrl-N does exactly the same as the Menu item, which surprises me: I thought I experienced a different behaviour earlier. Maybe it was before 2.0.1

**Comment by efficacy** [comment]
> > The menu item respects the context of the click, and creates a new file in the currently selected folder,
> Yes!
> > immediately prompting for a name inline in the file manager.
> No! (nor anywhere else)
> Ctrl-N does exactly the same as the Menu item, which surprises me: I thought I experienced a different behaviour earlier. Maybe it was before 2.0.1

I am using 2.0.1 and I still see the difference. This may be a settings thing. Do you have the "do not prompt" checkbox set in the advanced settings?
![image](https://user-images.githubusercontent.com/51254/139533792-c04621c8-9b4c-472d-ac4a-3ef6a1bbecc2.png)

I have unchecked that box because I always want to set a filename when I create a new file, but it does not seem to affect the Ctrl-N action :(

It may also be a platform-dependent thing. I am using Windows at the moment.

**Comment by AIBN60** [comment]
(facepalm) You are totally right! It is checked. Sorry :-(

But when checked, **both** ways lead in the same way to a new file. This time creating a floating file as you described it earlier.

**Comment by nathanlesage** [comment]
Yeah the behavior is a weird mixture of a default "always save files where you want them" and the more subtle "just create files without bothering me where".

The main problem is that both workflows are kind of important. For example, I frequently tend to see the need to create floating files just to paste stuff in, and then remove them afterwards, and then I also want to create files in specific directories. I guess, for me what prompted me to implement the behavior as it was is that the "create a file inside the currently selected directory" felt kind of "uncontrollable" (because you'd have to remember which dir is selected at the moment of file creation).

I'm definitely open for ideas of how to implement both workflows within Zettlr and make good and sound choices as to which options we would need to enable people to switch for them. But I guess that's kind of a longer discussion that we might want to lead on Discord, right? What do you think?

**Comment by pvjeetze** [comment]
Many congrats for rolling out Zettlr 2.x.x, it has definitely turned out quite neat! The "new file" issue, however, has also immediately received my attention as it does impact the workflow quite a lot. 

I would definitely also support the reintroduction of the "create new file" button just above the file list. With regard to the two options, this is my take: 
- In general I care about, where the files are stored, but for the major part of the cases this is actually the directory with the currently opened file list, so I don't want to be forced to specify it further (and being immediately able to type the file name, without any extra windows, came also quite handy). This could be the standard option for the "new file button" and Ctrl+N, as has been the case in earlier versions.
- The second option to me would be rather a cool additional feature that could be used by pressing e.g. Crtl+Shift+N or by right clicking at the top of file list or under File -> New File -> "Draft [?] Markdown" - something of that sort..

This only from my side, I'm sure that you'll find a neat solution there too!

**Comment by nathanlesage** [comment]
This button has been brought back in 2.3 thanks to the efforts of the Australian students!
