### ISSUE TITLE
Error generating PDF: "A JavaScript error occurred in the main process"

### ISSUE THREAD

**Issue by xxbc** [Zettlr/Zettlr#27]
## Error on generating PDF

`
Uncaught Exception:
Export failed: An error occurred on export: Error: Command failed: pandoc "/var/folders/sj/mnk7m9s114sc__bh8ykbjxb80000gq/T/export.tmp" -f markdown --template="/var/folders/sj/mnk7m9s114sc__bh8ykbjxb80000gq/T/template.latex"   --pdf-engine=xelatex -o "/var/folders/sj/mnk7m9s114sc__bh8ykbjxb80000gq/T/living-brands.pdf"
Error producing PDF.
! LaTeX Error: File shading.sty not found.
Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)
Enter file name: 
! Emergency stop.
<read *>    
l.14 ^^M
`

## It should generate a PDF for me

Error above

## Platform
 - OS: Mac OS 
 - OS Version: 10.13.6
 - Zettlr Version 0.18.1

## I had upgraded to 0.18.1 and had this happen. I then uninstalled completely and reinstalled fresh, same problem.

**Comment by nathanlesage** [comment]
Hey xxbc,

this error is a pandoc/LaTeX-issue. I've also encountered it when I tried to export a file. This is generated when you try to export code blocks, because pandoc then requires the file `shading.sty`, which seems to be optional in all `LaTeX`-installations and it seems that one needs to download it manually. I've tried to pin down the issue but haven't been successful until now. But I may have found something.

In [this issue](https://stackoverflow.com/questions/34180355/pandoc-syntax-highlighting-in-pdf-not-working) someone points to the `--listings`-flag for pandoc. Let me try this out and get back to you soon.

**Comment by xxbc** [comment]
@nathanlesage thanks for the links, I have pandoc and latex both installed and up to date but I'll check out the thread and see if adding anything additional helps resolve it.

**Comment by nathanlesage** [comment]
Thanks for the notice, I'll give the `--listings`-option a try. I believe it's pretty easy to solve, but the behaviour of pandoc is somewhat opaque concerning PDF generation…

**Comment by nathanlesage** [comment]
@xxbc The current development branch should successfully export code blocks now. There simply was a command missing in the template provided by Zettlr.
