### ISSUE TITLE
Export Project Does not Automatically Open File After 2.0

### ISSUE THREAD

**Issue by jpmessina** [Zettlr/Zettlr#2704]
### Description

None of my project files automatically open in my PDF reader upon export any longer. This is a new issue following the recent updates. When I use my finder to access the file, it shows a creation date of when I exported. (Mac OS 11.4). I have tried restarting and installing the more recent update.

### Reproducing

Create a project; right click the project name to export the entire project.

### Zettlr Version

Stable (most recent version)

### Specify version

2.0.1

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

11.4

**Comment by nathanlesage** [comment]
Cannot find a bug: When the project export is finished, there will be a notification popping up to open the project directory. Automatically opening exports are no longer a good option since we now have the ability to export into more than 10 formats at once, and nobody can want to have all of them open in various apps.

It could be that you have withdrawn Zettlr the ability to show notifications, which is why you might overlook that notification.
