### ISSUE TITLE
Autoformat https links does not always work

### ISSUE THREAD

**Issue by passar** [Zettlr/Zettlr#271]
## Description
Writing a https link does not format it into a link as a http does.
Ctrl-k a https link does paste link but same result, no link is made.

## Reproducing
Write a https `[https link](https://whatever.something.now).`
Compare it with writing a http link `[http something](http://whatever.something.now).`

You have to write the []() or use the C-k. You can paste a http link into the () and zettlr will not render a link.
Pasting the above lines sometimes gave me a sucsessfull result of rendering the https adress as a link.

## Expected behaviour
https links should behave the same as http links.

**Screenshots**
![2019-07-15](https://user-images.githubusercontent.com/547543/61207376-41a45d80-a6f5-11e9-9526-0fa269666bc8.png)

## Platform
Windows
 - OS Version [e.g. 11]
10
 - Zettlr Version [e.g. 0.15]
1.3.0

**Comment by nathanlesage** [comment]
Ah, I think I know what you mean. If you have a link in the Clipboard, and then press `Ctrl+K`, it will take the link as the target and position the cursor inside the square brackets so that you can enter a description. But as the link itself is not yet complete, the algorithm will detect the http(s)-link and render it before you finished writing your description. To render the full link, you have to click into the link to remove the rendered version, and then move outside again so that the full link is being rendered.

However, you're on to something. The [CommonMark specs](https://spec.commonmark.org/0.29/#links) are rather clear on Markdown links, and the rendering engine itself will need some overhaul, so I'll get to it!

**Comment by nathanlesage** [comment]
I believe this issue is long fixed, so I'm closing this
