### ISSUE TITLE
[Bug] On entering new line document scrolls randomly.

### ISSUE THREAD

**Issue by drmdshahid** [Zettlr/Zettlr#2725]
### Description

# Bug:
On pressing enter key (creating new line) the page automatically scrolls randomly up or down, sometime even throwing the line being edited out of view.
It is understood that on moving cursor to extremes of top or bottom adjusts the scroll to bring few lines above or below in view. 

# Expected behavior:
On creating new line, the line being edited should not scroll (stay anchored) unless next line is at the bottom of screen.

### Reproducing

1. scroll a markdown document little up or down
2. move the cursor to any line (end or middle) using mouse (mostly) or keyboard arrows
3. hit 'enter' (new line)

It results in unintended scrolling of the document.

this screen capture clip exemplifies:

![214](https://user-images.githubusercontent.com/7584004/138861984-58dd1f1c-5318-4583-a9ed-135ddb4465c5.gif)

### Zettlr Version

Stable (most recent version)

### Specify version

2.0.1

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
Just spent about an hour doing a runtime analysis, and I think I found the culprit. I could fix the issue by completely disabling the codeblock line-class hook, since somehow it triggered a re-render of the whole editor contents after CodeMirror has already recalculated everything.

Specifically, I could reproduce this with this section (placing the cursor at the indicated position and then hitting enter) — after inserting a newline the contents jumped.

![image](https://user-images.githubusercontent.com/17251683/139561145-3a4c4933-e721-40e5-a83f-c3aedc23c1f0.png)

After completely deactivating the codeblock classes hook, this behavior ceased. I'm not quite sure what happens, but I am pretty sure it's due to the usage of the `debounce` handler in there. Not because that would be bad code, but I think CodeMirror 5 is extremely built with sequential processing in mind, that is: Either you do EVERYTHING in one go BEFORE CodeMirror finishes, OR it will cause jumps. I'm remembering my first attempts with CodeMirror where there was jumping all around.

I'll see if I find some way to stop that behavior, but in any case, CC'ing @Redsandro here since you might be interested in this. (Sorry, btw that we have so much fuzz with your PR, I hope that doesn't scare you, it's def not your fault!)

**Comment by nathanlesage** [comment]
@Redsandro Found the culprit, was one `cm.refresh()` too much!

CodeMirror 5 do be black magic at times …

**Comment by drmdshahid** [comment]
Thank you.

**Comment by Redsandro** [comment]
> @Redsandro Found the culprit, was one `cm.refresh()` too much!

Omg that's a good catch! 

> Sorry, btw that we have so much fuzz with your PR, I hope that doesn't scare you, it's def not your fault!

Well, it's kiiinda my fault :sweat: I could have left it alone. :sweat_smile: 

I was contemplating just rolling back everything I did because all I wanted to do was make the blocks prettier and better style-able (and fix the broken indented code), and it has had more unforeseen consequences than I had anticipated. I'm not even sure if that's the end of it. The PR has definitely been more costly (in terms of time) to both of us than I had anticipated. I was planning to use the time spent on this issue alone on three issues I raised, and I assumed this would be the easy one. :clown_face: 

Theoretically, if possible, maybe not or maybe in CM6, code blocks should be their own instances of CM. This will instantly make block-level styling and other nifty preference-based features (like line numbers in code snippets) possible. It would have other draw-backs though, like not (easily) being able to make and copy a selection that includes not exclusively code blocks.

I apologize for the extra issues caused. I believe the rounded corners in code blocks do add that subtle premium look, and I hope that some people upgrade to 2.x late and get that slight happy feeling without the frustration of early bugs.

**Comment by nathanlesage** [comment]
> I was contemplating just rolling back everything I did because all I wanted to do was make the blocks prettier and better style-able (and fix the broken indented code), and it has had more unforeseen consequences than I had anticipated.

Nooooo! If I had done this, Zettlr would not be there – we all live for the horrors of bugs! :D 

> Theoretically, if possible, maybe not or maybe in CM6, code blocks should be their own instances of CM.

That's a very nice idea, and we should definitely keep that on our radar. But as you mentioned: Now that we can finally leverage CM5 correctly, we shouldn't abandon ship (especially since CodeMirror 6 is not even stable).

> I apologize for the extra issues caused.

No need to apologize! If you hadn't introduced these issues, I would have, so it's totally not your fault. But I guess now you're initiated to Zettlr and finally part of the team, so welcome again! ;)
