### ISSUE TITLE
[BUG] Image from URL is not preview rendered.

### ISSUE THREAD

**Issue by SebastianGrans** [Zettlr/Zettlr#274]
## Description
Some images that are not rendered in the editor when inserted as a URL. 

## Reproducing
Make a document with the following code. The top inline image does not render a preview image, the latter one does. 
```
![](https://se.mathworks.com/help/examples/vision/win64/EvaluatingCameraCalibrationExample_03.png) 

![](https://images.sftcdn.net/images/t_app-cover-l,f_auto/p/ce2ece60-9b32-11e6-95ab-00163ed833e7/260663710/the-test-fun-for-friends-screenshot.jpg)
```

(If the image from mathworks.com is downloaded and inserted as a local file, it is rendered) 

## Expected behaviour
Both should be rendered. 

**Screenshots**
![](https://i.ibb.co/xX76xN1/Screenshot-2019-07-18-at-14-02-48.png)

## Platform
 - OS: Mac OS Mojave 
 - OS Version: 10.14.5 
 - Zettlr Version: 1.3.0 and 1.4.0

**Comment by nathanlesage** [comment]
This is because there was a trailing space at the end of the image, currently, the image previewing engine requires you to begin the line directly with the exclamation mark and end it with the closing brace. I'll fix this, allowing for additional characters on the same line; which is what I wanted to do either way, but always forgot. So thanks for the reminder!

**Comment by nathanlesage** [comment]
P.S.: This means inserting the image URL into a freshly generated image tag will work!

**Comment by SebastianGrans** [comment]
I didn't even realize. Thanks!

Thanks for this awesome app. Keep it up! :)

**Comment by nathanlesage** [comment]
Done!
