### ISSUE TITLE
[Bug] Ctrl+ and Ctrl- to zoom in and out don't work with the + and - keys on the numeric pad

### ISSUE THREAD

**Issue by efficacy** [Zettlr/Zettlr#2740]
### Description

This is a bug I have seen occasionally in other software too. The Ctrl+ and Ctrl- key sequences need to work with the + and - keys on the numeric keypad as well as the ones on the main section of the keyboard. For those of us with a standard keyboard the + and - keys on the numeric keypad are much easier to use, as the + does not need to be shifted.

### Reproducing

1. Try to zoom using Ctrl and the + or - keys on the numeric keypad
2. Observe that nothing happens
3. Compare with using Ctrl and the + or - keys on the main section of the keyboard which zooms the interface.

### Zettlr Version

Stable (most recent version)

### Specify version

2.0.1

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
I'm not sure this will work, since the numpad "+" has a different character code than the regular "+" char. And we cannot assign multiple accelerators to menu items.

In general, I think we can only work around this using a completely custom approach that circumvents Electron's accelerator system as a whole or we need to ask them to allow multiple accelerators. However, there seems to be this snippet:

> Shortcuts are registered with the globalShortcut module using the register method, i.e.

So maybe we can add alias shortcuts using that method. But we need another service provider for that, and I'd like to also address the keyboard locale issues (i.e. that ANSI keyboards don't like `Cmd/Ctrl+!` to toggle the file manager) at the same time.

**Closing this issue in favor of a broader one addressing several of these issues**

***

cf.: https://www.electronjs.org/docs/latest/api/accelerator
