### ISSUE TITLE
[Bug] Empty space in front of the header

### ISSUE THREAD

**Issue by develop987** [Zettlr/Zettlr#2743]
### Description

I have an empty area in front of the text of the note.
When I create a new note, the same thing happens.
I do not know which version of the program I use.
![31 10 2021_11-03-12](https://user-images.githubusercontent.com/90496895/139573944-2f4173ec-cdeb-437e-9521-1e44baaabf79.png)
![31 10 2021_11-05-17](https://user-images.githubusercontent.com/90496895/139573942-61c2d1ab-6506-4cb2-ad78-cc6f4eae8b84.png)
![31 10 2021_11-07-32](https://user-images.githubusercontent.com/90496895/139573974-c499418f-71e4-40dd-96d5-140984df8571.png)

### Reproducing

I do not know how it happened.

### Zettlr Version

Stable (most recent version)

### Specify version

1.8.9

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
You have the Typewriter mode active, that's why. Just noticed that this is not documented. You can toggle the mode by pressing `Cmd/Ctrl+Alt+T`. We'll fix the documentation.

And wrt the Zettlr version: Before you open the next issue, please look that up. It's in the About dialog (Help menu). You seem to use 1.8.9 which is not supported anymore.
