### ISSUE TITLE
The template used in 1.8.x doesn't work on 2.0.x

### ISSUE THREAD

**Issue by Creling** [Zettlr/Zettlr#2747]
Hello:

I use the [legacy template](https://github.com/Zettlr/Zettlr/blob/zettlr-1.x-legacy/source/main/assets/export.tex) to export pdf files. However, Zettlr shows the following error messages:
```
Error producing PDF.
! Missing number, treated as zero.
<to be read again>
}
l.192 \end{document}
```

![image](https://user-images.githubusercontent.com/43109504/139591028-8a88a2e5-8e33-40b6-8523-5eb775424b14.png)

This is the metadata field of my md file:
```
---
MAIN_FONT: "STSong"
SANS_FONT: "Times New Roman"
---
```

To clarify, I do not modify the template except for commenting out line 76 since Zettlr 2.0.x will not pass `$TOP_MARGIN` and other parameters by default.

```latex
\geometry{verbose,$PAPER_TYPE$,tmargin=$TOP_MARGIN$,bmargin=$BOTTOM_MARGIN$,lmargin=$LEFT_MARGIN$,rmargin=$RIGHT_MARGIN$}
```
And, I use the `internal pandoc` for exports.

**Comment by nathanlesage** [comment]
Those variables are no longer present; Zettlr now uses the Pandoc default template, so these variables will not be replaced. Furthermore, a problem is that the Pandoc templating engine needs to have variables surrounded by dollar signs, a single leading one is not sufficient.

Luckily, the Zettlr legacy template is more or less the default Pandoc template, so you can easily switch and instead of using the PDF preferences dialog use the defaults variables. I've got something for you here: https://docs.zettlr.com/en/core/assets-manager/#how-to-adapt-the-pdf-preferences
