### ISSUE TITLE
[BUG] Markdown syntax is highlighted inside math mode

### ISSUE THREAD

**Issue by SebastianGrans** [Zettlr/Zettlr#276]
## Description
When writing equations in math mode ($$), syntax that is Markdown specific is highlighted and formated. 

This is a minor bug as it doesn't impare the use of the program. The LaTeX rendering is completely unaffected.

## Reproducing
Write the following in a document
```
$$
F_x = 2.4619*6.17
$$
```
and  everything after the asterisk (*) is syntax highlighted and slanted, as it is interpreted to be in italics. See screenshot
![](https://i.ibb.co/MZvHGcx/Screenshot-2019-07-19-at-14-37-44.png)

## Expected behaviour
Anything in mathmode should be unaffected by Markdown syntax.

## Platform
 - OS: Mac OS Mojave
 - OS Version: 10.14.5
 - Zettlr Version: 1.3.0

**Comment by nathanlesage** [comment]
It's due to the underlying Markdown mode; I can't alter that behaviour without bearing upon myself the work of always keeping the MD-Mode in sync with the official one on the CodeMirror-repo. Additionally, due to the fact how the Multiplex-Mode works I can't currently add another one to detect such LaTeX-blocks :/

**Comment by nathanlesage** [comment]
Just tested it out and have to confirm that I can't alter that at the moment. However, Markdown syntax highlighting should not be the worst problem for now!
