### ISSUE TITLE
Automatically closing disables »

### ISSUE THREAD

**Issue by thob** [Zettlr/Zettlr#277]
If on `»` (Alt Gr+y) is turned into `«»` instead of `»«`. If off `»` works. Not sure if this is expected behaviour.
Happens on Linux Mint 18.3

**Comment by nathanlesage** [comment]
Oh I see, thanks for notifying me! I'll get to it!

**Comment by thob** [comment]
I think it still doesn't work 1.4.0-beta 1

**Comment by nathanlesage** [comment]
I know, I forgot to mention that I already found the problem, but it requires some thinking on my part, as the French guillemets are incompatible with the German/English ones. If I remove the French ones, the German/English ones work again. I need a workaround.

**Comment by thob** [comment]
Just found out [Guillemet](https://en.wikipedia.org/wiki/Guillemet) can get even more complex w/ Finnish or Swedish ones. They go like `»Hi!»`

**Comment by nathanlesage** [comment]
@thob Oh well … But thanks a lot for researching, this prevents me from having to reopen that issue again and find a fix that works for all languages!

I'm currently thinking that maybe we should move this issue towards the auto-correct issue (#126) because while we could add options to the autoclose plugin until we're old and grey, and still we won't get everything perfectly working due to these language ambiguities.

So my suggestion is now the following:

When starting to add autocorrect-options, I'll begin by the standard ones that we know from LibreOffice: How to transcode `"` and `'` into the correct guillemets _or_ quotation marks. This way we can completely remove these from the autoclosing-plugin. I think this is the better way to do this. This way, everyone can choose their own favourite quotation marks, while also being able to simply type `"` or `'`, which is much easier than having to remember the correct keycodes anyway!

Here's a simple mockup for how I think it could be done:

![grafik](https://user-images.githubusercontent.com/17251683/62851573-e1e6a580-bce6-11e9-928a-5c9c40af8ca8.png)

![grafik](https://user-images.githubusercontent.com/17251683/62851585-ef9c2b00-bce6-11e9-9b5b-359debe23c80.png)

Any other ideas? Otherwise I'll close this issue and move it to #126 (including a forum post for gathering of data on all kinds of quotation marks)!

**Comment by nathanlesage** [comment]
Closing this issue as it's being continued in #126.
