### ISSUE TITLE
[Bug] Strange behevior of the program update window 

### ISSUE THREAD

**Issue by JetV** [Zettlr/Zettlr#2775]
### Description

Non-removable white (blank) update dialog window (on the additional picture)

![window](https://user-images.githubusercontent.com/6479885/140522147-9fec8244-f59b-4599-840a-df9745b1697d.JPG)

### Reproducing

When I try to check for a program update, and open" Help -> Check updates", a non-removable white window appears

### Zettlr Version

Stable (most recent version)

### Specify version

2.0.2

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 7

**Comment by nathanlesage** [comment]
Dammit, I knew that something like this might happen!

Would you mind doing the following?

1. Activate "debug" mode in the preferences
2. Open the update window so that it shows you that white void
3. Go to Develop -> Toggle DevTools
4. Inside the devtools (they work exactly like the Chrome DevTools), would you mind screenshotting the console.log? There are certainly errors logged, and they will help fixing this.

**Comment by JetV** [comment]
Yes... seems to work
![err](https://user-images.githubusercontent.com/6479885/140607484-375d52bc-0492-4d9e-9987-402b2184373d.JPG)
