### ISSUE TITLE
[Feature] Disable Update Check

### ISSUE THREAD

**Issue by newhinton** [Zettlr/Zettlr#2818]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [X] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

Disable the Update-check on startup. This is not always necessary, and providing the ability to turn off the check reduces the data-footprint generated by zettlr.

### Example Workflow

Start the app the first time, and let it check.
Go to settings, either general or advanced
unmark "update on startup" checkbox
Restart zettlr, without updatecheck

### Caveats

Disabling this obviously does not provide the most up to date translation

### Do you wish to attempt implementing this yourself?

Yes

### Platforms

- [X] Windows
- [X] macOS
- [X] Linux

**Comment by nathanlesage** [comment]
There have been many discussions about this on the issue tracker, and I have constantly argued against it because many people simply do not update if they are not prompted to do so. This then leads to a lot of issues reported based on outdated versions. Since I have a full-time job, I want to reduce the amount of issues reporting already fixed bugs as much as possible, and this is a very good method of doing so. Recently, the updater didn't work for a few days and the amount of issues reporting bugs that were already fixed has gone up quickly.

With regard to your very valid concern, which I share:

> […] turn off the check reduces the data-footprint generated by zettlr.

Zettlr does not have any data-footprint, since no information is being transmitted. It is a simple API query, so this leaves open the question: what data-footprint do you refer to? I am absolutely in favor of making Zettlr as privacy-respecting as possible, but I do not see how disabling the update ability would help in that regard. Would you mind to elaborate?

**Comment by nathanlesage** [comment]
> You can only get metadata, but i can find out when and how often a user starts the application. Disabling this would prevent such sort of tracking.

Yeah, I see the issue with that. (However, there is *also* a check to update languages, and since the translation service works asynchronously, it could literally break the app if we disable these. So in any case, we would have to think about that as well!)

> A compromise could be to make this an argument that needs to be passed, like '--no-update' or similar, or leaving the config-option in, and the GUI-representation out, so that only people who REALLY want this can opt out.

This is basically the tradeoff, yes. Although now that I'm thinking about that it seems a bit silly to not also add that thing to the settings; maybe I just need to be more rigorous wrt closing issues :D 

I'll have a look at the PR in a few days, I'm currently 120% loaded with work and can't really tend to Zettlr!

**Comment by newhinton** [comment]
Sure! I have already linked update and translation checks with the same setting, and my pihole did not register any checks, but i may have missed a place. The translation service just returns immediately when checks are disabled. Probably not the most elegant way, but i am not really used to electron/typescript applications, so just point me to a better solution when you eventually get to taking a look!

**Comment by nathanlesage** [comment]
> I have already linked update and translation checks with the same setting, and my pihole did not register any checks, but i may have missed a place.

These are the only two places with internet connectivity, so you got them all!

> Probably not the most elegant way, but i am not really used to electron/typescript applications, so just point me to a better solution when you eventually get to taking a look!

Will surely do, but probably not after Christmas :/ Let me pin this thing to make sure.

**Comment by Joelius300** [comment]
As a side-note, I'm using a package manager to install and update Zettlr so the notification doesn't really help me anyway and I'd love to disable it in the settings for example (I'm fine with the update-check being enabled by default). One could always re-enable or watch the GitHub repo for releases instead.
But more importantly than this, I'd like to second #2973 :)
