### ISSUE TITLE
[Maybe Bug] Ctrl-Click on link only sometimes opens a new tab, sometimes not

### ISSUE THREAD

**Issue by AndreGosselink** [Zettlr/Zettlr#2839]
### Description

_Current Behaviour_
Ctrl-Clicking on an internal or absolute link opens the linked file. However, it seems that sometimes a long click opens a new tab for the file. Other times it does not

_Expected Behaviour_
Ctrl-Clicking on an internal or absolute opens the linked file _always_ in a new tab

### Reproducing
- Create two .md files (with default id as filename)
- Create link from one file to other
- Ctrl-Click the link
- File opens in the same tab, sometime in a new tab
- Ctrl-Click with longer click duration
- File opens more often in a new tab

Variation of click timing seems to have an effect, but not consistently. Some sort of racing condition?

### Zettlr Version

Stable (but an older version)

### Specify version

2.0.2

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Manjaro Linux

**Comment by nathanlesage** [comment]
By default, Zettlr tries to avoid new tabs, so new files will be opened in new tabs only if there are modifications to the currently active file. To always enforce new tabs for files, you can uncheck the corresponding setting in the preferences.

The time-lag can be caused by the fact that, by default, autosave is engaged after 5 seconds, so before the auto save, following a link would open a new tab, whereas after the autosave, it would open in the same tab.

Does that solve your issue?

**Comment by AndreGosselink** [comment]
Checked behaviour as described. With unsaved changes, links are opened in a new tab opens. After saving (manual or auto) links are opened in same tab.
Unchecking: _Avoid opening files in new tabs if possible_ results in always using new tabs.

Thanks for clearing my confusion! In an afterthought: maybe this option should be renamed to _Always open files in new tabs_?
