### ISSUE TITLE
[FEATURE] Typewriter mode

### ISSUE THREAD

**Issue by SebastianGrans** [Zettlr/Zettlr#284]
## Description
In 'Typewriter mode', the current line is always centered. Similar to how an old typewriter works.

This mode could be an extension of the distraction free mode.

**Comment by nathanlesage** [comment]
Yup, have this on my mind for about a year, but didn't have the time to implement this so far.

**Comment by ploum** [comment]
I like it.

**Comment by Ellipsine** [comment]
Hi !  I have the same request ! 
I use Zettlr for preparing my novels... And I would like to use it to write my novel because it has every features I need (export, tags, outlining tool...).

However, the cursor stays at the bottom of my page, which is disturbing. I need to keep it at my eyes level to be comfortable to write. It is hard to keep my computer open for hours to work without comfort.

Is it possible to implement an option to keep the crsor at the middle of the page ?

Typora, IA Writer, WriteMonkey or FocusWriter make it too but they don't have the same features than Zettlr which is really a unique piece of software that I would love to use more and more.

**Comment by nathanlesage** [comment]
After almost a year, it's finally coming! (With the next release)
