### ISSUE TITLE
Bibliography in Reveal.js output

### ISSUE THREAD

**Issue by annargrs** [Zettlr/Zettlr#287]
Zettlr is fantastic for being able to combine its regular citation engine with reveal.js output. I haven't seen anything else in reveal.js ecosystem to even try to do that.

The problem is, however, that once the citations are rendered, they are all dumped on one last slide. If there's just one or two citations it's ok, but if there are dozens, it won't be readable. Scrolling does not solve the issue because it cannot be translated to the pdf-printed slides.

The default styling also seems to be that the bibliography section is centered, whereas normally they should be left-aligned or justified.

**Comment by nathanlesage** [comment]
Zettlr offloads as much work as possible to pandoc, because this is a great way to share the work. However, `pandoc-citeproc` obviously stiches together all citations in one place, as it's automated. Citeproc can't certainly know how many citations should be placed on one slide to make it look great. You can, however, control the placement and styling with a small trick [documented in the pandoc documentation](https://pandoc.org/MANUAL.html#citations):

```
::: {#refs}
Your references will be placed here
:::
```

You can also use the following, which is more customisable:

```html
<div id="refs">
<!-- Your references will appear here -->
</div>
```

For more control over your citations, I would probably suggest to manually insert the correct references, and "hide" the generated div by applying something like this:

```html
<div id="refs" style="display: none">
<!-- In HTML output, the style will be applied, rendering everything in here hidden -->
</div>
```

With the `div`-approach, you are also able to use custom styling like such:

```html
<!-- Place a style element somewhere in your Markdown file -->
<style>
#refs {
    text-align: left; /* This will render your citations left-aligned */
    color: yellowgreen; /* Anything works */
}
</style>
```
