### ISSUE TITLE
[Bug] Print button doesn't do anything

### ISSUE THREAD

**Issue by QazCetelic** [Zettlr/Zettlr#2878]
### Description

The print button or `CTRL + P` does nothing.

### Reproducing

1. Open Zettlr
2. Press `CTRL + P`
2. Nothing happens

### Zettlr Version

Stable (most recent version)

### Specify version

2.0.3

### Your Platform

- [x] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

### Additional Information

I've never used Zettlr before, so this _could_ be intended behavior, but I doubt it.

**Comment by Cipher-Coder** [comment]
Can confirm V2.0.3 same behavior on M1 MacBook Pro. Same thing... I had never used this and downloaded for the first time. I was just trying to get a preview and figured I would try to print. Nothing happens. CTRL + P = nothing. File --> Print = nothing. I just assumed it was more software not yet ready for Arm Mac's and I just moved on.

**Comment by nathanlesage** [comment]
> I just assumed it was more software not yet ready for Arm Mac's and I just moved on.

Zettlr works fine on M1 Macs. I cannot reproduce this locally. Would it be possible for both of you to take a look into the logs if there was any error?

By the way, the very first time you run Zettlr it might take longer to open the print window, because we have to wait for Pandoc to finish, that can take some time depending on your computer.

**Comment by Cipher-Coder** [comment]
> Zettlr works fine on M1 Macs. I cannot reproduce this locally. Would it be possible for both of you to take a look into the logs if there was any error?

Yes... Error: Export failed with code 83. How do i get to the logs? Or do you know what this error is without them?

**Comment by nathanlesage** [comment]
Aaaaaaaaah, Pandoc's code 83 means there is an error in the filter. That being said: It's the filter bug I accidentally made for the Zettelkasten link writer. In order to fix this bug until the next patch ships, please make sure to disable any reforming of Zettelkasten links in export in the settings. In the preferences' Export tab, select "Do not touch internal links"

Fix will come soon!
