### ISSUE TITLE
wrong placement of head scripts in reveal.js output

### ISSUE THREAD

**Issue by annargrs** [Zettlr/Zettlr#288]
## Reproducing

Try to generate the reveal.js output from the following markdown:

```markdown
<script>
let i;    
</script>

# Slide 1

some text
***
```

The generated output is as follows:

```html
<body>
	<div class="reveal">
		<div class="slides">
      <section class="slide level1">

<script>
let i;    
</script>
</section>
<section id="slide-1" class="slide level1">
<h1>Slide 1</h1>
<p>some text</p>
</section>

		</div>
	</div>
```

This creates an extra first slide and places the script inside it. So instead of a single-slide presentation there are two slides, with the first one being empty. 

## Expected behaviour

```html
<body>
	<div class="reveal">
		<div class="slides">
<section id="slide-1" class="slide level1">
<h1>Slide 1</h1>
<p>some text</p>
</section>

		</div>
	</div>
```

With the `<script>` placed in the header instead of the presentation body.

## Platform
 - OS: Ubuntu 18.04
 - Zettlr Version 1.4.0 (beta)

**Comment by nathanlesage** [comment]
Well, we're in Pandoc's realm here, so what it does is take the script, parse it into its internal AST and then spit out the (in this case revealjs) export output. The revealJS-writer will look for anything that seems to make up a slide-demarcation, that is, Markdown-horizontal-rulers (`***` on a single line, or `---`) and headings of the first order. As in the example you have given, the script is above the first heading level 1, the revealJS writer will detect that (because it doesn't differentiate between tags that will be displayed by the browser, e.g. `<p>`, and such that won't be, e.g. `<style>`. 

I can't tap into the revealJS-writer, but here's how you can easily solve that problem without losing any readability:

## Option 1: Add the script to the very bottom of your presentation

```markdown
Here's **a lot** of markdown text that's on your slides.

***

### Here's another slide

And some text on it

# This heading marks the beginning of another slide

Again, some text.

<script>
  /* This is the bottom, so here the script won't cause another slide to be created */
</script>
```

## Option 2: Add the script to your cover slide

Each Markdown presentation normally has a cover slide that only contains some meta information such as the author's name, the presentation title, date and location. So you won't need to edit this a lot, so the other option looks like this:

```markdown
# My presentation title

My name | 10.08.2019 | Europe

<script>
/* Add any code here */

# This heading 1 will begin a new slide

<!-- Alternative: Use a *** or --- divider instead of a heading 1 -->
</script>

# Here's the next slide, probably with contents

1. One
2. Two
3. Three
```

## The example, converted:

```markdown
# Slide 1

some text

<script>
let i;    
</script>
***
```

**Comment by nathanlesage** [comment]
But what I could offer is a better integration with some of the Pandoc vars in the template so that you could make use of more variables — but I have to test it!
