### ISSUE TITLE
[Bug] Start from Tray behaves weird if application is started from Launcher not from autostart

### ISSUE THREAD

**Issue by newhinton** [Zettlr/Zettlr#2936]
### Description

If Zettlr's 'start from tray' setting is enabled, the application always starts in tray, minimized. This reduces startup time when the application is opened by cli, launcher icon, autostart shortcut or via tray. 

However: If the setting is set, and the application is opened by the user manually (Possible reasons: Crash of Zettlr, intentional quitting the app), this setting is also active. This results in the application beeing mimimized (as expected), but since the user wants to open the app, it should not be minimized.

### Reproducing

1. Set system.startInTray to True
(Start via Startup (Actually, it is enough to start the application once, it does not really matter if it is started by the autostart process since it is the same behaviour anyway))
2. Start system. Zettlr starts, but only in tray.
3. Quickly reopens if started again or is shown via tray
4. Quit Zettlr, make sure no processes are running
5. Launch Zettlr again. 
6. Zettlr opens again, but only in tray. This is the unexpected behaviour, as a user may expect it to immediately start maximized

### Zettlr Version

Right off the develop branch

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Kubuntu 20.04

### Additional Information

This may be fixed by changing the behaviour of system.startInTray again. 
Maybe instead of starting minimized, we need to create an autostart entry if that setting is true, with a startup flag. 

This way, the startup entry starts the application minimized, but normal launchers open up as usual

**Comment by nathanlesage** [comment]
So to cut your story short, what you want is an option to start the app _on login_ minimized, and never else? Basically a setting "Start the app on system boot, but minimized", and whenever you start it manually, you just want the window to open?

Why didn't you say so earlier? This would simply necessitate another setting to enable starting automatically. Now we have some boilerplate that still doesn't give you what you need.

I have an idea of what we need. I'll reply in more length tomorrow.

**Comment by nathanlesage** [comment]
So, now, here's how we'll do this:

1. Remove the `--tray` CLI option
2. Remove the obviously counterintuitive new setting we added
2. Add a one that better describes what you want: `--start-minimized` (or launch, I'll think about this)
3. No fiddling around with internal state and stuff. `--start-minimized` will set the tray-setting to true if not already done, and the main application will just look for that one specific CLI flag, and show the window if it's not set, else not
4. Add a desktop file/launch file/autostart item depending on your OS and
5. Profit

**Comment by newhinton** [comment]
That was my initial implementation aswell, though we got sidetracked somehow. (also there is no `--tray`, that got removed in the process)

Can we create autostart/startup entries programatically on all architectures? because if we can do that, we could keep the gui switch, and just check if we should create the startup entry (which then is only the normal executable with the `--start-minimized` flag)
I know this should be rather easy on linux and windows because on those systems it's just a symlink, but i do not know if it is possible on mac.

You told me that cli arguments are rather hard to use on mac, so having it in the ui may be of benefit for users of mac devices

**Comment by nathanlesage** [comment]
> You told me that cli arguments are rather hard to use on mac, so having it in the ui may be of benefit for users of mac devices

Yes, this was a miscommunication: It sounded to me as if you wanted to be able to start it from the CLI sometimes, and that is super hard on macOS.

I think I got confused while we were talking about the necessary settings because it sounded super convoluted.

Please feel free to check out the newest commit (with which I'll be closing this issue) which does what you need: It's basically your initial `tray`-idea but with a (imho) better naming convention, since what you wanted is not to `--tray`, but what you wanted is to `--launch-minimized`. With that wording it makes much more sense and since you won't be typing it all the time we can use a much more expressive flag.

Another step would then be to auto-launch the app. There is a package, but it hasn't been updated in 4 years and so I'm unsure of whether we can use it, or just manually implement everything. On macOS it's — as always — much more convoluted. But since we now have the flag, everyone on every system will be able to manually add the app to autostart. What we can also do for now is to implement the autostart symlinking via a setting in the GUI and just disable that on macOS platforms until we've figured out a way of starting the app there. But I'd argue that's a different issue.
