### ISSUE TITLE
[Bug] 1.4.0beta-1: No spell checking at program startup

### ISSUE THREAD

**Issue by jothanne** [Zettlr/Zettlr#294]
## Description/Reproducing
When starting Zettlr the last used file is opened again but without the red underlinings of misspelled words. Besides this there are no entries in the user defined dictionary shown in the preferences.

You first have to click on the current (or another) filename in the file list to bring back spell checking and show the entries of the user dictionary.

## Platform
 - OS: Windows
 - OS Version: 7 & 10
 - Zettlr Version: 1.4.0beta-1

**Comment by nathanlesage** [comment]
Spell checking, due to the algorithm which is slow and blocks the app long enough for you to notice, and can even crash the app, we need to defer the start up of the spell checking for after the app has launched. As soon as you type anything, the spell checking will re-run your text and indicate correctly what is wrong and what is spelled correctly.

iirc this has already been answered in one issue …? But I'm not sure! I'll add it to the FAQ later on!
