### ISSUE TITLE
Internal link's auto-complete popup won't disappear

### ISSUE THREAD

**Issue by noah-arroyo** [Zettlr/Zettlr#2945]
### Description

Attempting to type an internal link in **Tab 2** while **Tab 1** is delayed-autosaving will cause the link's auto-complete popup to hang, and refuse to disappear. 

### Reproducing

1. In settings, set autosave to: "After a short delay."
2. Open two tabs.
3. In **Tab 1**, modify the file's contents somehow. Delayed autosave will activate.
4. While **Tab 1** is preparing to save, switch to **Tab 2**.
5. In **Tab 2** — and before **Tab 1** autosaves — type double open-brackets `[[` to begin writing an internal link to another note. This will also summon the link's auto-complete popup.
6. Now the popup will not disappear, even if you (a) select a link from the popup, (b) press `Esc`, or (c) wait until Tab 1 has finished saving. 

I think these steps work 95% of the time. Pretty sure I've had one or two instances where they didn't yield the bug, which implies that I don't fully understand what actions cause it.

Exiting Zettlr and restarting it will solve the problem, until you replicate these steps.

### Zettlr Version

Beta (if applicable)

### Specify version

2.1.0

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
Thanks a bunch for the reproduction steps, will have a look :)

**Comment by kyaso** [comment]
I can confirm this issue (running Linux), and I was also able to reproduce it using the steps provided by @noah-arroyo.

Does not happen in 2.0.3.

**Comment by nathanlesage** [comment]
There seems to be some bug within the autocomplete plugin. I just checked this out, and apparently whenever one of the databases is updated the plugin just stops working. Apparently this messes up the state somehow. Have to investigate further, but maybe just hard-restarting the autocomplete may solve the issue for now. (Easier said than done, though)

> Does not happen in 2.0.3.

This, however, is an interesting info, maybe I just introduced a logical error in between. If someone wants to do a `git bisect` to find out which commit exactly started the behavior that would be awesome!

**Comment by kyaso** [comment]
Hey, I just ran a bisect, and it looks like that the upgrade to Vue 3 introduced the regression: 6b4f2b71aef3790d95bf9eb0c41a6bf444d414bf

**Comment by nathanlesage** [comment]
@kyaso Ah perfect, thanks a lot for your work!

The easiest assumption right now would be that the `Proxy` is the issue here. Vue 3 uses proxies instead of the more clumsy reactivity implementation they used in Vue 2 (I think they used observers before …?).

However, proxies are extremely aggressive. For example, I had to completely remove the CodeMirror instances from the Vue component instantiation since the proxies messed with a few internal things within CodeMirror (since basically the full CodeMirror object had been transformed into a giant tree of proxies).

Since the recalculation of the autocomplete dropdown values occurs within the component state, there is a high chance I simply overlooked an avenue that opens up the whole autocomplete plugin to proxification, which could lead to that error.

I'll have a look as to where that problem might first occur, but please also feel free to have a look at the chain of events that happen after an autosave happens, if you find something.

**Comment by nathanlesage** [comment]
Good news: I found that we are indeed sending a proxied database to the autocomplete plugin, however that didn't cause the problem. So the next possibility would be to look for any logical error I made after saving, so maybe we should just spam a few console.logs and hope to stumble upon something.

I currently suspect I might be doing some violent updating to the CodeMirror instance (because the autocomplete plugin is tightly bound to the CodeMirror instance, and maybe if I perform specific actions that messes with the dropdown).

**Comment by nathanlesage** [comment]
Final update from me for today: I have not a single clue why the autocomplete breaks on autosave, but I now know that one reason why you can't simply re-open it is that the internal state of the autocomplete plugin doesn't reset because the 'endCompletion'-event is never fired. Furthermore, I haven't yet found a way to programmatically close the autocomplete hint prior to saving a document which would look ugly, but would still ensure that the autocompletion doesn't break …

**Comment by zh217** [comment]
I have autosave disabled and I also encountered this bug, and much more frequently after upgrading to 2.1.0.

**Comment by nathanlesage** [comment]
Yeah, I guess something went awry. Let's hope we find the cause quickly!

**Comment by noah-arroyo** [comment]
Anything I can do to help figure this out?

Keep in mind that I'm barely a power user — almost no programming skills.

**Comment by zh217** [comment]
I can reproduce this bug with autosave disabled, and without saving anything:

1. Jump from doc A to doc B by following a link;
2. Jump back from doc B to doc A by following a back-link, no editing of doc B is necessary;
3. Type "[[" and choose anything in the dropdown with keyboard;
4. Now the popup will not go away.

In my testing this happens 100% of the times on 2.1.0, and not once on 2.0.3.

**Comment by nathanlesage** [comment]
> Anything I can do to help figure this out?

I don't think so. It seems to have something to do with the Vue 3 migration, so we just have to dig somewhere in the code to see what has changed :/ 

> In my testing this happens 100% of the times on a freshly-opened 2.1.0, and not once on 2.0.3. If "avoiding new tabs" is enabled then following the above steps will not trigger the bug. So the tabs are causing the problem, not the saving.

That's a good thing, thanks for figuring this out! I'll make sure to look at the bad commit again and see what I have changed with regard to how the tabs work.

**Comment by nathanlesage** [comment]
Grrr, I just hooked into the underlying plugin code and, surprise, something has proxied the CodeMirror instance … 🙄 I assumed it was the documents, and indeed, after pulling them out of the Vue component data, the error was gone!

Please report if that should ever return!

**Comment by noah-arroyo** [comment]
Great catch, @zh217 — but I'll do you one better.

I'm now realizing that this bug manifests in v.2.1.0 after you return to a document _by any method._ You can return via an internal link, or through `Tab` / `Ctrl+Tab`, or just clicking on the note.

I.e., open Zettlr on Doc A, immediately navigate to Doc B, then navigate back to Doc A. Then when you type `[[` the link's auto-complete popup will hang.

@nathanlesage it sounds like you've fixed this? Will we be able to test in an upcoming nightly?

**Comment by nathanlesage** [comment]
@noah-arroyo Yes and yes! I think I may even start a nightly build manually today.

**Comment by nathanlesage** [comment]
@noah-arroyo I just scheduled a new nightly build, should be available in a few hours to test.

**Comment by noah-arroyo** [comment]
@nathanlesage I just tried the latest nightly, and indeed the bug appears to be gone. Well done!

**Comment by joep1977** [comment]
How do I install "the latest nightly" or does it update automatically?

**Comment by nathanlesage** [comment]
@joep1977 Visit https://nightly.zettlr.com and simply install the correct version of the app. Otherwise, you can also wait until I push the "official" release which will then be presented to you within the app.

**Comment by joep1977** [comment]
Thank you, very much appreciated!
