### ISSUE TITLE
[Bug] 1.4.0beta-1: Entries in user defined dictionary are not saved

### ISSUE THREAD

**Issue by jothanne** [Zettlr/Zettlr#295]
## Description/Reproducing
Adding words to the user defined dictionary only works for the current session.
After logoff/logon the user at OS level (Windows) or killing the Zettlr backround process in the task manager, no entries besides the default 'Zettlr' are listed in the custom dictionary - neither in the preferences nor in the associated 'user.dic'-file.

## Platform
 - OS: Windows
 - OS Version: 7 & 10
 - Zettlr Version: 1.4.0beta-1

**Comment by nathanlesage** [comment]
Yes, this is right — you may notice a slight lag about a second into application start — this is when the dictionaries are loaded. We can't load them on start, as they will crash the app, if we do, so we have to delay their start to a later point. This is due to the fact that the algorithm we use is still not completely grown, unfortunately. We may change the startup-behaviour to accomodate this, but we can't guarantee anything, as the package is not maintained by us.
