### ISSUE TITLE
v. 2.1.0 often stucks at line break [Bug] 

### ISSUE THREAD

**Issue by ptbeck** [Zettlr/Zettlr#2971]
### Description

(Windows 10 
v. 2..01 beta and final )

Some Zettels work fine, 
others stuck usually after inserting first line or first tag. 

Not possible to insert anything else in these Zettels.
Have to restart. 

Had to go back to 2.03 to continue working

### Reproducing

Difficult. Occurs occasionally, but often. (Every third or fourth new zettel.) n

### Zettlr Version

Stable (most recent version)

### Specify version

2.1.0 

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10 

### Additional Information

-

**Comment by nathanlesage** [comment]
I'm afraid I don't really know what you refer to with "stuck"? Would it be possible to create a ScreenRecording so we can better see what is going wrong there?

**Comment by ptbeck** [comment]
" refer to with "stuck"? "
Cursor hangs at the end of the line. You press {Enter} to go to the next line, but nothing happens. 
Usually it happened at the end of line one. 
In other cases after entering the first tag. (Cursor remained there at the end and could not be moved anymore.)

Instead of this behavior, in version 2.03 everything is fine.

**Comment by nathanlesage** [comment]
Okay, that sounds bad. You mention some files work well, others not? Would you mind sharing the contents of one working and one problematic file?

**Comment by ptbeck** [comment]
Thanks for your answer. 
I  have to reinstall 2.1.0 first. I'll try it tomorrow or the day after tomorrow. 
Happy New Year meanwhile.

**Comment by ptbeck** [comment]
Dear Hendrik,

thank you very much for your reply.

Erlaube mir bitte, in den PMs auf deutsch fortzufahren. Ich glaube verstanden zu haben, dass du in Deutschland studiert hast und wirst damit, im Gegensatz mir mit meinem Englisch kaum Schwierigkeiten hätte. Ansonsten bäte ich dich google translate o.ä. in Anspruch zu nehmen.

Ich habe mal einen typischen Ablauf extemporiert. Entschuldige den etwas unausgegorenen Inhalt. Es ging mir jetzt zuerst darum, möglichst schnell Zettel aus dem Ärmel zu schütteln.

Am besten gehst du sie der Nummerierung nach durch, um nachzuerleben, wann welche Fehler auftraten.

Ich möchte noch einmal betonen, dass an meinem Computer weder mit anderen Programmen noch mit Version 2.0.3 diese Blockaden auftauchen. Merkwürdig für mich nur, dass niemand anderes in den Foren, die von mir gemeldeten Schwierigkeiten bestätigt. Vielleicht liegt es an etwas anderem, Wer weiß?

Lieber Hendrik, ich möchte an dieser Stelle einmal deutlich zum Ausdruck bringen, wie sehr ich erstens rückhaltlos bewundere, was du mit diesem Programm bereits geleistet hast!
Darüber weiß ich sehr zu schätzen, wie engagiert du an diesem Projekt arbeitest und bereit bist, dich mit der Community auseinanderzusetzen. Das finde ich überhaupt nicht selbstverständlich. Ich finde das großartig.

So, die Zettel sind verpackt in einem Zipfile. Und jetzt kommt das große Rätsel: um es zu öffnen, benötigst du den Nachnamen des größten Mitstreiters und Förderers eines bedeutenden deutschen Philosophen. Kleiner Tipp: eines deiner css-Themen ist nach letzterem benannt.

Viel Spaß bei der Lösung und noch einmal:
Happy New Year to you

Peter Becker / Pete Beck

P.S. Ich hoffe, das funktioniert, Sonst sende ich sie dir noch mal anders.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by nathanlesage** [comment]
@ptbeck Vielen Dank! Englisch ist hier die Amtssprache, aber auch nur weil es dadurch relativ zugänglich für alle ist. Wichtig ist ja gerade, den Bug zu fixen, daher geht Deutsch natürlich auch mal!

Nichtsdestotrotz hast du leider via Email kommentiert, was bedeutet, dass Anhänge nicht hier abrufbar sind. Es reicht eigentlich auch eine Datei, anhand derer sich der Fehler reproduzieren lässt, und die kannst du gerne auch einfach hier als reinen Text reinkopieren, dann kann ich mir die schnell einfach rauskopieren und das austesten. Das geht auch schneller als mit einer ZIP-Datei. (Und bitte keine Rätsel, wenn das eigentliche Rätsel ja der Fehler ist ;)

**Comment by gerotakke** [comment]
Hi,
just to chime in, I think I'm experiencing the same thing on macOS Monterey (arm version).
For me, keyboard presses won't trigger any actions anymore. This happened often when inserting precomposed umlauts (so alt-u + u for an ü on the macOS international keyboard layout) or when pressing enter on the last line of the file.
I've also lost a file because of this; Zettlr was in this “keyboard not doing anything” state, I pressed cmd-s to save and restart Zettlr and upon restart, the file was empty.
I've downgraded to 2.0.3 for now but let me know if I should try and create a screen recording.
Cheers & happy new year from me as well!

**Comment by nathanlesage** [comment]
@gerotakke Thanks for your input! This seems weird, since on my machine (literally the same: macOS Monterey on an M1 Mac with US-ANSI keyboard + I need to insert ümlauts often) it works fine.

But I suspect it also has something to do with me messing up the Vue 3 migration a little bit. I was too confident that no one complained during the beta phase …

Would you mind trying out today's nightly (https://nightly.zettlr.com/)? If that works fine we know I can just push the update.

**Comment by gerotakke** [comment]
Thanks! I installed the nightly and so far haven't run into it again 🤞
Maybe let me try it out for the rest of tonight, I'll report back if I experience the issue again.

**Comment by nathanlesage** [comment]
Perfect! :) Thank you so much for the help!

**Comment by therealjeybe** [comment]
Just wanted to report that I'm also experiencing this issue in version 2.1.0. For me, however, other keystrokes do still work, only inserting new lines with the `Return` key does not work anymore. 
Platform is Linux, OS is Fedora 35, Architecture is x86_64. Am using the AppImage and also tested the RPM.

I downloaded the nightly as well about 15 minutes ago, it didn't reoccur yet. Will use it a bit and report back if it remains that way.

**Comment by nathanlesage** [comment]
> I downloaded the nightly as well about 15 minutes ago, it didn't reoccur yet. Will use it a bit and report back if it remains that way.

Fingers crossed!

**Comment by efficacy** [comment]
Just to chip in that I have been seeing this problem too. It often seems to happen when some kind of temporary choice appears (such as selectiing another Zettel card after typing `[[`). Ift feels as if the pop-up choice grabbed some of the keys (in particular Enter, Up and Down) but did not release them back to the main editor correctly when it had finished. I will also try the suggested nightly build, as this bug is really starting to annoy me now.

**Comment by therealjeybe** [comment]
I worked quite a time with the nightly build right now in about a dozen files and it didn't re-appear until now. So that seems fine, if it works for the others as well I guess that patch surely did it.

**Comment by gerotakke** [comment]
Same here, didn't re-appear for me with the nightly 👍

**Comment by nathanlesage** [comment]
> Ift feels as if the pop-up choice grabbed some of the keys (in particular Enter, Up and Down) but did not release them back to the main editor correctly when it had finished.

Aaaahahaha, yeah, that was the infamous issue #2945

I'm happy that my intuition was right, so this issue was related and can be considered fixed :)

I'll be releasing the patch tomorrow!
