### ISSUE TITLE
Bibfile and Latex [Bug] 

### ISSUE THREAD

**Issue by jorgeborg** [Zettlr/Zettlr#2979]
### Description

Thank you very much for this wonderful piece of software. I was trying it and have following problems. When the citation is with two athors, the first names are confused. When bibtex entry is with numbers (journal entry) the year is not correct, other iinformation is lacking ... (screenshots attached)

In "Export" Definition of Zettlr "CLS Styledatei" is empty and "Zitationsdatenbank" is with bibtex tile (here below):
![Literatur](https://user-images.githubusercontent.com/96977708/147873736-32b1eeed-7f9c-4f94-9f0e-d7f473f38190.png)
![zitation](https://user-images.githubusercontent.com/96977708/147873741-4351d001-c044-4861-b5c1-46be6b4fcc88.png)

### Reproducing

@InCollection{Chaigneau.2012,
	author = {Chaigneau, Clémentine; Seidendorf, Stefan},
	title = {Frankreich in der Europ{\"a}ischen Union},
	keywords = {Einf{\"u}hrung;Europ{\"a}ische Union;Frankreich},
	pages = {336--353},
	publisher = {{Bundeszentrale f{\"u}r Politische Bildung}},
	isbn = {978-3531146317},
	series = {Schriftenreihe},
	editor = {Kimmel, Adolf; Uterwedde, Henrik},
	booktitle = {L{\"a}nderbericht Frankreich. Geschichte, Politik, Wirtschaft, Gesellschaft},
	year = 2012,
	address = {Bonn}
}
@Book{Jachtenfuchs.2002b,
	author = {Jachtenfuchs, Markus},
	year = 2002,
	title = {Die Konstruktion Europas. Verfassungsideen und institutionelle Entwicklung. Zugl.: Mannheim, Univ., Habil.-Schr., 1999},
	keywords = {Deutschland;Europ{\"a}ische Union;Frankreich;Gro{\ss}britannien;Verfassung;Vergleich},
	address = {Baden-Baden},
	volume = 9,
	publisher = {Nomos},
	isbn = {3-7890-7906-5},
	series = {Weltpolitik im 21. Jahrhundert}
}
@Article{Jen.23.07.2011,
	author = {Jen, Stephen L.; Braunberger, Gerald},
	year = {23.07.2011},
	title = {Die Hedgefonds hassen den Euro. Im Gespr{\"a}ch:~Stephen L. Jen, Hedgefonds-Manager in London},
	keywords = {Religion;Staat},
	pages = 17,
	number = 169,
	journal = {Frankfurter Allgemeine Zeitung}
}

### Zettlr Version

Stable (most recent version)

### Specify version

2.1.0

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
So, since this issue has been open for quite some time, let's finalize this one. I tried out your entries several times, and I was always a little confused as to what is happening.

Here are my findings:

1. Umlauts with `{"a}` do not work, neither within Zettlr nor within Pandoc, so this should be something that either you manually or your reference manager should already be able to avoid.
2. Regarding your year, I was always confused what was happening. Pandoc is indeed able to correctly parse it so that it is being exported correctly. However, I figured out that your BibTeX entry contains an error. Specifically, you are assigning the full date to the `year` variable, but as I found out, you actually have to use _three_ different variables for this: `year`, `month`, and `date`. With that fixed, it works perfectly fine.

But maybe this error is already gone for you, which would be even better.
