### ISSUE TITLE
[Enhancement] Add toolbar buttons for back/forward navigation

### ISSUE THREAD

**Issue by kyaso** [Zettlr/Zettlr#2980]
### Description

I think it would be nice to also have dedicated toolbar buttons for navigating your file history, as an alternative for the already existing keyboard shortcuts.

### Proposed Changes

It could look like this (forgive my gimp skills):

![zettlr-back-forth](https://user-images.githubusercontent.com/18646029/147892042-e73e3b06-d0b6-4944-a0be-36aee0115afb.png)

Similar to a webbrowser, when you have reached either end of the history, the corresponding button should be greyed out.

### Caveats

I don't believe there are any.

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (but an older version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Operating System Version

Manjaro

**Comment by nathanlesage** [comment]
> It could look like this (forgive my gimp skills):

No worries, you don't know how easy it is to imagine something with an image attached, no matter the quality.

However, since there are now multiple issues open with requests to new toolbar buttons, and I don't want to clutter everyone's toolbar, I think it might make sense to first implement a way to programmatically show and hide toolbar buttons. Something that macOS has (with this drag and drop thing) might be cool, although pure checkboxes in the settings might be a good middle ground.

**Comment by curtcox** [comment]
I've been using Zettlr for 5 minutes. I'm evaluating it for personal use along with other tools. I'm looking for the equivalent of web browser forward and back buttons. @kyaso indicated that keyboard shortcuts are available, but I can't find them listed [in the documentation](https://docs.zettlr.com/en/reference/keyboard-shortcuts/).
The act of writing up the work-around that I did find (File >> Recent Documents) led me to find Previous File and Next File in the same menu. I suggest using "Recent Files" instead of "Recent Documents" for consistency with the rest of the menu.

**Comment by nathanlesage** [comment]
Implemented in 2.3.0
