### ISSUE TITLE
[Bug] 1.4.0beta-2: Some image paths not exported correctly via pandoc

### ISSUE THREAD

**Issue by jothanne** [Zettlr/Zettlr#299]
## Description/Reproducing
If image paths contain folder names starting with '_' (underline), the backslash in front for folder separation is omitted during export to html or revealjs.

So, for example the image path "D:\_Testdir\_Subdir\test.jpg" is exported to "file://D:_Testdir_Subdir\test.jpg".

Maybe other leading 'special' caracters in folder names are affected too. 

## Platform
 - OS: Windows
 - OS Version: 7 & 10
 - Zettlr Version: 1.4.0beta-2

**Comment by nathanlesage** [comment]
Does this only affect HTML/revealJS?

It's for sure because the underscore is a special character for Markdown (-> italics or bold font), therefore a backslash will be interpreted as an escaping of the underscore instead of being a directory-delimiter. You can actually see it with your description, where exactly those backslashes have been removed. Zettlr itself makes it correctly, so I assume it's a problem with the respective Pandoc writer, but I'll have a second look at it this evening!

**Comment by jothanne** [comment]
Sorry for the delay - as I tested recently, the described behaviour is the same with all the pandoc export options as far as the target files support pictures.

BTW: Why are the relative image paths used in Zettlr always exported as absolute ones and not as relative paths as expected?

**Comment by nathanlesage** [comment]
The image paths are always converted to absolute because in the past we've experienced some strange behaviour with pandoc and xelatex, as the working directory is not always predictable (and from that perspective, the relative image paths won't resolve to the same paths everytime).

The main problem, I think, is with the Windows path delimiters; I think I'll try to convert the backslashes to forward slashes, and it *should* so far work, even with folders beginning with an underscore.

**Comment by jothanne** [comment]
Thank you - that might be the solution!

**Comment by nathanlesage** [comment]
If you could simply test it out by trying it with one or two files in which you simply manually replace all backslashes with forward-slashes, then I'll implement it and ship it with 1.4!

**Comment by jothanne** [comment]
OK - here are the test results:

1. If I paste an image into a Zettlr document, the image description and link path both contain backslashes as usual in Windows. After converting all the backslashes to forward-slashes as suggested and exporting the file to HTML or RevealJS everything works like a charm - but exporting to PDF or ODT there is only the image description shown in the resulting document.

2. If I change the image path of an image pasted into a Zettlr file manually from absolute to relative, replace all remaining backslashes to forward-slashes and then export to HTML/RevealJS - then there  are no images shown. Instead the generated HTML output contains the original path string with backslashes and - in case of any leading underscores - missing backslashes.

Hope this will help you to implement the solution.

**Comment by nathanlesage** [comment]
It pretty much sounds as if the idea I've had might work. I'll implement the converter and then let's hope it's solved in 1.4 :)

**Comment by nathanlesage** [comment]
Should work in 1.4.2, at least with escaping on Windows.
