### ISSUE TITLE
The current file has been modified remotely

### ISSUE THREAD

**Issue by enteropositivo** [Zettlr/Zettlr#30]
I have a directory opened from my DropBox folder  and each time any file that is saved,  Zettlr  throws me a message:

The current file has been modified remotely. Replace in editor ?     And i only edit it from Zettlr 

This popup message is very annoying  when editing several files,  because i must accept the alert each time.

Perhaps a configuration option to accept/cancel allways  automatically ?

**Comment by nathanlesage** [comment]
Oh yes, I know that error and it's been driving me crazy for the last couple of months.

Luckily, since August 5 there's a fix! See here: https://github.com/Zettlr/Zettlr/commit/da74d2c052878589a00980915f12708826e2d515

It will be included in the next version, which will come I think next Friday (b/c this Friday is impossible for me to manage).

Cheers!
