### ISSUE TITLE
Home-End keys not working properly in RTL mode

### ISSUE THREAD

**Issue by safarzadeh** [Zettlr/Zettlr#3005]
### Description

When RTL mode is activated, Home and End keys are not working properly: Home key moves the cursor to the end of line, and End key moves it to the beginning.

### Reproducing

Activate RTL mode.
Wrtie a line in the editor.
Press Home and End key.

### Zettlr Version

Stable (most recent version)

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

10

**Comment by nathanlesage** [comment]
Do I understand you correctly, that you want the Home/End-keys to always move the cursor visually to the left/right of the line? If so, there should be a setting controlling the *visual* direction of the cursor. Does this solve it?

**Comment by safarzadeh** [comment]
Yes, I think that would solve it.
In RTL mode, Home key should move the cursor to the right of the line, and End should move it to the left.

**Comment by nathanlesage** [comment]
Would you mind trying this setting out, then? It's here (last setting):

![image](https://user-images.githubusercontent.com/17251683/148823952-2c2545b7-010f-4cf4-baf1-e1450aef1e9f.png)

**Comment by safarzadeh** [comment]
The "Use visual order..." is already selected; if I turn off this setting, right and left arrow keys would not work correctly.

And I just found another problem: when RTL mode is activated, in a mult-line paragraph, if you go to the end of a line by pressing left arrow key and then continue pressing the left arrow, the cursor would go to the previous line. The correct behavior would be going to the next line.

**Comment by nathanlesage** [comment]
> The "Use visual order..." is already selected; if I turn off this setting, right and left arrow keys would not work correctly.

Okay, maybe we could fix this by looking out for the setting and manually exchanging these two commands so that the behavior is the other way around.

> And I just found another problem: when RTL mode is activated, in a mult-line paragraph, if you go to the end of a line by pressing left arrow key and then continue pressing the left arrow, the cursor would go to the previous line. But it should go to the next line in this situation.

This could potentially also be a problem with CodeMirror itself. [This demo](https://codemirror.net/demo/bidi.html) here gives you the same options to select as Zettlr does. Would you mind trying out if you can reproduce your bug there? If so, we should ask Marijn to have a look at this, since it's a bug with CodeMirror then.

**Comment by safarzadeh** [comment]
Sorry for late reply...

Yes, I tried out the demo, and it's the problem with the CodeMirror.

**Comment by nathanlesage** [comment]
@safarzadeh That's good news, because I think that Marijn might have an idea of where the bug is occurring. Would you mind checking the CodeMirror repository, see if there is an issue already dealing with that ([here's a quick search I performed myself](https://github.com/codemirror/CodeMirror/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+RTL))? If there is, feel free to add your experiences, otherwise, feel free to open a new issue.

Feel free to also mention me so I can track the status of that issue.

**Comment by safarzadeh** [comment]
@nathanlesage 
Thank you for your guidance. I had a look at CodeMirror bugs. As it's said [here](https://github.com/codemirror/CodeMirror/issues/6531), it seems that we should wait for a stable version of CodeMirror 6 for this problem gets solved.

**Comment by nathanlesage** [comment]
Mh, I guess that becomes more and more true the better CodeMirror 6 is …

Well, I can promise that Zettlr will at one point switch to CM6, I just cannot say when!
