### ISSUE TITLE
Wrong spell check decorations for languages other than dictionary avaliable languages

### ISSUE THREAD

**Issue by johannhuang** [Zettlr/Zettlr#303]
## Description
All my Chinese charactors are red dot underlined.

## Reproducing
Open any MarkDown file with both English / Deutsch / ... and Chinese.

## Expected behaviour

No decoration for charactors the editor doesn't understand.

**Screenshots**
![image](https://user-images.githubusercontent.com/26480469/64236735-9ca44500-cf2d-11e9-9b15-c6e9d47a4357.png)

## Platform
 - OS: [e.g. iOS] macOS
 - OS Version [e.g. 11] Mojave
 - Zettlr Version [e.g. 0.15] 1.3.0
 - Screen Resolution [only necessary if the bug is relating to the GUI]

## Additional information

Thanks for this wonderful program.
Vielen Danke for dieses wunderbare Programm.

**Comment by nathanlesage** [comment]
Hey,

thanks for reporting, but it's not a bug, it's a feature: Zettlr has basically two logical behaviours:

1. If there are no spellcheck dictionaries active, spellchecking is considered disabled and nothing will be underlined.
2. If there is _at least one_ dictionary loaded, spellchecking is considered active and **everything not returned as being correct by the algorithm will be underlined red**.

To facilitate multi-language-spellchecking, simply load all dictionaries that you'd like to check your text against. So if you're writing in, e.g., English, German, and Chinese, simply load all of these dictionaries (but be aware not to load too many — three is normally a good maximum).

Why is this good behaviour? Well, Zettlr is trying to be as language-agnostic as it can possibly get, so it does not check what Unicode-range your text belongs to (all text is equal). It only checks: "Is this something reportedly correct or not?" Simply put, there are no characters the program "does not understand" — it understands everything just fine!

**Comment by johannhuang** [comment]
Thanks for your introducing!

Since there is no Chinese dictionary built-in yet, is there a way to add customized dictionaries now? Or is there a way except for totally disabling spellcheck to avoid annoying red dotted line?

**Comment by nathanlesage** [comment]
Please have a look at the docs: https://docs.zettlr.com/en/reference/spell-checking/

**Comment by chchen2021** [comment]
@nathanlesage Thanks for making Zettlr freely available. I recently started using Zettlr and I am on 2.0 beta. I really liked it and got pretty far in customizing it, and then noticed this deal-breaking issue for me: I write bilingually in English and Chinese, and have exactly the same problem reported in this post. I searched all over the web for Chinese dictionaries in Hunspell or LibreOffice, but could not find any, and I don't expect any in the foreseeable future based on online discussions. 

Is it possible for Zettlr to incorporate system spellcheck as an option? I am on macOS Big Sur right now, and the system spellcheck does not have any issue with bilingual spellcheck (or perhaps just selective spellcheck). 

If this is not possible, may I suggest that Zettlr include a keyboard shortcut to turn spellchecking on and off in one shot? Right now I use BetterTouchTool to automate the process. There are about 10 steps to click spellchecking languages on/off in Preferences and then click the eye-shaped icon to "Toggle readability mode" twice. Since there is no menu item (or any other user interface) associated with the readability toggle, BetterTouchTools needs to scan across the screen to find image of the eye-shaped icon first, and it is not very reliable. 

I suspect there are many other CJK users who are bothered or even turned away by the bilingual spellchecking issue. Please take a closer look at this issue and see if Zettlr could offer a workaround.

**Comment by chchen2021** [comment]
@nathanlesage One other idea: in Preferences/Spellchecking, can you offer an option to ignore unicode in a specified block? I am pretty sure the CJK unicode shares the same block.

**Comment by nathanlesage** [comment]
> Is it possible for Zettlr to incorporate system spellcheck as an option?

That is actually something I've been thinking about the whole time: Just completely kick out all custom spellcheck stuff and instead have the operating system manage it. Apparently Electron can simply tap into the OS spell checker for Windows and macOS and uses a native (and thus much faster) spellchecker for Linux. So that should work, but it does require a little bit of work!

**Comment by nathanlesage** [comment]
Feel free to open an issue around that, and also feel free to  have a look at the relevant electron docs for this: https://www.electronjs.org/docs/latest/tutorial/spellchecker/

This would basically mean that Zettlr incorporates the same abilities as Google Chrome with regard to spell checking.
