### ISSUE TITLE
[Enhancement] Autosave to temporary files like we're used to

### ISSUE THREAD

**Issue by Altreus** [Zettlr/Zettlr#3030]
### Description

I discovered that someone had already posted on the subject of autosave - that they had accidentally let it autosave a file they did not intend to permanently change.

We have recently lost literally hours of work because Windows chose to bluescreen, and we did not realise Zettlr did not autosave in the same manner as we were used to.

### Proposed Changes

The current method of autosave has two major flaws:

* It will overwrite a document that didn't want saving in the first place
* It will not save a document that has not been given a filename yet

A reference implementation of autosave would come from LibreOffice, which works like this:

* Select a directory in which to save autosave files (e.g. `$HOME/.zettlr/autosave`)
* Save *all* changes to this directory
* * Might need to add some sort of metadata to the autosaved file, but that's OK
* When the file is explicitly saved, delete the autosaved file
* On startup, check this directory and recover any files in it

This will solve the problems above:

* Files being edited experimentally can simply be restored to their original state by removing the autosave file
* New files are given a temporary filename of the current timestamp, so they can still be given autosave files to restore later
* We would not have lost hours of work because autosave would have worked as expected

It also means you can simply choose not to recover an autosaved file if you don't want to.

### Caveats

I can't think of one.

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [X] Windows
- [ ] macOS
- [X] Linux

**Comment by kyaso** [comment]
For now, there are currently two alternatives:
* Create a copy of the original file and work on the copy instead
* Track your files using some version control system like Git, and revert at any point in time

Note that autosave in Zettlr just means that your edits will be saved _directly_ to the file after some delay. It is - AFAIK - not meant to be a recovery feature as, in your example, LibreOffice has.

Related: #1683

**Comment by nathanlesage** [comment]
@kyaso Exactly.

Plus: Autosaving to a temporary file makes absolutely no sense if we're dealing with plain text files. This autosaving and recovery stuff is necessary for more complex data formats since writing them takes a considerable amount of time and, if you have a bluescreen while that saving process is going on, there is no way to easily recover that file. If you therefore continuously save to some other file, recovery becomes much easier. But given that we have autosave (and that it is on by default!) there is nothing we could additionally save, it would, in other words, not make a difference except that all your files are temporarily twice on your computer.

With regard to how autosave works this is much better captured by issue #2684

Feel free to add your input there as well, since I have not had the time to tackle that issue at all in the meantime!
