### ISSUE TITLE
Click on charactor `>` / `v` or area before to open folder tree branch

### ISSUE THREAD

**Issue by johannhuang** [Zettlr/Zettlr#304]
![image](https://user-images.githubusercontent.com/26480469/64237304-a8dcd200-cf2e-11e9-8e1c-ee02ee32e466.png)

Is it better to enable clicking on the green box area other than the red box narrow charactor to collapse or expend the folder tree branch?

**Comment by nathanlesage** [comment]
While it's not the biggest clickable area, I'd say that it makes more sense from a semantic perspective to open/close the trees only when clicking the indicators (it is counter-intuitive that a tree would open by clicking anywhere on the ribbon BEFORE the indicator, while clicking on the ribbon afterwards would not simply open/close, but actually SELECT the tree).

What we can certainly talk about would be to increase them, which I'd strongly discourage as the text is already in a very good size, and I would hesitate making it even bigger. If you disagree, please discuss it with other users on the [forum](https://forum.zettlr.com/), so that we can get a general mood from the community, and if there are more who think this way, I'd be happy to implement it!
