### ISSUE TITLE
[Bug] Dragging files into the document creates non-working links

### ISSUE THREAD

**Issue by leo-hstone** [Zettlr/Zettlr#3040]
### Description

Image this directory structure:
```
Folder
|-- Test.md
|-- Test.pdf
|-- Subfolder
|    |-- Subtest.md
```

Dragging a local file `Test.pdf` into `Test.md` creates automatically a link:

`[Test](Test.pdf)`

Clicking this link opens my webbrowser like this, resulting in an error:
![image](https://user-images.githubusercontent.com/62036826/149556099-9d876196-3eef-4ddb-bfbb-9e9f32fd74c6.png)

Dragging the file into `Subtest.md` automatically creates this link:

`[test.pdf](..\test.pdf)`

Clicking this link opens my webbrowser like this, also resulting in an error:
![image](https://user-images.githubusercontent.com/62036826/149556252-4ad2bb38-eb9e-4b8e-815e-51ebd3df848e.png)

What's the right was to link to local files? I have found that the folllowing variants work, but I have not found any documentation.

`[Test](./Test.pdf)`
`[Test](../Test.pdf` note: with a forward slash, instead of the auto-inserted backslash above
`[Test](file://C:\....Folder\test.pdf)`

It would be awesome to just drag files into the document!

### Reproducing

See description above.

### Zettlr Version

Stable (most recent version)

### Specify version

2.1.2

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

win32 10.0.18363 (architecture: x64)

**Comment by nathanlesage** [comment]
Well, these links are meant so that Pandoc etc. can easily find that (+ so that the links are not too long). If you click one of those links, they should automatically get resolved. Some documentation is [here](https://docs.zettlr.com/en/faq/#what-is-the-correct-uri-formatting-for-markdown-links), and a test file we're using to test out the link resolution is [here](https://github.com/Zettlr/Zettlr/blob/develop/scripts/test-gui/test-files/Miscellaneous/Link%20Resolution.md).

**Comment by leo-hstone** [comment]
Thanks for the link to the docs! 

To rephrase the issue: Zettlr should generate links to dropped files with the corresponding prefix (`./` or `file://` so that they are identified as files and not as website. 

I would really like to contribute, but I do not have any experience in Zettlr's programming languages. How do you estimate the workload to fix this bug? Is it easy enough for a newbie?

**Comment by nathanlesage** [comment]
Since the link *creation* apparently works as expected, the culprit seems to be the resolution shortly before Zettlr requests to open the file from the OS. If you're not afraid to use a lot of console.logs to see where the error begins, you should be fine playing around with the code. I think it should be the file `source/common/modules/markdown-editor/util/open-md-link.ts` (or something similar in the markdown-editor folder ...)

**Comment by leo-hstone** [comment]
I don't think I quite understand. The docs say: 

> To sum up: If you worry about how your links are treated, be more explicit. Two general rules of thumb can be used to force Zettlr to treat a link as a file or web-link: Prepend a ./ to explicitly request a file link, and append / to explicitly request a web link.

When I drag the file `test.pdf` into the editor, Zettlr includes `[Test](test.pdf)`. But according to the docs it should insert `[Test](./test.pdf)` (which works). So as far as I understand, the opening of links works as documented, but not the insertion.

**Comment by leo-hstone** [comment]
I think the problem is here: https://github.com/Zettlr/Zettlr/blob/a179e11e9bb99f8620549788e9140578acb3758a/source/common/modules/markdown-editor/hooks/drop-files.ts#L75

The returned string `relativePath` is missing a leading `./` for files in the same folder and is inserting backslashes rather than forward slashes for relative paths to files in other folders.

**Comment by nathanlesage** [comment]
@leo-hstone That's a good catch, let's see if we can fix this!

**Comment by nathanlesage** [comment]
Fixed! Thanks again for already finding the culprit :)
