### ISSUE TITLE
[DEVELOP] Migrate main modules to service providers

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#3063]
I'm opening this issue to have a communication channel with the rest of the community regarding a large refactoring I've begun.

Until now, there was this distinction between `modules` and `service providers`, where modules were roughly equivalent to simple Javascript modules (i.e. you have a folder with an index and in there resides the module) and service providers were modules which did not expose any access to other parts of the code. The only code which had direct access to the service providers is the lifecycle hook which boots them up and shuts them down. Access to the internal state of these modules was always facilitated using the `global` object (inside the main process) and the `broadcastIpcMessage` function (towards the renderer processes).

While that was a cool thing, the main reason I used the `global` object was both because module support in an early version of Node was not that good and simply because I honestly didn't understand how modules work.

Over the past two years, however, the whole setup of the app has changed quite considerably. That has had several reasons:

* First, I should name the efforts by the Electron team to mitigate security issues with Electron apps, among these deactivation of node integration, context isolation, and other features which were slowly included. This means that the renderers are now fully autonomous and we could – if we provide the correct APIs – just take some of the renderer process and display it as-is on a website.
* Then, @tobiasdiez has introduced TypeScript to the codebase, and, alongside with that, webpack, electron-forge and thus a host of new possibilities. Ever since his large PR was merged, the files are now combined, minimized and otherwise optimized.
* Furthermore, I lost my fear that something bad could happen in the main process. Or, rather: I now know how to keep code safe without locking everything up.

Additionally to these reasons, there are now new demands for the application: Progress is halting, mainly because code that I would like to implement doesn't have access to some of the codebase which is necessary to implement this simple. As a very palpable example, take the demand for a network visualization of the files: While we now do have a link provider, that link provider is currently unable to resolve the outlinks into correct path names. The functionality for that, however, is already there: the `findExact` method of the FSAL. However, since that is only accessible by the main Zettlr object, the link provider has no means to resolve those links.

In fact, the main Zettlr class is the last remnant from the early versions prior to 1.0 where I organized everything OOP, an hommage to my background with Laravel and PHP in general, where OOP is much more prevalent than in the JavaScript world.

Given that background, here's what I am currently trying to do:

1. Refactor the service providers from classes to functional components which maintain a module-wide state and expose functions which allow limited access to that state in a safe manner. This will not only remove our reliance on the global object, but additionally make typing much easier, since we can simply type the functions and thus remove a lot of boilerplate from the type files (which I already migrated into a new `types` directory)
2. Convert the FSAL, the DocumentManager, and the Importer and Exporter to service providers, that is: Functional modules residing on the top level of the app. This will then additionally end the distinction between service providers and modules: The main process will then only have service providers. The renderers will still have modules, but that is because there are multiple of them, and for example the Markdown editor is something that's needed in several places
3. After this has been done, one of my next goals would be if I can safely remove the `zettlr.ts` class file. I don't yet know how to do this the most proper way, but I'm sure after there is no more state which the class manages a few avenues will open up.

The benefits of this whole endeavor will be that the complexity of the main process is radically reduced and we can finally begin to implement a few other neat things such as the typing of IPC modules which Tobias has already begun working on. Furthermore, this will make it easier for us to slowly migrate the whole preload module towards a way that offers a simple API. This will in turn make it easy to – some day – take the main window code, move it to an external repository, and from there on build a web application (PWA) of Zettlr, which utilizes the code in two places: The desktop app and said web app.

***

In the end, I think this is simply the logical conclusion of going from "I have no idea what I'm doing" towards someone who actually knows what a desktop app needs and how to properly structure it. All in all, it's just another technical debt in the wall!

CC because you seem to be reasonbly active in making PRs and/or thus might be interested to know about this: @kyaso @derwok @Kangie @newhinton

**Comment by tobiasdiez** [comment]
I'm sadly not that familiar anymore with Zettlr code base and still have to learn how to walk the "javascript path" of doing things, so take the following suggestions with the required grain of salt.

> Refactor the service providers from classes to functional components which maintain a module-wide state and expose functions which allow limited access to that state in a safe manner.

While being a good option in some cases, a module-wide state is usually a huge burden (they are essentially the same as singletons). Latest if you think about (unit) testing, this design usually turns out to be pain in the ***. From you description of the problem, it sounds like you need an easy way to access say the FSAL in other parts of the application like the link provider. One way to solve this would be dependency injection, where roughly speaking the link provider says "hey, I need the FSAL to work" by either needing it as a constructor or as a class variable. I have good experience with tsyringe, so that's maybe worth checking out. That way you can get ride of the `globals` without much of a redesign.
As an example, have a look at
https://github.com/JabRef/JabRefOnline/blob/b3e288093fd9e038e287b0f19371d748b5c07abd/api/documents/user.document.service.ts#L31-L33
The `UserDocumentService` is the equivalent of the FSAL in that it manages what documents a user has etc. This is a webapp, so this data needs to be stored in a database, and this is what the `prisma` argument provides. In Zettlr's case this would be (an abstraction of) the file system. In tests, one can then easily mock the whole database and could pretend that certain documents are available or not; without changing any data or even having a real database installed.
https://github.com/JabRef/JabRefOnline/blob/b3e288093fd9e038e287b0f19371d748b5c07abd/api/documents/user.document.service.spec.ts#L6

Especially for managing the visual state (e.g. what files are currently open) one usually uses a "store" like https://pinia.vuejs.org/. But I'm not sure how well this works in an electron app; but the problem to be solved is the same "how do I share the state of one vue component to make it accessible somewhere else". 

Looking at the FSAL, I think this is a nicely designed class. Some of the code like
https://github.com/Zettlr/Zettlr/blob/0f86a73264ab16608ce5c34704e66097dd85a3fa/source/main/modules/fsal/index.ts#L495-L507
might be better moved to a "file helper" class. Some aspects (e.g. project management) feel like it could be exported to a new file that uses the FSAL (instead of being a method in the FSAL). But that are only minor refactorings.

**Comment by nathanlesage** [comment]
@tobiasdiez Hm, especially regarding unit tests you do have a very good point! However, it still feels that if we have "classes" there is this semantic meaning attached to that you should have multiple objects of them.

But regarding that dependency injection you gave me a super interesting idea: instead of keeping the state within the modules, we could create one global state and give each functional component always the sub-state they should modify. This way we can completely get rid of side-effects and enable module testing, even better than with classes since we only need a custom state object and don't have to instantiate every single class that acts as a dependency. This is additionally the same way CodeMirror mode manage their states.

While I have been very much in favor of functional programming in the last year, I see there are some problems with that. So I guess it might be a purely subjective decision. I will have to think about this, but feel free to think about that as well in the meantime!

**Comment by tobiasdiez** [comment]
Some quick remarks.

> However, it still feels that if we have "classes" there is this semantic meaning attached to that you should have multiple objects of them.

Well, in the end it's up to you how you use the classes. But it's quite common that in the real application you only have one instance of the class, while in tests you may create many instances to mock a certain state. 
On the other hand, you can also solve the same problem in a functional manner. For example, the `useStore` function of pinia is the functional equivalent of managing a singleton class.

>  instead of keeping the state within the modules, we could create one global state and give each functional component always the sub-state they should modify.

The problem with this is that then you have multiple components modifying the state without a clear interface of what is possible and what not. I think you do want to divide the state in logically independent parts and have special interfaces for each one of them. Otherwise you have a huge state monster where the file system state is mixed with some preference options.

> don't have to instantiate every single class that acts as a dependency

For this you have the dependency injection frameworks. There whole point of existing of these frameworks is to handle the orchestration of instances.

**Comment by nathanlesage** [comment]
You have very good points, as always! The main problem right now is that I already started converting some of the providers to functional modules... although I could reverse that easily thanks to git. Maybe we (I) should think about a general approach to that… I think I need to draw up how I think the functionality should work in a diagram and then we can improve that first sketch and afterwards implement that? At least that sounds like a bigger company would do it, right? (I have literally no idea how this is being done in the private sector 🙈)

**Comment by tobiasdiez** [comment]
Sorry, I didn't wanted to disrupt your process 👀 

Maybe the conversion that you already did could serve as a test field? During the refactoring you probably noticed that some parts got easier, while maybe other's got harder. If you want, I can also have a look at those commit and give feedback.

**Comment by nathanlesage** [comment]
Please do so! If our unit tests become easier, that would be something pretty delightful in my view (because the test directory is kind of laughable right now ...) I think it's good that you disrupted by process because just because I think something is cool doesn't mean it's something I'll be happy with it! Plus, Zettlr does deserve much more planning than I did thus far!

**Comment by nathanlesage** [comment]
So, I took some time to think about how Zettlr should function on an abstract level and quickly made a sketch:

![image](https://user-images.githubusercontent.com/17251683/150678433-a07d6419-1705-4a9a-858d-d4f8f1c31b4d.png)

In general, when the app starts, the service providers should boot up first, load their state and become ready. That's basically what happens in the lifecycle functions. When the service providers are ready, the rest of the app can start. That is currently done in the Zettlr object. However, thinking about it, the Zettlr object itself basically only enables commands and nothing else. Furthermore, the Zettlr object functions as a bridge from the service providers to the commands.

I think that is something that we can improve: The FSAL, the Window Manager and the Document Manager should become service providers (because other providers need to access them which they can't right now).

Next, we should put the commands on a more stable footing and get them out of the Zettlr main object so that they can be loaded after the service providers have booted and accept incoming requests from renderers.

Then, what is still missing is how to do the global state and whether to use functional components or classes. I have to read on these, but maybe sticking to Singleton classes is the way to go (since that's how it's done right now, so it requires less refactoring).

I think what I'll do in the next days is the following:

1. Revert the functional changes to the three providers
2. Move FSAL, Document Manager, Window Manager into the service providers realm
3. Move out the final functions from the Zettlr class into commands (as already indicated by the TODO-comments above those functions)
4. Reconstruct the Zettlr main object into some form of Command provider that can also be booted by the lifecycle

Then the remaining part is to figure out how to correctly introduce more tests and implement your very good suggestions to enable much more testing of the main process modules.

The question now is: What did I overlook? I'm not going to do more than point 1 today, and then wait for input by you guys!

**Comment by tobiasdiez** [comment]
I think your design looks very good!

What is your definition of a command and service provider?

So based on your description and the existing code, the following are the requirements for the state-full service providers (say the FSAL):
- Only want one instance (not meant in a object-oriented way) during the application life cycle
- Should be easy to mock or bring into a certain state to facilitate tests
- Should be easy to be consumed/used by other service providers and commands.

Are there more constraints?

The existing solution is to model them as normal classes and then use the global Zettlr class to ensure that only one instance exists. Your initial idea (as implemented in eg https://github.com/Zettlr/Zettlr/commit/4a7f8ec997c64f423dfc116ccc38eaa4add3ad05) was to replace the global Zettlr class essentially by the module import handler which would make sure that you cannot have multiple instances, and the class would be replaced by the module. Both approaches work and satisfy the above constraints except for the possibility to mock them. So we need something that can easily be restricted to exist only once in the application, but in many different forms in tests.

So in the end, there are three points that one could change:
- How the service providers are initiated (e.g. class vs module)
- How one make sure that there is only one instance during the application (e.g. singleton)
- How one pass down the dependencies (e.g. constructor injection, as a `context` parameter in the methods that needs it)

https://fsharpforfunandprofit.com/posts/dependencies/ has a great overview of approaches, and also a comparison of functional vs object-oriented. I would suggest to start reading on the last page which gives an overview of the different methods, and then dive into the ones that seem interesting to you.

**Comment by nathanlesage** [comment]
Thanks for the article, in general I think it supports my requirements and your concerns to my initial approach.

Basically, my interpretation of the different layers is like such:

* Renderers should be purely "slaves", that is: since it's both impure code (user interaction) and since there can be many of them, they shouldn't handle any business logic. Rather they should perform two tasks: first, displaying the state to users, and second, transforming a user-intent into a request to the main process
* These user-intents should be modelled in the commands which should serve as this translator between user intent and business logic: they should transform the request into small chunks of work to have the service providers do them. If some part of a request cannot be fulfilled, they should indicate this to the user using meaningful error messages. This means, they also have two tasks: first, translate a request into work and silently return void if everything worked fine. Secondly, if something went wrong, they should display warnings and errors as applicable.
* Lastly, the service providers are the core of the state: They try to fulfill any requests that are handled via the commands, and reject them if they can't fulfill them. But, furthermore, the service providers should also act on their own without user interaction if applicable. For instance, the FSAL should automatically remove deleted files from the state without user interaction through a command. That being said, service providers have a central task with two parts: keep the application state sane, first by handling user requests, and by watching the environment of the app and reflect changes.

And I think, every piece of code we have falls into one of these three categories. The renderers are already configured correctly, they do precisely what I described. The commands are right now still dispersed across the commands, but are also handled in the Zettlr class. Lastly, some modules that are de facto service providers are still simple modules under the sole guard of the Zettlr main class.

I think the easiest way to implement that with minimal refactoring would be to, again, following your advise, reverting the FP changes to the singletons that I already did, then disband the Zettlr module by first moving the remaining modules to the service provider level, and then transferring the rest of the functions to commands. Then, concerning dependency management, the easiest would be to create a new ServiceContainer class that returns singleton instances of the providers. That would only involve creating that new class and basically copy and paste the lifecycle functions there. And, to the constructors of the service providers, add the container instance as a parameter.

And then, we could look from there. Or what do you think?

**Comment by tobiasdiez** [comment]
Yes, that sounds like a very nice plan! For tests you could then simply replace the ServiceContainer by a TestServiceContainer that provides mocks of the real services. One tricky part I see is that you end up with a circular dependency: The ServiceContainer creates the provides, but is also passed as an parameter to them. That might be problematic (for example if one of the providers needs the other ones already in the constructor) but solvable.

One remark about the commands: Since the renderers have the job of handling the user interaction, I think it would be good if the commands would signal errors by throwing exceptions which are then handled by the renderes again (by eg showing an error dialog to the user or something more meaningful).

Feel free to tag me in PRs about this and I'll have a look.

**Comment by nathanlesage** [comment]
Sounds good! With regard to the service container I'll sneakily see how Laravel does it, maybe that's an inspiration :D 

And with regard to errors: I formulated that carefully: the renderers can't display errors because you need a main method to display such a prompt. The goos thing is that everything that could result in an error happens during command execution, so we are fine with only having that code in the commands.

I'll think about a good battle plan and then see to getting to it! I'll tag you as reviewer! 🙏🏼

**Comment by nathanlesage** [comment]
God bless `git revert` — the functional changes are now reverted (and, additionally, a bug I introduced into the appearance provider while doing the refactorings 👀 )

**Comment by nathanlesage** [comment]
Further update: I have begun refactoring the main Zettlr class to extract all functionality as commands, and it's working quite good.

Plus, I discovered that I already used a pretty good pattern within the commands: When they need some functionality from the application services, they all call `this._app.get<Provider name>()`. So I guess the easiest way would be to go for a service container that loads in all service providers, and can be accessed by the commands (and any other place).

So what we would need would be the following:

1. Move the Zettlr class into the lifecycle hook
2. Move the service provider instantiations to the Zettlr class
3. Move the remaining initialization code from this class into the lifecycle hooks
4. Rename the Zettlr class to ServiceContainerProvider (or anything else)

And I think as soon as that is done, we'll be much more scalable again. And can also begin mocking certain services in such a way that we can test the complete main process code.

Something additional I just thought about would be to test the Vue components. This is something unrelated (we only need to mock a very small part of the global API for that) and I think that testing out the Vue components require some different logic, there is a good tutorial available on the Vue documentation.

**Comment by tobiasdiez** [comment]
Sounds like a good plan!

For the state management, one direction one could explore is to handle the state in the renderer using normal vue tooling (i.e. pinia, the successor of vuex) and handle the "serialization" of the state using a [plugin](https://pinia.vuejs.org/core-concepts/plugins.html) that broadcasts the necessary change events on the ipc. In this way, the renderer would not need to worry about the ipc stuff and you get goodies like automatic binding/refs for free.

While looking at the code, I've realized another potential construction site: Currently, there is a very tight binding of various editor plugins and the actual codemirror editor. For example, almost editor plugins parse markdown in some way. I think it would be good to extract this parsing to external modules so that the plugins only tie the parking to the codemirror editor.

For vue-testing, I can recommend storebook for visual testing. Cypress seems to be the standard for functional testing, but I never got convinced enough that such UI testing is actual worth the effort to really use it.

**Comment by nathanlesage** [comment]
> While looking at the code, I've realized another potential construction site: Currently, there is a very tight binding of various editor plugins and the actual codemirror editor. For example, almost editor plugins parse markdown in some way. I think it would be good to extract this parsing to external modules so that the plugins only tie the parking to the codemirror editor.

That is a construction site I would rather leave right now. Zettlr will need to switch to CodeMirror 6, and since its API is completely incompatible with the CodeMirror 5 API, I'd rather leave it as it is right now, and begin to refactor everything only while already preparing the CM6 API bindings. My plan here was to just duplicate the MainEditor component, and offer some checkbox like "Enable CodeMirror 6 (EXPERIMENTAL!)" in the settings to switch between CodeMirror 5 and 6, so that we can gradually implement all functionality we have in CM5 in the new editor.

> For vue-testing, I can recommend storybook for visual testing. Cypress seems to be the standard for functional testing, but I never got convinced enough that such UI testing is actual worth the effort to really use it.

Yeah, there was a tutorial for testing on the vue site. It's not that I want to go all too deep into developing tests, but I do see the benefit of having at least some rudimentary tests that act as some form of canary if we're about to implement something stupid … it's more an insurance because I know myself :D
