### ISSUE TITLE
[Bug] Zettlr stops reloading citation database

### ISSUE THREAD

**Issue by nistude** [Zettlr/Zettlr#3104]
### Description

When updating entries in Zotero (5.0.96.3), Zettlr sometimes tries to reload the database JSON while it is being updated, leading to an import error:
```
[21:39:53] [Info] [Citeproc Provider] Database /home/sturm/SpiderOak Hive/zotero/My Library.json has been changed remotely. Reloading ...
[21:39:53] [Info] [Citeproc Provider] Parsing file /home/sturm/SpiderOak Hive/zotero/My Library.json as CSL JSON ...
[21:39:53] [Error] [Citeproc Provider] Could not reload affected database /home/sturm/SpiderOak Hive/zotero/My Library.json: Unexpected end of JSON input
```
At this point Zettlr doesn't ever retry the import and I have to restart the application or reset the citation database in the config.
I would expect Zettlr to retry the import for a few seconds and then go back to its regular file watching.

### Reproducing

Open a note in Zettlr that contains a citation reference.
Go to Zotero and update entries and notes until Zettlr fails to reload the citation database.
Citation references stop rendering in Zettlr.

### Zettlr Version

Stable (most recent version)

### Specify version

2.1.3

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Debian

### Additional Information

I noticed this issue at least in 2.1.2 but I don't remember it from 2.0.

**Comment by nathanlesage** [comment]
Thanks for reporting. Since several users reported problems I have now used this opportunity to improve two things:

First, the Citeproc provider now waits for 5 seconds until it assumes a file to be fully written. This should give the computer more leeway in writing even large databases. And secondly, if the error indicates that the database was simply not finished writing (`Unexpected end of JSON input`), it will attempt a second time after another 5 seconds delay. Tomorrow there'll be a new nightly, which you can test out. Feel free to report back if there are additional issues!
