### ISSUE TITLE
[Bug] Updater not working

### ISSUE THREAD

**Issue by joraphael** [Zettlr/Zettlr#3124]
### Description

After downloading and executing the available update within Zettlr, I get an error indicating that the file is used by another programme. In order to update I have to execute the file outside of Zettlr. I have had the issue already since a couple of update rounds.

![Zettlr_updating_error](https://user-images.githubusercontent.com/84806245/151819426-6796c231-8d05-4ae4-b9c3-ceedf9f64f74.png)
 

### Reproducing

Use the in internal updater.

### Zettlr Version

Stable (most recent version)

### Specify version

2.1.3

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
Yeah, the issue is known. The problem is basically that the running app still has something pointing to the installer when it tries to launch it. It's a minor nuisance, since you can just manually start the installer, but it's a nuisance, agreed!

**Comment by exanrauzer** [comment]
I would like to spot on that bug. From typical Windows User point of view that message means that whole program is somehow flawed or next version is broken (we suppose that this is te first time the User see this message). This do not work well for good reputability of Zettlr. As we agree that we aim for perfection.

**Comment by nathanlesage** [comment]
> This do not work well for good reputability of Zettlr.

I am fully aware of that, but I have literally no idea why this is happening, or how. I would appreciate anyone giving useful information on where we might start to look for fixing this.

**Comment by nathanlesage** [comment]
Okay, short update: I have a potential fix for the problem: I never closed the write stream. In other words: While most OSes will not complain, Windows requires file handles to be closed by the requesting application. In other words: Without closing the write stream, Zettlr will still have "locked" the update file, resulting in the aforementioned error. This also explains why, after quitting Zettlr, everything works fine: Because by quitting the app, the file handle is also automatically released.

Therefore, I hope this commit has now fixed the issue, but please try it out and report back if it doesn't.

**Comment by nathanlesage** [comment]
I just confirmed: The error message appeared because I forgot to close the write stream properly. It works now!

**Comment by exanrauzer** [comment]
Great!
