### ISSUE TITLE
What Regular Data is Sent from us by Zettlr via internet?

### ISSUE THREAD

**Issue by washere** [Zettlr/Zettlr#32]
I noticed Zettlr regularly needs to send data over the internet protocols.

Q1: What Regular Data is Sent from us by Zettlr via internet?

Q2: is it sent by secure protocls

Q3: What user data do you keep?

I have disabled data transfer by Zettlr with the Comodo Firewall until I find out what data is being transferred..

Thanks.

**Comment by nathanlesage** [comment]
Hey @washere,

you do not need to worry, because I value privacy. Currently, I myself do not receive *any* traffic from the app. The only page that _does_ receive data is GitHub itself, and this only, because Zettlr requests a list of all Zettlr-releases on start up so that it can check for updates.

Therefore the answers you seek are:

1.) On each update-check, up to four requests are made. The first three requests determine whether the app is online. They are made by the package `is-online` that I use to determine the online status (this step is only necessary, because the `net`-library throws an ugly error if the request fails due to missing connectivity, and no one was successful yet to catch it during runtime).

From the [docs of the is-online-package](https://www.npmjs.com/package/is-online):

> The following checks are run in parallel:
> * Retrieve icanhazip.com via HTTPS
> * Query myip.opendns.com on OpenDNS (Node.js only) [Is executed, because Electron uses node.js]
> * Retrieve Apple's Captive Portal test page (Node.js only) [Is executed, because Electron uses node.js]
> When the first check succeeds, the returned Promise is resolved to true.

After this check succeeds, one more HTTPS-request is sent to the URL https://api.github.com/repos/Zettlr/Zettlr/releases from within the app. This happens in [this line](https://github.com/Zettlr/Zettlr/blob/ad50203b7d227a61d8e593f47cb6db0b6892c875/source/main/zettlr-updater.js#L88).

While doing this, GitHub will receive your current, public IP address. As will the other pages.

I personally do not know what data GitHub saves, but using the `net.request()`-command it's a lot less than if you would check the releases page manually, because a lot of header information that is included in default Browser requests is not given by Zettlr.

2.) Yes. I do not use HTTP or other unsecured protocols.

3.) Nothing.

----

To answer some implicit questions my answer may have risen in some of you by now:

* Yes, I plan to integrate something that allows you to send anonymous user data. I would like this, but it will be strictly opt-in. I will _not_ phish your data just like that.
* No, this does not have priority at all. Features \> Your Data.
* I will not sell data.
* I will integrate a better online check to reduce the four requests made by a foreign package down to one or two made by me.

I hope this answers your questions! If you have further ones, please do not hesitate to ask. After there are no more questions, I will integrate the questions and answers into the [FAQ](https://zettlr.com/docs/faq)-section of the website.

**Comment by nathanlesage** [comment]
UPDATE: Already included `got`, thereby I've reduced the amount of requests made to only the one that goes towards the GitHub API.

**Comment by washere** [comment]
Hi Nathan,

Thanks for the detailed answers. Seems fairly straightforward and logical.

Maybe you can put this information somewhere on the website so your useful words are not buried in here in the archives as I will be closing this issue.

I had a short play with Zettlr, will spend more time over the weekend. Seems like a good Tree Outliner Markdown editor hybrid with a File manager/commander. It can turn into something quite unique. I like the speed, it is fast indexing files/folders.  

I like the resizing of panes (well, the right one which resizes left too), would be good if the left column could be individually resized. This was a reason I stopped using Trilium (also on Github) though it is a different category to Zettlr, more of a network version of NoteCase Pro. Zettlr focus on files/folders makes it good for book/screenwriting etc like Scrivener. where subfolders can be chapters/scenes etc with individual files folders like notes etc for each section/subsection. 

I would also uggest:
* Add "Down Arrow & Up Arrow" keys to move Down/Up the nodes in the left/middle column when it has the focus. This is standard for on Tree Outliners, the way pro users use them fast instead of just mouse.

* Add "Left Arrow & Right Arrow" keys to expand or collapse the nodes in the left column. Again this is fairly standard.

I am not opening issues for these, because I see you have a lot to do already.

Good job, bro, keep it up.

Thanks again.
