### ISSUE TITLE
[Bug] 2.2.3 and 2.2.4 crash on start

### ISSUE THREAD

**Issue by wilkohardenberg** [Zettlr/Zettlr#3240]
### Description

Right after installation 2.2.3 and 2.2.4 crash on start with the following message "Could not start FSAL: Cannot read properties of undefined (reading 'startsWith')"

![Screenshot 2022-02-20 at 15 07 23](https://user-images.githubusercontent.com/1612993/154846753-12bf1cb0-b1fc-46c2-9dd0-aedcaf98bdbf.png)
"

### Reproducing

As with my previous issue with 2.2.1 I don't know if this happens only to me. Again I installed the new version and since then, on starting Zettlr, it crashes. The last stable version I am able to use is 2.1.3

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.3 and 2.2.4

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

10.14.6

**Comment by rjkerckhoffs** [comment]
Hello, I face the same issue on my Mac. This time it is an Mac OS on ARM. Exact same error: Error starting FSAL
Could not start FSAL: Cannot read properties of undefined (reading 'startsWith')
On my Windows device it is working with the same repository (on OneDrive).

**Comment by wilkohardenberg** [comment]
I updated the issue, since it is still the case for 2.2.4

**Comment by nathanlesage** [comment]
Alright, I've had yet another look where the `startsWith` function is being called. It turns out: Almost every piece of code utilizes this.

However, I might've found the culprit.

In your `config.json` file (locations: see the docs) the property `openDirectory` is apparently accidentally set to `undefined`? It must be `null` instead.

So the easy solution would be: Remove the `config.json` and just start Zettlr with a fresh config. Then it should work as intended again. (That is: Remove the config.json, then install 2.2.4, and then launch it)

**Comment by nathanlesage** [comment]
Also, I just added an additional check to see that the corresponding config value has the expected kind of value. So the next nightly on Monday may work already without you doing anything.

**Comment by wilkohardenberg** [comment]
Brilliant, thanks! It works!

**Comment by nathanlesage** [comment]
BAM! Nice :)

Thanks so much for bearing with me over the last month!

**Comment by wilkohardenberg** [comment]
It's not like 2.1.3. didn't work brilliantly already. Now, however, I will procrastinate writing to find out all the new features I missed  :-D
