### ISSUE TITLE
Composite Markdown fixes [tweek suggestions]

### ISSUE THREAD

**Issue by jrcharney** [Zettlr/Zettlr#327]
In mathematics, there is a concept called [function composition](https://en.wikipedia.org/wiki/Function_composition) where you can set up two or more functions to work together to perform the tasks of each function. [Computer science](https://en.wikipedia.org/wiki/Function_composition_(computer_science)) has adapted the same concept which can be replicated in languages like JavaScript like in [this example](https://codepen.io/joelnet/pen/QdVpwB?editors=0010).

When you use **bold** and _italic_ together that is the composition of both **_bold and italic_**.

I brought up that first paragraph because I was trying to think of what to call it when you use two things on the same object. Calling it a "composite" seems appropriate.

Zettlr can do some markdown composites, but there seems to be a few things that could be resolved.

For instance, I noticed that if I put `code text` inside of a link, the code text doesn't appear in the monospace font and the back ticks appear. However, I can put a link inside of bold text or italic text.

Another issue is inline LaTeX (single dollar signs, not doubles; Doubles are block style) in tables. (I think I may have mentioned that in another bug report, but I though I would be ideal to mention that again since we're on the subject of fixing a few Markdown fixes.)  Inline LaTeX can appear in lists and regular text. The proper way to bold or italicize LaTeX text is to stick the inline LaTeX in a `\text{}` block and use `\textbf{for boldface}` or `\textit{for italic text}` if I recall correctly.

That brings me to another point, if code text has a backslash in it `\ `, (If I want to share what LaTeX code I use in inline code text) the backslash isn't included in the formatting. Should I use two backslashes to tell the Markdown editor that the backslash is part of the code?

I know that block style LaTeX and code blocks won't happen in lists, tables, or blockquotes (not unless there is some smart way for Markdown to figure  that out. So for now, let's not worry about that.

Finally, blockquotes. I think I may have mentioned this in a couple of other posts, but using them is hard to read in just about every theme in dark mode. Even worse is how the color theme can make bold, italic, link, and code text more difficult to look at. One suggestion is to modify the blockquote style to render text as usual but give it an accent background and maybe a left border with an accent color (sort of like how email does it or when the active file is chosen in the sidebar.  An accent background could also be ideal for styling multiline code blocks.  Markdown rendering should be rendered in place like how LaTeX is rendered in place.

I would really like to see horizontal rule (`<hr>`) be rendered in place.  I was under the impression that at least three tidles (`~~~`) or dashes (`---`) was the code for horizontal rule. If permitted, can we look into that and have it render-in-place?

At any rate, that's my experience so far. Keep up the good work.

**Comment by jrcharney** [comment]
Here's another issue with how Markdown is rendering text:  If the text has any square brackets or parenthesis in the text part (such that if two opening or closing characters are next to each other) or if in the link part there are parenthesis or periods next to the opening or closing parenthesis, the link will be rendered awkwardly. The outermost square brackets in the text part and the outermost parenthesis in the link part should be recognized as part of the link.

Inner parenthesis in should be re-rendered to correspond with their ASCII code as should any characters that may interfere with how links are processed.  Perhaps HTML style (`&` style) or URL/Hexadecimal style (`%` style) should be used to fix the rendering.

**Comment by nathanlesage** [comment]
That's quite some stuff to go through. Nevertheless, concerning the colours: We'll add them to our overhaul project. Could take some time, but if you have any suggestions as to colours, feel free to inform us.

> For instance, I noticed that if I put code text inside of a link, the code text doesn't appear in the monospace font and the back ticks appear. However, I can put a link inside of bold text or italic text.

That is because basic formatting (bold/italic) is recognised by the links. bold and italics also work within rendered links. Code was not one of my concern when implementing that functionality. Please also keep in mind that Zettlr is a WYSIWYM-editor rather than a WYSIWYG — so some rendering is allowed, but keep it realistic :)

> Another issue is inline LaTeX (single dollar signs, not doubles; Doubles are block style) in tables.

Very easy answer to this: No. LaTeX will never be rendered within Markdown files. It can indeed be used as some advanced formatting aid, but I will not go through the insanity of recreating something like KaTeX for a whole module plus LaTeX support. Zettlr is a Markdown editor, not a LaTeX editor, it's just by coincidence that you can make use of it additionally when it comes to PDF exporting.

> That brings me to another point, if code text has a backslash in it \ , (If I want to share what LaTeX code I use in inline code text) the backslash isn't included in the formatting. Should I use two backslashes to tell the Markdown editor that the backslash is part of the code?

Yes.

> I think I may have mentioned this in a couple of other posts, but using them is hard to read in just about every theme in dark mode.

Related to colouring, so please be patient on this one.

> Markdown rendering should be rendered in place like how LaTeX is rendered in place.

I think you have a small misconception about the philosophy of Zettlr: Markdown should not be rendered in place per se. The only reason Zettlr renders _some_ elements is to make them easier to read. Nothing less and nothing more. Zettlr is, as I said, WYGIWYM. And secondly, LaTeX is not rendered in place. If you really think about it, only Math is rendered in place. Not the other LaTeX stuff. Only equations.

> I would really like to see horizontal rule (<hr>) be rendered in place.

Horizontal rules can be done with asterisks or ticks: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#horizontal-rule

> The outermost square brackets in the text part and the outermost parenthesis in the link part should be recognized as part of the link

Unfortunately, not always. I have set up a file where I tried to encompass every single possibility of these brackets appearing close to each other, but I still have no luck rendering everything perfectly.

> Inner parenthesis in should be re-rendered to correspond with their ASCII code as should any characters that may interfere with how links are processed. Perhaps HTML style (& style) or URL/Hexadecimal style (% style) should be used to fix the rendering.

?

**Comment by jrcharney** [comment]
> Zettlr is a WYSIWYM-editor rather than a WYSIWYG — so some rendering is allowed, but keep it realistic :)
Fair enough. Still, sometimes the renders when typing subscripts (`x_{y}` prints x<sub>y</sub>) in LaTeX too soon, even if you set the italic setting to a pair of single asterisks instead of a pair of underscores.

> Very easy answer to this: No. LaTeX will never be rendered within Markdown files.
OK, I was just wondering. I may have said this, but I'm pretty sure the only way to do that is for the user to [create a table with LaTeX](https://www.tablesgenerator.com/). Hopefully KaTeX will support the [table syntax](https://www.latex-tutorial.com/tutorials/tables/).

For the last question you answered with "?" indicating that you may not have understood what I said. What I was trying to say was, if I copy a URL address with special characters in it, when I paste the URL, the address should be in the [encodeURI format](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) such that if I paste a URL like this one `"https://en.wikipedia.org/wiki/Function_composition_(computer_science)"` The URL in the link would be modified to `"[https://en.wikipedia.org/wiki/Function_composition_(computer_science)](https://en.wikipedia.org/wiki/Function_composition_%28computer_science%29)"`. 

Another instance is if the copied link's title has square brackets like `"Beginner's guide to Javascript arrays [PART 2]"`, the `"[Beginner's guide to Javascript arrays \[PART 2\]](https://dev.to/simplytammy/beginner-s-guide-to-javascript-arrays-part-2-411p)"` (backslashes to escape the square brackets in the text part).

**Comment by nathanlesage** [comment]
Ah now I see. So for the subscripts in LaTeX — it's natural because the Gfm CodeMirror mode is not aware of LaTeX and doesn't check for it. Nevertheless, if you want to go for PDF anyways, just use the Markdown subscripts/superscripts. Easier to write and these'll be converted to the sub-/superscripts during export (Pandoc will simply leave the LaTeX commands, but convert the Markdown ones to LaTeX prior to pushing it through XeLaTeX).

Concerning LaTeX in tables, I don't see a problem:

![image](https://user-images.githubusercontent.com/17251683/65026733-6dcc9c80-d939-11e9-8796-eecab89a85b1.png)

And for the last thing: It's an interesting solution to URIencode these URLs. However, I don't want to do this, because it is possible to do it with the right RegExes — for instance GitHub doesn't URIencode the URLs, and it still gets them right. So with enough thinking going into that it should be possible!

**Comment by jrcharney** [comment]
OK, here's a couple instances that needs to be addressed. 

Yesterday, I was using Zettlr to copy some CSS into a markdown example when I noticed that when I typed in a color string (e.g. `#444`), Zettlr still recognized it as a tag even though the string was in a code block (surrounded by text with three backticks in a line before it and three backticks in a line after it.

Today, I was documenting a line of inline code (single backtick on each side) a Regular Expression in JavaScript that had two numbered capture groups (e.g. `$1-$9`) when Zettlr treated the content inside it like an inline LaTeX.

Just to be sure, Zettlr does have a list of rules in order of **precedence** that know when's a good time to process a rule, right?  I know you said Zettlr is a WYSIWYM editor, but sometimes it better when WYSIWYM is WYSIWYG.

**Comment by nathanlesage** [comment]
Zettlr in fact has a precedence list, which is hardcoded here:

https://github.com/Zettlr/Zettlr/blob/9778467c3130961ba897f0d9d252b21cc40a348f/source/renderer/zettlr-editor.js#L344-L353

If any of the previous rendering elements have rendered something, the following don't do it. Nevertheless, as of now I have not implemented an automated detection of inline-comments, which needs addressing, yes.

a `#444` will still be treated as a tag, but obviously it should only happen outside of code blocks.
