### ISSUE TITLE
Missing URI encoding and decoding

### ISSUE THREAD

**Issue by BAKFR** [Zettlr/Zettlr#330]
## Description

Links and Image links are URL: I believe they should be URI encoded when added in markdown code, and decoded when read from the markdown to other use.
This is not the case, and it can cause issues when dealing with spaces or special characters.

## Reproducing / Expected behaviour

2 examples. There are others.

1. Drag & drop an image containing a `#` in its name.
  **Expected**: The generated markdown code should encode the path and display the image.
  **Actual result**: The generated markdown code uses the "#" symbol, and so the URL generated is invalid.

2. Paste an Image from the clipboard with a space in its name, from a source that add the URL in the clipboard too (ex: Eye of Mate).
  **Expected:** The "paste-image" window generate a default name with a space (Ex: "My file.png")
  **Actual result:** The proposed name is URL-encoded (ex: "My%20file.png")

## Platform
 - OS: Linux
 - Zettlr Version v1.4.1

## Additional information

I will provide a pull request to fix most of these, once I have fully understood the last details. 

I have a question about this code:
https://github.com/Zettlr/Zettlr/blob/17fa2698779b6aa440e2a1af2515ac84d9f94f82/source/renderer/zettlr-editor.js#L253-L255

Is there a particular problem using URI-encoded URL in markdown ? How can I reproduce it if I remove the `decodeURIComponent()` ?

**Comment by nathanlesage** [comment]
The problem why I did not URL-encode these paths was that Pandoc, when exporting to PDF or something, XeLaTeX would go mad at me. You can even see it specifically in the comments above that line you were questioning.

The problem is the following: Links can't be URL-encoded because then the engine will fail. Where they could be URL-encoded might be the preview. There are basically three places where these URLs matter: The previewing aspect (where `#` would be an illegal URL character), the exporting aspect (where `#` must stay decoded) and the HTML export aspect (where `#` might in some browsers be a problem). So we should spend some more research on that before doing something rash. It requires a lot of research.

**Comment by nathanlesage** [comment]
Closing b/c of inactivity and b/c I don't think this is an issue we can deal with …
