### ISSUE TITLE
The zettlr.desktop file has a few errors (in Gnome desktop environment / Linux)

### ISSUE THREAD

**Issue by jchalifour** [Zettlr/Zettlr#3322]
### Description

I had a problem where the Zettlr application icon wouldn't appear in the Gnome desktop's app grid (or search) up after being installed. I [posted to the Manjaro community](https://forum.manjaro.org/t/application-wont-appear-in-the-gnome-app-grid-or-the-search/105560/3) because I thought there was a problem not with Zettlr but with my desktop setup. That might still be the case but in the process, they identified a few small errors in the zettlr.desktop, which when changed, did solve my problem. 

The recommended changes to the zettlr.desktop file (which resolve errors that otherwise get reported) are as follows: 

`[Desktop Entry]
Version=1.0
Type=Application
Name=Zettlr
Comment=A Markdown Editor for the 21st century
Exec=zettlr
Icon=zettlr
Terminal=false
StartupNotify=false
Categories=Office;
MimeType=text/markdown;
StartupWMClass=Zettlr`

### Reproducing

Click the Gnome app grid, look for Zettlr
or
Click Activities (or Super key on keyboard) and type "zettlr" into the search.

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.4

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Manjaro, plain Gnome, up-to-date

### Additional Information

Here is the error message that was provided: 

`❯ desktop-file-validate /usr/share/applications/zettlr.desktop
/usr/share/applications/zettlr.desktop: error: value "Office;;" for key "Categories" in group "Desktop Entry" contains an unregistered value ""; values extending the format should start with "X-"
/usr/share/applications/zettlr.desktop: error: (will be fatal in the future): value "text-markdown;;" for key "MimeType" in group "Desktop Entry" contains value "text-markdown" which is an invalid MIME type: "text-markdown" does not contain a subtype
/usr/share/applications/zettlr.desktop: error: (will be fatal in the future): value "text-markdown;;" for key "MimeType" in group "Desktop Entry" contains value "" which is an invalid MIME type: "" does not contain a subtype`

**Comment by jchalifour** [comment]
After posting this, the person looking at the issue in the Manjaro forum, submitted a bug report to the Arch Linux community. I don't think that I really understand what is behind the issue but maybe it actually goes to something else (gendesk?), which maybe is relied on to create that zettlr.desktop file? In any case, here is a link to that report in case it's useful https://bugs.archlinux.org/task/74119

**Comment by nathanlesage** [comment]
So I had a look, and those values are coming from the file `electron-builder.yml` and are being consumed and written to said Desktop file by Electron Builder. The values in the YAML file are correct, and I just double-checked that I wasn't simply using some outdated property names. So it could be potentially three points of failure:

1) Electron Builder parses them incorrectly into the Desktop file (which could be because `text/markdown` becomes `text-markdown` in the Desktop file which indicates wrongful escaping),
2) there is some error in how the Arch Linux binaries are being created (that's what the issue you just linked is addressing),
3) there is an error in how the Desktop files are being consumed by the operating system itself.

Without knowing better it could be option 1 or 2, but 3 is unlikely.

Furthermore, I just ruled out option 1. Here is the Desktop file that Electron Builder generates — it should validate properly:

```ini
[Desktop Entry]
Name=Zettlr
Exec=/opt/Zettlr/Zettlr %U
Terminal=false
Type=Application
Icon=Zettlr
StartupWMClass=zettlr
Comment=A Markdown Editor for the 21st century.
MimeType=text/markdown;text/markdown;text/markdown;
Categories=Office;
```

Therefore I would argue the issue you just linked is absolutely at the right place, there seems to be a small bug in how the AUR package is being generated based on the prebuilt binaries. So I'm going to close this issue, if that is alright!

**Comment by jchalifour** [comment]
Great, glad to hear it seems like it's in the right place now.
