### ISSUE TITLE
[Bug] Folding not working with H2 headers and subtitle

### ISSUE THREAD

**Issue by davidoskky** [Zettlr/Zettlr#3331]
### Description

If you've got an H2 header (##) followed by a subtitle (---) the folding works only on the subtitle, the header cannot be folded by clicking on the triangle on the left.

### Reproducing

```
## Title
Subtitle
---

Content
```

Use this file for testing: clicking on the triangle adjacent to Title nothing happens, clicking on the one adjacent to subtitle the content is folded.

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.4

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Arch Linux

**Comment by nathanlesage** [comment]
This is intended behavior. The ATX heading with two hash-signs is a heading level 2, as is the SeText header if you use hyphens. Therefore, the triangle obviously only folds the heading, since the "Subtitle" is the same level as what you title "title".

If you want the "subtitle" to be folded into the whole section, use a heading of level one, denoted by a single hash-sign.
