### ISSUE TITLE
citations got wrong

### ISSUE THREAD

**Issue by Sisi-Wiciel** [Zettlr/Zettlr#334]
## Description
The author name written in Chinese got wrong when exported to docx\pdf\html, but it was correct in the GUI.

## Reproducing
I had tried to restart the apps, change the CSL, re-exported the documents.
The CSLs used in zotero were correct.

## Expected behaviour

**Screenshots**
![GUI](https://user-images.githubusercontent.com/21168981/65256316-f01fb100-db31-11e9-9fdd-e45ea96c950b.png)
![DOCX](https://user-images.githubusercontent.com/21168981/65256355-fc0b7300-db31-11e9-88c0-3ee910141e2b.png)

## Platform
 - OS: Windows
 - OS Version 10
 - Zettlr Version 1.40
 - Screen Resolution [only necessary if the bug is relating to the GUI]

**Comment by nathanlesage** [comment]
Due to my bad Chinese skills I have no idea what is wrong with these, but what I suggest is the following:

Zettlr uses a built-in style which makes it really easy to get an idea of what the references will look like, **but** I think that the default CSL style that Pandoc uses is a different one.

To make sure your exported styles are correct, please follow these steps:

1. Go to www.zotero.org/styles
2. Download the style you would like to use
3. Go to the Preferences -> Export -> Select your downloaded CSL-Style
4. Exporting will now use the respective CSL-Style.

The CSL-style used by Zettlr cannot be changed, but it is only for preview purposes either way!

Does this solve your problem?

**Comment by Sisi-Wiciel** [comment]
The problem was that when there were 3 characters of authors' name, when the document was exported to docx\pdf\html, there were only the first character and the third character. I had tried to use zotero to insert citation, it got right. I don't know what should I do.

**Comment by Sisi-Wiciel** [comment]
oh, there were the first and second character.

**Comment by nathanlesage** [comment]
There may be a problem with pandoc-citeproc and the configuration, but I do not really get the problem you are experiencing, I'm afraid :/

**Comment by Sisi-Wiciel** [comment]
Well. The problem is that if the author name was "任清涛" and when it was exported, the name turned to be "任 清". The third character will be lost, and there was a space in the first character and the second character. But the name in English gets right.

**Comment by nathanlesage** [comment]
Then I assume that this is an error in the citation style, or even the CSL engine …? But I strongly assume it's not a problem with Zettlr.
