### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by dakezuo** [Zettlr/Zettlr#3367]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [ ] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [ ] I have searched the documentation to make sure I did not overlook it.
- [ ] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

希望能够添加预览写作效果和标题工具栏

### Example Workflow

比如写“123456”，然后可以直接调整他的标题等级，如# 或者##，设置为1级或2级标题
比如# 123456 ，这是编辑模式 可以增加一个预览模式是直接 123456放大的标题这种

### Caveats

无

### Do you wish to attempt implementing this yourself?

No

### Platforms

- [ ] Windows
- [X] macOS
- [ ] Linux

### Additional Information

可以参考typora

**Comment by nathanlesage** [comment]
Closing due to wrong language. Please only open up issues using English, as it is the most inclusive language for our purposes here.

Translations via Google Translate, deepL, or similar are also absolutely fine if you do not feel comfortable just writing English by yourself, but issues need to be in English.

Furthermore, if you plan to open an English issue, please include more information. I unfortunately didn't get what you would like to have.
