### ISSUE TITLE
[Bug] blank editor after a md syntax mistake in checkboxes.

### ISSUE THREAD

**Issue by rakta** [Zettlr/Zettlr#3368]
### Description

Following syntax mistake leads to a blank editor window: `* [ ][[link]]`, thus without _space_ after `* [ ]`
The editor window is then blank for any files you open. The problem resolves after closing the affected file and restarting Zettlr.

### Reproducing

Create a file with following content (only the line with the link produces no unexpected behaviour)
```

* [ ][[link]]
* [x] jklsd
```

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.4

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 20.04 LTS

**Comment by nathanlesage** [comment]
Gave it a quick check, and indeed. The bug is because the underlying syntax highlighting mode retains in its state a boolean to see that it is within a task list, but the internal links as produced by Zettlr are basically "hidden" from the underlying mode, so that the line looks like this:

    * [ ]
    * [x] jklsd

I am not sure though what causes the underlying mode to fail. I'll have to look into that again.

**Comment by nathanlesage** [comment]
This should be fixed in the current nightlies.
