### ISSUE TITLE
Bold / Italic no color ¦ Zettlr 2.2.5

### ISSUE THREAD

**Issue by sjewson** [Zettlr/Zettlr#3404]
### Description

No Color styles when I use Italic or Bold markup
![image](https://user-images.githubusercontent.com/2188641/164739239-c4c32f6b-ad23-413c-9d7d-16700ba934a3.png)

No sorting files period 
![image](https://user-images.githubusercontent.com/2188641/164740634-2778d1c7-4376-4f74-aa3d-e40566f335ec.png)

### Reproducing

I have updated to ZETTLR 2.2.5 on Windows 10 and when I use Bold or Italic on words the color styles have now disappeared.

I have not created any CSS and I have rotated through all themes to see if this issue was related to a specific theme but the color styles do not appear on any theme within ZETTLR

I also notice that there are no files sorting options that did appear to the right next to "workspace " as per image

![image](https://user-images.githubusercontent.com/2188641/164740474-f812d6bb-16a4-4558-a77b-e789065a5f87.png)

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.5

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
The color has been removed due to popular request. You can always reinstate the colors using custom CSS by following the instructions in the documentation: https://docs.zettlr.com/en/core/custom-css/

With regard to the sorting icons: Again, this is absolutely working as intended. You can sort files by right-clicking a directory and selecting "Properties":

![image](https://user-images.githubusercontent.com/17251683/164741387-d4b35fef-3f8a-4188-a004-8e3222ec5e91.png)

**Comment by sjewson** [comment]
awesome thanks Nathan!

I was confused as my previous older version there was a sort option without having to right click a directory.
