### ISSUE TITLE
Non strikethrough checkboxes

### ISSUE THREAD

**Issue by davidoskky** [Zettlr/Zettlr#3405]
### Description

Right now in Zettlr you can have unchecked and checked checkboxes.
These can be defined in two different ways: ``- [x]`` and ``* [x]``
When the checkbox is checked, the text on that line is rendered as strikethrough.
There is no way to disable the strikethrough rendering, you cannot prepend ~~ to the text or to the checkbox to remove it.

A checkbox can represent an action; if it's unchecked the action hasn't been completed yet, if it is checked it has been completed. In this case the strikethrough is perfect, since you're not interested anymore in what has been completed.
A checkbox however can also represent the presence of something, specially if rendered with an X rather than a tick. In this case the checked items represent what is present and the unchecked items what isn't. In this case the strikethrough over checked items is not appropriate, since it is useful to know what is present in order to easily read it.

### Proposed Changes

I propose to introduce a way to have checked checkboxes rendered without strikethrough.
I believe this should be defined within the file, on a checkbox by checkbox basis and not at a global level.

I believe this could be accomplished in 3 ways, even though none of this is standard markdown. It has to be noted that rendering strikethrough text after checked checkboxes is also not standard markdown.
1. ``~ [x]`` This is the best option in my opinion: the definition of the checkbox stays the same, you just modify the - or * to indicate non strikethrough
2. ``~~- [x]``
3. ``- [x] ~~``

### Caveats

This is not standard markdown

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

**Comment by davidoskky** [comment]
@nathanlesage this is by no means urgent; but is it something you will ever address?

**Comment by nathanlesage** [comment]
Sorry for letting this wait for over four months-- my apologies.

> There is no way to disable the strikethrough rendering, you cannot prepend ~~ to the text or to the checkbox to remove it.

Yes there is a way: use custom CSS. The strikethrough styling has been added because most people use checkboxes as todo lists, but it's fairly straightforward to remove the strikethrough with custom CSS. Have a look at the English documentation, there's a guide!

**Comment by lxwulf** [comment]
> Sorry for letting this wait for over four months-- my apologies.
> 
> > There is no way to disable the strikethrough rendering, you cannot prepend ~~ to the text or to the checkbox to remove it.
> 
> Yes there is a way: use custom CSS. The strikethrough styling has been added because most people use checkboxes as todo lists, but it's fairly straightforward to remove the strikethrough with custom CSS. Have a look at the English documentation, there's a guide!

Sorry to bother you, but can you say where this is mentioned in the documentation? So is there an example or something else? I just found the section to apply custom CSS with a few other examples but no example or guide for the checkbox strike through. 

How and can I apply this per markdown file because I use checkboxes in different ways but also as to-do list, I don't want to have it activated always.

> In my installation the strikethrough of checkboxes are not present somehow...
