### ISSUE TITLE
(minor) cursor placed wrong after selecting citation with @-syntax

### ISSUE THREAD

**Issue by leo-hstone** [Zettlr/Zettlr#3435]
### Description

If you place a `[[link]]` and press enter/tab during the slection drop-down, the cursor is placed at the end, ready to type further.

If you place a `[@citation]` and press enter/tab during the selection drop-down, the cursor is placed inside the brackets.

Just a minor quality-of-life issuem but reported to keep track of😃 

### Reproducing

See above.

### Zettlr Version

Nightly

### Specify version

2.2.5 - nightly 20220418

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
That is actually intended behavior, since the square-brackets-citations are oftentimes used to also add page ranges afterwards. You are much better off just writing the citation without the square brackets if you're frequently citing without page ranges or anything else!

You can choose the most-used citation style that the autocompletion uses in the preferences!
