### ISSUE TITLE
[Bug] next and previous buttons not working

### ISSUE THREAD

**Issue by hxh970412** [Zettlr/Zettlr#3438]
### Description

When we developed the custom toolbar, we found that the next and previous buttons would not work normally in Linux and MacOS. they require two clicks like the gif in Reproducing.

### Reproducing

![May-01-2022 23-53-25](https://user-images.githubusercontent.com/31640026/166206448-5f81af1e-3353-4e34-880c-6382975ef960.gif)

### Zettlr Version

Stable (most recent version)

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Debian, MacOS

**Comment by nathanlesage** [comment]
Would you mind having a look into the logs, because the handler seems to have thrown an error which we can use to isolate the issue?

**Comment by EdgarTang** [comment]
I check all of the four types logs(Verbose, Info, Warning, Error). There is no any new log when I click the previous/next button.

The bug only happens when you first time switch the files.
For example. 
If you restart Zettlr, previous/next button can do nothing now.
We call the first file opened is `file A`(This file is the last opened file from the last time Zettlr closed).
Now you click another `file B`, then if you click the `previous button` should switch to the previous file which is `file A`.
But it does not work.
Now you click another `file C`, then if you click the `previous button` can switch to the previous file which is `file B`.
If you click `previous button` again, file can not switch to previous file which is `file C`.

So this just seems like an irrelevant question. Only the first file switch after Zettlr is opened is not recorded (I guess because the default open `file A` is not manually opened by the user).

We check these visions: 
1. macOS Version 2.2.5 (2.2.5) download from Zettlr website.
2. Windows and Debian download from Zettlr website.
3. Developer branch on macOS, Debian, and Windows.

**Comment by hxh970412** [comment]
> 
This is what I got when the button doesn't work
![image](https://user-images.githubusercontent.com/31640026/166479389-2ae57df8-9c80-46a6-ae7f-b1481c885e53.png)

**Comment by nathanlesage** [comment]
This is fixed in the current develop branch and comes with Zettlr 3.0
