### ISSUE TITLE
Typing in custom CSS editor automatically scrolls up

### ISSUE THREAD

**Issue by kyaso** [Zettlr/Zettlr#3439]
### Description

Whenever you start typing in the custom.css editor, it automatically scrolls the view up. The line you are editing is then still visible, just way at the bottom of the viewport.

### Reproducing

1. Open Custom CSS editor
2. Make sure there is enough content so that the editor is scrollable
3. Scroll down a bit
4. Place the cursor somewhere at the top/middle of the viewport
5. Start typing
-> Scroll up should happen

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.5

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Linux manjaro 5.14.21-2-MANJARO

**Comment by lillemets** [comment]
Probably related to this is that often after saving, the cursor is not related to text anymore. It can end up between lines and when then typing, the input goes to a seemingly random place in text.

**Comment by nathanlesage** [comment]
Can confirm on 2.2.6 on macOS. It only happens on keypresses, so there might be some scrollspy attached to that. It's probably an interaction effect, I can have a look at some point (or someone else!)

**Comment by nathanlesage** [comment]
I was wrong! I just had a look at what listeners fire when one presses a key, and I found the bug: It's caused by the editor's value being updated, triggering an update of Vue's `modelValue` which in turn triggers a `setValue` in the editor, which finally makes the view jump.

Fixed it with a simple check whether `modelValue` and what `getValue()` returns are actually different.
