### ISSUE TITLE
Table content not saved

### ISSUE THREAD

**Issue by bhigy** [Zettlr/Zettlr#3449]
### Description

Sometimes, changes I make to a table are not saved. Even stranger, some changes I made to a table before editing a paragraph following the table were not saved but the edits to the paragraph were saved.

### Reproducing

* Create a new note
* Add
```
# Title

|A|B|
|---|---|
|a|b|
```
* Save
* change `b` to `c` in the last cell
* [OPTIONAL] Add some text after the table
* Save
* Close Zettlr and open again.

=> The change to the table has not been saved (while the optional text is).

### Zettlr Version

Stable (most recent version)

### Specify version

2.2.5

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 22.4

**Comment by jothanne** [comment]
The same behaviour here  - still present in version 2.2.6 (on Windows 10). Seems that leaving the table by clicking elsewhere outside the table doesn't trigger the file-changed-flag (*). As a workaround you can switch from the last edited table cell to another one using the arrow keys or [Ctrl]+[Tab] **on the keyboard** - clicking the cell with the mouse doesn't help here.

**Comment by nathanlesage** [comment]
This is a direct effect from a bug report we had. The problem was back then that Zettlr would completely overwrite sometimes large part of one document if you were editing a table in one document and then _without clicking outside the table again_ immediately switch tabs. Therefore I constrained the overwriting abilities of the Table Editor, to the detriment that now **whenever you edit anything within the table, you have to click into another table cell first to have the changes be applied to the document.**

I am aware that this is far from ideal, but I haven't had the time to figure out a robust fix for that issue yet, and I'm not sure when I will have the time and mental capacity to do so :(

If someone else wants to give it a shot, as always: Please feel free to open a PR :)

**Comment by radifar** [comment]
So I have experienced the same issue. Interestingly enough, there is a save button on the table. So it turns out (for me, Zettr 2.3.0 nightly builds on Fedora 36) clicking outside the table then save not going to save the table content. And what I need to do to make sure it works is by clicking the save button on the top of the table every time I make the change.

**Comment by nathanlesage** [comment]
Exactly, that save button is a new addition because it makes the "When are changes actually persisted?" more transparent. Still not the ideal solution, but at least transparent.

**Comment by nathanlesage** [comment]
I'm gonna stick with this solution for now.

**Comment by LKirst** [comment]
I have the same issue on Windows and with Zettlr v2.3.0. Changes to my tables are not saved when I press Ctrl + S.
I couldn't find the save button on top of the table @nathanlesage uses.

**Comment by nathanlesage** [comment]
> I couldn't find the save button on top of the table @radifar uses.

@LKirst This button is only available in the current betas.

**Comment by nathanlesage** [comment]
> I couldn't find the save button on top of the table @radifar uses.

@LKirst This button is only available in the current betas.

**Comment by LKirst** [comment]
Thank you! Then, I'll upgrade to a beta release. 👍
