### ISSUE TITLE
Italian dictionary loading problem 

### ISSUE THREAD

**Issue by Enrico68** [Zettlr/Zettlr#3451]
### Description

Is the problem with the Italian and Portuguese dictionaries resolved ? I saw that the [issue1022](https://github.com/Zettlr/Zettlr/issues/1022) was closed. Still, I cannot load Italian dict. Any chance will be fixed in the near future ? 

### Reproducing

Making the `it` directory and moving  `index.aiff` and  `index.dic `files inside. 

### Zettlr Version

Stable (most recent version)

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

osx Catalina

**Comment by nathanlesage** [comment]
This is out of scope for Zettlr, we rely on nspell for this, which has this problem: https://github.com/wooorm/nspell

**Comment by nathanlesage** [comment]
Closing this to keep the issue tracker clean. The issue will not be forgotten, I am actively thinking about good alternatives.

**Comment by davef-gh** [comment]
Please correct me and accept my apologies if this is not the proper way to report my problem.

I am failing to get Zettlr to use the standard hunspell italian dictionary.

I have succeeded in getting Zettlr to use the standard hunspell french and spanish dictionaries.

So it would appear that I am putting the correct files in the correct folder 

/home/uname/.config/Zettlr/dict/it_IT/it_IT.aff
and 
/home/uname/.config/Zettlr/dict/it_IT/it_IT.dic

I also tried the alternate folder name /home/my-uname/.config/Zettlr/dict/it instead of /home/uname/.config/Zettlr/dict/it_IT — just in case

In neither case does italian appear in the list of available languages for spell checking.

Incidentally, I see no flag/language icon in the bottom status bar  — with documents of any language.

**Comment by nathanlesage** [comment]
Please open a new issue with your problem description. Old issues shall be left to rest, because oftentimes old context is no longer relevant. Thanks!
