### ISSUE TITLE
Blocquote issue

### ISSUE THREAD

**Issue by samarulmeu** [Zettlr/Zettlr#346]
I discoverd that using `Blockquote` from the formatting menu has a strange behaviour when the first character of the paragraph is `*` (an italic or bold format). It deletes the `*`. If you use `_` this doesn't happen.

**Comment by nathanlesage** [comment]
Yep, Blockquotes are internally treated as lists (because there is the Markdown-writing-style to use single line breaks instead of the soft-wrapping functionality, in which case you'd want the next line to be preceded by a `>`-sign as well). Internally, the list command simply takes the character you'd like, removes a potential list item and thereby replaces it.

It's necessary because only by this you could make a numbered list out of bullet points or vice-versa! Nevertheless, I should probably have a look at the regular expression detecting lists to make sure the asterisk is followed by a space!

**Comment by nathanlesage** [comment]
Was a mistake in the regular expression, which counted `*some text` just as a bullet point list as `* some text` would have been. The shortcuts are designed so that the block _changes_ (instead of just adding the new formatting mark), i.e. if you have a header, the header formatting characters would be removed and replaced by the `>`-sign. This caused the asterisk to be exchanged with the `>`, even though it is not a correct list according to the Markdown standard. It'll come with the next patch!

It was literally one character :D
