### ISSUE TITLE
[request to contribute] Adding Touch Bar menu

### ISSUE THREAD

**Issue by warpcut** [Zettlr/Zettlr#351]
## Description
Hi, I'm using zettlr and i love it, i'm using it on my MacBook Pro with touch bar and I would love to add one functionality for it, basically the text format menu .
If it's ok for you i'll do it. I have already seen that electron is fully compatible with it.
If you give me the ok, i would also like to know where you wish me to work, in a new file or in a particular file already present in the repo.

TY, Marco.

## Platform
 - OS: macOs
 - OS Version: 10.14.6
 - Zettlr Version [e.g. 1.4]

**Comment by nathanlesage** [comment]
Hey Marco,

surely. I can't implement the TouchbarMenu, because I have the standard line with F-keys. Nevertheless, we would need to flesh out the way that menu is done, because there's a lot to think about (what is ergonomically sound? What fits into the general design idea and philosophy of Zettlr? How should it behave in different contexts? etc…)

So eventually, I'd like this issue be discussed on the forums before actually beginning the work! This way, everyone would have a chance to contribute ideas.

Last but not least, it would require an additional module that is loaded in the app, so from a purely programming perspective, what would be great is if you could develop the base code for the TouchbarMenu and implement some sort of API that I could provide from within the rest of the app, because it certainly needs some information from the renderer process which needs to be processed, etc. pp. This base module could be developed during the talks on the forums, because this code will be needed independent of the contents of the TouchbarMenu.

It's actually a lot of work, but I really welcome your idea, which will make the app **a lot** better for many people using a Touchbar MacBook! I'll help wherever I can! :)

***

Here's what I think _might_ be appropriate (but please give your input, as I haven't dived to deep into the intrinsics of the Touchbar):

1. Conceptualise it as a service provider, as it seems to fit into that category (service providers are located in `source/main/providers`). It runs everytime and needs to update frequently
2. Load it in the main class during app boot
3. The service provider needs some input interface where other parts of the app can trigger different functionality (the question would be: what — which is to be discussed)
4. Additionally, it needs an output interface, where it can trigger actions within the app. This could probably be done through the app commands (located in `source/main/commands`), but I'm not sure.
5. The TouchbarMenu, if I understand the concept correctly, mainly correlates to the GUI, and _not_ the main process, right? Because it supplements the user interface, not only the inner workings of the app? Then a lot of changes would be actually required in the Renderer process to capture everything that's happening.

One potential use of the Touchbar I could think of would be a replica of the Toolbar? Maybe this could be a first design study …? I'm not sure, you do have a Touchbar, so you know best what might work and what not. But enough words — I would like to invite you to open up the corresponding issue in the forum and I would then disseminate the topic via Twitter so that other people get engaged!

**Comment by nathanlesage** [comment]
… the formatting menu (just saw that you specified that in your post, it's late, sorry :D) could be a context-sensitive action, for instance, when the text editor is active.

**Comment by warpcut** [comment]
Thanks, I'll create the post on the forum soon so we can start sharing ideas.
It might take a while because i'm actually new to Electron so i have to understand where and how things goes in a complex project like this.

As example (working on a basic program) i think that something like this might work for our case.
![menu](https://user-images.githubusercontent.com/17721684/66440993-56af3500-ea35-11e9-8161-4018c5f3ad15.jpeg)
![formatting](https://user-images.githubusercontent.com/17721684/66440995-5747cb80-ea35-11e9-91ba-7f0523f95930.jpeg)

**Comment by nathanlesage** [comment]
Yeah, something like this! :)

I think that the Electron Touchbar API also supports icons (would look nicer that way!)

I also found this handy thing so I could cross-check: https://github.com/sindresorhus/touch-bar-simulator

Anyways, here's the corresponding documentation: https://electronjs.org/docs/api/touch-bar!

**Comment by warpcut** [comment]
I'm still not able to publish on the forum, I think I need to be manually accepted.

Can I ask how can I call from my module the function that the formatting menu does? It's just for testing right now because I managed how to attach the touch bar to the main window and it works, but I can't figure out which functions to call.

**Comment by nathanlesage** [comment]
Whoops, yes, I haven't been on the forum for some time. I just accepted you!

**Comment by warpcut** [comment]
Here the link to the thread:
https://forum.zettlr.com/discussion/57/discusson-about-macbook-pro-touch-bar-implementation/p1?new=1

**Comment by nathanlesage** [comment]
Just wanted to let you know I've posted a comment on your commits so far (I don't know which things GitHub shows and which not): https://github.com/warpcut/Zettlr-bar/commit/e12ba3d02939b82de0cb913736064289dbadaaf3

Really appreciate your work so far and I think it's really a good addition :)

**Comment by warpcut** [comment]
Yep, I've seen, I had no time last week because I had my graduation, I'll read it carefully this evening.

**Comment by nathanlesage** [comment]
Ouh, then congratulations, of course! Take your time!

**Comment by warpcut** [comment]
Btw, I forgot to tell you that I'm working on a different branch in my fork, have a look here.
warpcut@82cbc30
