### ISSUE TITLE
Zettlr 1.4.2 does not work on Linux Mint

### ISSUE THREAD

**Issue by nyilasypeter** [Zettlr/Zettlr#355]
## Description
I installed Zettlr 1.4.2 on a Linux Mint system by the Debian package (where I previously had Zettlr 1.3). Zettlr starts, but most of it's functions are not working. E.g. I am unable to open any folder (Zettlr sais it is loaded, but nothing appears on the left). I am also unable to cerate a new file. I can open an existing markdown file (by simply clicking on it), it seems that I can edit it, but when I close Zettlr and reopen the same file all of my  edits are lost.

## Reproducing
I don't know how to reproduce it, it might be op.sys dependent?

## Expected behaviour
Normal working behaviour.
Since I used Zettlr 1.3 happily before upgrading to 1.4, it would be ok for me to downgrade to 1.3, but I can't download the old version...

**Screenshots**

## Platform
 - OS: Linux Mint
 - OS Version: Linux Mint 18 Sarah
 - Zettlr Version: 1.4.2
 - Screen Resolution [only necessary if the bug is relating to the GUI]

**Comment by carlocastoldi** [comment]
Might be #343 
Try to open `./config/zettlr/config.json` and set the `openPaths` to `[]` (so that it looks like this `"openPaths": []`), then open a directory that has no more than 8 nested folders inside.
Electron v6 have problems handling complex object such as complex directories

If you REALLY need to open complex folders i suggest you to try downgrading to 1.3.0, but before doing so i exhort you to think again if you really need to open such a big directory

**Comment by nathanlesage** [comment]
Did it work?

**Comment by nyilasypeter** [comment]
Thanks. It solved the problem. 
However I do need folders which contain more than 8 subfolders, so I just downgraded to 1.3. That's fine. Is a fix in Electron expected?

**Comment by nathanlesage** [comment]
> Is a fix in Electron expected?

There is a pull request on their repository, iirc, but I'm not sure. But they're aware that something bad happens there!

**Comment by nathanlesage** [comment]
Closing as another issue with a better title is also open.
