### ISSUE TITLE
Feature request: Option to remove separation by subfolders and make Zettlr recognize double # tags

### ISSUE THREAD

**Issue by Shandi97** [Zettlr/Zettlr#36]
Hi. I've recently started working on implementing a zettelkasten system and discovered your app a few weeks ago been indecisive on what to use but this is pretty much what I've been looking for.

Though there are two issues that while not game-breaking are bit annoying for my zettelkasten workflow.

The first and the main one is a problem with file sorting and subfolders. I am a noob so maybe I just missed something, but while we can sort files   #4  now they are still nested under subfolders if there are any. I use timestamps like 20181001174801 in file names for sorting purposes and for ID purposes. 

The problem is that if I have notes "2017" "2018" "2019" "2020" "2021" (with 2019 and 2020 in a subfolder) it looks like this

"**Folder**"

"2017"  
"2018"  
"2021"

"**Subfolder**"

"2019"  
"2020"

I want all notes in all subfolders of a given folder be in a single list so that I can fully use the sorting by timestamps. It would be nice if there was a setting for preview pane to list just the files and sort them as if there weren't subfolders.

It seems to be possible to work around this with virtual directories though it would be nice if it weren't necessary. Using this method would also be quite hassle with larger number of files, there doesn't seem to be a way to select multiple files at once, or maybe again I am a noob and just missed something.

The second lesser issue is with tags. Since you are familiar zettelkasten you may have seen some people use tags like ##sometag instead of #sometag for overview notes and special stuff.

The way it is now Zettlr will recognize a tag but it will ignore the first hashtag so this is the result #**#sometag**. You can get around this by putting the whole thing in global search but It would be good if Zettlr recognized these tags, these tags should othewise act like normal tags.

On another note I just want to say that I've tested the app 10 000 dummy md files (in a single folder) and it worked quite good did the same with 20 000 still worked quite good, today I tested it with 30 000 and searched for "the" in every file and while of course it did take some time it worked.

I've tested up to 20 000 QOwnNotes Atom, VSCode and Rene's sublimeless Zk.

Zettlr and QOwnNotes seemed to have best perfomance (though it took a little while for QOwnNotes to launch with that many files it ran smooth afterwards) similar with Zettlr at 30 000.

**Comment by nathanlesage** [comment]
Hey,

concerning the subfolders: I don't think that this would be wise, out of two reasons.

First, it is common practice to use tags to sort files, and not folders. Indeed, it is common to use folders only for _really_ coarse sorting, and use tags for a more finegrained categorising. It definitely is different to what we're used to, but with the possibilities of modern apps it is indeed better and more flexible. The second reason is that—albeit Zettlr tries to display your disk contents in a more feasible way than your file system does—I think it shouldn't go too far. While filtering out some files doesn't change the _structure_ of the actual situation on your disk, filtering out subdirectories would be. Zettlr should not divert from the structure present on disk, because this way you would most certainly get confused at some point, because you wouldn't be able to tell _where_ a new file will reside. It should always be clear to say how an app will behave from the mere looks of it.

Therefore I'm asking whether or not you might get well along without your subfolder structure? Or, in other words: what is the function of your subfolder structure inside your Zettelkasten? I only know of Zettelkästen not reliant on subfolders.

> […] there doesn't seem to be a way to select multiple files at once, or maybe again I am a noob and just missed something.

Don't worry, you're not a noob, you are correct — currently there is no possibility to select multiple files at once. I didn't find it necessary to implement yet. Also, there's still the shortcut of simply dragging the files using your file browser, because then Zettlr would detect the changes and re-read the affected directories.

Concerning the tags: Shouldn't pose a problem to accept hash characters inside tags, I only think that forcing you to keep tagging rather simple (by only allowing letters, numbers, - and _) prevents you from experimenting too much with fancy stuff. I've found it quite focus-improving to prevent myself from having too many options. But if you'll need it, it can be implemented. The only question I have is: How does using doublehash-tags improve the overview over your Zettelkasten? I mean, we still have the internal link feature for outline notes …?

And concerning your testing: First, thank you very much for testing so many files. I've only done this irregularly, and I am pleased to hear that Zettlr works well with that large number of files! Can you tell me _how_ laggy the app felt, especially with 30k files? I'm very interested in hearing a more detailed report on your testing!

On a sidenote: You'll find the next version of Zettlr quite intriguing, as the "@ID:"-affix is not necessary anymore. It has been a crutch from the beginning and I finally found time to remove it. Additionally, the ID generator can now be customised to your needs.

Cheers!

**Comment by Shandi97** [comment]
Alright, sorry to keep you waiting.

The files that I used were taken from [here](https://github.com/Zettelkasten-Method/10000-markdown-files), with additional files being just duplicates.

I've decided to do the tests again, nothing thorough just quick simple tests like before.

I did these tests with the UK and US english dictionaries on.

With 10 000 files there seemed to be no problems. Of course searching took some time, that includes links and tags but it was smooth. Not much lagging. 

At 20 000 it starts to be felt more but app runs smoothly. Search of course takes some time but seems smooth, at least largely. When creating new files there may be bit of a lag but its generally around 1 second maybe 2 at worst.  
When creating virtual directiories there is more lagging maybe 10 seconds. When moving files into VD it takes couple seconds (5 more or less).

I did the VD test also in another simillar directory to the previous, except this one had a subfolder where half of the files went. The subfolders didn't seem to cause any problems beyond the aforementioned, whether it was VD or searching.

General lagging occurs irregularly but nothing too disruptive.

Now onto 30 000. Now its definitely felt but it seemed to remain usable. More lagging in general. Switching between files is less smooth doesn't go above 2 or 3 seconds.  
Opening the folder may take up to a minute but mine seemed to remain at around 30 or 40 seconds.

The subfolder test was also done here except now there was one more. I also tried to use VD with files from both the main and subfolders like previously. Initially successful but I ended up getting whitescreened by the app. Same happened on my second try.

NOTE: The VD tests were done only with couple of files not more than 4.

> The only question I have is: How does using doublehash-tags improve the overview over your Zettelkasten? I mean, we still have the internal link feature for outline notes …?

The overview notes get tagged too. The ## tags are meant to be quick and clear shortcut to these notes though they are not meant to be limited to just that. In general they are meant for priority stuff. I am still working on figuring things out I don't even have zettelkasten now I've just recently started with the whole thing and I am right now working on my first set of notes. I encountered it on zettelkasten site I like it so I decided to try to incorporate it.

The other reason why I want that capability is because Rene's sublimeless ZK supports that so its nice if things work elsewhere too. Not using his app now (maybe after verson 1.0 comes out) but I keep it as backup plan.

> Therefore I'm asking whether or not you might get well along without your subfolder structure? Or, in other words: what is the function of your subfolder structure inside your Zettelkasten? I only know of Zettelkästen not reliant on subfolders.

You are right. Frankly I don't even really want to use the folders, I am well aware that for zettelkasten you are not suppossed to use subfolders. I didn't want to use them for sorting not really which is why I wanted the capability to ignore the subfolders. QOwnotes can do that so thats where I got the idea.

I got paranoid about file numbers and perfomance issues (yes I know its waaay too soon) so I thought to mitigate that a little with subfolders. the subfolders only provided small perfomance boost and that was in QOwnNotes, Zettlr had all around better perfomance so there wasn't even much room to notice any improvement, so it ended up not being all that helpful in the end.

Though like I said its not some gamebreaking feature, just my irrational fixation. So I guess I am abandoning the subfolder scheme.

I kinda have a bad habit of getting paranoid about far off future. A system like zettelkasten is bound to make it act up since its meant to be a longterm storehouse of your knowledge and thinking companion.

The only thing that matters in the end is going to be the performance. So thats the thing to focus on, if it doesn't improve the performance then its of no use for me.


Alright, thats all for now, kept procrastinating on writing this (also late so may be incoherent and with mistakes) , so I hope this is somewhat helpful.

**Comment by nathanlesage** [comment]
Alright, I just added hash-characters to the list of allowed tag-chars, so here you go! :)

**Comment by nathanlesage** [comment]
Yes, they will be treated as different tags. Basically, the system searches for `#`-characters followed by either a letter, a number, `-`, `_` or -- this is new -- `#`. So internally, the system will recognize as tags everything that gets highlighted, minus the first hash character. I.e.:

* What you write -> What you get
* `#sometag` -> `sometag`
* `##sometag` -> `#sometag`
* `#sometag#` -> `sometag#`
