### ISSUE TITLE
Cannot open Preferences

### ISSUE THREAD

**Issue by cliffr39** [Zettlr/Zettlr#3622]
### Description

Going File --> Preferences --> Preferences does not open. 
Clicking on the cog icon does not access either.
Going Help --> About Zettlr does nothing

### Reproducing

Going File --> Preferences --> Preferences does not open. 
Clicking on the cog icon does not access either.
Going Help --> About Zettlr does nothing

### Zettlr Version

Stable (most recent version)

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

AlmaLinux 9

### Additional Information

Tried the .rpm and the .appimage versions and same result, cannot access settings/preferences or about page.

**Comment by ramseyazad** [comment]
I am experiencing this issue also.  I have found a workaround for myself tho.  This is for windows, whatever the latest version is as of aug 2022.  I noticed that the task bar did show that the preferences bar was open, but I could not navigate to it.  because I have 2 monitors, I wondered if this was in any related, so I changed my desktop display settings.  It looked like, for whatever reason, zettlr's preferences dialogue opened on a 3rd monitor which doesn't exist, so I changed the settings to clone the desktop instead of extend the desktop.  I can access the preferences this way but it is quite awkward, and I certainly hope it gets fixed!
