### ISSUE TITLE
All-text footnote anchor not recognized as footnote anchor

### ISSUE THREAD

**Issue by dajare** [Zettlr/Zettlr#364]
## Description

If I use a footnote anchor made up of all alpha characters, like `[^abcd]`, then Zettlr does not recognize it as an anchor (and its "reference text" is not found), but seems to see it as a mis-spelled word. however, as soon as a digit is included, like `[^abc1]`, then Zettlr behaves as expected.

## Reproducing

Try including footnote reference + text as above.

## Expected behaviour

I expect *anything* using the syntax `[^alphadigi]` to be recognized as a footnote anchor.

**Screenshots**

These screenshots illustrate the behaviour as I see it:

(1) **ALPHA ONLY**

![note-not-found](https://user-images.githubusercontent.com/40625/66834792-3cee8000-ef56-11e9-8ac6-ff30b71f001c.png)

(2) **DIGIT INCLUDED**

![note-found](https://user-images.githubusercontent.com/40625/66834818-48da4200-ef56-11e9-9f92-0c058ae2167c.png)

## Platform
 - OS: Ubuntu
 - OS Version: 18.04 LTS
 - Zettlr Version: 1.4.2

## Additional information

[This commenter][1] in issue #181 seems happy, so I'm not sure why this should be an issue for me!

[1]: https://github.com/Zettlr/Zettlr/issues/181#issuecomment-490429147

**Comment by nathanlesage** [comment]
Interesting, from the pure looks at it, it should work:

https://github.com/Zettlr/Zettlr/blob/9778467c3130961ba897f0d9d252b21cc40a348f/source/renderer/zettlr-editor.js#L769

I'll have a look later this month.

**Comment by dajare** [comment]
Thanks, @nathanlesage - appreciated! I took a look at that line of code, and then went back to my file. With that in mind, I did a bit more checking:

- *If* I **turn off** the UK English spellchecker, *then* Zettlr's footnote display etc. works perfectly.
- *If* I turn **on** the US English spellcheck,  *then* Zettlr's footnote display etc. **also** works perfectly!
- *If* I use both English spellcheckers together, then Zettlr works perfectly.
- BUT *if* I use the UK spellcheck alone, then the footnote reference + text cannot be found.

I need to re-start Zettlr to see the full effects of changing the spellchecker settings.

So -- with NO spellcheck, or using UK *and* another dictionary, everything is fine. But using the UK spellcheck on its own means the fnRef is not found.

The problem appears to be with the UK spellchecker, then! I hope this is some help ... and for a work-around, I'll keep the US spellcheck on! ;)

**Comment by nathanlesage** [comment]
Aaaaaaaaah. No, the problem doesn't lie with the spellchecking _per se_, if I just got it right — but with the fact that "abcd" is not a valid word in most dictionaries, so Zettlr will apply a class to the footnote reference that indicates that the word is misspelled. And in that very function I also perform a check for the class of the element. So that means: If the word is detected as "correct" (which also applies to words with digits in them — these won't be checked) no class will be added, otherwise I think the class name will interfere with the function!

**Comment by nathanlesage** [comment]
I think this is actually the culprit, but I will need to have a look at this:

https://github.com/Zettlr/Zettlr/blob/9778467c3130961ba897f0d9d252b21cc40a348f/source/renderer/zettlr-editor.js#L420

**Comment by nathanlesage** [comment]
Done!

**Comment by dajare** [comment]
Uh oh! Has there been a regression? This issue has returned: now with v. 2.1.1 (under Ubuntu 18.04.06 LTS) I get this:

![zettlr-fn-issue](https://user-images.githubusercontent.com/40625/148535380-5f9deb07-cda1-41b4-b745-68e835a8413a.gif)

(Animated GIF, with 1.5sec delay + 5x loop) = "all alpha" footnote anchor is not recognized; but include a digit, and it is recognized.

**Comment by nathanlesage** [comment]
Grrr 😡 Taking a look at that

**Comment by kyaso** [comment]
@dajare @Wendell250 Does it also happen when you separate each footnote using a _newline_, like so?:
```
See [^abc]. Also refer [^xyz].

[^abc]: foo

[^xyz]: bar
```

@nathanlesage Could it be that whether the anchor name contains a number or not, doesn't matter at all? (because the example above works fine; only when the footnotes are not separated by a new line, I also see the behavior described in this issue)

**Comment by nathanlesage** [comment]
> Could it be that whether the anchor name contains a number or not, doesn't matter at all - and, instead, the linebreak is causing the issue?

That could in fact be. A few weeks ago I improved the footnote behavior so that you can also add multiple paragraphs (as stated in the Pandoc documentation). It could be that there is one check missing when a line begins with a footnote reference. Maybe I'm only checking for blank lines.

Relevant code: https://github.com/Zettlr/Zettlr/blob/develop/source/common/modules/markdown-editor/hooks/footnotes.ts#L86

**Comment by Wendell250** [comment]
> @Wendell250 Does it also happen when you separate each footnote using a _newline_, like so?:

Yes, separating footnotes with newlines fixes the issue!

![footnotes](https://user-images.githubusercontent.com/90041836/150657063-6426adb5-526b-447a-9368-d09e8267c707.gif)
