### ISSUE TITLE
zettlr slow - not usable anymore? 

### ISSUE THREAD

**Issue by ptbeck** [Zettlr/Zettlr#3668]
### Description

My database consists of 3064 md-files organized in some sub directories. 
Zettlr started I click to open one of these directories. Nothing seems to happen at first (for the nex half an hour). 
Then after 32 minutes has opened the files. 
Strangely enough not only the sub directory I clicked, but all of them. 

To insert Text: writing a sentence or two. Nothing shows up. The text appears only after 35 - 45 seconds. (Also in short articles of perhaps 100 words. 
To insert some words from the clipboard: 6 seconds to appear in Zettlr.

To open a file from the directory on the left: it takes 6 seconds to show up. 

### Reproducing

Happens every time I try to use Zettlr by now. 

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0 x64

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows10 

### Additional Information

Ryzen 7; 16 GB RAM; HP Envy

**Comment by ptbeck** [comment]
Temporary solution: 
Meanwhile I downgraded to version 2.2.3 
Everything smooth and fluently now. Database loads in less than 4 minutes (instead of 32 minutes). Writing appears instantly.

**Comment by nathanlesage** [comment]
With 3000 files loading shouldn't be taking 30 minutes. Your CPU and RAM are definitely not the problem here. And if downgrading improves loading this indicates that it's some interplay between Zettlr and your system.

The first step would be to look at the logs. Zettlr always logs how long it takes for it to parse the files when you launch the app. If that number is in the minutes, this would be an indication that maybe the drive you're using is very slow. For example, if you have a home server and a very slow LAN connection between that and your computer. Or any network share, generally. Could that be it?

**Comment by nathanlesage** [comment]
Closing as unattended and very likely solved during the development phase since summer
