### ISSUE TITLE
Linux System Theme

### ISSUE THREAD

**Issue by tio-trom** [Zettlr/Zettlr#3682]
### Description

Linux is well known for letting users customize their desktop wildly. So the lack of support for accepting the system's theme is quite surprising.

### Proposed Changes

Enable the system theme for Zettlr.

### Caveats

I do not see any.

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Stable (most recent version)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

**Comment by nathanlesage** [comment]
That's unfortunately impossible since Zettlr has to render elements using web technologies and cannot rely on UI libraries that would do the work for us, ergo: we's have to implement every border, every gradient manually in CSS, multiplied by every possible theme.

However, you can customize Zettlr's looks using Custom CSS so that it matches your expectations. Have a look here: https://docs.zettlr.com/en

**Comment by tio-trom** [comment]
Ok but I wonder how does it for windows and macos. I see such a feature is supported for those systems. Also, theming happens at the system's level right? The app devs do not have to manually edit everything for every Linux theme. Linux can theme GTK and QT apps.

**Comment by nathanlesage** [comment]
On Windows and macOS you just have one way how GUI elements can be displayed, and I painstakingly did all of that in CSS. On Linux, since you have so many different styles, I oriented myself at the GNOME design guidelines.

To reiterate: Zettlr is not a GTK app, its graphical user interface is a website, and no Linux operating system can style a website.
