### ISSUE TITLE
Feature: Option to reload files

### ISSUE THREAD

**Issue by dmlemos** [Zettlr/Zettlr#37]
Sometimes a file gets changed and Zettlr doesn't detect it. Would be cool to have an option to reload files.

**Comment by nathanlesage** [comment]
Should pose no problem to implement. Yet, can you give me specifics on when and why Zettlr doesn't detect some file changes?

**Comment by dmlemos** [comment]
This happened after doing a rebase in git. It detected that the file changed in the middle of the rebase, but after rebase was done it was still showing the old version.

**Comment by nathanlesage** [comment]
Thanks for your quick response!

Indeed, if a file is changed multiple times in a very short amount of time, the package `chokidar` I am using is combining several changes into one single event, and Zettlr therefore only detects one event out of many.

Having said this, you have two options:

1.) Keep the "Do you want to reload the file in editor?"-window open until the rebase (or any other process that keeps changing the file for some time) is completed. If you _then_ choose "Yes", it will simply replace the editor with the newest version. If you choose the option _before_ your process has finished, it may very well be that Zettlr doesn't get the last change right.

2.) Simply select another file and then re-select your old file. Zettlr does not keep your files in memory, but re-reads them everytime you open them. Therefore, by re-selecting the affected file, it will be read in its newest version by the app.

I don't think, a "reload"-option is necessary, therefore, because it unnecessary complicates the app without any benefit (pressing, e.g., `F5` versus re-selecting the file is not so much of a difference). If you happen to have this problem on a common basis, please object. Otherwise, I'll close this issue.
