### ISSUE TITLE
Zettlr compatible iPhone (iOS) App?

### ISSUE THREAD

**Issue by exislow** [Zettlr/Zettlr#3739]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [X] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [X] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

I love Zettlr -- really nice project! I would love to use the notes I have created with Zettlr on my iPhone as well. As far as I know there is no Zettlr version for iOS. I was wondering if somebody can recommend any reasonable iOS app which is compatible with the Zettlr file / form structure, so my notes do not get messed up.

**Comment by wideaperture** [comment]
I use [1Writer](https://1writerapp.com/) for this purpose, but lots of iOS markdown apps will work. Since Zettlr projects are just folders of plaintext files on your computer, it's pretty simple to set up syncing with a mobile device. Just install the desktop client for whatever cloud sync service you prefer — Dropbox, Box, Google Drive for Desktop, OneDrive, etc. — and place your Zettlr folders/files inside whichever directory is set to sync to the cloud.

For example, I'm using Dropbox to sync my notes, so I put the Zettlr projects that I want to sync inside `~/Dropbox`. Since 1Writer has Dropbox integration, all my Zettlr notes are available from within the 1Writer mobile app. Any notes I add or any changes I make to existing notes via 1Writer automatically appear in Zettlr and vice versa thanks to Dropbox. It's all pretty seamless.

There are, of course, a few caveats:

* Writing stats only reflect stuff that's typed directly into Zettlr. So any notes you create or writing you do on the mobile app won't show up in the word totals shown in Zettlr's stats window.

* Other Zettlr features, like generating and auto-suggesting permanent links, Zotero integration, snippets, custom CSS, etc. won't be available from within whatever mobile app you're using. Any cites you've added will be shown as markup when viewed from within the mobile app, though they will, of course, continue to render correctly in Zettlr itself.

It'd obviously be lovely to have a bespoke Zettlr mobile app — the FAQ section of the docs says as much. But it also explains that there's not yet sufficient development help to make it a reality. Hopefully that will change at some point. In the meantime, I've appreciated that Zettlr's set up in such a way that a generic cloud sync can get you most of the functionality you'd want via third-party apps.

**Comment by nathanlesage** [comment]
> Hopefully that will change at some point.

Basically all it would need is a bunch of volunteers – no one of those would even need to code. A set of reliable beta-testers that can give me detailed feedback plus a few "official" community moderators who help users like in this case would already be a huge improvement for me :)

**Comment by exislow** [comment]
I will a have a look at 1Writer. Since Zettlr is Using Textbundle V2 I am curious if 1Writer is really able to understand this package format. 

@nathanlesage I would love to volunteer. Shall we plan some sort of kick-off? Plus side, I also know how to code. Maybe I can support / debug in a helpful way somehow.

**Comment by exislow** [comment]
@nathanlesage: Do you have any thoughts further about this?

**Comment by nathanlesage** [comment]
@exislow Right now, I don't want to start up any other apps, because Zettlr 3.0 is in the making. Once that is out, and once the basic features are in there for future-proofness, we can maybe talk more about that. Right now, the best way to help would be to fix bugs and in a soon future beta-test and review the Codemirror 6 upgrade PR, here: https://github.com/Zettlr/Zettlr/pull/3776
