### ISSUE TITLE
PortableApps version does not start because of unnecessary access to Onedrive/documents

### ISSUE THREAD

**Issue by HolgerAusB** [Zettlr/Zettlr#3784]
### Description

I am using Windows 11 with enabled: Ransomeware Protection > Controlled Folder Access.
When trying to start Zettlr from the PortableApps Menü, Windows raises a warning that `ZettlrPortable.exe` tried to access the controlled folder `%userprofile%\OneDrive\Documents` and the app does not start.

I don't think, that the portable version need to have access to this folder. So please change this misbehavior. Zettlr should only use the PortableApps-folders by standard.

Today was my very first try with Zettlr.

### Reproducing

Activate 'controlled folder access' in windows.
Start Zettlr-Portable

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0 portableApps

### Installation Method

Other (please specify below)

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windowws 11

**Comment by nathanlesage** [comment]
The PortableApps release is a third-party service with whom I do not have any communication. I do not know what they do to their binary, and hence cannot help out here. Please try to get in contact with them instead, they may be able to help you.

By default, Zettlr only needs access to its data directory and any workspace/file you open with it. There is a way to modify the genuine binary from our website/here on GitHub so that it becomes portable. Please refer to this guide: https://docs.zettlr.com/en/portable/

**Comment by nathanlesage** [comment]
Well, I mean I can make Zettlr log an error instead of breaking when copying the tutorial fails.

**Comment by HolgerAusB** [comment]
and/or doing an optional start parameter could also help:

```
-tutorial "E:\textdata"   # copy tutorial to given path
-tutorial ""              # don't copy/create any tutorial files
                          # missing '-tutorial' > copy to standardpath: users documents
```
of course, if it fails to write to (given) path, zettlr should log ang showing an info/warning window without breaking, as you suggested.

**Comment by nathanlesage** [comment]
I had a look yesterday, and I'm already catching the error, so apparently the app doesn't crash inasmuch as the operating system seems to force-quit the app when it attempts to access the file system in the first place. This is not something I could fix as this behavior is intransparent to the app itself.
