### ISSUE TITLE
Pandoc error when exporting

### ISSUE THREAD

**Issue by syveqc** [Zettlr/Zettlr#3786]
## Problem Description
When exporting (e.g. to HTML, but happens in most modes) any document I get the following error: 
```
Export Failed
An error occurred on export: pandoc: error while loading shared libraries: libHSciteproc-0.7-9FyW7CahaskDUKMYJtIrY6-ghc9.0.2.so: cannot open shared object file: No such file or directory

pandoc: error while loading shared libraries: libHSciteproc-0.7-9FyW7CahaskDUKMYJtIrY6-ghc9.0.2.so: cannot open shared object file: No such file or directory
```

Running `pandoc` externally works on the same files.

## Zettlr Version
I am using 2.3.0 freshly installed using pamac.

## Other information
Operating System: Manjaro Linux 22.0.0
pandoc version: 2.18

**Comment by nathanlesage** [comment]
I do not recognize pamac. Would you mind trying to install a version from the official website? Sometimes third-party repositories have some quirks, and the bundled pandoc should not be searching for a citeproc-library, as it is part of Pandoc. This very much sounds like an issue with the repository, rather than with Zettlr.

**Comment by syveqc** [comment]
pamac is a package manager for Manjaro (with AUR support). I did not find any easily installable version on the website, so I built v2.3.0 from source and you are right, everything works fine there, so the issue seems to be with the specific build from the repository and not Zettlr itself!
I am closing the issue, thank you!
