### ISSUE TITLE
Counter’s bug

### ISSUE THREAD

**Issue by Monolecte** [Zettlr/Zettlr#379]
## Description
Counter give same number for words and letters.

## Reproducing
Open a doc and see

## Expected behaviour
Words are not letters

**Screenshots**
![Espace de travail 1_801](https://user-images.githubusercontent.com/28186535/68084052-c7791f80-fe30-11e9-81a7-59f87b7195e6.png)

## Platform
 - OS: Ubuntu
 - OS Version LTS
 - Zettlr Version the last one 1.4.3

**Comment by nathanlesage** [comment]
Mh, it's not a problem with any messed up characters or variables … for me it shows the correct values.

Oh, wait a moment. Did you maybe accidentally switch on this particular setting?

![image](https://user-images.githubusercontent.com/17251683/68085067-f5fcf780-fe3c-11e9-8870-8e14779fd000.png)

Because then the "word" counter actually counts characters (which is correct for symbol-scripts such as Japanese or Chinese)!

**Comment by Monolecte** [comment]
Bingo!
Thanks, boss.

**Comment by nathanlesage** [comment]
:) Glad it worked! :)

**Comment by nathanlesage** [comment]
@GTUser123 Feel free to open a PR with that. (But please translate the comments to English so that people like me who cannot speak Mandarin know what's going on.)
