### ISSUE TITLE
Flatpak support

### ISSUE THREAD

**Issue by nam1962** [Zettlr/Zettlr#386]
Flatpak is a software utility for software deployment, package management, and application virtualization for Linux desktop computers.

https://flatpak.org/

Packaging with Flatpak would handle all Linux Distro, version, flavour problems

**Comment by nathanlesage** [comment]
Flatpak-support is currently out of the question, as are any other additional formats, because we are experiencing a highly problematic situation with the Windows installers, which have far higher priority. It may come one day, but only if the other problems are mitigated in a way that they are reliably. Sorry!

**Comment by nathanlesage** [comment]
Nota bene: If you really want Flatpak-support, you could, of course, pull the Zettlr repository (only the tagged master-trees, as they contain exactly what we ship), you could built Flatpaks yourself, which we could advertise on the official website. For more, see the FAQ: https://docs.zettlr.com/en/faq/#do-you-consider-supporting-more-linux-platforms-except-debian-and-fedora-based-ones
