### ISSUE TITLE
"Filter" box to search in files content

### ISSUE THREAD

**Issue by samjohn24** [Zettlr/Zettlr#3865]
### Description

Documentation is not clear about the behavior of the "Filter" box. If  I am not wrong, "Filter" behavior is to search:

- in the file and folder names
- in the titles, and
- in the file content if the word is a tag.

This behavior is ok, but doesn't work in the most of the cases where a quick look-up is required as either the filename is not related to the content or  it doesn't have a title or a tag inside.

Looking at the code, it looks like that the function being called to do the search query is [this one](https://github.com/Zettlr/Zettlr/blob/ab5d53707d2041e17c2bdaddbec17b8a0491e784/source/win-main/file-manager/util/match-query.ts).

### Proposed Changes

My proposal is that "Filter" search for the file content too. So the new behavior would be to search:

- in the files and folder names
- in the file content (independent if it is a tag or not).

An example of the desired behavior is the [TiddlyWiki](https://tiddlywiki.com/) search box where:

> Typing text into the search box in the sidebar will turn up a list of all the tiddlers that contain that text.
> -- [Searching in TiddlyWiki](https://tiddlywiki.com/static/Searching%2520in%2520TiddlyWiki.html)

### Caveats

I know that look-up in file content is possible using "Search", but a quick look-up is often required without pressing buttons or keys.

### Do you Wish to Attempt Implementing this Yourself?

Yes

### Zettlr Version

Stable (most recent version)

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Operating System Version

2.3.0

**Comment by nathanlesage** [comment]
> My proposal is that "Filter" search for the file content too.

No. My reasoning for this is the following:

1. The filter is really intended just to be a quick filter and **not** a search. Tags are being searched because the filter looks at the *metadata* of the files, which includes the filename, the YAML frontmatter title, the first heading h1, and the tags. But this decisively does not include the actual contents.
2. The reason why I don't include a full-text search there is because searching a few hundred files takes some time. That is why there is a progress bar in the global search.
3. We can definitely talk about improvements on both the filter (fuzzy search, for example) and the global search (better search terminology), but the filter will not include a full-text search. Feel free to propose better access to the global search, however. Think about what you would need the global search to do for you to make it easier and better to use it!
