### ISSUE TITLE
[Export][Windows]: export fails with "cannot open ...links.lua" if user name contains Cyrillic characters

### ISSUE THREAD

**Issue by PetbkA** [Zettlr/Zettlr#3869]
### Description

When I'm trying to do export to other formats, I'm getting:
> Error running filter C:\Users\\**Марина**\AppData\Roaming\Zettlr\lua-filter\links.lua:
> cannot open C:\Users\\**Марина**\AppData\Roaming\Zettlr\lua-filter\links.lua: **No such file or directory**

error, although the file is there. I guess it's caused by cyryllic symbols in path to _links.lua_.

Tried to avoid it by changing the AppData folder name, but it's a little bit hard in Home Edition.

### Reproducing

1. Create a user with cyryllic name - OK;
2. Launch Zettlr under this user - OK;
3. Do an export to any format - NOK, after pressing export the "No such file or directory" error will appear for links.lua, although the file is there

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10 version 21H1 x64 Home RU

**Comment by nathanlesage** [comment]
This is unlikely an issue with Zettlr per-se. The absolute paths to these filters are inserted into the defaults YAML files before these are written to disk, hence Pandoc will read these paths from disk. It is likely that there is some issue. But I may be wrong.

Zettlr calls Pandoc on Windows using this code:

```typescript
const pandocProcess = spawn('pandoc', [ '--defaults', `"${defaultsFile}"` ], { shell: true, cwd })
```

The `defaultsFile` includes those file paths. Everything within Zettlr happens with UTF-8, so I see four potential issues:

1. Windows itself has a problem with non-ascii characters in paths and thus the NodeJS handler spits out garbage instead of the correct path (unlikely)
2. Pandoc somehow has a problem with non-ascii characters in paths (unlikely, but @tarleb, knows better than me, and maybe I'm wrong)
3. The Windows installation uses some weird Cyrillic subset of UTF that maps Cyrillic characters to wrong UTF-8 code points and hence renders those paths unusable. (not very likely, but also not unheard of)
4. Some interaction of everything I just described (likely).

In any case, I don't think it's an issue with Zettlr itself, so I'm going to close this issue for now.

**Comment by tarleb** [comment]
Here's what I suspect is happening:

1. Windows uses UTF-16 or a local code page for file names, not UTF-8.
2. Pandoc passes the filter file name to Lua, which then opens it. Lua uses the file-string as-is, i.e. it's UTF-8 encoded.
3. Windows provides a legacy interface that should support this, but apparently doesn't. Things go sideways.

I seem to remember fixing a bug that was related to this some months ago. Does updating pandoc help?
