### ISSUE TITLE
Text only paste keeps html code (nightly)

### ISSUE THREAD

**Issue by Etienne-TR** [Zettlr/Zettlr#3890]
### Description

Text only paste paste text with html code instead of text only content.

### Reproducing

If I copy for instance a Discord comment and then I do `CTRL+SHIFT+V` in Zettlr note, I get some html code instead of text only content.

### Zettlr Version

Nightly

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 22.04.1 LTS

**Comment by nathanlesage** [comment]
That is expected behavior. What is happening here relates to Markdown as this weird middle-thing between markup and plain text.

Within Zettlr we have for the past five years run on this assumption:

1. Ctrl+V = Paste HTML (converted to Markdown) if applicable, else whatever plain text is available
2. Ctrl+Shift+V = Paste the plain text (even if that includes HTML)

The only circumstance where Ctrl+Shift+V makes really sense is if you have Markdown in your HTML clipboard. But I am open to suggestions regarding a change in this behavior if enough people say it's confusing as it is (and has been, honestly, for the past five years).

**Comment by jgsw** [comment]
I think workflows of pasting Markdown from websites into Zettlr may be fairly common, so I don't this is a case of https://xkcd.com/1172/ ! 

The behaviour in 2.30 seemed to work perfectly for extracting the Markdown from HTML, but there are now a few glitches.  

Here's an example where things used to work, but no longer does. With Zettlr 2.3.0 you can paste text into a website such as Languagetool to check grammar, and then having corrected things, paste it back with Ctrl =Shift +V, without losing any information.

In nightly, if you try this, you get some odd artefacts that need to be cleaned up manually, such as that the text pasted is wrapped inside a <div>, and pieces of Markdown such as > (to introduce a quotation) get replaced with HTML equivalent &gt; .

**Comment by nathanlesage** [comment]
Hm, I'll have to get back to the code for this. Until the end of next week I'm super full with work, so it may take a while!

**Comment by Etienne-TR** [comment]
> That is expected behavior.

In Zettlr 2.3 (not nightly), when I `CTRL+SHIFT+V` I get text without HTML tags (for the same HTML selection copied to clipboard). Was that a bug ? It should have pasted HTML tags ?

(sorry I probably don't get it yet)

**Comment by nathanlesage** [comment]
Feel free to screenshot what you've copied and how Zettlr inserted it then, both in 2.3 and the nightly. This will make it infinitely easier for me to understand what you desire

**Comment by Etienne-TR** [comment]
I copy this comment from Discord : 
![Screenshot copy comment from Discord](https://user-images.githubusercontent.com/107387699/202897781-03e09e2f-cf9f-4386-8779-bf25df090563.png)

Then if I past into stable release 2.3 that gives to me : 
![Screenshot paste in stable](https://user-images.githubusercontent.com/107387699/202897868-123afb9c-09e0-4b6d-ab6f-8a591dc95d2a.png)
Well it is not an amazing example, there is few markdown formatting but still one title 3 and one emphasis.

Otherwise I get in nightly : 
![Screenshot paste in nightly](https://user-images.githubusercontent.com/107387699/202897919-0a085ceb-2f33-41ad-968e-4bc22aa813f3.png)
And so on, there is another full screen of html before I find text content.

I would prefer to get as it is in current stable : 
1. Text with markdown conversion on CTRL+V
2. The same text content without html tags on SHIFT+CTRL+V.

I understand html can be seen as the full text from clipboard. However, from markdown editor point of view, I think that full text without formatting means rather the same text content just without markdown from conversion.

**Comment by nathanlesage** [comment]
Alright, thanks for the screenshots, and I think now I finally am getting to what you mean. I'll try this out, as this might be an easy fix!

**Comment by Etienne-TR** [comment]
I thought, if to paste html tags (or any other full text code/formatting) is sometimes needed, it could be added a third paste action in context menu : 
1. Paste (as markdown)
2. Paste without format
3. Paste full text clipboard

**Comment by nathanlesage** [comment]
Nah, we don't need that. Basically:

1. Normal paste, there is plain text + HTML in the clipboard --> Take the HTML, transform it to Markdown, and insert it
2. Normal paste, but there is just plain text --> Take the plain text and insert it
3. Shift-paste, there is plain + HTML in the clipboard --> Take just the plain text

If someone needs to add HTML in there, one needs to explicitly copy the HTML source code. (Also, this is good because more security as stuff such as dangerous script tags should automatically be removed, makes it harder to accidentally put your computer at risk)

**Comment by nathanlesage** [comment]
Found the bug!
