### ISSUE TITLE
Troubles in formatting (nightly)

### ISSUE THREAD

**Issue by Etienne-TR** [Zettlr/Zettlr#3902]
### Description

1. Task button do nothing.
2. Inline Code format is not applied in editor.
3. Code and comment formatting are switched in the context menu when text selection.
4. Difficulty to print character \`.

### Reproducing

About the character \` I precise I use a french (obsolete, variant) keyboard.
I have to type `AltGr + 7 + 7` instead of simply `AltGr + 7`

### Zettlr Version

Nightly

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 22.04.1 LTS

**Comment by nathanlesage** [comment]
> Task button do nothing.

This is known, I just didn't yet come to implement it!

> Inline Code format is not applied in editor.

What do you mean by that? I can clearly see that there is formatting being applied. It just doesn't have the background as in previous releases, is that what you mean?

> Code and comment formatting are switched in the context menu when text selection.

You mean the formatting bar. There's nothing wrong with it, but I figured since comment and code are so close together I may need to differentiate the icons a little bit more. Will get to that.

> I have to type AltGr + 7 + 7 instead of simply AltGr + 7

That sounds very much expected to me. The backtick is an accent grave which is a compositional character. It works similarly on a German keyboard where you first press ` and then a letter to create, e.g., è or à. If it hasn't been this way until now, that would be a bug, I would say.

But, we've recently found out that there are some issues regarding keyboard presses, so please observe this going forward and think about: "Could this be wanted behavior? If not, what would be the wanted behavior?"

**Comment by Etienne-TR** [comment]
> Huh, so no backticks? I can't reproduce this locally.

Yes it does backtips, but when I click on the `</>` button (and not the `<>` one).

I've seen the relative commit. Maybe it is already fixed, but I don't really understand what I read.

About keyboard, I find it is a bit long for a block code to do 2 x 3 times backtip-space. But well, I can follow your argument and live this like some healthy finger exercises !

**Comment by nathanlesage** [comment]
So, I just stumbled upon this issue and I'll be closing it, since the accent thing has been figured out, the bug is gone, and for the icons there is currently an issue in planning!
