### ISSUE TITLE
Don't use /tmp for "Share"

### ISSUE THREAD

**Issue by jcuenod** [Zettlr/Zettlr#395]
## Description

This is obviously the immediate result of my recent experience but...

I was working on a paper that involved a lot of bidi text. Zettlr was getting frustrating so I used the "share" option to LibreOffice. I did about a week's worth on that paper religiously saving it and have just restarted my computer only to realise that it wasn't saved in the same directory as the `md` file but in `/tmp`. I know, rookie error but unbelievably depressing right now...

## Expected behaviour

My suggestion would be to create a temporary file in the same folder as the md file (like with a `~` prefix).

**Comment by nathanlesage** [comment]
I can totally understand you. The default setting to export to `/tmp` is so that you can easily "Save as …" from the target application, and, if you don't want the exported file, it'll be purged on restart so you don't have to remove a lot of unnecessary files.

Nevertheless, you can change this setting with this handy option:

![image](https://user-images.githubusercontent.com/17251683/68804524-32f99300-0662-11ea-8f16-bec2dc485ed2.png)

This will ensure that you might have to do a bit more of chores after working on something, but the files won't be purged on restart. And please also note that this will overwrite files with the same file name!

P.S.: I know that this might sound like a slap in your face right now, as it's not worth anything for rescuing your data, but: I'd recommend shutting down your computer every evening. This not only clears RAM and less-well written program data and saves energy, but also ensures you don't lose a week's progress …
