### ISSUE TITLE
BibTeX file cannot be selected for citations

### ISSUE THREAD

**Issue by trutzig89182** [Zettlr/Zettlr#3952]
### Description

Unable to open .bib file to use as source for references.

### Reproducing

Occuring both in v2.3.0 and v2.0.1.

v2.3.0 – I go to Preferences -> Zitieren -> Zitationsdatenbank (CSL JSON oder BibTex). When I click on the empty field the dialogue for selecting the source file opens. But despite having a .bib file in the folder, I cannot click on it to select it.
I go to Preferences -> Export -> Zitationsdatenbank (CSL JSON oder BibTex). When I click on the empty field the dialogue for selecting the source file opens. But despite having a .bib file in the folder, I cannot click on it to select it.

### Zettlr Version

Stable (most recent version)

### Specify version

2.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

MacOS 12.4

**Comment by nathanlesage** [comment]
Ahhhhh wait. I now get what is happening. So, the main issue here is usability related. I followed the recommended settings of Windows and applied them to macOS as well, which means: You have to select the format BibTex first. See this screenshot:

<img width="799" alt="image" src="https://user-images.githubusercontent.com/17251683/204096981-615b668c-1804-4422-8311-820cdb2def84.png">

If you click "Options", you can select BibTex as a format. On Windows, this is much more visible because that selector is already visible without having to click something.

***

The attached patch that will close the issue in a few seconds fixes that for good so that without having to go through this you can select both formats with no issues.

**Comment by trutzig89182** [comment]
Thanks! I guess the problem was only that the options were hidden at the outset. Otherwise clicking to select the corret file type would not have been a problem.

**Comment by nathanlesage** [comment]
Yes exactly. I simply don't understand why macOS would do that in the first place ... but anyhow, now it should be fixed (and, given that I knew about this problem for years by now, itms a shame I always forgot to fix the issue until now -- I guess that's the power of issues!)
