### ISSUE TITLE
Slow file saving/deleting

### ISSUE THREAD

**Issue by MishaRuko** [Zettlr/Zettlr#4001]
### Description

Saving a new file or deleting an existing one takes up to a few seconds. It seems that files are actually created and deleted very quickly on the disk and that the sidebar file manager updates slowly. Certain actions before the file manager updates causes the sidebar to freeze state (doesn't update when new files are created, but buttons work).

### Reproducing

Create a new file, then delete it. File manager takes a while to update.

To freeze file manager:
1. Create a new file
2. Add some text
3. Save it
4. Delete it
5. Add some more text before the file disappears
6. Spam command+s

I tested this in an empty workspace and with little text in the test file.

### Zettlr Version

Stable (most recent version)

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

Ventura 13.0.1

**Comment by nathanlesage** [comment]
The file manager takes exactly 5 seconds to update that; there have been some issues in this regard in the 2.3, but good news: This has been fixed in the current nightly, and it will ship with the betas, which start next week/in two weeks (early January), so please feel free to get the beta then, or already switch to the nightly!
