### ISSUE TITLE
Sidebar is blinky

### ISSUE THREAD

**Issue by almet** [Zettlr/Zettlr#401]
## Description

On the latest release, the sidebar blinks when new files are added to the system.

## Reproducing

Open Zettlr, sync your files with an external server (I'm using nextcloud here).

## Expected behaviour

The UI doesn't blink.

## Platform
 - OS: Debian GNU/Linux
 - OS Version 10
 - Zettlr Version 1.4.3

**Comment by nathanlesage** [comment]
It certainly seems so. Nevertheless, it's a behaviour I cannot influence; it is due to a bug in the external package we use to facilitate really huge lists of files (which you do NOT want rendered all at once; we've done benchmarks, and it simply doesn't work). We need to flush the full list and re-fill it everytime something in the list changes. We'll just have to hope the maintainer fixes this ...

**Comment by almet** [comment]
Thanks for your answer.

I believe we should let reopen this issue, until the issue is solved. I've tried to find an open issue about this before opening a new one, and I believe having this open can help other people know what's the cause here.

What about the other choices such as using another external library ?

Also, if you have a link to the upstream issue, that would be great, so that potential contributors can look it up, and maybe find a solution on the aforementioned library?

Thanks for all you work on this. Zettlr rocks thanks to you. I hope this message is helping, that's the purpose.

**Comment by nathanlesage** [comment]
Hey, yes, I also tend to think that maybe leaving issues open might help other people find them quicker, but then I'm a friend of leaving open only issues where I can both do something and haven't done so yet. For me, the issue tracker is some form of a "ToDo-List", and the number on the "Issues"-tab always gives me a measure of how good I am doing — keeping issues open makes me reeeeaaally nervous, plus … I mean you can also search the closed issues, and I hope it's understandable that I put my personal preferences first on this one!

> What about the other choices such as using another external library ?

It took me days just to find the one I'm using currently, and there are no other viable alternatives, unfortunately :( Otherwise I would've switched a long time ago. Plus, the issue is actually not that hard to find, I myself only didn't have time to delve into it and fix it. The corresponding issue is that one: https://github.com/Akryum/vue-virtual-scroller/issues/256

You can see precisely the error it was causing within Zettlr and why I had to resort to completely emptying the array out and re-filling it after any changes!
