### ISSUE TITLE
[Enhancement] add background color for code blocks

### ISSUE THREAD

**Issue by BAKFR** [Zettlr/Zettlr#403]
Currently, the code blocks are difficult to distinguish from the main content.
I suggest to use a slightly different background color for these blocks, for a better readability.

**Comment by nathanlesage** [comment]
Very good point, I've thought myself about this. But due to Codemirror's styles to only apply to spans, it'd require something like the heading-row-styling plugin, I haven't gotten to this.

After all, but, the full UX of Zettlr needs a redesign; I'm currently planning the first steps of gathering information through surveys about what to do, and I think this should come first before implementing something like this, to create something good in one piece rather than piecemeal!

**Comment by tiotrom** [comment]
One thing I really liked about Typora is that it allowed for easy code blocks where the entire code was wrapped inside a single "block". With Zettlr is only wrapping the code "per row". Like 
line1 
line2
line3

If these are part of the same code block, Zettlr highlights them row by row. Would be great to allow all of these to be wrapped inside a box.

You know what I mean?

And btw, many thanks for making Zettlr. Fantastic piece of software!

**Comment by nathanlesage** [comment]
You got me here, finally got the mood to implement this stuff:

![image](https://user-images.githubusercontent.com/17251683/80317519-963c4380-8804-11ea-8c7c-6e8226794121.png)

**Comment by tiotrom** [comment]
Oh fantastic, sir! Thank you very much!
