### ISSUE TITLE
Panes switch from horizontal to vertical causes malfunction

### ISSUE THREAD

**Issue by exanrauzer** [Zettlr/Zettlr#4033]
### Description

After closing horizontal panes and spliting panes vertical - the area of lower horizontal pane remains and is not accesible.

![Recording 2023-01-10 at 20 26 04](https://user-images.githubusercontent.com/103963891/211645632-d5a049a0-3e74-4f73-8f2c-b53876ecffdf.gif)

### Reproducing

Open panes horizontally, close lower one and open vertically.

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0

### Installation Method

None

### Your Platform

- [x] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
So quick update on this, I just tried this out on the current state of the develop branch.

It turns out the paneData that is stored in VueX is actually correct, so the whole process of setting works perfectly fine, but the components themselves don't pick up on that somehow. Apparently it looks like an issue with the reactivity.

Quick WORKAROUND: Keep debug mode active and select Develop --> Reload to fix this.

It may be as easy as just completely overwriting the paneData, but I'm not sure.

@kyaso If you wanna have a look, feel free to, maybe you have more time than me :D
