### ISSUE TITLE
Markdown style check only recognise 2 space indent

### ISSUE THREAD

**Issue by sith-on-mars** [Zettlr/Zettlr#4097]
### Description

In the beta version, the option 'Check Markdown for style issues' only recognises 2 space indent. If I use 4 space intent for example, the Markdown style checker will show 'Don't use mixed indentation for children, remove 2 spaces'. The Markdown style checker won't show the same warning if I use 2 space intent.

Here is the warning message when using 4 space intent:
![image](https://user-images.githubusercontent.com/37974764/215258743-1e2fb2c5-6719-4e0c-80be-00097abb2cac.png)

No warning message when using 2 space intent:
![image](https://user-images.githubusercontent.com/37974764/215258844-355c424d-4e83-49ef-a4a5-8cd90939cf23.png)

### Reproducing

See above.

### Zettlr Version

Beta (if applicable)

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

OpenSUSE Tumbleweed KDE

**Comment by gXxshock** [comment]
I was able to reproduce this, also seems to be the issue of: https://github.com/Zettlr/Zettlr/issues/4088

**Comment by nathanlesage** [comment]
Just a quick update on this as I see that this issue is gaining traction: currently, the Markdown linter runs on a set of default rules that I just activated to have some basic set. I have been annoyed by this behavior myself, so I can absolutely understand your concerns. However, what I want to do is enable you to select the rules you want to have, and this is a somewhat bigger change. Therefore I decided to leave this with this not-so-great behavior for now and get to a proper fix as soon as I have time.
