### ISSUE TITLE
[ENHANCEMENT] Some quotation pairs are still part of the matchbrackets configuration

### ISSUE THREAD

**Issue by samarulmeu** [Zettlr/Zettlr#411]
I'm a little late in reporting this error, but I hope it will get fixed in time. 

So if I choose from the AutoCorrect Primary Quotes menu `„...”` or `„...“` I get the same result when I type the quote mark: `„“`. In Romanian the **correct** quotation marks are `„...”` so I was really expecting this release to resolve the quotation problem (having to type both symbols).

**Comment by nathanlesage** [comment]
Huh.

\*looks into the source\*

Mh, I have to admit, it's a little bit irritating (which is why I'm thinking of providing additional information, such as the locales where those would be the primary quotation marks), so I definitely have to think of a way, maybe you can also provide some input on this:

1. Option one: Simply add a list of all locales which use the respective quotation marks by default; but this could potentially result in LONG lists
2. Option two: Provide small buttons below the two dropdowns that you can click to auto-select the correct magic quotes (both primary/double and secondary/single) for that locale

And concerning the magic quotes, would you mind having a look at these lines:

https://github.com/Zettlr/Zettlr/blob/a2e64d21f26261eb1aedb664bf150df7a7cccda5/resources/templates/dialog/preferences.handlebars#L657-L670

These are the double-quotes. What's in the `value=""`-field will be used; what's in the `ifCond` will trigger the option to be selected and what's in the `<option>`-tags will be displayed in the dropdown list (all three should be equal per line). It's very likely that I simply made an error while copying and pasting this from Wikipedia (yeah, I'm sorry, I stole from Wikipedia :see_no_evil:)

Here's the same for the single quotes:

https://github.com/Zettlr/Zettlr/blob/a2e64d21f26261eb1aedb664bf150df7a7cccda5/resources/templates/dialog/preferences.handlebars#L678-L692

**Comment by samarulmeu** [comment]
> These are the double-quotes. What's in the `value=""`-field will be used; what's in the `ifCond` will trigger the option to be selected and what's in the `<option>`-tags will be displayed in the dropdown list (all three should be equal per line). It's very likely that I simply made an error while copying and pasting this from Wikipedia (yeah, I'm sorry, I stole from Wikipedia see_no_evil)

I see no error in the file and it should behave properly, but... Please try to select this option `„…”` in your Zettlr and then press the `„` (the beginning quotation mark is the same in German, right?) and the program will use the `“` as closing mark and not what it is expected. 

As for the mentioned two options it seems that they add more *complexity* to the menu. The way it is now I think is ok, not to bloated.

**Comment by nathanlesage** [comment]
Ouuuuuh wait. Yes, of course, NOW I know what is happening! Some default quotation marks are still part of the matchbrackets configuration, so of course THAT plugin will trigger then :laughing: 

No wonder you experience difficulties. If you do not absolutely require the matchbrackets plugin, simply untick the "Automatically close the following character pairs" extension from the Editor-tab in the preferences until the next beta!

**Comment by nathanlesage** [comment]
N.B.: I just misused the issue title for a ToDo/reminder, don't worry!

**Comment by samarulmeu** [comment]
Great! I'll be waiting for the fix and the next beta.

**Comment by nathanlesage** [comment]
Aaaand here we go, will come with the next beta!
