### ISSUE TITLE
Better support for Pandoc ordered fancy lists

### ISSUE THREAD

**Issue by somelinguist** [Zettlr/Zettlr#414]
Pandoc supports ordered lists using the following notation in addition to standard one:

```
#. One
#. Two
#. Three
```

Exporting with Pandoc from Zettlr works fine, but would it be possible for Zettlr to create a new list item on enter/return as it does for other lists? Syntax highlighting would also be helpful, but not necessary (I'm glad to see that it already recognizes that #. is not a heading or a tag!) :slightly_smiling_face:

https://pandoc.org/MANUAL.html#ordered-lists

**Comment by nathanlesage** [comment]
I always found these ugly, but of course, if it's possible with pandoc, why not with Zettlr. I'm always hesitant adding support for things not within CommonMark specs, but … well.

***

_(Some technical stuff ensues I'd need for implementing … some day)_

I'd have to adapt this line:

https://github.com/Zettlr/Zettlr/blob/41718c3c4b81a10e8e7912eb4baf4d65a065b0d9/source/renderer/zettlr-editor.js#L414

Aaand then I'd have to cramp the highlighting support for that thing, for once in the gfm mode (I don't like it in the zkn-mode, so it might just as well mean a full adaptation of that mode). Also, I'd need to update the continuelist-plugin, but as it's already within Zettlr's assets, this should be the least problem we have.

**Comment by somelinguist** [comment]
Yeah. You're right. They are ugly. On second thought, they're not as useful as I thought, given that Zettlr automatically renumbers ordered lists when inserting items.

**Comment by nathanlesage** [comment]
Yeah, and it would be much easier for me to improve on the numbering algorithm so that the renumbering **always** works. Currently, there are some incidents, where that does not really work out.

If you think that the improvements are necessary, please run as many different scenarios as you can imagine and take note when the renumbering works, and when not, so that I can improve the algorithm! I'd say let's use a new issue then :)
