### ISSUE TITLE
Error opening workspace

### ISSUE THREAD

**Issue by redmeades** [Zettlr/Zettlr#4153]
### Description

After clicking Open Workspace in the menu and selecting a folder I receive an error window.

The particular folder sits within Onedrive and contains around 3400 items.

Opening other workspaces is successful. Opening another sub-folder of the target is successful.

<img width="641" alt="Screen Shot 2023-02-16 at 1 51 12 pm" src="https://user-images.githubusercontent.com/4978837/219256679-d8b28e1e-ca69-4667-b2e2-0a3b9171f3b1.png">

### Reproducing

1. Click File -> Open workspace
2. Select folder
3. Click Ok
4. There is a notification: "Opening new root reference"
5. Error message appears

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0-beta.2.nightly

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

Monterey 12.6.3

**Comment by nathanlesage** [comment]
The `ETIMEDOUT` error you receive indicates that a network operation took too long to finish. This normally happens when you (or the other end) has an unstable network connection.

You mentioned that you attempt to load a OneDrive folder that is of a reasonable size. It seems to me, however, that the folder is just too big – not for Zettlr or your Operating System, but for OneDrive to download it. I do not use OneDrive, so I cannot really say anything with certainty here, but the error you receive definitely comes from a network timeout. Could be something with OneDrive or with a slow internet connection, but it has nothing to do with disk itself, if I didn't completely misunderstand where this error can be thrown.

One solution to check that could be: Take the folder you want to open, and copy it to some place on your computer that is not managed by OneDrive, i.e., that it is fully on your computer with no connection to the cloud. If Zettlr then does not show you the `ETIMEDOUT` error, this would prove my point.

If there is anything else to this, feel free to comment here.
