### ISSUE TITLE
Incorrect file contents loaded when opening a file

### ISSUE THREAD

**Issue by efficacy** [Zettlr/Zettlr#4168]
### Description

Sometimes when I click on a file in the left-panel explorer it opens a new tab as expected, but the contents of the wrong file are shown. See attached pic
![image](https://user-images.githubusercontent.com/51254/220639848-fa5b9528-aed5-4338-8c3c-a14b4c2e05be.png)
In the picture, I had clicked on the file LWF Go Live Checklist but it has incorrectly loaded the contents of the file Akour2020, which is visible open in a different tab.

### Reproducing

This is not an easy bug to provoke, it seems to happen when Zettlr has been left open for a while, such as overnight. I have my Zettlr workspace synced with Google Drive which mounts as a separate virtual drive on my Windows machine, so this bug may be triggered by the Google syncing process.

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0 b1

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
Thank you for opening up the issue! As I mentioned on Discord, I can't reproduce this error myself, but I will attempt to do so.

In the meantime, please try to find steps to reproduce this bug. Once you did so, I can get to fixing this. I can't really think of any way why this would happen.

Ah, also, there is another thing I would like you to test out in the meantime:

If this bug happens, please – without doing anything else (especially not clicking on some tabs and files!) – activate debug mode and *reload* the affected window (Develop -> Reload). If the highlight on the tabbar then again works as expected, this means that the bug is within the window code, and not the main process. This would greatly reduce the amount of files where the bug could occur.

**Comment by efficacy** [comment]
I got it to happen again. This time by using the back arrow followed by the forward arrow which moved to the correct tab failed to refresh the display of the contents. When I did develop->reload as instructed it redrew the complete Zettlr window and everything now looks correct again.

**Comment by nathanlesage** [comment]
> I got it to happen again. This time by using the back arrow followed by the forward arrow which moved to the correct tab failed to refresh the display of the contents.

This is a very important observation: This would suggest that, the way to make that happen is to simply quickly change the state of the open files. Since this is asynchronous (opening/changing a file is sent as a command to main, which then checks that this is all good, and only then sends an update to the window), there is a very small time frame, in which you could send a second command _before_ the first command has been reflected in the GUI, hence causing a hiccup.

How quickly do you need to be to trigger this behavior? (And, given this information, can you reliably trigger this behavior?) Depending on how easy or difficult it is to run into this, I can prioritize fixing this, because I fear it may be non-trivial to do so …)

**Comment by efficacy** [comment]
Still gathering data on this, but I did have it happen again, this time just after I had done "close other tabs" with a lot (30+) tabs open. I have sometimes noticed a distinct lag when this happens - the tabs vanish very quickly, but Zettlr as a whole is largely unresponsive to new operations for a second or so. Without robust internal buffering or queuing I'm sure that messages could get lost in situations such as this.

**Comment by nathanlesage** [comment]
I just experienced that issue myself and can confirm I wasn't too quick in doing that, so it's not because of quickness.

But I have another theory: There is one issue where the wrong contents could be fetched: Since every editor has a direct connection for synchronization with the main process, it could be that the following series of events may occur:

1. A user has a document, and edits it
2. The editor hooks into the main process to listen to document changes
3. The user opens another document
4. The main process emits document changes
5. The same editor (which now supposedly holds a different document) receives the document changes and uses them to fully overwrite the correct document with the wrong one
6. It appears as if the editor has loaded a wrong document.

Potentially faulty line:

https://github.com/Zettlr/Zettlr/blob/193de94224c5c96354b3838147e5927808a6730f/source/win-main/MainEditor.vue#L175-L180

Specifically, there is a check that the updates being received come from the correct document, BUT when the actual updates arrive at the editor, that check is omitted. However, the check and the receipt of those changes is asynchronous, so that may be the cause. I'm going to implement yet another check to see if the document that's inside the editor is still the correct one upon receiving updates and, if it's not, not applying them.

**Comment by efficacy** [comment]
Good to know I'm not dreaming it, at least ;)

**Comment by nathanlesage** [comment]
As @kyaso has reported in #4188:

> When switching between two tabs using the back/forward navigation buttons, one of the tabs will start showing the content of the other tab.

This strengthens my suspicion that the document fetching process is not yet resilient enough. My brain already started crunching the code, and I am certain that I can overhaul the code properly over the next two weeks to ensure this does not happen anymore.

**Comment by nathanlesage** [comment]
@efficacy I've now created a commit 8bf3aa3 that could fix this issue (and a set of others). I cleaned up the code a bit and added another check, so feel free to have a look next week with the new nightly!

**Comment by efficacy** [comment]
Cool. I'll let you know how I get on.
