### ISSUE TITLE
Can not print preview or export Mermaid charts (EDIT: Zittlr does not support Catalina)

### ISSUE THREAD

**Issue by SamuelMiller** [Zettlr/Zettlr#4183]
### Description

The latest nightly build Beta 3 v2 on OS Catalina does not display Mermaid charts as charts in the print preview or export formats (e.g. PDF). Instead, they are displayed as Markdown Mermaid code.

### Reproducing

Insert  a mermaid chart code, select print preview or export simple pdf

```mermaid
    flowchart TD
        Start --> Stop
```

### Zettlr Version

Nightly

### Specify version

Version 3.0.0-beta.2.nightly (3.0.0-beta.2.nightly)

### Installation Method

None

### Your Platform

- [ ] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Catalina OS

**Comment by SamuelMiller** [comment]
According to https://github.com/Zettlr/Zettlr/discussions/4182#discussioncomment-5197519

"macOS Catalina is unfortunately no longer supported. The minimum required macOS version is 11.3."

**Comment by nathanlesage** [comment]
I mean, if the app works on your machine, that's great! I'm just keeping to the official recommended Operating Systems of Electron (upon which Zettlr is based).

Regarding your actual issue:

> Can not print preview or export Mermaid charts

You can do so, but it is not enabled by default. What you will need is a Pandoc filter that can process Mermaid charts. Zettlr itself is capable of pre-rendering those Mermaid charts, but only within the editor itself. In order to do so during print and export, do the following:

1. Search for a Pandoc filter that can help you, for example https://github.com/raghur/mermaid-filter (was the first Google result)
2. Set up anything the filter requires additionally, then open the Zettlr AppData directory (on macOS: `/Users/username/Library/Application Support/Zettlr`), and paste the filter into the `filters` directory.
3. Zettlr should now automatically run that filter upon exports (the print preview is also an export)

Note, however, that this feature is not officially supported, hence it could be that maybe something breaks. I don't expect it to, but if, you would be on your own. I hope that this nevertheless helps!

**Comment by mica100** [comment]
To complete that instruction of printing mermaid charts from Zettlr - export HTML and PDF with it, the following steps need to be done on Ubuntu Linux:

```
sudo apt install npm
sudo npm install -g mermaid-filter
```
In `Zettlr -> File -> Preferences -> Assets Manager -> Select Tab: Export` choose the format `HTML` in the left list and add after the lines:
```
filters:
- type: citeproc
```
the new line:
```
- mermaid-filter
```
Now printing and preview of mermaid charts works from within Zettlr. Tested with version: 3.0.2

**Comment by FBEZ** [comment]
@mica100 thank you very much! As an additional note, to make it work on windows replace 
```
- mermaid-filter
```
with 
```
- mermaid-filter.cmd
```
