### ISSUE TITLE
[3.0.0-beta.2.nightly] Data loss. Zettlr reverted to an older version of my text during a cut-and-paste action.

### ISSUE THREAD

**Issue by wideaperture** [Zettlr/Zettlr#4214]
### Description

I was writing up notes in a file and went to paste in a passage of text from another application. I had done the same action on several prior occasions without incident. However, on this occasion the text was not pasted, but instead the file unexpectedly reverted to what I assume was an earlier version of the file saved in memory — that is to say, some of my work was there, but most of what I'd done over the past half hour was gone. The cursor also jumped from the end of the file, where I'd intended to place the text, to the very beginning. Neither "Undo" nor "Redo" restored the missing text.

Another potential piece of the puzzle is that the file I was working on is saved to a folder that syncs with Dropbox. Because Dropbox saves iterative versions of files as it syncs, I was able to go through its version history of the file. Unfortunately, the file's version history did not include any of my lost work. Though I can't say for sure, the most recent version of the file on Dropbox is likely identical in its content to the text Zettlr reverted to when the bug occurred.

To me this suggests one of two possibilities. The first is that the text that I typed and lost existed only in Zettlr's memory and was never actually saved to the file, meaning auto-save wasn't functioning correctly. In this case, the bug would've occurred when Zettlr tried to load the latest version of the file from the hard drive and that summoned a file that did not reflect the in-memory changes.

I suppose it's also possible, though, that some confusion in timestamps occurred that caused a Dropbox sync error, in which case, Dropbox may've re-introduced an older version of the file, which Zettlr then regarded as the latest version. That said, this seems somewhat unlikely to me. It has never been an issue in the past and I have been using various versions of Zettlr with Dropbox sync since summer 2022.

Finally, I'll note that I did not have the Dropbox file open in any other app or device at the time, so no changes could've been introduced by another user agent.

### Reproducing

See above. I don't know that I could reproduce it, but I've at least tried to describe in detail what happened.

### Zettlr Version

Nightly

### Specify version

3.0.0-beta.2.nightly

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Manjaro (Rolling)

### Additional Information

Happy to provide screenshots or file versions from the Dropbox version history if these would be helpful.

**Comment by nathanlesage** [comment]
Thanks for being so verbose!

I can see three things happening here that could maybe lead to an explanation:

1. The cursor jumping. When that occurs, this indicates that Zettlr has, in the background, reloaded the file from disk. The reason is that, when you just overwrite the entire contents of the editor, the last cursor position may be farther back than the last character of whatever the new file contents are. To prevent errors, CodeMirror automatically resets the cursor to the beginning of the file.
2. You mention the possibility of Dropbox somehow reverting the file to a previous version. That would corroborate the first observation. If you have set the setting to automatically load remote changes to "on" this would have happened automatically under the hood.
3. You said that you have auto save turned on. I have heard from others that apparently the auto save functionality is a tad wonky, and I haven't had the chance to fix that, so there is a possibility that Zettlr thought that the file was always saved while it was not. Did the "modified" indicator turn on intermittent while Zettlr had not yet saved the file automatically? If not, that could be the indicator for this behavior.

Taken together, what could have happened based on what I see in your report, the following chain of events could have happened:

1. At some point auto save failed (I currently think that this is due to a race condition)
2. At that point, Zettlr did not save the file anymore, so Dropbox did not see any new updates
3. You said that Dropbox sometimes goes over the files, maybe it also modified the time stamp, which then caused Zettlr to revert to that state instead 
4. That this happened on paste was a mere coincidence.

What do you think, does any of this seem plausible?

**Comment by wideaperture** [comment]
This sounds reasonable. I'm certainly willing to believe that it was coincidence that it happened on paste.

I'm less sure of Dropbox's involvement, though. I'm honestly not certain what Dropbox's behavior is with respect to the sync directory, so I don't know enough to say whether it might've been the culprit. Typically, the Dropbox status bar icon indicates that it's syncing to the cloud any time Zettlr updates an auto-save, so Dropbox does seem to be actively monitoring the sync folder on a continual basis. But the file was not open on any other devices, so no foreign changes could've been introduced and if Dropbox were making unbidden modifications to timestamps, I feel like I would've experienced some bad effects long before now.

It seems almost certain that Zettlr stopped auto-saving the file at some point. But I'm not sure what triggered it to reload the older file version from the disk. Dropbox may've been involved, but I don't know enough to say for certain and it's been reliable in the past.

As to your question about the "modified" indicator, I admit I was not paying it close attention at the time and so I cannot remember whether it was turning on and off or when it might've stopped.

**Comment by nathanlesage** [comment]
I agree that Dropbox is the least likely culprit here. I think that the issue most definitely stems from failures in the auto save procedure.

In general, until I've fixed this: if you see that the modified indicator does not seem to work, copy and paste the entire file into some other editor, restart Zettlr and continue. Not the best solution, I know, but better than losing half an hour of work 👀 I'll try to keep this high priority!

**Comment by nathanlesage** [comment]
I *think* I have found the issue. The problem was the following:

Zettlr detects if a file has been modified if the last saved file version differs from the version that is currently in memory. However, due to me not fully thinking the logic through, the save function actually messed with this. Specifically, how it worked is as following:

1. Get the document's contents and begin writing them to disk
2. After that was done, update the last saved version number with whatever the current version is

However, that is problematic, because saving a file can take some time, and in the meantime, you – the user – could add additional changes. This means that the actual document's contents are more recent than whatever has been written to disk. In and of itself, this would basically only mean that a very small set of changes would be missing from the saved file – nothing too fishy.

However, these version numbers are *also* used by the actual editors to infer if they need to update their own contents within the editors from the main process. And when you mess with these numbers in unduly ways, this can cause a literal "hiccup" that means that the file is never marked as modified (because the current version equals the last saved version) even though more and more additional changes amass. And in that case, Zettlr won't attempt to save the file, because it doesn't detect any changes.

It's basically a heart rhythm disorder, so to speak.

What I now changed is to ensure that any timeouts are removed before any changes happen, and additionally, the save file function now takes a snapshot of the document state *first*, updates the descriptor with this snapshot's info, and only then attempts to save the document. This could also lead to problems when the saving itself fails, but this is extremely unlikely, because if you could open a file, this means it exists on disk, so in 99% of all cases this should work as expected.

***

But, to close off: Please observe this behavior. I think it should be resolved now, but it doesn't hurt to treat it with caution until we cannot observe this behavior anymore. I'll also be on the lookout if this bug reappears!

**Comment by wideaperture** [comment]
Thank you for the rapid response and deep dive, @nathanlesage! Do you know when a new nightly will be available with the (:crossed_fingers:) fix you've outlined?

**Comment by nathanlesage** [comment]
Should be here already! Go have a look: https://nightly.Zettlr.com
