### ISSUE TITLE
Provide a more explicit warning to the user when auto-save stops working.

### ISSUE THREAD

**Issue by wideaperture** [Zettlr/Zettlr#4229]
### Description

There are a number of extant bugs affecting the Beta that cause Zettlr to stop auto-saving changes to documents. And it's possible that other such bugs may come up in the future. If the user is paying close attention to the tab in which they're working when this occurs, they will notice that the asterisk indicating unsaved-changes stops blinking on and off. However, this is fairly easy to miss. I suggest a more prominent warning.

### Proposed Changes

I get the potential retort here: If Zettlr were "aware" that auto-save had stalled, then there'd be no problem in the first place. However, to the extent that detecting the problem might be distinct from solving it, might it be possible to pop up a warning to the user when auto-save has stopped?

I imagine a narrow red bar across the top of the editor that appears when auto-save stops functioning. It could contain the warning, "Auto-save appears to have stopped working. Please copy the text in this buffer to another application as a precautionary measure. Then save the document manually and restart Zettlr."

### Caveats

None that I know of.

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

Nightly

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Operating System Version

Manjaro (Rolling)

**Comment by nathanlesage** [comment]
I do get what you mean. However, as you yourself mention, this would be to a certain degree senseless. Such a warning as you envision it would make sense only in instances where *external* causes may prevent Zettlr from saving a file -- such as when a file suddenly becomes read only. I do agree that in that case a prompt would be appropriate, and I can certainly implement this because that is actually something Zettlr can detect.

Regarding the auto save failures we are experiencing in the beta: these are actual bugs, so there is no way to detect when auto save has failed -- and indeed, once we know why it fails, it is much more straightforward to fix that bug instead of basically saying "hey we found a bug, but instead of fixing it, here's a message that there is a bug"

You know what I'm trying to say? 🙈

**Comment by wideaperture** [comment]
I do get what you're saying. We're definitely on the same page. My reasoning — as someone who, like most of us, has occasionally created a slew of state variables and/or littered my code with `print` statements to discover why my code wasn't working as expected — is that there are plenty of occasions when I was able to detect when a chunk of code wasn't working as expected far in advance of actually understanding _why_ it wasn't doing so, and hence before I'd discerned a fix. If this isn't one of those instances, then obviously the proposed fix is nonsensical. I was merely wondering whether there was a way of detecting/flagging when auto-save was failing, even if the precise logic of how to prevent it from failing proved to be a longer-term issue.

Note that this is more an explanation of my reasoning than a defense of the original proposal. As I say above, if this isn't a case where the shoe fits, then it's not a feature that makes sense to implement. Though I do like the idea, as you say, of having a warning for read-only files.
