### ISSUE TITLE
Export to EPUB (with Kindle/KDP support)

### ISSUE THREAD

**Issue by paladini** [Zettlr/Zettlr#4249]
### Description

I would like to use Zettlr just like I use bibisco or Manuskript. Besides a developer, I'm also a writer that like to publish novels in Amazon Kindle Publishing (Amazon KDP) and also in other platforms as well, but all of them requires a format like EPUB and this is not currently supported by Zettlr.

### Proposed Changes

I would like to request a new feature, **Export to EPUB format**  with a checkbox option (not checked by default) to optimize export for Amazon Kindle Publishing Platform (KDP) [useful for writers, just ike me].

### Caveats

No caveats.

### Do you Wish to Attempt Implementing this Yourself?

No

### Zettlr Version

None

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Operating System Version

Ubuntu 22.04

### Additional Information

Correlated issues:
- https://github.com/Zettlr/Zettlr/issues/228
- https://github.com/Zettlr/Zettlr/issues/1005

**Comment by nathanlesage** [comment]
In the upcoming v3.0 you can easily create new export profiles (i.e.: Pandoc defaults files), which allow you to customize what Zettlr can export to to any degree you would like. I will be releasing another 3.0 beta within the next few hours, so I invite you to try these out. With them, you will be able to create the corresponding settings to achieve what you would like to.

Here's already the corresponding documentation; you can change the writer property of a profile that you don't otherwise use to achieve the same in v2.0: https://docs.zettlr.com/en/core/defaults-files/
