### ISSUE TITLE
REQUEST: Portable Version

### ISSUE THREAD

**Issue by vozer** [Zettlr/Zettlr#426]
Is it possible to get Zettlr as a portable version?

## Platform
 - OS: Windows

**Comment by nathanlesage** [comment]
Possible: Yes. Realistic: Currently not. I'm aware that on some forums people are lamenting the fact that Zettlr is not available as a portable version, but the reason for this is less that I'm not willing to do so, but because I'd first need to carefully refactor a lot of directory assumptions Zettlr makes internally (b/c currently Zettlr saves everything in the appData-folders, which, for a portable version, would not be the best option, if I assume this correctly). So while I know that this demand is there, I'll need to find time to actually implement this, which I cannot promise at this moment. There's still too much work left to do on the internals of the app. Installing it "Only for me" (that is, in the Roaming-folder of your user profile) is the closest you can get currently, as this circumvents administration access during install.

**Comment by teodias** [comment]
Hi,

will https://www.electron.build/configuration/win help?
There is something described, like adding 'target = portable' will do the trick?

Regards,
Teo

**Comment by nathanlesage** [comment]
That's not the problem. It'll take me literally five minutes to enable a portable target. The problem is that currently the data is completely written to the user directory, so even if you had a portable version, your user data would still be written to the user data on the computer, not the Zettlr directory on the flash drive. That's the main problem.
