### ISSUE TITLE
Table of contents doesn't immediately render

### ISSUE THREAD

**Issue by noah-arroyo** [Zettlr/Zettlr#4328]
### Description

**Expected behavior:** Upon opening a note, the Table of Contents should immediately render (if that sidebar is already open).

**Buggy behavior:** Upon opening a note, the Table of Contents only renders after the user first clicks within that sidebar and then clicks in the body of the note.

### Reproducing

(Reiterating the above)

Make sure your Table of Contents sidebar is open (if it isn't, you can reveal it with `Ctrl`+`Shift`+`?`). Open a note containing section headers, and see that the Table of Contents is blank. Mouse-click within the blank sidebar, then click in the body of the note, and the Table of Contents will now appear.

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0-beta.4

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
Heya, just saw this issue: I'm going to close this as a wontfix, because I can't satisfy this.

The reason is that we have to tap into CodeMirror's logic, which does not allow me to retrieve the entire syntax tree up front. (There is a way, but even for moderately sized documents this will incur a noticeable performance penalty upon opening a document, even on my very powerful laptop, which is unacceptable.)

Maybe CMs performance can be improved upon at some point, then I'm happy to accept PRs to improve behavior!
