### ISSUE TITLE
A few bugs and problems found while testing Zettlr

### ISSUE THREAD

**Issue by tk-li** [Zettlr/Zettlr#434]
* The Spellchecking Tab in Preferences drops to the lower part of the screen, unlike other tabs which are all right at the middle.  
* The first word in the footnote was colored and in different font instead of black text.  
* Undo and redo buttons under Edit in the pull-down menu don't work.  
* Images fail to be rendered within a list.  
* Links are not rendered if a title in double quotes is appended.  
* `\frac` in Latex fails to be converted in html file, but works in pdf and word files.   
* When Zettlr 1.4 was installed, Zettlr 1.3 was not uninstalled.  

OS: Windows 10
Zettlr v1.4.3

Hope this helps.

**Comment by nathanlesage** [comment]
Thanks for reporting!

1. Do you have a screenshot for that behaviour? Helps a lot in pinpointing the issue!
2. This is due to the underlying GFM mode. Unless we completely rewrite that mode by hand (which I don't want to happen, out of a lot of reasons), this is something we have to deal with at least for now.
3. You mean the main menu? That's good to hear, I'll have a look!
4. Images are only rendered when they are on their respective line, which is due to limitations in Codemirror's rendering engine and certain assumptions we cannot make. Doing otherwise leads to ugly and unhandy graphic glitches.
5. Good that you remind me, I need to rewrite the link rendering engine either way, I'll keep that in mind.
6. This is expected behaviour. Please [see the docs on that](https://docs.zettlr.com/en/faq/#i-know-latex-and-want-to-use-it-inside-my-markdown-files-as-well-is-this-possible)
7. That's not good — did this happen before, or only between 1.3 -> 1.4?

**Comment by tk-li** [comment]
1. See screenshot below. You just have to scroll down to see the whole thing.
![Screenshot (3)_](https://user-images.githubusercontent.com/58731242/70709527-0778cf80-1d18-11ea-83b4-6f393fd40b00.jpg)
3. Yes the main menu.
6. Alright, but many other math notations are rendered correctly in html, just not `\frac`.
7. I never installed any version before 1.3. Uninstalling Zettlr only removes v1.4 but not v1.3.

**Comment by nathanlesage** [comment]
Thanks for the screenshot; it sometimes happens, because I have to account for many screen resolutions, and sometimes a resolution is just an inch too short for dialogs to be displayed completely.

If Math notations are rendered, this sounds as if such conversions can take place within Pandoc, but then it's out of the scope of Zettlr to implement `\frac` — if you'd like to see it supported, head over to Pandoc and see where you might fit that issue in! As soon as Pandoc supports it, Zettlr also will support it.

Concerning the uninstallation — please try out 1.5 when it's released (this Christmas) and report back if it does _not_ uninstall 1.4, because then I may have to take a look at the Builder configuration (albeit I cannot promise anything due to missing hardware)

**Comment by tk-li** [comment]
Hi, I cannot download the latest update (v1.5.0) for some reason. I opened the download page and nothing got downloaded. I clicked on the Windows button to no avail. Any ideas?

**Comment by nathanlesage** [comment]
Somehow renaming the releases broke the auto-download detection. I'm working on it; but for now, only the GitHub releases page works: https://github.com/Zettlr/Zettlr/releases/latest

**Comment by tk-li** [comment]
Thanks. Now v1.4 was removed in Apps & Settings of Windows when v1.5 was installed. Links appended with a title in double quotes are also rendered now.
