### ISSUE TITLE
Right sidebar doesn't update when clicking on a document tab

### ISSUE THREAD

**Issue by exanrauzer** [Zettlr/Zettlr#4469]
### Description

The right sidebar in the application fails to update when clicking on a specific document tab. The sidebar contents remain unchanged until the document area itself is clicked. This behavior is inconsistent with the expected functionality and may lead to confusion for users.

Expected Behavior:
When clicking on a document tab, the right sidebar should immediately update to reflect the relevant information for that specific document. Users should not be required to click inside the document area to trigger the sidebar update.

### Reproducing

<details><summary>Gif</summary>

![Recording 2023-07-01 at 13 14 46](https://github.com/Zettlr/Zettlr/assets/103963891/eb79aaf6-10ad-4334-94a6-bab323b220c8)

</details>

### Zettlr Version

Beta (if applicable)

### Specify version

Zettlr 3.0.0-beta.5

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by carregal** [comment]
The issue still happens in version 3.0.2.

Not only the sidebar does not refresh, but when you have a sidebar displaying the outline of Tab1 and you switch to Tab2, clicking directly in one of the the sidebar outline links takes you to the Tab2 line number equivalent to the outline link line number in Tab1.

How to reproduce this:

- Open a document in Tab 1. The sidebar outline should reflect this document structure
- Click on one of the outline links for Tab1, this will take you to line NNN in Tab1.
- Switch to a different document on Tab2. The sidebar will not update and still shows Tab1 outline instead of Tab2 outline.
- Click on the same outline link used in step 2 of this procedure. The cursor for Tab2 will move to line NNN in Tab2.

Zettlr Version

Zettlr 3.0.2

Installation Method
From the website

Your Platform

 macOS

Architecture
 ARM 64bit

Operating System Version

MacOS Sonoma 14.0

Additional Information
None

**Comment by nathanlesage** [comment]
This should now work in the coming nightlies & the 3.1 betas/stable; I've spent a considerable amount of time refactoring the updating processes and it should now work reliably.
