### ISSUE TITLE
When exporting a project, footnotes in individual chapters are misplaced

### ISSUE THREAD

**Issue by Jaifroid** [Zettlr/Zettlr#45]
Example: I have a book project with several chapters. Each chapter has its own footnotes numbered sequentially from 1 to xx. When I export the project to PDF in Zettlr, footnotes from later chapters get assigned to footnote reference markers from earlier chapters.

I realize this is more of a pandoc issue, but it would be a major show stopper for your target audience,  so it's worth working around if possible. #42 might mitigate, but it doesn't solve the problem of how to get the separate chapters into Zettlr and renumber all footnotes in the first place. Also, most books by most publishers, especially edited books, restart footnote numbers per chapter. So I think this is a separate issue from #42..

Workaround 1: Under the hood, Zettlr could assign a unique chapter identifier to each note, since notes don't have to be numeric only.

Workaround 2: Use the pandoc option of writing a footnote inline using the syntax:

`Some text^[Text of footnote.]` 

Drawback is that footnotes can't have more than one paragraph, and they clutter up the main text. Advantage is ease of writing and editing footnotes. I've tested this option, and pandoc produces correctly numbered foot-of-the-page footnotes when exporting the project.

As this is a severe "bug", I think the Export function should throw up a specific warning about footnotes needing to be unique, until Zettlr can handle this automatically.

**Comment by nathanlesage** [comment]
> I realize this is more of a pandoc issue

Nope, unfortunately this is completely at the fault of Zettlr =D

This is what I mentioned in issue #42. To reiterate:

> The only thing that needed to change in the code (and this is something I have to do pretty quick) is to correctly number the footnotes on export (otherwise you'd have a footnote number 1 for each file, which would confuse Pandoc). This is not done currently, because I've had massive problems reordering the footnotes in the past.

In short: I need to do something about footnote renumbering on export, as in:

Internally, Zettlr "glues" the markdown files together and then exports them using pandoc. That means: While each individual file is loaded, I need to replace all footnotes based upon a general counter. Which is what I'll be doing in the next days for the next release, depending upon my speed!

**Comment by nathanlesage** [comment]
Alright, that was easy. Attached fix finally closes this problem.

Instead of manually reordering and renaming the footnotes, now I simply prepend them with the file's hash (which is unique), rendering the footnotes unique and preventing errors:

`cnt = cnt.replace(/\[\^([\w]+?)\]/gm, (match, p1, offset, string) => ´[^${String(this.hash)}${p1}]´)`

How Footnotes look in the temporary files:

<img width="376" alt="screenshot 2018-10-21 at 12 07 56" src="https://user-images.githubusercontent.com/17251683/47265559-0ab86700-d52a-11e8-83bc-6e3b217d8696.png">

References:

<img width="235" alt="screenshot 2018-10-21 at 12 08 03" src="https://user-images.githubusercontent.com/17251683/47265560-0b50fd80-d52a-11e8-87cc-ea4800cf53ce.png">

How footnotes look inside the files prior to export:

<img width="377" alt="screenshot 2018-10-21 at 12 08 11" src="https://user-images.githubusercontent.com/17251683/47265561-0b50fd80-d52a-11e8-84b9-f4fa415e4873.png">

What the exported result looks like:

<img width="352" alt="screenshot 2018-10-21 at 12 08 25" src="https://user-images.githubusercontent.com/17251683/47265562-0b50fd80-d52a-11e8-8b8f-f423b30ed8eb.png">

**Comment by Jaifroid** [comment]
@nathanlesage Many thanks!!
