### ISSUE TITLE
Do I have a way to pin certain files on Zettlr which I frequently use/ need to use? 

### ISSUE THREAD

**Issue by itsraghz** [Zettlr/Zettlr#4510]
### Checklist

- [X] Zettlr does not possess this feature (if it does, but the feature doesn't work out for you, propose an enhancement instead.)
- [ ] Zettlr's current features cannot be used to approximate this behaviour (otherwise, propose an enhancement instead.)
- [X] I have searched the documentation to make sure I did not overlook it.
- [ ] I have searched both open and closed issues to see if someone has already proposed this.

### Feature Proposal

At times I may have to view a particular file very frequently (say the Table of Contents of a book, or the main Syllabus of the materials) - for a cross reference. Do I have a way to pin certain files on Zettlr which I frequently use/ need to use?  

### Example Workflow

At times I may have to view a particular file very frequently (say the Table of Contents of a book, or the main Syllabus of the materials) - for a cross reference. I now have to keep opening everytime as the total number of files can be kept opened seems to be limited. Do I have a way to pin certain files on Zettlr which I frequently use/ need to use?  

### Caveats

I now have to keep opening everytime as the total number of files can be kept opened seems to be limited.

### Do you wish to attempt implementing this yourself?

Yes

### Platforms

- [ ] Windows
- [X] macOS
- [ ] Linux

**Comment by exanrauzer** [comment]
Hello! Have you checked latest beta? You can pin tabs.

**Comment by itsraghz** [comment]
@exanrauzer  I do use the version Version 2.3.0 (2.3.0) of Zettler on iOS on my Macbook Pro - which is the latest stable version I just downloaded a week ago. I see that there is a nightly build available on this page https://nightly.zettlr.com/. Should I have to consider this https://nightly.zettlr.com/Zettlr-3.0.0-beta.6.nightly-arm64.dmg ?

**Comment by exanrauzer** [comment]
Check Releases in main repositorium right sidebar.

@nathanlesage could you consider pinning beta info as discussed?

**Comment by nathanlesage** [comment]
As @exanrauzer said, the current betas are recommended and include the features you wish for.

Besides that, I would like to politely point you towards our Discord server. The issues you have been opening over the past days resemble more questions that our community could quickly answer and point you towards the correct resources.

By opening frequent issues here, many of which are more questions rather than bug reports/feature requests, you are binding my resources which slows down the overall speed of development for the app for all users. On Discord, many people will help you, and even tell you when it is actually time to open an issue. The community is not active here as this merely serves as a venue to report bugs to and request very specific things from me.

Thank you very much for your consideration.

**Comment by itsraghz** [comment]
sure @nathanlesage , I get that, thank you for your understanding and the right direction. I appreciate that.
