### ISSUE TITLE
[ENHANCEMENT] Improve markdown documentation and language support

### ISSUE THREAD

**Issue by maia-sh** [Zettlr/Zettlr#453]
## Description
I'm struggling to use the Markdown documentation (https://docs.zettlr.com/en/reference/markdown-basics/) to figure out which dialects I can use where (i.e., markdown preview vs. html). I understand that Zettlr uses a combination of different dialects with special extras, but as a relative markdown newbie, it difficult to figure out what features are available without documentation.

For example:
```
==hi==
```
displays marked/highlighted in yellow in markdown preview but does not render highlighted in HTML (with pandoc installed).

Additionally, language support for `mermaid` would be great and is supported in other markdown apps (e.g., https://cheatsheet.md/notable.pdf).

## Proposed Changes
- Additional documentation on markdown features, e.g., marked/highlighted text, in both markdown preview and HTML. Ideally these should match (i.e., the text should be marked/highlighted in both markdown preview and HTML.
- Language support for `mermaid`

**Comment by nathanlesage** [comment]
The main problem with Markdown is that it's not standardised. There are attempts (google for CommonMark), but it's still in early stages. This is what "several flavours" refers to.

Basically, Zettlr uses GitHub Flavoured Markdown for Syntax highlighting, and adds Zettelkasten-elements (IDs, Tags, also Footnotes and the like). Highlighting is supported almost nowhere. I've implemented it because someone mentioned they'd like that, but neither Showdown (For Copying and Pasting as HTML) nor Pandoc support these Highlight-elements.

Therefore, the basic Markdown documentation that's on the Zettlr site is only for starters, featuring those elements that are almost universally recognised without ambiguity. For further reference, I've linked to some resources in the last paragraph of the documentation page you've linked (albeit I have to confess the link's colour is not at all readable; it's only slightly darker than normal text ...)

Last but not least, concerning Mermaid support: It's already open in one issue, so I'm going to close this one to keep the issue list clean!
