### ISSUE TITLE
[BUG] CSL Environment error on PDF exports for Pandoc > 2.8

### ISSUE THREAD

**Issue by nathanlesage** [Zettlr/Zettlr#455]
## Description

[See the forum discussion](https://forum.zettlr.com/discussion/77/problem-pdf-export-with-citations-or-images).

## Reproducing

Apparently, having Pandoc 2.8 installed causes the error, as some additional TeX commands to the default template are missing which Pandoc expects.

## Expected behaviour

Produce a valid PDF, no matter the Pandoc version (although Pandoc >2.0 is required for Zettlr)

**Screenshots**

## Platform

 - OS and version: Not applicable
 - Zettlr Version: Not applicable (depends on Pandoc version)

## Additional information

Should you experience this issue, mitigation is possible by downloading the official template, adding the required code and pointing Zettlr to use that template instead of the built-in. The necessary steps are described also in the forum thread.

**Comment by frederik-elwert** [comment]
This bug is reproducible for me. I feel it has quite severe implications, as new users of Zettlr will inevitably run into this issue when they installed a recent version of pandoc. (I for my part will teach Markdown on Thursday and thought about using Zettlr, but it’s probably off-putting when PDF export is broken.)

So I think adding this snippet to the default template is probably a good idea. I created a pull request.

**Comment by nathanlesage** [comment]
Thanks so much, I just did a short code review, then I can merge it easily and release a patch soon!

Concerning your seminar: If you do your seminar on Thursday, I'd be pleased to hear some reviews, so that we can streamline some of the issues to know what's really urgent and what's not that important. This will help due to my currently somewhat limited resources; I want to fix some things before the end of January, and this might very well help me to decide upon which things need fixing!

**Comment by nathanlesage** [comment]
Solved by @frederik-elwert!
