### ISSUE TITLE
Character count is incorrect when including in-text references

### ISSUE THREAD

**Issue by Kathamorph** [Zettlr/Zettlr#4553]
### Description

I am currently writing a proposal with a very strict character limit of 20,000 characters including spaces, also including references and bibliography. The problem I am facing is that the character count shown in zettlr will not match the character count in the later on exported .odt file. One reason for this is obviously that the bibliography will only be added in the exported document and its characters therefore not be counted in the zettlr document. This is unhandy, but somehow manageable. Yet, the character count was still off in other places and I seem to be able to narrow it down to sentences that include in-text references. See screenshots: when only highlighting the sentence until before the reference, it will give me the correct charcter count of 280. Once I include the reference, it will give me an incorrect one of 356 (instead of 320 as it will be counted in the exported document that has to meet the character limit). 

![zettlr1](https://github.com/Zettlr/Zettlr/assets/138499271/b35b7338-55b0-4f9b-bcd3-03f1ae030d6b)
![zettlr2](https://github.com/Zettlr/Zettlr/assets/138499271/b559ed51-efce-4362-9f39-bd61ac89f73f)

### Reproducing

Write a sentence in zettlr and include an in-text reference through zotero. Export as pdf or odt and compare how the character counts match and don't match when excluding and including the reference in the count.

### Zettlr Version

Stable (most recent version)

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
A few thoughts on this:

1. The character count literally counts characters as they are in the selection.
2. This includes citations, however only the markup before rendering (i.e. `[@citekey]` which would be rendered as `(Author Year)` will count as 10, not 13), because the editor itself has no knowledge about what the citation will render as
3. While it may be possible with a lot of hacky code to correct these character counts (no guarantee that this will work as expected), this would still not help you, since your citations may be rendered in a different citation style upon export, which would then change the character count once again

Always remember that what you write in Zettlr is a form of source code, not yet the final exported soup. Therefore, word and character counts are immensely helpful to roughly aim for a goal, but can never get you there exactly.

I see that you seem to be working on a proposal at a German university; I've been through this issue with Zettlr myself quite often during my M.A.; here's my advice on hitting character limits with the pitfalls I just introduced:

1. If you have to submit as a PDF, rest assured that nobody will actually sit down and count the exact characters, so if you overshoot by a few hundred, that won't matter (at least not in the academic realm).
2. If you have to submit as ODF/DOCX or you suspect that the teacher to read through it can be mean, try to aim for 19,000 instead of 20,000 characters (or 17/18, if you need to account for a somewhat longer list of references).
3. From time to time, export the document to the target format and look at the resulting character count; then you have a good idea of how much you still have room or need to cut. After a while you'll get a good feeling for how many Zettlr-characters will result in how many "real characters", so to speak.

If you have any further questions or are unsure, feel free to ask!
