### ISSUE TITLE
Local Images not Found Correlating with Drag an Drop Workplace Error

### ISSUE THREAD

**Issue by tfr00** [Zettlr/Zettlr#4558]
### Description

Updated from 2.? to 3.0.8 (could not wait for multiple windows any longer)

- Problem 1: Local images (refered by: "`![xyz.png](xyz)`"; full paths also not working) do not show up any more (only placeholder image and mouse over gives: "Image not found: xyz.png"; nothing changed in local file structure/directories

Correlating with:

- Problem 2: Drag and Drop of images does not work, just giving "Could not open workspace"-Error; Log file: "[18:41:34] [Error] Could not open new root D:\XXX\YYY\zzz.jpg!"

Everything else seems to work properly: external links, internal links,  adding new files, links, ...

If already discussed elsewhere, please excuse; otherwise this may help for the next stable release. Thanks in advance.

### Reproducing

Problem 1: "Image not found: xyz.png" on mouse over on placeholder image

Problem 2: "Could not open workspace"-Error; Log file: "[18:41:34] [Error] Could not open new root D:\XXX\YYY\zzz.jpg!"
(see description)

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.8

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by nathanlesage** [comment]
Since we're currently en route to the next stable on Sept 1, can you please for quicker reproduction give me the paths where those images are, and where the corresponding files live? And exactly what the images look like? Makes it faster for me to reproduce and fix in time. Thanks!

**Comment by nathanlesage** [comment]
Thanks. The reason you were stumbling upon this was that Zettlr has to use heuristics to figure out if an "incomplete" (read: not absolute) path is actually a path to the local file system or a link. Mostly, we don't write links `https://www.google.com`, we only write `google.com`. Additionally, we mostly don't write paths like `C:\\Users\username\Documents\folder\subfolder\image.jpg` but rather only `image.jpg` (if the image is in the same folder).

No computer can decide if you *meant* to link to some website or to a local file.

I have now added an exception that if you have something along the lines of `image.jpg` in your files, Zettlr will nudge itself to search for a local file instead of looking on the internet.

To be sure, always add `./` in front of relative paths to indicate to the software that it's indeed a local path, not something on the internet.

See the relevant FAQ entry: https://docs.zettlr.com/en/faq/#what-is-the-correct-uri-formatting-for-markdown-links

**Comment by tfr00** [comment]
Thank you for the quick answer. 

I already had tried full paths but with no success. The thing is that it worked as it is before updating to 3.0.8. No changes were made. (Problem 1)

Also adding an image per drag and drop to a md-file does not work either after updating to 3.0.8. Windows is giving me the "Could not open workspace"-Error from the Windows-notification center as I try to drag an image to any md-file and the logfile says: "[Error] Could not open new root PATH" (the PATH given in the log file is the origin of the image e.g. d:\images\xyz.png while my Zettlr-workspace with other images, md-files etc. is in eg. e:\memex\...) (Problem 2)

I expected Problem 1 and 2 to be interrelated.
