### ISSUE TITLE
bring back titles for tabs in settings

### ISSUE THREAD

**Issue by derWalter** [Zettlr/Zettlr#4568]
### Description

I seldom have to use the settings menu, but every time I really struggle to find stuff, because all I have for orientation are the icons. in 9/10 cases I end up clicking trough many sections because I am never sure if I just missed it or if its simply not there.

for instance, there are three icons which are symbols for writing/text, I mean wtf :P
![image](https://github.com/Zettlr/Zettlr/assets/158642/48d005c4-81ae-4717-b203-d3b94a1de623)

### Proposed Changes

please bring back the titles under the icons for the sections of the settings

### Caveats

not so minimalistic anymore (but way more useful and quick)

### Do you Wish to Attempt Implementing this Yourself?

Yes

### Zettlr Version

Stable (most recent version)

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Operating System Version

win11

### Additional Information

<3 Zettlr!

**Comment by derWalter** [comment]
I wrote this because I am looking for five minutes now for this: "In the preferences you can tell Zettlr to avoid opening new tabs if possible." (_Source: https://docs.zettlr.com/en/core/tabs/#tab-behavior_)

I think I've read EVERYTHING from the settings now, but still cant find it >.<

**Comment by nathanlesage** [comment]
The tab titles are always shown when the preferences window is wide enough. But rest assured: one of the first projects after 3.0 release will be a reorganisation of the preferences because it's way too cluttered anyhow.

The documentation contains all settings and where they are located in a searchable way under reference -> settings, see https://docs.Zettlr.com

**Comment by derWalter** [comment]
I wanted to try it on my Zettlr Installation on Linux KDE Neon, actual .deb file from zettlr website, and there are NO symbols at all, only text, other problem there is, if I condense it vertically, it just hides the titles for which there is no space left :D

software development :palms_up_together: :+1:

**Comment by nathanlesage** [comment]
I think on Linux the Gnome HIG indicated that tabs should only have text, no symbols … if I remember correctly I tried to be overly correct with that layout. But be that as it may, there's gonna be changes incoming, so we won't have to worry about inconsistencies anymore!

**Comment by derWalter** [comment]
i want to confirm that the titles are there, if I widen the window a little bit.

I would like to add, that it would, at least in my perspective, an improvement,
if the titles text would be rendered (centre align) below the icons, therefore the would be
visible most of the time, without having to extend the window unnaturally (unintuitively) wide.
this would also fix the missing space between icon and title text, as it is right now.
![image](https://github.com/Zettlr/Zettlr/assets/158642/05c8f5cb-55d6-4ea1-836b-63434fa6517e)

<3 for the devs

**Comment by nathanlesage** [comment]
> if the titles text would be rendered (centre align) below the icons, therefore the would be
visible most of the time, without having to extend the window unnaturally (unintuitively) wide.
this would also fix the missing space between icon and title text, as it is right now.

Well, that was actually what the Windows 10 guidelines said to do – but I guess that's why they now reworked that bit :D 

This project is definitely up on my priority list so it'll hopefully launch sometime beginning next year!

I'm going to close this issues as the titles are definitely there, even if hidden at times ;)
