### ISSUE TITLE
[ENHANCEMENT] Add option to render soft breaks as spaces

### ISSUE THREAD

**Issue by Benjamin-Lee** [Zettlr/Zettlr#457]
## Description

Display Markdown like this:

```
Sentence one.
Sentence two.
```

as 

```
Sentence one. Sentence two.
```

## Proposed Changes

I am thinking that this would be a feature switch in the display preference pane. 

## Caveats

Nope.

## Additional Information

This is a key feature preventing me from dropping Typora for Zettlr. I use [SemBr](https://sembr.org) and rendering each sentence on a different line is pretty distracting.

**Comment by nathanlesage** [comment]
If I understand your request correctly, you are requesting that when you insert a single line break, it should be rendered only separated by a space. And this is exactly happening: Text written in Zettlr, when you only add single line breaks, will be concatenated using spaces in your final output. Just as the SemBr recommendation says. If you will, Zettlr is fully SemBr-compliant. If I did in fact misunderstood, please comment and we can reopen this.

**Comment by Benjamin-Lee** [comment]
Sorry for being unclear: I want an option to *display* soft breaks as spaces in the editor. For example:

```markdown
<!-- example.md -->
Hello world.
This is a second sentence.
And this is a third.
```

Typora: 
<img width="1502" alt="image" src="https://user-images.githubusercontent.com/13618205/71775642-33ffc000-2f41-11ea-8cbd-ec7035c599bd.png">

Zettlr:
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/13618205/71775671-f7809400-2f41-11ea-96ac-16176762bfb7.png">

**Comment by alerque** [comment]
How can you possibly _edit_ a file without the breaks shown? Wouldn't they get lost any time you edit over where there is a break? How would you insert a new one? That Typora screenshot looks more like an output preview rendering an input editor view.

**Comment by Benjamin-Lee** [comment]
That's the input editor view!

**Comment by Benjamin-Lee** [comment]
Here's a pic in source code input mode as opposed to interactive input mode (which is closer to what Zettlr does):

<img width="1502" alt="image" src="https://user-images.githubusercontent.com/13618205/71775792-08320980-2f44-11ea-9851-b3faf5f1a813.png">

**Comment by Benjamin-Lee** [comment]
And a video demonstrating inputting text with soft breaks rendered as spaces:



![](https://im7.ezgif.com/tmp/ezgif-7-477b5b3d0814.gif)

**Comment by alerque** [comment]
Can you _add_ breaks in that mode? Is there any visual indication of what is a line break and what is a real honest space? Can you tell when you've deleted one? I don't see any of these things there and I don't see how it would work in the context of Zettlr at all given that it is a source editor less towards the WYSYWIG visual editor side of things and more towards the syntax-highlighted source code side of things (which is precisely why I have people use it in the first place—I need copy editors to to edit shared Markdown files without mucking up the code, but I can't exactly teach everybody to use `neovim`).

**Comment by Benjamin-Lee** [comment]
>Can you add breaks in that mode?

Nope. 

>Is there any visual indication of what is a line break and what is a real honest space? 

Not beyond `<space><space>` for `<br>` and `\n\n` for `<p>`.

>Can you tell when you've deleted one?

Nope.

>I don't see how it would work in the context of Zettlr at all given that it is a source editor less towards the WYSYWIG visual editor side of things and more towards the syntax-highlighted source code side of things

My thought would be that this would be an option (probably set to off by default to prevent just the kind of mucking to which you are referring). Right now, Typora is the only editor with this feature and it's what's preventing me from switching. The main advantage of SemBr is that it makes for clean git diffs. I could in theory emulate this via [textlint-rule-one-sentence-per-line](https://github.com/Lab41/textlint-rule-one-sentence-per-line) as a pre-commit hook and then revert it to "anti-SemBr" (all sentences on one line) as a post-commit hook to make it look nice in Zettlr.

**Comment by alerque** [comment]
Eureka! Actually git smudge/clean filter pair for doing just that might be awesome! It wouldn't be a silver bullet but it would ease the pain of choosing between methods for *some* workflows. I'm interested in [making a project to do just that, care to join me?](https://github.com/alerque/git-filter-sembr) My biggest issue is it's going to need to work in languages besides English to be useful to me...

**Comment by Benjamin-Lee** [comment]
I’m down! For textlint-rule-one-sentence-per-line, I used sentence-splitter <https://github.com/azu/sentence-splitter> but for this it might make more sense to use pragmatic_segmenter <https://github.com/diasks2/pragmatic_segmenter>.

**Comment by nathanlesage** [comment]
Ah, now I get it. I wanted to include that in my first answer, but decided against it: This is precisely the behaviour why I thrashed Typora and went to write my own editor: I personally want an editor that shows me the source file as is with only those elements rendered/looking nice that actually have a benefit. For instance, you don't want to see the full URL of a Markdown-Link (`[Text to be shown](the link)`), but only the text itself. You want image previews. But you don't want _all_ formatting to be hidden, as Typora does, because then you get directly where Typora is going.

Here are some thoughts that undergird the philosophy of Zettlr:

- What you see is what you _mean_, without dictating what you will necessarily get. You _mean_ to type a header, but you might want it in another font during export. You _mean_ a blockquote, but depending on whether you put it on your blog, or write a paper, you will want to have it styled completely different.
- Hiding all underlying formatting will get you run into problems. For instance, one major thing that bugged me _every time I'm using Word_ is that when you have something emphasised within your sentence, and then want to add a word, you are prone to accidentally set your cursor inside the emphasis instead of outside of it, rendering the next word, which you don't want to have emphasised, in italics.
- Zettlr, therefore, is an editor that tries to find that very narrow sweet spot between displaying formattings in a way that seems reasonable with regard to final output without hiding the underlying source code completely. So whenever you see a rendered element and have worked with Markdown/Zettlr for at least one week, you will instinctively know what's the sourcecode behind what you are actually seeing.

What Typora does, and what prompted me to go away from it, is that it tries to be as close to a WYSIWYG-editor as possible. This is also the reason why it will remove single line breaks in the WYSIWYG-mode. Markdown specs state that single line breaks within standard paragraphs will be removed, while double line breaks will create a new paragraph. If you're in WYSIWYG mode and press Enter, it will indeed add two line breaks instead of one, and hide other line breaks.

After all, to drive the point home: SemBr's intent is to enable you to write as you _semantically mean it_, while not tampering with the output. You wouldn't want to hide this during composing a text, only in the final output (which is exactly what SemBr is writing in their specs, and it makes total sense to me). Therefore, long story short: The switch "Source Mode" <-> "Visual Mode" in Typora is the same as when you trigger the Print Preview in Zettlr. The way Typora does it violates one of the fundamentals of Markdown, that is: You see what you mean without "guessing" what the user may want. Nothing in Zettlr will tamper with what you write, the way it adds some characters automatically is fully transparent, while I do not see this in Typora.

This is why the specific feature you desire will not be part of Zettlr. I hope you understand and hope that you don't completely ditch Zettlr now :) But I think, while our Markdown editors (Typora, Zettlr, Abricotine, Notable, and the like) copy quite a lot of functionality from each other, they shouldn't be too close to each other because then what's the point in having all these options!
