### ISSUE TITLE
List bullets slightly misaligned

### ISSUE THREAD

**Issue by kyaso** [Zettlr/Zettlr#4607]
### Description

Bullet points are slightly aligned to far to the left, see below:
![image](https://github.com/Zettlr/Zettlr/assets/18646029/ede47009-d5c4-4edc-b621-354d37889c2c)

### Reproducing

Simply create a list and compare the offset to regular text.

### Zettlr Version

Stable (most recent version)

### Installation Method

None

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Manjaro

**Comment by nathanlesage** [comment]
Could be that the `basePadding` is needed after all after the measurement happened …? I find it difficult to observe this given that it's probably only 4px wide. Would you mind testing this …?

**Comment by H6nry** [comment]
If the issue annoys you very much, I found a quick and dirty workaround. So far (2 h light working) I didn't find any adverse effects, but I don't guarantee for anything. Adding the follwing to the custom CSS in the Assets Manager makes all bullet points aligned with the rest of the text again:

```
.cm-line {
  text-indent: 0px !important;
  padding-left: 0px !important;
}
```

I'm not sure why the bullet points do have the text indented by minus X pixels first, then padded back by plus X pixels in the first place. But maybe @nathanlesage can shed light on this.

---- 

Okay, I found at least one unintended behaviour with this workaround. If you set your indentation to "tabs instead of spaces" in the Editor settings, you'll get half-indented bullet points. No adverse effect with space indentation, though.

**Comment by nathanlesage** [comment]
> I'm not sure why the bullet points do have the text indented by minus X pixels first, then padded back by plus X pixels in the first place. But maybe @nathanlesage can shed light on this.

Basically, I'm setting a padding-left to the correct indentation, then pull the first line (`text-indent`) to the right again until the first letter of the bullet aligns with the second and third etc. lines.

**Comment by nathanlesage** [comment]
I can't observe this behavior anymore, and with the "dancing list items" problem gone, I assume it probably works across the board. If not, please just reopen the issue!
