### ISSUE TITLE
Loss of data in tables after interaction

### ISSUE THREAD

**Issue by WoodenMaxim** [Zettlr/Zettlr#4615]
### Description

Tables are currently quite buggy, and using them can irreversibly delete data within it and around it just by typing. See the video for a demonstration:
[https://www.youtube.com/watch?v=nwA0URKAbl4](https://www.youtube.com/watch?v=nwA0URKAbl4)

### Reproducing

1. Leave some space before the table in a new document,
2. Create any size of table and type some text into it,
3. Either type and text before it or type any text right after it and the text in the table gets deleted irreversibly (as in, control-z doesn't reverse it)

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.0

### Installation Method

Homebrew

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

MacOS Ventura 13.4.1 (c)

**Comment by jdnicholas** [comment]
This is probably happening because I think when using the table editor, you need to save the table before moving away from it and editing the rest of the file, either by clicking the Save button, or using Ctrl/Cmd+S - see here in the docs for details: https://docs.zettlr.com/en/core/tables/#editing-tables

I think @nathanlesage mentioned in the Zettlr discord he had plans to make the table top bar more visible to make it clearer when tables weren't saved, and data might be lost

**Comment by nathanlesage** [comment]
Exactly what @jdnicholas wrote. I am aware that the Table Editor is a little bit iffy to work with, but I don't consider this a bug, since the saving of the table content works flawlessly, even though there is one additional step involved. I cannot promise if and when there will be a remedy for that, but until then it works fine.
