### ISSUE TITLE
"Save" silently fails!!

### ISSUE THREAD

**Issue by kerryland** [Zettlr/Zettlr#4628]
### Description

When I press CTRL-S Zettlr writes to the file system, but it does not always write what is in the editor's buffer. This is a massive problem!

Attached is a screen capture shows:
- I manually add "AAAA" to the start of my "00150-petrenko..." file
- I press CTRL-S, and you can see the timestamp update in file explorer, changing from 2:14 to 2:19
- I also use "File|Save", just to give you a visual indicator. As an aside I'm quite sure that "File|Save" sometimes does NOTHING at all, but CTRL-S always writes the file (although perhaps with the wrong content).
- I open the "saved" file in a text editor, but you can see that the "AAAA" text is missing from the file.

https://github.com/Zettlr/zettlr-docs/assets/398113/94d09b14-c02d-43c6-94ae-a038eccced54

Not in the video, but I then closed Zettlr and silently lost the "AAAA" change.

I had _Autosave_ set to "Immediately", and suspect that this is somehow related. I noticed that after a fresh reboot of Zettlr that the file was being saved almost after every keystroke, which was not the case when I made the video.

### Reproducing

Not sure.

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.0 (UUID: 6c414122-4a3a-48c7-a6f3-cec55b393258)

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

win32 10.0.19042 (architecture: x64)

**Comment by nathanlesage** [comment]
Does auto save work more reliable if you set it to "after a short delay"?

**Comment by kerryland** [comment]
I will give it a try and report back.

**Comment by kerryland** [comment]
I've been using it all day today using "after a short delay" and have not encountered this bug with saving.

**Comment by kyaso** [comment]
Did you edit this file ever _outside_ of Zettlr by any chance?

After the 3.0 update, I was running into a similar issue on my setup: I have a script which edits one particular every time before Zettlr is launched. This works fine on my Linux machine. However, on my Windows machine, after Zettlr was running, any subsequent changes made to that file in Zettlr, were not saved. Like in your video, the "file changed" tab indicator (*) was not showing while editing the file. And after exiting Zettlr, the changes were gone.

I found out that it had to do with LF/CRLF line endings. On my Windows machine, the script (written in python) used CRLF endings when writing to the file. Zettlr (I believe) likes LF (which is also default on Linux). This confusion probably lead to some internal error, preventing any modification within Zettlr. I fixed the issue by making sure that the script writes LF line endings.

**Comment by kerryland** [comment]
> Did you edit this file ever _outside_ of Zettlr by any chance?

Almost certainly.

**Comment by StuporMundi1337** [comment]
Hello, this morning I encountered similar behaviour, although I'm not sure, if it's the same problem. 
After the update to Zettlr 3.0 (great work btw!) I've been writing into a file with "auto save after a short while". In a two hour period the file reset twice to a former state, killing my work of around 40 minutes. 
The first time it happened on auto save (the asterisk in the file tab disappeared, as did the last paragraphs I've been writing), literally while I was thinking about what to write next. The second time it happened on click into another section of the file.
Interestingly and unfortunately the file didn't reset to the last save, but into a former version, that was there for a longer time (I'm working with the pomodoro technique (not with the Zettlr integrated timer, however), and it reset twice to the file version BEFORE the 5min break). This is just an observation and I have no absolutely no idea how the saving process works, but could it be that the saving process takes a while/isn't working correctly and certain actions take the file back to the last "definitely" saved version? 

I think this is highly unfortunate, since it happend twice in about 2 hours this morning.

**Comment by kerryland** [comment]
I haven't provided any updates on this problem because I've stopped using zettlr. It looks great, but if it can't be relied upon to save my file (which is my #1 requirement in a text editor), then I just can't use it.

I looked at the "save" logic in the source code and discovered it's very complicated -- lots of opportunity for failure :-(

**Comment by nathanlesage** [comment]
> I looked at the "save" logic in the source code and discovered it's very complicated -- lots of opportunity for failure :-(

… which is why I'll be prioritizing the issue now. If it had been just a small unrelated incident, all good, but as you mention, there should be no data loss whatsoever.

@kerryland, I would like to invite you to return and use a manual saving strategy instead of the autosave. If I've now burned your trust, I can understand this, however.

I can guarantee that manual saving does not lead to data loss (I'm only using manual save, I don't like autosaving, and I haven't had any data loss in the past three years with upwards of a thousand different files). I have the feeling that the autosave process is still too fragile at this point. Users have asked for it, but I think I will have to get back to the drawing board, because the only two options to prevent data loss altogether would be to either remove autosave, or fix the process.

@kyaso keeping you in the loop here; currently my thought is the following: The only explanation for why there is no data loss in manual save, and so often in autosave is that users type something exactly at the very precise moment that the app saves. In other words: While a file is being written down, it changes in memory, so when the app checks for the inevitable "modified" event from the file system watchdog, it will see that there's a mismatch between the two and then always revert to the saved file instead of overwriting newer changes. In order to make the entire logic much less brittle, I first wanted to entirely separate the document authority from the documents provider as well as the FSAL, and then get to fixing this.

**Comment by kerryland** [comment]
> @kerryland, I would like to invite you to return and use a manual saving strategy instead of the autosave. 
> I can guarantee that manual saving does not lead to data loss (I'm only using manual save, I don't like autosaving, and I haven't had any data loss in the past three years with upwards of a thousand different files).

You have succeeded! I like your attitude :-)

**Comment by nathanlesage** [comment]
Thank you very much, that is very nice :)

I promise to solve these problems asap; I like to have happy users!

**Comment by kerryland** [comment]
I have returned to Zettlr, but have bad news. I'm not convinced it's an autosave related problem, rather it's thinking that the file is read-only, or something, when initially loaded. Anyway, here are the steps I went through, although I am unable to reproduce it again. 

- Firstly, I created a file in Typora
- Then I thought **NO** -- I will use Zettlr
- Open Zettlr
- Turned off auto-save immediately
- Updated to 3.0.1
- Open file in Zettlr
- Make changes to file
- Save it (ctrl-s)
- Preview it (ctrl-p)
- Notice changes do not appear
- Open file in vim
- Changes are not on disk!
- My explicit save did not work.
- Change some more in Zettlr
- Notice that there is no little asterisk indicating file has changed
- Go looking for "auto save" to make sure it's turned off, but can't find it.
- Switch to another tab, showing a random old file I had been editing long ago
- Insert some text
- Notice the little asterisk appears
- Saving it via ctrl-s seems to work fine
- Realise that Typora is still open, editing the file.
- Close Typora.
- Makes no difference. Zettlr still not recognising changes made in the editor, even when explicitly ctrl-s.
- Close the tab. Seems to be gone.
- Reopen from the "Files" panel on the side.
- Changes are STILL not recognised (no asterisk, and nothing saved)
- Exit Zettlr completely
- Open Zettlr again
- Reopen from the "Files" panel on the side.
- Asterisk now appears on changes, save is successful

PS: vim command ":w" also doesn't save the file, but I think that's unrelated to the core problem.

I hope this helps.

**Comment by kyaso** [comment]
> Notice that there is no little asterisk indicating file has changed

So, this is also what I observed in my [comment](https://github.com/Zettlr/Zettlr/issues/4628#issuecomment-1713663726) above.

@kerryland, could you enable logs (Settings -> "Advanced" -> "Enable debug mode"), then try to reproduce the situation where making edits to a file in Zettlr does _not_ show the "file changed asterisk". Then try to save the file manually and after that open the logs (in the toolbar at the top "Devolop" -> "Open logs"). When I reproduce this on my end, there is indeed an error:

> [R] [Main Window (7543f801-f097-42d6-980d-471e804d6402)] Pushing updates failed: Error invoking remote method 'documents-authority': RangeError: Applying change set to a document with the wrong length Error: Error invoking remote method 'documents-authority': RangeError: Applying change set to a document with the wrong length (index.js:2)

Update: I was writing the steps to reproduce the error (basically create externally a file with CRLF endings, open it in Zettlr, try to edit it -> no asterisk), but for some reason, now the editing works without issues no matter what I do... weird.

---

@nathanlesage In case the line endings are indeed what's causing the issue, could this be somehow related to what's mentioned in the [CM system guide](https://codemirror.net/docs/guide/) (under the "Document Offsets" section)?
> CodeMirror uses plain numbers to address positions in the document. These represent character counts—more precisely, they count UTF16 code units (so astral characters count as two units). Line breaks always count as a single unit (even when you [configure](https://codemirror.net/docs/ref/#state.EditorState%5ElineSeparator) a line separator that is longer than that).

This sentence:
> Line breaks always count as a **single** unit [...].

Would kind of fit the error above, which complains about "wrong length".

Not sure if it makes sense though, just wanted to throw it in.

**Comment by kerryland** [comment]
![image](https://github.com/Zettlr/Zettlr/assets/398113/08a585a3-808c-4b98-86c9-04e7893a8fa4)

Here's how I reproduced it, with `vim` mode enabled:

- Create a text file outside of zettlr with multiple lines, eg: [hello-world.txt](https://github.com/Zettlr/Zettlr/files/12707256/hello-world.txt)
- open the file inside zettlr
- press 'aaa'
- You should now see "haaello" in the editor, but no "change" asterisk, and broken save functionality.

**BEWARE** that there is all sorts of behind-the-scenes remembering going on. If you quit zettlr and reload it will load the file fine and 'asterisk/save will work correctly -- you need to start with a fresh file.

Also (and maybe this is a separate bug), while trying to reproduce this, I deleted the file from within Zettlr, but when I went to quit it warned me that I had unsaved files. Just for a laugh, I said yes, and the "deleted" file was saved back to the file-system containing earlier "lost" edits that had not just been displayed on the screen, *and* it decided to save the contents of other random tabs that were also open in Zettlr, changing their end-of-line characters (and nothing else, because they hadn't actually changed)

**Comment by nathanlesage** [comment]
@kyaso Feel free to have a look at the code, but I am fairly certain that I didn't bork the line feed changes. Basically, CodeMirror is *always* using LF endings, and Zettlr uses those internally as well, *except* for reading and writing files where Zettlr detects the line ending and only uses that again when it writes down the document to disk. I may have made an error, but I highly doubt it.

Then, the readonly thing could be one case (maybe Typora opens a file and locks it on the OS level?), because Zettlr currently doesn't detect readonly flags on the files. This would be a thing for an enhancement.

**Comment by kerryland** [comment]
> maybe Typora opens a file and locks it on the OS level?

It doesn't

**Comment by nathanlesage** [comment]
Hmhm, so … I think a first thing I'm going to do is separate the document provider from the rest of the file managing stuff. This will make a few tiny edge cases harder, but allow me to implement a proper state management that will hopefully fix these issues. Might take a while but I'll open a PR soon-ish. @kyaso I'll require definitely a code review for that once it's done …

**Comment by StuporMundi1337** [comment]
Just a quick heads up, because maybe the other problem is related: I could now reproduce the auto save bug with manual saving...
https://github.com/Zettlr/Zettlr/issues/4670#issuecomment-1736881600

**Comment by dd86k** [comment]
Sorry for bumping this, but I noticed that since I use Nextcloud for my workflow, the default timeout of one second came to clash with Nextcloud's file locking mechanic and making all future saves for all files silently failing.

I resolved my issue by setting the timeout to 5 seconds to avoid both of them clashing together. At least, hopefully, didn't see any fail for the few sessions I had.

Hoping this helps others in the future reading this.

**Comment by khakhalin** [comment]
I just installed Zettlr on a third computer in a row, and got this wild bug, for the first time ever. Everything worked smoothly on Mac and Win10, but now a new install on Win11 Pro - and I edited files for quite some time before realizing that all edits were lost (were only in the memory). No asterisks ever appeared. And because they never appeared, auto-saving also never appeared (it seems that Zettlr just wouldn't even notice that the file was changed). And a dialog on closing Zettlr never appeared as well.

Now, doing Ctrl-S manually DOES save the file (it is just that you, as a user, aren't aware that you even should press Ctrl-S, as there's no asterisk). Moreover, if you save the file manually at least once, and then reload Zettlr, this file does becomes "visible" to the asterisk system (it starts to behave normally for this file). But not until then.

Do we have any sort of project-wide solution for this bug? For how to make Zettlr recognize the files as its own? Can we, like, bring along some smell from the old nest or something? Coz opening every file manually and saving a trivial edit would take me weeks...

**Comment by khakhalin** [comment]
Update: I'm no longer sure that registering edits once (aka, showing the asterisk near the file name ones) solves the issue permanently, as I think I just got one of my files becoming untracked again. But I save the content to clipboard, reloaded Zettlr, and it became trackable again. It's a bit of a mystery, it seems...

**Comment by nathanlesage** [comment]
@khakhalin Could you please copy what you've written two days ago into the Autosave issue? This all belongs to a single issue and the more info is in this thread, the quicker will I be in finding the bug(s) and fixing them. This one: https://github.com/Zettlr/Zettlr/issues/4959

**Comment by nathanlesage** [comment]
I just tried this very specific bug out once more and regardless of what I tried I couldn't reproduce it (using the immediate autosave). Please try out the new nightly that just released and see if you can keep edits stable saved to disk. If not, please comment on the new "main" saving issue: #4959

**Comment by nilsi01** [comment]
Same bug here :(

**Comment by khakhalin** [comment]
Hi everyone, just a small update: I finally updated Zettlr (to 3.1.1), and the problem only got _worse_, not better :( Now if I try to edit a file that wasn't edited before (a file that was only cloned from git, but not yet edited locally) I have an error message saying "Document out of sync. Your modifications could not be applied to the document in memory. This means that saving might fail"

And indeed, the saving fails. And if I turn Zettlr off and reload the document, it doesn't get "healed" as before, but remains uneditable :(

Any suggestions for how to deal with it?

**Comment by nathanlesage** [comment]
@khakhalin Please switch to the nightly! There was a really stupid error I made, especially for Windows line endings ([see this article for background](https://www.hendrik-erz.de/post/how-hard-can-line-endings-be-really-a-horror-story-from-integration-hell)), and that has only been fixed in the current nightly. I'll get to pushing an update soon!
