### ISSUE TITLE
Table content gets deleted

### ISSUE THREAD

**Issue by derWalter** [Zettlr/Zettlr#4637]
### Description

when placing a level 1 header above a table, the content of the table gets deleted,
watch the video: https://youtu.be/DxIwXYECFMA

I had to redo the table 3 times as different actions lead to the deletion of the contents.

also ctrl+z deletes the table entries (didnt record)

### Reproducing

place a level 1 header above table

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.0.

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11 Pro, Version: 22H2, Build: 22621.2215, Windows Feature Experience Pack 1000.22662.1000.0

**Comment by derWalter** [comment]
I will now switch back to the old version, as I need to work on stuff and cant provide any more information about zettlr 3.0.0, due to its bugyness ;)

**Comment by nathanlesage** [comment]
Please watch your video again. You will notice that the "disk icon" symbol on top of the table has a red background. Please read the manual which states explicitly that this indicates that there are unsaved changes. You need to click this icon first before leaving the table as it otherwise will remove all the contents.

We can now start an unproductive discussion about the indisputable fact that this is really bad user experience, of which I am aware, but I find it a bit disrespectful, calling a feature buggy when its Problem is unfriendly ergonomics. Which, again, I am fully aware of.

**Comment by esyo** [comment]
Also unfortunately deleted an hour of work for me which was a bit painful, it would be good to warn users their table data isn't save explicitly. Not many users will be reading the manual I imagine. Cool stuff otherwise!

**Comment by derWalter** [comment]
this should be solved  with the arrival of 4.0.0, right?

**Comment by nathanlesage** [comment]
Yes, indeed
