### ISSUE TITLE
Internal Links are not recognized as such when using custom titles

### ISSUE THREAD

**Issue by pedroarnal** [Zettlr/Zettlr#4649]
### Description

When I add a custom title to an internal link, the link is no longer recognized as a link:
* no ctr+click
* no hovering preview
* linked documents do not appear in the related files pane

This worked ok in the 2.3 version.

I've searched the changelog, and found no references to this change. The current documentation does not say anything about custom titles for internal links.

### Reproducing

Freshly installed zettler via brew on macOS, default configuration. Previous zettler version configuration deleted.

Create a note `20230913123116.md`:

```
---
id: 20230913123116
---

# Test File 1

Test file 1.

```

Create another note `20230913123307.md`:

```
---
id: 20230913123307
---

# Test File 2

line 1: Test file 2 links to [[20230913123116]] Test File 1.

line 2: Test file 2 should link to [[20230913123116|Test File 1]].

````

Ctr+click on 20230913123307.md line 1 link opens 20230913123116.md.

Hovering on 20230913123307.md line 2 link shows:

![Screenshot 2023-09-13 at 12 41 11](https://github.com/Zettlr/Zettlr/assets/860007/fd1a0e70-976c-4666-814a-7998cb7b3f0c)

Ctr+click on 20230913123307.md line 2 link has no effect.

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.0

### Installation Method

Homebrew

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Big Sur 11.7.9

**Comment by nathanlesage** [comment]
> This worked ok in the 2.3 version.

There is no way this worked. Zettlr never supported the pipe-syntax to create titles for internal links, it has likely just created a whole bunch of files. Are you really sure this syntax worked? Because I am 100% sure it did not open the file `20230913123116.md`, rather, it may have opened some file along the lines of `20230913123116|Test File 1.md`

**Comment by pedroarnal** [comment]
It worked, but you are right in that it was not supported.

I used the Zettlekasten > Link ending configuration option with the value "|".  When creating new links zettler added the closing tag ']]' anyway, and a space after the pipe (`[[20230913123116| Test File 1]]`).

As I often edit the custom title in the link I was not "aware" of actively fixing that extra space 😓 .

With that setup ctrl+click and note preview worked:

![Screenshot 2023-09-17 at 14 34 12](https://github.com/Zettlr/Zettlr/assets/860007/e41141f8-9e0f-4851-85c7-ea498ae25482)

Sorry, my fault for not remembering my 2.3 configuration and not checking it before 😓 

Any plans about supporting custom titles and/or link directionality in wiki links?

Thanks!

**Comment by nathanlesage** [comment]
Link directionality is already supported. Titles ... well, it's not a priority right now, but the demand is here.

**Comment by pedroarnal** [comment]
Nice to know :-D

Zettlr is my favourite note editor, by far. But js is not my main stack, much less for desktop with electron :-(

Anyway, I'll try to have a look.

**Comment by nathanlesage** [comment]
> Zettlr is my favourite note editor, by far. But js is not my main stack, much less for desktop with electron :-(
> 
> Anyway, I'll try to have a look.

I can understand, don't you worry. If you want to give it a shot, all the pieces should be already there. Most work should only be thinking about how users will use the feature. Here's a quick todo list if you want to attempt this yourself:

1. Familiarize yourself with this PR that adds this feature to Pandoc and how it works: https://github.com/jgm/pandoc/pull/7705
2. Implement an additional node type to account for titles (the pipe character should be a simple `CodeMark`), if you leave the rest untouched it SHOULD (hopefully) work out of the box with the rest of the code. This is possibly the most difficult part for you, but since this is a matter of 2 minutes for me, I can do it for you, if you do all the surrounding research and the documentation update.
3. Prepare an edit to the Zettlr documentation to outline (a) that this is now a possibility and (b) how to enable it during exports (by activating the corresponding extension).

So how do you want to do it? Separate workloads or do you want to try everything?

**Comment by pedroarnal** [comment]
> I can understand, don't you worry. If you want to give it a shot, all the pieces should be already there. Most work should only be thinking about how users will use the feature. Here's a quick todo list if you want to attempt this yourself:

Thank you for the info!

I'll give it to the full thing try next week.

**Comment by nathanlesage** [comment]
Perfect. One complication I just realized is: Since there is no way for the parser to differentiate titles from filenames or IDs, users would need to change a preference setting first that would then affect what the parser detects as what – this will make the parser implementation much more difficult than I anticipated. Does this change your plans?

**Comment by pedroarnal** [comment]
I don't know yet, but note taken.
