### ISSUE TITLE
[ENHANCEMENT] Better typographic hierarchy

### ISSUE THREAD

**Issue by richardbatty** [Zettlr/Zettlr#465]
I find it hard to distinguish between different levels of headings (h1, h2, etc) because they look so similar to me. For structuring documents, it would be useful if they were more clearly distinguished. The hierarchy could be based off google docs if you don't want to invent one from scratch.

**Comment by nathanlesage** [comment]
Well, the main indicator in my opinion is to simply look at the formatting characters which are big and countable, hence you can see the level this way. Nevertheless, if you want to propose GUI changes, please refer to the respective issue so that we can tackle this in the big GUI rewrite: #448 

I'll be referencing this issue & close this so we can keep it focused on that issue!
