### ISSUE TITLE
[ENHANCEMENT] Windows warns for installation due to unknown publisher

### ISSUE THREAD

**Issue by keunes** [Zettlr/Zettlr#473]
## Description
When installing on Windows 10, the OS shows a warning screen: "Windows Defender SmartScreen prevented an unrecognised app from starting. Running this app might put your PC at risk."
It notes "Unknown publisher", which might be the reason why it's blocked. When users click on 'More information' they're able to click "Run anyway".

## Proposed Changes
Maybe ensuring publisher is encoded will prevent this warning? Similar issue in another project: https://github.com/getferdi/ferdi/issues/112

**Comment by nathanlesage** [comment]
Yeah, this is a known issue, of which I also warn when you download a Windows installer from the main page:

> **Dear Windows & macOS users**: Both Apple and Microsoft employ code signing technologies to verify the authorship of the installers. Due to technical reasons, **Zettlr's installers are not signed**. macOS and Windows (10 or newer) will therefore warn you that the developer's identity cannot be verified. In case of installers downloaded from this page or the official GitHub releases page, you can safely ignore this warning.

Concerning this and the somewhat ominous "technical reasons":

- Until recently I wasn't able to afford the necessary certificates. Now I do, but:
- I still need to figure out a provider where to receive a Windows 10 compatible code signing certificate from
- I have to set up CI w/ either GitHub Actions or Travis so that the builds are running automatic
- As soon as that works, I need to apply code signing, which should be less problematic.

I know that this is one of the most pressing issues for new users, and I have that on my mind!

**Comment by jrcharney** [comment]
I find installing Zettlr using [Chocolatey](https://chocolatey.org/search?q=zettlr) solves this issue. Primarly because you have to login using an Administrative PowerShell to install both Chocolatey and Zettlr.  Installing Chocolatey is usually a good excuse to change Window's security policy especially if you are installing software on your personal computer and not one for school or work.

**Comment by keunes** [comment]
> if you are installing software on your personal computer and not one for school or work

And it's exactly there (at work) that I was trying to install Zettlr :)

> warn when you download a Windows installer from the main page

Ah, I had completely missed that message (just saw it now, when checking) as I clicked 'download' on the homepage and the message is hidden on the download page by the Donation modal ;)

> Concerning this and the somewhat ominous "technical reasons"

Ah, that's a few steps before it will be in place. But at least it seems you well know what you're doing :)  Reading up a bit on signing apps, I came across [this page](https://blog.kowalczyk.info/article/lh6f/buying-a-certificate-for-signing-windows-applications.html) of the developer of [this app](https://github.com/sumatrapdfreader/sumatrapdf), for what it's worth.

**Comment by keunes** [comment]
kssst, go away bot. It's still relevant.

**Comment by nathanlesage** [comment]
Should be fixed now that the releases are all code-signed.

However, in order to get rid of ALL warnings, we need a certain amount of downloads and installations. However, Microsoft remains silent as to the actual amount needed, so all we can do here is pray.
