### ISSUE TITLE
[ENHANCEMENT] in-app explanation of what Zettelkasten is

### ISSUE THREAD

**Issue by keunes** [Zettlr/Zettlr#474]
## Description
I found Zettlr when looking for a Markdown editor and I love it. I guess due to its link with (social) sciences, there's something called Zettelkasten, which I came across in the settings. After reading the description there, I still don't know what it is.

## Proposed Changes
Include in the existing paragraph one sentence explaining what Zettelkasten is/does, and/or add a link to more information. EDIT: I just found your [blog post](https://www.zettlr.com/post/what-is-a-zettelkasten) - that might be a sensible place to refer to (?)

**Comment by nathanlesage** [comment]
This would be a good thing to place in any "First Start Guide", as soon as we're getting to making one (which I cannot promise right now).

But a more fundamental problem is that nobody really knows what a Zettelkasten is; so you can't really explain it in short … I'm currently working on a retrofitted concept, but this can very well take a lot of time. So I'm closing this for now, but especially if you see the definitive need for a "First Start Guide", please open up a respective issue for that.

**Comment by keunes** [comment]
To be honest, I think this issue and a 'First Start Guide' are/deserve two separate issues:
- this issue is about providing the slightest bit of context to a Preferences tab users might not understand at all (as they - like me - were just looking for and downloading a Markdown editor)
- a First Start Guide issue would be about providing guidance to users that want to use Zettlr as a Zettelkasten and helps them get started (don't know if that's what you had in mind?)

So in that respect, I would be in favour of reopening this, with the concrete suggestion to mix two sentences you already published, which I believe, well summarizes the concept:
> What the concept of a Zettelkasten essentially boils down to is a way to manage your knowledge.
> The structure of a Zettelkasten is fairly easy described: It's a database. It is simply a place where you file your knowledge in a semi-structured way.
> Conceive of a basic, but consistent structure of your notes. Elements that have to be present everywhere, such as an ID, some tags to categorise your thoughts, and the contents.

For example: "Zettelkasten is a way to manage your knowledge, by consistantly structuring your notes with elements such as an ID and some tags." (followed by the existing text on the tab)

**Comment by nathanlesage** [comment]
Nah, I opt against this. Because after all, if they see the Zettelkasten tab and wonder what it is, the first impetus is to google it, which will explain it fairly enough (or read the manual). This runs counter to all other descriptions (which are more about "Here you can control the display/advanced options/general options of Zettlr") — these don't explain, but serve as a form of short intro.

A Quick Start guide also will **not** focus on what a Zettelkasten is, but on a general introduction to how Zettlr works. There we could place a hint "If you want to know more about Zettelkasten, look into the docs".

In the end, the descriptions and hints in the app shall never become a replacement for reading a manual.
