### ISSUE TITLE
[ENHANCEMENT] HR and em-dash processing without conflict of code blocks or YAML

### ISSUE THREAD

**Issue by jrcharney** [Zettlr/Zettlr#476]
OK, I've created this Enhancement Request so as not to see like I was threadjacking #147 

Not sure why I was being grilled for a short list of things I noticed while using Typora, espeically since I would have hoped the replies in that enhancement request would have been about Mermaid, not how Zettlr processes em-dashes.

So  let's clarify some things.

Typora doesn't process em-dashes. The reason it doesn't isn't because of a conflict of other features, but because they just didn't add it. (BTW, Microsoft Windows will also process em-dashes. Why they haven't gone to someone who makes a markdown editor and propose a buyout of their product at this point is unfortunate. I think Markdown is the next big thing in Word Processing even if we aren't producing a Word Processor.)

But getting to @alerque's [point](https://github.com/Zettlr/Zettlr/issues/147#issuecomment-574526373), using three dashes for an HR doesn't seem to be an issue in Typora, and it shouldn't be in Zettlr. 

That doesn't seem to be an issue on Typora, even more so since I'm not using YAML metadata at the beginning.

The YAML Code block should kick in **ONLY** if the **FIRST LINE** in the document is three dashes. The codeblock closes upon the next line that is online three dashes. For all other cases, three dashes acts as an HR.

If line 1 is a H1 and line two is three dashes, then it will process as an H1 on line 1, and an HR on line 2.

It wouldn't make sense to put a YAML block in the middle or at the end of a document. That would be like putting the `<head>` section of an HTML document after the `<body>`, which the rules of HTML state is not permitted.

I would imagine there would be some precedence in the order of which processing is handled in real time.

The YAML/HR issues is a block element issue.

Meanwhile, let's talk about  em-dash conversion.  In Microsoft Word, em-dash conversion is on by default, but there is an option to turn it off.  Dash conversion should be allowed at the preference of the user.

For example, if I wanted to inline something like `x--` or `--x` as part of a inline code block describing a decrement in C, C++, Java or some other language that uses those operators, the two dashes inside the code block would not process, and inline processing should not occur within the open code block. Such that if I type the back tick and type the two dashes followed by the variable, or if I typed the variable then typed two dashes, those dashes would not be transformed into an em-dash. Within this construct, dash-conversion is turned off. But if I close the inline code block with another back tick, em-dash conversion is enabled again, such that if I type two consecutive dashes outside of the code block, those dashes become an em-dash.

The best thing is, you've likely already written these rules in your program, you just need to modify them with different characters.

When text highlighting was implemented, you created a construct such that if text was surrounded by two sets of double equal signs (`==`) becomes highlighted.  I recently took some notes about the equality operators in JavaScript, of which two equal signs were put inside of an inline code block. The equal signs on the inside didn't not start a highlighting sequence outside the back ticks. They also didn't do that when I was describing strict equality (`===`).  So, there is a set of rules written already, that state that anything inside the inline code block should not be processed into its special function.

Ideally, these rules can be rewritten such that em-dash processing only happens outside of a code block.

Basically, some refinement of the rules would be good.

It is my understanding that em-dash conversion would occur if a word (which may or may not be part of an inline code or inline LaTeX), not separated by spaces had two or three dashes next to it, followed by another word (which may or may not be part of inline code or inline LaTeX would) would then process the appropriate hyphenation. If there are any spaces in front or behind this sequence, the conversion doesn't happen. The only exception of this conversion would be if the dashes were inside of a code block.

If em-dash works like this, imagine what else it could be used for.  I see that there are features to botch other symbols (most of which should be done in LaTeX or if the text editor's monospace font is set to Fira Code), but I don't see any macros for converting something like `n~` within a word into `ñ`. Again, such processing should only happen within words such that the `n~` has letter characters before and after that sequence. (If you've ever check out a Spanish or Portuguese dictionary, you'll find there are very few, if not no words that start or end with `ñ` or `ã`.)

And while the I can easily pull up special characters using the `Window+full_stop` sequence to show special characters and emojis, there's still plenty of people who's keyboard layout isn't set to an American English keyboard. (To be honest, I do wish I had that `Window+full_stop` feature back in college. Digitizing my notes for Spanish Class would have been like a walk through the park.)

Don't get me wrong. Em-dash processing is a good idea, but in appearance. If I looked at my markdown notes where there was an em-dash or en-dash made of two or three hyphens, it should look like two or three hyphens, but in a markdown editor like Zettlr, the appearance of these characters should be processed.

I just wanted to clear the air about this so there was better processing.

A markdown editor should store data as text, but the appearance of markdown, either in a markdown editor or website that uses something like Jekyll, should appear how the user wants it too look like.

**Comment by nathanlesage** [comment]
Thanks for opening the issue! First of all: I didn't want to make it seem as if you were "grilled", but the em-issue somehow stuck out of your comment, and I think this is why the whole dynamics of the talk went towards this. But now we have it separated, so it's perfect now!

Then to the three-dashes-issue.

Let me describe the algorithms, because then maybe you can directly spot any issues. The YAML frontmatter algorithm is different from any `<hr>`-processing. The algorithm works as follows:

1. Does the first line equal three dashes? Yes? Then BEGIN YAML frontmatter, and apply YAML syntax highlighting.
2. If we are in YAML frontmatter, check each line. Does it equal either `---` or `...`? Then STOP YAML syntax highlighting and switch back to Markdown mode.
3. Does the first line not equal three dashes? Then never enter YAML syntax highlighting.

I personally agree with you that YAML frontmatters should only reside at the top of any given Markdown file. However, and I [quote from the Pandoc manual](https://pandoc.org/MANUAL.html#extension-yaml_metadata_block):

> A YAML metadata block may occur anywhere in the document, but if it is not at the beginning, it must be preceded by a blank line.

As Zettlr will always put special emphasis on compatibility with Pandoc for various reasons, I have to adhere a lot to what Pandoc expects. The rationale behind this:

- Pandoc is already well-known and is used by a ton of people around the world. Thus, we would be reinventing the wheel if we did not make use of all of the great software that's already out there.
- John McFarlane is part of the CommonMark taskforce that set out to standardise Markdown, and as standardisation is always good, Zettlr should adhere to what Pandoc does (as Pandoc implements CommonMark).
- Even if someone should not be using Pandoc, it is the de-facto standard, hence other programs will feature some compatibility with its signature.

Zettlr does not syntax highlight YAML metadata blocks occurring somewhere in the document, mainly because it is not common (which is a good thing). But as soon as people start demanding this functionality, there's a very good chance that I'll amend it for this.

But now finally to the em-dashes! em-dashes, just as any other replacement character will be triggered by AutoCorrect. That means: Write `---` and on the next `Space` or `Enter` it'll be converted to —. Don't want this? Then you can either remove the corresponding entry in the replacement table or hold `Shift` while pressing `Space` or `Enter`.

Furthermore: Three dashes will always form a `<hr>`, as it's [mentioned in the CommonMark specification](https://spec.commonmark.org/0.29/#thematic-break). This is also baked into the underlying [`gfm`-mode provided by CodeMirror](https://codemirror.net/mode/gfm/index.html) (the Syntax highlighting, anyways). Yet, it might be that the three dashes are meant to be used as just three dashes, in which case the AutoCorrect would be unwanted. In this case, the `Shift`-modifier will do the job.

AutoCorrect has had also some improvements, so it does not trigger when in comments or in YAML mode (just like MagicQuotes, which are implemented in the very same algorithm, because they're basically the same). I unfortunately don't recall if these improvements were already shipped with 1.5, so it might very well be that it doesn't work this way yet.

Does this enlighten the topic a little bit? Did I understand your issue correctly…?

**Comment by jrcharney** [comment]
Yes. I guess I will keep waiting then.

> But now finally to the em-dashes! em-dashes, just as any other replacement character will be triggered by AutoCorrect. That means: Write `---` and on the next Space or Enter it'll be converted to —. Don't want this? Then you can either remove the corresponding entry in the replacement table or hold `Shift` while pressing `Space` ==or== `Enter`.

My though is if this was a [sed](http://sed.sourceforge.net/) command with regular expression (which I think JavaScript has some sort of `.replace()` function) there would be a `2,$s/^---$/<hr>/g` This line states that starting as of line 2, convert all lines (g for global) that only have three dashes on them.  I think the first part (the `2,$` part) would be a little more descriptive to respect the the YAML feature.  (I just can't believe someone would think sticking a YAML block anywhere but the header would be logical, but that's the Pandoc people for you.) Following that rule would be the Auto correct rules that substitute the triple dashes that aren't on their own line into the em and en dashes.

That's why I keep thinking of these things in terms of how replacements would be done using regular expression. Those `^` and `$` operators make all the difference when processing changes.

**Comment by nathanlesage** [comment]
Ah, I think I'm beginning to understand your concerns.

So, regular expressions indeed cannot be used, because the text is rendered in-place, meaning: I only have access to a very small portion of the text at one time, both due to performance reasons and because this really suffices.

Going in again, here's what happens when AutoCorrect does its magic:

1. You press either `Space` or `Enter`
2. AutoCorrect begins at the current cursor position (before either the space or a newline is inserted).
3. AutoCorrect first checks "What is the longest piece of AutoCorrect replacements, we have?" For instance, if you need a Greek letter `:theta:`,  this would mean that AutoCorrect begins with the seven last letters right before the cursor.
4. If it does not match any replacements with seven characters, it'll only compare six characters.
5. Repeat until only one character is left.
6. If anywhere along the line the characters before the cursor match, replace them with whatever is intended as their replacement.

Now to triple-dashes on their own respective line: You'll never know whether or not people may simply want an em-dash on their own respective line, so even when you know "there are only three dashes" on that line, it might be that they still want the em-dash. This is in accordance with how Word works. And as Zettlr wants to act as a replacement for Word, we got to take the people in on board!

Furthermore, horizontal rulers can also be created using asterisks or plus signs, so it's not that bad (besides, typographically correct would be asterisks, as these have been used for creating horizontal rulers for centuries before Markdown was invented!)

However, regular expressions are indeed used in many, many, many places throughout the application, and I invite you to have a look at the source code (especially interesting in that regard would be all files containing `plugin` in their filename in the `./source/renderer/assets/codemirror`-directory)

**Comment by alerque** [comment]
> (I just can't believe someone would think sticking a YAML block anywhere but the header would be logical, but that's the Pandoc people for you.) 

As pointed out in many Markdown processors you can place YAML blocks anywhere, and there are some cases where this does make sense. I've run into several cases, but the most common one is probably concatenated documents where one of the included parts appends or overrides previous meta data. Markdown documents can, pretty much by design, be concatenated together as plain text and processed that way. Having rules about something having to be in the first bytes of a file ruins this very useful properly.

Just because _you_ don't use YAML meta data blocks and wouldn't put one anywhere but the beginning doesn't mean that it shouldn't be supported. The last thing I want in a Markdown editor is being limited to the editor's own unique flavor of Markdown. There are enough flavors out there as it is, I want an editor that can actually _deal with them_, not one that chokes on anything it didn't write.

> It is my understanding that em-dash conversion would occur if a word (which may or may not be part of an inline code or inline LaTeX), not separated by spaces had two or three dashes next to it, followed by another word

This is incorrect, and the logic for why would apply to many more things that just em-dash conversion. Text transformations of a→b (whether they are `---`→`—` or `teh `→`the `) should be universal enough happen anywhere **text** is allowed in the first place. This can and does include many places where there are no context "words" as you assume. Consider this example:

```markdown
# ---
```

This should be a chapter level heading (or h1 if you are thinking in HTML) where the text content is solely an em-dash. Pandoc handles this as expected:

```sh
$ echo "# ---" | pandoc -f markdown-smart -t html
<h1 id="section">---</h1>

$ echo "# ---" | pandoc -f markdown+smart -t html
<h1 id="section">—</h1>
```

Your proposed handling would make these kind of edge cases very difficult or impossible to get right.

An additional example would be in Turkish where em-dashes are used to give different semantic meaning than the same glyph in English would and they may be used after other punctuation marks, may be doubled, and can even appear at the start of paragraphs. Trying to bake in your context assumptions into an editor would break it for many users.

There is also such a thing as context dependent substitutions, for example `foo "bar" baz` can be transformed to `foo “bar” baz` based on the leading and trailing context. These however are limited to cases where the typography rules are specifically sensitive to their context to supply the meaning. This is _not_ the case for em-dashes which can appear in various other ways than between words.

**Comment by nathanlesage** [comment]
Can this issue be closed, or is there anything else we should discuss …?

**Comment by jrcharney** [comment]
I suppose. If at very least, it can be tabled for now.
