### ISSUE TITLE
UI breaks, when inserting Table

### ISSUE THREAD

**Issue by derWalter** [Zettlr/Zettlr#4776]
### Description

https://www.youtube.com/watch?v=DhWzTelWXhk

once I insert a table, I cant select (nor with clicking nor with the keyboard (arrow keys+shift doesn't work)) any text

### Reproducing

insert table in text, have fun :/

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.2 UUID: a7324926-355a-4c89-a25a-f95cf7523276

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11 Pro, Version: 22H2, Build: 22621.2506, Windows Feature Experience Pack 1000.22662.1000.0

**Comment by derWalter** [comment]
as I am a dummy and have no clue what I am talking about, but maybe it would be cool to have a feature to tick in the preferences, some thing like "use html tables instead of markdown" and then maybe there is some open source class for wysiwyg tables (something like tinymce has?)

like I said, I dunno... but if I could have html tables with something like tinymce as tableUI I would tick that box 10 out of 10 :D

**Comment by nathanlesage** [comment]
I cannot view the video, so I cannot see what the issue is. In any case, if the TableEditor is borked, disabling it should work. If that doesn't work, the table must be REALLY malformed.

As for the other points you raised: Pre-rendering anything except Markdown tables is a tad too complex for Zettlr, so I wouldn't bet on that functionality. What I will do at some point if I ever get time for that is rework the TableEditor so it finally stops being annoying to me and the users.

**Comment by derWalter** [comment]
the youtube video doesnt work for you?


ye.... I was afraid of such an answer :(

**Comment by nathanlesage** [comment]
No it doesn't, since I will not disable my adblocker for YouTube, and I have neither the energy nor the motivation to play stupid games with a multi-billion Dollar company.

**Comment by nathanlesage** [comment]
In addition, I recently found out that posting YouTube videos on Zettlr bugs appear when you search for Zettlr on YouTube, making it appear as if the app is really problematic due to the amount of bug report videos. I think I'll need to update the contributing guidelines to recommend not using YouTube for such videos in the future…

**Comment by nathanlesage** [comment]
Final comment here (sorry for the spam!), I have now put all of this in proper writing: https://github.com/Zettlr/Zettlr/discussions/4783
