### ISSUE TITLE
Add an Emoji shortcode picker

### ISSUE THREAD

**Issue by gforcada** [Zettlr/Zettlr#4778]
### Description

_This is more about a documentation bug_

I started using, and liking a lot 😊 , Zettlr, thanks __a lot__ for it! 🙇🏾 

At the same time I'm (over)using emojis all the time 😅 and despite seeing on the welcome text that emojis are displayed, I fail to see how to _write_ them...

I'm used to the GitHub `:` and start typing the emoji name, but I fail to see how to do it on Zettlr 😕 

I failed to see any reference on the documentation, nor on reddit either 🤷🏾 

My searching skills are not so good though, so I might have used the wrong words for it...

### Reproducing

- create a new markdown note, type `:tada:` and the text remains, no emoji is shown 😢 
- go to the documentation, search for emoji and only find it on the `Default files` documentation, but no reference on how to write/use them 😕 

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.2

### Installation Method

Flathub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Fedora Linux 39

**Comment by nathanlesage** [comment]
This is not a bug: There is no emoji picker implemented in Zettlr. There have been scattered calls for such a thing.

In principle, it would be easy to implement. *However*, I did not yet find a list of shortcode → emoji mappings that I found satisfactory.

Implementing such a list would be a matter of minutes; so the only stopgap is us missing a good (and complete) list. If you want to help out, feel free to Google around.

What we need is:

* A simple JavaScript mapping. I do not want some weird functions, I want a simple dictionary of shortcode to Emoji
* It should be as complete as possible
* It should have the same shortcodes as on GitHub (this is actually more important than being complete, because people will already know those shortcodes)

Maybe the Signal Desktop app repository is a good place to start, I know they also have such a shortcode list.

Once we have found a good and satisfactory list, I can quickly implement that.

**Comment by gforcada** [comment]
@nathanlesage hey, thanks for the reply. I did some search and turns out GitHub has a REST API to get all the icons and their shortcodes:

`wget  https://api.github.com/emojis`

It returns a JSON with:

```json
{
  "+1": "https://github.githubassets.com/images/icons/emoji/unicode/1f44d.png?v8",
  "-1": "https://github.githubassets.com/images/icons/emoji/unicode/1f44e.png?v8",
  "100": "https://github.githubassets.com/images/icons/emoji/unicode/1f4af.png?v8",
  "1234": "https://github.githubassets.com/images/icons/emoji/unicode/1f522.png?v8",
  "1st_place_medal": "https://github.githubassets.com/images/icons/emoji/unicode/1f947.png?v8",
  "2nd_place_medal": "https://github.githubassets.com/images/icons/emoji/unicode/1f948.png?v8",
  "3rd_place_medal": "https://github.githubassets.com/images/icons/emoji/unicode/1f949.png?v8",
  "8ball": "https://github.githubassets.com/images/icons/emoji/unicode/1f3b1.png?v8"
}
```

Would that be something enough to work with? 🤔 🍀

**Comment by nathanlesage** [comment]
Yes, that's exactly the data structure I had in mind, and replacing the links to those PNGs with the appropriate Unicode characters should also be simple as they've named the files already accordingly.

The only question would be: What's the license of that list? Or, does it come from a package? I think for that I'll have to ask GitHub support … Let me drop them an email once I get to it (feel free to remind me in January if I forget this, I know myself)

**Comment by nathanlesage** [comment]
Even better, I think I found the corresponding package: https://github.com/wooorm/gemoji

**Comment by nathanlesage** [comment]
I suspect this is something that you've had in mind, correct?

(Note that the entries on top are the snippets; since unfortunately the snippets trigger is the same as the one commonly used for emojis – the colon)

<img width="530" alt="image" src="https://github.com/Zettlr/Zettlr/assets/17251683/5d91f81a-9feb-4e83-a6c4-e6740ee00b5f">

**Comment by gforcada** [comment]
@nathanlesage Looks great! ⭐ 💫
