### ISSUE TITLE
Render === titles similar to # titles

### ISSUE THREAD

**Issue by khakhalin** [Zettlr/Zettlr#478]
Traditionally, Markdown has 2 ways to introduce level-1 titles. One is to have a hashtag, followed by a space, followed by a title. The other, used for the very title of the entire document, is to write something, and then place at least three = signs in the next row.

Right now Zettlr does render # -titles as html H1, but makes ===-titles merely **bold**.

Why including ===-titles explicitly could be useful? You see, # -titles don't only look good, they also appear in the interactive table of contents that you get if you press on the "#" button in the top right corner of Zettlr. But the title of the entire document doesn't really belong here! It's not a section of a document, it IS a document.

So right now, there are four ways to deal with it:
1. One is not to have a title, or use an auto-title some people want to see (generated from the document name): neither of this approaches work for me, for example. 
2. Another, is to use # -based H1 both for the title, and for level-1 sections. It inflates the TOC by 1 item, which is annoying. 
3. Yet another, to reserve # for the main title, and ## (level 2) for all other titles. It looks better graphically, but the TOC gets weird, as all sections of the document become numbered as 1.2, 1.3 etc. - with this leading "1." always present. Which is illogical, and thus mildly annoying :)
4. Finally, I can use the ===-title, but as described, it is not rendered as a title; just as a black-bolded text.

Let's maybe make sure that ===-titles are rendered as their own CSS class, and that the style of this class is set to look like H1. Kinda like GitHub or Typora renders it for Markdown. Let's not make it exactly H1 though, to keep it from the "#" interactive menu in Zettlr.

**Comment by nathanlesage** [comment]
Mh, interesting proposition. My stance towards Setex headers was always that they require more work to make them look good (more characters), while ATX-headers are fast and nice. This is why I implicitly without telling anybody, built Zettlr only with ATX-headers in mind; hence the Setex-headers are rendered by the GFM-mode which implements them, and the folding plugin, but nothing I've built in Zettlr deals with Setex headers at all. You're the first one to bring that up, actually :D

Nevertheless, I am pretty in favour of treating headers consistently, which means.

1. Auto-generated titles or a title within a YAML frontmatter should always take precedence as a document title, with `h1` only being a fallback
2. Using `h1` for both the title and the sections is obviously semantically incorrect and therefore should be avoided. `h2` is where the section headers come in.
3. Reserving `#` does not work, especially when it comes to projects, where headers `h1` should also be able to use as section headers, as opposed to only the title (which is, in PDF, reserved by the `title` property)
4. Even level-1 Setex headers should actually behave like ATX-headers, because otherwise you'd introduce an incongruency between Setex and ATX, which is not good.

So here's my offer to you:

1. First we need to add Setex header support to all of Zettlr so that it's consistent again.
2. Then we need to subsequently think of the specific problems you are experiencing, which is (if I understand you correctly) mainly related to the generation of the TOC, is this true? If so, what we should focus on how to determine whether or not there is a title, and if so, don't add it to the TOC.

Maybe the following heuristic would work:

1. Does the YAML frontmatter contain a `title`? If so, that's assumed the document title. All `h1` are rendered as section headers, and appear in the TOC.
2. Is the first heading on the document a `h1` header, be it Setex or ATX? Then use that as the title.
3. Is there any other header level before a `h1`? Then screw the document, as it's not semantically correct! 😈 (just kidding)

What do you think?

**Comment by khakhalin** [comment]
To be honest, I don't understand some of what you wrote here :) Like, I'm guessing Setex is this === thing, but what is YAML frontmatter in this context, I am not sure.

Below is a screenshow of (a part of) my screen that illustrates the problem. (It's not a major problem; I'm just wondering what the best solution is)

So the ideal behavior would be (let me describe how I feel it _should_ work):
1. There should be a noticeable, nice, large title on top. Ideally I should be able to edit its look with CSS, but if looks about like it looks now, I probably won't.
2. This title shouldn't be auto-generated. For papers, I want to use the actual title of an actual paper, and that's way too long for a file name or an ID. I want to be able to edit it, as I edit the rest of the document.
3. It shouldn't appear in the TOC on top, just because it's not a part of a structure of this page; it's just the title of this page.
4. The title should be a part of the markdown itself, and not stored elsewhere, so that the .md document would look OK even if I send it to someone, or push it on GitHub.

Does it makes sense? As you can see from the print-screen, points 1 and 2 are supported, point 3 is violated. I'm a bit worried by your writing about auto-generated titles though, as it seems that it could violate my point 1 (free editing), and potentially point 4 (md only, no extra database).

So if you see a good workaround here, please let me know!

![image](https://user-images.githubusercontent.com/17154125/72667696-9ac6b400-39ec-11ea-988f-e244a0ad80c9.png)

**Comment by alerque** [comment]
See also [Pandoc issue 5615](https://github.com/jgm/pandoc/issues/5615) and some of the cross-linked discussion and PRs there.

Short version: Pandoc tried to overhaul the way document titles and header levels interacted and it turned out to be a lot more complicated than anybody thought it would be going in. Pandoc even had to push out a point release backtracking on changes we thought were going to be good.

Not saying this can't be done, just proceed with caution when making assumptions about the levels of headers vs. attributes like document titles. I myself use Markdown in a publishing workflow and not all of our book projects use the same header levels. It turns out a one-size-fits-most approach likely works out worse for everybody.

P.S. Another ATX header style fan here, but of course Setex headers should be supported as exact equivalents.

**Comment by nathanlesage** [comment]
@alerque Thanks for pointing to the issue! Didn't know Pandoc stumbled upon the same problem. But basically this is what I'm saying: Headers are headers are headers and a TOC consists of headers, so it's gonna be difficult (at least if we're doing this without a preferences option).

And that Pandoc issue shows this pretty straightforward: You simply cannot assume for which person one single header 1 is the actual document title, and for which person it is not. Basically, treating headers as titles in certain circumstances violates point 1 by @khakhalin for all those people who don't think that the first header 1 is treated differently, if there's no other title :P

This definitely complicates things, and I'm not sure we should engage on the same endeavour as Pandoc…

To the Setex/ATX-question:

```markdown
This is a Setex Level 1 header
==============================

This is a Setex Level 2 header
------------------------------

# ATX level 1
## ATX level 2
### ATX level 3
#### ATX level 4
##### ATX level 5
###### ATX level 6
```

As you can see, Setex only supports level 1 and 2.

**Comment by khakhalin** [comment]
Thanks for the explanations! I didn't realize that Setex==ATX is an official policy that is worth enforcing. I thought that Zettlr kinda doesn't support Setex, and so assumed that it is "free for grabs", and could be used to patch this particular issue.

But so, it seems a Markdown-level issue, doesn't it? Like, Microsoft Word for example has a whole style (Title) that lies outside of the h1..h5 sequence, and doesn't affect TOC (among other things). But already HTML kinda doesn't have a title (it has a title that names the doc, and it has h1, but it doesn't have this header-style thing that is unique within the document by design). So for CSS, people usually either repurpose h1, or just make a div with a custom name. (Repurposing h1 is more popular traditionally, but also for a wrong reason: as a way to game search engine hierarchies). And it appears that Markdown inherited the HTML logic. Which is, in a way, incorrect.

Personally, my preferred solution would be to ditch full Setex support, and re-purpose it for these non-section titles. Arguments:
* Setex is not as popular
* With two levels only, it's obviously deficient, and thus unworthy
* It looks good at the beginning of raw md documents
* It is rendered properly by most markdown editors / viewers
* The issue seems to be with Markdown format itself, so maybe it's OK to challenge it: someone should, at some point

Another alternative is to change the logic for TOC, and just say that:

> Single # as the first renderable line of a document makes it into a TITLE, meaning that ## now generate 1. chapter, not 1.1. chapter entries in the TOC". More than one # , or # that is not in the beginning set #→1.Chapter, and ##→1.1.Chapter

It seems that it could still cause problems for some users (judging from the Pandoc discussion you cited), but it least there is some logic to it.

Finally, the most over-the-top solution would be to define titles as this YAML code you mentioned (I still couldn't find a good explanation of how Zettlr uses it, but at least now I've seen some references):
```
---
title: Sharkpig
---
```

And then just create a rendering style for it, that would make the `title:` word pale (sort of like you already do with reverse-quotation marks that are kinda there, but not really visible), and make the title itself large and bold (the same style you have for ATX h1). I think it's an overkill, and would make markdowns unpleasant to see outside of Zettlr, but if it saves compatibility issues with pandox etc, maybe we could at least make it look nice in Zetllr...

But that said, it's not like it's a big problem. It's just illogical, and this makes it annoying, particularly in the context of Zettelkasten! :) ZK feel like logic finally coming to your life and taking a residence there, and fixing it for good. So realizing that h1∙∙h6 system is actually broken is upsetting. But I bet for most people, it is all rather inconsequential.

**Comment by nathanlesage** [comment]
> But so, it seems a Markdown-level issue, doesn't it? Like, Microsoft Word for example has a whole style (Title) that lies outside of the h1..h5 sequence, and doesn't affect TOC (among other things). But already HTML kinda doesn't have a title (it has a title that names the doc, and it has h1, but it doesn't have this header-style thing that is unique within the document by design).

I think you hit the point with this thing. Yes, Markdown was originally inspired by how Emails work, and Email titles are the subject line. And HTML-titles are the ones you see in the browser. So yes, you have a inconsistency, because documents should have a title, but Markdown doesn't feature it. I think the discussion we're having here right now is actually one we should focus upon, because this kind of discussions is it that push Markdown further. You are completely right that Markdown, as a file format, needs some title, and the file name cannot be that, so much is correct.

The question, therefore, should be: Do we stick to the YAML frontmatter header (which would be an explicit "I want THIS as the title!"), or do we use a heuristic (which might come as a surprise to people).

The reasons pro YAML frontmatter would be general compatibility, because not only Pandoc uses YAML frontmatters, but other parsers have also started to support it (as Pandoc is sort of a reference implementation for Markdown). The reasons pro heuristics would be that it's easier (but it might cause issues with other users).

I just thought how I myself handle it, and it seems to work like this:

1. Do I have a standalone document, such as a single Markdown file that I export to a single result? Then I don't use a header in itself, but only use one H1 as both the title (it appears at the top) and the only H1 throughout the document. Also, I'm not confused by the H1 appearing in the TOC, because it somehow "belongs" there.
2. Do I have several documents that I glue together and export as a single PDF? Then the title resides in the project settings, and I still use H1 throughout the document. As always, this H1 is listed in the TOC as I expect it.

So, clearly, my own workflow does not answer this, the question is of what we do. I mean, if Pandoc failed to compile a correct logic, then such a comparably tiny project … could we make it?

**Comment by nathanlesage** [comment]
As Setext-headers are now correctly rendered, I'm going to close this issue (unless there's something I forgot to address so far!)
