### ISSUE TITLE
Cursor becomes invisible from time to time

### ISSUE THREAD

**Issue by BabakFarshchian** [Zettlr/Zettlr#4795]
### Description

Once in a while (not yet able to reproduce) the cursor in the editing window becomes invisible, which of course makes it very awkward to write and edit.

### Reproducing

I am not able to reproduce as it happens sporadically. I think it has to do with initial loading of files. But I am not sure.

### Zettlr Version

Nightly

### Specify version

3.0.2 nightly

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11

### Additional Information

I am running the nightly version because it fixes error #4732.

**Comment by BabakFarshchian** [comment]
One observation:

* The cursor is visible in file A.
* I open a file B by clicking on the file in the file explorer.
* The cursor becomes invisible in file B.
* I close file B, the cursor is visible in file A.

**Comment by BabakFarshchian** [comment]
I suspect this has somehow to do with the initial parsing of the file, and whether there are markdown style errors in the file. The reason is that:

* I opened a file where there was an extra line in between two bullet lists.
* The cursor was invisible (and the file color coding was not there, subject to another bug report/issue).
* I removed the extra line.
* After the file was saved, the color coding and the cursor were back.

**Comment by BabakFarshchian** [comment]
I notice that this problem occurs in conjunction with the rendering of whole file. It seems like it is not only the cursor that disappears. So does the color coding of e.g. references, links, hashtags etc.

**Comment by nathanlesage** [comment]
The cursor disappearing is a sign that the loading-process of the document produced some errors somewhere. The reason is that the cursor that we see is actually a CodeMirror plugin – and if anything goes wrong when the editor is being set up, this will disable all plugins and make the editor itself look extremely "raw", which also affects colors, as you correctly identify.

Please have a look when this happens at the Developer Console – there should be an error logged that may help fix the bug quickly.

**Comment by BabakFarshchian** [comment]
I guess you refer to the log viewer? The only error message that I can see there is [Application] Could not fetch link preview for URL. But it seems like this error message is unrelated because it comes up also when there is no CodeMirror cursor problem?

**Comment by nathanlesage** [comment]
Yeah, after I wrote that comment I did something on my current PR branch that I know would trigger the bug and to my disappointment there was no error logged. The next possibility is that somehow the editor doesn't fetch the proper information from main that it needs to set the appropriate extensions. (In other words, it just doesn't load any extensions instead of failing to load the correct ones.)

I'll continue the search for this issue in my recent PR, since that has to mop out many things anyhow and I have the feeling that'll be cleaner to do it there … but yeah, I mean the workaround is to close and re-open the file so while it's a nuisance I hope it's not an entire showstopper until then.

**Comment by nathanlesage** [comment]
Is this bug still occurring?

**Comment by BabakFarshchian** [comment]
I have not seen this bug in the last months actually. Not sure since when as I had completely forgotten about it :-)

**Comment by nathanlesage** [comment]
Alright, thanks for getting back to me. Then let's close this issue for now. Should the problem re-occur, please notify us!
