### ISSUE TITLE
Unwanted data when paste text from Word

### ISSUE THREAD

**Issue by Wietor-bb** [Zettlr/Zettlr#4803]
### Description

When I paste text from Word, unlike in previous versions of Zettler, I get an unnecessary XML-like header, before the main text. The main text appears between comments 
```
<!--StartFragment-->
Lorem **ipsum** dolor etc. 
<!--EndFragment--> 
```

Example of a header:
`
`

How to disable it? Is this a bug or an "enhancement"?

### Reproducing

Paste text from MS Word (docx file).

### Zettlr Version

Stable (most recent version)

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11

**Comment by nathanlesage** [comment]
In the last release we have exchanged the previous HTML -> Markdown transpiler with a new one; this looks like a regression. Should not be like what you're seeing. However, I don't have an elegant way of filtering out all potentially unwanted Word formatting. @kyaso Do you happen to have a creative way of what we might want to try?

**Comment by kyaso** [comment]
I was actually observing something similar, when copy-pasting _formatted_ text (I believe?) from an external source (I don't use Word btw); it would also be sourrounded by those HTML comments. I assumed it was default behavior, so I didn't really question it, and worked around by using `CTRL + Shift + V` instead to past the raw text.

I will pay more attention now to when it happens to see any patterns.

**Comment by nathanlesage** [comment]
@kyaso Yes, Word is the most egregious case, but I suspect that any other rich text editor (LibreOffice/OpenOffice included) will add some formatting information to their copying, which apparently ends up within Zettlr.

I know that `joplin-turndown`, which we've been using for a long time, actually handled that really well; we may draw inspiration from that plugin: https://github.com/laurent22/joplin/tree/dev/packages/turndown

(The reason I switched to `unified` was inspired by (a) the comparatively brittle logic of turndown and (b) because that gives us much more customizability of the HTML->Markdown compilation).

Although, WAIT A MOMENT. This gives me an idea. Maybe we can implement a custom HTML->Markdown converter based on the HTML Lezer parser, like the Markdown->HTML conversion…?

**Comment by dpflueger** [comment]
I get the same behavior also when copying any text from a browser (Chrome/Firefox). As mentioned above it can be worked around by using Ctrl+Shift+v to paste the text. I think it has something to do how Windows handles its clipboard. It stores the copied text in multiple formats, e.g. Rich Text. (This is nice because then you can copy formatted text from one application to another). When using Ctrl+v to paste text, it actually pastes the text in multiple formats and the applciation can decide how to handle them. I think that Zettlr (or Electron) somehow decides to use the RTF format but cannot parse it correctly. When pasting with Ctrl+Shift+v it only pastes the plaintext version of the clipboard content.

Maybe it is somehow possible to make this the default behavior, so that it always uses the plaintext content?

**Comment by nathanlesage** [comment]
@dpflueger This is not quite correct and may lead to misconceptions as to how both Zettlr as well as operating systems themselves handle clipboard text.

Any operating system offers as many clipboards as it wants, usually indexed with MIME-types. I.e., usually, you'll have a `text/plain` clipboard that simply contains plain text contexts. Applications may then choose to add, e.g., `image/jpeg` clipboards, `text/html`, etc. pp.

When you press Ctrl+C, the sending application needs to write whichever formats they want to, and when you press Ctrl+V, the receiving application needs to look at the clipboard contents and decide what contents to use.

Zettlr always has a look into the `text/html` rich text clipboard, and if there's something in there, it will take that and transform it HTML->Markdown and then insert that. Holding `Shift` forces Zettlr to ignore the HTML clipboard and immediately take the `text/plain` backup clipboard as-is.

Now, to explain once more what is happening here: When you copy something from an Office, you get an inconsistent set of stuff. There are many problems and bugs that are part of the Microsoft Office experience, but the fundamental one here is that Word copies a huge amount of formatting information to the clipboard. And Zettlr does not yet reliably remove that stuff on paste. This is what we need to fix.

Your suggestions would therefore be extremely detrimental to the user experience of Zettlr users, without really solving the root cause.

**Comment by kyaso** [comment]
I just saw this happening when copying any link from a website. Try it with this link: [Zettlr](https://www.zettlr.com/). If I highlight the link, press `Ctrl+C`, then in Zettlr do `Ctrl+V`, I get:
```
<!--StartFragment-->

 [Zettlr](https://www.zettlr.com/)

<!--EndFragment-->
```

I'm using Chrome on Windows 11.

Could anybody confirm this?

**Comment by nathanlesage** [comment]
The startfragment thingy is part of the copied part...?

In any case, I think what we need is some proper filtering... we may have to have a conceptual meeting for that...?

**Comment by dpflueger** [comment]
First of all, sorry for the misinformation in my previous comment, that was some wild guessing without really informing myself first, so thanks for clearing that up.

I did some tests and here is what happens for me:

When I copy any Text from a Browser (e.g. Firefox) like for example the sentence from your comment above, it will appear in Zettlr as

```
<!--StartFragment-->

The startfragment thingy is part of the copied part...?

<!--EndFragment-->
```

If I inspect what I copied via e.g. via https://evercoder.github.io/clipboard-inspector/, it contains two entries:
- text/plain: `The startfragment thingy is part of the copied part...?`
- text/html: 
```html
<html><body>
<!--StartFragment-->The startfragment thingy is part of the copied part...?<!--EndFragment-->
</body>
</html>
```
So these things are actually comments within the html.
I am also on Win 11.

**Comment by nathanlesage** [comment]
@dpflueger Ah, you found a clipboard inspector? I've been searching for long to find one but couldn't 😂  Very good, this will make inspecting what certain apps write into the clipboard easier!

Here's one quick example that shows the crazyness of Word: It will produce a lengthy HTML document:

<img width="1016" alt="image" src="https://github.com/Zettlr/Zettlr/assets/17251683/38f7daad-551d-402f-b7ee-4ff742566d30">

*Interestingly*, even Word seems to include this "StartFragment" indication:

<img width="847" alt="image" src="https://github.com/Zettlr/Zettlr/assets/17251683/333a31b7-769d-4204-95da-206f531835d1">

So I think the first thing to remove should be the `head` contents. I've seen that Joplin basically just hydrates the HTML in the DOM and then extracts the top node. This apparently already solves a lot of our issues.

**Comment by nathanlesage** [comment]
Quick addendum: I just saw that Turndown was using the built-in DOMParser for parsing the HTML: https://developer.mozilla.org/en-US/docs/Web/API/DOMParser

What we could do is split up pasting into two steps:

1. Utilize the DOMParser to quickly filter out large chunks of the unwanted HTML
2. Use the regular HTML->MD converter to convert only the wanted HTML into Markdown

The question would be a bit regarding security. I will fully sandbox the renderer processes in one of the next versions, so any leakage should less be a problem, and the Mozilla API description doesn't mention any particular security concerns (probably because JS won't be run from this fragment if we don't mount it onto the actual DOM??).

**Comment by nathanlesage** [comment]
Another addition: I now took a look at the pasting behavior, and I have questions: How tf are you capable of pasting text from Word in Zettlr in the first place? For me it ALWAYS (!) wants to paste an image because Word is super weird — in effect, I cannot reproduce your bug because I can't get the app to try to paste Word text with style lol

**Comment by nathanlesage** [comment]
@kyaso Fyi, I now enabled me to reproduce this bug in this commit: https://github.com/Zettlr/Zettlr/commit/064b474d5b882aa69b4182782af5e5aa568ea6fb

**Comment by nathanlesage** [comment]
I think …? I fixed it. The clipboard is arcane magic I feel.

**Comment by fr-laurentn** [comment]
Hi, 

FYI, I'm having the same issue, with Zettlr 3.0.3 running on Windows 10.

Is your fix supposed to be active on this version of Zettlr?

**Comment by nathanlesage** [comment]
@fr-laurentn 

> Is your fix supposed to be active on this version of Zettlr?

No, always the version released AFTER an issue has been closed.
