### ISSUE TITLE
Dollar sign pairs on a line renders text as italics

### ISSUE THREAD

**Issue by kwoodham** [Zettlr/Zettlr#482]
## Description

I have a line in my file that uses two monetary values:

> This $30K puts you $3.2K over the current budget.

In the display window, moving the cursor off this line renders it as:

> This _30K puts you_ 3.2K over...

_(See the screenshot)_

I can get $ to render as intended only if I escape as \\$

## Reproducing

See above

## Expected behaviour

I have underline selected for italics in settings. The currency values should render

**Screenshots**

![image](https://user-images.githubusercontent.com/753594/72921214-e0e78480-3d18-11ea-908f-84499c224b8e.png)

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.5 
 - Screen Resolution: 3440 x 1440

**Comment by johnblommers** [comment]
This behavior is extremely common in Markdown editors that support inline LaTeX formulas. And when writing two dollar amounts on a line it looks like a LaTeX formula to the parser. You have several choices:

1. Ignore the preview because the exported PDF or ODT file will look fine (from my testing)
2. Escape the dollar sign `\$`. The backslash will appear in the preview but not in the PDF or ODT (from my testing)
3. Preferences - Display  -; Render Formulae  Off

Use option 3 above if you don't use LaTeX formulas in your writing.

**Comment by nathanlesage** [comment]
This was a known issue persisting in Zettlr until 1.5; but since then there has been a patch that disables that wrong behaviour, and it will come with 1.6 :)

See the current dev build:

![image](https://user-images.githubusercontent.com/17251683/72930211-bb2f9f00-3d5b-11ea-9466-970a7ea0dd53.png)

(P.S.: The italics are not real italics, they're actually a math formula; as I said, nasty bug, but it's been resolved!)
