### ISSUE TITLE
Colons are allowed in Workspace-names, but break the split-view behaviour

### ISSUE THREAD

**Issue by Aaaamu** [Zettlr/Zettlr#4822]
### Description

Colons are allowed in Workspace-names, but completely break the split-view behaviour.

### Reproducing

Create a folder with Colons in the folder name in your filebrowser. Then choose it as a workspace from zettlr. 
The Bug only occurs this way. if you rename a workspace from within zettlr, colons get replaced by hyphens.

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.2

### Installation Method

Other (please specify below)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

ubuntu 22.04

### Additional Information

installed via deb package from your homepage (why not make it a repo by the way?)

**Comment by nathanlesage** [comment]
I wrongly expected colons to serve as path separators in some drag event code in the split views, so that's the issue. See here: https://github.com/Zettlr/Zettlr/blob/6879970dc7b87bc99b7d9f2492999fad3086d709/source/win-main/DocumentTabs.vue#L539

… and here: https://github.com/Zettlr/Zettlr/blob/6879970dc7b87bc99b7d9f2492999fad3086d709/source/win-main/DocumentTabs.vue#L698

With regard to colons getting replaced with hyphens on internal renames: That's by design so that users who need to use both Windows and Linux or macOS can reasonably expect files created on one platform to be opened on another, so the allowed characters when doing something internally with Zettlr will be the minimal subset of all platforms.
