### ISSUE TITLE
Internal links can travel across workspaces

### ISSUE THREAD

**Issue by ObjectBoxPC** [Zettlr/Zettlr#4845]
### Description

I have two workspaces open. If I type `[[` into a note in one workspace, Zettlr suggests notes in the other workspace. And if I use one of the suggestions, I can follow the link to the other note. I think of workspaces as being self-contained and separate, and this is inconsistent with that model. However, I understand if Zettlr uses a different model.

(Note: I have the Zettelkasten -> Link with filename only option checked. I'm not sure if this makes any difference.)

### Reproducing

1. Create two workspaces in two separate directories.
2. Open both workspaces in Zettlr at the same time.
3. Create a note in the first workspace.
4. Create a note in the second workspace.
5. In the note in the second workspace, type `[[`. Observe that the note in the first workspace appears in the suggestion list.
6. Use the suggestion. (Alternatively, manually copy the ID of the note in the first space.)
7. Follow the link. Observe that the link goes to the note in the first workspace.

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.3

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Debian Testing

**Comment by nathanlesage** [comment]
This is most definitely not a bug, but intended behavior. Many people actually want this.

This is something more suited for a discussion [here](https://github.com/Zettlr/Zettlr/discussions/); after which we can decide if we want to change this behavior, or need to adapt this. Please open a discussion, and feel free to also disperse it on our [Discord server](https://go.zettlr.com/discord) so that many people can chime in.
