### ISSUE TITLE
Cortex CDR shows security warning for Zettlr

### ISSUE THREAD

**Issue by fhg-isi** [Zettlr/Zettlr#4862]
### Description

![image](https://github.com/Zettlr/Zettlr/assets/76424482/1dd62c9d-1ea2-4d31-8c92-571afe8e82f0)

![image](https://github.com/Zettlr/Zettlr/assets/76424482/ee650518-16fa-4389-830a-6001f032f023)

### Reproducing

Install Zettlr on Windows and open Zettlr. 
Cortex shows an alert. => I uninstalled Zettlr.

### Zettlr Version

Stable (most recent version)

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10 Enterprise 22H2

**Comment by antaln** [comment]
I opened #4861 just a few hours before this ticket, with same symptoms.

Took a while to determine it's not some kind of a supply chain attack, but a side effect of
1. link rendering, which automatically opens links, and 
2. Zettlr tutorial shown on first run, which includes links to Reddit, Discord and Mastodon.

Disabling link rendering does the trick, but requires manually modifying config.json, because Cortex stops Zettlr on startup.
I don't see a good way to get this whitelisted on Cortex.

**Comment by fhg-isi** [comment]
Thanks. I close this duplicate.

**Comment by antaln** [comment]
@fhg-isi I will try to submit a "report incorrect verdict" in Cortex XDR to report a false positive. I encourage you and others that experience this issue to do the same, and maybe we can get Zettlr to get a permanent exception.
