### ISSUE TITLE
Editor loses focus after tab change using keaboard shortcut

### ISSUE THREAD

**Issue by Ardhanm** [Zettlr/Zettlr#4889]
### Description

**After changing tab using keyboard** shortcuts "Previous tab" or "Next tab" shortcut (_Ctrl+Shift+Tab_ or _Ctrl+Tab_ on Windows), the **editor cursor disappears**. 

Sometimes the cursor shows again by pressing Tab key several times, many other times, I just **can't get the cursor back until I press mouse button inside the editor area**. 

This slows down the workflow. Being able to navigate using just the keyboard is really a great feature.

### Reproducing

1. Open Zettlr.
2. Open several tabs (two tabs are enough).
3. Change tab using Ctrl+Shift+Tab (or Ctrl+Tab).
4. Try to type more text. 

Impossible to do, until mouse left button is pressed on the text area.

More info:
Sometimes the comes back by keeping the Tab key pressed.
- Repeat steps 1 to 3.
- Make sure text cannot be inserted by doing some random typing.
- Keep the Tab key pressed for several seconds, until the key repetition is triggered. some time after, the cursor should come back (along with tabs being wildly inserted in the text).

### Zettlr Version

Stable (most recent version)

### Specify version

3.0.3

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 11

**Comment by hungvvu** [comment]
I have been experiencing the same problem as well, which makes it a bit annoying to type in Vim mode because I'll have to reach for my mouse and click back in. I did find a workaround for this which is pressing Ctrl + Shift + T to focus on the file tree, and then Tab to get back in. I've attached a video of this bug below. It seems from this that switching with Ctrl + Tab bring the focus to something else that is neither the file tree nor the editor window. After Ctrl + Tab, Ctrl + Shift + Tab, and then finally Tab again to try and re-enter to editing, it focuses on one of the links instead of going back to the current cursor position like it should.

I would love to give this bug a try if nobody is working on it yet.

![Uploading zettlr-unfocused-windows-bug-report.gif…](Window unfocusing after Ctrl + Tab)
