### ISSUE TITLE
Follow resolvable hyperlinks

### ISSUE THREAD

**Issue by Jaifroid** [Zettlr/Zettlr#49]
Pandoc creates a table of contents for a markdown file (using the switch `--toc`), in which internal document links look like this:

`[Tangos, photography, and film](#tangos-photography-and-film)`

It would be brilliant if Zettlr were able to follow such links. It would need to use the same algorithm as pandoc for omitting punctuation, etc., but since Zettlr already has the logic to search for tags, it's really just a case of adapting the existing logic with a dynamically constructed regex successively matching a `#` and then the parts between the hyphens along the same line.

On a similar vein, but in this case linking to other files, it is a bit surprising that Zettlr can follow a link to another file constructed with Wiki-style links like this:

`[[My awesome markdown file]]`

… but it can't follow a link with a more standard markdown syntax like this:

`(The greatest document of all)[My awesome markdown file]`

In fact I can't get it to follow relative hyperlinks at all, no matter how I construct them. Could the second syntax be supported, and ideally also support actual relative hyperlinks of the type 
`(link)[my subdirectory/my file.md]`?

**Comment by Jaifroid** [comment]
@nathanlesage I completely understand there is a lot still to do on Zettlr, so this is not high priority, but since you asked... 

The rules for constructing the links are explained here:

http://garrettgman.github.io/rmarkdown/authoring_pandoc_markdown.html#extension-auto_identifiers 

However, you don't need to construct such implicit links, just follow them. To match a header from an auto-generated link, I'd do something like this:
```
var hash = '#tangos-photography-and-film';
// Turn the hash variable into a new regular expression to match the corresponding heading
findHeaderFromHashRegExp = new RegExp( '#[\\s]*?' + 
          hash.replace(/-/g, '[^\\r\\n]+?').replace(/^#/, '')', 'i' );
// The new regex should now match the corresponding heading in the document
document.match(findHeaderFromHashRegExp);
```
This works by turning the string of the hashed link into a regular expression: simply by replacing hyphens with `[^\r\n]+?` (= match any character that is not a carriage return *or* a line-feed at least once and as many times as possible, non-greedy). It won't go past a line-end even in different systems using different line-end characters. So `'#tangos-photography-and-film'` becomes the regex
`/#\s*?tangos[^\r\n]*?photography[^\r\n]*?and[^\r\n]*?film/i` which in turn will match
`'# Tangos, Photography, and Film'`. 

NB, just wrote this quickly, I haven't tested it, and some escaped backslashes might need an extra escape added to them, it's difficult to be sure till actually testing.

Hope it doesn't look like monkey-wrenching!!

Regarding the standard markdown hyperlink syntax `(link)[files/document.md]`, that's actually more standard that `[[document]]` for markdown files, no? So I don't think you'd be polluting the markdown by supporting it.

As I say, it's not high priority!!

**Comment by nathanlesage** [comment]
Uhh, pretty interesting idea to simply convert the links to RegExes! Nice one 👍 And thank you very much for your research, I'll see to it in some time!

And concerning your Wikilinks-Hack: Didn't think of this, but of course it does make sense.

> Regarding the standard markdown hyperlink syntax (link)[files/document.md], that's actually more standard that [[document]] for markdown files, no? So I don't think you'd be polluting the markdown by supporting it.

I'm still unsure. Markdown is a Source-code-file, meant to be exported to another format, and not a finally rendered HTML/PDF/DOC/whatever. This means: The relative file links to other Markdown files _will_ be invalidated during export, because *something* will change with the target file as well. And I think that Markdown hasn't been made to support file linkages after all, so I think hacking Markdown links like that would indeed "pollute" the Markdown in some way. Links should always be in the format they are supposed to _after_ export, not prior to it.

It is because of this that I decided to implement Wikilinks: They are definitely not standard, but are ignored by parsers and can be easily removed from files prior to exporting them (as the settings in Zettlr allow you to do already).

An example: If you decide to export some files to another format that contain these "special" links, this will result in you having several dead links inside the exported file — but you can't tell from only looking at the link; you'd have to click a link to see that your browser tells you that it can't open the target. If you only use Wikilinks for these internal links, you won't have that problem.

But you know what I suddenly realised? Markdown in Zettlr has evolved so far that it is more and more used not as a source file to compile to something else, but as a standalone file that just … stays Markdown and is never to be exported. There you see what impact on a human's perception auto-previewing of links, images, etc. can have!

**Comment by Jaifroid** [comment]
> because of the negative lookahead, which is still unsupported in ES6

Slight confusion I think - negative and positive lookahead are fully supported in all browsers all the way back to Internet Explorer <10 (we use it in Kiwix JS and Kiwix JS Windows all the time). It's positive and negative *lookbehind* that are not supported, and Chrome has just introduced them -- see https://www.regular-expressions.info/javascript.html (search for lookbehind on that page). Btw, I strongly recommend RegexBuddy, as it allows you test regexes for every language and even different browsers. Well worth it for a developer!

**Comment by nathanlesage** [comment]
Ahh, that is so great news. This means it'll only take some more weeks until the electron guys deliver the current chrome version until I can finally flatten out my code :)

This would then also make it possible for me to have link previews not render links if they are escaped. (Or, for that matter, anything)

**Comment by nathanlesage** [comment]
Just implemented your regexy-thing, and it seems to work rather well!

Please feel free to test some edge-cases, but it should work now :)

At least your Tango-example, and some of my own examples did work very well!

**Comment by Jaifroid** [comment]
Hmm, this one isn't working for me. But I wonder if we're looking at the same type of link? So, I have a t.o.c. produced by pandoc. A link in the t.o.c. looks like this:

![image](https://user-images.githubusercontent.com/4304337/48968735-8efb7f80-efeb-11e8-907d-5cdd9d744141.png)

The corresponding heading further down the document looks like `## Neorealism` (on a line on its own. When I click on the green link above, nothing happens. I've tried in dev tools putting a pause on the function that should process these links (the new one you've added, line 170 of `zettlr-editor.js`, but `markdownOnLinkOpen` doesn't seem to fire, either on opening of the grey link, or clicking on the green link. Are you supporting only `[[...]]` links here?

Also, am I debugging the right file when trying to debug this (`zettlr-editor.js`), or is this just a list of functions that are applied by another function, or a worker?

**Comment by nathanlesage** [comment]
Hey, the `markdownOnLinkOpen`-function is indeed the correct one.

But it only fires if you click on a link that has been rendered by the renderLinks command. This means, it must become underlined on hover. And, more importantly: You must `Alt`-Click the link! It shouldn't open (what happens if you simply click somewhere inside), but follow the actual link (which happens when alt-Clicking).

This behaviour is by design, because the first action you'd want to do in an editor is to edit, and only a secondary action is, e.g., to follow a link :)

Does this work for you?

**Comment by Jaifroid** [comment]
OK, now I know how to do it, it works! What I was doing was clicking on the grey link, which opens as in the image above, and then clicking on the green.

I completely agree that the main function of an editor is to edit, not to browse, so Alt-click makes sense. My only doubt is for touch-screen use. The standard Windows on-screen keyboard doesn't have the Alt key, so could you consider mapping Ctrl-click (Command-click on Mac, I think) as well? I've just tested this on a Surface. Ctrl is available using on-screen keyboard.

**Comment by Jaifroid** [comment]
Hee, hee, Microsoft moves in mysterious ways... Some intern probably said "This keyboard looks way too crowded... Who uses the alt key anyway?", and deleted it. Since they fired all their quality assurance testers, no-one noticed.

Anyway, "it would be nice", but don't spend a lot of time on this marginal use-case. May be worth a separate issue so you can close this one.

**Comment by nathanlesage** [comment]
Alright, thank you very much again! :)

**Comment by AndreaTosoni** [comment]
Hello,

I was looking for a way to create links to paragraphs in the same file and I found this helpful (very helpful) explanation. 
Thank you very much!

I believe, however, that there is a slight problem if the title from which the link is generated contains an accented letter.
Writing:

##Choix d’implémentation 

within Zettlr I can find the paragraph and create the link. I'm not really interested in following the link within the tool, I'm more interested in exporting it and having it available in the final document (Latex).

But in Latex the link can't work: the label is 
\label{choix-dimpluxe9mentation}
while the reference is
\hyperlink{choix-dimplmentation}{Choix d'implémentation}

it seems that the accented letter is in one case is removed while in the other case it's translated as a double character.

Maybe it's my mistake (I'm just using Zettlr) in which case I would be grateful if you could explain me how to handle this problem since I have to write some documentation in French.

Thanks in advance. Best regards,

                   Andrea

**Comment by nathanlesage** [comment]
@AndreaTosoni That could be behavior that might be improved. Feel free to try out more combinations and then open a new issue with these, so that we can improve Zettlr's behavior!
