### ISSUE TITLE
undo / redo not working with tables

### ISSUE THREAD

**Issue by hyphone** [Zettlr/Zettlr#490]
## Description

When I have a table with mulitple columns and lines and I delete a column I cannot undelete the deletion of the column.

## Reproducing

- Create a table with multiple columns and lines.
- fill the table
- delete a column
- try to undo

## Expected behaviour

column comes back again

## Platform
 - OS and version: Ubuntu 19.10
 - Zettlr Version: 1.5.0

**Comment by nathanlesage** [comment]
This is due to the fact that, when you are in edit mode of the table, you are actually editing the HTML representation of the table, and **not** the underlying Markdown. Your modifications are persisted into the Markdown, as soon as you leave the edit mode by clicking outside of the table. Then, undo and redo become possible.

Therefore: If you accidentally delete a column or row, or make any other mistake, simply click outside the table so that your mistakes are persisted onto the editor, which will then enable you to use `Ctrl/Cmd+Z` to undo the changes and do it again.

Maybe we can implement a super simple undo/redo, but this does not have priority right now, as there are so many issues open which need to be addressed prior!

**Comment by hyphone** [comment]
thank you for describing the behavior and how to deal with it

**Comment by jcolomb** [comment]
This should be included in the tutorial, it would have been enough for me to abandon trying zettlr if I was not able to find the answer here (If I could accidentally erase a column without possibility for undo, I will never use the tool)
