### ISSUE TITLE
Setting writing target failed

### ISSUE THREAD

**Issue by shanvrolijk** [Zettlr/Zettlr#494]
## Description
It's been a while since I can use set writing target.

## Reproducing
Whether it's setting target in the new or old zettlr slip/md, the feature doesn't work

## Expected behaviour
I hope it could work. How about putting the writing target in the same box with pomodoro, so, when I could set both without much oscillating motion between the sidebar and the taskbar?

**Screenshots**

## Platform
 - OS and version: Windows 10, Intel(R) core(TM) i5 8250U CPU @ 1.60GHz 1.80 Ghz.
 - Zettlr Version: 1.6.0-beta
 - Screen Resolution: 1366 x 768

## Additional information
Thank you so much 😄

**Comment by nathanlesage** [comment]
Do the logs tell you something that might help? b/c I can set writing targets on the 1.6 beta on both macOS and Windows, so it might relate to some configuration issues :/

**Comment by shanvrolijk** [comment]
Hello, this is what the log looks like, right after I run the application

![Screenshot 2020-01-30 09 55 07](https://user-images.githubusercontent.com/30141705/73416371-49e98080-4347-11ea-81dc-8fd254648ff2.png)

![Screenshot 2020-01-30 09 55 41](https://user-images.githubusercontent.com/30141705/73416377-4eae3480-4347-11ea-82e0-8dc591386f56.png)

![InkedScreenshot 2020-01-30 09 55 58_LI](https://user-images.githubusercontent.com/30141705/73416388-5372e880-4347-11ea-9a69-c2e90fb8afe9.jpg)

**Comment by nathanlesage** [comment]
The two log messages you marked are not a problem; this just indicates that setting writing targets does not work via a command but via the `ZettlrTargets`-class, which should then create the target in the `Users/<username>/Roaming/targets.json`-file, which due to some problem is not happening …

The problem seems to be somewhere in this function: https://github.com/Zettlr/Zettlr/blob/master/source/main/zettlr-targets.js#L159

I'll see to adding some additional logging from there

**Comment by shanvrolijk** [comment]
I actually have zero knowledge on programming languague, thus, do not know how to address this problem. Thank you for your help, Hendrik. 😄

**Comment by nathanlesage** [comment]
Yes, let's hope the logging helps; I'll be releasing another beta with the additional logging on Friday! Maybe then it'll be clearer what the problem seems to be!
