### ISSUE TITLE
Making links to other slips (Question)

### ISSUE THREAD

**Issue by chasrmartin** [Zettlr/Zettlr#495]
So, I've got a bunch of notes in Zettlr now. I'm (trying at least) using a Zettlkasten system, and everything is mostly wonderful (I have a couple of feature ideas I'll do separately.) Using the suggestions in the app, I'm identifying my slips with time-stamped ID, eg, `20200125T140629`.  (I did modify the ID format to make it match the ISO standard, because my OCD kicked in at non-standard timestamps.)

There is one thing I haven't figured out: how do I usefully make links among my notes?

**Example**

I'm editing a slip with notes on the current status of the Wuhan coronavirus. I have a bunch of them and I want to refer to one that includes the Clinical Characteristics of Coronavirus. If I know the ID, I can
enter `[[20200125T140629]]`, which is fine. But how can I *find* the ID of the page I want to link other than by searching through everything in my file or at least everything with my associated tag?  Is there any way to search for the slip with the right information?

**Comment by nathanlesage** [comment]
As soon as you enter the second square bracket (`[[`), Zettlr should present to you a list of all files within the current directory, that you can then link! It will automatically use the ID, if present, else fall back to the filename!

P.S.: I hope you remembered to modify the regular expression for IDs, as due to the "T" the ID is not 14 consecutive digits anymore, right?

P.P.S.: Maybe the manual section helps understand how Zettlr behaves when using Zettelkasten-stuff: https://docs.zettlr.com/en/academic/zkn-method/ If not, please feel free to ask for advice and discussion either on our [Forum](https.//forum.zettlr.com/) or on the [Subreddit](https://www.reddit.com/r/Zettlr)!

**Comment by chasrmartin** [comment]
Hendrik, my problem is that I can look at 20200129T123101 and don't know
what's in the slip. Is there anything that would, say, preview the first
line?

**Comment by nathanlesage** [comment]
Ah, I see what you mean. Well, since 1.6 beta (and, therefore, in the final 1.6) you have an additional settings option that duplicates the filename when linking files, that is, a note with name "My note title.md" and the ID "20200129T123101" would, after linked, look like this: `[[20200129T123101]] My note title`
