### ISSUE TITLE
Frontmatter title not shown in combined sidebar.

### ISSUE THREAD

**Issue by Wieke** [Zettlr/Zettlr#500]
## Description
When you set a title in the frontmatter it is not shown in the sidebar when the sidebar is set to combined mode. The thin and expanded modes do work as expected.

## Reproducing
Set the sidebar mode to combined and set a title in the frontmatter of a file.

## Expected behaviour
I was expecting the filename in the sidebar to be replaced with the title.

## Platform
 - OS and version: Linux
 - Zettlr Version: 1.5.0
 - Screen Resolution: 1080p

**Comment by nathanlesage** [comment]
This was meant as by design, as the combined sidebar represents a file tree, whereas the file list abstracts enough so that overriding the title is acceptable without sacrifising intuition. My fear is that people (rightfully) see combined mode as a small finder/Explorer thingy, and when titles override filenames, this might cause confusion.

**Comment by Wieke** [comment]
Yeah I was wondering if it was on purpose, though it seem like the kind of thing that could easily happen by accident.

> My fear is that people (rightfully) see combined mode as a small finder/Explorer thingy, and when titles override filenames, this might cause confusion.

I get what you mean. But doesn't the tree in the combined view already break such expectations already? A representation of the file system wouldn't have virtual directories and would probably show non-document files as well.

Anyway I just started using the expanded view instead, it's not as if I need the entire width of the screen anyway.

**Comment by nathanlesage** [comment]
Alright, let's see if others have something to say so that we can find a good answer to the question whether or not YAML frontmatter titles should be parsed!

**Comment by rockandska** [comment]
Hi

> Alright, let's see if others have something to say so that we can find a good answer to the question whether or not YAML frontmatter titles should be parsed!

Having this as an option will satisfy all of us :)
And, maybe as an option too, when displaying the front-matter title, having the filename displayed as a tiny/discreet text just bellow the front-matter title will be nice too.

Regards,

**Comment by nathanlesage** [comment]
The latter one sounds more like something for the GUI considerations --> #448

**Comment by Sherl0ck007** [comment]
I just stumbled over this while frantically looking for an explanation why the title that I explicitly set for files doesn't seem to work. As the combined sidebar is the only useful version of the sidebar for me, as it is closest to the view one has when using an IDE, I was wondering why this was "broken" and then pretty disappointed that not even the setting that specifically says "Use H1 instead of filename if it exists" seemed to work in the tree view.

> Having this as an option will satisfy all of us :)
I believe @rockandska provided a good solution here and having it as an option in the combined view would be nice / very useful.

I would appreciate it (and I think not just me) if this could be picked up again and not end up stale and closed again.
