### ISSUE TITLE
[3.1.0-beta.1] Can't open files in file manager with mouse click

### ISSUE THREAD

**Issue by tafli** [Zettlr/Zettlr#5065]
### Description

Follow up of #5060.

It doesn't matter, where on the file tile I click, same behavior and file does not open. I took another screen cap to show with clicks at different positions.

https://github.com/Zettlr/Zettlr/assets/15720039/72c7bb40-2234-49c7-ba9d-311eac120c3e

### Reproducing

See description of #5060 

### Zettlr Version

Beta (if applicable)

### Specify version

3.1.0-beta.1

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Sonoma 14.4

**Comment by nathanlesage** [comment]
Thank you for the screen cap! Could you repeat this with the dev tools open? (Preferences -> Debug mode on; then Develop Menu -> DevTools)

Sorry that I didn't think of mentioning this earlier, I just remembered that this would be helpful!

**Comment by tafli** [comment]
What exactly do you want to see? Just checked with latest nightly and dev tools open. Console doesn't show any messages when clicking on a file. So I didn't make a new screen cap.

**Comment by nathanlesage** [comment]
Mh, that's not ideal. I tried the whole thing once more, but again, I can't reproduce this issue regardless of what I try on either macOS nor Manjaro. @wideaperture Do you have any insight? This still happens from time to time, no?

**Comment by wideaperture** [comment]
Hi @nathanlesage, the file manager has been working for me since the last fix you published. But it's apparently not fixed for everyone. I wish I had more insight, but sadly that's all I know.

**Comment by nathanlesage** [comment]
Thanks for letting me know! I guess we're going to find out after I publish the next beta 👀 Maybe we just need a bit of aggressive FSAL cache cleaning (btw it's still super amazing to me that cleaning that cache actually solves something, it's as if Zettlr by now is a real application where restarting fixes things consistently lol)

**Comment by wideaperture** [comment]
+1 For what it's worth, though — for other users trying to troubleshoot at the moment — when this bug was at its worst, the thing that initially worked wasn't clearing the FSAL cache, but deleting my Zettlr config folder and then re-adding my workspaces. I backed the old config folder up, of course, so I had a copy of my snippets and customizations to add back as needed.

Anyway, this didn't so much solve the problem as temporarily reset it — my file manager had been completely locked up and was now usable again, but almost immediately the same bug started creeping back in and more and more files became un-selectable (or clicking them opened the wrong document).

The fix @nathanlesage published in Nightly a couple weeks back did seem to fix the issue permanently for me, though (knock on wood). But apparently not for everybody.

**Comment by nathanlesage** [comment]
My maybe there indeed was a bug somewhere in the config that made it crash, and if you're the only one who deleted the config, then this might be the solution for others as well?

If I remember correctly, I did in fact make a bug some time ago that would store faulty data in the config, and that can be really bad depending on the circumstances.

**Comment by wideaperture** [comment]
It's possible! I don't know why the bug would've crept back in after I deleted the config folder, but it at least helped initially, which suggests there's something in `config.json` or elsewhere in the config folder that affects the problem. Is there anything in the config folder that changes or builds up over time that might be causing the issue?

**Comment by wideaperture** [comment]
Also, I think I sent a copy of my config data at [your request back in February.](https://github.com/Zettlr/Zettlr/issues/4968#issuecomment-1967048384) Dunno if you'd still have it, but perhaps it'd be helpful? I may still have the backup folder from that time if you'd like me to send it again.

**Comment by tafli** [comment]
Tested latest nightly at home on Manjaro Linux without any problem. Will test it on another macOS machine.

Don't know if it helps, but drag and dropping files works.

**Comment by nathanlesage** [comment]
Perfect, thank you so much for trying it out and confirming the bug seems fixed!

**Comment by tafli** [comment]
@nathanlesage Not fixed but only reproducible on my MacBook. My other machine running Manjor doesn't have this problem.

**Comment by obitwrite** [comment]
I had this problem too on macOS in beta.1 @tafli @nathanlesage.

Tested and file manager is still mostly unresponsive in beta.2.

However, when a file is open in a tab, it IS suddenly clickable in the File Manager. So when for example 5 files are open in tabs, these are all clickable in the file manager. I'm not sure this was the case in beta.1.

**Comment by nathanlesage** [comment]
So in other words we're getting there! Maybe I find something else workable soon

**Comment by tafli** [comment]
Can confirm in beta.2 as @obitwrite wrote: As soon a file is open, it becomes clickable in file manager. As soon it is closed only right mouse click and selecting "Open in new Tab" helps to open the file.

**Comment by nathanlesage** [comment]
> As soon it is closed only right mouse click and selecting "Open in new Tab" helps to open the file.

Wait a moment.

OOOOOHHHHH now I know what is happening — you guys have the "Avoid opening new tabs" setting checked! Hah, I always use new tabs for files, so I didn't pay attention that it broke at some point. It just isn't even attempting to open a file in that configuration. Oh, and the actual bug is as stupid as it can possibly get 🙄 

Fixed it, have a laugh at the change I had to do

**Comment by nathanlesage** [comment]
Also, as a courtesy to you so you don't have to wait: I just started an extra nightly run, so in about an hour or so, visit https://nightly.zettlr.com to get basically beta.2 but with a functioning file opening thing.

But also, I invite you to try out letting many tabs open, it's actually quite nice (but since it's now fixed, nobody has to :D)

**Comment by tafli** [comment]
Tested with the new nightly and can confirm, that open files works with one single click! 🥳

And yes, the Option to avoid opening new tabs was checked.

Thanks, @nathanlesage, for finding the bug and for fixing it!
