### ISSUE TITLE
Citations not generated in exported document

### ISSUE THREAD

**Issue by marcusyoung** [Zettlr/Zettlr#508]
## Description
After citation is added to document, it correctly expands and the reference is shown in attachments. When exported the citation is not expanded. Same problem in Word and HTML export.

## Expected behaviour
Citation to be generated in the PDF

**Screenshots**
![citation1](https://user-images.githubusercontent.com/10391966/73929742-4c128880-48cd-11ea-8165-791a82f049dc.jpg)
![citation_pdf](https://user-images.githubusercontent.com/10391966/73929752-4f0d7900-48cd-11ea-8ba5-32238413b13e.jpg)

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.6.0 beta

**Comment by marcusyoung** [comment]
After further investigation, this only occurs after I have added `--filter pandoc-crossref` to the pandoc command. Once I remove that it works again. But it should be ok to add this filter?

**Comment by nathanlesage** [comment]
The correct filter is `--filter pandoc-citeproc`, but you should not add it manually, because it will be included in the expanded `$citeproc$`-variable in the command. Here's where it is happening:

https://github.com/Zettlr/Zettlr/blob/e29d849538e7c7eff34e5b44f7924f0cc2e57b5b/source/main/modules/includes/run-pandoc.js#L50-L58

So within the default command:

```
pandoc "$infile$" -f markdown $outflag$ $tpl$ $toc$ $tocdepth$ $citeproc$ $standalone$ --pdf-engine=xelatex -o "$outfile$"`
``

`$citeproc$` will be expanded to `--filter pandoc-citeproc --bibliography link/to/file.json --csl link/to/style.csl`

In effect, this means: Specify a CSL library file, and all your citations (as far as they exist in the bibliography) will be parsed.

The `crossref`-filter is not even mentioned on the official manual, so I'm not sure what adding this actually does. It's in the scope of Pandoc, not Zettlr.

**Comment by marcusyoung** [comment]
@nathanlesage 

I was using the crossref filter to be able to use cross references for sections and figures, as discussed here: https://github.com/Zettlr/Zettlr/issues/248

**Comment by nathanlesage** [comment]
Ahh, that's why the name sounded familiar! Well, then it'll only work guaranteed once that issue is closed. But what you might want to check (because it'll help in closing the issue) is, if Pandoc accepts multiple filter-flags in `--filter filter1 filter2` or if `--filter filter1 --filter filter2` also works!

**Comment by marcusyoung** [comment]
@nathanlesage

According to the docs:
>Note also that the command line can include multiple instances of --filter: the filters will be applied in sequence.

I have it working by removing $citeproc$ and then adding this to the command:

` --filter pandoc-crossref --filter pandoc-citeproc --bibliography link/to/file.bib`

Marcus

**Comment by nathanlesage** [comment]
Have you tried adding `--filter pandoc-crossref` in front of the citeproc-stuff? This should also work

**Comment by marcusyoung** [comment]
Ah, yes that does work and is much easier! So now I have:

`--filter pandoc-crossref $citeproc$`

at the end of the command box. The other way around does not work.

**Comment by nathanlesage** [comment]
Perfect! The reason the other way around does not work seems to be that you have the chain `filter (arguments for the filter) another-filter`. Apparently, Pandoc breaks when filters do not strictly follow each other …

But I would suggest that this is something Pandoc could maybe alleviate by parsing the filters, chaining them up and THEN running the command! Apparently the docs are not completely correct on this one. Maybe consider testing this in some variants and then opening up an issue over there, because this is clearly not wanted!
