### ISSUE TITLE
Can't open/create files/folders

### ISSUE THREAD

**Issue by moedn** [Zettlr/Zettlr#514]
First of all: Thousand thanks for this brilliant software! I also highly appreciate the tone in the issue discussions. For this and so many other reasons I recommended Zettlr to many people and will keep doing so.

## Description
Since a few weeks I can't neither open files/folders nor create new files using Zettlr – so effectively I cannot use it at all.

## Reproducing
1. Open existent MD file or start simply Zettlr will give the same result → open the last file I created before the error came up
2. Click on "Open existing directory" & choose a directory
3. in-app notification appear: "Opening new root <folder_name>"; "<folder_name> has been loaded"
4. nothing changed; still the old file, no directory tree on the left ("No directory found").
5. "Create new file" will do nothing (also no notification); may be related to #467

## Screenshot
![Screenshot from 2020-02-07 16-49-36](https://user-images.githubusercontent.com/45949491/74048327-e821ba00-49c9-11ea-8e23-92e5fdbd2209.png)

Note: This error message came up while I created this issue. Don't know, if it's related.

## Expected behaviour
Open desired file or directory :)

## Platform
- Fedora 31
- Zettlr 1.5.0 (the error first occurred under (if I remember that correctly) 1.4.2, so I updated to 1.5.0)
- Screen Resolution: 1920×1080

## Additional information
This error occurs for any folder, regardless of the number of sub- or superordinate folders

Please let me know how I can provide more useful information, logs etc.

Thanks!

**Comment by nathanlesage** [comment]
Hmmmmmm … would you mind trying to rename your config.json-file in the app's data directory to something different? (This will re-create a fresh one). It might have to do with some changes in the directory structure, because Electron 7 introduced a weird bug that prevented directories from being loaded. This way, we could make sure that at least you can open something.

Background: If you open a directory with more than 7 or 8 subdirectories, this will prevent the transfer of information from the main process to the graphical interface, which in turn displays "No directory selected" (because none of the actually opened directories reach the graphical interface).

**Comment by moedn** [comment]
Thanks @nathanlesage for the super fast reply!
Renamed the config.json, started Zettrl, error persists, new config.json was created automatically.
I tried different directories (with and without various subdirectories).

**Comment by nathanlesage** [comment]
Hmmm … curious. Are your files on a network drive? And, just curious: Do older versions still work as expected? And, furthermore, what about the current beta version? If the error is gone in them, it's likely that it'll be gone in the stable 1.6 as well!

**Comment by moedn** [comment]
I originally tried to open a folder synced to a cloud (but not a network drive). However, the same error comes up with any other (local) directory.
If the beta doesn't work, I'll try an older version and come back here, thanks! :)

**Comment by moedn** [comment]
Alright, 
- 1.6.0-beta.1 does not work
- 1.5.0 does not work
- 1.4.1 does not work
- 1.3.0 **does work**

---

BTW 1.6.0-beta.1 conflicted with my installed signal instance:
```Error: Transaction test error:
  file /usr/lib/.build-id/3c/a310025e6d72d037f1fe23888c08317ff5c5f7 from install of zettlr-1.6.0_beta.1-1.x86_64 conflicts with file from package signal-desktop-1.30.0-2.fc31.x86_64
  file /usr/lib/.build-id/3e/0326bc2ef360cbd8a9d39169b3cffed688d09f from install of zettlr-1.6.0_beta.1-1.x86_64 conflicts with file from package signal-desktop-1.30.0-2.fc31.x86_64
  file /usr/lib/.build-id/40/b87885166f5ef16d1873ab3a91c5c8113a7657 from install of zettlr-1.6.0_beta.1-1.x86_64 conflicts with file from package signal-desktop-1.30.0-2.fc31.x86_64
  file /usr/lib/.build-id/43/403913e1ccc0475b5e2d1d2ddca551b8815a99 from install of zettlr-1.6.0_beta.1-1.x86_64 conflicts with file from package signal-desktop-1.30.0-2.fc31.x86_64
  file /usr/lib/.build-id/ab/b8ed97d406d9d9dda07e51af4fdf18fb3f5437 from install of zettlr-1.6.0_beta.1-1.x86_64 conflicts with file from package signal-desktop-1.30.0-2.fc31.x86_64
  file /usr/lib/.build-id/e4/d702c06d6d2db24de306bdf36168f02207268b from install of zettlr-1.6.0_beta.1-1.x86_64 conflicts with file from package signal-desktop-1.30.0-2.fc31.x86_64
```

**Comment by nathanlesage** [comment]
> BTW 1.6.0-beta.1 conflicted with my installed signal instance

WHAT o_O How the hell?

However, turning to Zettlr: 1.4 changed quite a lot. The 1.4.0, does this work? If not, then it's probably the many changes that were introduced there. But *maybe* it's because of some dependency issues between Electron and your distribution. I've had quite similar problems reported by users of certain Linux distributions that could be either resolved by installing or removing certain packages, but don't push me on that …

**Comment by KevinCaseiras** [comment]
I also encountered this issue this morning

Using Zettlr v1.5, I closed the directory I was working in and tried to open another directory. I got notifications saying the directory was opened but nothing was displayed. Then I couldn't open any directory, even ones that had previously worked.

However, I was able to fix it by closing Zettlr, renaming the config.json and starting Zettlr again. I still couldn't open the directory that initially caused the problem (if I tried to I would have to delete the config.json again), but I could open other directories.

For me, it seems to be an issue with nested files. Doing some testing I noticed if I open a directory containing a file like this: `one/two/three/four/five/six/file.md` it works but if I add one more nested directory like this: `one/two/three/four/five/six/seven/file.md`  it fails.

**Comment by nathanlesage** [comment]
Ah, concerning this, see this handy issue: #343 

This is an external issue, and the Electron crew doesn't seem to have much time for fixing this at the moment …

**Comment by moedn** [comment]
@KevinCaseiras yeah, looks pretty much like #343 
@nathanlesage yes, 1.4.0 works! (don't know how I could overlook that)

Anyway; resolving dependencies with electron sounds like a good idea. How can I do that? :)

**Comment by nathanlesage** [comment]
Well … I'll be upgrading Electron in Zettlr to 8.0 in a few seconds, and then … well, either it's resolved or we have to sift through the Electron issues to see if this is being addressed somewhere else.

If I remember correctly, the problem was that the JSON stringifyer they're using is broken, but afaik there was some initiative to replace that thing, but I'm not quite sure — if you'd like, please go have a look why this is happening! :)

**Comment by moedn** [comment]
Just let me know, when you're done, so I can try the new beta :)
Until then I continue enjoying the old days with v1.4.0

**Comment by nathanlesage** [comment]
It's building; once this is finished I'll be publishing it!

**Comment by moedn** [comment]
Huups, need to correct this:
> @nathanlesage yes, 1.4.0 works! (don't know how I could overlook that)

issue came back today. v1.3.0 is the last version working

**Comment by nathanlesage** [comment]
Whaaaaaaat! Nice! One of the best messages this week! :) And, also, of course, thank you very much for your support! :))

(Can I close this issue then …?)

**Comment by moedn** [comment]
:D 
Whoops, sorry forgot to mention this → yes, issue can be closed :)
