### ISSUE TITLE
Including <img> tags

### ISSUE THREAD

**Issue by marcusyoung** [Zettlr/Zettlr#518]
## Description
I don't know if this is a bug or a missing feature. Usually with markdown it is fine to include html tags. This is often used when you want to control the width of images. I have quite a few documents created in Typora where I have done this, for example:

`<img src="2020-02-09_16-28-28.jpg" alt="2020-02-09_16-28-28" width=400px />`

But these aren't recognised by Zettlr, either in the app itself or when exported to PDF. The images are in the same folder as the document and appear in the attachments list.

**Comment by nathanlesage** [comment]
When exported to PDF, they don't work, you have to either use Markdown (and therefore have LaTeX control the size of your images) or LaTeX commands directly. But for the HTML preview … I mean I could add that, but concerning image sizes, I'm not sure of how to handle this (that's where the display image size preferences are for)!

And don't forget, Zettlr tries to do WYMIWYG, not WYSIWYG, and I therefore want to think about such things before implementing them :S

**Comment by marcusyoung** [comment]
ok, thanks.

**Comment by Annakan** [comment]
Hello
I feel like posting and +1 this issue because I feel the use case is very valid and is probably (from a not scientific ego centered point of view  ;) ) keeping a few many users from switching or seriously testing zettlr.

Basically it goes like this, you have a bunch of markdown files, maybe edited with Typora who does a great job as a markdown editor, and you open them with Zettlr. You see that none of your pictures show up and deduce that zettlr does not honor the (dubious but existing) "html is valid in markdown" mantra (and anyway is is time to go beyond markdown but that's another rant ;) ).

Non tech oriented users will probably stop at this point, lazy tech users will consider the benefits of making a big and complicated search replace in their documents to replace the <img> tag (because using regex with html open a[ doorway to hell, or at least ancient ones](https://blog.codinghorror.com/parsing-html-the-cthulhu-way/)), and then have all their document change format because the images have changed size. 
Regarding this, the preference slider is too coarse to fill the <img> tag  role, since it applies to all images regardless of their use : I want my rpg character pictures small but my maps big, I am picky like this ;)

To be honest and although I am a developer by trade (a bad one but still) , this is the major blocker to switch : is it worth going through all my docs changing this images and going back to managing my markers manually for benefits of Zettlr I do not "feel" yet (because I am a novice with it) ...

**Comment by rayachristian** [comment]
Many users need Zettlr to write simple README.md files.
<img> tags are supported by:
  - Github
  - Gitlab
  - Codeberg
  - the Markdown Viewer plugin for browsers
  - Marktext
  - ...

It is therefore clear that this is a significant limitation of Zettlr.
