### ISSUE TITLE
Bug: Math rendering

### ISSUE THREAD

**Issue by demersn** [Zettlr/Zettlr#52]
Math rendering seems arbitrary and sometimes behaves in unwanted ways. Getting out of preview also seems arbitrary. In my case, text following a simple line such as
Xh @ Y $/h = Y$ 
renders everything following Y in math mode. Not sure what triggers the math rendering but it it annoying and affects readability.

**Comment by nathanlesage** [comment]
Heya,

currently, math rendering is triggered by the following three options:

- Somewhere in a line there is text encapsulated by `$` and `$`
- Somewhere in a line there is text encapsulated by `$$` and `$$`
- A line equals `$$` and there is a line afterwards that also equals `$$`

If there is only `$$` on a line (i.e. math without any contents) or `$$$$`, or if a `$$`-line is not followed by a closing `$$`-line math won't trigger.

So I assume you want to use only single-$-signs without them rendering math? Or is the problem something different, such as Zettlr rendering *everything* after the first dollar-sign?

**Comment by nathanlesage** [comment]
Ahh, I think I fixed it. I updated the regex to match the following:

`/^\$\$(.+?[^\\])\$\$|(?<=[^\\])\$\$(.+?[^\\])\$\$/g`

Now you can't use single-dollars anymore to mark a Math equation, but I hope that won't be such a problem?

Cheers!

**Comment by corypanshin** [comment]
Is it possible to allow for having dollar signs in ordinary text without it triggering special formatting between them?  For example, I have one item that currently reads, "Prince has long been a contributor to the campaign of fellow Christian warrior Mike Pence, and he contributed \$100,000 to the pro-Trump SuperPAC Make America Number 1.  Prince's mother, Elsa, pitched in another \$50,000."  Until I added the backslashes, everything between the two dollar signs was appearing in a large italic font with no spaces between the words.  With the backslashes, it now renders properly, but trying to clean up lengthy quotations in the same way is obviously not a practical solution.

nathanlesage's common of November 3, 2018 seems to imply that he thought the problem was fixed, but I've been through several updates since then, including the most recent, and it clearly isn't.  (Windows 7, current version of Zettlr 1.2.2.)

**Comment by nathanlesage** [comment]
@corypanshin Yes, I've noticed this as well. I've been thinking about it and while I think the escaping is a reasonable workaround for now I think I'll add an additional check to make sure the opening dollar sign should not be followed by a space, as well as the closing dollar sign should not be preceeded by a space!
