### ISSUE TITLE
Sidebar → Other Files shows nothing

### ISSUE THREAD

**Issue by HJKLE** [Zettlr/Zettlr#5264]
### Description

Up to version 3.0.5, you could see all files in the sidebar that were in the folder that you had clicked/activated in the workspace view.

Since version 3.1.0, maybe earlier in the betas, nothing is displayed here. Only the message: 

#### Current folder
No other files

When I select a path to the default image folder, the only file in this folder is displayed correctly and can also be selected.

![Bildschirmfoto_2024-07-06_19-15-57](https://github.com/Zettlr/Zettlr/assets/133958042/b34adab0-b0fd-4643-87f7-34d3cdbbdf39)

However, the standard image folder contains lots of subfolders with PDF, Excel and ODT files. These are not displayed. Version 3.0.5 has managed this without any problems.

Following file extensions are activated to be visible in the sidebar:

![Bildschirmfoto_2024-07-06_19-13-27](https://github.com/Zettlr/Zettlr/assets/133958042/83c48811-7661-43c6-af3e-aa150bb93166)

### Reproducing

Install Version 3.0.5 and click on a random folder with files. All files whose file extensions have been set as visible in the settings under "Advanced" should be displayed.

### Zettlr version

3.2.0

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit (includes Apple Silicon)

### Operating System Version

Ubuntu 22.04.4 LTS (Xfce 4.16)

### Additional Information

Am I wrong to expect a different behaviour here? I am irritated because it worked differently in version 3.0.5 and I have based my entire workflow on this behaviour, among other things.

**Comment by nathanlesage** [comment]
This was a change as noted in the changelog for version 3.1: from then on there are two folders that will be considered for asset files:

1. The current file's folder 
2. The standard image folder (if absolute, it will always be the same, if relative, then relative towards the file's folder)

I agree that this could be overlooked due to the large amount of changes, but it was in there.

I'm CC'ing @sensologica because we may have to think about if we could improve the UX here, but it's not a bug. For further discussions, please join our [discord](https://go.zettlr.com/discord) so that we can find a solution that works for everyone.

**Comment by nathanlesage** [comment]
I agree that this was a (technically sound but UX wise super stupid) too fast change and I intend to reverse this behavior again. There are already some issues open which is why I closed this one -- to keep it all a bit more manageable. I haven't forgotten about this!
