### ISSUE TITLE
[Bug] tags cloud doesnt point to files  in subfolders when in root folder

### ISSUE THREAD

**Issue by danieltomasz** [Zettlr/Zettlr#530]
## Description

I  put  my zettlekasten notes into hierarchical  folder structure (root + subfolders, notes divided between private and academia ).  

 Now  while being  in  a  root folder in tree filepreview, the tag cloud  doesnt hyperlink  to specific files.
After  cd to subfolder containg note, tags are hyperlinking again.  

Tags cloud  always display all tags, including tags  pointing to files from other subfolders too. 

## Expected behaviour
I am not  sure what expected behavour should be. 
Eithe having global tags, hyperlinking to other folder too, or folder specific only.

**Screenshots**

## Platform
 - OS and version: Ubuntu 18/04
 - Zettlr Version: latest beta
 - Screen Resolution:

**Comment by nathanlesage** [comment]
It's indeed a global tag cloud. Some folder specific would require significant rewriting of code, or multiple databases. Due to low priority I'm closing this, BUT if the need arises definitely to have folder-specific tag clouds in any form, feel free to discuss that on the [Forum](https://forum.zettlr.com) and then we can do this at a later point in time.

Reason is that I'm maximally low on time, and concerning Zettlr, we have a German saying: "Die Hütte brennt"

**Comment by danieltomasz** [comment]
Would be nice to have visible link to forum (maybe with explicit encouraging people to go there to discuss enhancement) in README and on Zettlr page (at least I didnt find it)

**Comment by nathanlesage** [comment]
The forum is under the "Resources"-dropdown — there was not so much space in there :S 

But putting it in the Readme is indeed a good idea!
