### ISSUE TITLE
Install requires acceptance of the GPL which is a misconception of what GPL is

### ISSUE THREAD

**Issue by zyga** [Zettlr/Zettlr#5335]
### Description

GPL is a _distribution_ license. Nobody needs to accept GPL to use the software it is distributed under. GPL binds the distribution of the software. As a user I do not need to accept the GPL to use the software, only to share it further.

This is a common mistake where an installer uses a "license" or "eula" screen to show what is ultimately a distribution agreement and not any constraint on usage.

This is common enough that there's a FAQ entry on https://www.gnu.org/licenses/gpl-faq.html#ClickThrough

I would suggest to modify the installer to display the license, but not offer any acceptance checkbox or control.

### Reproducing

Install Zettlr using the Windows installer.

### Zettlr version

3.2.0

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit (includes Apple Silicon)

### Operating System Version

Windows 11

**Comment by nathanlesage** [comment]
This is an interesting point. Indeed, I'm merely using the predefined places to add the GPL license, and I agree that it's not technically true that you have to "accept" the GPL for using the software.

However, I will keep it as it is for now, for the following reasons:

1. I want to keep the GPL being shown to users, even if only to raise awareness for its existence. People usually only see weird commercial EULAs and so seeing a GPL license that actually doesn't bind you to anything is nice, and possibly educational for a lot of people.
2. It raises awareness that, if users want to modify the software, they already have seen the license's name somewhere, making it less likely for people to ignore the license agreements if they distribute Zettlr's source code in closed source applications. On a pure legal basis, it's simpler because it will be harder for those people to argue "oh we didn't see the license :O" and easier for me to potentially sue people should I get to know this.
3. It's not legally binding, so even if you click "accept" you don't actually have to accept anything. Most people will click accept anyhow, and those who are unlikely to do so are usually the ones actually reading the license, thus realizing they aren't accepting anything when they click that button.
4. Finally, I think it's nitpicky. The benefits of showing the license to people by far outweigh the technical wrongfulness of the confirm button's label. This is corroborated by the FAQ entry you linked: `This is neither required nor forbidden.`
