### ISSUE TITLE
Checkbox with link

### ISSUE THREAD

**Issue by demersn** [Zettlr/Zettlr#54]
## Description
Checkboxes followed by links don't render properly.
It shows as
`- ] [foo`
when 
`- [ ] [foo](foo.bar)`
has been written

## Reproducing
Start with a checkbox, and follow up with a link. 

## Expected behaviour
Should render as you would expect

## Platform
 - OS: Win10
 - Zettlr Version 0.20.0

**Comment by nathanlesage** [comment]
I'm on it!

**Comment by nathanlesage** [comment]
Hey,

I just had the chance to check the issue. It did render perfectly well and as you would expect it in the current development build.

On investigating I could confirm that 0.20 still had the wrong regular expression for detecting links:

https://github.com/Zettlr/Zettlr/blob/3beb5ccc97da020b1b48a256c1cfd1a146514710/source/renderer/assets/codemirror/zettlr-plugin-render-links.js#L19

But it had already been fixed, that is: it will be fixed in 0.21!
