### ISSUE TITLE
After updating from version 3.2.3 to 3.3.0, local images and external links in my md files do not work anymore

### ISSUE THREAD

**Issue by marziod** [Zettlr/Zettlr#5489]
### Description

After update from version 3.2.3-x64 to 3.3.0, Local images and external links does not work

### Reproducing

1) enter a .md document with an image reference, from example
![Graph](./Local graph.png)
the image does not show up
2) or a document reference:
[test.pdf](c:\path\test.pdf)
doing ctrl + click does not open the document with the default windows application

### Zettlr version

3.3.0

### Installation Method

Other (please specify below)

### Installation Method (Other)

Update popup from Zettlr version: 3.2.3

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit (includes Apple Silicon)

### Operating System Version

Windows 11

**Comment by tfr00** [comment]
Same here. Pasting images (copy+paste) ends up in something like: "![3e5643180d76638a.png](..\..\..\..\..\..\..\AppData\Local\Temp\3e5643180d76638a.png)". The path-error is reproducible! Also normally copy+pasted images are saved to path of the specific md-file not in a temporary folder. External (Web)links (incl. Frames) are working fine.

Something similar happend some versions before. 

Windows 11, Version 3.3.0. Version before was OK.

**Comment by nathanlesage** [comment]
I suspect this to be an issue in the new handler for the safe file protocol. I'll see if I can boot up my windows machine tomorrow to follow this up, but I don't know if I will have the time. If someone else has time and energy to track it down before me, please do so, this sounds like a bad time. PRs very welcome!

**Comment by nathanlesage** [comment]
Also, another observation: this bug seems to be exclusively related to Windows, so I strongly suspect an issue with windows path names.

**Comment by nathanlesage** [comment]
I now did some digging, and it was a bit more work than expected. Specifically, since we now must accept URLs instead of plain file paths slapped onto `safe-file://`, Windows is making problems.

So, **I hereby confirm that it is exclusively related to Windows.** If you use macOS or Linux, you have nothing to fear.

Here's what's happening:

In order to either display an image or open a file remotely, we utilize a custom protocol, `safe-file`. This has worked fine thus far with our `registerCustomProtocol` implementation, because it took the requested URL literally. Now, that we have had to switch to `handle` (we had to do this, prescription from the Electron team), this function parses the URL, thereby doing some funny things.

Now, what are the funny things, you may ask? Well, here's the thing: Windows uses this thing called drive letters (`C:`), but they contain a colon, which is illegal in the pathname part of a URL. What we have to do is basically force Windows from `C:/something` to `/C:/something` to ensure that the URL gets properly encoded and understood.

The `URL` constructor already does this automatically, but it forces usage of the `file` protocol. Instead of trying to pry apart the logic I've built over many years to parse a variety of links, I now decided to literally monkeypatch adding and removing a slash in front of Windows drive letters into the code base. Thus far, it appears to work.

For reference: https://en.wikipedia.org/wiki/File_URI_scheme

***

It has now been fixed, and I'll start a new patch immediately. I really hate this OS, did I already mention this?

CC @kyaso, and bring popcorn, I'm very salty atm

**Comment by tfr00** [comment]
Every is working as intended again. Thank you!
