### ISSUE TITLE
Source code archive for 3.3.0 seems to actually include 3.2.3

### ISSUE THREAD

**Issue by tramir** [Zettlr/Zettlr#5490]
### Description

The source code archive from [https://github.com/Zettlr/Zettlr/archive/refs/tags/v3.3.0.zip](https://github.com/Zettlr/Zettlr/archive/refs/tags/v3.3.0.zip) seems to include version 3.2.3 instead of 3.3.0. At least that's what is listed in package.json:
`https://github.com/Zettlr/Zettlr/archive/refs/tags/v3.3.0.zip`

Compiling from source produces indeed version 3.2.3, which warns that an update to 3.3.0 is available.

### Reproducing

Click on the link for source code under [https://github.com/Zettlr/Zettlr/releases/tag/v3.3.0](https://github.com/Zettlr/Zettlr/releases/tag/v3.3.0)

### Zettlr version

3.3.0

### Installation Method

From the Website or GitHub

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit (includes Apple Silicon)

### Operating System Version

Sequoia 15.1.1

**Comment by nathanlesage** [comment]
This is a non-issue. I forgot to manually put the target branch to master, making it pull from develop, but the literal only difference is the version number, because that's the only thing I always change on master. Plus, I'll be releasing a patch in a few minutes, then the Zip files will be up to speed again.
