### ISSUE TITLE
Disable auto-completion in the search field

### ISSUE THREAD

**Issue by Zverik** [Zettlr/Zettlr#550]
## Description

Currently when you type something into the search field, it tries to auto-complete file names from the current directory. Please disable it, since it interferes with real search queries.

## Reproducing

Type something that starts as an existing file. E.g. you're searching for "zettlr", but you have "zettlr-plans-2020.md" file, and you have to be very careful to remove the part you don't need.

## Expected behaviour

No autocomplete. Or autocomplete _only_ for tags (after entering `#`).

## Additional information

When I click the search field, I know what I'm searching for. Very seldom I use a full file name for searching: often it's a term that can be either in file name, or in tags, or inside a file. Autocompletion for file name requires me to constantly watch the field to remove the part I don't need.

Usually in search field auto-completion is done not by filling the rest of the string, but by opening a drop-down list. That way you can continue typing what you want and ignore the list if you don't need it. Interfering with the user input is considered a bad practice, leading to errors.

Obviously this issue won't bother those who start their file names with an id.

**Comment by quickfold** [comment]
I agree that this should be fixed but recommend disabling autocomplete by starting queries with a specific character, such as `
I suppose the default (auto-complete or not) should be determined by whether most actual user searches are helped or hurt by autocomplete.

**Comment by nathanlesage** [comment]
Well, what I was anticipating with the autocomplete was to have a full dropdown where matching files would appear, so that you could select these with arrow-keys. I did implement the autocomplete in such a way that it would not override any of your own characters, so characters would appear until the first one results in a query that does not match a file name. If you want to search for something, simply type in everything and don't let yourself be distracted, and once you're ready and there's still autocompletion text, a simple backspace will remove it — the added text is ALWAYS selected so that you can easily remove it. Nevertheless, a dropdown might be worth considering.

**Comment by Zverik** [comment]
One of the questions is — does this autocomplete in its current form really help with anything? E.g. won't it find the note without autocompleted file name?

**Comment by Zverik** [comment]
> and once you're ready and there's still autocompletion text, a simple backspace will remove it — the added text is ALWAYS selected so that you can easily remove it.

Suppose you typed a string with a typo, and returned to add two missing characters inside. Suddenly when you type the first character, it get autocompleted (because you've got a thousand note names, and one of them matched). Now you have to:

1. Press "backspace" to remove the autocompleted part.
2. Press "left arrow" key enough times to return to the position you need to add the second letter.
3. Add a letter.
4. Remove autocompleted part once more because you're not searching for a file, but for a word inside files.

I've stumbled upon this once, and it was very frustrating.

**Comment by nathanlesage** [comment]
Yeah, but only once :P 

The main idea was that I found it cumbersome to always type the exact file name (because searching for an exact file name will open the file, it's sort of a quick jump), so it helped. But as I said: I could implement a dropdown at some point, something like "Jump to file xyz".

**Comment by Zverik** [comment]
I suggest splitting "make a proper drop-down for autocomplete" from this one, "disable current autocomplete". Would you be okay with that? The first one is a big feature, the second can be done in a minute.

**Comment by nathanlesage** [comment]
Be that as it may, but I don't want to disable the autocomplete without replacement, so I'd rather suggest putting this up to a high priority after 1.6. There are people who rely on that feature.

**Comment by BellLongworth** [comment]
Trying to solve two very different features at once is hard.

If you search for a specific file, you want full autocomplete all the way to the file name and the ability to initiate the search with one Enter. This can expand to a drop down if there are multiple matches.

If you search for a word or a tag (everything related to "something"), you may want autocomplete on a WORD level (so "somet" becomes "something"), or you may not want it at all. 

The backspace solution mentioned [here](https://github.com/Zettlr/Zettlr/issues/550#issuecomment-588681358) is problematic. Search is an action that is done very frequently and becomes one done through muscle memory. Since backspace is sometimes needed and sometimes not, this gets really confusing.

A possible quick solution (maybe not great, I'm brainstorming) is to have the auto-complete text show but for search to not actually search for it unless the user presses tab first.
So if I type "writ" and press Enter, I get results for "writ". If I type "writ" and press Tab-Enter, I get results for "writing".
