### ISSUE TITLE
[ENHANCEMENT] Undo/redo history for multiple files.

### ISSUE THREAD

**Issue by Wieke** [Zettlr/Zettlr#552]
## Description

I would like it if the editor would keep track of undo/redo history for multiple files. My current workflow has me switching between files a lot, either to edit something or to reference something in another file (though I just remembered I could use quicklook for the latter), and it's sometimes quite inconvenient that the editor seems to discard history the moment I open another file.

## Proposed Changes

Have the editor keep track of edit history per file and have undo/redo actions be performed based on the history of the file currently open. Only discard history when closing the editor or removing a file.

## Caveats

It would increase the memory usage of the editor. This could be curtailed by limiting the amount of history tracked per file, or the number of files whose history is being tracked. Though I suspect this wouldn't be much of a problem, as modern systems tend to have plenty of memory.

**Comment by nathanlesage** [comment]
This will come, once I implement tabs, anyway, because implementing tabs means that I'll cache the CodeMirror `Doc` instances, along with their history! :) (which means I'll be closing this issue for now, but if something bothers you once tabs/multiple files are implemented, please feel free to comment back on this issue again so I can re-open it!) --> #243 

Just a word of caution: Before I can implement multiple files, I'll have to rewrite the file system; but I already started doing that so hopefully it'll make it till 1.7! :)

**Comment by Wieke** [comment]
Nice.

I kinda assumed Zettlr not having tabs was a deliberate design decision. But yeah having tabs would also solve this.

**Comment by nathanlesage** [comment]
It was a deliberate design decision, but it was based on the original design of Ulysses, and this turned out to be more of a hassle (as long as you don't need to simply copy from other notes, more tabs are definitely preferable to QuickLooks)
