### ISSUE TITLE
[BUG] Words that have trailing "#numbers" are highlighted

### ISSUE THREAD

**Issue by Zverik** [Zettlr/Zettlr#558]
## Description

For some unknown reason in `whatever#123` the word gets highlighted.

## Reproducing

Write `whatever#123` (without a space) anywhere.

## Expected behaviour

Expected nothing to be highlighted here. It's no link or nothing. Instead, the "whatever" is colored like a link. Nothing happens when I Alt-Click on it.

This does not happen when there are letters after the `#` instead of digits. An advice "just add a space" won't help, because that way `#123` would become a tag.

## Additional information

I've studied Markdown docs — nothing there suggests this notation means anything. Github doesn't highlight this: whatever#123.

MacOS 10.14.5 / Zettlr 1.6.0 beta4

**Comment by nathanlesage** [comment]
Funny bug :D I'll have a look.

**Comment by nathanlesage** [comment]
This is due to the underlying Markdown mode, so it's out of the realm of Zettlr and in the Realm of CodeMirror, but I fear one has to make a PR to fix that behaviour, as the mode seems to be not actively maintained at the moment! (See, e.g., John's comment on this issue: https://github.com/codemirror/CodeMirror/issues/6129)
