### ISSUE TITLE
[FEATURE] Toggle block

### ISSUE THREAD

**Issue by PiotrSss** [Zettlr/Zettlr#574]
## Description

Basically a copy of functionality from Notion https://www.notion.so/Toggles-c720af26b4bd4789b736c140b2dc73fe

It would allow to use [Active Recall](https://www.youtube.com/watch?v=fDbxPVn02VU) method combined with [Leitner system](https://en.wikipedia.org/wiki/Leitner_system) for spaced repetition (using tags, e.g. #srs1, #srs2, etc. and scheduling it in some task manager/calendar) directly in this app.

I guess the major building blocks are already there, because one can toggle headers, so one could just use ##### for that, but the problem is that it doesn't remember state of the toggle, everything is visible when user came back to the note.

**Comment by Zverik** [comment]
1. Zettlr is a markdown editor. What's the syntax for toggles? It's not clear from the Notion documentation.
2. What use cases of toggle blocks are not achieved with a table of contents?

**Comment by panpiotrs** [comment]
```
- Question

    Answer
```

is how Notion does this in export to markdown. But it's how simple bullets are done in markdown so it will not be possible without extending/playing with default syntax. The simplest solution would be probably to use `-` and `+` to store state in plain file (- when open, + when closed), with option in preferences "Render toggle blocks" (or something like that) to add toggling arrow on the left (identically as with headers) only if there is text indented below line starting with `-` or `+`. Shouldn't interfere with default use case of using `-` line after line to render simple lists if someone would like to have both toggles and normal lists, I think.

**Comment by ibihim** [comment]
Isn't the most sexy syntax for using it quickly, but it seems to be supported in GitHub that way:
https://gist.github.com/Ashton-W/864d09d71f7cb8e5b47ebaac02b98455

I think it is super useful, the same you can toggle code block in IDEs.

**Comment by Zverik** [comment]
You can toggle chapters in text, and that's good enough imo.

**Comment by ibihim** [comment]
Yes, this is what @PiotrSss said: "I guess the major building blocks are already there, because one can toggle headers, so one could just use ##### for that, but the problem is that it doesn't remember state of the toggle, everything is visible when user came back to the note."

The point of toggling is to hide answers for questions in order to do active recall as the combination of spaced repetition and active recall seems to have the strongest positive impact on learning success. So if you tell me a quality of life feature for a knowledge management tool is not necessary, that is good to know.

Resources about the benefits of practice-tests / active recall vs other echniques of learning:
- [Retrieval Practice Produces More Learning than Elaborative Studying with Concept Mapping](https://science.sciencemag.org/content/331/6018/772.full)
- [ Improving Students' Learning With Effective Learning Techniques: Promising Directions From Cognitive and Educational Psychology
](https://pubmed.ncbi.nlm.nih.gov/26173288/)
- [Studies in Retention](https://www.gwern.net/docs/spacedrepetition/1939-spitzer.pdf)

**Comment by nathanlesage** [comment]
Zettlr is first of all a Markdown ("Word Processor") editor, not a system designed for SRS, for which I'd recommend the [Mochi app](https://mochi.cards/), and not Zettlr. Knowledge management is built-in, but only so far.

**Comment by ibihim** [comment]
Ok, sure. If the purpose of this software is laser-sharp-defined and won't be touched, I respect that. And thanks for the suggestion!

I started to inspect Zettlr after seeing that the [pay-wall protected version](https://roamresearch.com/) of it is super expensive and considered it for all the things.

**Comment by nathanlesage** [comment]
Yeah, I wanted to go in that direction with Zettlr for some time, but after all I had to realize that it's much more important to have a good challenger to Word Processors (as the whole SRS/PKM market is pretty much saturated now with all those apps like Roam, Obsidian and Mochi)
