### ISSUE TITLE
[ENHANCEMENT] Support title metadata when adding internal links

### ISSUE THREAD

**Issue by nistude** [Zettlr/Zettlr#587]
## Description

I would like to use `title` metadata when adding internal links.

## Proposed Changes

I use note IDs as filename to have them static and use note metadata to set the actual title of my note (which changes sometimes when I find a better title). Internal links with `[[` only provide access to the filename, so I can only select from IDs, which is not really helpful. At the moment, I have to copy and paste note IDs manually.
My proposed change is to add the title metadata or maybe even replace the ID with the title in the search. I cannot imagine someone actually searching notes by ID but you never know...

## Caveats

With this change comes the question of how to represent the link in the document. At the moment my notes look like
```
See also "some other note title" [[1234455]]
```
I can imagine something like
```
See also [[some other note title]]
```
to be a sensible replacement. Personally, I would find it distracting to have the ID in front of the title.

**Comment by nathanlesage** [comment]
Well, I think there are two different chunks we're talking about: First the dropdown list that gives you all notes — with an ID-only filename it's definitely hard, of course. But I can add potential titles to that dropdown list so that you can search for these as well, and still link using the ID!

Then the representation: I personally fear that allowing notes to be linked using their YAML title would make the system vulnerable to volatilities in this respect, but maybe this is something that might fit well into this issue here: #559

**Comment by nistude** [comment]
Having titles in the dropdown is definitely the most crucial part for me and focus of this request.

**Comment by nathanlesage** [comment]
Perfect, should be easily implementable!

**Comment by nathanlesage** [comment]
In fact, it's already implemented, one line of code added :D
