### ISSUE TITLE
Transaction test error: conflicts with signal-desktop 1.32.1

### ISSUE THREAD

**Issue by moedn** [Zettlr/Zettlr#589]
### Thanks
for this awesome piece of software that I almost have/had in use on a daily basis. Keep it up! :)

### Bug Description

The latest package of signal-desktop conflicts with the latest version of [zettlr](https://github.com/Zettlr/Zettlr) → I cannot have both installed on my system.

I created the same issue in signal's repo ([link](https://github.com/signalapp/Signal-Desktop/issues/4026))

### Steps to Reproduce

1.  install zettlr v1.6.0
2.  (try to) install signal-desktop 1.32.1

…or vice versa

### Platform Info

Signal Version: 1.32.1-1.fc31.x86_64

Operating System: Fedora 31

Zettlr Version: 1.6.0 (v1.5.0 _did not_ conflict; error first appeared with 1.6.0-beta)

### Log

directly copied from the terminal when trying to install signal-desktop:

```
Error: Transaction test error:
  file /usr/lib/.build-id/4b/e54e7b4072d723a4bf5d11f7ef2b7b2e3b3a26 from install of signal-desktop-1.32.1-1.fc31.x86_64 conflicts with file from package zettlr-1.6.0-1.x86_64
  file /usr/lib/.build-id/5b/fbd3977f004574cd6668333fd1dc52e6b31010 from install of signal-desktop-1.32.1-1.fc31.x86_64 conflicts with file from package zettlr-1.6.0-1.x86_64
  file /usr/lib/.build-id/68/31304e78fc4f4cd1bd8216d99e32dabe4973c3 from install of signal-desktop-1.32.1-1.fc31.x86_64 conflicts with file from package zettlr-1.6.0-1.x86_64
  file /usr/lib/.build-id/72/d86eb8b1163969d3fc6f34b62b5160a33ad726 from install of signal-desktop-1.32.1-1.fc31.x86_64 conflicts with file from package zettlr-1.6.0-1.x86_64
  file /usr/lib/.build-id/75/2db195051aa513f5916d17ecc6e5d755124e14 from install of signal-desktop-1.32.1-1.fc31.x86_64 conflicts with file from package zettlr-1.6.0-1.x86_64
  file /usr/lib/.build-id/9f/604335c41e24151c5dbca16a33b81dc56c4c54 from install of signal-desktop-1.32.1-1.fc31.x86_64 conflicts with file from package zettlr-1.6.0-1.x86_64
  file /usr/lib/.build-id/cc/813d23c84126298d221a8a7c70184d3fca320d from install of signal-desktop-1.32.1-1.fc31.x86_64 conflicts with file from package zettlr-1.6.0-1.x86_64
  file /usr/lib/.build-id/cf/cca356ccaabf8d1e182054675cf63a92ad57a9 from install of signal-desktop-1.32.1-1.fc31.x86_64 conflicts with file from package zettlr-1.6.0-1.x86_64
  file /usr/lib/.build-id/f1/49c1b37a035c9c336c70bb56777811230332c9 from install of signal-desktop-1.32.1-1.fc31.x86_64 conflicts with file from package zettlr-1.6.0-1.x86_64
```

**Comment by nathanlesage** [comment]
> Signal doesn't officially support Fedora. You'll need to reach out to whoever produced the package you installed.

Whoa, someone's cocky over there…

Well, Signal is also built upon Electron and I would guess that that's the problem. In the past, me and many others have — from time to time — experiences super interesting situations where every electron app AND Chrome itself would simply freeze at the same time, crash at the same time or something like this.

It's interesting because \~something\~ in the codebase of Chromium seems to rely upon a certain piece of memory or a file or something along the lines of this, and if several instances of Chromium including Electron are accessing it at the same time … boom. However, I assume that maybe Fedora doesn't like two different versions of the Electron framework being installed — the problem could be that Zettlr is currently at Electron 8, while Signal uses Electron 8.0.3.

But what you could suggest is that they simply throw out Fedora packages like I do. As long as they do not have any native code that would need to be ported, it's a matter of three lines of code in the build-script. And I just had a look at the mess they did with their codebase — nothing seems to be native Rust/C/whatever-code that needs to be compiled. If they offer Debian, Signal _does_ support Fedora natively as well.

**Comment by moedn** [comment]
Thousand thanks (again) for this super fast and competent reply. This is not a crucial issue for me; I just wanted to keep it documented. However, it seems to be a electron-specific issue anyway. Plus rather on Signal's than on Zettlr's side.

I'll close the issue here then :)

**Comment by nathanlesage** [comment]
Alright, if anything else comes up, please let me know! :)
