### ISSUE TITLE
[ENHANCEMENT] Adding highlight formatting to text format -menu

### ISSUE THREAD

**Issue by ME7DYCgw8M** [Zettlr/Zettlr#603]
## Description

Highlight formatting could be added to text formats -menu.

## Proposed Changes

Highlight should be added to text formats -menu. Maybe settings dialog should also have radio button, so user could choose which characters triggers the highlight. Like bold and italics have.

## Caveats

I guess highlighting is not basic markdown functionality? Formatting would not work with other programs.

## Additional Information

For those who don't know; in Zettlr text can be highlighted with surrounding == or ::.

**Comment by nathanlesage** [comment]
> I guess highlighting is not basic markdown functionality?

This is the reason I added the support, but without much pomp, because it's not standard and if there's too many too visible options to highlight, this would prompt many users to use it more, and then complain that it's not working with anything else. I wanted to give the option to users who knew what they were doing!
