### ISSUE TITLE
Recognition of special characters in tags and nested lists not being indented

### ISSUE THREAD

**Issue by Shandi97** [Zettlr/Zettlr#61]
Hello its me again with tags once more.

I mostly write in English so I haven't noticed it until recently. Zettlr doesn't appear to recognize in tags characters that are not part of basic Latin alphabet. My native language is Slovak so that is a problem because it uses a lot of special characters with diacritic marks.

I assume you are already familiar with this since you speak German and it also has some special characters which likewise don't appear to be recognized unless I missed something.

There is also a second minor issue, it isn't that important to me but I will mention it just in case.

My nested lists which I made in other markdown apps (ghostwriter, QOwnNotes) didn't seem to display properly (they weren't indented) in Zettlr. This I found out appears to be because I used TAB to make them, in Zettlr doing so works alright but doing so in those apps and then opening the file in Zettlr results in the above issue. This appears to be because Zettlr when using TAB creates four spaces whereas those two don't.

**Comment by nathanlesage** [comment]
> I mostly write in English so I haven't noticed it until recently. Zettlr doesn't appear to recognize in tags characters that are not part of basic Latin alphabet.

That is by design. Just yesterday I discovered I have been using some Umlauts as well in some of my tags. But I decided to remove tham and only use English words.

Benefits:

- You are able to force yourself to stick with one language, minimising the risk of duplicate tags (e.g. #kirche and #church, which both have the same semantic meaning, but no software on the world would be able to see that without reasonable effort)
- Tags without Umlauts are safer, especially in cross-platform applications. You can be sure that every software will display them correctly, no matter of the characters that a certain font includes or the charset used.
- The base language of whatever file you are editing is completely independent of your tag language.

Tags are not meant to be a perfect fit, they are meant to ensure that you can cross-link several files via tags. Therefore I currently think that only to support A-Z, 0-9, - and _ will be the safest bet. I mean, think about what might happen if I add the diacritics of Slovak and German to the app. There are so many languages that would need to be supported that you can basically support the whole Unicode-charset and run into problems we can't even fathom at this point …

> My nested lists which I made in other markdown apps (ghostwriter, QOwnNotes) didn't seem to display properly (they weren't indented) in Zettlr.

Concerning this issue, I see your point. I have been chasing this bug for months now, but I didn't come up with a good solution until now. I'm still on it.

**Comment by Shandi97** [comment]
I see, it is kind of annoying but nothing insurmountable I can make do without it. Things will be understandable (although awkward and weird) even without the special characters, if the need comes to use Slovak or other such language, I've been using English anyway as a primary language because of the issue of multiple languages and confusion as you mentioned and because I find English easier to write with.

Thank you.

**Comment by maxtar** [comment]
@nathanlesage Sorry, bro. But I couldn't agree with you. In some cases I want to have duplicated tags on different languages. If I have two articles in two different languages for example.
If I write only on my native language why I need to have tags in English?
My opinion would be a cool if I can use any unicode symbols for tags. If you  have trouble with urls I suggest what tags needs to start only  on new line and without spaces in start.
