### ISSUE TITLE
[ENHANCEMENT] Always Insert Title with [[Wiki Link]] Drop-down Option

### ISSUE THREAD

**Issue by privid** [Zettlr/Zettlr#612]
## Description
When you insert a link to a note using the [[wiki-link]] drop-down suggestions, and there's an ID included in the body text but not in the title/file name, it inserts the ID rather than the note title/file name. While I knwo you can add the title in the settings, this clutters my writing, when I could just have a clean [[link]] rather than "[[2321312]] link".

## Proposed Changes
I'd like to have the option to insert ID or title/file name of a note when using suggestions via the wiki-link drop-down menu. 

## Additional Information
<img width="385" alt="image" src="https://user-images.githubusercontent.com/1971633/76664780-cf3a9480-6585-11ea-96dd-de7fc3304c24.png">

**Comment by nathanlesage** [comment]
Do I understand you correctly, that you'd like to add a fourth option "never, link using the filename instead" here in the settings?

![image](https://user-images.githubusercontent.com/17251683/76665321-9ef3f580-6587-11ea-9529-1ff3f0c19b69.png)

**Comment by privid** [comment]
That's basically it. I like to link using titles only, but I still keep an ID in the contents; however, I don't want the presence of an ID to change the linking behaviour to [[ID]].

**Comment by reuseman** [comment]
My request is pretty similar, so I am writing here. 

@nathanlesage Whenever a wikilink is added using the autocompletion and the option to add the filename is turned on, this is the output.
`[[20200405160801]] -title-of-file`

It would be amazing to have the option to achieve this:
`[[20200405160801-title-of-file]]`

In this way, the compatibility with other markdown editor is not broken.

**Comment by nathanlesage** [comment]
Yeah, so it boils down to adding the fourth option and simply drop that filename in there with no further ado.

**Comment by charliebarber** [comment]
If this is possible, it would make for very easy integration with [this automatic backlinking tool](https://github.com/andymatuschak/note-link-janitor). I'd like to have a go at tackling this issue, where do I start?

**Comment by Jos512** [comment]
This is an interesting feature request, thanks for making it!

However, I'm a bit worried about what happens if people change the note's title. Say my note A contains a link to note B. Zettlr nicely inserts the title of note B, rather than its ID.

But then at a later point I improve the title of note B. Now will the link in note A be broken? :thinking:

**Comment by charliebarber** [comment]
I guess you could still think of the links by their ID but display them as the title. Or run a script that automatically changes it. Seems like it could easily get very complicated so I see why the ID approach works well.

**Comment by privid** [comment]
I think it's just a risk you take if you decide to (1) link using only titles rather than IDs, or (2) combine them; they're just much more fragile. But the existing option to link via ID only will remain anyway, if I understand correctly.

**Comment by obedm503** [comment]
Not stale, just waiting.

**Comment by cobblepot1** [comment]
Late follow up question here - other similar software allows for a distinction between the link target and the link display text, either by default or when manually changed. e.g. Obsidian allows an internal link to another note/file with `[[link]]` but also lets you change the display text with a vertical pipe like this: ` [[link|Custom Link Name in Preview]]`. Any chance this solution could be implemented in Zettlr?

**Comment by nathanlesage** [comment]
> but also lets you change the display text with a vertical pipe like this

Nope, not coming. I can't find the issue where I elaborated my reasoning, but more or less it boils down to the fact that even internal wiki-style links are not really wiki-links, but fuzzy searches that have the benefit of opening files additionally; and adding this option would cause confusion and do more harm than good!

**Comment by cobblepot1** [comment]
> Nope, not coming. I can't find the issue where I elaborated my reasoning, but more or less it boils down to the fact that even internal wiki-style links are not really wiki-links, but fuzzy searches that have the benefit of opening files additionally; and adding this option would cause confusion and do more harm than good!

Obsidian has a Discord with 9,000+ members after 4 months even though it's still early beta software.
I have no idea how many active users are in the Zettlr community after 2 years, but I doubt it's anywhere near that many.
Consider that your attitude of "nope, not coming" and "I know what is worthwhile and what is not" is possibly part of the reason why.

Do you want Zettlr to be software that is useful and used by a wide group of people, all of whom have different writing and note-taking goals and styles?

Do you really think that you have the knowledge and experience to know what filenaming and linking conventions confuses vs. helps most people? What does more harm than good? Do you have any idea even how many people use notes with unique identifiers in their filenames vs. those that don't? No, nobody does. 

Let me suggest that you could have very easily responded by saying "My workflow wouldn't benefit from such a change because I personally don't mind looking at long UIDs in links, but I am happy to help answer questions if you want to develop this feature." Many other people are really bothered by long UIDs in links. Other people use links differently than you do. One reason lots of people love Roam is because they can easily integrate the links into [[sentences]] without breaking up the flow and leaving [[sentences readable]]. You may not care, but others do.

Having so-called "links" that are actually fuzzy searches is confusing to many and I suggest calling them what they are in the documentation--fuzzy searches (see https://forum.zettelkasten.de/discussion/1167/links-vs-searches). There are benefits and drawbacks to each method. You like seeing other files in the search results, but other people would rather have them displayed separately in a backlinks panel.

Seriously, as a motivated open-source developer your intuitions about workflow are going to be different than most of the people using your software, so I suggest that you can get maximum impact from your efforts by being more open to and more inviting of different approaches.

**Comment by cobblepot1** [comment]
Sorry for the rant. I just spent about a month trying org-roam and then 2 weeks on Obsidian before returning to Zettlr for the Zotero integration. Those communities are incredibly welcoming and collaborative, so it was very off-putting to come here and be told, "Won't happen, because I decided it's not worth it for me/for anybody."

**Comment by nathanlesage** [comment]
Don't worry, but let me try to explain my behaviour:

I frankly don't care about the size of their communities. Plus, you're here on the issue tracker, NOT in the community. I have realized that the people on both the forum and reddit are extremely welcoming themselves, and help each other out, which I really appreciate.

Zettlr is 100 % Open Source, and I have a normal job (unlike Obsidian or Roam, whose devs are being paid full-time for doing just that). I am coding on Zettlr in my free time. Furthermore, there is not even a team behind Zettlr. Yes, Tobias does a lot of work now and I am honestly super relieved that he's joined the team, but it's still only two people for (at the time of writing) 176 open issues and 17 Pull Requests which I have to manage.

And managing means:

1. Estimate the costs of implementation/merging of each one of those, as opposed to the costs that I will incur having to maintain these additional features.
2. Manage how these will play together, that is: Will one feature impede usefulness for another feature? If so, how can we mitigate?
3. Actually implement almost all of these features
4. Make sure it fits within the broader development goal of the application
5. Try to gauge the expectations of most users.

I think there are lots of things going on behind the scenes which you do not realize (because, well, obviously, they're _behind_ the scenes, so how could you know?). First, most of the things, even if added by someone else through a PR, are things that will then transfer to me with regard to maintaining. So if someone does a super fancy new feature, most of the time I have to fully understand what is happening in order to maintain the feature for the future. Because obviously everything will break at some point, and I cannot hope for the implementor to be around when the feature breaks and do it, because most people cannot afford (or simply do not want to) make a commitment to sticking around. I've had lots and lots of features implemented which I now have to maintain completely on my own.

Then, obviously, there is a huge amount of users which is neither on any community forum etc., so I have to take their expectations into account myself. And the target audience mostly are researchers from the arts and humanities. These people do not expect the most fancy state-of-the-art PKM-stuff, so this has a very low priority. My aim is to give a tool to this community that helps them migrate from Word. And this is a hard job in and for itself.

Here on the issue tracker there are some marginal groups who are active which I do not primarily target with Zettlr:

1. Technically engaging people who know enough to have a GitHub account
2. Science researchers who also are not afraid of Markdown
3. Programmers and coders

So the main target audience is seldomly active here, but I keep in contact with these people via mail, in personal conversations and such. So it does give a false impression of the users of the application when only looking at the GitHub section. Feel free to roam around a little bit, and you will notice some common themes of the specific features these groups demand: Almost all concern syntax highlighting and other tools that are primarily useful for technical stuff. Which is _not_ the main aim of the app. I added a lot of this stuff because it didn't interfere with the rest of the app.

Furthermore, please try to see that many, many, many feature requests are in fact integrated, and this is the first in a long time that I had to deny, so it sounds extremely entitled to generalize from this one instance to "You're not welcoming!" and I find this a little bit disrespectful. Plus, when this issue was raised for the first time a few weeks ago, I was extremely polite, but if you have to close, like, 10 issues because people don't search for the issue in the closed section, then it is more than reasonable to lose temper a little bit. This whole thing is exhausting as hell, and people barking at me because one feature they themselves really like isn't being implemented, is not at all helpful, nor is it considerate. Try to imagine my work first, and if you are then still convinced that I handle things in a non-optimal way, I am certainly open for suggestions, especially if these make my life easier.

**Comment by cobblepot1** [comment]
Hi, I suppose each of us did not have the context for the other's comment.

You are right that I don't know about the things happening behind the scenes of Zettlr development. But also, I have not been following the community closely for the last month, so I had no idea how many requests you approve or deny, so it is not the case that I'm willfully ignoring your frequent request approvals; I just haven't been keeping count.

I understand that you are a volunteer developer without a team, and I don't expect that you will implement every feature, and I don't feel entitled to your time to implement my wish list. I was upset that you rejected my suggestion not because of the rejection but the tone that I read into it, which seemed to say "I won't consider this because it doesn't seem useful and will confuse people." You knew that you have discussed this many times before and offered reasons, but I did not. I would have been fine if you had said, "I have too many pull requests to manage right now, so I can't consider this until I get through the backlog."

I agree that it is very confusing to people that what we call "links" are actually fuzzy searches. The fact that people apparently keep requesting this feature is evidence for this confusion. Can I highlight a suggestion I made earlier? Stop calling them links. Call them saved searches. That's what they are. When there is time or you get more volunteers, fix the documentation to reflect that. Then the feature will not be requested in this way. No one will say, "Can we have the saved search for `20203303` display as `taking notes`?" or if they do, at least they will know what they are asking.

If you insist on continuing to call them links, then you are inviting more people to ask you to make them work like most links do and allow them to change the text displayed. Thanks.

**Comment by nathanlesage** [comment]
> Can I highlight a suggestion I made earlier? Stop calling them links. Call them saved searches. That's what they are.

Yes, that is right.

Communication is sometimes hard, and I did not want to sound in any way overly dismissive, apologies.
