### ISSUE TITLE
[BUG] Attempting to use the Table Editor on non-pipe-tables can result in severe data loss

### ISSUE THREAD

**Issue by AIBN60** [Zettlr/Zettlr#615]
## Description

An existing table is not fully shown (except title row) although it is existing as output to TXT shows. When adding a row by using the plus-sign, the former contents is deleted. This does not happen when the table is created manually by using |A|B| a.s.o. Adding cols and rows will work then; contents is not lost

## Reproducing

The error is not always reproducable; depends on file and does not happen when manually created. 
But when a table is not shown (except title row), then the prevouisly existing table is changed, data is lost. In files with more than one table it could happen to only one table; all others are fine

NB: creating a table using the format button does not work; see issue 614

## Expected behaviour

editing table without data loss

**Screenshots**
![Table_not_shown](https://user-images.githubusercontent.com/62201504/76698960-ac54d100-66a8-11ea-92a5-21e12e23f2b3.png)
![Tabledestroyed](https://user-images.githubusercontent.com/62201504/76698959-abbc3a80-66a8-11ea-8926-81531bf42707.png)

## Platform
 - OS and version:
Unix-Kernel: 4.15.0-88-generic
Ubuntu-Version: Ubuntu 18.04.4 LTS

 - Zettlr Version:
1.6.0

 - Screen Resolution:
1920*1080

**Comment by nathanlesage** [comment]
Uff. This is due to the fact that the table editor only assumes pipe tables, not all the other flavors in which they come for Pandoc (pipe tables are among the easiest to parse, which is why I chose them). I do see the problem, and I am unsure why the Table Editor even attempts to render these tables o.o

Nevertheless, this requires extensive rewriting of the parser …

I'll rename the issue so that it's more clear what is happening!

**Comment by nathanlesage** [comment]
So, did it, it's in the devlop branch and will go out with the next release!
