### ISSUE TITLE
Add support for YAML blocks

### ISSUE THREAD

**Issue by snauth** [Zettlr/Zettlr#62]
Rendering of optional [YAML blocks](https://pandoc.org/MANUAL.html#extension-yaml_metadata_block) in editor window similar to [Typora](https://typora.io/) .

**Comment by nathanlesage** [comment]
This fix should render YAML metadata correctly!

**Comment by snauth** [comment]
Works well, thanks! However, an unintended side-effect is that stuff after a horizontal rule (`---`) is rendered as if it were inside a yaml block. This can be worked around by using other ways of indicating a rule (or using two) but I guess it will confuse people.

**Comment by nathanlesage** [comment]
Well, these YAML-Blocks do have some drawbacks; they have to be used appropriately, and I wanted to stick as close as possible to pandoc's filter. Everything should render fine by leaving an empty line between the closing line and the next line of text, otherwise the styling is confused, because the markdown mode unfortunately also tries to render SETEX-headers, and not only ATX …

**Comment by nathanlesage** [comment]
Okay, I just realised that the matching function of CodeMirror seems to be unable to make use of line-starts inside regular expressions, which means I've had to remove the functionality for the time being and have to think of something else …

**Comment by nathanlesage** [comment]
Short update: the way the modes are implemented in CodeMirror I can't do anything about the YAML metadata blocks for now :(
