### ISSUE TITLE
Math and citations in tables are not rendered properly

### ISSUE THREAD

**Issue by tobiasdiez** [Zettlr/Zettlr#620]
## Description
If you put mathematics or citations in a table, then they are displayed as normal text instead of being rendered properly.
![image](https://user-images.githubusercontent.com/5037600/76946229-030a1700-6904-11ea-99a7-3f9930e55fed.png)

## Reproducing
Have a table with math and citations.
```
| S             | M      | $Gr_S(M)$  | References                 |
|:-------------:|:------:|:----------:|:--------------------------:|
| codimension 2 | volume | symplectic | [@Swift2000 Corollary 3.2] |
```

## Expected behaviour
Have a nice display of math and citations as it is the case if those are put in normal text.

**Screenshots**

## Platform
 - OS and version: Win 10
 - Zettlr Version: 1.6
 - Screen Resolution:

## Additional information
Maybe related: https://github.com/Zettlr/Zettlr/issues/601

**Comment by nathanlesage** [comment]
Not going to impelement this. At least not this year. Maybe never.

That is not because I don't _want_ it to display properly — after all it would indeed be great —, but because it will take an enormous amount of work to get this working. This is because the TableEditor makes use of `contenteditables`, and while it's possible to do some HTML, it's super difficult to implement in a way that does not destroy any data. So weighing my limited time with this simple display improvement (as it will render properly when exported) and other issues, I'm afraid this is not going to happen at this point.
