### ISSUE TITLE
Cannot create new files or dicrectories

### ISSUE THREAD

**Issue by jk31** [Zettlr/Zettlr#626]
## Description
I just discovered this project, installed the program for Win10 and started it. The program does not react when I try to create new files or new directories. Sometimes a window flashes for a short moment but it disappears instantly. I also restarted the computer and tried to run it as admin. It doesn't help.

## Reproducing
See description

## Expected behaviour
See description

**Screenshots**

## Platform
 - OS and version: Win10
 - Zettlr Version: lates
 - Screen Resolution:

**Comment by nathanlesage** [comment]
Zettlr is explicitly made so that you have one (or more) directories "always open" as sort of workspaces. So to create files and directories, it wants you to `Open…` a directory before beginning to use it normally. All operating systems should give you the option to create new directories when choosing to `Open…`. I know we need to make this more explicit at the first start, but haven't come to it as of now!

Please comment if this does not solve your problem so that we can investigate!
