### ISSUE TITLE
Zettlr setting my MBP on fire

### ISSUE THREAD

**Issue by danielianrock** [Zettlr/Zettlr#629]
## Description
Zettlr seems to use a lot of energy. I'm not sure why!

## Proposed Changes
Modify code to be less energy intensive (not sure what's causing it). 

## Caveats
It depends on the source of the problem. I'm sorry I don't know why.

**Comment by PhilHem** [comment]
Without knowing what's causing this problem, there is no way to know what one should change about the code to make it more efficient.
You can use the Activity Monitor of OS X to monitor is Zettlr is actually the culprit with your energy drain. For my Late 2013 MacBook Pro, the energy drain is below 5%.

**Comment by danielianrock** [comment]
Yeah that's how I figured out it was Zettlr. I was surprised because it doesn't seem like the type of thing that would generate those effects.

**Comment by danielianrock** [comment]
For example:
[image: Screen Shot 2020-03-24 at 12.31.49 PM.png]

**Comment by nathanlesage** [comment]
> Modify code to be less energy intensive (not sure what's causing it).

It's not the code, it's Electron. Simply download [any other app](https://www.electronjs.org/apps) and see what happens. Most of them do that. There's not much I can do, it's — presumably — a bug in Chromium that begins to drain rendering energy for no apparent reason. If you find out more, please feel free to get in touch!

**Comment by danielianrock** [comment]
ah thanks!

**Comment by nathanlesage** [comment]
I seriously hope Electron gets this fixed soon, because it's happening with me as well; I always notice when the fans in my MBP go crazy after I used Zettlr for some time :D Normally, restarting the app solves it (but I've had worse days!)

**Comment by LacikaG** [comment]
Zettlr is draining the battery massively. When I open the app the estimated battery drops from 7 to 2 hours. Then I close Zettlr and it goes back to 7 hours. I have tried to restart but the same happens all the time. I can feel how the laptop gets heat at the battery area.
Evidently there is a problem, I am not sure what since I am not an IT expert.  

Here are the screenshots of opening the app and then closing:

![Screenshot 2020-06-20 at 19 59 25](https://user-images.githubusercontent.com/66075400/85208409-97837b80-b330-11ea-85ef-458f5548d3a0.png)


![Screenshot 2020-06-20 at 19 54 58](https://user-images.githubusercontent.com/66075400/85208352-f09edf80-b32f-11ea-8575-70a0f8a42376.png)


![Screenshot 2020-06-20 at 19 52 44](https://user-images.githubusercontent.com/66075400/85208326-af0e3480-b32f-11ea-9faf-65e0ffd25167.png)

**Comment by nathanlesage** [comment]
This happens with other Electron apps as well, but there is, indeed, room for massive improvements with respect to efficiency. Unfortunately, this can't be done with one issue but requires constant effort. But don't worry, this is precisely what I want to do, and what I always keep in mind while developing!

**Comment by LacikaG** [comment]
Hendrik,

Thank you for the quick answer. Zettlr is a great software and I use it for my academic writings. I hope the issue will be resolved quickly because I hate WORD. I do not mind if there is a licence fee but resolve the draining issue.

Laszlo

**Comment by nathanlesage** [comment]
Don't worry! And if you notice that specific actions seem to drain the battery faster, feel free to report this (what action did you do that seemed to drain the battery faster?), because the more specific the issues are, the easier it's for us to address them! :)

**Comment by LacikaG** [comment]
Hendrik,

I have given up on Zettlr. When I start Zettlr the battery consumption jumps high and reduces the available time for at least 50%. 

I am sorry because the Zettlr features are unique and it is the software I would like to use for writing my new book. It is easy to use and beautiful to look at. I adore the project export features.

Please let me know when the battery issue resolves.

Laszlo

**Comment by nathanlesage** [comment]
@LacikaG We're constantly on the watch for performance bottlenecks, but we can't guarantee speed. In case you find some particularly heavy actions that lighten up the energy consumption, make sure to report this, so that we have something specific to investigate. This helps us because we don't have to run all those time-consuming performance-checks on the whole codebase. Any information can help!

**Comment by LacikaG** [comment]
Hendrik,

I just couldn’t let Zettlr go, I thought my battery draining issues must have a solution. So, I have reinstalled Zettlr, set it up what for academic writing and believe it or not I have finished my master thesis in Zettlr, it seems the battery draining issue was solved in the meantime. Or, I changed something during the reinstall… I don’t know. But it works now, and thank you.

Happy New Year and please continue with the great work… the world needs Zettlr.

L.

**Comment by nathanlesage** [comment]
> it seems the battery draining issue was solved in the meantime

Yes, indeed it has been solved in the meantime (for 1.8.1 I think)! Glad to hear that! I wish I've had Zettlr back in my M.A. thesis writing days …
