### ISSUE TITLE
[ENHANCEMENT] Track Changes

### ISSUE THREAD

**Issue by danielianrock** [Zettlr/Zettlr#630]
## Description
Track changes functionality would be great for collaboration. This would include both changes as they relate to the text as well as commenting w/labels for the user who did comments.

## Proposed Changes
Create a sidebar panel view that collects changes and comments to markdown documents as well as an option to toggle on/off. The MS word and overleaf versions of this are good examples. Additionally include the option to delete all comments and accept all changes.

The UI component would probably be the harder part. Diff'ing the file with earlier version to pick up any changes seems straightforward.

## Caveats
I wouldn't imagine this would change other features in theory, but in practice... not sure.

**Comment by nathanlesage** [comment]
Zettlr itself will not implement any versioning control. But it will detect `git` repositories and let you handle them in some way as VSCode lets you. But before that can happen, we need to implement the FSAL, which is still a long way from finished. Git integration is already on my bucket list and will be implemented with the new FSAL, but it may take some months due to the multiplicity of problems with Corona … but it will come.
