### ISSUE TITLE
[ENHANCEMENT]inline MathJax rendering in tables

### ISSUE THREAD

**Issue by PhilHem** [Zettlr/Zettlr#631]
## Description
Enable inline MathJax rendering within tables.

The following is an example how it could look like. In other Markdown editors that allow math, this syntax sometimes works:

```
| $A$       | $w$ | $f$ |
|:---------:|-----|-----|
| $\lnot A$ | $f$ | $w$ |
```

I am pretty sure that the problem lies in the HTML table rendering, which does not know how to interpret die dollar signs.

## Caveats
I don't think this will change anything about how tables or anything else works. 

## Additional

I understand, Zettlr was originally conceived from the viewpoint of social sciences and the like, but it increasingly becomes more interesting for people in computer- and natural sciences. Attention from these folks could possibly further the project more, as they might be interested in participating in the development.

**Comment by nathanlesage** [comment]
> I don't think this will change anything about how tables or anything else works.

Actually, it will change a lot, because the TableEditor makes use of contenteditable fields, which are super fishy to handle. I've closed multiple of these issues in the past and will do with this one as well, but instead I will be opening a new "meta-issue" combining these efforts. Have a look here: #632
