### ISSUE TITLE
Unwaders.A!ml potentially unwanted software detected in Zettlr 1.6 for Windows

### ISSUE THREAD

**Issue by Jaifroid** [Zettlr/Zettlr#649]
I was very surprised to see Windows Defender suddenly pop up with the message below. This is on Windows 10 Pro 64bit, fully up-to-date. I downloaded Zettlr from GitHub releases. I'm sure it's a false positive, but...

![image](https://user-images.githubusercontent.com/4304337/78686553-19940480-78eb-11ea-8ac1-3d5401281eda.png)

**Comment by chanon** [comment]
Can confirm. My Windows reported the same.

**Comment by Jaifroid** [comment]
@nathanlesage Please check your build chain. There's a possibility of an infection in one of the Windows build packages you use.

**Comment by nathanlesage** [comment]
Hey,

yesterday morning after reports mounted, I ran the Zettlr-1.6.0.exe through both Kaspersky and VirusTotal, and both came out negative, except one of the tested algorithms for VirusTotal, so maybe that's the source. It's definitely a false positive, because also the checksums check out correctly.

Concerning my build chain: This is highly unlikely, because  if so I would already have gotten a security alert from GitHub, so either it's a zero-day, or there is no infection.

My current theory is the following: Some idiot built a virus on basis of Electron, and as Electron makes out most of the installer binary, every Electron app looks quite similar from the standpoint of hashing algorithms. This means that once the malware was reported to the virus checking community, other Electron apps may have been flagged as false positives as well. However, I was as of now unable to verify this assumption. Plus, I'm not a security expert.

@Jaifroid The whole build chain is hosted by GitHub, because we're using an GitHub actions CI workflow. I cannot think of any place where any malware might've gotten into the system without GitHub noticing & taking action, but [please feel free to double-check the file](https://github.com/Zettlr/Zettlr/blob/develop/.github/workflows/build.yml), maybe I'm just overlooking something!

Last but not least: I'm not a security expert, neither am I completely in touch with the Windows ecosystem right now, as I stopped using Windows machines about 5 years ago, so I'm not sure what the right course of action is right now … I am very glad for any help on that issue!

Cheerio (and Happy solitary Easter to you!)

**Comment by Jaifroid** [comment]
Thanks @nathanlesage . I think it most likely is a false positive because: a) it is only the installation executable that triggers the virus match, the installed application does not trigger it; and b) I ran a full malwarebytes scan on my system and apart from the installation executable that has already been quarantined, there is no trace of the Trojan on my system.

I think writing to Trapmine is a good idea. It would be good to get the virus signature revised.

**Comment by nathanlesage** [comment]
I just got very good news! Trapmine quickly reviewed the installer, concluded that it's indeed a false positive and will be shipping an updated model which whitelists the installer! :)

Thank you all for reporting & in case something like this happens again, just let me know!
