### ISSUE TITLE
[FEATURE] customizable prefix character to define tags

### ISSUE THREAD

**Issue by taubmann** [Zettlr/Zettlr#650]
## Description

Some editors and tools use a different syntax for tags, mostly the "+" (eg. +todo instead of #todo before the tag itself. It would be great if it could definable in the settings witch character to use as the prefix for tags.

**Comment by nathanlesage** [comment]
From a purely technical perspective, this should not be that much of a problem.

But from a usability perspective, I would like to question the usefulness of this. Because the hashtag symbol (`#`) is something unambiguously understood to indicate a tag. Plus, it's really easy to spot within files. Furthermore, even while searching, you immediately know what a tag is without syntax highlighting. Plus-signs seem to hinder that, because they're much less obvious and easy to overlook.

Besides, hashtag-tags will be detected by far more tools out there, as they are ubiquitous.

**Comment by taubmann** [comment]
sorry for the late Answer:
You are right about the benefits of the hashtag symbol and this is probably a minor enhancement for users coming from tools supporting (& following) the todo.txt rules for keywords like [imdone](https://imdone.io/).
