### ISSUE TITLE
Would it be possible to make linked notes "viewable" in a single page and show the linked pages? 

### ISSUE THREAD

**Issue by johnson0915** [Zettlr/Zettlr#659]
Hi there! 
Thanks for developing this great app! I've been struggling in the last two days two find an app help me implement the Zettelkasten method, and I think Zettlr is great for this purpose! 
## Description:
However, it lacks the feature of enabling users to see all the notes linked to an id. 

## Example Workflow
For example, this is what Roam Research (another good alternative, but being cloud-based makes me very reluctant to use it!) does: 
![image](https://user-images.githubusercontent.com/26791011/79072776-29448c00-7ce3-11ea-8a93-c80f2ffdf525.png)
Say that this is my notebook, and I've 
1. paper, which is something that I need to write based on the notes that I've taken during my lectures
2. note1, note2, note3, and so on, which are the notes that I've taken 

So I need to write a paper by making references to note1, note2, and note3. 
How does Roam achieve this that Zettlr cannot currently? 

Step 1: 
![image](https://user-images.githubusercontent.com/26791011/79072811-56913a00-7ce3-11ea-8fcb-878f83287950.png)
By typing [[page name]]
Step 2: 
By clicking [[page name]], which is an internal link that's also the name of another page, one will be redirected to the [[page name]]. 
Step 3: 
![image](https://user-images.githubusercontent.com/26791011/79072842-922c0400-7ce3-11ea-9fca-09bbf38df3d6.png)
Here's what it looks like in [[page name]], which in this case is "paper." With Roam, one can easily view all the notes that've been linked to a common page. And this is really fantastic if we think about it: instead of going through pages after pages in order to find the linked text (which is what we have to do in Zettlr if we want to see all the notes linked), Roam gives its users the chance to see all the notes that've been linked to that page!

This becomes even more powerful when we have literally hundreds and thousands of notes to read in order to produce something meaningful (I think this is quite common in academic settings). 

!-- Now, are there any caveats, such as other features that would be affected? -->
Wow...I wish I had more expertise to provide more technical experience...But sorry...

## Additional Information
1.
Also powerful is the feature of enabling users to easily go back to linked pages. Here, for example, if I click "note 1," I'll be redirected to the page [note 1] 

Before the click:![image](https://user-images.githubusercontent.com/26791011/79072981-3d3cbd80-7ce4-11ea-8766-f0454690a7b7.png)

After the click: ![image](https://user-images.githubusercontent.com/26791011/79073012-652c2100-7ce4-11ea-841c-f6f31a411da8.png)

2.
Besides, it would be very nice if this feature let users to see only the notes linked, even if they came from the same page. Again, here is what Roam does: 

Please note that in "note 1" we have three points:
![image](https://user-images.githubusercontent.com/26791011/79073207-8e997c80-7ce5-11ea-8f14-23c126cc292d.png)
Now, say that I want to link only point 1 and point3 to "paper," and not "point2" since I think it's irrelevant for the paper that I need to write. 
This is what it looks like after I've linked point1 and point3 to "paper:"
![image](https://user-images.githubusercontent.com/26791011/79073259-d3bdae80-7ce5-11ea-84be-80fbb7cba44a.png)
Only point1 and point3 have the blue link 

And as I open "paper," wow, look at what we have:
![image](https://user-images.githubusercontent.com/26791011/79073278-ee902300-7ce5-11ea-85aa-98bdaf272795.png)
I can see ONLY point1 and point2! 

It would be very nice if Zettlr had this as well.

3. 
Finally, with Roam one can link as many notes as they'd like to a page:
![image](https://user-images.githubusercontent.com/26791011/79073339-47f85200-7ce6-11ea-8c88-d39064ac754b.png)
Here in note3 I've created a new id/link that links to "paper"

![image](https://user-images.githubusercontent.com/26791011/79073350-59415e80-7ce6-11ea-8ccf-9c9c675a8980.png)
Here's what I can see when I open "paper." All the notes, let them be from note1 or note3, are viewable. 

I really wish all the features I've mentioned could be accomplished in Zettlr as well! This would make Zettlr super handy to use and very appealing for people like me who tend to create a lot of pages and want to implement the Zettelkasten method! 

Thanks for reading and time!
Looking forward to hearing from you!
Stay safe!!

**Comment by nathanlesage** [comment]
… are you basically asking to re-write the core of Roam? :D 

Well, Roam has a different approach at notes which I — personally — don't like that much. Everything is basically bullet points, and it's really unnerving to me. It is indeed very good for notes and for that back and forth, but I have the fear that this is basically an inch *too fuzzy* for me.

Zettlr is focused around files as in text-files, not so much in notes. It attempts to take this rather old concept and wrap it around a little bit with some sugar to enable more and more file-system operations. Reproducing the logic of Roam in Zettlr would feel like "stealing" for me, especially given the support I receive from Conor.

Nevertheless, Zettlr _does_ have some lack of good functionality for this approach, so it needs to do better. But I got my own idea on how to do so. I can't spoil too much because I'm still in the process of rewriting half the code base, but afterwards I'll get to something really fancy (at least if it works out as intended)!

Concerning what you want: I would like to point you over to #354, as this is basically what you're describing — only more "file-centered", if you want so!
