### ISSUE TITLE
[Feature] Add a context menu entry for opening links

### ISSUE THREAD

**Issue by SamuelBlickle** [Zettlr/Zettlr#66]
I just wanted use a link in one of my files but unfortunately it doesn't open/follow the link on my Linux machine (Kubuntu 18.04) when I `ALT + Click` it. Neither URL links nor internal links (both via name or ID).  

I have tested the same link with a Windows machine and everything works as expected.

While i struggled with my links, I also had an idea for a small accessibility improvement: It would be very nice to have an option to follow links in the right-click context menu.

**Comment by SamuelBlickle** [comment]
I've just noticed i have to use ALT + ALT-GR + Click... okay whatever^^

anyhow, i think the context menu addition would be nice.

**Comment by nathanlesage** [comment]
`ALT+ALT-GR+Click`…? Holy shit, that's long. Internally, the app only listens to a pressed `altKey`, so I am not quite sure where this behaviour originates. What does happen when you only hold down the `ALT`-key? Is the link removed and the cursor placed where you clicked or does simply nothing happen? If nothing happens, I'd be interested whether or not there's an error output in the development console. Would you mind checking that?

The Context-Menu entry is a good idea. I just thought of adding more specialised context menu entries throughout the app, because currently it's rather coarse (also for images, etc.)

**Comment by SamuelBlickle** [comment]
There is no error and it does not change anything when `ALT` is pressed on my machine.

And btw no, the KDE shorcuts don't play into it, I've tested it (if someone else expeciences this).

**Comment by nathanlesage** [comment]
That should definitely not happen. @escapedsalmon Do you have time to look over this bug, and whether or not this occurs generally on Linux systems?

It sounds to me as if there's some error in `electron.shell.openExternal(url)` on Linux systems.

**Comment by nathanlesage** [comment]
@SamuelBlickle Could you try the current Beta if this happens there as well? If so, I'll have to look into it …

**Comment by escapedsalmon** [comment]
So.. there we go. I currently only tested the develop branch. @SamuelBlickle are you able to have a quick look into the develop branch from git on your system?
Otherwise I would kindly ask you to provide some more information on which Desktop/System/whatever you are currently using so that I further look into it.

Anyway, what I wanted to say in the first place: I can't verify the described issue here on my system (Fedora 29, current Gnome 3 on Wayland, Zettlr-Develop). So every link opens as expected here using the `Alt + Click.Left` combination.

**Comment by SamuelBlickle** [comment]
@escapedsalmon there isn't any change with the issue in the dev branch, I'm sorry.

The system is a Kubuntu 18.04 with a 4.15.0-42-generic x86_64 kernel. KDE Plasma 5.12.7
I really _do_ think this is some strange KDE b***shittery, as it works fine for me with different dristros and desktops.

**Comment by nathanlesage** [comment]
So we've started with links not working and have identified the issue as "we need an alternative key for clicking links"?

I'm currently thinking of offering `Shift` … would that be suitable?

**Comment by SamuelBlickle** [comment]
`Shift` sounds great but I'd still highly +1 the context menu option.

**Comment by nathanlesage** [comment]
Nobody said the context menu option wouldn't come :)
