### ISSUE TITLE
Links to local notes do not work if the target file name contains an "é" (Windows)

### ISSUE THREAD

**Issue by Vetii** [Zettlr/Zettlr#668]
## Description

If I create links to notes in Zettlr, following the link fails if the file name contains "é".

## Reproducing

1. Create two notes, one called "note" and one called "é".
2. Create a link in "note" to "é": `[link](é.md)`
3. Try to use `Ctrl+click` on the link

Zettlr displays "could not open file://C:/.../é.md", even though the path seems right.
 

## Expected behaviour

Zettlr should create a link to the file (in fact, creating the link with `[[é]]` works)

**Screenshots**

None.

## Platform
 - OS and version: Windows 10 (Doing this on Linux works)
 - Zettlr Version: 1.6.0
 - Screen Resolution: Irrelevant

## Additional information

Since `[[é]]` works, what path does this method use?

**Comment by pizzakinggod** [comment]
I think this regex is the culprit. Though I think people didn't notice this bug because many use internal linking `[[]]` with generated ID for linking files.

https://github.com/Zettlr/Zettlr/blob/6f01e9fa8d1aa237bf4b25021724f8b2118dffa0/source/common/util/make-valid-uri.js#L20

**Comment by nathanlesage** [comment]
@pizzakinggod From the looks of it, you might be right! I don't have the capacity to look into that right now, but if we make changes to that RegEx, we might want to look at the sanitize-filename-package, which does a decent job in detecting malicious characters. Plus, I just see that the `tex`-file extension is missing from that RegEx either way …

**Comment by pizzakinggod** [comment]
Using unicode expression per https://mathiasbynens.be/notes/javascript-unicode#regex

```javascript
const mdFileRE = /.+\.(?:md|markdown|txt|tex)$/iu
mdFileRE.test('테스트.md') // true
mdFileRE.test('é.md') // true
```
However, it still shows "could not open file://..  " So there must be something else... I will look into it..

**Comment by pizzakinggod** [comment]
https://github.com/Zettlr/Zettlr/blob/6f01e9fa8d1aa237bf4b25021724f8b2118dffa0/source/renderer/util/open-markdown-link.js#L26-L32

> https://github.com/electron/electron/issues/6302
> 
> If you want to open file you should usually use `openItem`, which works with Unicode characters.


There was an opened issue in electron's repo, which says it fixed openExternal function with unicode, however, does not look like it since it does not work🤔. 

However, `shell.openItem(validURI)` successfully opens the markdown file(with unicode characters) with an external editor.

So changing regex as above, and separating URI opening function, that is, use `openItem` for URI with file and `openExternal` for the rest (as it is now) will fix the issue I think.

**Comment by pizzakinggod** [comment]
https://github.com/Zettlr/Zettlr/blob/6f01e9fa8d1aa237bf4b25021724f8b2118dffa0/source/renderer/util/open-markdown-link.js#L26-L32

> https://github.com/electron/electron/issues/6302
> 
> If you want to open file you should usually use `openItem`, which works with Unicode characters.


There was an opened issue in electron's repo, which says it fixed openExternal function with unicode, however, does not look like it since it does not work🤔. 

However, `shell.openItem(validURI)` successfully opens the markdown file(with unicode characters) with an external editor.

So changing regex as above, and separating URI opening function, that is, use `openItem` for URI with file and `openExternal` for the rest (as it is now) will fix the issue I think.

**Comment by nathanlesage** [comment]
> However, shell.openItem(validURI) successfully opens the markdown file(with unicode characters) with an external editor.

I'm extremely against monkeypatching something on our side simply because Electron doesn't do its job … which is to have openExternal to actually open these files, if I understand the discussion correctly, right?

**Comment by nathanlesage** [comment]
As we've migrated to `openPath`, and furthermore amended the regex to include unicode characters as well, I'll consider this issue fixed, please comment if not (relative to a new beta I'll be releasing soon)
