### ISSUE TITLE
[ENHANCEMENT] Jump to existing note when creating note

### ISSUE THREAD

**Issue by PhilHem** [Zettlr/Zettlr#679]
## Description
Jump to existing note when note creation fails due to duplication.
Transfer the note creation error message to the system notifications of Zettlr with something like: "Note already exists. Here you go." 

## Additional Information
When I read things, I will look up wether I already have a note on something. It would be good time saver if I can just hit CMD+n and enter a title, instead of looking up wether I already have note with that name, or attempt to create a new note, get the failure message, then go through the search. 

What do you think? 

Also: My initial text for this was a lot longer, and I edited it strongly. I hope you don't mistake my short entry as unenthusiasm for it. :)

**Comment by nathanlesage** [comment]
I see where you are getting to, albeit I'm wary, because a lot of changes in the last few weeks have pushed the definition of "file" more into the way of "note", which is something where I don't want to completely go. However, writing the title in the global search bar is likely what you want, because it autocompletes your file names and opens them if one file matches its filename!
