### ISSUE TITLE
Bug when correcting a word with a "l'"

### ISSUE THREAD

**Issue by wedza** [Zettlr/Zettlr#69]
## Description
When correcting a word with a "d'" or "l'" , Zettlr adds another "l'" to the word. I thik it's because the corrector catches the 
This is particulary annoying when writing in French, because there are a lot of theses.

## Reproducing
Try to correct the word "l'apelle" for example

## Expected behaviour
Correct the word and deleting the previous characters involved in the correct suggestion.

**Screenshots**
https://i.imgur.com/PyrVUnM.gifv

## Platform
 - OS: Windows 10
 - OS Version 1809
 - Zettlr Version 0.20.0

Thanks

**Comment by nathanlesage** [comment]
Yes, I see where this comes from. When you correct a word, Zettlr internally selects the whole word prior to the replacement, and currently it does not watch out for apostrophes within words, because they can also occur as 'quotes', in which a replacement of them would not be wanted.

I'll see to correcting it within the next beta build!

**Comment by nathanlesage** [comment]
Attached patch should fix this issue!
