### ISSUE TITLE
Copy as HTML does nothing [1.6.0]

### ISSUE THREAD

**Issue by filipgoc** [Zettlr/Zettlr#690]
## Description
Copy as HTML copies actually as markdown it seems. 

## Reproducing
- Select text
- Menu > Edit > Copy as HTML
- Paste in a plaintext editor or examine your clipboard
- It's markdown

## Expected behaviour
The clipboard should be loaded with HTML

## Platform
 - OS and version: macOS High Sierra Version 10.13.6
 - Zettlr Version: 1.6.0
 - Screen Resolution: 2880 x 1800

**Comment by nathanlesage** [comment]
> Paste in a plaintext editor

What do you expect? If it's a good editor, it'll pull the plain text from the clipboard :D

But clipboards after all can be confusing, because there're four of them. Basically, most editors (both code editors and word processors) will treat it as such:

1. "Copy with style" will fill up the HTML and RTF portion of the clipboard with HTML- or RTF-rendered stuff, while the plain text clipboard will be filled with a plain text representation of the same stuff for editors that do not support markup.
2. "Paste" will then in most instances work as such: If the editor understands HTML or RTF formats, take that portion of the clipboard and insert it as needed. But if it doesn't, take the plain text portion and paste that instead.

So what you're actually aiming for is HTML-markup in your _plain text clipboard_ so that you can then basically do a "paste without style" to use the word processing term here, and this can be achieved by exporting! Remember, Zettlr is more leaning towards Word processors, and less towards code editors, hence "Copy as HTML" refers not to "Convert to HTML and let me paste this" but rather "Copy this in a form Word or other processors will understand and be able to make sense of".
