### ISSUE TITLE
Hash # render as h1 in code mode

### ISSUE THREAD

**Issue by danieltomasz** [Zettlr/Zettlr#691]
## Description

Hash # render as h1 in code mode

## Reproducing
set specific rendering of titles to h1/h2...
copy fragment
```
# Ignore all compiled CSS files
/*

# Also add the .gitignore to the repository
!.gitignore
```

**Screenshots**

<img width="637" alt="Screenshot 2020-04-21 at 20 48 22" src="https://user-images.githubusercontent.com/7980381/79902298-893ce000-8411-11ea-984d-f90b9c1900b5.png">

## Platform
 - OS and version: Latest Catalina
 - Zettlr Version:  1.6
 - Screen Resolution:

**Comment by nathanlesage** [comment]
Just tried this on the FSAL-refactor branch (that is, what will become the 1.7 release) and couldn't reproduce, so apparently I made a mistake but then fixed it! In case during the beta releases you notice this once again, please just comment here so that I can re-open this issue :)

(Wouldn't be the first time I accidentally made a bug, then fixed it and suddenly re-implemented it)
