### ISSUE TITLE
[FEATURE] SpellCheck Grammalecte and Antidote

### ISSUE THREAD

**Issue by qwertygc** [Zettlr/Zettlr#696]
Hello everybody and thinks you for Zettlr, I love this program.

## Description
In a lot of word processors (MSOffice Word and LibreOffice), we have the possibility to have advanced grammar checkers. Personally, I use [Grammalecte](https://grammalecte.net/) and [Antidote](https://www.antidote.info/fr). Grammalecte works for French and Antidote for French and English.

## Example Workflow
We have different possibilities :
- right-click and in the contextual menu we have options for correct text : select all text and open in Antidote/Grammalecte
- We have a button on the nav bar to select all text and open with Antidote Grammalecte

## Caveats
Antidote (and Grammalecte) Need to be installed on the computer.
## Additional Information
- [Antidote API documentation](https://www.antidote.info/en/antidote-10/documentation/developer-tools)
- I know that Grammalecte have a CLI Mode...
- I have [tried to implant](https://gist.github.com/qwertygc/78053a067bd28da94c2eb757c962250d) on a webpage Grammalecte and Antidote, it's easy in JS version. I don't know Electron, I don't know if it's also easy to implant.

**Comment by nathanlesage** [comment]
Are these programs Open Source? This would be a fundamental precondition in order for Zettlr to implement it!

**Comment by qwertygc** [comment]
Grammelecte yes, but antidote no (it's the only not open source software on my computer)

**Comment by nathanlesage** [comment]
Hmhm, is Grammelecte under development? Open Source does seem to indicate that more languages would be possible, which is a good sign!

Additionally: Are there any potential alternatives? Even `node.js`-only modules (without a GUI) would be perfect! If you could do some research, this would be awesome!

**Comment by qwertygc** [comment]
Yes, Grammelecte is under development (and it is active). [NodeJS](http://code.grammalecte.net:8080/timeline?r=nodejs) version seems to be.

**Comment by jgsw** [comment]
LanguageTool might be a better Open Source Grammar checker to target -- it's available for more than 20 languages: see https://languagetool.org/. It's Java, but can run as a server on your computer, with communication with it via http http://wiki.languagetool.org/http-server. There have been some attempts to provide a JS API -- but they look unfinished: see e.g. https://www.npmjs.com/package/languagetool-api

**Comment by nathanlesage** [comment]
> It's Java

\*shrugs\*

**Comment by jdittrich** [comment]
I like _language tool_, but as it is Java-based, [write good](https://github.com/btford/write-good) (en) and [schreib gut](https://github.com/TimKam/schreib-gut) (de) might be at least OK alternatives, since they are Javascript based and seem to be relatively easy to extend. 

@nathanlesage maybe change the title of this issue to "integrate grammar and stylechecker"  or open another issue with that title and forward from this one?

**Comment by nathanlesage** [comment]
@jdittrich hmm, let's keep this issue right now. Because during the last week I've more and more been thinking about integrating a Unified.js pipeline for Markdown linting, which we should be able to easily extend with features for grammar checking, spellchecking, etc. — the ecosystem already offers a lot of stuff out of the box, so maybe this is a better alternative as it would allow us to keep dependencies minimal (only 1 pre-processor pipeline for a lot of stuff) and also modular

**Comment by l4nn1312** [comment]
+1 for language tool, it is java-based but it provides wonderful suggestions. Having LanguageTool support would enable me to switch from Ulysses to Zettler as my primary writing app.

**Comment by nathanlesage** [comment]
Aaand moved up the ladder

**Comment by beardhatcode** [comment]
LanguageTool has a http API that provides feedback on text, there is an open source browser extension that calls that API with JavaScript. If someone could give some pointer on where I could inject such code, I will try to look into this.
