### ISSUE TITLE
Bug: Editor keeps on sending message saying current file has been modified remotely

### ISSUE THREAD

**Issue by leetang888** [Zettlr/Zettlr#71]
I am using Google Drive to store the files on my writing projects. I believe Google drive refreshes the files every few seconds, I received repeated confirmation messages as below:

"The current file has been modified remotely. Replace in Editor?"

This is very annoying because it interrupts my writing.

![error](https://user-images.githubusercontent.com/45865262/49981622-b9739500-ff26-11e8-8740-9057a1a62866.gif)

Lee Tang

**Comment by nathanlesage** [comment]
Huh, that looks annoying. I'll be looking into the GDrive synchronisation (although I can't think of a reason why Google would do that)!

**Comment by Jaifroid** [comment]
@leetang888 Although I use OneDrive for backing up my Zettlr project, rather than GDrive, my setup is that I have created a folder called Repos in my OneDrive root directory, and inside that folder I create a symbolic link (actually, a junction) to the actual folder elsewhere on my computer that contains the Zettlr project. With OneDrive, at least, this has the effect that files are backed up only when I log in to the computer, or after a period of sleep, or if I manually pause and restart syncing on the OneDrive client. (Technically, it's when the sync client does a full folder scan to check for changes it might have missed when offline.) This might not suit everyone, but I find it's perfect for me. Coupled with the File History feature, I can still retrieve versions since the last OneDrive backup, but I also know that not every little mistake I make when editing a document will overwrite the stable version in the cloud. Of course, the GDrive client might not work this way.

**Comment by leetang888** [comment]
It seems the problem goes away if I use Dropbox instead of GDrive.

**Comment by nathanlesage** [comment]
@Jaifroid Holy … this system is complex! =D

And @leetang888: that means that the modification date is actually overwritten by GDrive on sync, which is definitely not supposed to happen. Normally, when something syncs, Zettlr double-checks that also the modification date has changed, otherweise it will ignore the respective event.

As sometimes hundreds of files might be changed remotely (which still crashes the app, though…) I can't implement a reading-md5-hashing-closing procedure to make sure that even the contents haven't changed, which renders it difficult to circumvent this GDrive bug :/

I would suppose to drop a mail to Google support, because, as I said: This shouldn't happen!
