### ISSUE TITLE
Update dependencies using dependabot

### ISSUE THREAD

**Issue by tobiasdiez** [Zettlr/Zettlr#714]
I noticed there are a few outdated dependencies. I would propose to use dependabot, which provides automatic updates as pull requests. See https://dependabot.com/javascript/

**Comment by nathanlesage** [comment]
Well, the dependencies should not be outdated since I updated all of them two days ago :D 

I was going to say that dependabot, while a nice idea, is difficult because I tend to look at the changelogs, not so much to see that nothing breaks, but more because the changelogs sometimes reveal better functionality for stuff, and announce breaking changes early, so I always like to read through all of them. However, I found this gem:

> Dependabot PRs include release notes, changelogs, commit links and vulnerability details whenever available.

Which means, sounds good! I'll certainly have a look to see how I can configure this thingy.

**Comment by tobiasdiez** [comment]
The PRs generated by dependabot are quite nice and contain a lot of helpful information, see for example https://github.com/JabRef/jabref/pull/6363.
You can also configure it so that the PRs are automatically merged if the tests are green. 

Configuration can be done either from their admin panel, or via a config file. For the latter see e.g.
https://github.com/JabRef/jabref/blob/master/.dependabot/config.yml
(where we set the update cycle to once a week in order to reduce noise).

**Comment by nathanlesage** [comment]
Thanks for the links, I was about to look something like that up! Thanks!

**Comment by tobiasdiez** [comment]
Should work, as you can have multiple `update_configs`. e.g. https://github.com/dependabot/demo/blob/master/.dependabot/config.yml
see also https://dependabot.com/docs/config-file/

By the way, what's the reason to use the two-package structure? According to the discussion in https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/1827 this seems to be no longer needed now.

**Comment by nathanlesage** [comment]
> this seems to be no longer needed now.

Precisely because of that: Legacy reasons! :D There's so much I need to do that I tend to keep to things that still work fine, even if they are no longer needed … it keeps the mental overhead small. But it's good to know that the two-package-structure is in fact not needed anymore, so that I can remove that thingy soon.

**Comment by tobiasdiez** [comment]
Dependabot is now integrated into Github. You can enable it under https://github.com/Zettlr/Zettlr/settings/security_analysis - Settigs > Security & Analysis (I don't have the rights to do this) and a configuration file needs to be added (similar to https://github.com/JabRef/cloudref/blob/master/.github/dependabot.yml).

**Comment by tobiasdiez** [comment]
@nathanlesage is this something that you would like to have?

**Comment by nathanlesage** [comment]
Not unless the amount of work is bearable with regard to other issues, I cannot also keep up with frequent dependabot PRs, currently it is much easier to sit down one hour per month to update everything accordingly for me. This currently adds more overhead than which it removes.

**Comment by tobiasdiez** [comment]
Makes sense. Then I'll close this for now, and will reopen it as soon as dependabot supports combining multiple changes in one PR. Then you can set the check interval to monthly, and essentially get your workflow except that you don't need to look for updates yourself.

**Comment by nathanlesage** [comment]
That would be perfect.
