### ISSUE TITLE
Rendering equation

### ISSUE THREAD

**Issue by redoxmatlab** [Zettlr/Zettlr#725]
Dear colleague,

Zettlr supports inline rendering of simple math formulae. Could you please help me addressing the following issue with the equation below? 
$$
\begin{align*}
y = y(x,t) &= A e^{i\theta} \\
&= A (\cos \theta + i \sin \theta) \\
&= A (\cos(kx - \omega t) + i \sin(kx - \omega t)) \\
\end{align*}
$$

Also, does Zettlr support formula numbering?

Many thanks

**Comment by Wieke** [comment]
The $$ signs basically denote a math environment and `align*` can't be used within a math environment so you should be using `aligned` instead, getting this:

```md
$$
\begin{aligned}
y = y(x,t) &= A e^{i\theta} \\
&= A (\cos \theta + i \sin \theta) \\
&= A (\cos(kx - \omega t) + i \sin(kx - \omega t)) \\
\end{aligned}
$$
```

Out of the box zetlr doesn't really support math numbering\refrences nicely. Part of the problem is that Katex (the library that renders the equations on screen) doesn't seem to support them. If you're only going to be exporting to pdf then you could just mix in the appropriate latex commands. If you need to export to other format as well you could use [pandoc-crossref](https://github.com/lierdakil/pandoc-crossref) (by installing it and adding it to preferences > advanced > pandoc command). I have pandoc-crossref set up and if I export this to pdf:

```md
$$
\begin{aligned}
y = y(x,t) &= A e^{i\theta} \\
&= A (\cos \theta + i \sin \theta) \\
&= A (\cos(kx - \omega t) + i \sin(kx - \omega t)) \\
\end{aligned} 
$$
{#eq:foo}

Some reference to @eq:foo.
```

I get this:

![image](https://user-images.githubusercontent.com/6737186/81172986-91635680-8f9f-11ea-8da7-f99b12ee8f03.png)

**Comment by redoxmatlab** [comment]
That's great! Thank you.

**Comment by nathanlesage** [comment]
Is this solved now? :)

**Comment by redoxmatlab** [comment]
Yes it is. Thank you. I'll close this issue.

**Comment by chchen2021** [comment]
>  If you need to export to other format as well you could use [pandoc-crossref](https://github.com/lierdakil/pandoc-crossref) (by installing it and adding it to preferences > advanced > pandoc command). I have pandoc-crossref set up and if I export this to pdf:

@nathanlesage: How do I add pandoc-crossref in the 2.0beta? The instruction above does not seem to work. I also tried adding `filter: pandoc-crossref` to "Assets Manager | Exporting | PDF", but there is no effect.

**Comment by chchen2021** [comment]
On 2.0beta, I guess the [PDF Preferences](https://docs.zettlr.com/en/reference/settings/#pdf-preferences) has been moved to the Assets Manager. However, I am having trouble in changing the default paper size from A4 to letter. I tried different syntax but none worked. 

I must be missing something simple. Could you give the code to change paper size so I have a reference point?

**Comment by nathanlesage** [comment]
> The following YAML is literally printed at the beginning of the pdf:

This indicates that Pandoc doesn't properly detect the YAML metadata block. Pandoc will never literally print out a YAML metadata block, so there might be some error in the YAML syntax …?

**Comment by nathanlesage** [comment]
Aaaaah, yeah "PDF Document" means that Zettlr will export the file to HTML and then, using Chromium's built-in stuff "print" it to PDF. I don't know how the papersizes are set there and unfortunately don't have time to dig into this right now :(

**Comment by nathanlesage** [comment]
To make it more readable, you can omit the curly brackets and write it like so:

```yaml
variables:
  papersize: letter
  geometry: "margin=1in"
  fontsize: 11pt
  linestretch: 1.1
  CJKmainfont: "Songti SC"
```
