### ISSUE TITLE
[ENHANCEMENT] Behaviour of tab opening/closing when files aren't changed

### ISSUE THREAD

**Issue by Bubblbu** [Zettlr/Zettlr#734]
## Description

Multiple tabs are great, however, imho, the default behaviour for openning and closing tabs for "browsing" through tabs could be enhanced.

**Currently** each click will permanently open a new tab. I think it's common behaviour to click through your notes and browse contents without actually engaging with the note. This will at the moment lead to a lot of tabs or requires a lot of closing tabs.

## Proposed Changes

Maybe borrowing from other code editors:

Single click + no file change: Re-use the same tab for new notes.
Single click + file change: Keep tab
Double click: Make tab permanent

## Caveats

I think that this behaviour feels quite natural, but I might also be biased by my usage of code editors. Browsers definitely behave differently. At the same time, non-coders are probably also used to the idea of a double-click for a new tab

**Comment by nathanlesage** [comment]
Damnit, I should've seen that coming :D 

I decisively opted against such a feature out of the following reasons:

I am utterly unnerved by this feature, which is why I've turned it off in VSCode. The reason is that  it feels somewhat random when clicking on files. The natural assumption is "click = open", and not "click = maybe keep open". While this certainly saves space and enables a more fuzzy workflow, it does come across as a little bit intransparent. And especially if you quickly want to open a host of files (e.g. after a search) it does incur a slight mental overhead having to think to "double-click" instead of single click. Long story short: Basically both double click and single click open a file, but in one case it's somehow "pending" and it becomes easily intransparent.

To take your caveat section:

>  I might also be biased by my usage of code editors. Browsers definitely behave differently.

Yes, absolutely. And, as Zettlr is aimed at those who normally don't code (at least not that much), we should be wary of all the people using Zettlr but never commenting here because that's out of their world. We, as developers, will quickly get used to Zettlr behaving somewhat differently to code editors, but weighing all pros and cons, this is why I think it's more clear this way.

> At the same time, non-coders are probably also used to the idea of a double-click for a new tab

Yes, but not in Zettlr; here the "tradition argument" has a certain weight, because double clicking works in the Windows Explorer/Finder/Linux file browsers, but in Zettlr up until now it's just single clicking, so people would be a little bit confused, I would argue.

However, you do say something really important:

> requires a lot of closing tabs.

I have it on my radar to enable `Cmd/Ctrl+W` to close the editor tabs first before closing the window. Because then having more tabs than necessary is not that bad, as this is something "normal users" will be accustomed to as they know it from browsers.

… and, in the end, we have to accept the fact that a lot of these people are mouse-lovers who even copy and paste using the context menu … 🙊 

Any other opinions? (I'm closing this to keep the issue list clean, but as always I'll be notified of comments and will answer)

**Comment by Bubblbu** [comment]
Ha! It's interesting. I've mostly gone with the code editor argument, because I also had to get used to the new VSCodesque behaviour (I still rarely use double clicks, I must admit) but just assumed that following that new trend might be more common.

But I can definitely follow your line of thought there and might actually give it a try and turn off that function in my own code config.

> I have it on my radar to enable Cmd/Ctrl+W

As long as this is available, I think I'd be personally happy. I can workaround these things.

---

Playing the devil's advocate, I wonder if the VSCode style couldn't be actually better for pure mouse users... It's just utterly horrible to have to close 10+ tabs if you're basically only browsing through a directory and trying to get an overview of what you did. (I am now assuming that the user doesn't use keyboard shortcuts at all, so on Ctrl+W even after it's implemented).

Maybe that behaviour could be an option to choose depending on the preference of the user? In the end, this would still obviously bring up the question of the default behaviour... and how to neatly integrate the option (offer the option to the other kind of user) etc.

---

Overall, maybe it's good to keep it simple :D Current behaviour + shortcuts and I'm happy.

**Comment by nathanlesage** [comment]
> It's just utterly horrible to have to close 10+ tabs

Not if you do it as Zettlr does, where you can simply put your mouse cursor at the right edge of the tab bar and just keep clicking — no weird re-positioning of tabs as in Chrome for instance 😎 

> Overall, maybe it's good to keep it simple

Yes … because what I didn't even get to mention is the amount of work needed. Unfortunately, while tabs look pretty simple, it's much more complicated, as these don't work like windows internally, but this is basically just a graphical representation of documents currently loaded into the editor, and the thought of adding yet another flag (permanent yes/no) frightens me 🙃

**Comment by BellLongworth** [comment]
> Yes, absolutely. And, as Zettlr is aimed at those who normally don't code (at least not that much), we should be wary of all the people using Zettlr but never commenting here because that's out of their world. We, as developers, will quickly get used to Zettlr behaving somewhat differently to code editors, but weighing all pros and cons, this is why I think it's more clear this way.

I think this is the correct approach (especially as I'm not a coder). But then, the logical solution would be to implement a browser-like behavior.

You don't want to invent your own UX just yet ;). It is best to comply to a common design and avoid mix and match.

There are 3 possible designs to choose from:
1. Code editors
2. Browsers
3. Windows file explorer

As code editors were ruled out and Windows file explorer is not something that people interact with nearly as often as browsers, my conclusion at least is that a browser like behavior is best.

**Comment by nathanlesage** [comment]
Please y'all head over to this issue and give your estimates on how that should work: https://github.com/Zettlr/Zettlr/issues/743
