### ISSUE TITLE
[FEATURE] API for notes, directories, and projects

### ISSUE THREAD

**Issue by Bubblbu** [Zettlr/Zettlr#736]
## Description

I was wondering if you have considered creating an API for notes, directories, and projects? Similar to what Joplin offers: https://github.com/laurent22/joplin/blob/master/readme/api.md

Why?

While definitely not crucial for Zettlr's functioniality, I think it would invite tinkerers and other projects to use and consider Zettlr. I could very much see people automatizing their workflows by pushing & pulling content directly from Zettlr while using the GUI to manage and work with the content.

Disclaimer: I am one of those people who are considering to tinker with that as I'm working on a [CLI tool](https://github.com/bubblbu/zotnote) that provides some tooling around literature managed with Zotero/BBT especially for the initial creation of the notes with templating. I could very much see myself offering dedicated options to support Zettlr or Joplin. While the basic features could actually be easily implemented in Zettlr, I do think that there is a space for a, e.g., editor-agnostic cli tool for us weird folks who like the command line

## Additional Information

This is definitely not the correct place for that, however, I just wanted to say thanks for your work here on Zettlr! I will adopt a lot of ideas for Zotnote and the templates of notes + internal structure of my classes based on your implementations and thoughts around Zettelkasten and note-taking for academia.

**Comment by nathanlesage** [comment]
> This is definitely not the correct place for that, however, I just wanted to say thanks for your work here on Zettlr! I will adopt a lot of ideas for Zotnote and the templates of notes + internal structure of my classes based on your implementations and thoughts around Zettelkasten and note-taking for academia.

Thank you very much, I'm honored :)

> I was wondering if you have considered creating an API for notes, directories, and projects?

Yes, there's a callback API waiting to be implemented, see #140 

However, based on the age (it's been waiting for over a year now -.-) and due to much more info in this comment, I'll close the former one!

P.S.: To give me more motivation in tackling this earlier, please feel free to think about any API endpoints that would need to be available.

P.P.S.: Also take into account that I will only implement an API that requires a valid token in order for Zettlr to respond to requests. Makes integration one step more difficult, as you'd have to generate such a token beforehand, BUT with a valid token we could basically open the gates to ANY tinkering! 😈 

![image](https://user-images.githubusercontent.com/17251683/81350879-404c8300-90c3-11ea-900a-9ba23bc7bfda.png)
