### ISSUE TITLE
New lines don't show up in windows notepad

### ISSUE THREAD

**Issue by Kurren123** [Zettlr/Zettlr#757]
If I make the following file on windows : 
![image](https://user-images.githubusercontent.com/3525980/81474289-5316a300-91fc-11ea-9db6-4c81275d5b64.png)

Notepad++ shows this as:
![image](https://user-images.githubusercontent.com/3525980/81474314-8ce7a980-91fc-11ea-8610-799c739ddd0b.png)

However plain notepad shows as:
![image](https://user-images.githubusercontent.com/3525980/81474327-a12ba680-91fc-11ea-9cc5-8e6cfb8fe50c.png)

Could it be something to do with newlines in zettlr using `\n` and windows using `\r\n`?

**Comment by nathanlesage** [comment]
By default, Zettlr uses the much more compatible (cross-platform) linefeed newlines ("LF") instead of the "CRLF" linefeeds which only notepad uses. Notepad is also on Windows not a recommended editor. However, if you have a file that contains CRLF-linefeeds, Zettlr will persist them! But it is not recommended.

**Comment by Kurren123** [comment]
@nathanlesage thanks for your reply. Is there an option to always persist these? Most editors such as notepad++ or vscode does crlf by default on windows I think.

**Comment by nathanlesage** [comment]
> Most editors such as notepad++ or vscode does crlf by default on windows I think.

VSCode defaults to "auto" which might on some machines in fact add a CRLF. However, I am heavily inclined against enabling default CRLFs, due to numerous reasons:

- The carriage return is a remnant of a past, and we can save this byte to keep the code clean.
- Windows (especially newer versions) does handle standard linefeeds (LF, without the CR) pretty well, except some older binaries of the Notepad
- LF is used across every single system and makes the files cross-platform as well
- There even are some security-concerns, as apparently there are ["CRLF" attacks](https://www.acunetix.com/websitesecurity/crlf-injection/)
- [Newer versions of the Windows notepad](https://devblogs.microsoft.com/commandline/extended-eol-in-notepad/) give you the ability to switch to simple LF newlines instead of the old CRLF.

Zettlr retains CRLF feeds if it encounters them in case some older files need to retain these line feeds (there was an issue by a user who had to work with an old Windows code base where everything was full of CRLFs), but we won't support _creating_ new files using the legacy EOL sequence.
