### ISSUE TITLE
Windows release contains trojan?

### ISSUE THREAD

**Issue by jacquescorbytuech** [Zettlr/Zettlr#760]
Hi,

When trying to download the Windows release Windows Defender is telling me the file contains a trojan.

![image](https://user-images.githubusercontent.com/49435000/81498160-39886080-92bb-11ea-898d-c8365db1d0d6.png)

**Comment by nathanlesage** [comment]
There was a small issue a Month ago, because one virus scanner accidentally identified the binary as a trojan, but this has been rectified already. However, it may very well be that some of the lists containing all malicious apps have not yet been updated properly, so you can safely ignore this warning **if, and only if** you downloaded the installer either from https://www.zettlr.com/download **or** from https://github.com/Zettlr/Zettlr/releases.

There are a few malicious installers out there, but not on our website. With 1.7 this should be fixed, as we are finally able to code-sign the Windows releases (hence Windows can verify that they stem in fact from me, and not some malicious third party).
