### ISSUE TITLE
[BUG] File list is broken on Linux

### ISSUE THREAD

**Issue by Zverik** [Zettlr/Zettlr#762]
## Description

I've built Zettlr from source (`develop` branch) on Fedora Linux, and I don't see any files. Instead, the sidebar contains multiple directory items, separated by large empty space.

## Reproducing

```
get checkout develop
yarn install
cd source; yarn install; cd ..
yarn less
yarn handlebars
yarn wp:dev
yarn start
```

## Expected behaviour

This is what I get — and I'd like a file list, like on macOS:

![empty-files-zettlr170](https://user-images.githubusercontent.com/766031/81502689-04dece00-92e8-11ea-8725-ace9af6cf35b.png)

## Platform
 - OS and version: Fedora Linux 32
 - Zettlr Version: 1.7.0 beta1 (built yesterday)

**Comment by nathanlesage** [comment]
It would have been much more helpful if you had added a screenshot containing the 155 errors I can spot in your console 🙄

Nevertheless, the problem was a broken `moment.js`-version, which I already reversed (a more stable patch is currently on hold here: #758 )

If you build now from the most recent source on develop, this should work again!

**Comment by Zverik** [comment]
Indeed, the error's gone. Thank you!
