### ISSUE TITLE
Enhancement: Place Mouse Cursor on Text Cursor When the Menu Key is Pressed.

### ISSUE THREAD

**Issue by TUSF** [Zettlr/Zettlr#78]
## Description

When I see a word is marked as misspelled, I end up using the "Menu Key" on my keyboard, in hopes of bringing the menu up and correcting the mistake. Instead, the cursor is for some strange reason shifted over several characters to the left. This in turn means that I don't receive any correction suggestions, and the cursor has been forced to the left, the length of the menu. I have a screenshot below to better explain this issue.

As a result of this, I also noticed the Menu key refuses to work if I open it close to the start of the line, where the cursor won't be able to be forced any further left.

I like using the Menu key on my keyboard, because sometimes I just feel more comfortable not bothering with my mouse, so this is a bit of an annoying issue for me.

## Reproducing

Use the Menu key. This behavior sometimes doesn't happen, but it almost always does, and even when it doesn't, spelling suggestions are still not displayed on the menu.

## Expected behaviour

For the Menu to open where the cursor is, so I can correct the misspelled word without needing to move my mouse.

**Screenshots**

![screenshot_2018-12-23_21-42-46](https://user-images.githubusercontent.com/8594356/50390363-2a236a00-06fc-11e9-8eae-3d6e54f11918.png)

In the image above, the blue arrow is where I had the cursor when I hit the Menu key, and the red arrow shows where it got moved to. 

## Platform
 - OS: Ubuntu 18.04
 - Zettlr Version 0.20.0
 - Screen Resolution 1280x1024

## Additional information

Right clicking works as intended no matter where I do so. Only trying to open the menu through the keyboard key results in this issue.

**Comment by nathanlesage** [comment]
I believe that — on above screenshot — your mouse was where the red arrow is pointing at. I think that the application menu button simply triggers the `context`-event, receiving the last known mouse coordinates — which have not been altered since you last moved the mouse. Then, while your cursor has been at the blue arrow, the application key triggered a right mouse click at the mouse coordinates, which caused the cursor to first jump to the position of the mouse button and afterwards triggered the right-click.

The only possibility I could think of would be to listen to `keydown`-events on the CodeMirror instance, reposition the mouse cursor where the text cursor is before the `context`-event is triggered. But I cannot promise that this hack would work.

Therefore, this is not a bug, but it describes an enhancement, but one I can clearly see the benefits of.

To continue, please tell me the JavaScript keycode of the application key by visiting this site and pressing the key: https://keycode.info/

Then I can implement this enhancement in a future version.

**Comment by TUSF** [comment]
The keycode is `93`.

That said, this issue is _not_ caused by the mouse. In fact, when this bug happens, the context menu appears the same distance to the left, no matter where I have the mouse. I even tested this by repeatedly using the Menu key, without moving the mouse, and this cause the cursor to be pushed to the left with each successive press.

It's not always the same distance, but the the cursor is always pushed to the left, regardless of where the mouse is.

**Comment by TUSF** [comment]
Yep, looks to be a bug in CodeMirror.

It doesn't happen always, but after typing a bit and hitting the Menu key, the cursor is moved to the left by 4 characters, and the context menu pops up there. This happens regardless of where my mouse is.

Oh, it looks like the distance that the cursor is pushed to the left increases the more I type, although it "resets" after a certain point. It's a pretty weird bug, but it does seem to have _some_ kind of logic behind it?

**Comment by nathanlesage** [comment]
Okay, I think I have a slight idea what is happening.

The keycode for the menu key is located [here](https://github.com/codemirror/CodeMirror/blob/master/src/input/keynames.js).

So CodeMirror clearly recognizes it. So what I think may be happening under the hood of CodeMirror is that whenever a "mod" key is pressed (there are several of them) some logic applies and only afterwards, the "real" contextmenu-command is issued. I think something in [here](https://github.com/codemirror/CodeMirror/blob/master/src/edit/commands.js) is interfering.

But as this is not a Zettlr-bug, I would like to kindly ask to open up this issue on the repository of CodeMirror so that Marijn can address this issue. They request some information according to [this](https://codemirror.net/doc/reporting.html). The CodeMirror release in Zettlr 0.20.0 is `5.39.0`.
