### ISSUE TITLE
Stop generating tags form inline hashtags

### ISSUE THREAD

**Issue by Shandi97** [Zettlr/Zettlr#79]
Once again another tag issue.

Zettlr interprets hashtags inside url as tags. The links work but it does give me some false tags. I can escape them but that breaks some of the links. Tried putting them into markdown links but it doesn't help and has issues there too.

https://imgur.com/qb6gCKD  
https://imgur.com/9L6D5PI  
https://imgur.com/HePgTUY

**Comment by nathanlesage** [comment]
Damn, I thought I had fixed this … I'm on it!

**Comment by nathanlesage** [comment]
Alright, I fixed most of the tags:

![image](https://user-images.githubusercontent.com/17251683/50631758-d60f5580-0f45-11e9-87ce-d0c7d6b212c9.png)

I'm still on the explicit markdown syntax, because there the error is not in tag detection (the `#Perversion` is not detected as tag by the engine) but in the URL detection. This could take some further time.

To circumvent this just replace the closing brace with `%29` (iirc)

**Comment by nathanlesage** [comment]
Alright, the link detection does not work because Wikipedia links in many cases contain literal braces (`(` and `)`), which makes it hard to check against such links. To circumvent those specific link issues for now is to escape the characters with both `%28` (opening brace) and `%29` (closing brace). These links work just as fine.

Links then look like this: `https://en.wikipedia.org/wiki/Sexual_Desire_%28book%29#Perversion`

**Comment by nathanlesage** [comment]
Concerning the links you reported: These work fine as well now!

As for the numbers: I wondered yesterday whether or not I accounted for multiple reportings — now we have the answer: I didn't 😅

I'm on it!

**Comment by pkritiya** [comment]
Is this the same problem? 

Zettlr recognizes words followed by # as a tag - which is fantastic! 
However, is there a way to avoid Zettlr tagging when # is used in the middle of the word (when there is no space in between a word and #). 

For example, 

sk://robert#21 - zettler recognizes #21 as a tag, but I need # needs to be used in the middle of the word in order to link external pdf files. Is this possible? 

robert #21  (#21 as a tag) 
BUT NOT robert#21 (#21 not as a tag in this case) 

Thanks

**Comment by nathanlesage** [comment]
@pkritiya Yes, this is the same problem, and it has been fixed. The patch will ship with the next version!
