### ISSUE TITLE
[BUG] ? Zettlr 1.7.0 beta 3 - JavaScript error

### ISSUE THREAD

**Issue by elkrause** [Zettlr/Zettlr#791]
## Description
I just installed the newest Zettlr beta and get this error message. Zettlr doesn't not open.

## Expected behaviour

**Screenshots**
![grafik](https://user-images.githubusercontent.com/53222869/81851615-0e6f6c80-955a-11ea-8572-9cf3e8f59f88.png)

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.7.0 beta 3
 - Screen Resolution: 1920x1280

**Comment by henrique9i** [comment]
Me too, same platform

**Comment by IulekShi** [comment]
same here, macOS Catalina latest (10.15.4)

<img width="450" alt="Schermata 2020-05-13 alle 21 03 05" src="https://user-images.githubusercontent.com/55080372/81854224-e5e97180-955d-11ea-8fe8-232cb9cbb163.png">

(installed beta 2 back)

**Comment by enricllagostera** [comment]
Hi, I had the same error, on Windows 10, 64 bits, on Zettlr 1.7.0 beta 3.

![image](https://user-images.githubusercontent.com/7241869/81856222-81fb8480-952e-11ea-8b58-84ed5f6fb5cb.png)

**Comment by nathanlesage** [comment]
Ah crap, it was a bad idea to merge that PR so close to beta … gimme a sec …

**Comment by nathanlesage** [comment]
@tobiasdiez Just fyi: As there was no failsafe the devTools `require` in `main.js` threw up in built release, as we didn't include the Vue devTools in the inner `package.json` …

To the rest: I'm currently rebuilding, shouldn't take too long …

**Comment by nathanlesage** [comment]
And here we go, Beta 4 is out, this time it should work!

**Comment by enricllagostera** [comment]
Just confirming: it is fixed in my machine.

**Comment by nathanlesage** [comment]
💯

**Comment by IulekShi** [comment]
that was fast!
It starts beautifully now, thank you very much!

**Comment by tobiasdiez** [comment]
Sorry everybody that was a mistake on my side! Thanks @nathanlesage for the quick fix. I should test these PRs that touch the build environment also in the production mode.

**Comment by nathanlesage** [comment]
@tobiasdiez Yeah, but I've made this kind of mistake more than once myself, so it's really hard to think of it when we're doing something like that … to a certain extent I was thinking that maybe weekly nightlys might help …?

**Comment by tobiasdiez** [comment]
Maybe have a "nightly" channel which automatically updates to the current version in the `develop` branch?
For JabRef, we have a Github workflow that uploads the recent builds to builds.jabref.org/ after every commit to master.
https://github.com/JabRef/jabref/blob/master/.github/workflows/deployment.yml
This works quite well and we get a lot of early feedback from people trying out the dev version. If you have a large enough group doing this, you actually don't need any beta/alpha releases anymore because the current dev version is well tested. Also has the advantage that you can point people to the newest version after fixing a bug/implementing an issue.

For electron you can have even auto-update I think, so that users don't have to do anything to stay up to date.

**Comment by nathanlesage** [comment]
This is basically what I was getting at, yes!

> For electron you can have even auto-update I think, so that users don't have to do anything to stay up to date.

Yeah but it's again so much stuff we'd need to account for that I don't want to do this before 2.0 :/ Better just use what we already have and gradually getting to other things… but thanks for sharing the workflow, I'll give it a look and think of a smart way to do this with Zettlr (if you have something, feel free to drop it in! — maybe we should even put this whole "meta-discussion" to another channel …?)
