### ISSUE TITLE
Something seriously wrong with Latex and HTML export templates 

### ISSUE THREAD

**Issue by EcoFin** [Zettlr/Zettlr#795]
Zettlr is unable to export the following minimal example correctly in any of versions 1.6, 1.7.1, 1.7.4.

"installed at:	C:\Users\ajryounger\Anaconda3\envs\Wagtail_test\Lib\site-packages\wagtailmarkdown" (ignore the quotes)

The latex export fails. Here is the export error message:

![image](https://user-images.githubusercontent.com/7763730/81879176-07475f00-9558-11ea-9168-4a435c93df23.png)

Amusingly, the HTML export just silently trashes the input.  It produces ...

"installed at: C:_test-packages".   That is worse than the error message, because you might not notice in a long document.

It makes no difference whether the slashes are escaped or not.  

Typora has no problem with this file exporting either to latex or HTML.

**Comment by nathanlesage** [comment]
Literal backslashes need to be escaped, I just copied over that to my installation, and Zettlr already escaped them for me. Exporting works just fine. I assume the reason Typora doesn't fail at exporting this is simply because you cannot make use of LaTeX-statements within MD-files in Typora, so their algorithm can basically assume every backslash needs to be escaped prior to exporting to PDF. This does not work with Zettlr, as Zettlr gives you the ability to add LaTeX-code to your files, hence: Zettlr cannot simply assume "Ah, let's just escape all backslashes" as this would render inoperable potential LaTeX-statements.

**Comment by EcoFin** [comment]
I know escaping backslashes can often be problematic.  I had already tried both escaping them and replacing with forward slashes.  Neither made any difference (and was tedious to do by hand obviously!).  You are right that Typora allows you to embed html but not latex.

But do I understand that you were able to copy my little example into Zettlr and it worked fine?

Auto-escaping is exactly what we want.  Is there something I'm doing wrong?

**Comment by nathanlesage** [comment]
> But do I understand that you were able to copy my little example into Zettlr and it worked fine?

Yes

> Auto-escaping is exactly what we want. Is there something I'm doing wrong?

I am not sure … do you use double-backslashes? It needs to look like this:

![image](https://user-images.githubusercontent.com/17251683/81955167-0a028c80-960a-11ea-973e-c05c6273d80b.png)

**Comment by EcoFin** [comment]
Yes, I tried that but it did not help.  In any case it would be impractical to do it manually.

 

ay

**Comment by nathanlesage** [comment]
Hmm … which versions of XeLaTeX and Pandoc do you have installed …? Maybe it's an error in one of these programs that only got fixed later …?

**Comment by EcoFin** [comment]
I keep those things pretty up to date. Pandoc is 2.9.2.1.  That was installed as soon as it was released.  Miktex is 2.9.  I run the package update every month or so.

 

arthur
