### ISSUE TITLE
[bug] Bar of reopened note not visible  in the tab view when multiple other notes are open

### ISSUE THREAD

**Issue by danieltomasz** [Zettlr/Zettlr#799]
## Description

1. Open specific note in tab
2. Open more notes that, the first note is not visible in tab bar now
3. Open the first note again (from sidebar)
4. Only the body with the content of the note is visible, the name of the note is not visible in the tab view (app doesn't focus on it)
5. After closing other notes the bar with note name is again visible

## Expected behaviour

**Screenshots**

## Platform
 - OS and version:
 - Zettlr Version: 1.7.4
 - Screen Resolution:

**Comment by nathanlesage** [comment]
> Only the body with the content of the note is visible, the name of the note is not visible in the tab view (app doesn't focus on it)

you can scroll left and right in the tabbar, just like VSCode. Only the scroll-into-view for leftmost notes is as of now missing!

If you wanna have a look: https://github.com/Zettlr/Zettlr/blob/develop/source/renderer/util/editor-tabs.js#L107

😄

**Comment by Zverik** [comment]
How do I scroll tabs left and right with a regular mouse? Scroll wheel does nothing.

Also, I believe scrolling tabs is among the worst UI decisions: tabs are supposed to give a quick access to files, and if you have to scroll them, then why not just use the always visible file list on the side?

I would suggest:

* Using non-monospaced font to see longer titles in tabs.
* Setting a limit on open tabs and closing the oldest tabs over that.
* Optionally pinning tabs to not have them closed.
* Removing tab scrolling, for it is confusing, and nothing now prompts you even can or should do that.

**Comment by nathanlesage** [comment]
> How do I scroll tabs left and right with a regular mouse? Scroll wheel does nothing.

I think here my macOS bubble stroke, because with a trackpad it's easy (or if you have a middle mouse button that supports left/right tilting).

> Also, I believe scrolling tabs is among the worst UI decisions

Then how should we handle …

1. Different screen sizes?
2. Too many tabs?

I don't want to end up like Chrome:

![image](https://user-images.githubusercontent.com/17251683/82028409-e422c980-9695-11ea-9060-3d631678ab42.png)

> Using non-monospaced font to see longer titles in tabs.

Which theme does have a monospaced font on the tab titles?! o.O

> Setting a limit on open tabs and closing the oldest tabs over that.

No, no no no! This introduces opaqueness into the behaviour. You would certainly not expect Zettlr to simply close tabs, plus: No other program is doing this. Then rather find something to make the tabbar accessible for non-trackpad users as well

> nothing now prompts you even can or should do that.

This is basically the question I keep asking you :D 

There are several options:

## Option 1: Simply shrink the tabs into oblivion, like Google Chrome:

![image](https://user-images.githubusercontent.com/17251683/82028409-e422c980-9695-11ea-9060-3d631678ab42.png)

## Option 2: Provide scroll buttons, like e.g. OctoberCMS

![image](https://user-images.githubusercontent.com/17251683/82028729-4e3b6e80-9696-11ea-87d1-07fa253b7904.png)

Also, slightly better implementation in Firefox:

![image](https://user-images.githubusercontent.com/17251683/82028822-67441f80-9696-11ea-8c8b-bc00ec2c817a.png)

## Option 3: Leave it like now, like VSCode, but add a very thin scroll bar

![image](https://user-images.githubusercontent.com/17251683/82028895-788d2c00-9696-11ea-898f-f96fddca4685.png)

**Comment by danieltomasz** [comment]
The simplest solution in my original problem (without UX consideration, which is also imortant) would implementing  tabs as an stack, if reopened tab is not visible should be moved from the previous position to the top of the stack (and the tabs from top of stack are  visible)

**Comment by danieltomasz** [comment]
About UX: I like VSC folder like view of the opened files/tab, according to me this would be sufficienT

I am on Mac (sometimes on Linux too) and ctr + tab doesnt work in my case :(

**Comment by nathanlesage** [comment]
> I am on Mac (sometimes on Linux too) and ctr + tab doesn't work in my case :(

Because the shortcuts are not yet implemented, again! Stop asking me about this until I've managed 😄 First the logic, then the neat easy details such as shortcuts! =D

**Comment by nathanlesage** [comment]
How about we leave it like that, because using Tab and Ctrl+Tab you can go through the tabs already …?

**Comment by danieltomasz** [comment]
it's implemented in the new beta? the shortcut doesn't work for me or I missed something

**Comment by nathanlesage** [comment]
current develop, not beta — just implemented it today.

**Comment by danieltomasz** [comment]
Sorry, I was confused, the app is developing so fast :P

**Comment by nathanlesage** [comment]
I missed the most obvious choice for non-macOS-systems: Simply transpose vertical scrolling with the mousewheel/trackpad into horizontal scroll movements lol

So I'm gonna implement that one :D
