### ISSUE TITLE
Feature Request: Inline Image and Table Preview

### ISSUE THREAD

**Issue by sahil48** [Zettlr/Zettlr#8]
It would be great if you could show a preview of images or tables added tot the document within the editor. Not sure what the best way to approach it would be, though. I was thinking of a tiny unobtrusive button next to images and tables you could click for a preview, or maybe hovering over it.

**Comment by nathanlesage** [comment]
That's a feature I'm currently working on. I have planned in doing it in the same respect as Abricotine because Thomas is using CodeMirror to display text as well. It still doesn't work reliably, but it is the thing I'm currently working on.

As for tables, I think they will need to be coming in a later version, but there's definitely a plan to implement this!
