### ISSUE TITLE
[BUG] Link autocomplete not always works

### ISSUE THREAD

**Issue by b4nn** [Zettlr/Zettlr#819]
## Description
Sometimes when creating a new link with [[]], autocomplete menu does not appear. When this happens restarting the app fixes the issue.

## Platform
 - OS and version: win32 10.0.18362 (architecture: x64)
 - Zettlr Version: v1.7.0-beta.5

**Comment by shanvrolijk** [comment]
this also happens to me. I modified the id/zettelkasten id by adding spacebar in front of it so that the title of the file will be visible in the tab. This works just fine. But sometimes, especially when I created or renaming a file, that file will refuse to be included in the autocomplete menu, or if included, it will be rendered as [[title_ID]] instead of [[ID]] Title.

    OS and version: Windows 10, Intel(R) core(TM) i5 8250U CPU @ 1.60GHz 1.80 Ghz.
    Zettlr Version: v1.7.0-beta.5
    Screen Resolution: 1366 x 768

**Comment by nathanlesage** [comment]
Could you two give me precise examples of what Zettlr is doing, and what you expect it to do?

E.g.:

```
```

**Comment by b4nn** [comment]
When I type "[[]]" in the editor window, I expect the autocomplete menu to appear with my notes like here:
![image](https://user-images.githubusercontent.com/65569952/82315137-c8cffb00-99c2-11ea-8b76-f50156bb74f9.png)

Sometimes, when doing the same action the autocomplete menu does not appear so I'm not able to create a link. I don't know what is causing the issue other than it seems to happen when Zettlr is running longer than couple minutes. Every time I restarted the app it worked fine again.

Let me know if I can clarify this more.

**Comment by nathanlesage** [comment]
> I don't know what is causing the issue other than it seems to happen when Zettlr is running longer than couple minutes.

\*quickly checks\*

Ah, can confirm!
