### ISSUE TITLE
[BUG] Pasting html text that is longer that a single paragraph doesn't copy hyperlinks and italics

### ISSUE THREAD

**Issue by b4nn** [Zettlr/Zettlr#821]
## Description
Pasting html text that is longer that a single paragraph doesn't copy hyperlinks or italics

## Reproducing
Copy couple paragraphs with hyperlinks or italics for a example from [this article](https://aeon.co/ideas/hypocognition-is-a-censorship-tool-that-mutes-what-we-can-feel) and paste it to Zettlr. Hyperlinks or italics are not getting copied. Strangely, when copying and pasting a single paragraph it works okay.

## Platform
- OS and version: win32 10.0.18362 (architecture: x64)
- Zettlr Version: v1.7.0-beta.5

**Comment by nathanlesage** [comment]
This is an external issue that is caused by the interplay between Google Chrome and the Joplin-Turndown library Zettlr uses for the conversion from HTML to Markdown. The bug does not occur on Firefox. See this issue that pertains precisely this: https://github.com/laurent22/joplin-turndown/issues/11

**Comment by b4nn** [comment]
@nathanlesage I've installed the firefox but the same issue occurs. I'm able to copy and paste a single paragraph correctly, but multiple paragraphs copy without all the links or italics.

**Comment by nathanlesage** [comment]
@b4nn I couldn't reproduce it — I used the article you linked, used Firefox, and copied two paragraphs with emphasis and links in them, and it worked fine for me
