### ISSUE TITLE
Export internal link

### ISSUE THREAD

**Issue by LacikaG** [Zettlr/Zettlr#844]
## Description

Internal link [Chapter 5]([[Chapter 5 Leadership]]) is good in Share the current file in PDF, but not in the Project export. 

## The problem is that internal links do not work in the Export Project (pdf).

Below, you can see in pictures the three versions: the first is the Editor, the second is Export Project and the third one is Share the current file in PDF.

## Reproducing

Export an internal link with Project export (pdf) and Share the document in pdf. The result is not the same. 

**Screenshots**
![Screenshot 2020-05-28 at 16 08 51](https://user-images.githubusercontent.com/66075400/83153261-0d644080-a0ff-11ea-9c80-416b0d5b2d9b.png)
//////////////////////////////
![Screenshot 2020-05-28 at 16 09 25](https://user-images.githubusercontent.com/66075400/83153277-11905e00-a0ff-11ea-89b3-caa140ae5cf4.png)
////////////////////////////
![Screenshot 2020-05-28 at 16 09 54](https://user-images.githubusercontent.com/66075400/83153300-15bc7b80-a0ff-11ea-9c88-46de26e69814.png)

## Platform
 - OS and version: 10.15 OSX
 - Zettlr Version: 1.6
 - Screen Resolution: 1440 x 900

**Comment by nathanlesage** [comment]
I am very sure that these links you are describing are also not working in regular exports, because what you're attempting to do is not a valid Markdown link.

Zettlr basically allows the following kinds of links:

- `[Link text](www.google.com)`
- `[Link text](./path/to/file.md)`

Putting a Wiki-link in there (`[Link text]([[my-link]])`) does not work, because it is internal to the Zettelkasten logic, and therefore counters the logic of Markdown links. If you want to link files, please provide a relative or absolute path to the file, which should — in most converters — result in correct links, and use wiki-links only for "fuzzy-searching" for files!
