### ISSUE TITLE
Only displays a white screen after npm install

### ISSUE THREAD

**Issue by JulienMir** [Zettlr/Zettlr#846]
## Description
As I wanted to contribute, I cloned the repo.
Following the instructions, I run `npm install` in Zettlr directory and `npm install` in Zettlr/source directory.
Then, back in the main folder after running `npm start`, all I see is a "white screen" (as in #829).

When I only use the `npm start` command after cloning, everything works fine.

## Reproducing
`git clone https://github.com/Zettlr/Zettlr/`
`cd Zettlr`
`npm i`
`cd source`
`npm i`
`cd ..`
`npm start`

## Expected behaviour
Standard editor view I usually get when I open the Zettlr binary I installed

**Screenshots**
Exact same as #829 

## Platform
 - OS and version: Win10
 - Zettlr Version: develop branch
 - Screen Resolution: 1920x1080

**Comment by nathanlesage** [comment]
Yeah, there's some malfunctioning dependency that npm pulls but not yarn — I haven't had the time to look at it. Normally, if you just see a white screen, opening the devtools will still work and then you'll see an error. In this case some module screwed up offering a default export or something — if you find the time to pin down that bug, please feel free to open a PR for that! I'm extremely sure it's because a newer dependency broke which is not (yet) in the `yarn.lock`

**Comment by nathanlesage** [comment]
Please feel free to check again! if npm install won't work for now, please use Yarn until we've got this fixed, as it doesn't have priority!
