### ISSUE TITLE
Search by tag not present

### ISSUE THREAD

**Issue by An-png** [Zettlr/Zettlr#853]
Have the ability to search for md files that do not have a cetrain tag.

**Comment by danieltomasz** [comment]
This would involve implementing more advanced search rework

**Comment by nathanlesage** [comment]
Yup … I mean, it does sound reasonable, but there's so much we'd need to do reworking the whole search algorithm again (which we should do either way …)

**Comment by An-png** [comment]
> This would involve implementing more advanced search rework

Forgive me if I am being ignorant (as I do not understand the intricacies of your code and I am still very much a beginner in coding), but:
Surely you can just use a `not` operator?

For example, if this was the pseudocode for the search function

then couldn't you use a `not` operator, i.e. display a file when the tag ISN'T found? (Or am I completely oversimplifying things?)

This could happen if a tag is preceded by a minus sign (`-`)

**Comment by nathanlesage** [comment]
> Surely you can use a not operator, i.e. display a file when the tag ISN'T found? (Or am I completely oversimplifying things?)

The problem is that a `not` operator is semantically different from `does not have`. By using the NOT operator (`!#my-tag`) you are telling Zettlr basically to exclude everything where the mentioned tag exists. This is insofar problematic as you have specified what you do NOT want to have, but you haven't yet specified what you DO want, that means: To search for files not having a certain tag you'd need to specify the search FOR something (using anything else).

So what we're basically looking at is a detection mechanism to see "Ah, the user is ONLY searching for NOT-stuff, so reverse the meaning of search". Currently, the search is biased towards searching FOR something. What the implication of this issue is, is basically to reverse all search results, and this cannot be simply dropped in, unfortunately …
