### ISSUE TITLE
Hide the markdown elements

### ISSUE THREAD

**Issue by tiotrom** [Zettlr/Zettlr#856]
In simple terms, would be great if users can also hide all of the markdown elements and use this as a normal text editor with all of the features that markdown has. 
![image](https://user-images.githubusercontent.com/34804533/83337146-59f37b80-a2b9-11ea-90e5-7f6e423bd352.png)
![image](https://user-images.githubusercontent.com/34804533/83337178-87402980-a2b9-11ea-9ca1-e352191d7e0d.png)
To be like an opt in thing in the settings. Could be useful since at times I copy stuff from Zettlr to something else, and it copies with the markdown symbols.
Cheers!

**Comment by nathanlesage** [comment]
What you are referring to is a WYSIWYG editing mode. While not officially supported, you can turn on something like this by activating the debug mode, opening the developer tools and typing in `renderer._editor._wysiwyg = true` and this will (until restart) activate a WYSIWYG editing experience. However, it is highly experimental and may not work as expected at all times. Furthermore, the feature is currently not under active development as **Zettlr is fundamentally a WYSIWYM-editor** (What You See Is What You Mean). That means: Instead of simply rendering all markup, it will only render those markups _that will significantly ease your work_ — such as links. This is a conscious design decision which I tend to uphold for now.

However, what you actually want to achieve is something different:

> Could be useful since at times I copy stuff from Zettlr to something else, and it copies with the markdown symbols.

When you copy text over from the editor, be aware that you're actually typing plain text, and this is what Zettlr will **always** copy to the clipboard by default. However, it is absolutely understood and also supported that there are many instances where you might want to copy over stuff from Zettlr and simply paste it into Word, Wordpress, any other word processing editor or any online content management system/blog software. **This can be achieved by copying that as HTML, or as a shortcut, `Cmd/Ctrl+Alt+C`.**

**Comment by Clindbergh** [comment]
Coming from Typora this is what I miss most about zettlr. Are there any plans to support a WYSIWYG mode?

**Comment by nathanlesage** [comment]
We more or less have one by now with the introduction of rendered emphasis in the last update.

**Comment by Clindbergh** [comment]
I went back and checked (again) all settings and did not find any settings that would improve the rendering (in the current release). Is this feature (rendered emphasis) already activated by default?

If so, the experience still largely seems similar to the screenshot of the author. Headings still start with `h1`, `h2`... and similarly blockquotes, code snippets and lists still show there original syntax. Links, Italics and Bolds are rendered as expected (from a WYSIWYG editor) and only show their syntax once the cursor is on an element. 

Furthermore the collapse feature is nice, but adds additional noise on the user interface . Typora does a better job at rendering, but also has less buttons which leads to a much cleaner ui overall. The option to hide the toolbar (#2976) will definitely be helpful here too.

Zettlr really seems quite feature rich and it's nice that there are efforts to improve it further. Also, thanks for the quick response.

**Comment by tio-trom** [comment]
How do I use this "rendered emphasis"? I'd like to check it. Thanks!

**Comment by nathanlesage** [comment]
The main problem we currently have (and this became extremely visible when we introduced the emphasis rendering) is that it is super hard to create a proper WYSIWYG feeling in the app without having access to an AST of the document. This is currently a little bit of a showstopper, but I'm continuously moving that idea back and forth in my head and will get back once I have a proper way of doing all of these requests without any glitches or other unexpected behavior.

**Comment by tio-trom** [comment]
Thanks! Should we then keep this issue as open?

**Comment by nathanlesage** [comment]
Nah, because *this* issue is fine so far. That is something bigger which needs to be addressed separately.

**Comment by tio-trom** [comment]
Gotcha! But when this will be improved maybe posting about it here could be helpful, if not will try to keep an eye on the release notes. Cheers!

**Comment by biva** [comment]
Hello, I love your program, thank you so much! The rendered emphasis is really great, and as mentioned by @tio-trom in https://github.com/Zettlr/Zettlr/issues/856#issuecomment-1085246708, this is perfect for bold and italic. The way Obsidian does it would be really perfect, notably for headings and code block (```)
- They are hidden by default
- When you click on the title, it shows the #
- When you click on a code block, it shows the ```

**Comment by iMikeG6** [comment]
If I may, I'll add my vote on this feature. I really like this program, but adding the rendering emphasis of code block and header would be a great addition. Also, if it can also render the note block which start with `>` would be even better.

**Comment by PwrSrg** [comment]
I also come from **Typora**, and the ability to quickly and easily hide/show the markup is by far Zettlr's **#1 missing feature**.

**Comment by agentlibre** [comment]
This issue has been closed. Does it mean that it has been resolved? 

To hide markup annotations would be a game changer, and steer many more users to Zettlr.

**Comment by nathanlesage** [comment]
> This issue has been closed. Does it mean that it has been resolved?

Yes.

**Comment by biva** [comment]
@agentlibre For linked features, this is being followed in distinct issues: 
- Italics and bold: https://github.com/Zettlr/Zettlr/issues/2377
- Code blocks https://github.com/Zettlr/Zettlr/issues/2378
- Headers: https://github.com/Zettlr/Zettlr/issues/5085
