### ISSUE TITLE
[ENHANCEMENT] Wrap selection in ** 

### ISSUE THREAD

**Issue by kjaquier** [Zettlr/Zettlr#864]
## Description

When selecting text and then pressing `[`, `_`, `(`, `'`, the selection is wrapped in `[...]`, `_..._`, etc.
When using `*` for italic and `**` for bold, one would expect it to work the same when pressing `*`.

## Proposed Changes

When selecting text and then pressing `*`, the selection is wrapped as follows: `*...*`

The `**` case is probably less obvious.
The easiest would probably be to handle it the same way as for `[[...]]`, i.e if already wrapped, wrap again.

## Caveats

Implementation or functionality might conflict with https://github.com/Zettlr/Zettlr/issues/860.
Personally, I think it would feel natural for `*` to not do anything smart (just wrap with `*` regardless of the selection), and for `CTRL+B` to toggle boldness (wrap/unwrap depending on selection).

## Additional Information
Using v1.6.0

**Comment by nathanlesage** [comment]
The reason this does not work is because it will interfere with the way lists are being made. Example: You type some text, use asterisks to automatically wrap stuff in italics and/or bold, and it goes fine. Then you press Enter, and attempt to create a list, but then you'd always have to get back to deleting the automatically added second asterisk, which is unwanted in this regard. Furthermore, it's more detrimental of having this problem regarding lists than regarding emboldening characters.

That being said: While we could easily make asterisks also wrap automatically, this will break for a lot of people, and as it is impossible to integrate context-aware behaviour (you may want to begin a line with italics), we settled for the way it currently is: Everywhere where a closing character is almost always necessary, we automatically wrap it, but due to the dual-use-nature of the asterisk, it is the only character that does not exhibit this behaviour. If you'd like to have automatically-closing characters, you can use underscores, as these are duplicated automatically, just like you proposed with the asterisk!
