### ISSUE TITLE
[Issue] Converting markdown that contains LaTeX control sequence to PDF fails

### ISSUE THREAD

**Issue by Sh4pe** [Zettlr/Zettlr#871]
## Description

Exporting a markdown document that contains some special strings (LaTeX commands) to PDF fails.

## Reproducing

Create markdown document that contains this text:
```
a \in b
```

Then try to export it to PDF. This fails for me.

## Expected behaviour

I want the PDF to be created, but instead an error occurs.

**Screenshots**

![Bug](https://user-images.githubusercontent.com/146497/83605088-92c07880-a577-11ea-965c-d7496498de94.png)

## Platform
 - OS and version: Windows 10, Version 1909
 - Zettlr Version: 1.6.0

**Comment by nathanlesage** [comment]
What you describe could either be a math equation (in which case the dollar-signs surrounding it are missing; at least one might read the error message this way), or the corresponding package is not required by the default Zettlr template. Please feel free to investigate that error, and how to resolve it!

**Comment by Sh4pe** [comment]
Not sure when I'll find the time to investigate, but if I could scratch together some hours, I'll look into it.

Note that I did not want a math equation. I stumbled accross this problem when I was trying to export a fairly large document. Somehow, the typo "\in" got into it, I just wanted to write "in". Took some time to figure that out... Maybe others have similar problems.

**Comment by nathanlesage** [comment]
Ah alright; yeah the thing is that LaTeX-commands are not filtered out, which could confuse the TeX-engine if `\in` as a command has not been defined …? I'm unfortunately very literate concerning TeX, so I'm not completely sure as to what this means …

**Comment by Sh4pe** [comment]
My LaTeX has grown very rusty too, but I think that \in is used inside math environments in LaTeX (i.e. parts that are enclosed with `$`) and denotes being an element in a set.

Anyways, it would propably be impractical to filter out all LaTeX commands since they are very many  and can even be defined by the user. 

But why is LaTeX used to create a PDF anyways? LaTeX (or TeX) seems to be a very advanced typesetting environment. I could not think of a reason that we need LaTeX for the very limited typesetting capabilities of Markdown...

**Comment by nathanlesage** [comment]
> Anyways, it would propably be impractical to filter out all LaTeX commands

Yeah, which would also be counterintuitive! It's meant to be in there, precisely because these commands enable much better typesetting:

> But why is LaTeX used to create a PDF anyways? LaTeX (or TeX) seems to be a very advanced typesetting environment.

This answers your question precisely!

> I could not think of a reason that we need LaTeX for the very limited typesetting capabilities of Markdown..

We need LaTeX __because__ of the limited typesetting capabilities of Markdown.

Remember the Zettlr philosophy: Use Markdown because first and foremost your own content counts. But as soon as you are satisfied with your content, you __then__ need capabilities to actually create good looking documents. And that's where LaTeX comes in!

Just have a look at one recent document I myself created using Zettlr:

![image](https://user-images.githubusercontent.com/17251683/83657016-93c9c800-a5c0-11ea-90df-f3c9367fc328.png)

I wrote that without any commands in there, but after I was finished, I added some small LaTeX commands here and there to improve the output.

Zettlr aims to be the "better Word", uncoupling writing and layouting processes within the application and adding a lot of features Word fails at implementing :)

But getting back to this issue: Do you think it's something we need to do something about or is the question resolved …?

**Comment by Sh4pe** [comment]
Na, I'm fine to resolve the issue. I have my workaround and am happy with it :)

**Comment by nathanlesage** [comment]
Perfect, I'm glad it worked out!
