### ISSUE TITLE
Deleting notes in 1.6.0

### ISSUE THREAD

**Issue by ditServices** [Zettlr/Zettlr#873]
## Description
When deleting notes via right click in the directory bar. The application hangs for 2/3 minutes, the note is eventually deleted. 

## Reproducing
Delete any note

## Expected behaviour
Deleting a note and not to cause hang

**Screenshots**

## Platform
 - OS and version:
 - Zettlr Version:
 - Screen Resolution:

KDE Neon 5.18
Zettlr 1.6.0
1920x1200

**Comment by Jos512** [comment]
I can imagine that this issue is related to the number of files in your directory, with the more files you have the slower Zettlr is. How many files do you have, if you don't mind me asking?

---

The new version 1.7.0 should, from what I understand, work much more efficient and quicker. It might be that the deletion process is also improved in the new version. :slightly_smiling_face:

**Comment by ditServices** [comment]
Its a new installation, there are no more than 10 notes

**Comment by ditServices** [comment]
Updating to the beta solved the issue

**Comment by nathanlesage** [comment]
> Updating to the beta solved the issue

This is good to hear! Please just notify us here on the repository if that issue starts to appear again so that we can fix it, in case the bug returns!
