### ISSUE TITLE
No highlighting of search results when global search term occurs in filename

### ISSUE THREAD

**Issue by kyaso** [Zettlr/Zettlr#874]
## Description
**Situation:**
Say, there is a file named `note-foobar.md`. This file also contains one or more strings containing "_foo_" somewhere in it.

Now, when doing a global search for "_foo_", the file `note-foobar.md` is found, however, none of the "_foo_"s inside it are highlighted.

## Reproducing
1. Create a note named `note-foobar.md`
2. Put some text + some "_foo_" strings
3. Search globally for "_foo_"
4. None of the "_foo_"s are highlighted

When the file is renamed to, e.g., `note.md`, the highlighting of "_foo_" works.

## Expected behaviour
Highlight search terms irrespective of their occurrence in filenames.

I was not sure at the beginning if this behavior is inteded. If you search for the _exact_ filename, then obviously Zettlr assumes you want to open that file, so there is no need to highlight anything. 

But I believe when you search for term(s), which also happen to be part of a filename, a regular search with highlighting should be performed.

## Platform
 - OS and version: Ubuntu 20.04
 - Zettlr Version: 1.6.0
 - Screen Resolution: 1920x1080

## Additional information
None.

**Comment by nathanlesage** [comment]
Hey, so it's super late, but here's the thing: If the filename matches your search terms, this means that the Zettlr search will use a shortcut (if the filename already matches, Zettlr will stop any further search). The reason for this is that the internal search engine is still somewhat slow.

I am right now in the process of researching better search engine algorithms, and when I implement these, this will automatically be improved upon. For now, this is a "wont-fix" issue because your files will be found, and you can still work around this by performing an additional internal search after you open the file!
