### ISSUE TITLE
How to move around chapters inside a project?

### ISSUE THREAD

**Issue by Sklanfurt** [Zettlr/Zettlr#88]
Hi, 
I just installed Zettlr and I am missing a core feature. Especially when I begin writing the Outline is changing constantly and I need to move around whole chapters with subchapters. This can be accomplished by using the Outline-Mode in Word or the Navigator in Libre Office. In general I am asking for the ability to move around chapters (respectively .md-files) inside the project or headings with attached subheadings inside a .md-file. 
Thanks in advance, 
SimonK

**Comment by nathanlesage** [comment]
So basically you request manual block-wise moving (e.g, all text from an h2 up to, but not including the next h2) and manual file sorting?

I always opted against the manual file sorting, as this would result in another file inside the directories in which I would need to store the information where the files are — but Zettlr tries to be a completely database-less program. Therefore I would opt for renaming the files to reflect the sorting using numbers (`001` until `143`) in the filenames. If this is difficult to accomplish (e.g. because a lot of files need to be renamed) I could certainly implement some batching!

Concerning the block-wise moving of chapters within files: I'll see to it!

**Comment by Sklanfurt** [comment]
Hi Nathan, 
thanks for the quick response and the evident reason why the rearrangement of files could be problematic.
To make myself clear, by moving chapters block-wise within files, I will try to give an example. I would like to be able to do something like: 

If the original text looks like:

> h1 Title
> 
> h2 Subtitle A
> h3 Text AAA
> h3 Text BBB
> 
> h2 Subtitle B
> h3 Text CCC
> h3 Text DDD
> h3 Text EEE
> 
> h2 Subtitle C
> h3 Text FFF
> h3 Text GGG
> 

Change this to:

> h1 Title

> h2 Subtitle C
> h3 Text FFF
> h3 Text GGG
>  
> h2 Subtitle A
> h3 Text AAA
> h3 Text BBB
> 
> h2 Subtitle B
> h3 Text CCC
> h3 Text DDD
> h3 Text EEE
> 


This should or could be accomplished by marking [h2 Subtitle C] with both h3 items inside it, and then dragging and dropping the item somewhere above [h2 Subtitle A] (see example above).

**Comment by nathanlesage** [comment]
Oh, thank's for the compliment =D

Concerning the rearrangement of sections: I think this should be rather easy, I'll get on it!

**Comment by offray** [comment]
Just to let you know, we at the [Grafoscopio][gf] community are using Zettlr for our [last project] and we dealing with rearrangement of files by creating a notebook which contains the files in the order we want to arrange them, something like:

![](https://i.imgur.com/pDhpxKi.png)

But I think that section rearrangement would be pretty useful, and also some kind of mini-outline for the titles and subtitles of a file that enables such rearrangement, including promoting and demoting (sub)titles in the document.

 [gf]: https://mutabit.com/grafoscopio/index.en.html
