### ISSUE TITLE
[BUG] Linking notes does not always add the filename

### ISSUE THREAD

**Issue by jadcx** [Zettlr/Zettlr#888]
## Description
When linking notes within a note, the filename is not always added when the option is set to 'always' in preferences.

## Reproducing
I am unable to reliably reproduce - this sometimes happens when selecting the highlighted search results from the autocomplete options, and doesn't ever seem to happen when selecting an unhighlighted one.

## Expected behaviour
Link the filename as indicated in the preference panel.

## Platform
 - OS and version: MacOS 10.15.5
 - Zettlr Version: 1.7.0-beta.9

**Comment by nathanlesage** [comment]
I noticed something similar, but didn't have the time to investigate right now. As soon as you find out some pattern, please notify us here so that we can dig into that problem!

**Comment by PhilHem** [comment]
Got the same issue on OS X 14.4.0

**Comment by davidtimmons** [comment]
Same issue on Windows 10 Home (10.0.19041 Build 19041) with Zettlr 1.7.5. It happens regularly, but I have also not observed a consistent pattern.

**Comment by nathanlesage** [comment]
There'll be a 1.8 beta soon, I'd like you to test it out with this as well – I won't touch the 1.7.x branch anymore due to missing bandwidth!

**Comment by davidtimmons** [comment]
I have not had a chance to test the 1.8 beta, but I did discover how to reliably reproduce this bug in 1.7.5. I understand 1.7.x is no longer under development. However, since this may also apply to 1.8.x, I am sharing what I found.

This bug appears to be associated with the auto-save feature. Here are the steps to reproduce the bug:

1. Create two new files.
2. In either file, begin typing the file link syntax, e.g. `[[xyz]]`, to cause the file link selection box to appear.
3. Leave the box open; do not make a selection.
4. Note the asterisk next to the file name in the file tab at the top of the screen.
5. When the asterisk disappears, indicating the file has been saved, make a selection in the open file link box.
6. The title from the linked file will not be included in the resulting file link.

If one quickly makes a selection before the file auto-saves, the link and its title are both added to the file.

**Comment by nathanlesage** [comment]
> However, since this may also apply to 1.8.x, I am sharing what I found.

Yes, thank you!

Now that I have a reproducibility, I can have a look :)

**Comment by mousetrappling** [comment]
This bug has reappeared with the most recent betas for 2.0.0 and is definitely related to saving (which is why it went away in the first couple of 2.0.0 betas when there was no autosave).

Quickest steps to reproduce:
1. type [[
2. while the dropdown list is open press ctrl-s to save the file
3. choose an item from the dropdown list

If you do this then the title is not appended to the [[ID]].  I have tested this with autosave off and with autosave set to "a short delay" (the latter is my normal setting, which is how come I noticed the unwelcome behaviour was back!).

**Comment by nathanlesage** [comment]
I'm not sure if that's something I'd consider fixing. The list will remain static as long as it's displayed, so to "fix" this all you'd need is to cancel the autocomplete and re-start it (for example by hitting Esc and then typing the triggering character sequence again). I'd say this is as far as it can go, because the list cannot be made dynamically I think. I could definitely look into that but it has absolutely no priority if the fix is that easy, because I have so extremely less time …

**Comment by nathanlesage** [comment]
> I just tested it, and as I thought it's never possible to get the title to show up because the file saves as soon you type anything that opens the dropdown menu thus triggering the bug.

Ah wait, so there might be interference with the dropdown menu instantiation? That sounds like something I should definitely fix. Would you mind opening a new issue outlining as precisely as possible what is happening, what should happen, and maybe a few other contextual info? Then I can have a look.

**Comment by mousetrappling** [comment]
No, sorry I was unclear.

You get a dropdown menu and can choose the file to link to just fine.  But with autosave set to "immediately" it doesn't matter what you have "When linking files, add the filename..." set to in your preferences, you will NEVER have the title/filename appended, you will ONLY get [[ID]].

What I was trying (unclearly) to suggest was that because one's autosave settings effectively override the option to add the filename/title to the ID link then you might want to note it somewhere in the manual or next to the option in the preferences dialog so that you don't as many bug reports.

**Comment by nathanlesage** [comment]
> because one's autosave settings effectively override the option to add the filename/title to the ID link

And that's precisely the bug, because that should not happen! What I was thinking earlier was that maybe just the file itself was not present, but if autosaving completely destroys the filename addition, that's clearly a bug!

Let me quickly reopen this …

**Comment by noah-arroyo** [comment]
Just in case it's helpful... I'll confirm that I'm experiencing this too. This bug has been around for a long time, but I never knew how to reproduce until now (with guidance from previous comments, here).

Link-name autocomplete reliably fails when a save instance occurs _while_ the link-selection dropdown menu is open.

**Comment by nathanlesage** [comment]
Found it ✌🏻
