### ISSUE TITLE
[Bug] Relative path logic not working for images using ../

### ISSUE THREAD

**Issue by Quantumrunner** [Zettlr/Zettlr#889]
## Description
I'm currently looking for a markdown tool for an open source project. Documentation for the tool is based on GitHub wiki pages. There are some people involved in the project which are not used to writing documentation in markdown and therefore prefer an easy to use editor.

Zettlr looks perfect so far but after a bit of testing I found a problem regarding image links.

GitHub Wiki Pages only allows rendering relative image pathes when using a _relative-indicator_ using two dots (../). But this does not seem to be supported in Zettlr currently. The tool recognizes the images but can't render them:

This

![grafik](https://user-images.githubusercontent.com/58113888/83973947-08b33f80-a8ea-11ea-99b6-127ee006bbad.png)

renders as:

![grafik](https://user-images.githubusercontent.com/58113888/83973953-1a94e280-a8ea-11ea-8e8e-c69cd3b423c2.png)

## Example Workflow
To solve this it would be perfect if Zettlr would also support a _relative-indicator_ using two dots to show images in the editor:

Example:

`![](../Images/Test.png)`

# Additional Information
Version: 1.6.0
OS: Windows 10 (Version 10.0.18362 Build 18362)

**Comment by nathanlesage** [comment]
Well, relative paths do work, which means if your use-case doesn't work it's a bug! I'll have a look into the algorithm!

**Comment by Quantumrunner** [comment]
Thank you for the quick feedback. I added version and OS information and updated the issue title.

**Comment by nathanlesage** [comment]
Ah, one more question: The devtools console should tell you which path Zettlr tried to parse (to open, activate Debug mode in the "Advanced"-Tab of the preferences, then menu -> develop -> Open DevTools, and there in the tab "Console")

There should be some error message ("Could not load image" or similar) with the path. Would you mind pasting it here? This would help me further verify this (because I just had a look at the code and it's clearly a logical error somewhere)

**Comment by Quantumrunner** [comment]
I have created a test using in a folder called `Markdown` which contains a file `test.md` and a subfolder `Image` (including the file `test.png`):

![grafik](https://user-images.githubusercontent.com/58113888/83979452-ab7db500-a90e-11ea-8667-3af049a568f0.png)

The path does not contain the parent folder name (`markdown`):

`file:///E:/Images/Test.png?1591561681291 net::ERR_FILE_NOT_FOUND`

`/E:/Images/Test.png?1591561681291` should be: `/E:/markdown/Images/test.png"`

**Comment by nathanlesage** [comment]
Thank you for clarification! I just had a look, and at least from the logic, it should work perfectly. But I may have just realized something (please correct me if my assumption here is wrong!)

Am I right to assume that the full path to your file is `E:/markdown/file.md`?

If so, then there might be an error in your syntax, because you put **two** dots in front of the path, which effectively means "traverse **up** one directory before following the rest of the path" — so, in case I am not mistaken here, the right path would only include **one** dot (`./Images/Test.png`).

But that's solely based on my assumption that your Markdown file resides in the folder `markdown` …

**Comment by Quantumrunner** [comment]
Yes you are correct. Everything is working fine in Zettlr. It was just the Preview window of the GitHub wikis that was behaving weird. Sorry to have brought this up!

Just one last question:
Is a similar dialog to the "Insert Image from Clipboard"-dialog available to choose an image from a project folder?

Using `Text Formats > Image` the image tag gets added but there does not seem to be any other ui-logic behind it.

![grafik](https://user-images.githubusercontent.com/58113888/84000070-40f76400-a964-11ea-8a19-702efe071d92.png)

Also adding images using drag'n'drop will always use the _absolute path_ of the image. I'm just thinking about the usability for the non-techies here.

**Comment by nathanlesage** [comment]
> Also adding images using drag'n'drop will always use the absolute path of the image. I'm just thinking about the usability for the non-techies here.

I think there's an other issue open here somewhere asking for that … somewhere

> Is a similar dialog to the "Insert Image from Clipboard"-dialog available to choose an image from a project folder?

This would be yet another feature

**Comment by Quantumrunner** [comment]
Thanks. Nothing to do here anymore.

I'll open a new feature request for the latter one.
