### ISSUE TITLE
[ENHANCEMENT] Offer Windows ARM builds

### ISSUE THREAD

**Issue by smitec** [Zettlr/Zettlr#890]
## Description

I had expected the installer to install a 32 bit version based on the download link title but it seems it installs the 64 bit version even on ARM. This results in a windows error on opening "This app can't run on your PC".

## Reproducing

Run the latest installer on an ARM based windows device. Tested with the latest stable and beta.

## Expected behaviour

Installer should detect the architecture and install the 32 bit version until an ARM build is available.

## Platform
 - OS and version: Windows 10 Home V2004
 - Zettlr Version: 1.6.0 & 1.7.0-beta.9
 - Screen Resolution: 2880x1920

**Comment by nathanlesage** [comment]
As far as I know this is not an issue of 32/64 bit. Rather, the windows installer expects an x86-processor, not a RISC ARM. Zettlr currently does not have a build target for Windows ARM.

**Comment by smitec** [comment]
I could be wrong on this one. Was based on:
64-bit (x64) apps won’t work. You'll need 64-bit (ARM64) apps, 32-bit (ARM32) apps, **or 32-bit (x86) apps. You can usually find 32-bit (x86) versions of apps**, but some app developers only offer 64-bit (x64) apps.

https://support.microsoft.com/en-us/help/4521606/windows-10-arm-based-pc

**Comment by nathanlesage** [comment]
> 64-bit (x64) apps won’t work. You'll need 64-bit (ARM64) apps

Here you have the answer: Both x86 cores and ARM64 cores support 64bit, but the one is an extended instruction set (hence x86), whereas ARM-cores ship with a reduced instruction set. I'm no expert on that, but that's basically the problem here …

If enough users say yay, I might add the build target in the future, but not without someone testing this out first :)

**Comment by nathanlesage** [comment]
> If the installer contains both a 32bit and a 64bit version, then the problem is with the installer not "knowing" that it should install the 32bit version of Electron.

Precisely. And I think this is something Windows should address, because I can fully understand that an installer that ONLY sees "Aha, 64 bit" will not check "Aha, but it's ARM, so I'd cleverly have to install my 32bit version, hehe!"

And yup, can confirm, apparently [there's only a hack](https://medium.com/@h.hocine.abdellatif/electron-builder-create-separate-32-and-64-bits-installers-for-windows-77d12184c0ac) which I won't implement.

***

But, why do we even have this discussion? [Electron supports building for Win ARM](https://www.electronjs.org/docs/tutorial/windows-arm), so let's just keep it short, implement that and be done with it, what do you say?

**Comment by smitec** [comment]
An ARM build would work for me

**Comment by Jaifroid** [comment]
I agree that an ARM build is an optimal solution. It's just a case of adding another build target to the manifest, no?

**Comment by nathanlesage** [comment]
> I agree that an ARM build is an optimal solution. It's just a case of adding another build target to the manifest, no?

As long as electron builder doesn't do something weird, yes!
