### ISSUE TITLE
Table Editor not working with Linux

### ISSUE THREAD

**Issue by treborxy** [Zettlr/Zettlr#897]
## The Tableeditor neither renders exsisting markdown-tables nor the "insert new table" function works

**Screenshots**

![zettlr](https://user-images.githubusercontent.com/19653937/84020865-da823e00-a983-11ea-91c0-1f76f9adfed4.png)

## Platform
 - OS and version: Linux elementary OS 5.1.5 Hera (Auf Basis von Ubuntu 18.04.4 LTS, Linux 4.15.0-101-generic, GTK 3.22.30)
 - Zettlr Version: 1.6
 - Screen Resolution: 1920x1080

**Comment by nathanlesage** [comment]
The table editor doesn't render the existing table, because the link rendering module has precedence (FIRST Zettlr attempts to render links, SECOND it attempts to render the table)

Simple mitigation: Disable link previewing for now, or make sure they're not within a table in order to use the TableEditor. The issue at hand is the order of plugins to load, but that's quite a different story …

**Comment by treborxy** [comment]
Not sure if the bugreport wasn't closed too early...

- The first issue ("exiting table will not be rendered") can't be mitigated by disabling link previewing, at least not in my case. It does not render - any other idea?

- what about the second issue ("Table editor does not work", see the screenshot given) ? Could you pleasengive a hint how to avoid this (or at least how to give some information that helps you to understand what happens)?

**Comment by nathanlesage** [comment]
Ehm, it might very well be that both issues are connected. I just changed the order of rendering, now Table has a much higher priority, and maybe the second issue resolves … I'll be releasing a beta this evening, please feel free to check it, and if it does not mitigate the error, please comment again!
