### ISSUE TITLE
Feature Request: Open Editors, like Visual Studio Code

### ISSUE THREAD

**Issue by sahil48** [Zettlr/Zettlr#9]
https://code.visualstudio.com/docs/getstarted/userinterface#_open-editors

Useful for keeping documents regularly edited available for easy access. I would prefer that it be a separate section above the preview pane, so that you can scroll through open/pinned documents and the preview pane separately.

**Comment by nathanlesage** [comment]
Puh, I've deliberately not implemented a tabbed view and instead a file tree, because I'm not such a fan of tabs when writing academic texts. But I get the surplus of your thought.

The thing that I fear would be that this might be "too much" functionality, to basically have two panes that do the same :/

**Comment by sahil48** [comment]
I'll reply to this in a separate post.
