### ISSUE TITLE
Navigating around the app with keyboard not working as expected

### ISSUE THREAD

**Issue by cognociente** [Zettlr/Zettlr#907]
## Description

New Zettlr user here. Looks like very interesting software. Well done.

I went to the keyboard shortcut page for Zettlr to learn how to navigate my way around and certain of these keyboard shortcuts (unfortunately imprtant ones IMHO) are not working for me: 

Certain keyboard shortcuts do not work
(1)
Control+w: does not close the active file

(2)
Arrow up & down in the file list does not do anything: I would expect that it would select the next file and display it in the text editor

(3)
Control+Shift+t: does not switch to the file pane when I am in the note editing pane

(4)
After I search in the global search box and the file list is narrowed, there seems to be no key I can press (the down arrow would be great) that would allow me to navigate between the filtered list of files such that I can see which one I would want to edit?

NB: lots of the keyboard shortcuts do work for me.

## Expected behaviour

Covered above.

**Screenshots**

## Platform
 - OS and version: Windows 10 18363
 - Zettlr Version: 1.6 (latest stable)
 - Screen Resolution: 3840 x 2160 (@175%)

**Comment by nathanlesage** [comment]
Hey, thanks for the issue! The shortcut section is already up to date with the shortcuts that will come in 1.7, but unfortunately, the beta is dragging around a little bit longer than we originally anticipated, which is why there is this gap. If you would like to use the new shortcuts, feel free to switch to a beta-version! They can be downloaded from the releases page here on the repository!

If then something doesn't work, make sure to check out the already existing issues! I hope that helps! Glad to have you on board :)
