### ISSUE TITLE
Place the picture automatically when rendering a project

### ISSUE THREAD

**Issue by ploum** [Zettlr/Zettlr#917]
Currently, when rendering a project, pictures are placed at the exact place they were placed in the MD file.

This is of course useful in lot of cases.

But there are also lot of cases where you want the picture to be placed at the "best" place (like Latex does).

According to our discussion on Twitter, this is currently possible but it is not really clear how.

**Comment by nathanlesage** [comment]
I do remember very vaguely that there is a way to accomplish that in LaTeX, but this would require a somewhat modified template. Currently, Markdown image tags are converted to LaTeX commands that … puh, are somewhat (?) defined by Pandoc, and these commands need to be somewhat modified in the template in order to achieve this.

I'm neither an expert on LaTeX, nor do I think that this is an issue that specifically applies to Zettlr. Nevertheless, as I said back on Twitter: What would be ideal is if you could experiment a little bit with the template (that is, download the Zettlr default template, and in the PDF preferences point Zettlr towards this, and then modify it to see what happens). If you find out any improvements to the current default template (always remember: The default template is supposed to work out of the box, which means: No special cases, no fancy stuff that cannot be counted as "common sense"), please feel free to share them in that case!

**Comment by nathanlesage** [comment]
There was a PR that changed image placement, so maybe this fixed it — if not feel free to comment!
