### ISSUE TITLE
Markdown File preview

### ISSUE THREAD

**Issue by luapy** [Zettlr/Zettlr#925]
## Description
Hi~ I am accustomed to see both markdown gramme view and markdown Preview without gramme code,So I hope splite it with two alone windows inside the application instead of put all of them in only one window,Beacause it's look confused.

## Proposed Changes
I hope Zettlr can add a new preivew mode that can choose  have two alone windows ,one of them is a markdown gramme view window and  the other one is a markdown Preview without gramme code window. Plz~ :)

**Comment by nathanlesage** [comment]
Hey, thanks for your issue! But unfortunately, this would run counter to Zettlr's philosophy. Basically, there are three kinds of Markdown editors: Those with two separate windows with preview, WYSIWYG-editors (such as Typora), and WYSIWYM-editors like Zettlr, that renders some elements in place, but keeps preview hidden until you need it, in order to force you to focus on the text you write.

Adding a split preview pane would therefore introduce an element into the editor that would counter the WYSIWYM-idea of Zettlr, and henceforth this is not possible :/

I hope that this is not a complete dealbreaker for you, glad to have you on board! 🚀 

***

_(As a sidenote: By pressing `Ctrl/Cmd+P` you can from time to time open up such a preview window to preview your content, maybe this is a compromise that works for you?)_

**Comment by scapoor** [comment]
@nathanlesage Can you make the WYSIWYM-Editor of Zettlr as a setting?
Even though it's good but since it renders "in-place", as we type, it gets a lot distracting. (Quite a deal breaker, when the rest of the product so good).

If this would be a setting, it would allow people to toggle Zettlr as the WYSIWYM-editor or normal mode (no rendering, simply like notepad or vscode or vi ..etc.).  

Having both modes would definitely improve this tool for people who prefer simpler editors and who like what's currently in place..

So by default you can enforce WYSIWYM-editor mode and people will use it but people who find it distracting or simply wants something simpler, they would have an option to use it as a simple editor (**```cmd/ctrl+p```** can be used to check the final results as needed - _**No need for the split preview pane if you didn't foresee it in the product.**_)  but having the content rendered in place is a lot distracting when you have a few headings, sub-headings and mixed content.

I feel that having this as an option would be a win for the product's philosophy and a lot of user's use cases.

Hope you would consider this request.

**Comment by nathanlesage** [comment]
> If this would be a setting, it would allow people to toggle Zettlr as the WYSIWYM-editor or normal mode (no rendering, simply like notepad or vscode or vi ..etc.).

It is a setting. In the preferences -> Display you can select which elements Zettlr will pre-render. Deactivating all means you get only syntax highlighting, no pre-rendering, just as you described.

**Comment by scapoor** [comment]
@nathanlesage Either something is wrong with my installation or it isn't working properly. Because I have those disabled from my first installation but still it's rendering headings , links, tables ..etc even though all the settings are disabled. Maybe those elements are not available as settings or something is broken. (Tested on 1.7.0 Beta as well as the latest stable version).

The reason for this request is not just the distraction free work but also this works perfectly on smaller screens as well as when you have multiple windows opened. (Simple text don't take any space and you don't have to scroll up/down but partially rendered/fully rendered text do.)

Please check the screenshots.
I would prefer the VSCode like editing as it's simple.
![Zettlr_0SGTfXm0Lv](https://user-images.githubusercontent.com/42283188/84803265-66990300-b01f-11ea-85ae-9c0a8b4907e8.png)
![Zettlr_qtb1N9BxHJ](https://user-images.githubusercontent.com/42283188/84803267-67319980-b01f-11ea-9d41-ff16ca0bdc6e.png)

The below screenshot is what I'm referring to. 
![Code_ovfAfVT3Kg](https://user-images.githubusercontent.com/42283188/84803270-68fb5d00-b01f-11ea-949d-a4217f114e48.png)

**Comment by nathanlesage** [comment]
The tables are rendered by the TableEditor (Preferences -> Editor, and not Display), so that's where this comes from.

It might help to close and re-open the affected file. I can't reproduce this here.

**Comment by scapoor** [comment]
@nathanlesage TableEditor was already disabled in my settings but still had this issue. Closing and reopening file(s) had no effect.
I tested it again after reinstalling today. Same issue, currently on the 1.7.0 beta. 

Aside from tables (which don't have much use case for me), can you do something for the headings atleast (**something as simple as the last screenshot - no rendering of any kind, no change in font size due to rendering**)?

If you are not able to reproduce the heading problem or the heading issue is only on my system, **can you send a screenshot of how your markdown file looks like (with headings, tables ..etc or use my template attached below)** with all rendering disabled?
I just need a frame of reference whether the issue is with my installation or not.

Template: 
[20200609232220 - Example Template for Zettelkasten Notes.txt](https://github.com/Zettlr/Zettlr/files/4788470/20200609232220.-.Example.Template.for.Zettelkasten.Notes.txt)

**Comment by nathanlesage** [comment]
> no change in font size due to rendering

This is a case for Custom CSS.

![image](https://user-images.githubusercontent.com/17251683/84825711-24bd8c00-b022-11ea-879d-33fac58b735f.png)

This is how it looks locally for me (using Bordeaux theme, everything rendering disabled) — so just the different font size for the headings remains, which, as I said, can be addressed using Custom CSS!

Just in case: Do you use the LATEST beta? There've been quite a few, unfortunately, due to several unexpected bugs …

**Comment by scapoor** [comment]
> > no change in font size due to rendering
> 
> This is a case for Custom CSS.

Thanks. I'll fix it using custom CSS.
> 
> ![image](https://user-images.githubusercontent.com/17251683/84825711-24bd8c00-b022-11ea-879d-33fac58b735f.png)

Thanks for the attachment.
> 
> This is how it looks locally for me (using Bordeaux theme, everything rendering disabled) — so just the different font size for the headings remains, which, as I said, can be addressed using Custom CSS!
> 
> Just in case: Do you use the LATEST beta? There've been quite a few, unfortunately, due to several unexpected bugs …

Using the latest beta 1.7.0-beta.11.

**Comment by scapoor** [comment]
@nathanlesage Fixed the issue, thanks for helping.

**Comment by nathanlesage** [comment]
Perfect, glad it worked out!
