### ISSUE TITLE
Notes in inactive tabs are not auto-saved

### ISSUE THREAD

**Issue by Zverik** [Zettlr/Zettlr#929]
1. Make a change in a note.
2. Switch to different tab.

Expected: the asterisk in the tab title disappears in a few seconds.

Result: after a minute, the note is still unsaved.

_Zettlr 1.7.0-beta.11 on macOS 10.14.5_

**Comment by nathanlesage** [comment]
This is because the timeout only attempts to save the currently active file. I've noticed, but didn't bother, and currently I actually use this behaviour as a way to debug some parts of the app, because this way I can quickly check what Zettlr does when there are unsaved changes.

It's the little brother of rubber-duck debugging: Keeping bad behaviour because it's the only reproducible thing in the whole new feature 🙃

**Comment by Zverik** [comment]
Is it currently hard to save a note when a user switches to another tab?

**Comment by nathanlesage** [comment]
> (I understand it's useful for debugging, but it can be unexpected when you release the final 1.7.0)

Absolute, you're right, and therefore I need to fix this beforehand! I still hope that we're able to fix that one bug, so that I have the motivation to do another, final round of bug-fixing before we can finally make it to 1.7!

**Comment by Zverik** [comment]
Cool, thank you!
