### ISSUE TITLE
Hide heading characters

### ISSUE THREAD

**Issue by SSLPP** [Zettlr/Zettlr#931]
## Description
Headings rendered are not justified when the 'Hide heading characters' is on (Display/Hide heading characters)

**With hide heading option off:**

![image](https://user-images.githubusercontent.com/42621751/84730356-cf627b80-af4a-11ea-85eb-93dd4c04e9f3.png)

**With hide heading option on:**

![image](https://user-images.githubusercontent.com/42621751/84730335-beb20580-af4a-11ea-9563-01edb21366ea.png)

## Expected behaviour

Desired:
![image](https://user-images.githubusercontent.com/42621751/84730235-798dd380-af4a-11ea-9415-b07eddef0c92.png)

## Platform
 - OS and version: Win 10
 - Zettlr Version: 1.7.0-beta11 
 - Screen Resolution:

**Comment by Amar0ks** [comment]
Have a look at this discussion here: 
[Reddit - hide the markdown syntax? ](https://www.reddit.com/r/Zettlr/comments/g17y4k/is_there_a_way_to_autohide_the_markdown_syntax/)

But a proper option would be nice.

**Comment by nathanlesage** [comment]
Well, there's the experimental WYSIWYG-plugin which you can activate by typing `renderer._editor._wysiwyg = true` into the dev console, but this is not, and probably will never be fully supported, because I've finally settled that full WYSIWYG will not come. Zettlr should keep it with WYSIWYM, that is, never completely hide everything; always display as much information as necessary so that everyone always has a clear idea what is going on.

However, that being said you could set the width of the heading-indicators to zero pixels, if you'd like to hide them completely:

```css
body .heading-tag {
    display: none;
}
```

You'd have to turn the "hide heading characters" option on in the settings for this to work.

**Comment by chchen2021** [comment]
@nathanlesage I find it much easier to continue on an existing discussion (that has clear screenshots), but do let me know if I am not supposed to comment on a closed issue.

I have a suggestion that would keep the WYSIWYM design choice but also improve the readability. Can you move the heading-level indicators `##` or 'h2' to the left of the body text, so that the actual heading is aligned with the body text? 

In some cases, WYSIWYM has an advantage over WYSIWYG, especially with the extra option to "hide heading characters". However, I think the misalignment defeats the purpose of replacing `##` with `h2` in the example cited in this discussion thread. Simply moving `##` or `h2` to the left would make the hiding more useful and the text more readable.

**Comment by nathanlesage** [comment]
> Can you move the heading-level indicators ## or 'h2' to the left of the body text, so that the actual heading is aligned with the body text?

Unfortunately not with the current CodeMirror implementation

**Comment by chchen2021** [comment]
@nathanlesage In that case, the hashtags themselves are pretty good indicators of the level of heading. They use the same font size as the actual heading and are much less distracting than the half-sized "h1", "h2" indicators, which I need to click on to edit anyway. That said, I have another recommendation. 

I am regularly using about half a dozen markdown editors. Among them, Zettlr is my top choice if I am dealing primarily with texts (instead of equations). I agree with the vast majority of the WYSIWYM design choices, including the decision not to offer a live preview, but I am not really getting the current option to "hide heading characters".  I honestly cannot imagine myself using this option for any writing because the formatting is so oddly distracting. 

If Zettlr finds it fitting to render tasks, links and formulas, why not render the headings properly? The headings are the most information-rich components of any writing. If the visible hashtags are included by default, and a user has to click an option to "hide hashtags", I think it is a reasonable option to make the headings free of hashtags but clickable to reveal the hashtags. After all, it takes the same amount of work to click "h1" or (as proposed) to click the actual title to reveal the hashtags, but the option I am proposing looks much cleaner.

**Comment by nathanlesage** [comment]
Hm. That sounds like an idea worthy of discussion. Feel free to open a discussion and then we'll see how it turns out! :)
