### ISSUE TITLE
Issue with using Zotero library

### ISSUE THREAD

**Issue by BenjGH** [Zettlr/Zettlr#934]
## Description

Zettlr has issues to use my main ZOTERO library. It always says: "Could not update bibliography!" in German it is: "Beim Erstellen der Bibliographie ist ein Fehler aufgetreten". I tested to connect another smaller library, which works perfectly fine. So the problem lays probably in my ZOTERO database. What could it be?

## Reproducing
Open Zettlr. Create a citation via "[@.....]"

## Expected behaviour
Open a drop down menu to choose a library item for citation

**Screenshots**

<img width="1828" alt="Bildschirmfoto 2020-06-16 um 12 14 14" src="https://user-images.githubusercontent.com/66998849/84762408-1001d980-afcb-11ea-87d0-5e420c516114.png">
<img width="1626" alt="Bildschirmfoto 2020-06-16 um 12 15 02" src="https://user-images.githubusercontent.com/66998849/84762417-11cb9d00-afcb-11ea-857d-1c3fbfd5401e.png">

## Platform
 - OS and version: macOS Catalina, 10.15.5
 - Zettlr Version: 1.6.0 (1.6.0)
- Zotero Version: 5.0.88

**Comment by nathanlesage** [comment]
Hey, thanks for notifying!

Would you mind checking the logs for any information that might be relevant for this issue? Here's how you find the logs:

## If the error just occurred

The easiest way to retrieve logs is to wait for the error to occur and then immediately check the logs within the app. To do so, follow these steps:

1. Ensure the "debug mode" is active (Preferences -> Advanced -> Debug mode)
2. In the "Develop"-menu item, choose "Open Logs"

## If the error occurred and you already closed the app

After you quit the app, Zettlr will save the collected logs to disk. You can find them …

* On Windows: `C:\Users\<your username>\AppData\Roaming\zettlr\logs`
* On macOS: `/Users/<your username>/Library/Application Support/zettlr/logs`
* On Linux: `/home/<your username>/.config/zettlr/logs`

They are named after the day where they were created in the format `yyyy-mm-dd.log`

> So the problem lays probably in my ZOTERO database. What could it be?

This is something that will be fixed by Zettlr 1.7, as we have significantly improved error handling on malfunctioned citekeys. One of the **most common errors** we have encountered across various bug reports were malformed **date parts** if there are unidentified date-informations saved. Normally, you can check whether Zotero successfully detected a date in such a field by checking if there are grey markers next to the input field:

![image](https://user-images.githubusercontent.com/17251683/84763773-04afad80-afcd-11ea-95c8-32732c0ea840.png)

**Comment by BenjGH** [comment]
Thanks for your quick response, Hendrik! Here are some screenshots of the log after the occurrence. Do they contain the information you need?

<img width="1138" alt="Bildschirmfoto 2020-06-16 um 16 16 23" src="https://user-images.githubusercontent.com/66998849/84786625-4bad9b00-afed-11ea-9104-3aad45f95b72.png">
<img width="2048" alt="Bildschirmfoto 2020-06-16 um 16 18 19" src="https://user-images.githubusercontent.com/66998849/84786661-5405d600-afed-11ea-8a0f-9c0fbf207ad4.png">

**Comment by nathanlesage** [comment]
Yes, as I suspected, the four red lines in the second screenshot indicate what I feared: There's some date field in one or two of your citekeys mismatching. Maybe the arrow on the right-hand side of the log window can show you which one it is (1.6 was so long ago I've forgotten how the code looked back then). In any case, if it doesn't yield the necessary citekeys, I'd recommend you switch to the 1.7 betas, because there an improved logging is included which'll tell you with which citekeys there are problems!

I hope that we'll be able to ship 1.7 stable soon so that this kind of guessing which one it is will come to an end! :)
