### ISSUE TITLE
[ENHANCEMENT] Enable access to LaTeX header to use individual packages

### ISSUE THREAD

**Issue by PhilHem** [Zettlr/Zettlr#935]
## Description

I'd very much like to have access to the header that defines the packages that can be used within Zettlr.

## Proposed Changes

Similar to the css-manipulation window, there could be a latex-manipulation window. 

## Additional Information

It would be very nice if this was possible. I have a few LaTeX packages that implement symbols I would love to use, but they certainly are not necessary for everybody. A solution where I could simply enter `\usepackage{xyz}`, for it to get added to the header would be neat!

**Comment by nathanlesage** [comment]
Good thought! Albeit we already do this: You can simply insert a custom template that'll be used instead of the official one.

Due to some yadda yadda with LaTeX and that some packages override commands by other packages etc. I don't think it's a good idea to *only* give access to the header of the template.

Instead, I'd recommend [downloading the official template](https://github.com/Zettlr/Zettlr/blob/develop/source/main/assets/export.tex) (and from time to time updating it if something doesn't work) and adapting that one as much as you like!

The included template is only meant for basic exporting — as soon as you need more fancy stuff, it's almost always a good idea to simply provide a custom template. This is the good thing that Zettlr relies upon Pandoc for this: The internet is already full of compatible templates that can be used in conjunction with Zettlr for that very reason :) (e.g. [Eisvogel](https://github.com/Wandmalfarbe/pandoc-latex-template))

But, it might very well be that the docs don't express that very well (so if you have some time at hand, I'd be glad if you could help out by making it more verbose in this respect!)

**Comment by PhilHem** [comment]
Oh, I am not talking about the LaTeX export, I'm talking about the rendering within Zettlr. Could you maybe point me to the file in which these packages are defined? I'll gladly play around with it myself :)

**Comment by nathanlesage** [comment]
> I'm talking about the rendering within Zettlr.

But … the rendering does not have anything to do with the LaTeX directives o_O I'm not sure I understand what you mean

**Comment by PhilHem** [comment]
well if I enter for example `$\begin{cases}\end{cases}$`, it clearly uses the LaTeX `amsmath`package to render the cases within Zettlr, doesn't it? My line of thought is, that somewhere it is defined to use `amsmath`. Whereever this is defined, I'd like to add some other packages for myself.

**Comment by nathanlesage** [comment]
Ah, yeah, that's defined in KaTeX. Have a look at this PR for further development: #642
