### ISSUE TITLE
Enhancement: Only change cursor over internal elements while the Alt-Key is pressed

### ISSUE THREAD

**Issue by jeverettm** [Zettlr/Zettlr#94]
## Description
Left clicking on internal links does not open matching note.

## Reproducing
I am using the recommended Zettelkasten set-up as directed on the website. The first file has an id generated by Zettlr using standard 14 character string (in this case: 20190207071706). The id shows up in the snippet for this file, so I assume it is formatted correctly and matches the regex. In the body of a second file, I placed an internal link referring to the first file. It looks like [[20190207071706]]. When I hover over this number the mouse pointer changes to a hand, but when I left-click, nothing happens. 

## Expected behaviour
My expectation was that left-clicking on an internal link would open the file with the matching ID. Zettlr does find the note if I use an alt-click, but this also filters the contents of the sidebar, which I would not want to happen every time I jump to another note.

## Platform
 - OS: Windows 10, Version: 1803, Build 17134.523
 - OS: Windows 8, Version: 6.3, Build 9600
 - Zettlr Version: 1.0.0

**Comment by nathanlesage** [comment]
Hey, thanks for your notice!

That you have to `Alt-Click` the files is by design, because this way you can easily click into any element without triggering any action. This prevents you from, e.g., accidentally opening files when you simply wanted to edit the links to those files.

Concerning the searching of the file list, this is also by design so that you can easily see what other files link to the file you just opened. This is essentially useful for generating knowledge after a certain amount of time when you already forgot which files you linked to which others!

If you don't want the filtered sidebar, you can easily exit the search by clicking the `x` in the global search field or focusing it and pressing `ESC`!

**Comment by jeverettm** [comment]
Ok. I see your logic and agree. It makes sense for a click in the editor to move the cursor rather than jump to a note. I guess I expected something to happen because the mouse pointer changed when I hovered over the ID? Is it possible to have the pointer change only after the Alt key is pressed? 

Also, for me on windows, pressing ESC doesn't clear the search unless my cursor is in the search box. So I have to move the mouse up there and clear it. Not a big deal, but if I'm wanting to toggle between a bunch of notes, having to go up and clear the search box each time will get annoying after a while.

I don't mean to complain too much. I've been looking for Zettelkasten software and I like the clean simplicity of what you've created. Thank you for putting your work out there!

**Comment by nathanlesage** [comment]
> I guess I expected something to happen because the mouse pointer changed when I hovered over the ID? Is it possible to have the pointer change only after the Alt key is pressed?

This is indeed a very good idea, because here I see what the natural assumption is. CodeMirror somehow manages to alter the cursor only while pressing the `Alt`-key, so I'll look into it!

> Also, for me on windows, pressing ESC doesn't clear the search unless my cursor is in the search box.

That is the same on all other operating systems. I cannot listen for the `ESC`-key being pressed globally, because this might mess with other things (you probably don't want your search cleared if you close the find-popup using the Escape-key). But as a shortcut: You can always jump to the global search by pressing `Ctrl+Shift+F`, so this might be a shortcut to focus the searchbar before pressing Escape. If you happen to have an idea of how to mitigate this further, I would welcome this!

> I don't mean to complain too much. I've been looking for Zettelkasten software and I like the clean simplicity of what you've created. Thank you for putting your work out there!

Don't worry, these are valid concerns and you are very polite, so it's all good! After all, I depend on such "usability-reports" because I can only talk for one single workflow out of many — my own. So every person that brings forth issues concerning the user interface (or, for that matter, other feature requests, obviously) helps in making Zettlr an app that manages to fulfill all our needs to the best of its capabilities! :)
