### ISSUE TITLE
Include non-in-line references with Zotero

### ISSUE THREAD

**Issue by keikhcheung** [Zettlr/Zettlr#940]
## Description
Not sure if this is an enhancement request, a feature request or a bug.

Is there a way to cite with Better BibTeX and Zotero while not having making in-line citation? Like if I just want to include the full citation at the bottom of the page when I export the note in PDF but not having mentioned the item in the body text?

I looked up the [Pandoc documentation](https://pandoc.org/MANUAL.html#citations) and it said it could be achieved by adding in the front matter metadata as:

```
---
nocite: |
  @item1, @item2
...
```

But somehow I still couldn't get it to work on Zettlr. Either the entire front matter section will be rendered as a code block on PDF export, or `@item1` and `@item2` would be treated as in-line citation together with the front matter as normal body text.

Is there a way to omit the metadata in PDF export while having the `@Citekey` item included in the reference list?

## Proposed Changes
Add non-in-line citation with BibTeX if this has not been a feature.

**Comment by nathanlesage** [comment]
Just to get you right:

* You have a frontmatter with the `nocite`-property.
* Your intention is that these citekeys are cited in the references albeit they do not occur in the text
* They are, in fact, not rendered in the references, albeit intended?

Or is the problem that Zettlr attempts to render citekeys in the frontmatter?

**Comment by keikhcheung** [comment]
Yes, to the first two points.

It was yes to the third point as well. But then I was writing my reply and wanted to include some screenshots to better explain it, and all of a sudden… it works! Very bemused. (It didn't work last night and I dug online for so long to try to find a solution…) I can't believe my eyes. Sorry for the confusion.

**Comment by nathanlesage** [comment]
Don't worry! I am pretty sure this won't work right now as well, because the _references_-section of Zettlr doesn't scan for standalone "nocite"-thingies. BUT I am open to adding that behaviour after 1.7, because right now I just want 1.7 going :D 

So feel free to add the `nocite`-property to the discussion once it gets around supporting more YAML frontmatter vars!

As for now: Your exports will work fine, because Pandoc will do that and hence care for respecting the `nocite`-property. It's, therefore, only a matter of visuals!
