### ISSUE TITLE
[ENHANCEMENT] Shortcut "Hide side bar"

### ISSUE THREAD

**Issue by PhilHem** [Zettlr/Zettlr#943]
Just checked the new .12 Beta and saw that now commit #edbe0fb now hides the the tab bar in distraction free mode. 

I find it very helpful to not see the sidebar, but still see the tab bar.  With commit #edbe0fb, I can't use distraction mode for that now. 

I see two solutions:
1. Make hiding the tab bar for distraction free mode optional
2. Create a shortcut that hides the side bar

I'd be happier with the second option, also because it's less cluttered. 

# Additional information

My main problem is that I need to be able to see the save status of notes because it still messes with the creation of new notes. I'll open another issue for that.

**Comment by nathanlesage** [comment]
> Make hiding the tab bar for distraction free mode optional

Simply use Custom CSS to prevent the editor from dropping over the tab bar, and it'll be all good. This basically involves undoing the changes in mentioned commit. There are way too many people who even want the toolbar gone, which is why their preference gets priority in this case. Implementing a setting to steer this is unfeasible at the moment.

**Comment by PhilHem** [comment]
@nathanlesage 
Sure! I'd be happy with that. 

I've been messing with the css a little bit, but I can't seem to make it the way I want it. Could you possibly pass the me right css to revert this?
