### ISSUE TITLE
[ENHANCEMENT] Enable more mermaid.js functions

### ISSUE THREAD

**Issue by PhilHem** [Zettlr/Zettlr#954]
Been experimenting a little with mermaid and I really like it! Unfortunately, some of the functions that the current mermaid version allows are not available in Zettlr. I suspect this to be a problem with an older version of mermaid. Can this be confirmed?

**Comment by nathanlesage** [comment]
As long as they didn't suddenly include a bunch of features since the `8.0.0` (current is `8.5.0`), it's certainly not because of an older version.

**Comment by PhilHem** [comment]
Well, there are a lot of things, like different node shapes, new diagram forms and so forth that were introduced. They don't currently seem to work. Examples are stadium shaped nodes, ER-Diagrams etc.

**Comment by nathanlesage** [comment]
Well, then it's a matter of updating mermaid.js, which should fix these things. But not for 1.7, because I've had my fair share of negative experiences with updating dependencies shortly before a release :D 

But I will immediately update all dependencies (including mermaid) once 1.7 has been released, so that they will ship in 1.7.1. If then something else is missing, feel free to open up specific issues! But please be patient until after 1.7.1! :)
