### ISSUE TITLE
Global search inconsistent text selection

### ISSUE THREAD

**Issue by andersbetner** [Zettlr/Zettlr#958]
## Description
When using global search with  ⌘-⇧-F the text in the search field gets selected. If I release the keys in the wrong order the text is deselected.

### Not working
1. Type some text in the global search filed.
2. Edit some text in a note.
3. Hit command-shift-F
4. Release "F", release command, release shift. The text is deselected.
### Working
1. Type some text in the global search filed.
2. Edit some text in a note.
3. Hit command-shift-F
4. Release "F", release shift, release command. The text remains selected.

It is a bit flaky, so the above is not always true.

## Expected behaviour
No matter how i release the keys in 4. the text should remain selected until I type my first character in the field.

**Screenshots**

## Platform
 - OS and version: OSX 10.15.5
 - Zettlr Version: 1.6.0
 - Screen Resolution: 1920x1200

**Comment by nathanlesage** [comment]
> If I release the keys in the wrong order the text is deselected.

I just tried this like fifty times with different ways of releasing keys but could not a single time reproduce this. Nevertheless, this might very well be a bug with 1.6, which will get superseded by 1.7 on Friday (where I just tested it, and it works) — if it does not work in 1.7, please comment here so that we can re-open the issue for the 1.7 release after that!
