### ISSUE TITLE
[FEATURE] Zettelkasten Index Creator

### ISSUE THREAD

**Issue by amirography** [Zettlr/Zettlr#959]
## Description
It would help a lot to have a feature in which, you could make a list of selected notes (using their zettelkasten link) and copied to your clipboard.

## Example Workflow
So, as an example, I have a couple of notes, each note about a friend of mine. I want to make a an index file out of these notes. 
**First**, I select a couple of notes using the sidebar
![2020_06_29__14_39_56_](https://user-images.githubusercontent.com/28535608/86046630-cc937a80-ba62-11ea-8e6a-008d078532e9.PNG)
**Second**, I would right-click on these selections and select the "copy list" button (imagine it is there)
![2020_06_29__14_40_27_](https://user-images.githubusercontent.com/28535608/86046791-167c6080-ba63-11ea-9809-50933b0ada21.PNG)
**Last**, I will create a new note, and paste it there. 
![2020_06_29__14_39_20_](https://user-images.githubusercontent.com/28535608/86046863-36138900-ba63-11ea-9a81-526da2706695.PNG)

This can also help organize notes, taken from different classes. Using time stamps and tags may cause a lot of mayhem when your notes are inconsistent and you gather others' notes. 

## Caveats
I have no idea if it does affect any other functionality. 

## Additional Information
**Z**ettlr **<3**

**Comment by nathanlesage** [comment]
Ouh, interesting idea. This might be easily possible once we have multi-selections (right now the renderer only allows one single selection, but I already put in place some gears behind the scenes so that we can easily add multi-selections at a later point), because then we can do a bunch of stuff like moving _all_ selected files at once, deleting all at once, maybe renaming (to finally welcome the dreaded `(1) ... (143)`-name additions to the party) and in general performing stuff.

**Comment by amirography** [comment]
Yeah, I guessed that the multi-selection component is a prerequisite. I just thought once (and if) the wheels of adding that feature started rolling it would be easy to add this feature as well, while in the role. Thanks a lot!

**Comment by daltroaugusto** [comment]
I think this would be useful.

**Comment by recluse099** [comment]
what happened to this? Was an auto-index generator created for zettlr?
