### ISSUE TITLE
List issue [Feature Request]

### ISSUE THREAD

**Issue by subi54** [Zettlr/Zettlr#96]
Possibly a bug report, otherwise a feature request. I think it's the latter.

Lists work fine as long as they are like this:
```
* one
* two
```
or
```
1. like
2. this
```
But if you try to put line breaks, they break. [possible bug]

I have long notes of reading lists that go like this:
```
1. [title](link) by [author](link)
03 (< chapter no.) `#tag` (< tags like `#reading`, `#dropped` or such complete with spaces between the paragraphs)
Summary (which can be a paragraph or two with spaces between the paragraph)

1. 
```
 Each of these kind of lists have from 1-300 items. Have more than 100+ lists.

Would it be possible for the render-er to render `1.` in the beginning of the line as a ordered list numbers? Like you did with headings, it shows as `1.`, `2`, `3`... but it actually is `1.`, `1.`, `1.`.

**Comment by nathanlesage** [comment]
Errrm … I'm not quite sure I understand what you mean.

So, if you export your above code, you have the following output, which is, according to the specification, correct:

![image](https://user-images.githubusercontent.com/17251683/52474527-06778e80-2b99-11e9-96e1-4636d6e340e3.png)

If you mean the rendering directly within the app — I think this ain't possible so easily. As Markdown is a source file, after all, even the rendering of all the elements that Zettlr renders is somewhat a "violation" of that principle. So I think manually inserting numbers `1.`, `2.`, `3.`, etc is the best practice!

**Comment by subi54** [comment]
![zetllr2](https://user-images.githubusercontent.com/8841727/52474983-1060b800-2bc0-11e9-8195-16cb25552b4f.png)

I already insert `1.`, `1.`, `1.` manually. I thought the app might just layer a virtual ordered list over it. Like `h1` is shows over `#`.

**Comment by subi54** [comment]
![qownnotescapture](https://user-images.githubusercontent.com/8841727/52480389-92a5a800-2bd1-11e9-8404-471993921bb4.PNG)

See, QOwnNotes does something similar.

**Comment by nathanlesage** [comment]
Ah, yeah, QOwnNotes is showing you a simple Markdown-preview on the right side.

Basically, there are three types of Markdown editors around: The first are those that simply show you only the hard markdown syntax with no sugar whatsoever (e.g., vim, or Atom).

Then there are those that let you view both your source code and a pre-rendered version (such as QOwnNotes). The problem with these is that you always have two different windows open, which at least I personally dislike.

The third variant are those editors, such as Typora, Ulysses or Zettlr that try to combine both ideas into one window, so basically they're returning some way to the standard Word Processors such as Word or OpenOffice.

For some time now I've thought about finally taking the plunge and pre-rendering every single element in the editor just as Typora does, but I'm still hesitant because I don't want to purport the amount of alienation this approach entangles.

I see what you mean, now, but I'm not sure that I should do this. After all, you can simply use the numbers as you want them manually. Also, the heading-layers work "in-place", that means the script counts the amount of hashes and replaces them with a span containing the number. To apply such a prerendering layer to lists would require to constantly scan the whole document according to Markdown specifications for where lists are etc, which is quite difficult. Plus above mentioned reasons.

**Comment by subi54** [comment]
Alright. Thank you for the explanation.

I could number them but every time I've to add a new one in the middle, I'll have to renumber them manually. In a list with 100+ bullet points, that'd be a massive waste of time.

**Comment by nathanlesage** [comment]
Yeah that's right! I'll see to it, but it doesn't have such a high priority!

**Comment by subi54** [comment]
Thank you, much appreciated.

**Comment by nathanlesage** [comment]
Heya, due to the long list of issues and some other stuff that's going on, I decided that I'll definitely leave closing this issue to the maintainer of the continuelist-plugin to leverage workload. So please also get in touch with him for this issue (after all it's in his realm)!
