### ISSUE TITLE
[FEATURE] Add support for AsciiMath

### ISSUE THREAD

**Issue by slevey087** [Zettlr/Zettlr#965]
## Description
AsciiMath (http://asciimath.org/) is a markup language for writing mathematics that is FAR, FAR simpler than LaTeX. Whereas LaTeX makes me want to scream with pain, AsciiMath is a delight to use.

Ideally, Zettlr would support it natively, meaning inline rendering and pdf rendering. There are already parsers/filters/plugins to convert AsciiMath to HTML, to LaTeX/KaTeX (https://www.intmath.com/help/asciimath-input-latex-katex-output.php and https://github.com/judah/asciimath-tex]) and for pandoc (https://github.com/vbwx/pandoc-asciimath).

## Example Workflow
Inside the normal KaTeX math delimiters, eg. $ and $$, add another delimiter to distinguish this as an AsciiMath block, such as `?` or backticks. Eg.:

```
$` sum_(i=1)^n i^3=((n(n+1))/2)^2 `$
```

**Comment by nathanlesage** [comment]
> LaTeX makes me want to scream with pain

Welcome to the pack, buddy :D 

> pdf rendering

This would be something users would need to install manually (maybe we could add a simpler setting for adding filters, but that would be a different issue for later)

> inline rendering

Does there happen to be a lightweight (!) JS library for this? (I'm too lazy to google now, but it doesn't have a deadline!)

> Inside the normal KaTeX math delimiters, eg. $ and $$, add another delimiter to distinguish this as an AsciiMath block

Are there any "best practices"? What does the Pandoc filter do?

**Comment by slevey087** [comment]
> > inline rendering
> 
> Does there happen to be a lightweight (!) JS library for this? (I'm too lazy to google now, but it doesn't have a deadline!)

[This library](https://github.com/christianp/asciimath2tex) converts AsciiMath to standard LaTeX, which could then be rendered the way Zettlr already renders LaTeX.

> > Inside the normal KaTeX math delimiters, eg. $ and $$, add another delimiter to distinguish this as an AsciiMath block
> 
> Are there any "best practices"? What does the Pandoc filter do?

I don't think there are best practices here because AsciiMath is relatively new and not widely used (yet!?). But I've used AsciiMath inside LaTeX in two different forms. One method (from a [LaTeX package](https://github.com/judah/asciimath-tex)) uses backticks (`) to enclose/bracket AsciiMath from standard LaTeX. The other method (from the [pandoc filter](https://github.com/vbwx/pandoc-asciimath)) uses a question mark to indicate that a particular block was AsciiMath rather than LaTeX.

My personal preference was for the enclosing backticks, because then you could switch back and forth between AsciiMath and LaTeX inside the same math block, whereas with the single question mark your $$ block was either entirely AsciiMath or none at all.

**Comment by nathanlesage** [comment]
> But I've used AsciiMath inside LaTeX in two different forms. One method (from a LaTeX package) uses backticks (`) to enclose/bracket AsciiMath from standard LaTeX. The other method (from the pandoc filter) uses a question mark to indicate that a particular block was AsciiMath rather than LaTeX.

We need to sort that out, depending on who uses this and how, in order to enable support for this. So everyone who wants this, might want to comment here. Maybe even suggest opening a thread on the [forum](https://forum.zettlr.com/).

**Comment by amatsukawa** [comment]
+1 I want this. I am actually discovering this for the first time in this ticket, but this looks awesome!

If we could toggle back and forth between latex and asciimath, that would be amazing. eg:
```
$$
\begin{aligned}
`sum_(i=1)^n i^3` 
    &= `((n(n+1))/2)^2` \\
    &= `((n(n+1)))^2/2^2`
\end{aligned}
$$
```

**Comment by amatsukawa** [comment]
Javascript is really not my thing so I have no idea if I did things "correctly" but I looked up where math rendering was happening in the editor and added a small logic to trigger the library @slevey087 linked before calling to katex: https://github.com/amatsukawa/Zettlr/commit/238a139874978cf5d5469153936e3a23ad7ba876.

This works, my above snippet:
```
$$
\begin{aligned}
`sum_(i=1)^n i^3` 
    &= `((n(n+1))/2)^2` \\
    &= `((n(n+1)))^2/2^2`
\end{aligned}
$$
```
Gets rendered as expected:
<img width="225" alt="Screen Shot 2020-07-14 at 11 12 33 PM" src="https://user-images.githubusercontent.com/463809/87499375-22058500-c628-11ea-881a-681158da7b84.png">

It doesn't interfere anywhere else (eg. code block backticks) because I'm only doing this inside of math blocks. This isn't the full solution, because this is only rendering -- a similar preprocessing needs to happen before pandoc. But it seems like doing a similar thing should be possible (having read 0.5% of the code 🤣) before exporting to pandoc also.

**Comment by nathanlesage** [comment]
@amatsukawa Looks cool! In general, for Zettlr to render stuff there are two things that need to happen:

1. Pandoc needs to be able to do so, which mostly requires an additional filter (`pandoc-citeproc` being the most prominent, as citations are one of the core features)
2. Then, additionally, Zettlr needs to mirror that behavior for pre-rendering, because rendering ≠ final exported output by Pandoc. This is mostly done using CodeMirror plugins.

So before I let something implement, I want to be sure that the rendering feature is also supported by Pandoc. This is because of usability-issues: If something can be rendered using Zettlr, but there is no way it can actually be exported, this will be frustrating for users, as it is not always completely transparent to them why that happens. One prime example is the mermaid-support, a decision I regret up to this date … even though there is a Pandoc-plugin for it …

**Comment by amatsukawa** [comment]
I got pandoc to work also. With this filter, https://github.com/amatsukawa/Zettlr/commit/9798d987f3d9c2f5606ea856aace52ac534ef2a1

This `test.md` file:
```
# Heading

Test test
$$
\begin{aligned}
`sum_(i=1)^n i^3`
    &= `((n(n+1))/2)^2` \\
    &= `((n(n+1)))^2/2^2`
\end{aligned}
$$
```

Becomes this pdf:
```
pandoc -t latex --filter ~/src/Zettlr/source/main/modules/export/asciimath-filter.js test.md -o test.pdf
```
![Screen Shot 2020-07-15 at 8 41 38 AM](https://user-images.githubusercontent.com/463809/87546271-450b5580-c677-11ea-9160-5aef7e480416.png)

**Comment by slevey087** [comment]
Besides just dedicated math blocks ($$), does this work for inline math expressions (appearing with a single $ sign in the middle of normal text) as well?

**Comment by amatsukawa** [comment]
Yup. The filter matches both `DisplayMath` and `InlineMath` (the renderer matches both with regexes and handles them in the same code path too, iirc.

```
# Heading

Test testing some inline math: $`x !in X`$.
$$
\begin{aligned}
`sum_(i=1)^n i^3`
    &= `((n(n+1))/2)^2` \\
    &= `((n(n+1)))^2/2^2`
\end{aligned}
$$
```

![Screen Shot 2020-07-16 at 9 48 53 AM](https://user-images.githubusercontent.com/463809/87678943-9126ca80-c749-11ea-9ae3-2546e7b94b41.png)

Sorry to do a hit and run, but I was evaluating Zettlr and Obsidian, and for now I've decided to go with Obsidian for various details that I think Zettlr does not support by design (eg. live previews, showing linked, non-existing pages in the autocomplete which would require the use of a database, etc).

So I don't think I'll be able to send this PR after all. However, I'll leave my work so far up on my github (links are above) so if there is interest, someone else can go ahead and integrate it :)
