### ISSUE TITLE
[ENHANCEMENT] Making custom fonts/CSS easier to apply

### ISSUE THREAD

**Issue by nyanpasu64** [Zettlr/Zettlr#982]
## Description

Zettlr should make it easier for users to create their own CSS customizations. Ideally it would be as simple as the Stylus browser extension.

## Proposed Changes

I just downloaded Zettlr to see how it worked, and compare it against Typora (another WYSIWYG Markdown editor). I didn't like the initial appearance, but found several roadblocks to customizing the styles.

- Preferences, Theme tab lets you pick a theme, but doesn't let you customize the available themes. It should point you towards Custom CSS in the File menu.
- Custom CSS dialog should have an "apply" option or live CSS preview, so I can edit CSS while observing the effect.
- Even better, it would be a separate non-modal window so I can interact with the program while editing CSS.
- Custom CSS is undocumented, and I don't know what classes I can restyle. It should point you towards help at https://docs.zettlr.com/en/core/custom-css/#custom-css.
    - These docs are quite incomplete. It explains how all rules are rooted at body/body.dark. and supplies a list of all classes, but does not specify what rules exist, or what hierarchy the elements form. I don't know how to look in the source of the app, nor how to rebuild the program from scratch to customize the UI styles.
    - There is a large "grab bag" of pre-written GUI tweaks. Maybe these could be program options instead, I'm not sure.
    - Without F12, I don't know what elements I can style, how they're arranged in a tree, or what existing rules exist.
- https://docs.zettlr.com/en/core/custom-css/#custom-css should explain how to open developer tools.
    - Currently, that link doesn't mention developer tools at all. I had to search to find a different doc page, https://docs.zettlr.com/en/get-involved/#devtools-development-tools, which mentions you need to enable "debug-mode". I searched the docs, but couldn't find how to enable debug mode. I eventually discovered it's via Preferences, Advanced tab (where it's called "debug mode" without a hyphen).
- (feature request) Add entries in the preferences dialog, for the user to pick a font, font size (allow user to enter any decimal pt, since there are more valid px sizes than pt sizes), and font weight.
    - I find the default font size too big, and the bundled Lato font too thin.

Feedback from actually customizing fonts:

- Does Less inline all variables (like `@font-code`) into the CSS? Is there a way to reconfigure Less variables using the Custom CSS feature? If not, is it better to use CSS variables instead of Less variables?
- By default, the program uses Lato Light and Liberation Mono as "network resources". Are these bundled with the program?

**Comment by nathanlesage** [comment]
That is quite a bit.

So, as for custom CSS, it is being regarded as an advanced feature. Yes, there could be better support, but this also opens the gate to a lot of feature requests for "Can we please customize XYZ" which will not be handleable at all.

I totally get that the CustomCSS feature can get some improvements, but the issues you outlined do partially belong to the documentation repository.

One major reason the documentation on CustomCSS is outdated is that I haven't been able to refactor the LESS source in quite some time, hence class names change a lot, hence I don't have the incentive to keep the documentation updated. This is clearly something this needs to happen, and I am quite happy with a few things you mention, but I'd like you to open the documentation-specific issues on the docs-repository, so that we can focus on the programming/implementing stuff here! Docs repository: https://github.com/Zettlr/zettlr-docs

Nevertheless, pointing people towards the CustomCSS is a good idea that we might implement!

**Comment by nathanlesage** [comment]
I have just updated the docs for this, but in short:

> Does Less inline all variables (like @font-code) into the CSS? Is there a way to reconfigure Less variables using the Custom CSS feature? If not, is it better to use CSS variables instead of Less variables?

Yes. No. Yes.

The whole CSS needs to be refactored, and until that happens it will be difficult to make it easier. Apart from that, custom CSS is a feature for advanced users, and it has proven pretty awesome to have some users publish their custom CSS for others to use on the forum. So the ROI for adding more functionality as of now is low. But I would welcome a PR with a refactored LESS stylesheet, where the hierarchies are cleaned up and additional useful inline LESS variables are made available as CSS root variables too.
