### ISSUE TITLE
[FEATURE] Command Palette

### ISSUE THREAD

**Issue by onemenzel** [Zettlr/Zettlr#985]
## Description

One thing that I appreciate very much about Editors like Visual Studio Code or Sublime Text ist their command pallette. You press a shortcut (usually `Cmd/Ctrl+Shift+P`) and you get _every_ action that you can perform from within the GUI or through shortcuts, together with a fuzzy search bar. This is really helpful for discovering features, learning Shortcuts (those get displayed there, too) or not having to search through multiple menus to get to a feature of which you may already know the name. I'd like to see that in each and every software I use.

## Example Workflow

- A user wants to do something that they would normally achieve by clicking through menus or knowing a shortcut
  - e/g switching to dark mode, import a file or change the Custom CSS
- the user presses the shortcut to open the command palette (could be `Ctrl/Cmd+Shift+P` for consistency with other software)
- command palette (containing every action in Zettlr) opens
- the user types what they want to do, maybe even making small spelling errors or typing only beginning letters
  - to do the "beginning letters" trick, one would type e/g "cucs" for "Custom CSS"
- the user gets a list of actions matching their query

## Caveats

As this feature would have to be sprinkled across the while app, I guess it would be a bit of work to implement it. Though I'd reason that formatting options do not have to be integrated in the command palette – eliminating the need of messing with CodeMirror – there would still be a lot of changes to make, since every other feature is affected by this. Also, for all future features, developers would have to remember to integrate their feature into the command palette.

I would however consider the benefits in terms of efficiency brought to the user being high enough to justify that.

**Comment by nathanlesage** [comment]
Mh. I am not sure this is in the scope of Zettlr. Our main aim is to provide an editor that can challenge Word's monopoly on the computers of researchers in the arts and humanities, and a command palette may be something too far off. This would be feature blow.

Why?

First of all, I don't think that there are that many commands you can use. In VSCode the main benefit of the command palette is to provide an easy way for plugins to register text changing functionality, and in the realm of code this is surely beneficial, because you'll always run into the problem of wanting to beautify your file, lint it, run it in a browser, etc. pp.

But with Zettlr being a basic text editor, I can promise you there won't be that many commands to choose from (you wouldn't want Copy and Paste to end up there). It is strongly GUI-driven, because it attempts to bridge the gap between these horrific clicky-clicky-apps like Word, and a more keyboard-focused shortcut-world.

A command palette won't be used by many and is super difficult to maintain. I'd rather focus on making the global search fuzzy and performing some more clever magic that is more fit to the use-case of Zettlr. This clearly promises a greater yield than adding a command palette, which, as I outlined, is super helpful for code editors, but Zettlr is not a code editor.

However, as always, if there are enough voices opting in favor of this feature, feel free to discuss this over on the forum first, and I may reconsider!

**Comment by r-darwish** [comment]
Hi @nathanlesage. I wanted to make a similar request so I search "palette" and got here. In addition to the command palette, these editor usually have file navigation based on the same control as the command palette (Usually when pressing `Ctrl+P`)

While Zettlr doesn't have many commands, users usually have many files in their nodes directory, so I think a "File Palette" would be useful.

**Comment by ditsuke** [comment]
New to Zettlr and felt this'd be nice to have! I find command palettes particularly useful for navigation and switching through preferences. An example to look at would be the [Mark Text](https://marktext.app/) markdown editor. I feel much more attuned to the design and feel of Zettlr but I do miss the palette now becoming ubiquitous in many of the applications I use, including now [Github](https://docs.github.com/en/get-started/using-github/github-command-palette)!
