### ISSUE TITLE
[ENHANCEMENT] Too many dependencies

### ISSUE THREAD

**Issue by noonien** [Zettlr/Zettlr#991]
## Description
Currently, Zettlr has [954 dependencies in yarn.lock](https://github.com/Zettlr/Zettlr/network/dependencies).
I'm not sure if there is a process in place to review dependencies when they are added, and updated.

## Proposed Changes
I'm not sure what can be done, 954 is a lot of dependencies to have, and review, most are probably transitive.

## Caveats
Not reviewing dependencies can severely affect Zettlr's security.
What assurances are provided that updating/installing the program does not also install malware? This has happened several times in the past, with small and big projects, so it's a legitimate concern.

**Comment by nathanlesage** [comment]
Yeah, most of the dependencies are transitive, and most are due to the mermaid dependency, I am not very fond of this myself (especially because there are like 4 packages with the exact same one-liner-function in the dependencies).

I hate pieces of dependencies like that:

![image](https://user-images.githubusercontent.com/17251683/86511100-10d1a280-bdf6-11ea-80ae-72a2eb9d3b4f.png)

But for now I'm unsure as to how to handle this. I can't really go through all the dependencies' repositories and ask them to reduce their own dependencies, but if you have a better idea, feel free. However, please note that there's already [someone trying to tackle this problem](https://github.com/Zettlr/Zettlr/pull/938), so maybe it would be a good idea to team up with them!

After all, I think there's only that much we can do, because the whole dependency hell is a large problem of the `npm`-community at large, and unless the mindset changes, there's not much we can actually do, I'm afraid.

***

As for security concerns and unused dependencies: As soon as I get a security alert from GitHub, I'll immediately update the dependency to a secure one, and publish a patch version asap, so I'm well aware of the security concerns. And with regard to packages: I am pretty sure I always remove all dependencies I no longer use, albeit I may have overlooked one or two.

**Comment by tobiasdiez** [comment]
I agree with @nathanlesage. At the moment there is not really something we can do here as all dependencies are needed (maybe except one or two that were overlooked). I'll thus close this is now. Feel free to open it if you find a specific dependency that is no longer required.
